### ISSUE TITLE
Inconsistence row and or column of response data

### ISSUE THREAD

**Issue by kadalcj** [mscdex/ssh2#1000]
Hi, I basically do ssh to list of device, run some script, and parse response data and convert it to csv. Every time I run the ssh, it gave me inconsistence response even after I add `stream.setWindow(0, 0, 0, 0)`. 

What I mean is something like this:
```
(...)

  '    RTT Values:',
  '      RTTAvg  : 2          RTTMin: 1          RTTMax : 4         ',
  '      NumOfRTT: 10         RTTSum: 22         RTTSum2: 54',
  '    Packet Loss Values:',
  '      PacketCount  : 10         PacketLoss      : 0         ',
  '      OutOfSequence: 0          DiscardedSamples: 0         ',
  '      VerifyErrors : 0          DroppedErrors   : 0         ',

(...)
```
And sometime gave response like this:
```
(...)

  '    RTT Values:',
  '      RTTAvg  : 2          RTTMin: 1          RTTMax : 4         ',
  '      NumOfRTT: 10         RTTSum: 22         RTTSum2:',
  ' 54',
  '    Packet Loss Values:',
  '      PacketCount  : 10         PacketLoss      : 0         ',
  '      OutOfSequence: 0          DiscardedSamples: 0         ',
  '      VerifyErrors : 0          DroppedErrors   : 0         ',

(...)
```
***It was occurred in random line**

Is it possible to make it consistence? Thank you

**Comment by mscdex** [comment]
You can specify the pty dimensions and other pty properties for either `shell()` or `exec()`. My guess is you will need to set the dimensions to something large enough for your needs.
