### ISSUE TITLE
Does anyone know how to connect to the bastion machine

### ISSUE THREAD

**Issue by Lee-42** [mscdex/ssh2#1002]

**Comment by mscdex** [comment]
Can you elaborate?

**Comment by Lee-42** [comment]
In our company, multiple business servers are connected through a jumper. When you want to access a business server, you need to connect the jumper first. I only know that when I try to directly connect to the business server, the SSH2 module will return some error messages, but I have no idea to proceed with the next operation. Maybe the implementation of this function has nothing to do with the SSH2 module. If this question is temporarily no one can help. I will close this issues

**Comment by mscdex** [comment]
Perhaps [this example](https://github.com/mscdex/ssh2#connection-hopping) will be of use.
