### ISSUE TITLE
List of supported kex, cipher, serverHostKey and hmac in v0.5.5

### ISSUE THREAD

**Issue by smanish01** [mscdex/ssh2#1003]
Hi,

We are using the ssh2 v0.5.5. We need to know the list of supported kex, cipher, serverHostKey and hmac in the specific version 0.5.5. We had gone through the README file of the v0.5.5, but didn't get the required information. In the latest version we are able to get the default as well as supported details, but we need the same details regarding the v0.5.5.

Can someone please provide us the required list of default as well as supported kex, cipher, serverHostKey and hmac in v0.5.5?

Thanks.

**Comment by mscdex** [comment]
The information would've been in the `ssh2-streams` dependency documentation. Pre-v1.0.0 releases of `ssh2` are no longer supported.
