### ISSUE TITLE
Abort createWriteStream options autoClose.

### ISSUE THREAD

**Issue by sdir** [mscdex/ssh2#1007]
https://github.com/mscdex/ssh2/blob/f13a09644307095fa7f1d3a1e56d0ab7ed55c863/lib/protocol/SFTP.js#L3400

This stream.Writable autoDestroy defined as true by default in nodejs v14. Need set options.autoDestroy false  when options  autoClose is false before  WritableStream call.

**Comment by mscdex** [comment]
This should've been fixed in c0de05d186065ad4081b98d2f7aa0fe22161ec09.
