### ISSUE TITLE
What do you mean by host.key?

### ISSUE THREAD

**Issue by JamieGrimwood** [mscdex/ssh2#1008]
I am just testing with this module and I want to create a simple ssh server however I do not know what you mean in your example to "Create a server host key". I have looked it up with no success. Do you mean a public and private key? I have set my public key to foo.pub and my private one to host.key but when connecting with the key termius says "No error" with failed to connect.

Help appreciated! :)

**Comment by mscdex** [comment]
A server needs a valid private key. The public key can be automatically derived from the private key, so you don't need that.
