### ISSUE TITLE
Wireshark reports malformed packet with using ssh2 as a client

### ISSUE THREAD

**Issue by billchurch** [mscdex/ssh2#1011]
- mscdex/ssh2 v0.8.9
- node v14.17.0
- client (node host) macOS 10.15.7 (19H1030) OpenSSH_8.1p1, LibreSSL 2.7.3
- server (Ubuntu 14.04.5 LTS x86_64) OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10, OpenSSL 1.0.1f 
- wireshark Version 3.4.5 (v3.4.5-0-g7db1feb42ce9) AND Version 3.0.2 (v3.0.2-0-g621ed351d5c9)

When using ssh2 as a client, wireshark reports malformed packets after key exchange complete in the first encrypted data packet. In the example [malformed_packets.pcapng](https://github.com/billchurch/ssh2-test/blob/main/malformed_packets.pcapng) line 19 shows the example.
![image](https://user-images.githubusercontent.com/1668075/119132405-a541f500-ba08-11eb-87a0-21838b8a9ff1.png)

And example of the same session using the macOS client (OpenSSH_8.1p1, LibreSSL 2.7.3) and executing the same command does NOT result in these malformed packets (again line 19 in [normal_packets.pcapng] (https://github.com/billchurch/ssh2-test/blob/main/normal_packets.pcapng)
![image](https://user-images.githubusercontent.com/1668075/119132357-98250600-ba08-11eb-9a92-422780fe0cc8.png)

In both cases, the wireshark element is running on the macOS client/node server and the Ubuntu server is running on a seperate VM host outside of this environment.

User of my WebSSH2 package [reported an issue](https://github.com/billchurch/webssh2/issues/250). 

I was able to reproduce this with one of the samples provided by this repo and replicated my findings here: https://github.com/billchurch/ssh2-test

sample code:
```
var Client = require('ssh2').Client;
 
var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('uptime', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: '192.168.99.81',
  port: 22,
  username: 'testuser',
  password: 'youwish'
});
```

**Comment by mscdex** [comment]
There is no problem with `ssh2`. The wireshark dissector just makes some bad assumptions. In this particular case it's assuming the entirety of an SSH identification exists in a single chunk, that's why you don't see the client identification ever get decoded (it just shows up as plain TCP data). The fix for the dissector would be to buffer (since TCP is a stream) until the terminating CR-LF is seen.
