### ISSUE TITLE
Possible `ssh2Stream._channels[chan]` leak (v0.8.9)

### ISSUE THREAD

**Issue by Luluno01** [mscdex/ssh2#1012]
I am forwarding out TCP connections from remote system to local system. A few hundreds of connections were established and ended (the `end` event emitted). However, the `._channels` also had hundreds of properties with numerical keys and `true` as their values. It looks something like

```
Client {
  ...
  _channels: {
    '0': [Function (anonymous)],
    '1': [Function (anonymous)],
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': true,
    '8': true,
    '9': true,
    '10': true,
    ...
    '478': true
  },
  ...
}
```

After searching for all accesses to `_channels` in the code and some inspection, I found it could be a leak. Here are the related code snippets for your easy reference.

Assignment to `_channels[*]`:

https://github.com/mscdex/ssh2/blob/v0.8.x/lib/client.js#L1508

Deletion of `_channels[*]`:

https://github.com/mscdex/ssh2/blob/v0.8.x/lib/client.js#L1199

Call chain of deletion:

https://github.com/mscdex/ssh2/blob/v0.8.x/lib/client.js#L338

https://github.com/mscdex/ssh2/blob/v0.8.x/lib/client.js#L1156

It seems these properties will be removed only when the underlying SSH connection is closed:

https://github.com/mscdex/ssh2/blob/v0.8.x/lib/client.js#L313-L338

**This will eventually exhaust the memory because in my case the port forwarding is intended to be persistent.**

**Comment by mscdex** [comment]
The reserved channel numbers are deleted [when the channels themselves are closed](https://github.com/mscdex/ssh2/blob/v0.8.x/lib/Channel.js#L107).

Judging by the (large number of) `true` `_channels` values you're seeing, it appears either `accept()` or `reject()` are not being called for those incoming forward requests.

**Comment by mscdex** [comment]
Actually, upon further review, I think I may see what's happening here.....

**Comment by mscdex** [comment]
Thanks for the report!

**Comment by Luluno01** [comment]
Thank you for your attention! So the fix is only available in the latest unreleased version? Is it recommended to update to the latest version and how to migrate to the latest version? If not, when can I safely delete those leaked channels (as a workaround at the moment)?

**Comment by mscdex** [comment]
It will be included in the upcoming v1.0.0 release. I will probably do that release in the next couple of days or so.

**Comment by mscdex** [comment]
Regarding changes between v0.8.x and what will be v1.0.0, you can find most of them here: https://github.com/mscdex/ssh2/issues/935

**Comment by Luluno01** [comment]
Sounds great! Thanks!
