### ISSUE TITLE
Do not wait until Comand has finished running.

### ISSUE THREAD

**Issue by sb2050** [mscdex/ssh2#1017]
Good day,
I noticed that I get a result from `.on('data', (data) => {}` before the command is finished.
I need the result only after the command is fully executed.
Does anyone have any idea what could be the reason for this?
I have already tried a few things....:

```
const sshClient = require('ssh2').Client;

module.exports = {
    exec: (command, connectionData) => new Promise((resolve, reject) => {
        let ssh = new sshClient();

        ssh.on('ready', async () => {
            ssh.exec(command, (err, stream) => {
                if (err) {
                    resolve([false, err]);
                }
                stream.on('close', (code, signal) => {
                    if(code !== 0){
                        resolve([false, `${code} ${signal}`]);
                    }
                    ssh.end();
                }).on('data', (data) => {
                    resolve([true, `${data}`]);
                }).stderr.on('data', (err) => {
                    resolve([false, `${err}`]);
                });
            });
        }).on('error', (err) => {
            resolve([false, err]);
        }).connect(connectionData);
    }),
};
```

**Comment by mscdex** [comment]
Never make any assumptions about the number of `'data'` events you receive (this is general advice for node streams). If you need to, just buffer the stdout and stderr data until you see `'close'`, then resolve your promise as you see fit.

**Comment by sb2050** [comment]
Thank you. I got it to work.

**Comment by Mdhaker** [comment]
@sb2050 can you share your solution ? I'm facing the same problem but I'm not using promise like you because I have to run command in a loop based in some conditions, I can use your solution to update my code. thanks
