### ISSUE TITLE
SFTP Server KEX algorithm issues from 0.8.9 to 1.1.0

### ISSUE THREAD

**Issue by SamDuvall** [mscdex/ssh2#1025]
I'm currently using `ssh2` to stand up an SFTP Server (thank you for making that possible). I upgraded `ssh2` from 0.8.9 to 1.1.0 and I'm having issues with some (not all) clients being able to connect to the SFTP server now.

I'm seeing fatal errors at the following locations. 
https://github.com/mscdex/ssh2/blob/master/lib/protocol/kex.js#L1402
https://github.com/mscdex/ssh2/blob/master/lib/protocol/kex.js#L239

Did the upgrade to 1.x drop support for the group exchange KEX methods? Do you have any guidance on what KEX methods I should be using for an SFTP Server?

**Comment by mscdex** [comment]
group-exchange was never supported for `ssh2` server implementations. It should still be supported for client implementations though. However, only the sha256 variant is used in the default kex algorithm list. The option to re-enable the sha1 variant is there if you need to support older clients.

**Comment by SamDuvall** [comment]
Gotcha. Thank you for the quick response. I'm guessing, but don't know for sure, that my clients are choosing an sha1 variant before getting to the group-exchange variants in 0.8.x, but I hadn't come across the group-exchange error in 0.8.x.

**Comment by mscdex** [comment]
In general, the `-sha1` kex algorithms were removed from the default list in `ssh2` v1.0.0. The last version of `ssh2-streams` (which `ssh2` v0.8.9 uses) removed all but one (`diffie-hellman-group14-sha1`) of the `-sha1` kex algorithms by default.

Either way, you can compare the debug output of both versions when connecting to the same server to see what is being offered by both sides and which algorithms were selected during the handshake. (In v1.0.0+ you can get at the handshake parameters programmatically, but not in earlier versions so it will be easier to just compare the debug output)

**Comment by mscdex** [comment]
Just a note about the default algorithms in `ssh2`: I generally try to align with OpenSSH's defaults as much as possible.

**Comment by jscottsf** [comment]
@mscdex I know this is closed, but may be experience a similar issue. We're forced to connect to a older SFTP server running OpenSSH 4.1 and I'm getting the error:

```
Error: Unsupported algorithm: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
```

I explicitly added thtese algos to the `kex` config based on what the server offered. But no go. Running Node 14.17.

Any thoughts greatly appreciated.
