### ISSUE TITLE
Bump npm version with new windows binding.cc

### ISSUE THREAD

**Issue by dylanharty** [mscdex/ssh2#1026]
###  Can't resolve './crypto/build/Release/sshcrypto.node' 
As noted in your last commit on ssh2\lib\protocol\crypto\src\binding.cc Windows will not compile the binding.cc without the newest commit. This breaks ssh2 on Windows. You need to download a copy of the newest binding.cc to compile sshcrypto.node

```
Module not found: Error: Can't resolve './crypto/build/Release/sshcrypto.node' in '...\node_modules\ssh2\lib\protocol'
 @ ./node_modules/ssh2/lib/client.js 34:29-60
 @ ./node_modules/ssh2/lib/index.js 27:10-32
 @ ./src/index.ts 2:19-34

```

If you download the newest copy of binding.cc and override the existing in ssh2\lib\protocol\crypto\src and run `node .\install.js` in the node_modules\ssh2\ folder this issue is resolved.

**Comment by mscdex** [comment]
v1.2.0 is now released.
