### ISSUE TITLE
Add proxy-procotol support

### ISSUE THREAD

**Issue by 131** [mscdex/ssh2#1027]
I want to use ssh2 server behind haproxy, but i do not want to loose remoteAddr info.

Using haproxy proxy-protocol seems to be the right way to do it.

Proxy-protocol is a fixed length simple header in a tcp stream [see specs](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). Decoding the proxy-procol [is trivial](https://github.com/balena-io-modules/proxy-protocol-parser/blob/master/lib/v2_decode.js), but this need to be done in ssh2 directly and cannot be done outside of this module (as ssh2 is creating the listening socket)

If you are OK with this, I'll push a simple PR with proxy-procotol v2 header decoding in ssh2@1 server signature

```
const {Server} =  require('ssh2');
new Server({
  hostKeys: [readFileSync('host.key')]
  proxyProcol : true
}, (client) =>  ...
);
```

**Comment by mscdex** [comment]
I think I'd rather have a nice, neat way of creating a server that accepts (duplex) streams instead of listening on a socket. I'm not sure offhand if that will break any existing server functionality though (I'm thinking not).

**Comment by 131** [comment]
I've pushed a naive implementation, please tell me whether or not it fits you
