### ISSUE TITLE
password authentication retry count

### ISSUE THREAD

**Issue by killjoy2013** [mscdex/ssh2#1035]
Is it possible to cancel, or at least limit password retry? Currently, it retries many times and only after that, an error happens. This takes unnecessary long time.

Regards

**Comment by mscdex** [comment]
This library does not retry password authentication unless you configure it to do so (e.g. by setting the `authHandler` config option appropriately).

**Comment by killjoy2013** [comment]
Hey @mscdex , below is my connect part. Any suggestion on it?

```
 .connect({
        host: this.ip,
        port: 22,
        username: process.env.READUSERNAME,
        password: process.env.READPASSWORD,
        authHandler: function (methodsLeft, partialSuccess, callback) {
          callback({
            type: 'password',
            username: process.env.READUSERNAME,
            password: process.env.READPASSWORD,
          });
        },
        readyTimeout: 99999,
        keepaliveInterval: 120000,
        keepaliveCountMax: 10,
        debug: process.env.NODE_DEBUG ? console.log : undefined,
        algorithms: {
          kex: [          
            'diffie-hellman-group1-sha1',
          ],
          cipher: [
            'aes128-ctr',
            'aes192-ctr',
            'aes256-ctr',
            'aes128-gcm',
            'aes128-gcm@openssh.com',
            'aes256-gcm',
            'aes256-gcm@openssh.com',
            'aes256-cbc',
          ],
          hmac: ['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'],
          compress: ['none'],
        },
      });
```

**Comment by mscdex** [comment]
Is there a reason why you are using `authHandler` if you're just using a username and password that are already known upfront? `authHandler` is only really useful if you need more control over the authentication process (e.g. custom authentication method order or asynchronous authentication handling). You should be able to get by by just removing `authHandler` and keeping your `username` and `password` in your connection config.

**Comment by killjoy2013** [comment]
I removed the authHandler. When I supply wrong password, I immediately receve `All configured authentication methods failed` 
without retry now.

Thanks you @mscdex
