### ISSUE TITLE
unhandledRejection handler crashes applications that import ssh2

### ISSUE THREAD

**Issue by kklin** [mscdex/ssh2#1042]
We recently upgraded our `ssh2` version from `0.1.7` to `1.0.0`, and noticed that that our entire Node process would randomly crash.

We've traced this down to some unhandled promise rejections in our codebase, which get caught by `ssh2`'s handler [here](https://github.com/mscdex/ssh2/blob/master/lib/protocol/crypto/poly1305.js)
```
process.on("unhandledRejection",J)

function J(a){if(b.onAbort)b.onAbort(a);L(a);O=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");
```

These unhandled rejections are completely unrelated to ssh2, so they ssh2 shouldn't be unilaterally crashing our entire process.

What is the `ssh2`'s handler for? Could it just be removed?

**Comment by mscdex** [comment]
I don't know offhand, that's emscripten's doing. My guess is there's a reason it's there, so I'm not sure if flat out removing it will cause issues or not.

**Comment by mscdex** [comment]
Ah ok I see they added separate flag for removing the `'unhandledRejection'` handler. Should be fixed now in 2480ed9dad7d7de1d72ff0d3bd66b0ac950eda8f. Let me know how that works for you.

**Comment by kklin** [comment]
@mscdex that worked, thanks! Are you planning to make a npm release soon?

**Comment by mscdex** [comment]
Probably this weekend.

**Comment by Lianecx** [comment]
Same problem here, npm already out?
