### ISSUE TITLE
Clarification on the SFTP Packet Type Used in  end() method

### ISSUE THREAD

**Issue by madushankaf** [mscdex/ssh2#1047]
Hi @mscdex 

Could you kindly let me know for the SFTP end() method, what is the SFTP packet type being issued?  I believe what has been used is below as per code analysis. 

SSH_FXP_CLOSE               4
ref: https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13#section-4.3

Could you kindly confirm it? 

Thanks in advance !

**Comment by mscdex** [comment]
FWIW this is the correct RFC to follow for what `ssh2` (and OpenSSH) implements: https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02

There is no SFTP packet type for closing an SFTP connection, you just close the underlying SSH channel.
