### ISSUE TITLE
connect to an existing interactive session [question]

### ISSUE THREAD

**Issue by DeanKamali** [mscdex/ssh2#1049]
Is it possible to connect to an already established / interactive shell session? I have a use case where `Server A` connects to `Server B` and would like to have the `client` connect to that already established connection?

```
1. [Server A] ---> [Server B] // interactive shell 

2. [client] ----> [Server A] ---> [ tap into interactive shell establied to Server B ]
```

**Comment by mscdex** [comment]
That's outside the scope of this module. You will need to come up with something to accomplish that. It sounds like what  you want would already be served best by programs like screen or tmux though.
