### ISSUE TITLE
channel.incoming is undefined in onCHANNEL_CLOSE

### ISSUE THREAD

**Issue by nicferrier** [mscdex/ssh2#1050]
Version 1.2.0
I can't cut and paste the error because it's in a closed environment.

utils.js/onCHANNEL_CLOSE is being called with the channel where channel.incoming is not set but is being checked.

Not sure precisely why... I am being hit by ssh orchestrated by an enterprise security product so there may be non-conformance to spec... but onCHANNEL_CLOSE doesn't seem very well protected against various failures.

**Comment by mscdex** [comment]
Can you give details on how to reproduce this situation? Are you implementing an `ssh2` server or using the `ssh2` client?

**Comment by ms270169** [comment]
I think this problem pops up when the connection is closed before a channel was created or used.
I get this error when:
1) server: new ssh2.Server(...)
2) client: sshClient = new ssh2.Client(...)
3) server: connection handler callback is called, 'ready' 'authenticate' ... callbacks defined
4) server: on authenticate callback called ... -> passed
5) client: sshClient.end()

Now an internal error happens:
``
Uncaught Exception:
TypeError: cannot read property state of 'undefined'
``
