### ISSUE TITLE
X11 forwarding connection refused to localhost:6000 ?

### ISSUE THREAD

**Issue by jeremyfix** [mscdex/ssh2#1053]
Hello, 

I'm on a Ubuntu 20.04 client, the remote to which I try to connect runs a Fedora core 8  and using ssh2 v1.2.0 ; 

I can successfully run and see `xeyes` when run through ssh -X : 

```
ssh -X mylogin@myremote "xeyes"
```

unfortunately, if I run you client example / Forward remote X11 connections, although I can connect to the remote, the `xserversock.connect(6000, 'localhost')` fails with 

```
yarn run v1.22.11
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6000
}
```

Do you have any clue on how to solve that and actually display the xeyes program ? 

Note: I though there might be issues with permissions to access X11, but after a `xhost +`, it still fails with the same connection refused error. 

Thank you for your help.

**Comment by mscdex** [comment]
Perhaps you have a different display number (`echo $DISPLAY`)? 6000 should work for `:0` but if you are using `:1` then it would be 6001 and so on.

**Comment by jeremyfix** [comment]
Sorry, I should have given that information , indeed :

```
$ echo $DISPLAY 
:0
```

so I should have excepted 6000 to work ; 

I do not know if I can try, for testing,  connecting to the X server from the terminal directly to test if I can connect to my X server outside from the node execution.

**Comment by mscdex** [comment]
Additionally, it could be that the X server is listening on a UNIX socket instead of a TCP port. If that's the case then you will just need to pass the UNIX socket path instead of the TCP port and host.

**Comment by jeremyfix** [comment]
Indeed, that was the thing.

By changing :

```
xserversock.connect(6000, 'localhost');
```

into :

```
xserversock.connect('/tmp/.X11-unix/X0');
```

I got `xeyes` displayed. 

Thank you for your (very quick!) help.
