### ISSUE TITLE
Atomic unlink() + rename()

### ISSUE THREAD

**Issue by kripper** [mscdex/ssh2#1054]
Hi,

I implemented support for using temp files when uploading files with the vscode-sftp plugin for Visual Code.
See Pull Request: https://github.com/Natizyskunk/vscode-sftp/pull/29

The feature is discussed in detail here: https://github.com/Natizyskunk/vscode-sftp/issues/16

When I first tried to rename the temp file to the existing target file I got an exception, so I added unlink() before doing rename().

The problem is that the operation is not atomic and the web server will fail if it tries to access the file between unlink() and rename().

Is there any chance to use rename() to overwrite the existing target file instead of throwing an exception?
This way, the upload operation would be atomic.

**Comment by mscdex** [comment]
This module can't provide anything that SFTP doesn't already provide. My only suggestion would be to instead try `sftp.ext_openssh_rename()` if the remote server is OpenSSH.

**Comment by kripper** [comment]
Is `sftp.ext_openssh_rename()` able to use the flags described in the [SFTP protocol spec](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13#section-8.3)?

SSH_FXF_RENAME_OVERWRITE  0x00000001
SSH_FXF_RENAME_ATOMIC     0x00000002
SSH_FXF_RENAME_NATIVE     0x00000004

**Comment by kripper** [comment]
a) It seems you are using [version 2](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02)?
This version doesn't support this flags, but version 5+ does.
Any plan to upgrade to version 5?

b) A workarround could be to send both commands (unlink + rename) together to get pseudo-atomicity. Is this possible?

**Comment by kripper** [comment]
I confirm `ext_openssh_rename()` works fine overwriting any existing file.
I'm just concerned about compatiblity.
I guess we will need to add an option to enable openssh support.

**Comment by mscdex** [comment]
`sftp.ext_openssh_rename()` is an OpenSSH-specific SFTP extension and doesn't use any flags.

> a) It seems you are using [version 2](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02)?

It's actually version 3, but you linked the correct RFC.

> Any plan to upgrade to version 5?

Not really. OpenSSH only supports the same SFTPv3 spec as well, which is by far the most common implementation.

> b) A workaround could be sending both commands (unlink + rename) together to get pseudo-atomicity. Is this possible?

I'm not sure which `rename` you're referring to here. `sftp.ext_openssh_rename()` should be the equivalent of a `mv` in *nix, so as far as I know it should be atomic. For the SFTP standard rename, there is no special ordering or sending of the requests that will get you any kind of (guaranteed) atomicity.

Ultimately if you need atomicity and the SFTP server is not OpenSSH, you will need to rely on executing ssh commands to achieve the same thing. If ssh commands are not permitted, I don't know what else to suggest.

**Comment by kripper** [comment]
Thanks. We will rely on ext_openssh_rename() when explicitly enabled by the user.

**Comment by kripper** [comment]
Maybe autodetect when connecting to an OpenSSH server and always use ext_openssh_rename() instead of rename().
And if it's not an OpenSSH server and rename() throws an error because the target file exists, then automatically do a unlink() and rename() again?
This way developers would just have a working rename() function and protocol issues would be handled transparently by the "ssh2" module.
This could also be enabled with a flag called "renameOverwrite" in case a user prefers to catch an error when the target file exists.

**Comment by mscdex** [comment]
I'm not comfortable with making that kind of decision automagically. Feel free to do this yourself though, just wrap the extension call in a try...catch and do a fallback rename of some kind in the catch handler.
