### ISSUE TITLE
How do I use ssh2 in a way which will not try to build cpu-features?

### ISSUE THREAD

**Issue by FrankDMartinez** [mscdex/ssh2#1055]
I want to use this package in a project on Azure DevOps but DevOps doesn’t have cmake and, as far as I know, I cannot install cmake in DevOps. Therefore, when DevOps tries to build our project, we get build errors with respect to cpu-features.

Since cpu-features is optional, I’d like to use this package without if possible. So, is there a particular setting I need to use somehow?

Thanks in advance.

**Comment by mscdex** [comment]
It's already optional.

**Comment by mscdex** [comment]
If the build output is that big of an issue for you, npm (or whatever package manager you're using) probably has a CLI flag you can use to skip optional dependencies entirely. Whether functionality like that is available via package.json for your package manager is another question.

**Comment by YanivBah** [comment]
I also had the same problem and couldn't control the flags of the npm install command.
If you go to your package-lock.json and remove cpu-features it will not try to install it anymore.

Remove this inside package-lock.json:
```json
    "cpu-features": {
      "version": "0.0.2",
      "resolved": "https://registry.npmjs.org/cpu-features/-/cpu-features-0.0.2.tgz",
      "integrity": "sha512-/2yieBqvMcRj8McNzkycjW2v3OIUOibBfd2dLEJ0nWts8NobAxwiyw9phVNS6oDL8x8tz9F7uNVFEVpJncQpeA==",
      "optional": true,
      "requires": {
        "nan": "^2.14.1"
      }
    },
```

and also the line inside the requires of ssh2:
```json
"ssh2": {
      "version": "1.3.0",
      "resolved": "https://registry.npmjs.org/ssh2/-/ssh2-1.3.0.tgz",
      "integrity": "sha512-OjBQ5FR+ClYav3fRnvkhycmd5co5qEfofBaZEqVO3I4tKJLZqu+Ku4LN4nJSckjhqQnomqBqlCdvD3iGV+6isA==",
      "requires": {
        "asn1": "^0.2.4",
        "bcrypt-pbkdf": "^1.0.2",
        "cpu-features": "0.0.2", THIS LINE
        "nan": "^2.15.0"
      }
    },
```

**Comment by FrankDMartinez** [comment]
Turns out this was produced as a "warning" by my build system and I had the settings for that system set too high for acceptability. Closing the ticket.
