### ISSUE TITLE
Module parse failed: Unexpected character

### ISSUE THREAD

**Issue by FrankDMartinez** [mscdex/ssh2#1056]
Hello.

I received this error during my build. Can anyone point me in the direction of information how to resolve this error? The URL given in the message seems to provide no useful information on this point.

```
ERROR in ../../node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node 1:2
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ../../node_modules/ssh2/lib/protocol/crypto.js 30:12-60
 @ ../../node_modules/ssh2/lib/server.js 27:29-60
 @ ../../node_modules/ssh2/lib/index.js 33:10-32
 @ ./src/subscriber/sftpJobHandler/index.ts 7:13-28
```

Thanks in advance.

**Comment by mscdex** [comment]
Looks like your CLI tool is incorrectly interpreting a binary addon file as a plain text javascript file. You'll want to lodge an issue with whatever tool you're using.

**Comment by FrankDMartinez** [comment]
I figured it out. I had to add the "node-loader" package. I don't know if that package is supposed to be a dependency of this one but, if not, you might want to consider such a change. Meanwhile, I will see if I can reach out to my CLI tool vendor. Thanks!
