### ISSUE TITLE
SSH2 + TLS seems to hang mysql2

### ISSUE THREAD

**Issue by odubuc** [mscdex/ssh2#1062]
I've posted a question [ here on MySQL2](https://github.com/sidorares/node-mysql2/issues/1386) and since the issues raised after combining both libs ( SSH2 + mysql2 ), I figured I'd ask feedback from both sides, maybe someone would know what is happening.

As described in my issue, SSH2 and mysql2 works great together as long as I don't enable TLS on the forwarded socket. Is there a known limitation that could prevent me to do such a thing ?

**Comment by mscdex** [comment]
There's no limitation from `ssh2`, you can forward any port that the server will permit.

**Comment by odubuc** [comment]
Thank you very much for your input, I will focus my effort on mysql2. closing this for now since I only needed a positive feedback on my tests.
