### ISSUE TITLE
Server Host Key ssh-rsa-1024

### ISSUE THREAD

**Issue by sid370** [mscdex/ssh2#1063]
Server Host Keys does not accept ssh-rsa-1024 as a server host key? Is there a workaround for this?
![image](https://user-images.githubusercontent.com/44199281/133315909-244c79dc-b3ea-430a-bc98-728f5e82ebb7.png)

**Comment by mscdex** [comment]
That's not a valid algorithm name. You probably want just `'ssh-rsa'`.
