### ISSUE TITLE
Does it support ssh option like ''-o option"?

### ISSUE THREAD

**Issue by fbs2016** [mscdex/ssh2#1065]
I can ssh to server with “VAR=test ... -o SendEnv=VAR" from host terminal, in TS code, I try to set the options "-o xxx" but can't find the right option, does it support it? 
this.config = {
      host: undefined,
      port: undefined,
      localAddress: undefined,
      localPort: undefined,
      forceIPv4: undefined,
      forceIPv6: undefined,
      keepaliveCountMax: undefined,
      keepaliveInterval: undefined,
      readyTimeout: undefined,
      ident: undefined,

      username: undefined,
      password: undefined,
      privateKey: undefined,
      tryKeyboard: undefined,
      agent: undefined,
      allowAgentFwd: undefined,
      authHandler: undefined,

      hostHashAlgo: undefined,
      hostHashCb: undefined,
      strictVendor: undefined,
      debug: undefined
    };

**Comment by mscdex** [comment]
`env` is supported in both `exec()` and `shell()`. The server may restrict what environment variables you're able to set though. Otherwise you might try setting them explicitly in your `exec()` command or `shell()` session.
