### ISSUE TITLE
Need help with passing user input

### ISSUE THREAD

**Issue by itzJOHv** [mscdex/ssh2#1066]
Hi so um I need to pass a user input in this case, I'm using some code from internet to emit enter press but it doesn't work. Any ideas how to make this?
![image](https://user-images.githubusercontent.com/68508885/133790871-20328e15-3810-472e-84e7-fd9892b3f813.png)

ssh2 ver 0.8.9

**Comment by mscdex** [comment]
Write to the `stream` or `stream.stdin` (they both point to stdin) that you get from `exec()`. A better solution though would be to utilize a non-interactive mode (using environment variables, command line parameters, or perhaps a config file) for whatever program you're trying to use.

**Comment by itzJOHv** [comment]
> Write to the `stream` or `stream.stdin` (they both point to stdin) that you get from `exec()`.
> 
> A better solution though would be to utilize a non-interactive mode (using environment variables, command line parameters, or perhaps a config file) for whatever program you're trying to use.

But can I write to the `stream` after it's closed? (As I need to get the data first to know if it contains the thing I need)

**Comment by mscdex** [comment]
> But can I write to the `stream` after it's closed?

In node in general you cannot write to streams that are closed.

**Comment by itzJOHv** [comment]
> In node in general you cannot write to streams that are closed.
So thing I want to do isn't really possible?

**Comment by mscdex** [comment]
Specifically since it looks like you're using certbot in this case, you can run certbot in a non-interactive mode (provided you supply all of the other required command-line flags so it has all of the information it needs to answer the prompts) which should solve the problem of needing to manually simulate keyboard entry.

**Comment by mscdex** [comment]
Also on an unrelated note, `ssh2` v0.8.x is no longer supported.

**Comment by itzJOHv** [comment]
> Specifically since it looks like you're using certbot in this case, you can run certbot in a non-interactive mode (provided you supply all of the other required command-line flags so it has all of the information it needs to answer the prompts) which should solve the problem of needing to manually simulate keyboard entry.

Ohh that makes sense, thanks.

**Comment by itzJOHv** [comment]
> Also on an unrelated note, `ssh2` v0.8.x is no longer supported.

I can update but not sure if it's going to work as it is working on v0.8 because I'm using source code that uses v0.8

**Comment by itzJOHv** [comment]
forgot to close it earlier
