### ISSUE TITLE
Error with Cisco 888 device: Tried to get more bytes than in SSH Buffer

### ISSUE THREAD

**Issue by Telecom-Object** [mscdex/ssh2#1068]
Hi,

Cannot connect to cisco 888 device, with version > 1.0.0, with the version 0.8.9 no problem.
The logs from cisco: 

Sep 21 08:51:17.711: %SSH-3-BUFF_GET_FAIL: Tried to get more bytes than in SSH Buffer
Sep 21 08:51:17.711: %SSH-3-PACK_INTEG_ERROR: Packet integrity error (614 bytes remaining)

**Comment by mscdex** [comment]
Can you try the master branch? There were some fixes made recently for Cisco devices.

**Comment by Telecom-Object** [comment]
Works with the master branch.
Thank you !!

I will wait for the next release
