### ISSUE TITLE
ssh2 not returning files permissions, defaults to 644 since update to 1.4.0

### ISSUE THREAD

**Issue by vmkalbskopf** [mscdex/ssh2#1073]
Will this feature be enabled again?

**Comment by vukbgit** [comment]
Hello, adding some context here: switched into [ftp-remote-plus atom package](https://github.com/vukbgit/ftp-remote-edit-plus) from ssh2 0.5.5 to 1.4.0, and now into the method client.sftp() callback argument, the sftp object does not seem to stat files permission anymore (permission property of the stats object is empty)

**Comment by mscdex** [comment]
Switching from `ssh2` 0.5.5 to 1.4.0 is quite the jump, the author of that package will probably need to update their `ssh2` API usage.
