### ISSUE TITLE
How can I execute a local script file?

### ISSUE THREAD

**Issue by yancheng199287** [mscdex/ssh2#1088]
When I use SSH to connect to the server remotely，How can I execute a local script file?

I don't want to execute after uploading。

just like that：

`client.exec("C:\Users\alice\Desktop\test.sh",parameter1, parameter2)`

Can you give me some suggestions and ideas？ Thanks.

**Comment by mscdex** [comment]
You will need to create the entire command string yourself and pass it to `exec()`.

**Comment by Ross249** [comment]
what about use sftp to upload your script and exec it ?
