### ISSUE TITLE
Capturing a client keep alive request ?

### ISSUE THREAD

**Issue by khkiley** [mscdex/ssh2#1089]
Hello, is there a way within the server module to capture the keep alive requests from the client ? I've tried listening to different events, as well as taking a crack going through the source, and was unsuccessful in finding it if its possible.

Thank you.

Kurt

**Comment by khkiley** [comment]
Thank you for the quick reply.

I'm looking to build a managed SSH tunnel to access clients on prem SQL database from the cloud. The keep alive information could be used to analyze connectivity quality, and to anticipate/analyze connection problems pre-emptively.  The keep alive information would also ensure the ssh client is alive, not only connected.

**Comment by mscdex** [comment]
The server already has built-in support for keepalive handling, the documentation is just lacking.

The server uses the same two keepalive configuration property names that the Client uses (`keepaliveCountMax` and `keepaliveInterval`). If those are not valid numbers, then it uses `Server.KEEPALIVE_CLIENT_INTERVAL` and `Server.KEEPALIVE_CLIENT_COUNT_MAX` as the defaults (15 seconds and 3 keepalive packets respectively) if they are valid numbers. If those variables have been overridden and are not valid numbers, then keepalive is not used.

**Comment by mscdex** [comment]
Additionally for both Client and Server, this keepalive mechanism is only used when there is absolutely no traffic being received, so you won't see OpenSSH-style keepalive requests going back and forth if there are other packets.

**Comment by khkiley** [comment]
Thank you, from your explanation and looking at the code I think I understand what the process is. Keep alive is a "fire and forget" action. The server is not looking for a specific response back from the client, any response at all will reset the timer and outstanding request counter. If the server's keep alive interval is shorter than the client, the client will not send any keep alive requests, and vice versa.

**Comment by mscdex** [comment]
You are correct. That is why it doesn't matter whether the other side responds with a success or failure to our (dummy) keepalive request, just so as long as we keep hearing back from the other side.
