### ISSUE TITLE
Cannot forward connections on remote port with ip other than local ip

### ISSUE THREAD

**Issue by arrkiin** [mscdex/ssh2#109]
In the example "Authenticate using password and forward remote connections on port 8000 to us" forwarding is done with "curl -I http://127.0.0.1:8000". If I use "curl -I 192.168.0.100:8000" the system respond with "curl: (7) couldn't connect to host".

The corresponding lines in my javascript are:
c.on('ready', function() {
  console.log('Connection :: ready');
  c.forwardIn('0.0.0.0', 8000, function(err) {
    if (err) throw err;
    console.log('Listening for connections on server on port 8000!');
  });
});

If I use "curl -I http://127.0.0.1:8000" instead, all is ok.

**Comment by shivasrk8** [comment]
How can we mention GatewayPorts no when we are creating ssh server using this module.?

**Comment by mscdex** [comment]
@shivasrk8 If you're creating a server with `ssh2` that's totally up to you how incoming port forward requests are handled. `ssh2` does not handle port forwarding automatically. If you want to support "GatewayPorts no", then just ignore `info.bindAddr` in your `request` event handler on the client connection and only use `info.bindPort`. Then it's just a matter of creating a `net.Server` that listens on that port on localhost only.

**Comment by shivasrk8** [comment]
@mscdex Brian Please look at issue 435 where I posted the process(Code) which I am following! Actually I want to go which "GatewayPorts clientSpecified" which I have to handle using ssh2 module.
