### ISSUE TITLE
readdir returns false, but 'continue' event never emitted

### ISSUE THREAD

**Issue by vorfol** [mscdex/ssh2#1090]
the question is - who should emit 'continue'? me on readdir callback or some code inside ssh2?

**Comment by mscdex** [comment]
`ssh2` v1.0 and newer no longer uses `'continue'` events.

**Comment by vorfol** [comment]
somebody should update @types/ssh2

**Comment by mscdex** [comment]
Sorry, I don't use TypeScript. You'll have to look to whoever was previously maintaining those definitions.
