### ISSUE TITLE
SSH Server: prefer publickey, than none.

### ISSUE THREAD

**Issue by antonmedv** [mscdex/ssh2#1092]
I want to create SSH server which allows **publickey** and **none** authorization methods. But if I specify switch with both, only **none** is used even if I specify  private key via cli: `ssh -i id.rsa localhost`.

```js
  client.on('authentication', (ctx) => {
    switch (ctx.method) {
      case 'publickey':
        ctx.accept()
        break
      case 'none':
        ctx.accept()
        break
      default:
        return ctx.reject(['publickey'])
    }
    username = ctx.username
  })
```

Is it possible to prefer publickey and after none? Thanks for the awesome package! Really like working this it.

**Comment by mscdex** [comment]
That's up to you to enforce an order for authentication methods. You could store an array in the parent scope (still scoped per connection) containing the expected methods in order and then just shift them off one by one if they match what the client offers.

**Comment by antonmedv** [comment]
I'm not getting it. How I can allow both none and publickey, but prefer publickey?

If I add log:

```diff
    client.on('authentication', (ctx) => {
+     console.log(ctx.method)
      switch (ctx.method) {
```

I can see:
```
Client connected!
none
publickey
publickey
Client authenticated!
```

If I reject on none, it's works for publickey. But if user authenticates only with none - will get `anton@localhost: Permission denied (publickey).`

**Comment by antonmedv** [comment]
I tried something like this:
```
  let none = false
  client.on('authentication', (ctx) => {
    console.log(ctx.method)
    if (!none && ctx.method === 'none') {
      none = true
      console.log('reject', 1)
      return ctx.reject(['none', 'publickey'], false)
    } else {
      if (ctx.method === 'publickey') {
        ctx.accept()
      } else {
        console.log('reject', 2)
        return ctx.reject(['publickey'])
      }
    }
  })
```

But looks like it's impossible to support both publickey and now with publickey being preferable method.

**Comment by mscdex** [comment]
I don't think there is any server-side solution to what I think you're wanting. There is no way to know if a client is going to end up attempting 'publickey' authentication after attempting 'none'. Is there a reason why you're wanting this behavior? Typically you require either exactly one authentication method or require multiple authentication methods. In most cases the 'none' method is never accepted and is only used by clients to attempt to detect which methods are actually valid (by expecting the server to return a valid list of methods that can continue).

**Comment by antonmedv** [comment]
Yes, this is also what I got from RFC. 

> Is there a reason why you're wanting this behavior?

I'd like to allow publickey user to login, and others (none) to register at server.
