### ISSUE TITLE
Packet length exceed the maximum.

### ISSUE THREAD

**Issue by yuqihang** [mscdex/ssh2#1094]
The definition in `lib/protocol/SFTP.js:116` v1.5.0
https://github.com/mscdex/ssh2/blob/6b4c64ce5c16f488d90b87997aa0f19c871abe2f/lib/protocol/SFTP.js#L116
Error: 

> Packet length 1214346853 exceeds max length of 262144

How to process packet length exceeding this value? I came across this error, and how can I resolve the problem? @mscdex

**Comment by mscdex** [comment]
A single 1.2GB SFTP packet is either a bug in the SFTP parser or the client is actually trying to send such a large SFTP packet. If it's the latter, then I don't think we should be supporting such packets.

**Comment by yuqihang** [comment]
Yes, you are right. I also wonder what happened. I tried to reset my config files, but it didn't work. I need to look for other methods, thanks a lot！
