### ISSUE TITLE
Add support for non-OpenSSH variants of 'aes128-gcm' and 'aes256-gcm' ciphers

### ISSUE THREAD

**Issue by colemujadzic** [mscdex/ssh2#1100]
In f1b5ac3, 'aes128-gcm' and 'aes256-gcm' were removed from the DEFAULT_CIPHER list in lib/protocol/constants.js.

I wanted to ask if y'all would welcome a pull request to add these back to SUPPORTED_CIPHER (see: https://github.com/mscdex/ssh2/blob/master/lib/protocol/constants.js#L102-L115) in order to maintain support for servers that still use them.

Thanks and let me know if y'all need any additional information!

**Comment by mscdex** [comment]
We can re-enable it again, but I fear people connecting to (some) Cisco hardware might complain based on my experiences in https://github.com/mscdex/ssh2/issues/1064.

**Comment by colemujadzic** [comment]
Thanks for the quick response!

My thought is that leaving them out of the 'default' list and adding them to the 'supported' one (so that folks can choose whether to use them or not, but they wouldn't be used by default when no overrides are provided) _should_ be okay. 

That being said — I can do some testing with a few sandboxes I have access to (Cisco IOS-XE, HP Procurve, SonicWall, etc.) and follow up with a PR if that's alright with you?

**Comment by mscdex** [comment]
Sure.

**Comment by yaverin** [comment]
Please clarify, when are you planning to make new release with these changes?

**Comment by colemujadzic** [comment]
Would also love to see this make it into a release soon, as it would unblock a lot of work for us 🙂

**Comment by shubhamkd** [comment]
Is it resolved now? If yes, can we get it closed?
