### ISSUE TITLE
Node app crashes few minutes after using node-ssh

### ISSUE THREAD

**Issue by leobgm** [mscdex/ssh2#1105]
My app connects to a remote server using node-ssh. Everything is fine, but the app crashes after few minutes with this error

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/var/www/iostream/node_modules/ssh2/lib/client.js:745:12)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
[nodemon] app crashed - waiting for file changes before starting...

I searched about it and looks like it's something related to closing the connection abruptly by the remote server. Seems like the connections are kept open and not closed properly.

**Comment by mscdex** [comment]
Can you reproduce this using `ssh2` directly? How are you closing the connection?

**Comment by soroushBgm** [comment]
In node-ssh document there's nothing refrerring to close a connection.
Should I use ssh2 instead?

**Comment by mscdex** [comment]
You should definitely close the connection if you're no longer needing it. I can't speak about `node-ssh`'s API if they provide a way to do that, you may need to take it up with that package's maintainer.

Either way, you should have proper error handling in place to prevent crashing. For `ssh2`, that would mean attaching `'error'` event handlers.
