### ISSUE TITLE
Using agent.js to proxy agent requests to a web client

### ISSUE THREAD

**Issue by cintolas** [mscdex/ssh2#1107]
Hello,

We hacked an older version of your ssh2 module to emit a 'public-key' event that would get the public key from a remote system.
The remote system would also sign the key data.

This way we did not need to store the private key file/password on the same system as the node ssh client library.

It seems to me that this is pretty much what the agent.js script does as well.

Do you have any tips on how this can be accomplished with the already built agents?

Or perhaps it's better for us to build and contribute a new ProxyAgent, whose job is just to forward the requests somewhere else.

In our current configuration, we listen for events on the nodejs server, and then proxy them through the web to a web client that holds the private keys.  
The web client then will send the public keys
and sign any sign data passing HTTP requests  back and forth as JSON messages with base64 encoded results.

**Comment by mscdex** [comment]
I would suggest implementing a custom Agent and using that for authentication, see the documentation for `BaseAgent`. There is also a simple implementation in test-userauth-agent.js.

**Comment by cintolas** [comment]
I am starting to extend BaseAgent

I made a getIdenties method.

The callback is callback(err, keys)

I am sending keys as an array of Buffers.
However it is not working.  

What are keys supposed to be?  In my old hacked version we sent the publicKey as a buffer

**Comment by mscdex** [comment]
Each key can either be already parsed with `utils.parseKey()` or be a Buffer/string containing a public key in a format (e.g. OpenSSH, RFC4716, or PPK) that can be parsed by `utils.parseKey()`.

**Comment by cintolas** [comment]
So before sending the keys to the callback, i should use utils.parseKey() on them?

**Comment by mscdex** [comment]
You don't have to:

> or be a Buffer/string containing a public key in a format (e.g. OpenSSH, RFC4716, or PPK) that can be parsed by `utils.parseKey()`.

**Comment by cintolas** [comment]
Thanks!  I got it up and running.
