### ISSUE TITLE
When using shell, the stream's on.data callback function gets both inbound and outbound data.

### ISSUE THREAD

**Issue by JoeNemo** [mscdex/ssh2#1108]
First, I apologize that I cannot find a discussion area for this package, as I guess this is intentional behavior.   However, in my function that handles the on('data') of the stream like,
```


conn.on('ready', () => {
  console.log('Client :: ready');
  conn.shell((err, stream) => {
    if (err) throw err;
    stream.on('close', () => {
      console.log('Stream :: close');
      conn.end();
    }).on('data', (data) => {
      console.log('OUTPUT: ' + data);
    });
    stream.end('ls -l\nexit\n');
  });
}).connect({
```

I don't know of any general way to distinguish data that comes from by inbound shell commands, from the outbound output.   I don't think the data is round-tripping through the server.  I think the duplex stream that the shell provides is being pushed/written to on the node.js side of the conversation.  Of course, I could be wrong.  

Thanks and apologies in advance for missing the obvious or not understand Node.js streams as well as I should.

**Comment by mscdex** [comment]
`shell()` is designed to be used as an interactive session, which is why you're seeing input echoed back. This is coming from the server.

For at least Linux servers, you can use commands like `stty` to disable local echo, but you're probably better served by `exec()` instead of `shell()`, which is for non-interactive command execution.

**Comment by JoeNemo** [comment]
Thanks for the prompt and helpful response.  I forgot about stty, and that clears up a lot of confusion.  I thought that exec ran one command and then closed.   I want to keep the connection open and send and receive multiple pieces of data.   Normally a sane person would do this through tunnelling, but I am working on a system in which the admins own the sshd config and will not configure a tunnel for my app.  So what I am doing is really a bit of a hack.

**Comment by mscdex** [comment]
It depends on what you're doing, but if you're referring to a process that stays open and you just feed it more data via stdin, then you can most definitely do that with `exec()`.

As far as tunneling goes, if you can't use `forwardOut()` there are alternative ways of tunneling, such as using tools on the remote server like `socat` or `netcat`.

**Comment by JoeNemo** [comment]
Thanks for all the help.   I have learned a lot and thing are beginning to work in my tests.  The target platform (not Unix/Linux/Windows) doesn't implement socat or netcat, and the admins are unlikely to open any ports in their firewalls beyond port 22.  That's why this library you have written is so great!
