### ISSUE TITLE
No passphrase error was thrown instead of emitted

### ISSUE THREAD

**Issue by daveteu** [mscdex/ssh2#1115]
Not sure whether it was intend but if we were to do with no passphrase given for a encrypted private key, the error was thrown instead of emitted to `on('error')`

            ssh.connect({
                host: profile.host,
                port: profile.port,
                username: profile.username,
                privateKey,
                // passphrase: "123!"  //intentionally omitted
            })

The error message is 
>  Cannot parse privateKey: Encrypted private OpenSSH key detected, but no passphrase given

We need to use try/catch to catch this error.

Is it not better if it can be emitted to the `error` event?

**Comment by mscdex** [comment]
My general approach when writing node.js code is to throw if the error occurs synchronously (e.g. before the end of the function/code) and to use callbacks/events/etc. for errors that occur asynchronously (after the end of the function/code).
