### ISSUE TITLE
SFTP: Inbound: Malformed STATUS packet

### ISSUE THREAD

**Issue by sbulheller** [mscdex/ssh2#1116]
After upgrading the ssh2-sftp-client from 6.0.1 to 7.2.1 an file-upload was no longer possible. I filed an issue there (https://github.com/theophilusx/ssh2-sftp-client/issues/373), but it seems to be a problem with the ssh2 lib.

To verify this i used a simple put script:
```
'use strict';

// simple test file using low level put command based only on ssh2 lib

const path = require('path');
const fs = require('fs');

const dotenvPath = path.join(__dirname, '..', '.env');

require('dotenv').config({ path: dotenvPath });

const { Client } = require('ssh2');

const config = {
  host: process.env.SFTP_SERVER,
  username: process.env.SFTP_USER,
  password: process.env.SFTP_PASSWORD,
  port: process.env.SFTP_PORT || 22,
  debug: console.log
};

const client = new Client();

const sourceFile = process.argv[2];
const remotePath = process.argv[3];

client
  .on('ready', function () {
    client.sftp(function (err, sftp) {
      console.log(`Sending ${sourceFile} to ${remotePath}`);
      if (err) {
        console.log(`Error: ${err.message}`);
        return err;
      }
      let stream = sftp.createWriteStream(remotePath, { encoding: null });
      stream.on('error', (err) => {
        console.log(`Stream Error: ${err.message}`);
        client.end();
      });
      stream.on('finish', () => {
        console.log(`File successfully uploaded to ${remotePath}`);
        client.end();
      });
      let rdr = fs.createReadStream(sourceFile, { encoding: null });
      rdr.on('error', (err) => {
        console.log(`Reader Error: ${err.message}`);
        client.end();
      });
      rdr.pipe(stream);
    });
  })
  .on('error', function (err) {
    console.error(err.message);
  })
  .connect(config);
```

this is the error i get, when trying to upload a file to netfiles.de:

> Custom crypto binding not available
> Local ident: 'SSH-2.0-ssh2js1.5.0'
> Client: Trying netfiles.de on port 3333 ...
> Socket connected
> Remote ident: 'SSH-2.0-OpenSSH_8.2p1'
> Outbound: Sending KEXINIT
> Inbound: Handshake in progress
> Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
> Handshake: (remote) KEX method: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
> Handshake: KEX algorithm: curve25519-sha256@libssh.org
> Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
> Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa
> Handshake: Host key format: rsa-sha2-512
> Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
> Handshake: (remote) C->S cipher: aes256-ctr,aes256-gcm@openssh.com
> Handshake: C->S Cipher: aes256-gcm@openssh.com
> Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
> Handshake: (remote) S->C cipher: aes256-ctr,aes256-gcm@openssh.com
> Handshake: S->C cipher: aes256-gcm@openssh.com
> Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
> Handshake: C->S MAC: <implicit>
> Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> Handshake: (remote) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
> Handshake: S->C MAC: <implicit>
> Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
> Handshake: (remote) C->S compression: none,zlib@openssh.com
> Handshake: C->S compression: none
> Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
> Handshake: (remote) S->C compression: none,zlib@openssh.com
> Handshake: S->C compression: none
> Outbound: Sending KEXECDH_INIT
> Received DH Reply
> Host accepted by default (no verification)
> Host accepted (verified)
> Outbound: Sending NEWKEYS
> Inbound: NEWKEYS
> Verifying signature ...
> Verified signature
> Handshake completed
> Outbound: Sending SERVICE_REQUEST (ssh-userauth)
> Inbound: Received SERVICE_ACCEPT (ssh-userauth)
> Outbound: Sending USERAUTH_REQUEST (none)
> Inbound: Received USERAUTH_FAILURE (publickey,password)
> Client: none auth failed
> Outbound: Sending USERAUTH_REQUEST (password)
> Inbound: Received USERAUTH_SUCCESS
> Outbound: Sending CHANNEL_OPEN (r:0, session)
> Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
> Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
> Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
> Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
> Inbound: REQUEST_SUCCESS
> Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
> Inbound: CHANNEL_SUCCESS (r:0)
> Outbound: Sending CHANNEL_DATA (r:0, 9)
> Inbound: CHANNEL_DATA (r:0, 42)
> SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com)
> Sending ./test.txt to /xxx/projectfiles/test.txt
> Outbound: Sending CHANNEL_DATA (r:0, 62)
> SFTP: Outbound: Buffered OPEN
> Inbound: CHANNEL_DATA (r:0, 17)
> SFTP: Inbound: Received HANDLE (id:0)
> Outbound: Sending CHANNEL_DATA (r:0, 25)
> SFTP: Outbound: Buffered FSETSTAT
> Inbound: CHANNEL_DATA (r:0, 13)
> SFTP: Inbound: Malformed STATUS packet
> Malformed STATUS packet
> Socket ended
> Socket closed

**Comment by mscdex** [comment]
I am not able to reproduce this. My guess is they are using some custom/third-party implementation for the SFTP portion of the server (and not the one included with OpenSSH). One piece of evidence that makes me believe that is that the SFTP server only advertises the posix-rename extension, whereas the typical OpenSSH (8.2) SFTP server will advertise 6 extensions in total (it *is* possible to disable individual SFTP extensions, but I've never seen anyone do that).

My hunch here is that this SFTP server implementation is not sending the language field (I've seen this before and it seems like this workaround did not make it from v0.8.x to v1.0.0), but not sending an error message would also trigger it although I've never seen that missing from any server implementation before. Either way, try this patch and let me know if everything works for you:

```diff
diff --git a/lib/protocol/SFTP.js b/lib/protocol/SFTP.js
index b10d9e5..f667916 100644
--- a/lib/protocol/SFTP.js
+++ b/lib/protocol/SFTP.js
@@ -2596,12 +2596,6 @@ const CLIENT_HANDLERS = {
     const lang = bufferParser.skipString();
     bufferParser.clear();
 
-    if (lang === undefined) {
-      if (reqID !== undefined)
-        delete sftp._requests[reqID];
-      return doFatalSFTPError(sftp, 'Malformed STATUS packet');
-    }
-
     if (sftp._debug) {
       const jsonMsg = JSON.stringify(errorMsg);
       sftp._debug(
```

**Comment by sbulheller** [comment]
i commented out the lines and the test script worked:

> Custom crypto binding not available
> Local ident: 'SSH-2.0-ssh2js1.5.0'
> Client: Trying netfiles.de on port 3333 ...
> Socket connected
> Remote ident: 'SSH-2.0-OpenSSH_8.2p1'
> Outbound: Sending KEXINIT
> Inbound: Handshake in progress
> Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
> Handshake: (remote) KEX method: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
> Handshake: KEX algorithm: curve25519-sha256@libssh.org
> Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
> Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa
> Handshake: Host key format: rsa-sha2-512
> Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
> Handshake: (remote) C->S cipher: aes256-ctr,aes256-gcm@openssh.com
> Handshake: C->S Cipher: aes256-gcm@openssh.com
> Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
> Handshake: (remote) S->C cipher: aes256-ctr,aes256-gcm@openssh.com
> Handshake: S->C cipher: aes256-gcm@openssh.com
> Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
> Handshake: C->S MAC: <implicit>
> Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> Handshake: (remote) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
> Handshake: S->C MAC: <implicit>
> Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
> Handshake: (remote) C->S compression: none,zlib@openssh.com
> Handshake: C->S compression: none
> Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
> Handshake: (remote) S->C compression: none,zlib@openssh.com
> Handshake: S->C compression: none
> Outbound: Sending KEXECDH_INIT
> Received DH Reply
> Host accepted by default (no verification)
> Host accepted (verified)
> Outbound: Sending NEWKEYS
> Inbound: NEWKEYS
> Verifying signature ...
> Verified signature
> Handshake completed
> Outbound: Sending SERVICE_REQUEST (ssh-userauth)
> Inbound: Received SERVICE_ACCEPT (ssh-userauth)
> Outbound: Sending USERAUTH_REQUEST (none)
> Inbound: Received USERAUTH_FAILURE (publickey,password)
> Client: none auth failed
> Outbound: Sending USERAUTH_REQUEST (password)
> Inbound: Received USERAUTH_SUCCESS
> Outbound: Sending CHANNEL_OPEN (r:0, session)
> Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
> Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
> Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
> Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
> Inbound: REQUEST_SUCCESS
> Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
> Inbound: CHANNEL_SUCCESS (r:0)
> Outbound: Sending CHANNEL_DATA (r:0, 9)
> Inbound: CHANNEL_DATA (r:0, 42)
> SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com)
> Sending ./test.txt to /xxx/projectfiles/test.txt
> Outbound: Sending CHANNEL_DATA (r:0, 62)
> SFTP: Outbound: Buffered OPEN
> Inbound: CHANNEL_DATA (r:0, 17)
> SFTP: Inbound: Received HANDLE (id:0)
> Outbound: Sending CHANNEL_DATA (r:0, 25)
> SFTP: Outbound: Buffered FSETSTAT
> Inbound: CHANNEL_DATA (r:0, 13)
> SFTP: Inbound: Received STATUS (id:1, 8, undefined)
> Outbound: Sending CHANNEL_DATA (r:0, 58)
> SFTP: Outbound: Buffered SETSTAT
> Inbound: CHANNEL_DATA (r:0, 13)
> SFTP: Inbound: Received STATUS (id:2, 8, undefined)
> Outbound: Sending CHANNEL_DATA (r:0, 47)
> SFTP: Outbound: Sent WRITE (id:3)
> Inbound: CHANNEL_DATA (r:0, 13)
> SFTP: Inbound: Received STATUS (id:3, 0, undefined)
> Outbound: Sending CHANNEL_DATA (r:0, 17)
> SFTP: Outbound: Buffered CLOSE
> File successfully uploaded to /xxx/projectfiles/test.txt
> Outbound: Sending DISCONNECT (11)
> Socket ended
> Socket closed
> Stream Error: No response from server

**Comment by sbulheller** [comment]
@mscdex : Thank you for your efforts!
