### ISSUE TITLE
fastPut mangles text files while uploaded to exavault.com

### ISSUE THREAD

**Issue by air2** [mscdex/ssh2#1120]
Hello, 

When I try to upload simple csv files of 600kb with fastPut to exavault.com the files become mangled. When I use the put method the upload works just fine. Would love to see this fixed, but I am not sure if this is a problem in this code base or in exavaults implementation. The first 68510 bytes are fine, but after that it is mangles somehow.

**Comment by mscdex** [comment]
Out of curiosity, if you set `debug: console.log` in the connection config object, what does the remote ident string look like?

**Comment by air2** [comment]
Remote ident: 'SSH-2.0-mod_sftp' (executing)

**Comment by air2** [comment]
I could get you the credentials of an exavault.com sftp server, they are still valid for I guess 2 weeks. If that helps

**Comment by albertosantini** [comment]
Thanks for your efforts in this package.

I am afraid it is not about the server. 
I noticed the same problem: the size of file is correct, but a lot of characters are replaced with others.
`put` is ok. Me too I have been using `ssh2-sftp-client` package.

**Comment by mscdex** [comment]
If someone can come up with something that is easily reproducible, preferably with a VM as the server, let me know. Otherwise it's nearly impossible to tell what the problem is.
