### ISSUE TITLE
SFTP-server doesn't get any events when transferring files

### ISSUE THREAD

**Issue by jatester** [mscdex/ssh2#1121]
Did anyone tested sftp server when using FileZilla? I can get it working when login to sftp in terminal and typing put /file but when I log in in FileZilla and try to move file to remote directory it reconnects and none of available events are triggered. I am testing with debug: console.log and I see only

**Comment by mscdex** [comment]
As mentioned in https://github.com/mscdex/ssh2/issues/1119, you need to add handlers for the requests the client is sending.

**Comment by SantyTaco** [comment]
> Did anyone tested sftp server when using FileZilla? I can get it working when login to sftp in terminal and typing put /file but when I log in in FileZilla and try to move file to remote directory it reconnects and none of available events are triggered. I am testing with debug: console.log and I see only

Could you explain me how did you get it working using a terminal? I am getting this message: 
 % sftp -P 8070 foo@localhost        
foo@localhost's password: 
Connected to localhost.
Couldn't canonicalize: No error
Need cwd

And I don't know what to do after it, I would like to interact with the server using the terminal commands like this example:
❯ sftp root@172.105.186.216
root@172.105.186.216's password:
Connected to 172.105.186.216.
sftp> ?
