### ISSUE TITLE
Can't compile with tsc because of syntax error

### ISSUE THREAD

**Issue by FrankAppGenerics** [mscdex/ssh2#1122]
Compiling with tsc results in error:
  The file was required from 'C:\Work\src\cloud-control\vcc_host-agent\dist\version.js'
> Error! Identifier directly after number (162:63)

This is the following line:
    const dmp1 = bigIntToBuffer(bn_d % (bigIntFromBuffer(p) - **1**n));

It's not allowed to start variable names with a number.

**Comment by mscdex** [comment]
That's a [bigint literal value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt). It's supported in the minimum required node.js version.

I can't help you with TypeScript as I don't use it, but a brief google search reveals it's a configuration/version issue. It seems you need at least TypeScript 3.2 and possibly need to use a new enough TypeScript target (supposedly `esnext`). If that doesn't work, you should file an issue on the TypeScript issue tracker.

**Comment by FrankAppGenerics** [comment]
Thanks for your answer. Tsc seems to compile without problems, but pkg does have probably some issues with BigInt.
