### ISSUE TITLE
Bug: huge memory consumption of ssh2 with native `http` module

### ISSUE THREAD

**Issue by DmitrySobchenkoPA** [mscdex/ssh2#1123]
Hello everyone,

Problem: when using `ssh2` and making any request with native `http` module, the process consuming huge amount of memory.

### Steps to reproduce:

`npm i ssh2 http`

```
tee -a test.js <<EOF
require('ssh2');
const https = require('http');

(async () => {
  await new Promise((resolve => {
    const req = https.request({ host: 'checkip.amazonaws.com', path: '/'}, res => {
      let allData = '';
      res.on('data', d => allData += d);
      res.on('end', () => {
        console.log('request has been finished', allData);

        setTimeout(() => resolve(), 10000); // waiting 10 seconds, to check memory consumption
      });
    });
    req.end();
  }));
})();
EOF
```
Run test script:
`node test.js &`

Check memory consumption:
`ps aux| grep test.js`

It shows me 11170 MB on one machine with node v16, and 9322 MB on other machine with node v10.

---

Both `ssh2` and `http` packages are used in [`testcontainers`](https://www.npmjs.com/package/testcontainers), which causes high memory consumption.

After some digging I located the place which causes high consumption:
`POLY1305_WASM_MODULE = await require('./crypto/poly1305.js')();`

Do you have any ideas how to fix it?

**Comment by mscdex** [comment]
I have several questions:

1. Why are you doing `npm install http` to use the *native* `http` module?
2. What memory are you actually measuring here? RSS? Virtual memory? Something else?
3. The WASM version of the poly1305 MAC is only loaded once on startup.
4. Your code is not actually using `ssh2` at all. Additionally, the only time `ssh2` ever uses/references `http` or `https` from node core is when you are explicitly creating the SSH `http`/`https` Agent instances for tunneling requests. So I don't see how this combination of modules (`ssh2` and `http` from npm) could have the potential to cause any memory issues.

**Comment by DmitrySobchenkoPA** [comment]
Thank you for a responce!
> Why are you doing npm install http to use the native http module (built into node)?

I have checked again: install only `npm i ssh2 `on empty project,  and the bug has still reproduced

> What memory are you actually measuring here? RSS? Virtual memory? Something else?

VSZ: 11170284k
RSS: 45012k
Node's  process.memoryUsage() doesn't show big numbers.

> Your code is not actually using ssh2 at all. Additionally, the only time ssh2 ever uses/references http or https from node core is when you are explicitly creating the SSH http/https Agent instances for tunneling requests. So I don't see how this combination of modules (ssh2 and http from npm) could have the potential to cause any memory issues.

Just `require('ssh2')` makes run initialization code at `./crypto/poly1305.js`. 
Later, when any `http.request` has started, it somehow causes huge memory consumption.

I have checked this on two different hosts with Unubtu 18 and Ubuntu 20.

**Comment by DmitrySobchenkoPA** [comment]
Addition: 
If I just comment the line:
`POLY1305_WASM_MODULE = await require('./crypto/poly1305.js')();`, 
then making `http.request` doesn't causes huge memory consumption anymore.

**Comment by mscdex** [comment]
Virtual memory (VSZ) does not indicate actual memory usage. It's basically just address space usage, which doesn't cost anything itself. The main thing is to look at the RSS, that's how much memory your process is currently using.

If I had to guess what's happening in this instance, the virtual memory is probably increasing because V8 is `mmap()`'ing the WASM file. In that case the file is still stored on disk but the OS needs to reserve address space for the process to access that file's contents (as if it was stored all in memory).
