### ISSUE TITLE
issues about installing ssh2

### ISSUE THREAD

**Issue by qishibo** [mscdex/ssh2#1126]
Using new versions of SSH2 is really twists and turns, It's not the same as using the version 0.5.4

node: 14.8.3
os: ubuntu 16.04
cmake: 3.5.1

when I install `tunnel-ssh` which depends on ssh2 1.4.0, `cpu-feature` errors `cmake not found`
![image](https://user-images.githubusercontent.com/5136418/151701500-6fa738c8-076c-4712-af3c-c0c00e20cd45.png)
the code raise a warning like this
![image](https://user-images.githubusercontent.com/5136418/151701525-acc33066-4f08-4c61-824b-0f4fba8c426e.png)
then I install cmake 3.5.1, the code raise an error...and my code can not exec
![image](https://user-images.githubusercontent.com/5136418/151701632-a0ea3b30-edf8-4295-8407-2260407b0229.png)
so I add `node-loader` to run the cpufeatures.node, and add rules to `webpack.base.conf.js`
```
{
  test: /\.node$/,
  loader: "node-loader",
},
```
but it raised another more error...
![image](https://user-images.githubusercontent.com/5136418/151701722-98b231fd-587b-4f42-9b5e-5ddd14d8d22e.png)

**Comment by mscdex** [comment]
`ssh2` should have installed successfully without cmake.

As far as webpack goes, you will have to create an issue on that project's issue tracker about that. Other webpack users have apparently gotten it to work in the past though by adding the node-loader option that you mentioned. I can't really help with this though.

**Comment by qishibo** [comment]
What's embarrassing is that if I uninstall cmake, it goes well though some warnings, but if I install cmake, things go bed.. :cry:
