### ISSUE TITLE
Handshake failed with digital envelope routines:INT_CTX_NEW:unsupported algorithm

### ISSUE THREAD

**Issue by fbx31** [mscdex/ssh2#1131]
Hello,
using sftp-promises package relying on ssh2 v1.5.0, nodejs v14.17.5. I face a strange issue.
Developping under windows, I succeed to connect (username, password, no key) to a RedHat machine with the following successfull handshake and communication
```
Socket connected
Remote ident: 'SSH-2.0-OpenSSH_7.4'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
**Handshake: KEX algorithm: curve25519-sha256@libssh.org**
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
**Handshake: Host key format: ssh-ed25519**
Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
**Handshake: C->S Cipher: aes128-gcm@openssh.com**
Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
**Handshake: S->C cipher: aes128-gcm@openssh.com**
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
**Handshake: C->S MAC: <implicit>**
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
**Handshake: S->C MAC: <implicit>**
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: none,zlib@openssh.com
**Handshake: C->S compression: none**
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: none,zlib@openssh.com
**Handshake: S->C compression: none**
Outbound: Sending KEXECDH_INIT
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
**Handshake completed**
```

Using the same source, packages and nodejs version but under linux pod in OpenShift, I failed to connect to the same RedHat machine.
Here is the trace 
```
Socket connected
Remote ident: 'SSH-2.0-OpenSSH_7.4'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
**Handshake: KEX algorithm: curve25519-sha256@libssh.org**
Handshake: (local) Host key format: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
**Handshake: Host key format: ecdsa-sha2-nistp256**
Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
**Handshake: C->S Cipher: aes128-gcm@openssh.com**
Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
**Handshake: S->C cipher: aes128-gcm@openssh.com**
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
**Handshake: C->S MAC: <implicit>**
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
**Handshake: S->C MAC: <implicit>**
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: none,zlib@openssh.com
**Handshake: C->S compression: none**
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: none,zlib@openssh.com
**Handshake: S->C compression: none**
Outbound: Sending KEXECDH_INIT
**Error: error:0609D09C:digital envelope routines:INT_CTX_NEW:unsupported algorithm** 
Socket ended
Socket closed
```
As you can see the negociation seems to work, the host key format selected is different between the 2 environments, but agreed on both sides.

I don't understand why I got unsupported algorithm on INT_CTX_NEW as all algorithms have been negociated...

Any idea, please Help
Thanks in advance,

**Comment by mscdex** [comment]
Probably the version of node in the problematic environment was compiled against a shared OpenSSL that has disabled one or more algorithms that the OpenSSL bundled with node ordinarily supports. Typically this would be much older algorithms, like the RC4 cipher for example, but based on the handshake details you've shown, I can't imagine why someone would build OpenSSL without support for the selected algorithms as they are fairly modern.

**Comment by fbx31** [comment]
Thanks for your answer, so if I follow you, the node version in OpenShift has been compiled with an OpenSSL lib without some algorithms that normally should be there.
OK I will go to my OpenShift admins to check and in parallel, I will try to identify which algorithms are missing on this environment.
Any source or link on how to check quickly which crypto algorithms are really working on a node version?
Thanks

**Comment by fbx31** [comment]
Hum, made a quick check with
`node -e "console.log(process.versions)" | grep openssl`
And yes, on my windows env: got openssl: '1.1.1k'
and on linx pod in OpenShift, got openssl: '1.0.2k',
Thanks

**Comment by mscdex** [comment]
For this specific handshake, to check for the ....

* KEX: `crypto.generateKeyPairSync('x25519')` should return an object with a private and public key
* Host key: `crypto.getCurves().includes('prime256v1')` should return `true`
* Cipher: `crypto.getCiphers().includes('aes-128-gcm')` should return `true`

> and on linx pod in OpenShift, got openssl: '1.0.2k',

What does the node version on that system show (in `process.versions`)?

**Comment by mscdex** [comment]
The last node.js version to bundle OpenSSL 1.0.2k was node v8.0.0.

**Comment by fbx31** [comment]
For process.versions, got this
{
  node: '14.17.5',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.0.2k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

**Comment by fbx31** [comment]
except openssl, all other versions are ok compared to windows version one.

**Comment by fbx31** [comment]
Last question: Waiting for a potential update on my node image built, what are the algorithms I can restrict to comply with openssl v1.0.2 to continue my tests ?

**Comment by mscdex** [comment]
Yeah that's a strange configuration. Typically organizations/distros that package a version of node.js with a custom OpenSSL version will use the same version bundled with node for compatibility but compiled with different flags for example. I believe that's why this hasn't been a problem much before.

This module was originally written back before people started doing such things so it was safe to make certain assumptions about what functionality was available (e.g. availability of certain ciphers). I've already been working on doing more runtime checks for various algorithms before making them available for SSH handshakes.

**Comment by mscdex** [comment]
> what are the algorithms I can restrict to comply with openssl v1.0.2 to continue my tests ?

There is no simple answer for that, especially given the custom OpenSSL build being used there. You will just have to manually check what is in `crypto.getHashes()`/`crypto.getCiphers()`/etc. and/or just try various configurations until I'm able to add more runtime checks.

**Comment by fbx31** [comment]
Succeed to find a list of cyphers for specific openssl v1.0.2k, I will have a close look and test.
One again, many thanks for your efficient support, you made my day!
Have a nice weekend.

**Comment by mscdex** [comment]
For future reference, it looks like this is what Openshift/Redhat may be using in this scenario to use such an old OpenSSL version with their node builds: https://github.com/sclorg/node-ssl-shim
