### ISSUE TITLE
Execute multiple commands through exec and stdin

### ISSUE THREAD

**Issue by M-Hoogie** [mscdex/ssh2#1135]
Hey! Sorry for asking a question that's probably been asked a lot of times, but I can't seem to find a definitive answer. I'm trying to create a small deployment script for our developers and they have some requirements regarding executing a command, and responding to that command. 

```javascript
 client.exec("ls -la", (err, stream) => {
        if (err) throw err;

        stream
          .on("data", function (data) {
            if (!data.toString().includes("my-dir")) {
              stream.write("mkdir my-dir");
            }
          })
          .on("close", function (data) {
            console.log("Stream closing: " + data);
            client.end();
          })
          .stderr.on("data", (data) => {
            console.log("STDERR: " + data);
          });
      });
```

This is a simplified version of the actions we want to do, but it approximates that we want to act the result of the first data returned. 

Unfortunately writing to the stream doesn't seem to execute another action. I thought this might be the stdin which i'm writing to, but no result.  

An alternative I'm looking into is the shell method, (which I got working) but then I need to handle the input being returned and error codes. So I was wondering if you have any tips and tricks that might help me forward. 

Thanks in advance (and for the library), and sorry if i'm missing something obvious 😅

**Comment by mscdex** [comment]
`exec()` is for executing one or more commands, like you would type at a shell prompt. When you write to the stream passed to your `exec()` callback, you're writing to the stdin of whatever process is running from your command string. This is similar to doing `ssh foo@example.org 'ls -la'` with the OpenSSH client.

`shell()` is for starting an *interactive* shell session, when is similar to doing `ssh foo@example.org` with the OpenSSH client. You get a shell prompt that you can type commands that get executed and when they finish, you get the shell prompt again.

So when you `stream.write('mkdir my-dir')` when `stream` comes from `client.exec('ls -la')`, you're sending the string 'mkdir my-dir' to the stdin of the `ls` program that's running, which doesn't do anything (`ls` probably ignores stdin).

If you want to execute multiple commands *interactively* you want `shell()`, if you want to execute multiple commands *non-interactively*, you will want `exec()` along with the appropriate shell syntax (e.g. `''ls -la && mkdir my-dir`). Both methods have their advantages and disadvantages (notably each `exec()` call is isolated and does not retain the environment or cwd from previous `exec()`s), but those are their intended use cases.

**Comment by M-Hoogie** [comment]
Great explanation, thanks for your time.
