### ISSUE TITLE
Question: Should I release the ssh connection manually?

### ISSUE THREAD

**Issue by childrentime** [mscdex/ssh2#1136]
I'm trying to implement a webssh. So I'll open many ssh connections in node,  when the browser is closed, they also run in nodes? So, do I need to send a request to the server to destroy the  ssh connect when the browser is closed? btw,  do these connections have unique identifiers, or do I have to identify them myself?

**Comment by mscdex** [comment]
> So, do I need to send a request to the server to destroy the ssh connect when the browser is closed?

It's up to you how/when you want to close them. As long as your node process is alive the ssh connection will stay open as long as nothing else severs that connection. Relying on a notification from the browser to reach the server when the tab/window is closed is probably not a good idea. You will probably need to include some fallback(s) in case you never receive those notifications for one reason or another.

> do these connections have unique identifiers, or do I have to identify them myself?

They're just normal javascript objects, like many things in javascript. If you need to reference/look up a particular connection by some identifier, that is up to you to handle.

**Comment by childrentime** [comment]
Thanks😘😘😘!
