### ISSUE TITLE
sftp connection path cache

### ISSUE THREAD

**Issue by Lee-42** [mscdex/ssh2#1137]
I tried connecting to a jump machine and it returned me the message below, and I could choose any machine to go in.

On the same sftp side, I call the readDir("/") method to return some links, and then I use the readDir("someLink") method to successfully enter the server's file directory.

But when I try to connect to sftp again, instead of returning so many connections, it goes directly to the directory I chose last time.

Then after a period of time, connect again, and return in the form of a link

Does anyone know what's going on here
I know this is a weird question

**Comment by mscdex** [comment]
I'm not sure if you've posted this issue in the wrong repository? `ssh2` doesn't have a GUI. If you're asking about code you've written that *uses* `ssh2`, you'd have to show me code that isn't working, what's actually happening, and what's expected.

**Comment by Lee-42** [comment]
I'm trying to connect the jump server, it manages multiple machines
This is my code, 
![code](https://user-images.githubusercontent.com/95179300/155957765-05802dcb-7928-4ee0-ad79-684e0a6c5bd3.jpg)
I just simply get the files in the "/" directory, the first time I run the code below, I get the link
<img width="453" alt="link" src="https://user-images.githubusercontent.com/95179300/155957826-8f9590fa-ebf8-4ea9-9a81-387718a1df28.png">
The second run of the code gets the folders and files
<img width="506" alt="dir" src="https://user-images.githubusercontent.com/95179300/155957843-632816a3-5599-4a3a-b7da-fe3c75f53a2c.png">

**Comment by mscdex** [comment]
The code you've shown makes a direct connection to a machine and does not use a jump server. The code itself and the resulting output looks fine to me. I don't know anything about the setup you have or what you're expecting to see. I'm guessing however there is more going on than just the code snippet you've shared (especially if there is a jump server being used).
