### ISSUE TITLE
please add a ChangeLog - and possibly include the change notes when tagging

### ISSUE THREAD

**Issue by GitMensch** [mscdex/ssh2#1138]
The main thing I've found so far was the [1.0 status update note](https://github.com/mscdex/ssh2/issues/935), otherwise only the [git log](https://github.com/mscdex/ssh2/commits/master).

To be able to quickly check what changed in earlier/current/upcoming versions a ChangeLog.MD would be most useful - for some notices why this is useful for repos even when there's a git log and with suggestions how to format / what to include there I suggest to have a look at https://keepachangelog.com .

When keeping an "unreleased" part and adding to it, there's also a nice summary that can be used during tagging - making the tag/release information also much more useful.

As an initial version there are a bunch of [npm tools available](https://www.npmjs.com/search?q=changelog) that I didn't try but they may help if the information isn't "somewhere else" (like announcements) already.

**Comment by mscdex** [comment]
As someone who single-handedly maintains several projects in their free time (which isn't much these days), about the only time I have for non-coding tasks like that is when there are major/breaking changes that people need to know about. On top of that, those kinds of changes are not very frequent for my projects, so it's a reasonable tradeoff.

These days I *do* try to publish releases frequently to get fixes in the hands of users, but I can't be bothered to write changelog entries for all of these quick changes for all of my projects. About the only thing I *could* provide would be a changelog containing git commits and messages, like node.js core does, but that's not very useful as someone can obtain that same information from the github web interface.

**Comment by billchurch** [comment]
Love all you're doing and appreciate your work. Something you may want to consider, which could be lightweight in the sense of maintenance, would be to adopt [Standard Version](https://github.com/conventional-changelog/standard-version). This generates changelogs dynamically based on commit messages. It doesn't need a lot of change to your workflow and could help to accommodate what's being asked for.

**Comment by mscdex** [comment]
Closing this for the reasons I previously mentioned.
