### ISSUE TITLE
Request to remove cpu-features.

### ISSUE THREAD

**Issue by cweijan** [mscdex/ssh2#1139]
Hi, your library has an optional dependency on cpu-features, but it will be installed during npm install, and an error will be reported if the node-gyp environment is not installed.

But users with node-gyp environment are few, now ssh2 works fine, I don't want to install node-gyp environment for this optional feature.
![image](https://user-images.githubusercontent.com/27798227/156517661-7c39d569-78f4-4f77-aff7-a4ea9130bca0.png)

**Comment by cweijan** [comment]
I saw the previous discussion, cpu-features is used to choose a better algorithm, is it possible to consider using other methods to choose an algorithm.

**Comment by mscdex** [comment]
> I don't want to install node-gyp environment for this optional feature

Then don't install it. `ssh2` is usable without the optional dependency.

**Comment by cweijan** [comment]
Hi sir, 
I have been troubled by this problem again recently, I think a possible way is to move cpu-feature to devDependencies, this will not have any effect on you, for ssh2 users, cpu-feature is now really become Optional dependencies.

**Comment by ArminEberle** [comment]
Just commenting that the cpu-features thingy is giving me a hard time as well, we are building an electron-app with electron-builder. 
The bad thing is that electron-builder does a cross-platform install but will not do yarn install --ignore-optional automatically. 
And the setup of the node-gyp environment is rather fragile. 
So for some developers, they can build the electron-app nicely on their windows-pc, others just won't. Like me.
So my attempt is to do the cross-platform yarn install on my own, but this is adding lots of additional build-code and has its own problem possibilities.

**Comment by cweijan** [comment]
To avoid this problem, I released a package with cpu-features removed, `@cweijan/ssh2`, if anyone suffers from this, you can use it: `npm i @cweijan/ssh2`
