### ISSUE TITLE
allow automated connection hoping

### ISSUE THREAD

**Issue by GitMensch** [mscdex/ssh2#1145]
Currently connection hoping needs to be implemented by each user of ssh2 who wants it, as outlined in #764.

Can you please extend the `connect()` method to allow multiple connection objects to be passed?

```ts
var tConn = new Client();
tConn.connect({
  host: '192.168.1.1',
  port: 22,
  username: 'username1',
  password: 'password1',
} , {
    host: '192.168.1.2',
    port: 22,
    username: 'username2',
    password: 'password2',
  });
```

This would create a new internal client from within tConn and connect via stream mode.
Calling tConn.close() would then trigger a check in tConn if it has an internal client and if yes close this connection first.

The nice thing here: it can also contain an unlimited numbers of connection configurations, each would "just" connect to the next index and have an internal connection until no more connections are setup.

Something similar is available with [ssh2-promise](https://www.npmjs.com/package/ssh2-promise#connect-to-ssh-server-via-hopping), but why use a wrapper if ssh2 could do it in the core?

**Comment by mscdex** [comment]
> why use a wrapper if ssh2 could do it in the core?

Because I don't want `ssh2` to be a kitchen sink module or to have to make decisions about how such extra features should be implemented (for example, someone may want to do connection hopping using `exec()` instead of `forwardOut()` because of remote server limitations). I would rather leave that to downstream modules.

**Comment by GitMensch** [comment]
Thanks for the explanation. Solved for me (and now anyone that comes back again has a chance to find that information, too).
And yes, in theory the connection configuration would need to have additional attributes.

Just out of interest: would you _consider_ to review and possibly include a PR if it is "minimal intrusive"?
