### ISSUE TITLE
undefined symbol: EVP_CIPHER_CTX_get_key_length

### ISSUE THREAD

**Issue by tassosblackg** [mscdex/ssh2#1149]
Working with nodejs `version 17.6.0`, I get the following error

> node: symbol lookup error: /home/user/code_api/node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node: undefined symbol: EVP_CIPHER_CTX_get_key_length

 and I don't manage to find any possible solution. What might be wrong?

the code trying to use is:
```
       const conn = new Client();
        conn.on('ready', () => {
            console.log('Client :: ready');
            conn.shell((err, stream) => {
                if (err) throw err;
                stream.on('close', () => {
                    console.log('Stream :: close');
                    conn.end();
                }).on('data', (data) => {
                    console.log('OUTPUT: ' + data);
                });
                stream.end('ls -l\nexit\n');
            });
        }).connect({
            host: 'remote-host-address',
            port: 22,
            username: 'user',
            password: 'some-password'

        });
```

OS: Manjaro Linux 21.2.4

**Comment by mscdex** [comment]
How did you install node? It sounds like your copy of node 17.x is using OpenSSL 1.x instead of 3.x.

**Comment by tassosblackg** [comment]
I've installed node using the 

`official repositories (community)`  

As for the `node -pe process.versions` output:

> {
>   node: '17.6.0',
>  v8: '9.6.180.15-node.13',
>   uv: '1.43.0',
>   zlib: '1.2.11',
>   brotli: '1.0.9',
>   ares: '1.18.1',
>   modules: '102',
>   nghttp2: '1.46.0',
>   napi: '8',
>   llhttp: '6.0.4',
>   openssl: '1.1.1m',
>   cldr: '40.0',
>   icu: '70.1',
>   tz: '2021a3',
>   unicode: '14.0
> }

**Comment by mscdex** [comment]
Can you try the master branch? I want to make sure things are fixed there now.

**Comment by mscdex** [comment]
I'm confident this is fixed in the master branch now. If you find out otherwise, let me know.
