### ISSUE TITLE
fastGet and fastPut SFTP client methods return `undefined` error if file has size 0

### ISSUE THREAD

**Issue by alex12058** [mscdex/ssh2#1151]
The `fastGet` and `fastPut` [SFTP client methods](https://github.com/mscdex/ssh2/blob/dfc5fc83eace815b3b7e49ea9b10059c934e0e91/SFTP.md) return `undefined` in the error callback if the file to upload or download has a file size of 0.

In the file [lib/protocol/SFTP.js](https://github.com/mscdex/ssh2/blob/master/lib/protocol/SFTP.js) this is the line that throws the error.
```js
if (fsize <= 0)
  return onerror();
```

**Comment by mscdex** [comment]
Can you describe the problem this is causing? If a file is zero length, then there's nothing else left to do but close the destination file. There is no error.

**Comment by alex12058** [comment]
Sure. Here is the code I am using to retrieve a file using `fastGet`.
```ts
await new Promise<void>((resolve, reject) => {
  this.sftp.fastGet(
    remote_path,
    local_path,
    {
      step: (bytes, _chunk, total) => {
        if (bytes === total) resolve();
      },
    },
    (error) => reject(error)
  );
}).catch((error) => {
  log.error(`Failed download ${remote_path} --> ${local_path}`);
  throw error;
});
```

If the error callback is called I reject and throw the first argument of the callback expecting it to be an error.

If the file has a non-zero length it works fine and the error callback is not called. If the file has no length then the error callback is called and the `error` argument of the callback is `undefined`.

**Comment by mscdex** [comment]
It's not an error callback, it's a final callback that is called when the transfer finishes, due to an error or not. You should be resolving/rejecting from that callback instead (based on whether an error was passed or not). The `step` callback is purely an opt-in, informational thing if you want to track the progress.

**Comment by alex12058** [comment]
Thanks mscdex.  I will change my code to use `error => error ? reject(error) : resolve()`.
