### ISSUE TITLE
If I call exec () nodejs many times in different functions, it will be slower and slower. How to solve it  I released the conn object with conn.end(). Did exec not release it    

### ISSUE THREAD

**Issue by lockingball** [mscdex/ssh2#1155]

**Comment by mscdex** [comment]
You'll have to explain more about what you mean by "slower and slower".

**Comment by lockingball** [comment]
> You'll have to explain more about what you mean by "slower and slower".

thank you ,i already fix it. ssh2 is no problem. i just forgote using the onload() when i using XMLHttpRequest.
