### ISSUE TITLE
SSH2 has not continued shell?

### ISSUE THREAD

**Issue by ohad99** [mscdex/ssh2#1163]
Hello,

I'm using conn.shell() and it's always reset the shell.
If I'm typing "cd .." to go to /home and then "ls -l" it brings me back to the home user folder (/home/boi)

![Screenshot_59](https://user-images.githubusercontent.com/103418417/163492601-31fe663c-db79-4434-b66a-c7f21d45f061.png)

**Comment by mscdex** [comment]
That's how all shells (that I'm aware of) operate. `conn.shell()` creates a new interactive shell session.
