### ISSUE TITLE
Fine Tuning SSH/SFTP Server

### ISSUE THREAD

**Issue by questiosn9832** [mscdex/ssh2#1165]
Hello, 

I was wondering how someone would be able to make configuration changes to the SFTP server/code. Is there a specific file I can edit that would be akin to an ssh config file so I can edit specific server values such as max sessions/connections/timeouts/ports/etc for when I run SFTP server?

**Comment by mscdex** [comment]
There are some things you can configure when [creating a server](https://github.com/mscdex/ssh2#server-methods), but most of what I believe you're after you will mostly have to implement in your own code.
