### ISSUE TITLE
SSH Multiplexing

### ISSUE THREAD

**Issue by nick-george** [mscdex/ssh2#1167]
Hi there, 

Does this library support SSH Multiplexing (e.g via ControlMaster & ControlPersist)? I noticed @mscdex mentioned multiplexing here (https://github.com/mscdex/ssh2/issues/436#issuecomment-224874396), but I don't see any mention of it in your docs or in the GitLab issues. 

If this feature is not currently supported by the library. Do you have an estimate of how much effort it would take to implement (if even possible)?

Many thanks,
Nick

**Comment by mscdex** [comment]
That sort of thing (along with many other OpenSSH features) is outside the scope of this module. You'll need to implement it yourself or find an existing module that already does.

**Comment by mscdex** [comment]
I should note that multiplexing at the SSH level most definitely already exists though, in that you can open as many channels as the server will allow (e.g. via `shell()`, `exec()`, `forwardOut()`, etc.).

**Comment by nick-george** [comment]
Thanks for the clarification @mscdex. 

We're definitely after the OpenSSH style multiplexing. Is it something you'd consider being paid to develop and add to this library? If so, it might be better to discuss further outside of this GitHub issue ticket. 

Cheers, 
Nick

**Comment by mscdex** [comment]
Unfortunately I'm not really interested in trying to reach complete feature parity with OpenSSH. Also like I said, I believe those sorts of features are best left to downstream modules. I prefer to keep `ssh2` more as a building block rather than an all-encompassing solution.

**Comment by nick-george** [comment]
OK, no problems and thanks @mscdex!
