### ISSUE TITLE
SFTP readdir() appears to only return owner & group IDs, not names

### ISSUE THREAD

**Issue by nick-george** [mscdex/ssh2#1169]
Hi there, 

It appears that this module returns returns only IDs for readdir() calls. The openssh sftp client returns usernames & group names (by default). From our previous discussions, I understand that you're not looking for feature parity with OpenSSH. However, is this information already being returned to this module and being discarded internally? If so, would it be possible to just include this additional information in some extra fields? 

I initially posted this question on the ssh2-sftp-client, not realising that it relied on this module. The question full question is here: https://github.com/theophilusx/ssh2-sftp-client/issues/409

Thanks again for your time. 
Nick

**Comment by mscdex** [comment]
Version 3 of SFTP only gives numeric values for user and group ownership of directory entries. However, the `longname` typically contains an `ls -l`-style listing for the file, which you may parse for user/group names if you want to go that route. All the usual cautions of parsing `ls` output apply though.

**Comment by nick-george** [comment]
Many thanks for this answer @mscdex!
