### ISSUE TITLE
SSH2 doesn't receive answer after exec with ERICSSON Router

### ISSUE THREAD

**Issue by RiadOkba** [mscdex/ssh2#1170]
Dear,

I'm testing ssh2 with Ericsson Router... the authentication is working but when sending a request via exec command, the debug shows a total silence! 
I tried the ssh2 (using the same piece of code) with linux and kubernetes access node. it worked just fine...

Here's the output from DEBUG:  
[log.txt](https://github.com/mscdex/ssh2/files/8546531/log.txt)

Here's how it is supposed to work from terminal session:
![image](https://user-images.githubusercontent.com/67765342/164887582-bfea570d-d207-4463-9856-8c2859599ea0.png)

I thought at first it's ssh protocol interoperability issue... but then the debug shows the auth is working and the silence comes after sending the command...

Any help is more than welcomed, it's literally 4 months of software development that would go down the drain if no fixe to my problem...

Regards

**Comment by mscdex** [comment]
Can you show the `ssh2` code you're using?

**Comment by RiadOkba** [comment]
Thanks for checking my question.

Here's the code (it's from the samples... I had created my own class which worked perfectly with Linux/Kubernetes but then seeing this problem with the router, I switched to a simple example) :

console.log('START!')

const { Client } = require('ssh2');

const conn = new Client();
conn.on('ready', () => {
  console.log('Client :: ready');

  setTimeout(()=>{
      console.log('timeout cleared!')
    conn.exec('show running-config swim', (err, stream) => {
        if (err) throw err;
        stream.on('close', (code, signal) => {
          console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
          conn.end();
        }).on('data', (data) => {
          console.log('STDOUT: ' + data);
        }).stderr.on('data', (data) => {
          console.log('STDERR: ' + data);
        });
      });
      console.log('exec done!')
  },2000)
  
})

conn.connect({ host: '10.223.183.131', port: 22, username: 'training', password: 'training', debug: (debug) => { console.log(debug) } });

console.log('END')

**Comment by mscdex** [comment]
My guess is either you need to set up a `pty` by passing a config object to `exec()` if the remote end is expecting a terminal *or* something I've seen on most routers and embedded devices is that they only support interactive shell sessions, in which case `exec()` won't work and you'll have to use `shell()`.

**Comment by RiadOkba** [comment]
Hello Again,

Unfortunately the shell didn't work... I can see the prompt message but not the output. I have joined the code I have used with the output...
[index.txt](https://github.com/mscdex/ssh2/files/8561470/index.txt)
[output.txt](https://github.com/mscdex/ssh2/files/8561482/output.txt)

Any advice is welcome... is there anything I can try? (I was thinking using c++ as external module but then realized ssh2 is already doing it. Right?)

Regards
Riad

**Comment by mscdex** [comment]
When using `.shell()`, try using `stream.write()` instead of `stream.end()`, otherwise the server may end up truncating the output since it saw that you requested to end the session immediately.

**Comment by RiadOkba** [comment]
I replaced stream.end with stream.write as suggested. It got me the same output as before : (

**Comment by mscdex** [comment]
You may also need to add a delay (or scan the output for an expected prompt) when using an interactive shell session before writing to the `stream` as the remote end may ignore some/all output until the prompt is first displayed.

**Comment by RiadOkba** [comment]
Thanks a million!!!
It is working now with the ssh2 module! as you have suggested I used setTimeout with a small delay... it worked :D

I will continue my software implement on electron.js, I'm guessing it will work just fine with "electron-ssh2" module...

Regards,
Riad
