### ISSUE TITLE
why?error: Unable to request X11

### ISSUE THREAD

**Issue by hktalent** [mscdex/ssh2#1174]
## why?error: Unable to request X11
my code:
```js
const conn = new SSH();
    socket.on('geometry', (cols, rows) => {
      termCols = cols;
      termRows = rows;
    });
    conn.on('x11', (info, accept, reject) => {
      const xserversock = new net.Socket();
      xserversock.on('connect', () => {
        const xclientsock = accept();
        xclientsock.pipe(xserversock).pipe(xclientsock);
      });
      // connects to localhost:0.0
      xserversock.connect(6000, 'localhost');
    });


conn.on('ready', () => {
      // X11
      conn.exec('xeyes', { x11: true }, (err, stream) => {
        if (err)
        {
          debugWebSSH2(err)
          return err;
        }
        let code = 0;
        stream.on('close', () => {
          if (code !== 0)
            console.log('Do you have X11 forwarding enabled on your SSH server?');
          conn.end();
        }).on('exit', (exitcode) => {
          code = exitcode;
        });
      });
}
```
<img width="606" alt="image" src="https://user-images.githubusercontent.com/18223385/166109328-44c715c8-defe-40cc-b857-359cda7358a1.png">

<img width="899" alt="image" src="https://user-images.githubusercontent.com/18223385/166109953-b2be2b0e-ea5b-4572-a846-14eed6e1c86e.png">

**Comment by mscdex** [comment]
Possibly because the X server is being strict with authentication and requires a specific `cookie` value. The `xauth` utility will help you with managing authentication with the X server, including listing existing credentials with their associated display number and protocol name. If the server is using strict authentication, you will need to set your `x11` property to an object containing values that are shown by `xauth`.

**Comment by hktalent** [comment]
@mscdex 
I use ssh -Y -X is ok
use web ssh
display
<img width="674" alt="image" src="https://user-images.githubusercontent.com/18223385/166113381-35fb9233-7e41-4c8d-9ed1-eb9b676de79f.png">

**Comment by mscdex** [comment]
I'm not sure what you mean by "web ssh", but you obviously need an X11 server wherever `ssh2` is connecting from. However, like I said before, you need to set the `cookie`, `protocol`, and `screen` in an object and set that as your `x11` property value when executing the remote command. You get those values (locally) from `xauth list`. The first column shows you the hostname and display/screen number (separated by a `:`), the second column shows you the `protocol`, and the third column is the `cookie`.

**Comment by mscdex** [comment]
I should also note that when you do `ssh -X -Y`, OpenSSH is literally performing that exact same step behind the scenes (executing `xauth list` and parsing the output).

**Comment by hktalent** [comment]
@mscdex It would be nice to provide a demo code for X11, including an example of the operation steps😂thanks

**Comment by mscdex** [comment]
You just execute "xauth list" locally and parse its output, passing the cookie, protocol, and screen number to `ssh2` as the `x11` option when you call `ssh.exec()`.

As far as including an example of this in the readme, I'd rather not as there are plenty of examples in there as it is that cover the most common scenarios. The API documentation should be sufficient for anything else. Specifically for X11, there is no single/correct answer for setting the cookie, protocol, and screen number, "xauth list" is just one of them and maybe the easiest.

**Comment by hktalent** [comment]
@mscdex 
ok, thanks a lot, although I didn't find an option to set in the code
x11 option is ExecOptions
```
export interface ExecOptions {
    /** An environment to use for the execution of the command. */
    env?: NodeJS.ProcessEnv | undefined;
    /** Set to `true` to allocate a pseudo-tty with defaults, or an object containing specific pseudo-tty settings. */
    pty?: true | PseudoTtyOptions | undefined;
    /** Set either to `true` to use defaults, a number to specify a specific screen number, or an object containing x11 settings. */
    x11?: boolean | number | X11Options | undefined;
}


export interface PseudoTtyOptions {
    /** The number of rows (default: `24`). */
    rows?: number | undefined;
    /** The number of columns (default: `80`). */
    cols?: number | undefined;
    /** The height in pixels (default: `480`). */
    height?: number | undefined;
    /** The width in pixels (default: `640`). */
    width?: number | undefined;
    /** The value to use for $TERM (default: `'vt100'`) */
    term?: string | undefined;
}

export interface X11Options {
    /** Whether to allow just a single connection (default: `false`).*/
    single?: boolean | undefined;
    /** The Screen number to use (default: `0`). */
    screen?: number | undefined;
}
```
Thank you very much again, this has pointed my security research in a new direction，like this：
xauth list

**Comment by mscdex** [comment]
I don't maintain typescript definitions, so it looks like that definition is outdated.
