### ISSUE TITLE
Problem executing local python script on remote SSH server using ssh2 based client

### ISSUE THREAD

**Issue by nick-george** [mscdex/ssh2#1180]
Hey there, 

I'm attempting to automate the execution of a local python script on a remote (openSSH) server using this library. To do this, I  run your exec() call without setting any pty options (so that python doesn't think we're starting in interactive mode). 

I then attempt to write the content of the python script over the connection using stream.write(). Please see code below: 

```
    conn.exec('/usr/bin/python3', function (err, stream) {
      if (err) {
        nsp_sock.emit('error', err);
        nsp_sock.disconnect();
        return errorLog(err);
      }
      const stdout_decoder = new StringDecoder('utf8');
      const stderr_decoder = new StringDecoder('utf8');
      stream.write(my_script_content);
      stream.write('\x04'); //Send EOT to indicate to python that the input has ended
    }
```
Unfortunately, I don't see anything come back out of the remote python program. I have verified through your debugging code that the correct data seems to be getting sent over the channel, so I'm a little unsure why the code isn't being executed. 

I understand that this probably isn't an issue with your code, but rather some kind of I/O issue with python (or the way I'm executing it). I'm happy to close the ticket if it's not something you're interested in investigating. 

Many thanks, 
Nick

**Comment by mscdex** [comment]
Perhaps python is expecting a tty. If so, you will need to enable that with `exec()`'s options.

**Comment by nick-george** [comment]
Thanks @mscdex. 

If I use the OpenSSH client and do this `ssh <remote_host> python3`. I end up in a mode where I can paste in a python script, then hit CTRL-D and then it executes. 

However, if I run the following so that I'm allocated a TTY. `ssh -t <remote_host> python3`

I then end up at the interactive version of python
```
$ ssh -t host python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
So it seems that python has code to detect whether or not it is running on an interactive shell, and if not, it's expecting to get the content of the script on STDIN. 

I am not familiar with the SSH spec, I'm currently sending CTRL-D (\x04) to try and close the stream after writing script over the channel. With your intimate knowledge of the SSH protocol, does that sound correct? Should I be sending some other sequence to trigger SSH/python that the end of the script has arrived? 

Many thanks for your thoughts and time, 
Nick

**Comment by mscdex** [comment]
I'm not familiar enough with python, so I'm not sure what else to suggest. Maybe try adding `stream.end()` to close stdin?

**Comment by nick-george** [comment]
OK thanks, will give that a go!

**Comment by nick-george** [comment]
Hi @mscdex. That was it, I didn't realise that stream.end() was a thing until you told me. 

Many thanks!
