### ISSUE TITLE
Inbound: CHANNEL_FAILURE (r:0)

### ISSUE THREAD

**Issue by ItzArty** [mscdex/ssh2#1185]
Hello, I completely new to ssh2 library and I just tried to use the code from npm to connect to my vps and try ssh2 out, well, it turns out, none of my 2 vps is willing, or rather, ssh2 is not willing to resolve a connection. I keep receiving this error:
```
Inbound: CHANNEL_FAILURE (r:0)
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: Unable to start subsystem: netconf

```
I dont see, how this could be an error on my side, is there anything I can do to fix this?

**Comment by mscdex** [comment]
Looks like your SSH connection is fine. Were you intentionally trying to start netconf or ?
