### ISSUE TITLE
Issue with running commands in SSH shell

### ISSUE THREAD

**Issue by akshaygh0sh** [mscdex/ssh2#1189]
I am currently writing code to develop a web-based terminal that SSH's to a device using socket-io and xterm.

I created a small demo by refactoring some of the "Start Interactive Shell Session" example code in this repo. I was just wondering how the commands actually get run, is it when the stream gets anything in stdin (i.e. something is written to stream.stdin)?

In my code, I write to stdin when I received a socket (command) from the client, but it seems like as soon as I do that, the command that was received just gets sent back to the client. Here is a snippet of the code that handles the data coming in and out of the sockets:

```
conn.shell((err, stream) => {
            if (err) {
                console.log('Error while initializing SSH Shell')
                return socket.emit('data', '\r\n Error while initializing SSH Shell')
            }

            // Run command
            socket.on('data', (data) => {
                console.log('Received command: \'' + data + '\'')
                stream.stdin.write(data)
            })

            stream.stdout.on('data', (d) => {
                console.log('Sent data to client' + d.toString('binary'))
                socket.emit('data', d.toString('binary'))
            })

            stream.on('close', () => {
                conn.end()
            })
        }).on('close', () => {
            socket.emit('data', '\r\n SSH Connection closed \r\n')
        }).on('error', (err) => {
            socket.emit('data', '\r\n SSH Connection error \r\n')
        })
})
```

**Comment by akshaygh0sh** [comment]
Here's an example of the kind of output I get when the user interacts with the front end (in this example I just typed ls from the front end once the SSH connection was made):

> Received command: 'ls'
Sent data to client ls

**Comment by mscdex** [comment]
That's just how interactive sessions/shells work. The input is echoed so you can see what input you typed made it to the server. It works just like if you were using a terminal locally (outside of ssh). Most shells typically have ways to disable echoing of input, but you probably shouldn't because with a true interactive session (someone physically typing at the keyboard) you'd want to see what you're typing.

**Comment by akshaygh0sh** [comment]
Shouldn't I also be receiving the output of the command though? Why am I only getting the command itself back? When I run a different version that just uses the VSCode terminal as the console with nearly identical code (obviously with no socket.io), I get the output of the commands as well.

**Comment by mscdex** [comment]
Sounds like a frontend/socket.io problem then if it works without socket.io.

**Comment by akshaygh0sh** [comment]
The problem is the output of the command doesn't even show up in a console.log() in the 
```
stream.stdout.on('data', (d) => {
        console.log('Sent data to client' + d.toString('binary'))
        socket.emit('data', d.toString('binary'))
})

```
snippet of code. The only thing that seems to show up is the echo of the command that the client sent. I don't see how this could be an issue with socket.io since the output isn't even logged to the console.

Also, when I make the initial SSH connection, I get the expected output upon connecting to the server sent to the client (i.e. the "welcome" message when successfully connecting to the server), indicating that the stream.on('data') listener does seem to be working in some cases.

**Comment by mscdex** [comment]
Are you missing the newline after your command? Typically that would be sent when the enter key is pressed (xterm.js sends this as you would expect, like other control characters IIRC).

**Comment by akshaygh0sh** [comment]
That was it! Thank you so much, such a silly mistake.
