### ISSUE TITLE
Max number of exec?

### ISSUE THREAD

**Issue by Minganie** [mscdex/ssh2#1190]
Is there a maximum number of .exec that can be called on one Client? I'm running a script and it seems to fail pretty consistently after ~70 calls to .exec. I keep the one Client and wait for every .exec (mostly test or ls commands) to finish before I call another. I can put code here if you need, but I thought I should ask about theoretical limits first.

Does it matter if I use the same client for .sftp? I also wait until the sftp operations are done before I start another sftp or exec operation.

**Comment by mscdex** [comment]
There is no artificial limit on `ssh2`'s side, it's instead entirely dependent on the server. For example, for OpenSSH servers, the *default* `MaxSessions`, which defines how many concurrent sessions per connection (one `exec()` uses one session), is 10.

**Comment by Minganie** [comment]
I see. Thank you for the clarification.

**Comment by Minganie** [comment]
You were exactly right, it will work indefinitely with .exec that I make sure are done before I start another. However, with sftp, it crashes after exactly 10 fastGet or createReadStream, even if I wait for the file to be downloaded or the stream to emit 'close'. (I start createReadStream with no options so autoclose should be true by default). Do I need/ Can I manually close sessions for sftp? Without closing the Client, that is.

**Comment by mscdex** [comment]
`ssh.sftp()` consumes one session, `sftp.*()` do not consume extra sessions as all SFTP requests are all within the same SFTP session.

Servers may implement limitations and restrictions in any part of the SSH/SFTP server. What "crash" are you encountering?

**Comment by Minganie** [comment]
I changed my implementation to save my client.sftp and reuse between calls. Now I can make 100 consecutive calls without open failure. Thank you so much for the help.
