### ISSUE TITLE
mv or cp api ?

### ISSUE THREAD

**Issue by Lee-42** [mscdex/ssh2#1191]
Is it a good idea to use exec to execute the mv command to implement the move operation that the ssh2 module does not implement

**Comment by mscdex** [comment]
SFTP already has a move command (`sftp.rename()`), unless you're looking for something else?

**Comment by Lee-42** [comment]
what about cp

**Comment by mscdex** [comment]
For a remote copy there's `sftp.ext_copy_data()`, but as it's an extended request it may not be implemented by the server. OpenSSH for example only started supporting it server-side with OpenSSH 9.0 (released on 2022-04-08).
