### ISSUE TITLE
running command as different user 

### ISSUE THREAD

**Issue by reidsneo** [mscdex/ssh2#1193]
Hello how do running command with different user?
Below is using typescript with will sleep for 1 second before virtually typing the password

```
conn.exec("sh -c 'sleep 1; echo p4ssw0rd' | /usr/bin/script -qc  'su -c 'whoami' - root '", (err, stream) => {
    if (err)
    {
        console.log(err);
    }else{
        stream.on('close', (code, signal) => {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
        }).on('data', (data) => {
            console.log('STDOUT: ' + data);
        }).stderr.on('data', (data) => {
            console.log('STDERR: ' + data);
        });
    }
});
```

it didn't return as expected
only return

`STDOUT: Password:`

which is working on other platform
for example PHP
`$sftp->exec('sh -c "sleep 1; echo p4ssw0rd" | /usr/bin/script -qc \'su -c "whoami" - root \'');`

would return

```
Password: 
root
```

Thanks!

**Comment by mscdex** [comment]
Your use of single quotes looks wrong in the /usr/bin/script command arguments.

**Comment by reidsneo** [comment]
> stream.write(\`sh -c 'sleep 1; echo p4ssw0rd' | /usr/bin/script -qc  'su -c '/tmp/whoami.sh' - root ' \n\`);

Ok this is working good, \n was missing though
