### ISSUE TITLE
Can't compile or run SSH2 module in a Node.js / Vue.js project

### ISSUE THREAD

**Issue by mbusch3** [mscdex/ssh2#1194]
I'm trying to create a Node.js / Vue.js app that will use the SSH2 code and have dozens and dozens of compiling errors. I've restarted with a completely clean app just to get the module working, and have the same errors.

I've used the standard Vue CLI to create a fresh app using ``` vue create ssh-app```
I've been using yarn to handle packages and dependencies, so added ssh2 with ``` yarn add ssh2 ```.

For reference, my entire "clean" app is a single file:

```
<template>
  <input type="text" v-model="username" /><br />
  <input type="password" v-model="password" /><br />
  <input type="text" v-model="ip" /><br /><br />
  <button @click="connectSSH">Connect SSH</button>
</template>

<script>

const { Client } = require('ssh2');

export default {
  name: 'App',
  data() {
    return {
      username: "admin",
      password: "password",
      ip: "8.8.8.8"
    }
  },
  methods: {
    async connectSSH() {
      let ssh = new Client();
      ssh.on('ready', () => {
        console.log("Client :: ready");
      }).connect({
        host: this.ip,
        username: this.username,
        password: this.password
      });
    }
  }
}
</script>

<style></style>
```
When I try to compile, I'm immediately met with 28 errors, mostly of the following type:
```
ERROR in ./node_modules/ssh2/lib/server.js 14:4-18
Module not found: Error: Can't resolve 'net' in 'C:\Code\ssh-2\node_modules\ssh2\lib'
```
Great, so there are dependencies that yarn missed. No biggie. I know how follow error instructions and I know how to Google. For all the errors that say there's a way to resolve them, I follow the instructions (including ``yarn add``ing all of the appropriate modules, like browserify-zlib), and for the rest, I follow Google and resolve with a 'false' value. I end up with a vue.config.js file that looks like this:
```
const { defineConfig } = require('@vue/cli-service')

module.exports = defineConfig({
  transpileDependencies: true,
  configureWebpack: {
    resolve: {
      fallback: {
        "zlib": require.resolve("browserify-zlib"),  // 28 -> 31 errors
        "util": require.resolve("util/"),           // 31 -> 27 errors
        "path": require.resolve("path-browserify"), // 27 -> 25 errors
        "assert": require.resolve("assert/"),       // 25 -> 20 errors
        "crypto": require.resolve("crypto-browserify"),  // 20 -> 16 errors
        "stream": require.resolve("stream-browserify"),  // 16 -> 11 errors
        "https": require.resolve("https-browserify"),  // 11 -> 12 errors
        "http": require.resolve("stream-http"),  // 12 -> 11 errors
        "url": require.resolve("url/"),           // 11 -> 9 errors
        "net": false,   // 6 errors
        "tls": false,   // 5 errors
        "fs": false,    // 2 errors
        "dns": false,   // 1 error
        "child_process": false  // FINALLY compiles!
      }
    },
  }
})
```
Well, now it compiles and I can view the app, but the page doesn't render because it's finding another error (in the browser console):
```
Uncaught ReferenceError: Buffer is not defined
    at eval (utils.js?aaee:7:1)
```
So there are references to Buffer in ```/ssh2/lib/protocol/utils.js``` that aren't handled in the code. More Googling leads me to providing plugins, and I update the vue.config.js file some more:
```
const { defineConfig } = require('@vue/cli-service')
const webpack = require('webpack');

module.exports = defineConfig({
  transpileDependencies: true,
  configureWebpack: {
    resolve: {
      fallback: {
        "buffer": require.resolve("buffer"),
        "child_process": false,
        ...
        "zlib": require.resolve("browserify-zlib")
      }
    },
    plugins: [
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      }),
    ]
  }
})
```
Next the following error from ```/ssh2/lib/protocol/zlib.js``` shows up in the browser console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'DEFLATE')
    at eval (zlib.js?96dc:7:1)
```
At this point, I have to admit my Google Fu has failed me, and assume I must be doing something fundamentally wrong with how I've set up the app or imported the SSH2 module. Is there a process or step that I've missed so that compiling and running the SSH code just magically works? Or how much farther do I need to go down the rabbit hole?

**Comment by mscdex** [comment]
`ssh2` is for node.js or similar environments (as noted in the [requirements section of the readme](https://github.com/mscdex/ssh2/blob/b294780a8d62463ce953012f8d393cfc990a2a63/README.md#requirements)). If you're trying to use it in a web browser context, you're on your own. At least natively, web browsers are still missing key features (as you noticed) to allow something like `ssh2` to work.

These days probably the most obvious missing feature is being able to make raw TCP connections. While there have been a [couple](https://wicg.github.io/direct-sockets/) of [different](https://www.w3.org/TR/raw-sockets/) potential standards for doing this in browsers, it's not entirely clear when we'll see either of them actually shipping in web browsers. I suppose node.js API-polyfilling projects could support it by using a server as a proxy for raw sockets, but at that point you may as well just do everything server-side :man_shrugging:

**Comment by mbusch3** [comment]
So I WAS doing something fundamentally wrong with how I set it up... Thank you so much for your quick response and very kind way of saying "read the requirements, doofus." I'll have a go from the Node.js side of the app and expect that things will go much smoother from there.

Thank you again!
