### ISSUE TITLE
[HELP] How to get parameter/body of POST on forward local connections 

### ISSUE THREAD

**Issue by SupianIDz** [mscdex/ssh2#1198]
I do a local port forward to the server, then the server makes a POST request with the data, how to get the POST data instead of Buffer ? in the example below I only get Plain Text mixed in with the header. I just want to get the data. Thank you

<img width="908" alt="Screen Shot 2022-07-08 at 21 06 43" src="https://user-images.githubusercontent.com/37969970/177997891-3f4af141-960b-45f8-a8a0-f4eafc8e5ca4.png">

```js
// @ts-ignore
import { AcceptConnection, Client, ClientChannel, RejectConnection, TcpConnectionDetails } from 'ssh2';

const client = new Client();

client.on('ready', () : void => {
    // TODO : make port configurable
    client.forwardIn('localhost', 1337, (error : Error | undefined, port : number) => {
        console.log(`Forwarding Inbound Connection To localhost:${ port }`);
    });
});

const headers : string[] = [
    'HTTP/1.1 200 OK',
    'Date: Thu, 7 Jul 2022 02:07:58 GMT',
    'Server: ForwardedConnection',
    'Content-Length: 0',
    'Connection: close',
    '',
    '',
];

client.on('tcp connection', (details : TcpConnectionDetails, accept : AcceptConnection<ClientChannel>, reject : RejectConnection) : void => {
    accept()
        .on('data', (data : Buffer) => {
            console.log(data.toString());
        })
        .end(headers.join('\r\n'));
});

client.connect({
    host: '123.45.67.89',
    port: 69,
    username: 'foo',
    password: 'barbaz'
});

```

**Comment by mscdex** [comment]
That's beyond the scope of this project. You will need to use an http parser to parse http messages.

`ssh2` just provides the underlying connection and deals with raw bytes. What you do with those bytes is entirely up to you.

**Comment by SupianIDz** [comment]
> That's beyond the scope of this project. You will need to use an http parser to parse http messages.
> 
> `ssh2` just provides the underlying connection and deals with raw bytes. What you do with those bytes is entirely up to you.

thanks for the help & new insight for me
