### ISSUE TITLE
Question: How to stablish connection object, then use it later

### ISSUE THREAD

**Issue by eliezercazares** [mscdex/ssh2#1199]
Hello,

As far as I am aware, node-ssh works with a promise, like:

```
ssh.connect({}).then(function() {
do mein thing
})
```

but I am using artillery io so I need to stablish the ssh connection and keep it open during tests execution, and call it from time to time programatically to log into a ssh server to get performance logs via ssh after each scenario execution and before it.

Is it possible to do something like:

```
class {
let objSshClient = ssh.connect({});

function whatevs() {
objSshClient.do({});
}
}
```

I would avoid creating multiple connections, which kills the ssh server.

**Comment by mscdex** [comment]
I can't speak for other modules, but for `ssh2`, you should just be able to keep the object around after creating it with `new`, as in the examples.

**Comment by jbuhacoff** [comment]
This works just like @mscdex wrote, you can create the object, connect, and reuse it. It's up to you to keep a reference to it wherever you need it, and for as long as you need it, and close the connection when you're done. I use `ssh2` and `node-ssh` in a tool that does exactly that, sending multiple commands to the server before closing the connection.
