### ISSUE TITLE
sshcrypto.node not found on Unix ? 

### ISSUE THREAD

**Issue by ClementValot** [mscdex/ssh2#1201]
My Node/ESM project makes use of a `ssh2` dependency through `ssh2-sftp-client`. 
It uses `rollup` as a bundler, with `rollup-plugin-natives` as a plugin to handle the native dependencies of ssh2 (optional dependency to `cpu-features` and direct dependency to `sshcrypto.node`).

The plugin scans the dependencies to .node files and moves them to the bundle. 

Now, the files are all correctly bundled on Windows and MacOS, but the bundling seems to fail on Unix machines (On Jenkins specifically), the plugin raises the warning `Plugin rollup-plugin-natives: my-jenkins-workspace/node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node does not exist`.
Indeed, a quick `ls -R` on node_modules/ssh2 shows the file tree structure is different on Windows, MacOS and Unix, notably `lib/protocol/crypto/build/Release` only contains folder `obj.target`, and no `sshcrypto.node` file, which subsequently cannot be found by `rollup-plugin-natives`.

I am not aware whether this is intended, thus cannot determine whether it is an `ssh2` issue or `rollup-plugin-natives` issue

**Comment by mscdex** [comment]
Probably the compilation failed for one reason or another. Either way, `ssh2` will work without it.

**Comment by ClementValot** [comment]
Thnks for the quick answer!

So, on Windows/MacOS, the bundling fails because the .node binary exists and rollup cannot read it as is, hence the need for the plugin that handles native files. 

But on Unix environments the .node file is not served in the ssh2 package (Which is not a problem since it is an optional dependency for ssh2 which defaults to another dependency). 
In the meantime, my bundler has put an explicit `require('sshcrypto.node')` which fails at runtime if the file is not present. 

Band-aid solution for me, and possible fix for `rollup-plugin-natives`, is wrapping the require in a try/catch
