### ISSUE TITLE
stdout return old data from the client 

### ISSUE THREAD

**Issue by itzikorfa** [mscdex/ssh2#1202]
Hi,
I run several commands to different VMs using the SSH2 module.
The issue is that sometimes I get in the STDOUT outputs from previous commands and not as expected; how can I get the output of the command I run and not leftovers?

waiting for your answer 
Izia

**Comment by mscdex** [comment]
Perhaps you're reusing a variable? It's hard to say.

**Comment by billchurch** [comment]
Would be helpful to see your code. I'm using this module on a project that sees thousands of sessions and I've not come across this myself.

**Comment by theophilusx** [comment]
Sounds suspiciously like buffered data not being flushed from an output
stream before the next command?

Really need to provide a minimal script which reproduces the issue in
order to help diagnose.
