### ISSUE TITLE
ClientChannel get each command's character at `onData` event

### ISSUE THREAD

**Issue by zWingz** [mscdex/ssh2#1203]
I want to proxy the ssh, but when I write data to target, I would get prev command at `onData` event
<img width="697" alt="image" src="https://user-images.githubusercontent.com/13031838/184268385-cda4a8ca-adbf-411e-ad2d-82e32697f54c.png">
<img width="341" alt="image" src="https://user-images.githubusercontent.com/13031838/184268191-689c242d-a33a-4c70-b879-5d2bf6d94152.png">

<img width="268" alt="image" src="https://user-images.githubusercontent.com/13031838/184268343-d56a4de0-3124-461c-8610-86156871de50.png">

one message from sock will be split to multiple, debug on `crypto.js`
<img width="163" alt="image" src="https://user-images.githubusercontent.com/13031838/184276428-433397e0-3892-4ac3-a758-ed4306342ac7.png">

**Comment by mscdex** [comment]
That's just the nature of interactive sessions (`shell()`). Your input is echoed back by default by the server. You can disable remote echoing by setting the `ECHO` terminal mode to `0` when starting the shell session:

```js
client.shell({ modes: { ECHO: 0 } }, (err, stream) => {
  // ...
});
```

**Comment by zWingz** [comment]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/13031838/184279216-e444d6ab-9bdc-4111-a3ac-1d86fb8f8199.png">


It seem doesn't work
<img width="211" alt="image" src="https://user-images.githubusercontent.com/13031838/184279202-155c8291-f42a-4d6b-939a-4fafac6535ae.png">

**Comment by mscdex** [comment]
I don't know what you're logging, as it's not shown in the code you've posted thus far. It certainly works for me though.

**Comment by zWingz** [comment]
Is this expected behavior?
<img width="264" alt="image" src="https://user-images.githubusercontent.com/13031838/184280961-f0b35fe7-ed29-4369-8115-e1932e7ce13b.png">

**Comment by zWingz** [comment]
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/13031838/184281102-92a0f1a1-ef8c-4426-9dcf-63614de02e47.png">

**Comment by mscdex** [comment]
No, but then again I don't know what your code is doing. Here is my example that connects to a Linux SSH server:

```js
const { Client } = require('ssh2');

const client = new Client();
client.on('ready', () => {
  client.shell({ modes: { ECHO: 0 } }, (err, stream) => {
    if (err) throw err;
    process.stdin.unref();
    process.stdin.pipe(stream.stdin);
    stream.stdout.pipe(process.stdout);
    stream.stderr.pipe(process.stderr);
    stream.on('close', () => {
      client.end();
    });
  });
});
client.connect({ ... });
```

**Comment by zWingz** [comment]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/13031838/184281508-aebb08e4-3835-412c-8416-0bd1998b04c5.png">

**Comment by mscdex** [comment]
Peppering logging statements in `ssh2` like that isn't very reliable especially since you're proxying and dealing with two different sides. The logging statements don't indicate which side they're dealing with.

**Comment by zWingz** [comment]
```js
new Server({
  hostKeys: [readFileSync('host.key')],

}, (client) => {
  console.log('Client connected!');
  client.on('ready', () => {
    console.log('Client authenticated!');
    client.on('session', (accept, reject) => {
      const conn = new Client();
      conn.connect({})
      const session = accept()
      session.on('shell', (accept) => {
        const sessionStream = accept()
        conn.on('ready', () => {
          conn.shell({
            modes: {
              ECHO: 0
            }
          }, (err, stream) => {
            stream.pipe(sessionStream)
            sessionStream.pipe(stream)
          })
        })
      })
    });
  }).on('close', () => {
    console.log('Client disconnected');
  });
}).listen(4545, '0.0.0.0', function () {
  console.log('Listening on port ' + this.address().port);
});

```
I want to use ssh2 to make a `ssh-proxy-server`

**Comment by mscdex** [comment]
> the left is connect by your example code, right is connect by natvie ssh-client

Perhaps your SSH server ignores terminal modes then.

**Comment by mscdex** [comment]
You could also do `stream.stdin.write('stty -echo\n');` which achieves the same thing, but you will see the stty command echoed back.

**Comment by zWingz** [comment]
> > the left is connect by your example code, right is connect by natvie ssh-client
> 
> Perhaps the SSH server you're proxying to ignores terminal modes then.

you're right. I change a server and It work.. thanks

<img width="395" alt="image" src="https://user-images.githubusercontent.com/13031838/184282460-4bcfd7b1-4d52-4368-9fe2-c20afa531075.png">
