### ISSUE TITLE
session.pipe/stdin/stdout is undefined

### ISSUE THREAD

**Issue by zWingz** [mscdex/ssh2#1204]
The session was defined as `Duplex`, but I can't get `pipe`, `stdin` and `stdout` at runtime.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/13031838/184285066-1192a0a3-e8cd-4a35-8b7d-fa9593d8399c.png">

<img width="238" alt="image" src="https://user-images.githubusercontent.com/13031838/184285079-d43ff870-0e0f-45e0-ab0d-eab4426f4994.png">

**Comment by mscdex** [comment]
The session is not a duplex stream. However some requests that occur *within* the context of a session can create streams (e.g. `exec`, `shell`, and `subsystem`). You can see an example of that from the code you posted in https://github.com/mscdex/ssh2/issues/1203.
