### ISSUE TITLE
sshcrypto.node:1:2 - Error: Module parse failed: Unexpected character '�' (1:2)

### ISSUE THREAD

**Issue by ChristianSchwarz** [mscdex/ssh2#1213]
using "ssh2": "1.11.0"

When I build my electron app I get the following errors:

```
./node_modules/cpu-features/build/Release/cpufeatures.node:1:2 - Error: Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

./node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node:1:2 - Error: Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

How to solve it? Whats wrong here?

**Comment by mscdex** [comment]
I don't use webpack, so I can't really help you with that. If I had to guess though, perhaps webpack has a configuration setting that you need to enable or tweak to support addons in one way or another. A quick google search reveals [this webpack module](https://webpack.js.org/loaders/node-loader/) which may be of use.

**Comment by ChristianSchwarz** [comment]
@mscdex I fixed my issue by uninstalling "Microsoft Visual C++ 2015-2022 Redistributable".  Now on "npm i" the compilation shows error, thus the optional dependencies are not build. That doesn't seem to be a problem, the app builds again, without problems.

**Comment by worksofliam** [comment]
Moral of the story for this issue:

1. Either don't have the compilers installed and the install process won't build the binaries
    * https://github.com/mscdex/ssh2/issues/1213#issuecomment-1240549359
2. Ignore the binaries from the webpack build
    * `new webpack.IgnorePlugin({ resourceRegExp: /(cpu-features|sshcrypto\.node)/u })`

**Comment by PedroS11** [comment]
I was facing the same issue, installing node-loader and adding it to my webpack fixed this error. For reference, i followed this link https://webpack.js.org/loaders/node-loader/
