### ISSUE TITLE
Empty catch {} block causing issues with babel.

### ISSUE THREAD

**Issue by keating99** [mscdex/ssh2#1216]
Hi all,

I'm just wondering if anyone else has come across the issue with babel and webpack where the ssh2 module doesn't parse because of catch {} littered throughout the code? 

One example of this is: 
```
Module parse failed: C:\Users\...node_modules\ssh2\lib\client.js Unexpected token (315:16)
[0] You may need an appropriate loader to handle this file type.
[0] |         try {
[0] |           sock.end();
[0] |         } catch {} << this is the offending line of code 
[0] |       },
```

Maybe there is a babel plugin that deals with this issue? I can't seem to work it out, I'd imagine this is a fairly common issue that I have yet to find a solution for. 

Any help or pointers from anyone out there would be great. Thanks

**Comment by mscdex** [comment]
You're better off asking on the appropriate webpack or babel forum/issue tracker. This particular syntax is supported by the minimum version of node required by `ssh2` (node v10.16.0 as of this writing).
