### ISSUE TITLE
remove "test" folder from release package

### ISSUE THREAD

**Issue by Lock128** [mscdex/ssh2#1217]
Hi team

we are using this node package and during a security scan (AquaSec) the private keys that are part of the "test" folder have been flagged as sensitive data.

With this issue I would like to ask you to exclude the "test" folder from the "release package".

Is that possible?

Regards
Johannes

**Comment by theophilusx** [comment]
Sorry, please ignore my previous message. Was looking at a different
issue and replied to the wrong message!

For what it is worth, I agree the test directory should be added to a
.npmignore so that it is not included in the package pushed to npmjs.com

**Comment by theophilusx** [comment]
I think you may have the wrong project repository. This is the mu (mail
utils) and mu4e (Emacs mail client) project, not a node package project.

Perhaps your looking for https://github.com/apparatus/mu ?

**Comment by sasha-arrabi** [comment]
I opened a PR to add an exclusion for the `test` and `examples` folders from being published: https://github.com/mscdex/ssh2/pull/1306

**Comment by anumalasri** [comment]
Without any reason, its very absurd to push test file with all PEM, KEY Files.    

Hope there will be an alternative to this package.
