### ISSUE TITLE
cpu-features isn't really optional. Can you create a branch without it?

### ISSUE THREAD

**Issue by SVVSD-Woods** [mscdex/ssh2#1219]
I've tried just about everything, except hacking the package.json and removing the optional dependencies. I have a large project and installing it with 'npm install --omit=optional' causes other packages to break because apparently their "optional dependencies" are not optional either.

This seems to be a frequent request, so I'm just adding my support for it.  I've spent too much time today trying to get the 1.11.0 version to install, and going back to 0.8.9 causes deprecation issues with Buffer.

Thanks for considering...

**Comment by mscdex** [comment]
If your package manager is failing to install `ssh2` because the optional dependencies are failing to install, the problem is with your package manager and not `ssh2`. `ssh2` works just fine if the optional dependencies cannot be installed.
