### ISSUE TITLE
How to get the port of Remote Forwarding

### ISSUE THREAD

**Issue by zWingz** [mscdex/ssh2#1224]
`ssh -R port1:localhost:port2 host1`
Hot to get the `port1`

**Comment by mscdex** [comment]
See [this example](https://github.com/mscdex/ssh2#forward-local-connections-to-port-8000-on-the-server-to-us), where `port1` would be 8000. The example listens on that port on 127.0.0.1 on the remote server and forwards incoming connections to the client (via the `tcp connection` event).

**Comment by mscdex** [comment]
Also, if you're referring to the server side, that would be listening for the [`'request'` event on the client connection object](https://github.com/mscdex/ssh2#connection-events) and reading the `bindPort` from the `info` argument.

**Comment by zWingz** [comment]
thanks
