### ISSUE TITLE
how to end SSHTTPAgent?

### ISSUE THREAD

**Issue by alanhg** [mscdex/ssh2#1225]
When I start an SShHTTPAgent, it's alive, I wonder how to end the agent.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/9245110/194990837-8aeaa2f0-4f24-4b67-b1d3-38b893ea28ae.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/9245110/194990865-b4a84dbc-8229-489d-8420-9ebf5b3af3ee.png">

**Comment by mscdex** [comment]
SSH client connections are created only when needed and they automatically disconnect when node closes the underlying "socket"/stream.

If you want to forcefully close any open "sockets"/streams used by the agent, you can use [`agent.destroy()`](https://nodejs.org/docs/latest/api/http.html#agentdestroy) and any other standard agent APIs.

**Comment by alanhg** [comment]
Solved, thank you.

**Comment by alanhg** [comment]
> SSH client connections are created only when needed and they automatically disconnect when node closes the underlying "socket"/stream.
> 
> If you want to forcefully close any open "sockets"/streams currently in use by the agent, you can use [`agent.destroy()`](https://nodejs.org/docs/latest/api/http.html#agentdestroy) and any other standard agent APIs.

meanwhile, is any method to execute the command by the agent, for example, I want to stop any service,  if so, I don't need to create another connection.

**Comment by mscdex** [comment]
No, the agents are just for sending HTTP/HTTPS requests.

**Comment by alanhg** [comment]
> 

ok, tks.
