### ISSUE TITLE
How i can create a SFTP server? 

### ISSUE THREAD

**Issue by StreamerYT** [mscdex/ssh2#1233]
I tried to use this code, but when connecting, the client gives an error.

```ts
        SFTPWrapper.on('READDIR', async (reqId, buf) => {
            const handleId = parseInt(buf.toString())
            const dir = handles[handleId] as (undefined | fs.Dir)
            if (!dir)
                return SFTPWrapper.status(reqId, ssh2.utils.sftp.STATUS_CODE.FAILURE)
            console.log(`_READDIR`, { handleId })

            try {
                for await (const dirent of dir) {
                    const stat = fs.statSync(dirent.name)
                    SFTPWrapper.name(reqId, [
                        {
                            filename: dirent.name,
                            longname: `drwxr-xr-x  56 nodejs nodejs ${stat.size} Nov ${stat.mtime.getDate()} ${stat.mtime.getFullYear()} ${dirent.name}`,
                            attrs: {
                                mode: stat.mode,
                                size: stat.size,
                                uid: stat.uid,
                                gid: stat.gid,
                                atime: +stat.atime,
                                mtime: +stat.mtime
                            }
                        }
                    ]as any)
                }
                return SFTPWrapper.status(reqId, ssh2.utils.sftp.STATUS_CODE.EOF)
            } catch {
                return SFTPWrapper.status(reqId, ssh2.utils.sftp.STATUS_CODE.FAILURE)
            }
        })
```

**Comment by mscdex** [comment]
As I said in https://github.com/mscdex/ssh2/issues/1229, you can only respond to a request *once*.

In this code you're showing, you're responding multiple times again: once per iteration of your for loop, and then again after the for loop.

You will need to somehow maintain state between a client's SFTP requests to know what to respond with at any given moment. For READDIR, this means either sending back one or more directory entries (a single array at a time, not multiple `name()` calls) *or* a status (indicating error *or* EOF -- meaning there are no more entries).

If you want the client to be able to get a list of files on the server's local disk, one way to do it would be to call `fs.opendir()` for OPENDIR SFTP requests, then `dir.read()` for READDIR requests, and then `dir.close()` for CLOSE requests. For READDIR specifically, you can `dir.read()` one or more times and then call `name()` *once* with an array containing all of the entries you read *or* you can call `status()` with EOF if `dir.read()` returned `null`.
