### ISSUE TITLE
can't handle "Your account has expired; please contact your system administrator" Error

### ISSUE THREAD

**Issue by nadimgeagea95** [mscdex/ssh2#1234]
The account i'm using to connect to a certain remote host has expired (Your account has expired; please contact your system administrator).

i'm using "try catch" to handle errors as follows,

    try {
        commandResult = await ssh.exec(command) 
    } catch (error) {
        console.log(error);
    }

When i log the error, it shows as null.

Is there a better way to handle this error and know when my account has expired.

**Comment by mscdex** [comment]
I feel like you may have posted this to the wrong project issue tracker. `ssh2` only exposes callback-based APIs, so you would have needed to pass a callback to `exec()` and attaching some stream event handlers instead of using `await` in order to get any kind of output.
