### ISSUE TITLE
ssh client num is equal to agent socket num?

### ISSUE THREAD

**Issue by alanhg** [mscdex/ssh2#1236]
now I create HTTP-SSH agent as a proxy. and visit server-local-web.

I'm a bit confused about how to set it up the agent config.

![image](https://user-images.githubusercontent.com/9245110/202466001-c8cd9186-17d9-4bb7-bb2a-8e4d0d0dc186.png)

## version info
- ssh2@1.11.1
- node@12.18.3

**Comment by mscdex** [comment]
The first object is what you'd ordinarily pass to `connect()`. The second object should contain [properties to be passed to node's `http.Agent` constructor](https://nodejs.org/docs/latest/api/http.html#new-agentoptions).

**Comment by alanhg** [comment]
Thanks, my doubt is max sockets setting, for example maxSockets.

I know it's agent-config.

**Comment by mscdex** [comment]
As to why the server is rejecting the channel open requests, if you're using the bundled HTTP(S) Agent implementation, it could be that the server has limits in place by IP, by user, some combination thereof, or something else entirely.

**Comment by alanhg** [comment]
> > if I set maxSockets as 5, ssh-http-agent will create 5 ssh connection?
> 
> The bundled HTTP(S) Agent implementation will create a new SSH client connection for every new socket that node.js asks for.
> 
> > I looked at the error and found that the connection failed, so I was curious about what this is for
> 
> What you've highlighted in the first screenshot is the server sending a success response to the hostkeys-00 request.
> 
> In the second screenshot it's just the server responding to the keepalive request. For SSH keepalive requests it doesn't matter whether it fails or not, the intent there is to just provoke a response from the server to know the connection is still alive.

thank you.
Curious where do you see that it's for keepalive requests. the second screenshot.

**Comment by alanhg** [comment]
> I have to forward request ws and http by http-agent.  


I tried the http-agent again, but found another error

Do you know reason 2 meaning? and for why? I don't know if it's http-agent-error or not.

![image](https://user-images.githubusercontent.com/9245110/202515607-126afa79-9dae-4c40-a387-7c395bf2d3c3.png)
![image](https://user-images.githubusercontent.com/9245110/202515752-272567b9-5f4a-4ed8-aeb9-960fcc68c426.png)

**Comment by mscdex** [comment]
> Curious where do you see that it's for keepalive requests

`REQUEST_SUCCESS`/`REQUEST_FAILURE` should always be matched to the previous `GLOBAL_REQUEST`.

> Do you know reason 2 meaning? and for why? I don't know if it's http-agent-error or not.

I don't know either. Perhaps your logging library is stripping message or other information?

**Comment by mscdex** [comment]
I can't really help you there. You'll need to do some debugging with whatever websocket library you're using.

As far as the screenshot goes, the other side ("inbound") is closing the connection.

**Comment by alanhg** [comment]
Okay, thank you very much, I'll look into it again.
