### ISSUE TITLE
How to bind input an output?

### ISSUE THREAD

**Issue by hytkilo** [mscdex/ssh2#1237]
I want to create a terminal like this. Now it can work, but I want to achieve `one command bind its replies`, because of some commands like `top` need to dynamically update the contents or control the keyboard in the bubble. how to do?
![1668821249576](https://user-images.githubusercontent.com/20276393/202827548-a6222a3a-4068-4560-ba19-4605b75ca5dc.jpg)

**Comment by mscdex** [comment]
Beyond calling `exec()` to execute a command and get its output, there's not much else I can suggest as anything program-specific is outside the scope of this project. If you're trying to handle arbitrary command execution along with interactive programs, it'll be up to you to implement things like command execution timeouts and handling terminal emulation.
