### ISSUE TITLE
The program keeps crashing on connection.

### ISSUE THREAD

**Issue by wonkyungup** [mscdex/ssh2#1238]
![스크린샷 2022-11-19 오후 10 35 47](https://user-images.githubusercontent.com/34180230/202854133-071f00cc-b26e-4530-9317-517874145d01.png)
![스크린샷 2022-11-19 오후 10 51 07](https://user-images.githubusercontent.com/34180230/202854137-ddf2bb67-da33-4d5a-907a-e3337651deab.png)
![스크린샷 2022-11-19 오후 10 51 13](https://user-images.githubusercontent.com/34180230/202854138-1fafbb58-c928-439b-b4fc-0ad7b0a86fad.png)

Connecting and stopping the port works normally, but an error occurs when the port is used. How do I debug?

**Comment by mscdex** [comment]
The code you're referencing appears to have nothing to do with `ssh2`? I don't see `ssh2` in the stack trace either. Perhaps it's a problem with vue or in a bundler (e.g. webpack) if you're trying to use `ssh2` in the browser/browser-like environment?

**Comment by wonkyungup** [comment]
@mscdex I solved it thanks for your hint. thank you
