### ISSUE TITLE
request often pending by httpagent.

### ISSUE THREAD

**Issue by alanhg** [mscdex/ssh2#1241]
somtimes, 502,504 or 404. sometimes is ok.

I use httpAgent to proxy visit code-server-web. I found it's instability. some request report 404,502,504.

but I visit localhost on the target machine. it's ok.

```js

...
new HTTPAgent({
      keepaliveInterval: 30000, // 心跳间隔，毫秒
      keepaliveCountMax: 200, // 心跳次数，毫秒
      readyTimeout: 20000, ...connectOpts,
    }, {
      keepAlive: true, keepAliveMsecs: 30000, maxSockets: 5, maxFreeSockets: 5, timeout: 20000, localPort: 0,
    });

...



        const response = await axios({
          headers,
          baseURL: `http://${codeServerProxifier.host}`,
          method: ctx.method,
          url,
          data: ctx.request.body,
          httpAgent,
          proxy: false,
          maxRedirects: 0,
          responseType: 'arraybuffer',
          decompress: false,
          params: ctx.request.query,
        });

```

## version 
- ssh2@1.11.1
- axios@1.2.0

**Comment by mscdex** [comment]
If you're receiving HTTP responses, there's nothing else `ssh2` can do as all it does is provide the underlying connection for the HTTP request when node asks for one. Perhaps there is something wrong with the HTTP server or with the HTTP request (e.g. headers, url, etc.).

**Comment by alanhg** [comment]
pending has noting to with httpAgent?

![image](https://user-images.githubusercontent.com/9245110/204856729-67c945fc-7925-4ee2-adbc-4f7f3e99dbe2.png)



localhost is ok, but request by agent, pending or 4xx, 5xx .

**Comment by mscdex** [comment]
All I can suggest is try to debug from node's side (e.g. setting `NODE_DEBUG=http`) and from `ssh2`'s side (perhaps by setting `debug` for each created connection). You could also retry the "pending" requests using different HTTP clients (e.g. curl) to make sure nothing in your browser is blocking the connection for some reason.

**Comment by alanhg** [comment]
I have some clues.

I found if I set keep alive false, it's ok. 

If I set to keep alive ture, always pending when I refresh webpage.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/9245110/213393898-a3f77767-1192-49fc-9840-f00ceeecfea9.png">

So I don't why.
