### ISSUE TITLE
How to pass standard input to a script

### ISSUE THREAD

**Issue by nikolayg** [mscdex/ssh2#1244]
I'm trying to use the library to call a script `test.sh` on a remote SSH server. It reads from the standard input as follows:

```bash
#!/bin/bash
echo "Hello please enter a value:"
read value
echo "You just entered '${value}'"
echo "Please enter another value:"
read value
echo "You just entered '${value}'"
echo "End!"
```

How can I programmatically pass a string to the input?

**Comment by mscdex** [comment]
It works much like node's `child_process.spawn()`. You just write to the process's stdin. `read` expects a newline, so you'll need that for `read` to return.
