### ISSUE TITLE
Error when installing ssh2 with Typescript

### ISSUE THREAD

**Issue by LinirZamir** [mscdex/ssh2#1246]
I tried installing ssh2 on my webserver, but I kept gettign errors. After a lot of tries I managed to duplicate the issue on a fresh environment using Node 18.12.1 and npm 9.2:

- Install a new react typescript website using `npx create-react-app my-app --template typescript`
- Install the ssh2 package using `npm i ssh2`
- Add this code to 'App.tsx' file: 
```
const { Client } = require('ssh2');
const conn = new Client();
```
Then when I try to run with `npm start` I am getting a lot of errors most of them are ` ...Can't resolve 'XXXX' in...` with packages such as assert, stream, fs, and more.. 

Here is a short snippet from the errors I get

```
Module not found: Error: Can't resolve 'assert' in 'E:\ProjectsAI\testingapp\node_modules\asn1\lib\ber'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
ERROR in ./node_modules/asn1/lib/ber/reader.js 3:13-30
Module not found: Error: Can't resolve 'assert' in 'E:\ProjectsAI\testingapp\node_modules\asn1\lib\ber'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }

ERROR in ./node_modules/asn1/lib/ber/writer.js 3:13-30
Module not found: Error: Can't resolve 'assert' in 'E:\ProjectsAI\testingapp\node_modules\asn1\lib\ber'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }

ERROR in ./node_modules/safer-buffer/safer.js 5:13-30
Module not found: Error: Can't resolve 'buffer' in 'E:\ProjectsAI\testingapp\node_modules\safer-buffer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
```

**Comment by mscdex** [comment]
This isn't an `ssh2` issue but a webpack issue as seen by the error messages. You will need to follow the recommendations given by the messages.

`ssh2` is designed for node.js. If you try using it in other environments (or by bundlers that aren't node.js-aware), you will most likely need polyfills and such to recreate missing APIs and such, hence the messages you're getting.

**Comment by zhijianglee** [comment]
I am facing the same issue too, and have resolved those polyfills issue

except for these 

WARNING in ../node_modules/ssh2/lib/protocol/constants.js 6:12-35
Module not found: Error: Can't resolve 'cpu-features' in 'C:\Users\1568568\OneDrive - Standard Chartered Bank\Documents\work\TestReactApp\node_modules\ssh2\lib\protocol'

WARNING in ../node_modules/ssh2/lib/protocol/crypto.js 34:12-60
Module not found: Error: Can't resolve './crypto/build/Release/sshcrypto.node' in 'C:\Users\1568568\OneDrive - Standard Chartered Bank\Documents\work\TestReactApp\node_modules\ssh2\lib\protocol'

**Comment by mscdex** [comment]
@zhijianglee You'll need to figure out how to get whatever tooling you're using to support compiled addons, which is what those two references are. Otherwise you can just ignore them as they are both technically optional addons.

**Comment by zhijianglee** [comment]
Some context here: I am using React with Typescript, attempting to sftp into a sever to download some logs

 The documentation claimed that there are optional addons, However, the error actually blocked the app from running. 

import SSH from 'ssh2'

const conn = new Client();  // When I remove this line the error gone and the app appears to be working again. 


So, those are NOT OPTIONAL ADDONS

Unfortunately based on current information I have, I am in the dark on how should I proceed

**Comment by mscdex** [comment]
@zhijianglee They are [definitely](https://github.com/mscdex/ssh2/blob/fb1aa6f527a1a4460cc6e608722b5194bf7b1c33/package.json#L19) [optional](https://github.com/mscdex/ssh2/blob/1aee6c055d9e6219f2d0e3fef7fe30579ba7a200/lib/protocol/crypto.js#L29-L33) [dependencies](https://github.com/mscdex/ssh2/blob/73542199290ce7f2d592e8e67251caa6bf3852be/lib/protocol/constants.js#L6-L8).

If your package manager or other tooling is not treating them as such (whether at install time or runtime), then that is a bug that needs to be reported to the appropriate project's issue tracker.
