### ISSUE TITLE
Question: SFTP terminal connection

### ISSUE THREAD

**Issue by SantyTaco** [mscdex/ssh2#1247]
I have implemented a SFTP server that is working for node js sftp client. I would like to know if it is possible to create a connection like this:
❯ sftp root@172.105.186.216
root@172.105.186.216's password:
Connected to 172.105.186.216.
sftp> ?

I have tried to connect to the sftp server using a terminal but I have this response:
sftp -P 8070 foo@localhost        
foo@localhost's password: 
Connected to localhost.
Couldn't canonicalize: No error
Need cwd

This is my sftp server implementation: 

```js
new ssh2.Server({
  hostKeys: [{key:readFileSync('id_rsa'), passphrase:'welcome1'}]
}, (client) => {
  console.log("Client connected!");
  client.on('authentication', (ctx) => {
    let allowed = true;
    if (!checkValue(Buffer.from(ctx.username), allowedUser)) allowed = false;
    allowed = checkAuthnticationMethod(ctx.method, ctx.password, allowedPassword);
    allowed ? ctx.accept() : ctx.reject();
  }).on('ready', () => {
    console.log('Client authenticated!');
    client.on('session', (accept, reject) => {
      const session = accept();
      session.on('sftp', (accept, reject) => {
        console.log('Client SFTP session');
        const openFiles = new Map();
        let handleCount = 0;
        const sftp = accept();
        sftp.on('OPEN', (reqid, filename, flags, attrs) => {
          console.log('OPEN')
          const handle = Buffer.alloc(4);
          openFiles.set(handleCount, true);
          handle.writeUInt32BE(handleCount++, 0);
          sftp.handle(reqid, handle);
        }).on('WRITE', async (reqid, handle, offset, data) => {
          try {
            if (handle.length !== 4
              || !openFiles.has(handle.readUInt32BE(0))) {
            return sftp.status(reqid, STATUS_CODE.FAILURE);
          }
          await uploadFile(bucketName, fileName, data);
          sftp.status(reqid, STATUS_CODE.OK);
          } catch(error) {
            return sftp.status(reqid, STATUS_CODE.FAILURE, error);
          }
        }).on('OPENDIR', (reqID, path) => { 
          console.info('OPENDIR', path);
          readDirPath = path;
          const handle = Buffer.alloc(4);

          openFiles.set(handleCount, true);
          handle.writeUInt32BE(handleCount++, 0);
          sftp.handle(reqID, handle);
        }).on('READDIR', async (reqID, handle) => {
          try {
            if (handle.length !== 4 ) {
              return sftp.status(reqid, STATUS_CODE.FAILURE);
            }
            const directory = await getDirectoryList(readDirPath);
            sftp.name(reqID, directory);
          } catch(error) {
            return sftp.status(reqid, STATUS_CODE.FAILURE);
          }
        }).on('REALPATH', (reqid, path) => {
          console.log('path', path);
          return sftp.status(reqid, STATUS_CODE.OK);
        }).on('CLOSE', (reqid, handle) => {
          let fnum;
          if (handle.length !== 4
              || !openFiles.has(fnum = handle.readUInt32BE(0))) {
            return sftp.status(reqid, STATUS_CODE.FAILURE);
          }
          console.log('Closing file');
          openFiles.delete(fnum);
          sftp.status(reqid, STATUS_CODE.OK);
        });
      });
    });
  }).on('close', () => {
    console.log('Client disconnected');
  }).on('error', (err) => {
    console.error(`A client error occurred from ${err}`);
});
}).listen(8070, function() {
  console.log('Listening on port ' + this.address().port);
});
```

Also, If I tried to use filezilla I am not able to make a connection.
![Screen Shot 2022-12-19 at 3 44 43 PM](https://user-images.githubusercontent.com/38363806/208530101-ff3ee79a-5aa7-4374-b481-e879c12b56f9.png)

I would like to know what I am missing in my server implementation to use terminal commands and filezilla client.

**Comment by mscdex** [comment]
1. You should probably enable full debug output on the OpenSSH sftp client to find out what command it's sending that you're missing support for. For determining the cwd, it's probably using something like `REALPATH`.

2. For Filezilla I can't really help you there. Check that the username and password you're using in Filezilla are both correct. It could be that Filezilla requires the server to send back a list of acceptable authentication methods before it even attempts to send the password, in which case you can send back the list of authentication method names by passing an array of string names to `ctx.reject()`.

3. This code:

  ```js
      let allowed = true;
      if (!checkValue(Buffer.from(ctx.username), allowedUser)) allowed = false;
      allowed = checkAuthnticationMethod(ctx.method, ctx.password, allowedPassword);
      allowed ? ctx.accept() : ctx.reject();
  ```

  doesn't look quite right as it appears to allow a user with a matching password but non-matching username. It is important to always check the password (using a constant-time comparison algorithm or node's built-in `crypto.timingSafeEqual()` as demonstrated in the readme) whether or not the username is allowed though, to avoid leaking information about allowed usernames.

**Comment by SantyTaco** [comment]
Thank you for your answer, I could establish an interactive connection from a terminal using this event. 
`.on('REALPATH', (reqid, path) => {
          return sftp.name(reqid, [{ filename: path }]);
   })`

After that, I had to start implementing the events for each command that I want to use for example (ls, cd .. and put)
