### ISSUE TITLE
[Question] ssh2-compatible interactive shell lib ?

### ISSUE THREAD

**Issue by KaKi87** [mscdex/ssh2#1248]
Hello,

Would anyone know of an interactive shell lib (e.g. like [`vorpal`](https://github.com/dthree/vorpal) or [`cliffy`](https://github.com/drew-y/cliffy)) that would be work over `ssh2`, i.e. capable of setting custom `stdin` & `stdout` streams ?

Thanks

**Comment by mscdex** [comment]
You're better off asking somewhere else like https://github.com/nodejs/help or similar places where general questions will have a better chance of being seen/answered.

**Comment by KaKi87** [comment]
Well, for anyone who might need the same thing, I was finally able to [do it using `commander`](https://github.com/tj/commander.js/issues/1841#issuecomment-1407368531).

Thanks
