### ISSUE TITLE
Client.exec stream not able to get whole output

### ISSUE THREAD

**Issue by deadshot674gam** [mscdex/ssh2#1249]
I have a UseCase where i am trying to fetch a stdout of a command , which is very large.

The problem is while doing so the stream is emitting `exit ` event before receiving the whole stdout and hence the output is not complete.

It works fine when the output is not long.

Below is the code example.
```
var dataBig : string = ''
stream.on('data',(data: string)=>{
      console.log('data still coming')
      if (data.includes('password')) {
           stream.write("${this.password}\n")
      }  else {
           this.stdout+= data
      }
})

stream.on('exit', (code: string) => {
console.log("exiting the stream with code - ${code}")
callback(this.stdout)

 })

```

The output terminates early and the callback is received

**Comment by mscdex** [comment]
Listen for `'close'` to know when the process has exited and there is no more stdout/stderr data. Like with node child processes, it is also passed the same arguments as the `'exit'` event.

**Comment by deadshot674gam** [comment]
Cool thanks , it worked like a Charm :))
