### ISSUE TITLE
Is there a Way to provide {captureRejection: true} for EventEmitter ?

### ISSUE THREAD

**Issue by deadshot674gam** [mscdex/ssh2#1251]
I have a use-case where the Error events needs to be handled (printed in logs or returned as a logic)

I added this in my code 

```
this.client.on('error', (err) => {
            throw err;
})
```

I want to catch this error in other part of code, but instead the code is failing with ERROR in Console

**Comment by mscdex** [comment]
I'm not sure what you're asking. `captureRejections` has to do with using `async` functions for event handlers, which is not the case in your example.

If you want client-level errors handled elsewhere then move the handler to the appropriate scope.

**Comment by deadshot674gam** [comment]
the code is placed with the 

```
this.client.on('error', (err) => {
           throw err;
 })
       

this.client.connect({
            host: hostname
            username: username,
            password: password,
            tryKeyboard: true,
});
```


At the time of Authentication failure i can see the script errors out with - 

```
Error: All configured authentication methods failed
```

I dont want script to error out, i want this to get caught

**Comment by mscdex** [comment]
`throw err` is causing your problem. Don't do that.

**Comment by deadshot674gam** [comment]
Ok got your point, I can think of a workaround, will try that and close this.
:)🧑‍💻

**Comment by xuxucode** [comment]
How to enable `captureRejections`  for the client instance. For example:
```ts
new Server({ hostKeys }, (client, info) => {
  client.on('authentication', async ctx => { // async listener
    await something()
  })
})
```
