### ISSUE TITLE
The session always exits after executing a command

### ISSUE THREAD

**Issue by meguoe** [mscdex/ssh2#1253]
Always end the session automatically after logging in to the HuaWei firewall using the ssh2 module and executing the command

```js
import { Client } from 'ssh2';

const conn = new Client();
conn.on('ready', () => {
  console.log('Client :: ready');
  conn.shell((err, stream) => {
    if (err) throw err;
    stream.on('close', () => {
        console.log('close')
        conn.end()
    })
    stream.on('error', (error) => console.log('ERROR: ' + error))

    stream.end('display ip routing-table \n');

    setTimeout(async () => {
        await stream.end('display ip routing-table \n');
    }, 3000)
    
    
  });
}).connect({
    host: 'xxx.xxx.xxx.xxx',
    username: 'xxx',
    password: 'xxx',
    keepaliveInterval: 3000,
    debug: (e) => {
        console.log(e)
    }
});
```

```
Custom crypto binding available
Local ident: 'SSH-2.0-ssh2js1.11.0'
Client: Trying xxx.xxx.xxx.xxx on port 22 ...
Socket connected
Remote ident: 'SSH-2.0--'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,curve25519-sha256,curve25519-sha256@libssh.org
Handshake: KEX algorithm: curve25519-sha256@libssh.org
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa
Handshake: Host key format: ssh-rsa
Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
Handshake: (remote) C->S cipher: AEAD_AES_256_GCM,aes256-gcm@openssh.com,AEAD_AES_128_GCM,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
Handshake: C->S Cipher: aes128-gcm@openssh.com
Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
Handshake: (remote) S->C cipher: AEAD_AES_256_GCM,aes256-gcm@openssh.com,AEAD_AES_128_GCM,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
Handshake: S->C cipher: aes128-gcm@openssh.com
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: AEAD_AES_256_GCM,AEAD_AES_128_GCM,hmac-sha2-512,hmac-sha2-256
Handshake: C->S MAC: <implicit>
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: AEAD_AES_256_GCM,AEAD_AES_128_GCM,hmac-sha2-512,hmac-sha2-256
Handshake: S->C MAC: <implicit>
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: none,zlib
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: none,zlib
Handshake: S->C compression: none
Outbound: Sending KEXECDH_INIT
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_FAILURE (publickey,password)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_BANNER
Inbound: Received USERAUTH_SUCCESS
Client :: ready
Outbound: Sending CHANNEL_OPEN (r:0, session)
Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:3)
Outbound: Sending CHANNEL_REQUEST (r:3, pty-req)
Inbound: CHANNEL_SUCCESS (r:0)
Outbound: Sending CHANNEL_REQUEST (r:3, shell)
Inbound: CHANNEL_SUCCESS (r:0)
Outbound: Sending CHANNEL_DATA (r:3, 26)
Outbound: Sending CHANNEL_EOF (r:3)
Inbound: CHANNEL_DATA (r:0, 2)
Inbound: CHANNEL_DATA (r:0, 193)
Inbound: CHANNEL_DATA (r:0, 2)
Inbound: CHANNEL_DATA (r:0, 8)
Inbound: CHANNEL_DATA (r:0, 27)
Inbound: CHANNEL_DATA (r:0, 30)
Inbound: CHANNEL_DATA (r:0, 2)
Inbound: CHANNEL_DATA (r:0, 234)
Inbound: CHANNEL_DATA (r:0, 161)
Inbound: CHANNEL_DATA (r:0, 735)
Inbound: CHANNEL_DATA (r:0, 8)
Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
Outbound: Sending CHANNEL_CLOSE (r:3)
Inbound: Received REQUEST_FAILURE
Inbound: CHANNEL_CLOSE (r:0)
Inbound: Received DISCONNECT (2, "The connection is closed by SSH Server
")
```

**Comment by mscdex** [comment]
I'm not sure if you're asking a question or not, but `stream.end()` will definitely end the interactive session, so if you don't want that to happen, don't call `stream.end()`.

**Comment by meguoe** [comment]
> 
Sorry，code sample error, Please take a look at this code. It is still wrong after execution

`
const conn = new Client();
conn.on('ready', () => {
  conn.exec('display ip routing-table', (err, stream) => {
    if (err)  throw err;
    stream.on('close', (code, signal) => {
      console.log('close: ' + code + ', signal: ' + signal);
    }).on('data', (data) => {
      console.log(data.toString());
    }).stderr.on('data', (data) => {
      console.log('stderr: ' + data);
    });
  });
}).connect({
    host: 'xxx.xxx.xxx.xxx',
    username: 'xxx',
    password: 'Mxb123=-@',
    keepaliveInterval: 3000,
    debug: (e) => {
        console.log(e)
    }
});
`

Local ident: 'SSH-2.0-ssh2js1.11.0'
Client: Trying 124.236.16.226 on port 22322 ...
Socket connected
Remote ident: 'SSH-2.0--'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,curve25519-sha256,curve25519-sha256@libssh.org
Handshake: KEX algorithm: curve25519-sha256@libssh.org
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: ssh-rsa
Handshake: Host key format: ssh-rsa
Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
Handshake: (remote) C->S cipher: AEAD_AES_256_GCM,aes256-gcm@openssh.com,AEAD_AES_128_GCM,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
Handshake: C->S Cipher: aes128-gcm@openssh.com
Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
Handshake: (remote) S->C cipher: AEAD_AES_256_GCM,aes256-gcm@openssh.com,AEAD_AES_128_GCM,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
Handshake: S->C cipher: aes128-gcm@openssh.com
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: AEAD_AES_256_GCM,AEAD_AES_128_GCM,hmac-sha2-512,hmac-sha2-256
Handshake: C->S MAC: <implicit>
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: AEAD_AES_256_GCM,AEAD_AES_128_GCM,hmac-sha2-512,hmac-sha2-256
Handshake: S->C MAC: <implicit>
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: none,zlib
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: none,zlib
Handshake: S->C compression: none
Outbound: Sending KEXECDH_INIT
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_FAILURE (publickey,password)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_BANNER
Inbound: Received USERAUTH_SUCCESS
Outbound: Sending CHANNEL_OPEN (r:0, session)
Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:3)
Outbound: Sending CHANNEL_REQUEST (r:3, exec: display ip routing-table)
Inbound: CHANNEL_SUCCESS (r:0)
Inbound: CHANNEL_DATA (r:0, 2)
Inbound: CHANNEL_DATA (r:0, 193)
Inbound: CHANNEL_DATA (r:0, 2)

DATA: <detect>
DATA: Inbound: CHANNEL_DATA (r:0, 92)

Inbound: CHANNEL_CLOSE (r:0)
Outbound: Sending CHANNEL_CLOSE (r:3)
Inbound: CHANNEL_DATA (r:0, 2)
close: undefined, signal: undefined
Socket ended
Socket closed
Waiting for the debugger to disconnect...

**Comment by meguoe** [comment]
Always after executing a command  _Sending CHANNEL_CLOSE (r:3)_

**Comment by meguoe** [comment]
use socket.write() ^_^
