### ISSUE TITLE
Question: The write event is just uploading 32KB from a file of 630KB

### ISSUE THREAD

**Issue by SantyTaco** [mscdex/ssh2#1254]
Hi,
My sftp server is working well for small size files but when I try to upload a big size file the connection close in the server and in the client this is the message that it shows "Couldn't close file: Failure". The file's size in the server is 32KB but the real size of that file is 630KB and I cannot open the file.

The current bufferSize is 20

```js
        sftp.on('OPEN', (reqid, filename, flags, attrs) => {
          const handleBuffer = Buffer.alloc(bufferSize);
          const fileRecord = {
            "handle": handleCount,
            "path": filename.replaceAll('\\', '/'),
            "readComplete": true
          };

          openFiles.set(handleCount, fileRecord);
          handleBuffer.writeUInt32BE(handleCount++, 0);
          sftp.handle(reqid, handleBuffer);
        });

        sftp.on('WRITE', async (reqid, handle, offset, data) => {
          console.log('Write')
          try {
            const fileRecord = getFileRecord(handle);

           if (handle.length !== bufferSize || !openFiles.has(handle.readUInt32BE(0))) return sftp.status(reqid, STATUS_CODE.FAILURE);
          
            await uploadFile(fileRecord.path, data);
            sftp.status(reqid, STATUS_CODE.OK);
          } catch(error) {
            console.log('Error', error);
            return sftp.status(reqid, STATUS_CODE.FAILURE);
          }
        });
```

What could I do to upload a big file?

**Comment by mscdex** [comment]
Writes come in chunks, so don't expect it's done until the file is closed.

**Comment by SantyTaco** [comment]
So, should I save each chunk in an array and when it is close concat the buffer? something like that?

**Comment by mscdex** [comment]
How you handle incoming chunks is totally up to you, whether you want to store them in memory, store them on local disk, store them in the cloud, write them to /dev/null, you can do it however you want.

**Comment by SantyTaco** [comment]
Thank you for your response, I resolved the problem with the chunk data, but in Winscp I am getting this error. In other clients like cyberduck I am not getting that.
![Screen Shot 2023-01-23 at 9 52 40 AM](https://user-images.githubusercontent.com/38363806/214085578-da0118bd-d099-405a-be9f-014c078fbb7c.png)
Do you know if I need to add something else in the sftp server?

**Comment by mscdex** [comment]
If you enable debug output (`debug: console.error` in your server config object) you should see which request the client is sending. `ssh2` will automatically send a 'status' reply to requests that aren't explicitly handled. I would guess it's one of the stat-related requests though.
