### ISSUE TITLE
Reverse Tunnel

### ISSUE THREAD

**Issue by peterromero** [mscdex/ssh2#1255]
I've been banging my head against this for months now. I cannot figure out how to make a reverse tunnel with this library. I can open the tunnel fine using terminal and SSH.

Here's my setup: I have a server that functions as the "forwarder" for connections. On the remote side, another computer connects to it via SSH using the `RemoteForward` (`-R`) option. This means anything connecting to the forwarder on port `11111` will be forwarded to the remote computer on port `22222`. This isn't part of my script, since it takes place on the remote computer:

```bash
ssh -R 11111:127.0.0.1:22222 [FORWARDERUSER@FORWARDERURL] -p 33333
```

Once it's connected, I open a terminal window locally and connect to the forwarder using the `LocalForward` (`-L`) option. This forwards my local port `44444` to port `11111` on the forwarder, which is already listening as shown above.

```bash
ssh -L 11111:127.0.0.1:44444 [FORWARDERUSER@FORWARDERURL] -p 22
```

Then I can connect to my localhost and it allows me to connect to the remote computer through the forwarder.

```bash
ssh [REMOTEUSER]@127.0.0.1 -p 44444
```

Again, this works in Terminal. I read that `forwardOut()` "doesn't actually listen on the local port" (what on earth does it do then?). I'm totally clueless as to how to set this up. Here's the essence of what I've tried (with lots of permutations):

```node
let connection = new Client();

connection.on('ready', () => {
  // This connection works fine.
  this.connection.forwardOut(
    '127.0.0.1',
    44444,
    '[FORWARDERURL]',
    11111, (err, stream) => {
      // Here we get (SSH) Channel open failure: Connection refused
    }
  );
}).connect({
  host: '[FORWARDERURL]',
  port: 22,
  username: '[FORWARDERUSER]',
  privateKey: '[PRIVATEKEY]'
});
```

**Comment by mscdex** [comment]
I'm not sure if there are copy-paste errors in your port numbers, but

```
ssh -L 11111:127.0.0.1:44444
```

would bind to port *11111* on your local machine and connections to it would be forwarded to port 44444 on the SSH server, so I'm not sure how `ssh [REMOTEUSER]@127.0.0.1 -p 44444` could ever work.

Anyway,



> I read that `forwardOut()` "doesn't actually listen on the local port" (what on earth does it do then?)

Because the OpenSSH client is traditionally used for its standalone binary (as opposed to the C library), it does two things when forwarding local connections to the SSH server:

1. It has to bind to an IP/port so that network clients have a place to connect to
2. It has to perform the SSH protocol-level communication that allows the data to flow between the bound IP/port and the SSH server.

`ssh2` is purely a library and designed to be flexible. That means its `forwardOut()` does not need to do \#1 above as it has the opportunity to completely skip that overhead and just do \#2 above. This is what is meant when the readme says it doesn't listen on the local port. If you need this functionality, you will need to create and bind a `net.Server` yourself and call `forwardOut()` on new incoming connections and pipe the two streams together.

Additionally, it appears you may/may not have the `forwardOut()` arguments wrong. The first two values are the source IP and port. These can be any reasonable values really, I'm not even sure if SSH servers (especially OpenSSH) even do anything with them apart from possibly including them in debug logs. I believe the original intention in the SSH specification was that these values would be your `net.Server`'s bound IP/port. The second two values are the most important as they are the destination IP/port (where you want to connect to from the SSH server).

Again, since I don't know if it's a copy-paste error, but for a command like

```
ssh -L 11111:127.0.0.1:44444
```

the destination port for `forwardOut()` would need to be 44444 instead of 11111. Perhaps that is why you are seeing the "connection refused" error.

**Comment by peterromero** [comment]
@mscdex it is possible I have the ports flipped in my example. In real life, my local port and the port on the forwarder are the same, so I could have mixed them up in my post.

Shoot. I've been all over the internet and I can't seem to find any complete, working examples of this. I've been trying and trying with `net.createServer()` and what not, but it's way over my head. I've tried lots of libraries that claim to do it as well, but none of them do. Does anyone know if there's a library that just does this task out of the box? It's way too complicated for me.

**Comment by mscdex** [comment]
@peterromero It's quite easy. Create a `net.Server`. Then for incoming connections you simply call `ssh.forwardOut()` and inside the callback you pass to it, pipe the incoming socket and the stream passed to your callback together in both directions. That's literally all there is to emulating OpenSSH's `-L` forwarding.

**Comment by peterromero** [comment]
Thanks for the tips! I've spent hours on it today; probably many many more to come. If I ever figure it out I'll update.

**Comment by peterromero** [comment]
Let's see here.

> Create a `net.Server`.

```javascript
const net = require('net');

// Create a net.Server.
let listenerOn127001 = new net.Server();
listenerOn127001.listen(11111, '127.0.0.1');
```

> Then for incoming connections

```javascript
const net = require('net');
const {Client} = require('ssh2');

// Create a net.Server.
let listenerOn127001 = new net.Server();
listenerOn127001.listen(11111, '127.0.0.1');

// Connect to localhost.
let connTo127001 = new Client();
connTo127001.connect({
    host: '127.0.0.1',
    port: 11111,
    username: '[REMOTEUSER]'
});

// For incoming connections,
listenerOn127001.on('connection', socket => {
    // this happens when connTo127001 connects.
});
```

> you simply call `ssh.forwardOut()`

This is where I get lost.

```javascript
const net = require('net');
const {Client} = require('ssh2');

// Create a net.Server.
let listenerOn127001 = new net.Server();
listenerOn127001.listen(11111, '127.0.0.1');

// Connect to localhost.
let connTo127001 = new Client();
connTo127001.connect({
    host: '127.0.0.1',
    port: 11111,
    username: '[REMOTEUSER]'
});

// For incoming connections,
listenerOn127001.on('connection', socket => {
    // call ssh.forwardOut() on what? Is this where I create a connection to the forwarder?
    // If so, here's what that looks like:
    let connToForwarder = new Client();
    connToForwarder.connect({
        host: '[FORWARDERURL]',
        port: 22,
        username: '[FORWARDERUSER]',
        privateKey: '[PRIVATEKEY]'
    });
    connToForwarder.on('ready', () => {
        connToForwarder.forwardOut(
          '127.0.0.1',
          11111,
          '[FORWARDERURL]', // or does it need to be a remote IP address? Something else?
          11111,
          async (err, stream) => {
            // We never make it here.
          }
        );
    });
});
```

**Comment by mscdex** [comment]
The simplest approach is to just create a new SSH connection on every incoming local connection:

```js
function localNetServerOnConnection(socket) {
  const ssh = new Client();
  ssh.on('ready', () => {
    ssh.forwardOut('127.0.0.1', 12345, destIP, destPort, (err, stream) => {
      if (err) throw err;
      stream.pipe(socket);
      socket.pipe(stream);
    });
  });
  ssh.connect({ ... });
}
```

Obviously you will need appropriate error handling, but that is the gist of all you need to do.

**Comment by peterromero** [comment]
@mscdex Thanks for the code. I'm assuming I still need some part of what I already wrote above (not sure yet where to get the `socket` that comes into this function). Will bang on this some more.

**Comment by mscdex** [comment]
The source or destination address can be an IP or hostname, it can't be a URL as SSH (the protocol) does not utilize URLs.

**Comment by peterromero** [comment]
So with the IP address in place, my code is now hitting the callback from `forwardOut`, but `stream` is `undefined`. Any ideas?

**Comment by mscdex** [comment]
I don't know what to tell you then. Either the destination IP or port are still wrong on the client side or nothing is listening on that IP and port on the server side.

**Comment by peterromero** [comment]
I've been comparing the output of `netcat` on my computer before and after executing the `ssh -L` command (which works), with the results before and after running this script and arriving at the `forwardOut` function. In both cases, the new entries I see are almost* exactly the same.

\* This is what gets added to the output of `netcat`:

```
TCP    my_local_ip:62228     forwarder_ip:22        ESTABLISHED
TCP    127.0.0.1:11111       0.0.0.0:0              LISTENING
TCP    [::1]:11111           [::]:0                 LISTENING    * I get this one on the command line but not with the script
TCP    127.0.0.1:11111       127.0.0.1:62230        ESTABLISHED
TCP    127.0.0.1:62230       127.0.0.1:11111        ESTABLISHED
```

I don't think the missing ipv6 entry would make a difference. I don't know what else to check.

**Comment by mscdex** [comment]
If your SSH server is listening on 127.0.0.1:44444, then does `destIP === '127.0.0.1'` and `destPort === 44444`?

**Comment by peterromero** [comment]
I think so. I'm trying to forward my local port `127.0.0.1:11111` to the remote port `my_forwarder_url:11111`, so that SSH connections to `127.0.0.1:11111` are received by `my_forwarder_url:11111`. I've been assuming `forwardOut` is the right choice for this (and not `forwardIn`). Here's how my code looks for that:

```javascript
...
connToForwarder.forwardOut(
  '127.0.0.1',
  11111,
  '[FORWARDER_IP]',
  11111,
  async (err, stream) => {
    if (err) {
      reject(err);
    } else {
      stream.pipe(socket);
      socket.pipe(stream);
      resolve(true);
    }
  }
);
...
```

**Comment by mscdex** [comment]
`destIP` should be the IP address *relative* to the SSH server, so it should _not_ be the (external) IP address of the SSH server itself for example.

Judging by the `-R` example in your OP, it looks like you're binding to 127.0.0.1 on the SSH server, so `destIP` should be `'127.0.0.1'`.

**Comment by peterromero** [comment]
So should both source and destination be `127.0.0.1`? One is local; one is remote. How would it know the difference?

**Comment by mscdex** [comment]
> So should both source and destination be `127.0.0.1`? One is local; one is remote. How would it know the difference?

Like I said before, the source IP and port can largely be anything (syntactically/numerically valid) and aren't very important. `destIP` and `destPort` on the other hand are where you want to connect to from the perspective of the SSH server and are the important values to get right. So if the SSH server you're connected to has a process listening on 127.0.0.1 port 11111, then those are the values you want to use for those parameters respectively.

I still don't totally understand what setup you have going on or know what you have listening where, so I can't really help you further with the "Connection refused" error. All I can tell you is that [the `forwardOut()` example I gave](https://github.com/mscdex/ssh2/issues/1255#issuecomment-1381104061) is all you need to accomplish OpenSSH's `-L` type of forwarding.
