### ISSUE TITLE
[Question] How to use with 'node:repl' ?

### ISSUE THREAD

**Issue by KaKi87** [mscdex/ssh2#1256]
Hello,

As I'm trying to serve a REPL through an `ssh2` server, I can't figure out an issue that only occurs in that situation but not when using `process.stdin` & `process.stdout` : the user's input isn't output back to them, despite the server successfully catches it.

Here's my minimal reproducible code :
```js
import {
    readFileSync
} from 'node:fs';
import repl from 'node:repl';
import ssh2 from 'ssh2';
new ssh2.Server({
    hostKeys: [ readFileSync('./host.key') ]
}, client => {
    client.on('authentication', async authentication => {
        authentication.accept();
        client.once('session', async accept => {
            const session = accept();
            session.on('pty', accept => accept());
            session.on('shell', accept => {
                const stream = accept();
                repl.start({
                    input: stream.stdout,
                    output: stream.stdin,
                    eval: line => console.log(line)
                });
            });
        });
    });
}).listen(0, '0.0.0.0', function(){
    console.log('Listening on port ' + this.address().port);
});
```

Thanks

**Comment by mscdex** [comment]
> ```js
>                     input: stream.stdout,
>                     output: stream.stdin,
> ```

This isn't quite right, you have the two swapped. The stdin is coming from the client and stdout and stderr streams are what the server writes to.

Also, you can just use `stream` for both since the readable side is stdin and writable side is stdout and both refer to the same object. If you want to write to stderr however, you will need to do that by explicitly using `stream.stderr`.

**Comment by KaKi87** [comment]
Well, nothing changes anyway.

**Comment by mscdex** [comment]
There's a few more things that are needed, most importantly `terminal: true` in your `repl.start()` config and removing `eval`.

You will also need to do some trickery to get previews to render correctly due to the inflexibility of node's REPL implementation when it comes to newline handling.

Here is a more complete example that should work:

```js
const { Transform } = require('stream');
const NLConverter = (() => {
  // Converts `\n` to `\r\n`
  const CR = Buffer.from('\r');
  return class NLConverter extends Transform {
    _transform(chunk, enc, cb) {
      let i = 0;
      let last = 0;
      while ((i = chunk.indexOf(10, i)) !== -1) {
        if (i === 0) {
          this.push(CR);
        } else if (chunk[i - 1] !== 13) {
          this.push(chunk.slice(last, i));
          this.push(CR);
          last = i;
        }
        ++i;
      }
      if (last === 0)
        this.push(chunk);
      else
        this.push(chunk.slice(last));
      cb();
    }
  };
})();

// ...

client.on('session', (accept, reject) => {
  const session = accept();
  let rows;
  let cols;
  let outputStream;
  const handlePtyUpdate = (accept, reject, info) => {
    accept && accept();
    rows = info.rows;
    cols = info.cols;
    if (outputStream) {
      outputStream.rows = rows;
      outputStream.columns = cols;
      outputStream.emit('resize');
    }
  };
  session.on('pty', handlePtyUpdate);
  session.on('window-change', handlePtyUpdate);
  session.on('shell', (accept) => {
    const shellStream = accept();

    outputStream = new NLConverter();
    outputStream.rows = rows;
    outputStream.columns = cols;
    outputStream.pipe(shellStream);

    repl.start({
      input: shellStream,
      output: outputStream,
      terminal: true,
    }).on('exit', () => {
      shellStream.end();
    });
  });
});
```

**Comment by KaKi87** [comment]
> `terminal: true` in your `repl.start()` config

That's what I missed, thanks !

> removing `eval`.

Actually, I need it, as my goal is to provide my own REPL (probably powered by [`commander`](https://github.com/tj/commander.js)), not Node's.

> You will also need to do some trickery to get previews to render correctly due to the inflexibility of node's REPL implementation when it comes to newline handling.

Actually I did not, I only changed my `eval` function to the following :
```js
(
    line,
    _,
    __,
    callback
) => {
    // TODO something with `line`
    stream.stdin.write('My output here\r\n');
    callback();
}
```

However, for other interactive CLI modules like [`inquirer`](https://github.com/SBoudrias/Inquirer.js/tree/master/packages), I did need to make a function that replaces `\n` with `\r\n` :
```js
import {
    PassThrough
} from 'node:stream';

export default stream => {
    const
        stdin = new PassThrough(),
        stdout = new PassThrough();
    stdout.on('data', data => stream.stdin.write(Buffer.from(data.toString().replaceAll('\n', '\r\n'), 'utf8')));
    stream.stdout.on('data', data => stdin.write(data));
    return {
        input: stdin,
        output: stdout
    };
};
```
