### ISSUE TITLE
Proxy SSH Shell

### ISSUE THREAD

**Issue by ptorrent** [mscdex/ssh2#1258]
Hello there !

Thanks for this awesome dev.

I'm trying to proxy shell on a debian SSH Server

So this is what I do:

```
var conn = new Client();
conn.connect({
	host: '127.0.0.1',
	port: 22
....
},);

//client from server
serverClient.on('session', function(accept){
	var session = accept()
	session.once('shell', function(accept, reject, info){
		conn .shell(function(err, stream){
			if(err) return reject()
			var a = accept()
			a.pipe(stream).pipe(a)
		})
	})
})
```

Client is connected to the debian SSH server. 

I saw this:
https://github.com/mscdex/ssh2/issues/718
But it's not sure it's my case, because i'm not using readline

I'm using Putty as client. It's working well except for specific command. Like "tab" "ctrl+c" and mybe other special char , any idea ?

Thanks for your help !

**Comment by mscdex** [comment]
There shouldn't be any problems as far as sending those characters/sequences go.

You should proxy terminal size changes and send the initial terminal size and terminal type when starting the interactive shell session though.

My suggestion would be to check what PuTTY is sending when you press tab or ctrl-c by reading the raw bytes out of `a`.

**Comment by ptorrent** [comment]
Thanks for your answer ! It seems I was able to make it works but I can't explain it !

```
session.once('pty', function(accept, reject, info){
	console.error('pty')
	accept()
})
session.once('shell', function(accept, reject, info){
	conn.shell(function(err, stream){
		if(err) return reject()
		var a = accept()
		a.pipe(stream).pipe(a)
         })
})
```

The server log output :

```
Client authenticated!
pty
shell
```

It seems that adding 
```
session.once('pty', function(accept, reject, info){
	console.error('pty')
	accept()
})
```

solve my issue

if I write:

```
session.once('pty', function(accept, reject, info){
	console.error('pty')
	reject()
})
```

I still have the issue with tab, ctrl-c etc...

**Comment by mscdex** [comment]
Yes, you will need to accept pty requests if you want to receive terminal escape sequences and other things, otherwise clients that require it will not send such things.
