### ISSUE TITLE
Best way to do a SFTP proxy

### ISSUE THREAD

**Issue by ptorrent** [mscdex/ssh2#1259]
Hello !

What is the best way to do a SFTP proxy ?

```
serverSession.once('sftp', function(accept, reject){
		conn.sftp(function(err, stream){
			if(err) return reject()
			var a = accept()
				a.pipe(stream).pipe(a)
		})
})
```
Looks like the stream given by  conn.sftp is not a usable stream to pipe.

I read about SFTPStream but did not find an example

Thanks for your support !

**Comment by mscdex** [comment]
You can proxy using the more generic subsystem event/method:

```js
serverSession.on('subsystem', (accept, reject, info) => {
  if (info.subsystem === 'sftp') {
    conn.subsys('sftp', (err, upstream) => {
      if (err) return reject();
      const downstream = accept();
      downstream.pipe(upstream).pipe(downstream);
    });
    return;
  }
  reject();
})
```

**Comment by ptorrent** [comment]
Awesome thanks !

Just notice something

info.subsystem => undefined

This is what i got

```
info = {
name : 'sftp'
}
````

Don't know if it's normal

**Comment by mscdex** [comment]
Yep, was a typo.
