### ISSUE TITLE
Getting client ip address

### ISSUE THREAD

**Issue by ptorrent** [mscdex/ssh2#1260]
Hello!

I didn't found any method to get client ip address on a ssh2 server.

Actually I found this:

```
 client._sock._peername
=> { address: '::ffff:62.167.164.6', family: 'IPv6', port: 4185 },
```

Is the an other way to do that ?

**Comment by mscdex** [comment]
The [`'connection'` event](https://github.com/mscdex/ssh2#server-events) receives an object containing various pieces of information about the client, including the IP.
