### ISSUE TITLE
Is SSH yubikey auth possible with SSH2? 

### ISSUE THREAD

**Issue by nick-george** [mscdex/ssh2#1261]
Hi there, 

I'd love to be able to use a yubikey with your library to harden SSH logins. The scenario I'm considering is this one https://rameerez.com/how-to-use-yubikey-to-log-in-via-ssh-to-server/. It seems that openssh can create a private key that requires the  yubikey to unlock it. 

I fear this would be impossible, given that that private key would be stored on the web-backend and I'm doubting the browser would expose the correct functionality to unlock the key. I'm hoping I'm wrong. 

Have you ever thought about this scenario? I'm not asking you to implement it; I'm just wondering if it's possible. 

I understand that I could protect access to the web application via a mechanism such as WebAuthn, but I'm looking to protect against scenarios where the SSH keys stored in the backend are leaked. 

Cheers, 
Nick

**Comment by mscdex** [comment]
No idea offhand. I have not really looked at any of that. I know OpenSSH has some `-sk` suffixed key types, but that's about it. Not sure if explicit support is needed or if an ssh-agent can handle all of the security key-specific bits and just list normal key types (in which case, that would work today without any changes).

**Comment by nick-george** [comment]
Thanks for that @mscdex. 

To confirm my understanding of your ssh-agent suggestion, would the ssh-agent run on the same host as the SSH2 backend (on nodejs)? If that's the case, the Yubikey would have to be plugged into that backend host, which wouldn't scale or allow the backend to be physically distant from the user. 

I strongly suspect that what I want to do isn't possible. I could use one-time passwords (a la google authenticator) with SSH, but they're a pain. 

Many thanks, 
Nick

**Comment by mscdex** [comment]
The ssh-agent would run where your SSH client is.

**Comment by nick-george** [comment]
Thanks.. yeah not quite what I'm looking for, as we've written a web app that does SSH where the backend runs the SSH client on behalf of the user. Any security key would be attached directly to the browser. 

Cheers, 
Nick

**Comment by mscdex** [comment]
After a brief look, _technically_ I don't see why you couldn't create a custom agent class that uses webauthn behind the scenes to do SSH authentication. It appears webauthn does signing and provides public keys, which is about all you need for SSH authentication.

Now it's probably going to be a bit more involved unless you have a third-party module/library to do all the webauthn stuff for you (including dealing with all of the intermediate data formats used by webauthn) as `ssh2` is expecting typical public key formats.

**Comment by nick-george** [comment]
Thanks for looking further into this @mscdex; much appreciated. 

I'll describe my scenario a bit more completely. I have a browser in the mix here, and the Yubikey is plugged into the host running it. Please see the diagram below. Private keys are currently stored with an extra layer of encryption on the backend web server. However, if the encryption key that secures the keys and the keys themselves are exposed, then all is lost. I want to be able to use a physical token to secure each user's keys individually. 


```
                  ┌───────────────┐          ┌─────────────────────┐           ┌────────────────┐
                  │               │          │                     │           │                │
                  │  Web browser  │          │  Web server         │           │ Remote system  │
                  │  xtermjs      │          │  NodeJS             │           │ openssh-server │
                  │  SSH window   ├─────────►│  mscdex/ssh2 client ├──────────►│                │
┌───────────┐     │               │          │  private key store  │           │                │
│  Yubikey  ├────►│               │          │                     │           │                │
└───────────┘     └───────────────┘          └─────────────────────┘           └────────────────┘

```


From reading the openssh-client docs around -sk suffixed keys, the Yubikey has to be plugged into the machine that reads the private key (in this case, our web server). Ideally, the Yubikey would be plugged into the client (browser) machine where the user is. This would allow us to protect each user's private key(s) individually (even though they're stored on the web server). 

I suppose a fallback is that I could plug a single Yubikey directly into the backend host, which would protect against the loss of the keys should the server ever be compromised. I can see that I'd still have to write some kind of custom agent that would assist mscdex/ssh2 to use the -sk keys. Is this the scenario you're discussing? I'm not sure how Webauthn would provide any additional help (its core function is to remove the need to store any "secrets" from the web server). Unfortunately, this approach wouldn't protect each user's keys individually and also wouldn't work if the web server was in the cloud. I'd also need to figure out if the Yubikey could decrypt the -sk key without needing a physical press on its button (given the location of the web server). 

I hope all this makes sense. 


Many thanks, 
Nick

**Comment by mscdex** [comment]
AFAICT you'd really need to have the Yubikey or other hardware device manage the keys themselves and perform the data signing (the intended use for these kinds of devices).

The only alternative I can see that might eventually support your use case is the "large blob extension" for webauthn that allows storing opaque blobs with credentials. Unfortunately I believe only Chrome currently supports this extension and as of this writing it's hidden behind a flag there.

**Comment by jogemu** [comment]
The scenario described involves ecdsa-sk or ed25519-sk. You can use the yubikey provided that feature request #1206 is implemented.
