### ISSUE TITLE
sshagent meet ECONNREFUSED always

### ISSUE THREAD

**Issue by alanhg** [mscdex/ssh2#1263]
I found SSHAgent's createConnection not triiger.

So when to trigger agent create connection?

## need

I want to visit remote server's local web by SshAgent.

## code

```js
 this.agent = new SSHTTPAgent({debug: console.log, ...connectOpts}, {
        keepAlive: true,
        timeout: 20000,
      });




  codeServerProxy.agent = proxy.agent;
      codeServerProxy.web(req, res, {target: proxy.url}, (e) => {
        reject(e);
      });
```

## version info 
    "ssh2": "1.11.0",
"http-proxy": "1.18.1"

## error output

error Error: connect ECONNREFUSED 127.0.0.1:36000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:130:17) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 36000
}

**Comment by mscdex** [comment]
Try removing `http-proxy` from the equation and using [the example from the readme](https://github.com/mscdex/ssh2#make-https-connections-easily-using-a-custom-httpsagent) to connect to the web server running on the SSH server. If that still doesn't work, then verify either something is listening on 127.0.0.1:36000 on the SSH server or that the SSH server isn't restricting your forwarded connections.

**Comment by alanhg** [comment]
> the example from the readme

1. demo test ok.
2. `connection:close` is needed?
3. demo is ok,  new Agent is ok for http-proxy . but sshAgent is not ok for http-proxy.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/9245110/213340881-6133b63d-c67e-438b-b6c8-ede69f18c370.png">

I

**Comment by mscdex** [comment]
> * `connection:close` is needed?

No.

> * demo is ok,  new Agent is ok for http-proxy . but sshAgent is not ok for http-proxy.

The bundled HTTP/HTTPS Agent implementations should work just like node's built-in HTTP/HTTPS Agent implementations as they implement the required interfaces. I don't know why http-proxy is having problems. You might also double check that your `connectOpts` is complete.

Do you ever see debug output from `ssh2` when using http-proxy? If not, then that definitely points to a logic or http-proxy issue outside of `ssh2`. If you do see output, perhaps that should show you what is/isn't happening?

**Comment by alanhg** [comment]
@mscdex 

I know the issue.

## ok

```
const proxyServer = httpProxy.createProxyServer({
  secure: false,
  ws: false,
  autoRewrite: true,
  changeOrigin: false,
  hostRewrite: true,
  proxyTimeout: TIMEOUT,
  timeout: TIMEOUT,
  agent // sshAgent
});

http.createServer(function (req, res) {
  proxyServer.web(req, res, {target: 'http://127.0.0.1:36000'});
}).listen(9000);


```

## not ok
```
http.createServer(function (req, res) {
  proxyServer.agent=agent;
  proxyServer.web(req, res, {target: 'http://127.0.0.1:36000'});
}).listen(9000);

```


dynamic agent  is not ok.

**Comment by alanhg** [comment]
@mscdex

thank you. I know the root cause .

```
http.createServer(function (req, res) {
  proxyServer.agent=agent; // sshAgent
  proxyServer.web(req, res, {target: 'http://127.0.0.1:36000'});
}).listen(9000);
```

change to

```
http.createServer(function (req, res) {
  proxyServer.web(req, res, {target: 'http://127.0.0.1:36000',agent:}); // sshAgent
}).listen(9000);
```

**Comment by mscdex** [comment]
For what it's worth, according to a brief look at `http-proxy`'s code it seems you should be able to override options passed to `createProxyServer` by setting the appropriate properties in the object passed as the last argument to `.web()`, like:

```js
proxyServer.web(req, res, {target: 'http://127.0.0.1:36000', agent});
```

**Comment by alanhg** [comment]
ok. after fixing the issue. the pending request error occurs.
 I will investigate it. - https://github.com/mscdex/ssh2/issues/1241
