### ISSUE TITLE
Architectural question regarding sftp streams

### ISSUE THREAD

**Issue by dmpriso** [mscdex/ssh2#1266]
As far as I understand, the ssh-streams project isn't used by ssh2 any more, and the implementation has fallen behind.
My use case is that I need to impersonate a process (on Windows) which handles the file access.

The easiest way to do that is to get the channel from the `subsystem` callback, create an `SFTPStream` in my impersonated subprocess, and pipeline them together via stdin/stdout.

But doing so using what is available in the `ssh` lib isn't possible any more, cause as I can see, the `SFTP` implementation is tied too much to the ssh server. 

Just asking is that true or is there something I miss?

**Comment by mscdex** [comment]
That is currently the case, yes.

**Comment by dmpriso** [comment]
I understand the rationale to not maintain two repos without much standalone use for the other, but would you consider adding sftp-stream to this repo as implementation of the sftp protocol for more flexibility and if yes, would you accept PRs for merging the changes made in this repos SFTP implementation to ssh2-streams as a first step, if that appears to be useful?

**Comment by mscdex** [comment]
I wouldn't be interested in doing that because I don't want to maintain/support two separate SFTP implementations.

**Comment by dmpriso** [comment]
OK I see, thanks a lot for the info! And for the library :)
