### ISSUE TITLE
Host key is accepted when hostVerifier has not resolved promise

### ISSUE THREAD

**Issue by SanjulaGanepola** [mscdex/ssh2#1268]
To verify the host which I am connecting to, I am trying to define a `hostVerifier` function when calling `connect`. In this function, I am calling an `await` to compare the host key with the host keys in my known_hosts file. Thus, I am return a Promise which resolves to a `boolean`:

```
hostVerifier: (key: Buffer) => Promise<boolean>
```

When calling connect with a function defined like this, the host key is being accepted even though the Promise has not been resolved yet. Is there anyway to ensure that the verification is complete before it is accepted?

**Comment by mscdex** [comment]
If you're doing asynchronous verification, make sure your `hostVerifier` function returns nothing and use the callback parameter to pass the boolean value when you have it.

For example, let's say you have a function that performs an async database query to look up the key. It might look something like this:

```js
hostVerifier: (key, cb) => {
  findKeyInDatabase(key, (err, exists) => {
    cb(exists === true);
  });
},
```

**Comment by SanjulaGanepola** [comment]
@mscdex Thank you for the reply. I gave this approach a try, but seem to still have the same behavior. For example, if I try the following:

```typescript
const client = new Client();
client.on('connect', () => {
    console.log('connect');
}).on('ready', () => {
    console.log('ready');
}).on('handshake', (negotiated: any) => {
    console.log('handshake');
}).connect({
    host: host,
    username: username,
    password: password,
    hostVerifier: async (key: Buffer, verify: (valid: boolean) => void) => {
        console.log('Start verification');
        const result = await verifyHostKey(hostKey);                    
        console.log('Complete verification. Result: ' + result);
        verify(result);
    }
});
```

I get the following output which indicates the `ready` event is being fired before the verification is complete.
```
connect
Start verification
handshake
ready
Complete verification. Result: true
```

**Comment by mscdex** [comment]
You can't use the `async` keyword as that implicitly returns a Promise from the function you're using the `async` keyword with.

**Comment by mscdex** [comment]
If you really want to use `await` still, you would need to use an `async` IIFE:

```js
    hostVerifier: (key, verify) => {
        (async () => {
          console.log('Start verification');
          const result = await verifyHostKey(hostKey);                    
          console.log('Complete verification. Result: ' + result);
          verify(result);
        })();
    }
```

**Comment by SanjulaGanepola** [comment]
An `async` IIFE worked perfectly. Thanks for the help!
