### ISSUE TITLE
will it be possible in sftp.js to get caller machine name? ssh2 - npm node sftp server

### ISSUE THREAD

**Issue by maulikhdave9601672767** [mscdex/ssh2#1269]
0

I m using ssh2-sftp-client - npm.

I have function called sftpConnection which connect with sftp.

will it be possible to get caller machine name inside Sftp client.

https://www.npmjs.com/package/ssh2 I m using this code for my sftp.

will it be possible to get caller machine name inside my sftp.js ?

**Comment by mscdex** [comment]
If you're using `ssh2-sftp-client`, you should probably ask on that project's issue tracker instead. However, I'm not sure what you mean by "caller machine name".
