### ISSUE TITLE
No PATH environment variable when executing the command

### ISSUE THREAD

**Issue by Capricair** [mscdex/ssh2#1271]
I need to execute an npm command, prompting that npm is not a command, exporting the PATH variable before executing the npm command can solve this problem, but this is not a good way

**Comment by mscdex** [comment]
There's nothing `ssh2` can do about that. The server handles the setting up of the environment, the current working directory, etc.

About the best you can do is you can request that the server set `PATH` (by setting the `env` option for `exec()` or `shell()`) before executing your command or starting your interactive shell. There's no guarantee the server will honor that request though.

**Comment by Capricair** [comment]
Thanks, by the way, I'm curious how xshell does this, do you know how it works?

**Comment by mscdex** [comment]
I'm not familiar with xshell. A brief google search reveals it's not open source, so there is no way to know what they are doing.
