### ISSUE TITLE
Unable to get size of the incoming file

### ISSUE THREAD

**Issue by tariqhaque** [mscdex/ssh2#1272]
I have created a SFTP/SSH server. I am trying to get the incoming file's size, but attrs.size property is always 'undefined'. My end goal to implement file size restrictions.  Here is the code snippet:

.on('OPEN', async (reqId, filename, flags, attrs) => {
                   console.log(filename);
                   console.log(attrs.size); // This property comes in as undefined, even though the attrs object is not undefined
                   const handle = Buffer.alloc(4);
                   openFiles.set(handleCount, true);
                   handle.writeUInt32BE(handleCount++, 0);
                   console.log('Opening file for write');
                   sftp.handle(reqId, handle);
})

**Comment by mscdex** [comment]
There is no size for open requests (or any client requests really for that matter). Think of the open request as `fs.open()` in node.js. You're passed the requested filename and mode and you need to return back an error or a unique handle (like a file descriptor with `fs.open()`) representing the open file.

You'll find many other parallels with client requests and node's `fs` API, so it may help to think about it in that way.

**Comment by slifty** [comment]
Just to be clear for OP -- this means that you can't reject an open based on size limit; instead you'll need to keep track of how much data has been sent via the `WRITE` calls and return an error at the point at which a given write pushes over the limit / the size has gotten too large.

This is also just a reality of the SFTP spec, not this particular implementation.
