### ISSUE TITLE
SFTP WriteStream not emitting errors from _write method

### ISSUE THREAD

**Issue by huston** [mscdex/ssh2#1274]
In the SFTP WriteStream._write method, the callback handler for the sftp.write call doesn't emit an error event when an error occurs:
```
  this.sftp.write(this.handle,
                  data,
                  0,
                  data.length,
                  this.pos,
                  (er, bytes) => {
    if (er) {
      if (this.autoClose)
        this.destroy();
      return cb(er);
    }
    this.bytesWritten += bytes;
    cb();
  }
```
This leads to pipe and other calls just hanging when an error occurs during writing. Adding `this.emit('error', er);` to the callback handler seems to fix the issue but I don't know if this is the correct fix.
```
  this.sftp.write(this.handle,
                  data,
                  0,
                  data.length,
                  this.pos,
                  (er, bytes) => {
    if (er) {
      if (this.autoClose)
        this.destroy();
      this.emit('error', er);
      return cb(er);
    }
    this.bytesWritten += bytes;
    cb();
  }
```
Let me know if I should open a PR with this change or if there is already a mechanism in the library for handling this situation and I just missed it.

**Comment by mscdex** [comment]
Node should already be handling this and emitting the `'error'` event when an error is passed to the callback passed to a stream's `_write()`.
