### ISSUE TITLE
diffie-hellman-group14-sha1 not supported

### ISSUE THREAD

**Issue by bannisa** [mscdex/ssh2#1276]
I am using this library to connect to network equipment that can only supports diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1 as key exchange algorithms. 

Here is the code I am using
    const conn = new Client();
    conn.on('ready', () => {
    console.log('Client :: ready');
    conn.shell((err, stream) => {
        if (err) throw err;
        stream.on('close', () => {
        console.log('Stream :: close');
        conn.end();
        }).on('data', (data) => {
        console.log('OUTPUT: ' + data);
        });
        stream.end('enable\nshow ip int brief\nexit\nexit');
    });
    }).connect({
    host: '10.0.0.2',
    port: 22,
    username: 'admin',
    key: ['diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1']
    });

Below is the output from the network device.

Feb 28 15:48:58.361: %SSH-3-NO_MATCH: No matching key algorithm found: client curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512 
server diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1

diffie-hellman-group14-sha1 is not supported.

**Comment by mscdex** [comment]
You need to use the `algorithms` option in your connection config object.

**Comment by bannisa** [comment]
@mscdex answered this. diffie-hellman-group14-sha1 must be specified in the **algorithms** object. This has solved my issue, thanks.
