### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by vahidvdn** [mscdex/ssh2#1277]
This is my configuration object:

```javascript
const tunnelConfig = {
    host: 'xxx.xx.xxx',
    port: 22,
    username: 'root',
    privateKey: require('fs').readFileSync('/Users/myusr/.ssh/id_rsa'),
    passphrase: 'mypassphrase',
    tryKeyboard: true
  };
```

This is how I connect to DB with Sequel Ace via ssh:
<img width="499" alt="Screen Shot 2023-03-05 at 11 45 25 PM" src="https://user-images.githubusercontent.com/11078601/222990312-20edf1dc-fecb-48a7-b90a-5d35da1c74e4.png">

I also tested `tryKeyboard` and `.on('keyboard-interactive'` but no chance. Any idea?

**Comment by mscdex** [comment]
Possibly https://github.com/mscdex/ssh2/issues/989

**Comment by mscdex** [comment]
The aforementioned fix has now been committed and will be in a release soon. If you are still encountering the same issue after the fix, let me know.
