### ISSUE TITLE
Ehancement: Support additional SFTP status codes

### ISSUE THREAD

**Issue by slifty** [mscdex/ssh2#1278]
The [SFTP spec](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-9.1) has a long list of status codes, but only the first few seem to be [supported by this library](https://github.com/mscdex/ssh2/blob/dc03f2757e3c549c18db0b98005ca3efee2e83e1/lib/protocol/SFTP.js#L32-L58).

Could we add support for the full list of sftp status codes?  (I'll open a PR for this in hopes it will be considered!)

```
SSH_FX_OK                            0
SSH_FX_EOF                           1
SSH_FX_NO_SUCH_FILE                  2
SSH_FX_PERMISSION_DENIED             3
SSH_FX_FAILURE                       4
SSH_FX_BAD_MESSAGE                   5
SSH_FX_NO_CONNECTION                 6
SSH_FX_CONNECTION_LOST               7
SSH_FX_OP_UNSUPPORTED                8
SSH_FX_INVALID_HANDLE                9
SSH_FX_NO_SUCH_PATH                  10
SSH_FX_FILE_ALREADY_EXISTS           11
SSH_FX_WRITE_PROTECT                 12
SSH_FX_NO_MEDIA                      13
SSH_FX_NO_SPACE_ON_FILESYSTEM        14
SSH_FX_QUOTA_EXCEEDED                15
SSH_FX_UNKNOWN_PRINCIPAL             16
SSH_FX_LOCK_CONFLICT                 17
SSH_FX_DIR_NOT_EMPTY                 18
SSH_FX_NOT_A_DIRECTORY               19
SSH_FX_INVALID_FILENAME              20
SSH_FX_LINK_LOOP                     21
SSH_FX_CANNOT_DELETE                 22
SSH_FX_INVALID_PARAMETER             23
SSH_FX_FILE_IS_A_DIRECTORY           24
SSH_FX_BYTE_RANGE_LOCK_CONFLICT      25
SSH_FX_BYTE_RANGE_LOCK_REFUSED       26
SSH_FX_DELETE_PENDING                27
SSH_FX_FILE_CORRUPT                  28
SSH_FX_OWNER_INVALID                 29
SSH_FX_GROUP_INVALID                 30
SSH_FX_NO_MATCHING_BYTE_RANGE_LOCK       31
```

**Comment by mscdex** [comment]
That's for a later SFTP version. `ssh2` implements SFTP version 3, like OpenSSH does.

On a related note, it unfortunately seems that the IETF has recently removed the documents for all but the latest SFTP version on their website. [This is the reference for SFTP version 3](https://web.archive.org/web/20221007230001/datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02).

**Comment by slifty** [comment]
Ah thank you!  Appreciate the clarity.
