### ISSUE TITLE
Cannot install on windows10 with VS2022

### ISSUE THREAD

**Issue by altmind** [mscdex/ssh2#1280]
You are using a package cpu-features that uses an outdated version of package buildcheck(v0.0.3) that does not recognize VS2022 in windows(10).

The cpu-features issue is almost a year now https://github.com/mscdex/cpu-features/issues/10

Should we switch to cpu-features fork and change in package.json?
` "optionalDependencies"  "cpu-features": "~0.0.4"`

to 
` "optionalDependencies"  "cpu-features": "git+https://github.com/altmind/cpu-features.git#v0.0.5"`

**Comment by mscdex** [comment]
This should be solved by 6f3e9dd51d7c7d43da4b919fb3189c850923697a.
