### ISSUE TITLE
Show message after login successful

### ISSUE THREAD

**Issue by kakopappa** [mscdex/ssh2#1282]
Hi, 

Just wondering whether it's possible to send a message to back when the client login is successful.

eg: Message Of The Day:
https://serverfault.com/questions/1123573/ssh-server-show-message-after-login-successful
https://serverfault.com/questions/407033/how-can-i-edit-the-welcome-message-when-ssh-start

**Comment by mscdex** [comment]
To be clear, there is no way to do this without the client attempting to open an interactive shell (you could do it when the execute a non-interactive command too, but that would be very disruptive), so it would not work if the client connects and only forwards outbound or inbound connections for example.

However, when you accept a client's request for an interactive shell, you are given a bidirectional stream, so you can write whatever you want to it.

**Comment by kakopappa** [comment]
Thanks!
