### ISSUE TITLE
Error: -bash: ssh-keygen: command not found 

### ISSUE THREAD

**Issue by as2r9** [mscdex/ssh2#1283]
While creating the Private and the public key inside my server, I am getting this error. If i try to do the installations using 
`sudo xcode-select --install
`

I use a macOS system and am even unable to execute the sudo command inside the server.

If i try to execute this i am getting the following error
<img width="253" alt="image" src="https://user-images.githubusercontent.com/129253777/228435890-f33fbef3-6483-40ef-a5dd-35da10a87dca.png">
To solve this i tried
```
sudo apt-get update
sudo apt-get install ssh
ssh-keygen -t rsa -b 2048 -f /path/to/private/key
```
But am still unable to do

**Comment by mscdex** [comment]
I think you're posting this issue in the wrong repository. This is for the `ssh2` node.js module and has nothing to do with sudo, installing packages, or Docker.

**Comment by as2r9** [comment]
When i was trying the following code i got the error while connection and to rectify that i used the above mentioned code and got that error
`const fs = require('fs');
const { Client } = require('ssh2');

const privateKey = fs.readFileSync('/path/to/private/key');

const conn = new Client();

conn.on('ready', () => {
  console.log('Connected to remote server');
  
  // execute a command on the remote server
  conn.exec('ls -l', (err, stream) => {
    if (err) throw err;

    stream.on('close', (code, signal) => {
      console.log(`Command exited with code ${code} and signal ${signal}`);
      conn.end();
    }).on('data', (data) => {
      console.log(`Received data: ${data}`);
    }).stderr.on('data', (data) => {
      console.log(`Received error data: ${data}`);
    });
  });
});

conn.on('error', (err) => {
  console.error(`Error connecting to remote server: ${err.message}`);
});

conn.connect({
  host: 'remote-server',
  port: 22,
  username: 'user',
  privateKey: privateKey
});
`

**Comment by mscdex** [comment]
I don't understand the problem you're having. You'll need to be more specific as I'm still not sure if this is related to `ssh2` or not.
