### ISSUE TITLE
How to listen for journalctl like events?

### ISSUE THREAD

**Issue by sunsetlover36** [mscdex/ssh2#1287]
Hey there!

I'm executing `sudo journalctl -u service -f --no-hostname` command and I want to listen for incoming logs. How to do it?

Or another example:
I'm executing `git clone ...` command but all that I'm receving is `Cloning into...`

My code:
```
shell
  .on('close', (code, signal) => {
    console.log('Stream :: close :: code: ' + code + ', signal: ' + signal)
  })
  .on('data', (data) => {
    console.log('STDOUT: ' + data)
  })
  .stderr.on('data', (data) => {
    console.log('STDERR: ' + data)
  })
shell.write(command)
```

I don't receive any output when using `journalctl`, just plain command in return.

Thanks for the answer in advance.

**Comment by mscdex** [comment]
First, interactive shells (assuming you're using `ssh.shell()` here) don't have/utilize a separate `stderr` stream, so you'll never get anything on that stream.

Secondly, I don't have any advice for your specific commands as interactive shells just display output -- there is no stdout/stderr or exit codes from individual commands or anything like that. However if you're actually using `ssh.exec()` to run your commands, you may need to request a pty to be allocated for some programs, which is not done by default (`ssh.shell()` *does* do this by default). That can be done by setting the `pty` option in the options object passed to `ssh.exec()`.

**Comment by sunsetlover36** [comment]
And one more question please
<img width="150" alt="image" src="https://user-images.githubusercontent.com/119140647/230615165-c2c6a8bf-8440-444d-a4c7-5092e97b4a3b.png">

How to read such output? When user needs to press "Enter" to read more and more lines. For such output I don't receive any stdout/stderr though.

I apologize in advance for beginner questions as I started to use `ssh2` only few days ago.

**Comment by mscdex** [comment]
You can write whatever you need/want to the stream, whether that's a newline to simulate pressing "enter" or anything else. You're probably better off instructing whatever program(s) to operate in a non-interactive way if possible though to make things easier.

Either way, this is beyond the scope of `ssh2` as it's program/command-specific.
