### ISSUE TITLE
Retrying password authentication with different username

### ISSUE THREAD

**Issue by dmpriso** [mscdex/ssh2#1288]
We have an SSH client connecting to this library which allows for trying a different username if password-based login has failed.

I failed to find something disallowing that in RFC 4252, but this fails because:

1. https://github.com/mscdex/ssh2/blob/master/lib/server.js#L1257 doesn't reset `authCtx`
2. Second try with different username then subsequently fails with `PROTOCOL_ERROR` due to the username check here https://github.com/mscdex/ssh2/blob/master/lib/server.js#L1065

Would it be possible to just reset the `authCtx` to undefined at pt. 1?

**Comment by mscdex** [comment]
I believe the behavior falls under [this section of RFC 4252](https://www.rfc-editor.org/rfc/rfc4252#section-5) where it says:

> If it is unable to flush an authentication state, it MUST disconnect if the 'user name' or 'service name' changes.

FWIW the OpenSSH server does [the same thing](https://github.com/openssh/openssh-portable/blob/51875897b81b5c21b80c256a29597916edbde454/auth2.c#L312-L317).

**Comment by dmpriso** [comment]
I see (although I find it contradictiory - in the cited section it also says 
> The 'user name' and 'service name' are repeated in every new authentication attempt, and MAY change

Still I see OpenSSH does the same. Thanks for the clarification!

**Comment by mscdex** [comment]
Right, the RFC is saying a client is allowed to try it, but it's not guaranteed that the server will support it.

**Comment by mscdex** [comment]
Closing this as I'm siding with OpenSSH on this one, it's probably not a good idea to support this.
