### ISSUE TITLE
Server publickey auth method stopped working

### ISSUE THREAD

**Issue by gilad-deel** [mscdex/ssh2#1289]
```
import {readFileSync} from 'fs';
import ssh2 from 'ssh2';

const server = new ssh2.Server({hostKeys: [readFileSync('host.key')]}, (client, info) => {
    console.log('connection', info);
    client.on('authentication', (context) => {
        console.log('authentication', context.username, context.method);
        switch (context.method) {
            case 'publickey':
                return context.accept();
        }
        context.reject();
    });
});
server.listen(2222, '0.0.0.0', function () {
    console.log('Listening on port ' + this.address().port);
});
```

```
$ ssh -p 2222 -i ~/.ssh/mykey test@127.0.0.1    
test@127.0.0.1's password: 
Permission denied, please try again.
```

```
Listening on port 2222
connection {
  ip: '127.0.0.1',
  family: 'IPv4',
  port: 60678,
  header: {
    greeting: '',
    identRaw: 'SSH-2.0-OpenSSH_9.0',
    versions: { protocol: '2.0', software: 'OpenSSH_9.0' },
    comments: undefined
  }
}
authentication test none
authentication test keyboard-interactive
authentication test password
```

I'm using latest version of `ssh2`., I never receive a challenge for a public key. I've tried to login with several keys (RSA, DSA etc) - none is challenging the server.

What am I missing here?

Thanks.

**Comment by mscdex** [comment]
Perhaps there is something wrong with the key you're trying to use (e.g. permissions). You can try adding `-vvv` to your OpenSSH client command line, it might clue you in as to why it's not trying the key you've specified.

**Comment by giladno** [comment]
Thanks @mscdex , I do notice now "no mutual signature algorithm" and found out SHA1 is deprecated. Generating ED25519 based keys did solve the problem - thanks a lot!

Reference: https://confluence.atlassian.com/bitbucketserverkb/ssh-rsa-key-rejected-with-message-no-mutual-signature-algorithm-1026057701.html

**Comment by mscdex** [comment]
The issue with the RSA key signature algorithm should be fixed soon, see https://github.com/mscdex/ssh2/issues/989.

**Comment by mscdex** [comment]
The aforementioned fix has now been committed and will be in a release soon.
