### ISSUE TITLE
env does not work

### ISSUE THREAD

**Issue by cruiseliu** [mscdex/ssh2#1293]
I expect the following script to output `test`, but it outputs `/usr/local/sbin:/usr/local/bin:/usr/bin` instead.

ssh2 version: 1.11.0
node.js version: 18.15.0
openssh version: 9.3p1 (packaged by [archlinux](https://archlinux.org/packages/core/x86_64/openssh/))

```js
import { Client } from 'ssh2';
const conn = new Client();
conn.on('ready', () => {
    conn.exec('echo $PATH', { env: { PATH: 'test' } }, (err, stream) => {
        stream.on('close', () => { conn.end(); });
        stream.on('data', (data) => { console.log(String(data)); });
    });
});
conn.connect({ host: '127.0.0.1', username: 'tmp', password: 'password' });
```

**Comment by mscdex** [comment]
Environment variables can easily be restricted/ignored by the server. For OpenSSH servers for example, this would be configured via the `AcceptEnv` configuration option.

**Comment by cruiseliu** [comment]
So it depends on the server setup and in many cases it will not work, and therefore we should never rely on it.
Suggest to clarify it in the doc. Thanks.

**Comment by mscdex** [comment]
Well, the same could be said about anything sent by an ssh client. SSH servers may restrict what commands you can execute, may refuse interactive sessions, may refuse port forwards, etc. It all depends on the server configuration.
