### ISSUE TITLE
server detect -o options

### ISSUE THREAD

**Issue by rgillan** [mscdex/ssh2#1295]
Hello,
Implementing a reasonably comprehensive server using this excellent module.  Already have shell/pty and -L tunnels working.  Have seen #1065 but this appears to be discussing the client side.  Trying to pass -o options to the server on the ssh command line.  Have looked at the session.on('env') event when using something like
-o "SendEnv=LC_newvar newvalue"
and the ssh gets connected without error, but the env.info object only has {"key":"LANG","val":"en_AU.UTF-8"}
Is there any way to retrieve the arbitrary key/values from the -o command line arguement.
Any help gladly appreciated, Rob

**Comment by rgillan** [comment]
Looks like it's an OSX side thing, if I simply send -o SendEnv=PATH it appears in the env event

**Comment by mscdex** [comment]
AFAIK `SendEnv` should work as long as the specified environment variable names exist at the time of connection. I'm not sure if they have to be set to a non-empty value though.
