### ISSUE TITLE
Error running sudo commads using ssh2.

### ISSUE THREAD

**Issue by mai1x9** [mscdex/ssh2#1300]
**Error: When below code is run,**
```
ssh.exec("sudo cat /etc/postgresql/12/main/pg_hba.conf", (err, stream) => {} )
```
I got error:
```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper\n',
```

When `-S` is passed,  
```
ssh.exec("sudo -S cat /etc/postgresql/12/main/pg_hba.conf",  {stdin: "XXXXXXX"}, (err, stream) => {} )
```
where `XXXX` is password, the temrinal hangs forever. I have tried appending `\n` to password but did not work.
I have passed other arguments like 
```
{execOptions: {pty: true}, stdin: "...."}
```
and
```
{options: {pty:true}, stdin: "..."}
```
Both of them did not work. How to solve this.

-------
Could anyone please provide a sample code how to run sudo commands using ssh.exec

**Comment by mai1x9** [comment]
I have done it in another way as 
```
echo -e "PASSSWORD\n" | sudo -S {COMMAND}
```
and this worked. However using `{stdin}` as option did not work

**Comment by mscdex** [comment]
There is no `stdin` option for `exec()` with `ssh2`. The writable side of `stream` represents stdin.

**Comment by mai1x9** [comment]
> There is no `stdin` option for `exec()` with `ssh2`. The writable side of `stream` represents stdin.

yes I could figure it out. the channel. `channel.write()` does the trick. thanks.
