### ISSUE TITLE
tcpip forward best practice

### ISSUE THREAD

**Issue by ptorrent** [mscdex/ssh2#1301]
Hello,

What is the best practice for forwarding request to a local service.

In this example the service is listening on port 4321

```
client.on('tcpip', function(accept, reject, info) { 
		var opt = {
			host  			: info.destIP, //127.0.0.1
			port 			: info.destPort //3221
               }
		var downstream 		    = accept(); 
		var connect    				= require('net').connect(opt)
		downstream.pipe(connect).pipe(downstream);
})
```

Is that a correct way to do the forwarding ?

**Comment by mscdex** [comment]
There really is no "correct" way. Aside from missing error handling (e.g. `'error'` events on the streams), there's nothing really wrong with what you're doing. You might want to do host and/or port checking though, to make sure the client isn't trying to connect to something other than what you're expecting, unless of course you want to allow any host and any port.
