### ISSUE TITLE
sftp server

### ISSUE THREAD

**Issue by ptorrent** [mscdex/ssh2#1307]
Hello there !

Do you've a working example for sftp server ? I tried yours with filezilla and this is the message I get:
```
Statut :	Listing directory /tmp/foo.txt
Erreur :	Unknown eventType 37
Erreur :	Impossible de récupérer le contenu du dossier
```

Here the example i'm talking about:
https://github.com/mscdex/ssh2/blob/master/examples/sftp-server-download-only.js

Thanks for your help

**Comment by mscdex** [comment]
The available events you can listen for and implement are listed [here](https://github.com/mscdex/ssh2/blob/master/SFTP.md), perhaps Filezilla is sending more requests than what is implemented in the example you linked to.

**Comment by ptorrent** [comment]
Thanks for your answer, yes I've read the documentation but a bit hard to understand for me.

Is it possible to make async call in READDIR events ? as the event is flooding unitl EOF ?


```
sftp.on('READDIR', function(reqId,){
asyncCall(function(){ 
        sftp.name(reqId, [ ... ])
    } )
})
```

**Comment by mscdex** [comment]
You can do whatever you want in the event handlers because a response isn't sent until you explicitly send one (e.g. `sftp.name()`).

**Comment by ptorrent** [comment]
But I've to call after sftp.name is send ?

Not with the same reqId I suppose ?

sftp.status(reqId , ssh2.utils.sftp.STATUS_CODE.EOF)

**Comment by ptorrent** [comment]
Ok I think I understood and now it's work. I've an other question for you ! What wuold be the best practive to forward a stream to the open event:


```
sftp.on('READ', function(reqId, buffer, offset, length){
					var stream = downloadFile(currentOpen)
					if(stream.__pendingBuffer){
						console.error('PIPE')
						sftp.data(reqId, stream.__pendingBuffer);
						stream.next()
					}
					else{
						console.error('ignore',offset, length)
					//	sftp.status(reqId, ssh2.utils.sftp.STATUS_CODE.EOF)
					}

})
```

**Comment by mscdex** [comment]
You can't really use a stream because the client can request any offset. You would need to either have the data locally or have wherever you're getting the data from be able to accept an offset and a length.

**Comment by ptorrent** [comment]
erf.. that was what I'm thinking... sad story
