### ISSUE TITLE
Crash despite registered error handler

### ISSUE THREAD

**Issue by AuspeXeu** [mscdex/ssh2#1308]
```
import { Client as SSHClient } from 'ssh2';
const ssh = new SSHClient();
ssh.on('error', (err) => console.log(err))
...
ssh.connect({...});
```
Leaves me with the following error crashing the application. Shouldn't this not be the case? What did I miss?

![image](https://github.com/mscdex/ssh2/assets/2115696/e59773ed-d839-4baa-8189-a39a78b602ce)

**Comment by axkibe** [comment]
Are you sure your application is crashing? Because if there is no more network, file or timeout activity going on, node.js will simply end, because there is nothing left to do. And the message is as you said the result of your console.log

**Comment by AuspeXeu** [comment]
This did the trick.
![image](https://github.com/mscdex/ssh2/assets/2115696/ed087874-e69a-4f07-9a59-d746bea1383c)
