### ISSUE TITLE
Please remove "pure javascript" from this project's description.

### ISSUE THREAD

**Issue by rubythulhu** [mscdex/ssh2#1310]
We ended up using this package based on the above claim, and have no end of issues around the fact that, despite this project claiming to be "pure javascript", the binary module here https://github.com/mscdex/ssh2/tree/master/lib/protocol/crypto causes non-deterministic builds because when node-gyp generates a Makefile, the ordering of Makefile dependencies is not deterministic, so this module re-compiling on every build causes the built .zip's sha sum to change every time, forcing our system to re-deploy any component built with ssh2 every time.

This claim is outright false, this package is absolutely not pure-js if it has an embedded c++ dependency. I'm sure many other people who use this have no idea this was building binary modules under the hood.

**Comment by mscdex** [comment]
All binary addons used by this module are completely optional, that's what makes it pure javascript.

**Comment by rubythulhu** [comment]
Oh! How do we disable it then? README doesn't mention binary node modules at all, nor how to disable them. 

We don't have ssh2 as a direct dependency, it's a dependency of https://github.com/theophilusx/ssh2-sftp-client which we are using for sftp functionality. Do we need to contact them and get them to make code changes to stop this binary dependency from being required? Or is there something we can do in our code to fix this?

**Comment by mscdex** [comment]
That's entirely dependent upon whatever package manager you're using. npm for example allows you to explicitly disable install scripts and ignore optional dependencies entirely. I can't speak for other package managers.

**Comment by rubythulhu** [comment]
I suspect that these modules being built by esbuild is also a factor.

But I'd be worried about applying that change globally to all of our packages, and that option sounds like it's an "all or nothing" type of deal. 

how does the optional bit work? does it just attempt to load the binary module, and fall back if it fails? I suspect that this is not the case, because:
* `ssh2-sftp-client` doesn't contain `crypto` or `sshcrypto` anywhere in its source code, and doesn't directly import/require your binary module.
* we had a build issue where this binary module was not being included in our deployment package, and that deployment (an AWS Lambda) failed at runtime because this binary module wasn't there (which explains why i was shocked to hear you call this an "optional" dependency -- the late nights i've worked have strongly implied that this is not optional).

**Comment by mscdex** [comment]
> how does the optional bit work? does it just attempt to load the binary module, and fall back if it fails?

Yes.

> * we had a build issue where this binary module was not being included in our deployment package, and that deployment (an AWS Lambda) failed at runtime because this binary module wasn't there (which explains why i was shocked to hear you call this an "optional" dependency -- the late nights i've worked have strongly implied that this is not optional).

I would need to see some proof that missing optional addons were causing you problems.

**Comment by rubythulhu** [comment]
I have had a long conversation in evanw/esbuild#3173. This problem goes far deeper than this package. There's apparently problems in the AWS Runtime, node-gyp, and possibly in SST that all contribute to this issue.

Apparently, due to an issue in AWS lambda where their runtime breaks the `try {require} catch {}` (in ssh2 itself, and the compiled esbuild version adds another `catch{}` layer) and causes the runtime error, the only ways to fix this are all different variations of "remove the part where ssh2 tries to load the binary module entirely":

* make an in-house private fork of both `ssh2` and `ssh2-sftp-client`, which will likely lead to them becoming outdated compared to the upstream versions
* make an in-house private fork of `ssh2` only, and use  [this](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to inject it instead, though we would have to also include `ssh2` as a top-level dependency, and manually keep `ssh2-sftp-client` and `ssh2` in sync, and that would be difficult to enforce without writing custom tooling.
* use [yarn patch](https://yarnpkg.com/cli/patch) to completely patch out import of the binary module
* create an esbuild plugin to do the same thing.

I would like to apologize for my snarkiness in this issue. I've spent so much effort trying to get this binary module to work. It legit blew my mind to hear you say this was optional, because that contradicted my world view, and has since led me down a rabbit-hole of "what actually causes this?". 

I have a bunch of bad options, because AWS lambda completely breaks the `try{}catch{}` part, and something in the build process (maybe sst? not us, and esbuild says its not them) causes this module to be recompiled for each individual subcomponent of our platform, when it could instead copy the `.node` file from node_modules (which we have cached between ci runs), and `node-gyp` that builds binary node modules non-deterministically (if i `yarn install; mv node_modules node_modules2; yarn install; diff -uNr node_modules node_modules2`, the only differences are dependency ordering within a makefile, and the binary modules themselves).

**Comment by mscdex** [comment]
I'm not sure there is anything to be done in `ssh2` itself. You should try lodging an issue/feature request on node-gyp's issue tracker about the Makefile issue.

**Comment by theophilusx** [comment]
rubythulhu ***@***.***> writes:

>
> I would like to apologize for my snarkiness in this issue. I've spent so much effort trying to get this
> binary module to work. It legit blew my mind to hear you say this was optional, because that contradicted
> my world view, and has since led me down a rabbit-hole of "what actually causes this?".
>

I wanted to acknowledge and thank you for your apology and refreshing
honesty. People like @mscdex put in significant effort to support
modules like ssh2 and simple thanks and acknowledgement goes a long way
towards maintaining the motivation to continue contributing.  Too few
exhibit the intellectual maturity you have demonstrated and it needs to
be acknowledge and encouraged. Thanks you.
