### ISSUE TITLE
Trying to use SSH2 in MongoDB Functions - Error -  failed to compile source for module './protocol/keyParser.js'

### ISSUE THREAD

**Issue by madhuridara** [mscdex/ssh2#1314]
failed to compile source for module './protocol/keyParser.js': SyntaxError: node_modules/ssh2/lib/protocol/keyParser.js: Line 149:61

Hi,

I am trying to use the SSH2 package in MongoDB Atlas with a basic connect code like this:

 const { NodeSSH } = require('node-ssh');
  
  const ssh = new NodeSSH();

   ssh.connect({
            host: 'xxx.xx.xx.xxx',
            username: 'user',
            password: 'pwd'
        });
  
   ssh.close()

It fails with the above error.

I am however able to use it successfully outside MongoDB Atlas, on cmd shell.

Please advise.

**Comment by mscdex** [comment]
What version of `ssh2` are you using? Please make sure you are using the latest version.

Also, are you using a supported version of node (v10.16.0 or newer)?
