### ISSUE TITLE
Add .npmignore file to exclude test code in published package

### ISSUE THREAD

**Issue by jamesoleary123** [mscdex/ssh2#1315]
Had an issue recently where some security scanning was finding issues with some test code.

The scanner was incorrectly finding these files as potential security issues - its test code so was a false positive.

https://github.com/mscdex/ssh2/tree/v1.14.0/test/fixtures

That said though think it be better to add a .npmignore to exclude the test folder from the published artifact.

**Comment by mscdex** [comment]
I'm not really interested in removing such files at this time.
