### ISSUE TITLE
All configured authentication methods failed, while working with normal ssh command

### ISSUE THREAD

**Issue by cedricbieder** [mscdex/ssh2#1317]
Hi guys,

I try to connect via the package from an ubuntu20.04 machine to a openSUSE 11.4.

A normal ssh command with the terminal works here
```ssh user@host``` 
or 
```sshpass -p 'password' ssh user@host```

But if I try it with the package I get:

> Error: All configured authentication methods failed
    at doNextAuth (/home/ubuntu/testNode/node_modules/ssh2/lib/client.js:865:21)

```
const { Client } = require('ssh2');

const conn = new Client();
 conn.on('ready', () => { console.log('Client :: ready'); conn.exec('uptime', (err, stream) => { if (err) throw err; 
stream.on('close', (code, signal) => {
console.log('Stream :: close :: code: ' + code + ', signal: ' + signal); conn.end();
}).on('data', (data) => {
console.log('STDOUT: ' + data);
}).stderr.on('data', (data) => {
console.log('STDERR: ' + data);
});
});
}).connect({
host: 'host', port: 22, username: 'user', password: 'password'
});
```

I have no idea why this is happening. 
I hope some of you can help me here.

Thank you

**Comment by mscdex** [comment]
Are you using the latest version of `ssh2`?

**Comment by cedricbieder** [comment]
Yes, I am using ssh2@1.14.0.

**Comment by mscdex** [comment]
Next you should validate how you're actually authenticating with the OpenSSH client. Use `ssh -vvv` when connecting and it should log whether it's using really using the password or silently using a key for example.

If it is using the password, it may highlight whether it's using the password authentication method or the keyboard-interactive authentication method. If it's using the latter, you will need to set `tryKeyboard: true` in your `ssh2` connection config and appropriately add and use a `'keyboard-interactive'` event handler on the connection object to answer (password) prompts sent by the server.

**Comment by axkibe** [comment]
Your code works for me.
tested:
OpenSSH_8.4p1
OpenSSH_9.0p1 

You sure your username/password/hostname is correct, you have nothing strange going on in your ssh-config and you are not actually using the ssh keys as mscdex suggest when using your ssh client test?

**Comment by cedricbieder** [comment]
Thank you for the hint. It seems to be the keyboard-interactive:
`ssh ip -vvv`:

`debug2: we did not send a packet, disable method
debug3: authmethod_lookup keyboard-interactive
debug3: remaining preferred: password
debug3: authmethod_is_enabled keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug3: send packet: type 50
debug2: we sent a keyboard-interactive packet, wait for reply
debug3: receive packet: type 60
debug2: input_userauth_info_req
debug2: input_userauth_info_req: num_prompts 1
`

i added to my code:

```async function testSsh2() {

const { Client } = require('ssh2');

const conn = new Client();
 conn.on('ready', () => { console.log('Client :: ready'); conn.exec('uptime', (err, stream) => { if (err) throw err; 
    stream.on('close', (code, signal) => {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal); conn.end();
    }).on('data', (data) => {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', (data) => {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: 'my_ip', port: 22, username: 'my_username', password: 'my_password',
 tryKeyboard: true,
  onKeyboardInteractive: (name, instructions, instructionsLang, prompts, finish) => { 
        console.log('keyboard auth')
        if (prompts.length > 0 && prompts[0].prompt.toLowerCase().includes('password')) { 
            finish(['my_password']);
         } else {
             finish([]);
         }
     }
});
}
```

but it just timeouts:

`Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/home/ubuntu/testNode/node_modules/ssh2/lib/client.js:1116:23`


Any other ideas?

Best

**Comment by mscdex** [comment]
Instead of `onKeyboardInteractive`, you have to use the standard node.js EventEmitter interface for attaching an event handler (`.on()`), much like your code has already done for the `'ready'` event.

**Comment by cedricbieder** [comment]
ah yes, thank you. that seems to work.





btw: now i found this [stackoverflow_entry](https://stackoverflow.com/questions/36122217/error-all-configured-authentication-methods-failed-levels-client-authenticati), which described the whole thing again :)
