### ISSUE TITLE
Support for public key identity files for querying SSH agents

### ISSUE THREAD

**Issue by matthew-e-brown** [mscdex/ssh2#1318]
[(skip context)](#user-content-feature-request)

## Context

When using OpenSSH (i.e., `ssh` on the command line), the `IdentityFile` option is used to tell `ssh` which additional keys it should use to attempt to authenticate with the remote, alongside `IdentitiesOnly`, which tells `ssh` that it should use only the keys specified as `IdentityFile`s. As far as this library, which does not check any SSH config files, is concerned, `IdentitiesOnly` is implied; one key is given directly to `Client.connect` with the `privateKey` option, and it uses that for authentication. This is not a problem, and it works well enough&mdash;it is up to consumers of the library to select which key to use.

However, this starts to fall apart slightly when using the `agent` option to connect. In this case, the user has no private keys to provide to `Client.connect`, since the agent has them all. The way that OpenSSH handles this by default is by asking the agent for its list of keys, and then trying them one by one. This works fine in most cases, but will break for anybody with more than a few keys due to [the default limit of 6 attempts for authorization][authtries].

That breakage was remedied in OpenSSH sometime last year (at least, [it was documented sometime last year][changelog] \[commit `21625a6`\]). Now, `IdentityFile` and `IdentitiesOnly` can be used to skip trying every possible key with an agent:

> _[`ssh_config(5)`][identfile]:_
>
> `IdentityFile` may be used in conjunction with `IdentitiesOnly` to select which identities in an agent are offered during authentication.

As mentioned, this library already implies `IdentitiesOnly`, since all keys are provided directly as an option to `Client.connect`. What this library _doesn't_ support, however, is limiting the attempted keys by passing a public key. In the event that the SSH agent has more than six keys, this library simply fails outright to connect to any server with a low enough `MaxAuthTries` setting.

### Example

By adding several temporary keys to my agent, and modifying my server-side `authorized_keys` to require the last one, you can see that authentication fails before it ever gets to the correct key:

![OpenSSH-AgentFailure](https://github.com/mscdex/ssh2/assets/43387454/590c4718-5039-4b3e-b701-eab7da49cb33)

With OpenSSH, this can be fixed with `IdentityFile`+`IdentitiesOnly`:

![OpenSSH-AgentSuccess](https://github.com/mscdex/ssh2/assets/43387454/9c07298e-5895-4446-931e-62462c4524e2)

But with this library, without any `identityFile` or `publicKey` option, the authentication simply fails:

![ssh2-AgentFailure](https://github.com/mscdex/ssh2/assets/43387454/8d495cae-604c-48bd-869c-1d2bfd207820)

## <a href="#user-content-feature-request" id="feature-request">#</a> Feature request

It would be nice if there was a way to tell `Client.connect` which key from an SSH agent should be used. This would prevent authentication failures when using an agent that has more than the server's `MaxAuthTries` amount.

This could be done by passing a public key alongside the `agent` option, which `ssh2` would then explicitly use with the agent. Something like this:

```js
const conn = new Client();

conn
  .on('ready', () => {
    conn.exec(..., () => { ... });
  })
  .connect({
    host: 'somesite.com',
    username: 'matt',
    agent: '\\\\.\\pipe\\open-ssh-agent',
    publicKey: fs.readFileSync('~/.ssh/id_ed25519.pub'),
  });
```

It could maybe even be passed as part of an object with the path, which would disallow passing `publicKey` being passed without `agent`:

```js
conn
  .connect({
    host: 'somesite.com',
    username: 'matt',
    agent: {
      path: '\\\\.\\pipe\\open-ssh-agent',
      publicKey: fs.readFileSync('~/.ssh/id_ed25519.pub'),
    }
  });
```

I suppose that it could also be given directly as `privateKey` (which would be renamed to `identityKey` or something), to match how OpenSSH handles `IdentityFile` (which does double-duty). That would be a pretty breaking change, though, so I feel like the second option would probably be the best.

---

Sorry (:maple_leaf:) that this issue is so long. I would like to mention at the end here that I am willing and eager to implement/assist with implementing this feature, should you (the owner/maintainers here) like the idea.

P.S., As a followup question/mini second feature request, what's the current sentiment behind being able to specify multiple private keys (and public keys, once this feature is implemented)? That would allow the `privateKey` option, if given an array, to mimic how `IdentityFile` works in `~/.ssh/config`. This library already supports attempting multiple keys/authentication methods (like when `agent` is given), so I don't think that's too crazy of a question. Perhaps it could be made into a part of the same PR as this?

[identfile]: https://man.openbsd.org/ssh_config#IdentityFile
[authtries]: https://man.openbsd.org/sshd_config#MaxAuthTries
[changelog]: https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/ChangeLog

**Comment by mscdex** [comment]
I'm +0 on this as this should already be fairly easily achievable by extending the publicly available `OpenSSHAgent` and wrapping/overriding its `getIdentities()`.

> what's the current sentiment behind being able to specify multiple private keys

That's already achievable by setting a custom `authHandler` value in your connection config object.
