### ISSUE TITLE
Dumping encrypted ssh traffic with Wireshark

### ISSUE THREAD

**Issue by caltuntas** [mscdex/ssh2#1319]
I would like to see packets exchanged  during a session for educational/troubleshooting purposes. I use ssh2 library as a client to execute a simple "ls" command on a Ubuntu box. I know, first set of steps aren't encrypted and can be seen from Wireshark but my aim is also seeing the packets after "key exchange" phase. 

Wireshark has a dissector and it requires a file that contains following values to be able to decrypt the session. 

[https://gitlab.com/wireshark/wireshark/-/blob/release-4.0/epan/dissectors/packet-ssh.c#L1933](https://gitlab.com/wireshark/wireshark/-/blob/release-4.0/epan/dissectors/packet-ssh.c#L1933)

```c
    /* File format: each line follows the format "<cookie> <key>".
     * <cookie> is the hex-encoded (client or server) 16 bytes cookie
     * (32 characters) found in the SSH_MSG_KEXINIT of the endpoint whose
     * private random is disclosed.
     * <key> is the private random number that is used to generate the DH
     * negotiation (length depends on algorithm). In RFC4253 it is called
     * x for the client and y for the server.
     * For openssh and DH group exchange, it can be retrieved using
     * DH_get0_key(kex->dh, NULL, &server_random)
     * for groupN in file kexdh.c function kex_dh_compute_key
     * for custom group in file kexgexs.c function input_kex_dh_gex_init
     * For openssh and curve25519, it can be found in function kex_c25519_enc
     * in variable server_key.
     *
     * Example:
     *  90d886612f9c35903db5bb30d11f23c2 DEF830C22F6C927E31972FFB20B46C96D0A5F2D5E7BE5A3A8804D6BFC431619ED10AF589EEDFF4750DEA00EFD7AFDB814B6F3528729692B1F2482041521AE9DC
     */
```

The information provided above is given by considering openssh as a client. In my case, I tried to map these to ssh2 and dump required values by modifying the code little bit but it didn't work. Probably the values I dumped were wrong. Here is what I did

![image](https://github.com/mscdex/ssh2/assets/35517929/d324c5a0-3eaa-464f-8c1d-389eac813a72)
![image](https://github.com/mscdex/ssh2/assets/35517929/8adcb74f-565c-400e-b15f-dbb38816c263)
![image](https://github.com/mscdex/ssh2/assets/35517929/18a2a1e3-79d7-4319-957b-d298685bd9f4)
![image](https://github.com/mscdex/ssh2/assets/35517929/ee467530-81fb-4347-a76b-905465d9999e)

Could you point me to the right direction? It might be also added as a feature, if it makes sense. Thanks.

**Comment by mscdex** [comment]
I'm not really interested in adding support for this. The existing debug log functionality should suffice for most use cases.
