### ISSUE TITLE
Install Error on yarn v3. 

### ISSUE THREAD

**Issue by forest1102** [mscdex/ssh2#1322]
When installing using yarn v3, the following errors occurred.  
```bash
$ yarn install
...
➤ YN0000: │ ssh2@npm:1.11.0 STDOUT Usage Error: Couldn't find a script name "node-gyp" in the top-level (used by ssh2@npm:1.11.0). This typically happens because some package depends on "node-gyp" to build itself, but didn't list it in their dependencies. To fix that, please run "yarn add node-gyp" into your top-level workspace. You also can open an issue on the repository of the specified package to suggest them to use an optional peer dependency.
--
➤ YN0000: │ ssh2@npm:1.11.0 STDOUT
➤ YN0000: │ ssh2@npm:1.11.0 STDOUT $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
➤ YN0000: │ ssh2@npm:1.11.0 STDOUT Failed to build optional crypto binding
```

I think that in yarn v3, modules not listed in package.json dependencies can not be used due to strict package boundaries.  
Does the error above have an impact on running script?

**Comment by mscdex** [comment]
As the output says, it's an *optional* binding, so the only impact will be a (negative) performance impact. The module will still function just fine though.

**Comment by forest1102** [comment]
Thanks for confirmation.  
So, is there any reason why node-gyp is not listed on optional dependencies?

**Comment by mscdex** [comment]
Because npm has always bundled it and made it available for use in package scripts. I guess yarn doesn't (or at least maybe yarn v3).

**Comment by forest1102** [comment]
So, should i make PR to add node-gyp in optional dependencies?

**Comment by mscdex** [comment]
I don't think I'd prefer that since AFAIK it'd end up installing node-gyp twice for npm users.
