### ISSUE TITLE
keyboard-interactive authentication for SFTP does not work from CLI script

### ISSUE THREAD

**Issue by psaji1** [mscdex/ssh2#1326]
I am using ssh2 with NestJS. 
I have a script that is executed from CLI that connects to a third party SFTP that has keyboard-interactive authentication enabled. 
When I run the script from app or NestJS cron, it works fine. 
The same script does not work from the CLI script. I execute the script like this` npm run execute create_report`
From the script, it never get into the `keyboard-interactive` event. 
Sample code

```
conn.on('ready', async() => {
   console.log('ready')
}).on('close', () => {
  conn.end()
}).on('error', (err) => {
  console.log(err);
  conn.end();
}).on('keyboard-interactive', (name, instructions, instructionsLang, prompts, finish) => {
  console.log('keyboard')
  finish([detail.password]);
}).connect({
  host: detail.server,
  port: detail.port,
  username: detail.username,
  //password: detail.password,
  readyTimeout: 20000,
  tryKeyboard : true,
  debug: console.log
});
```

Here is the debug log
```
Custom crypto binding available
Local ident: 'SSH-2.0-ssh2js1.14.0'
Client: Trying xxxxxx on port 22 ...
```

**Comment by mscdex** [comment]
If it's not connecting at all (judging by the debug output you've provided), then it sounds like a firewall/networking issue, a `host`/`port` issue, or the remote server is dropping/not receiving the traffic. That's about all I can suggest.

Additionally, where your code is executed (whether interactively from a terminal or not) has no bearing on keyboard-interactive availability.

**Comment by psaji1** [comment]
telnet works fine. So I think there is no issue with network/firewall.
I am able to connect to SFTP from app with the same code. So no issue with host/port. 
Something going wrong on CLI. Can't figure out what it is.

**Comment by psaji1** [comment]
I was doing some debugging on client.js 
I noticed that when I execute the script from CLI, it does not enter this function here https://github.com/mscdex/ssh2/blob/master/lib/client.js#L762
I have no clue.
