### ISSUE TITLE
[HELP] SSH proxy tunnel thing

### ISSUE THREAD

**Issue by CyberFoxHax** [mscdex/ssh2#1331]
Forgive my second intrusion. But I've ran into a snag again.

I've been trying to build a relay for connecting securely to our own customer network. For that i use a middle man server, (this application). I've managed to get SSH and SFTP running, not optimally, but it works. But i also want it to be compliant with tunneling.

Such that i can connect to the relay with a standard ssh client like so `ssh node1234@masterserver.zerg -L 5900:localhost:5900`
and the final outcome would be that my `localhost:5900` will be forwarded to `node1234:5900`

(Since i don't use username for anything i decided to use it to select which node to connect to. So in this example node1234 is the name of the node)

I've been assembling pieces from
https://github.com/mscdex/ssh2/issues/698
https://github.com/mscdex/ssh2/issues/1285
https://github.com/mscdex/ssh2/issues/1255 (First comment is very informative and should be part of a document)

My code in a vacuum.
```javascript
new Server({hostKeys}).on("connection", (connection) => {
    connection.on('ready', () => {
        // i've seen some use on("request") but it does nothing on my version
        connection.on("tcpip", (accept, reject, info)=>{
            console.log("TCPIP ", info);


            var chan = accept();

            // same result
            /*net.createServer(()=>{
                console.log("net.server connect"); // never called
            }).listen(12588);*/

            const client2 = new Client();
            client2.on('ready', ()=>{
                client2.forwardOut("127.0.0.1", 12588, info.destIP, info.destPort, (err, chan2)=>{
                    if(err){
                        console.error(err.message); // (SSH) Channel open failure: Connection refused
                        return;
                    }
                    chan2.pipe(chan).pipe(chan2); // never
                });
            });
            client2.connect({ ... });


        });
    });
});
```

Please let me know if there's any more information you would like to know.

**Comment by mscdex** [comment]
If the connection is refused, you should `reject()` the tcpip request instead of `accept()`ing it early.

**Comment by CyberFoxHax** [comment]
I kept looking at https://github.com/mscdex/ssh2/issues/1285 and I was able to get it working

```javascript
new Server({hostKeys}).on("connection", (connection) => {
    connection.on('ready', () => {
        // i've seen some use on("request") but it does nothing on my version
        connection.on("tcpip", (accept, reject, info)=>{
            console.log("TCPIP ", info);

            const client2 = new Client();
            client2.on('ready', ()=>{
                client2.forwardOut(info.srcIP, info.srcPort, info.destIP, info.destPort, (err, chan2)=>{
                    if(err){
                        console.error(err.message);
                        reject();
                        return;
                    }
                    var chan = accept();
                    chan2.pipe(chan).pipe(chan2);
                });
            });
            client2.connect({ ... });


        });
    });
});
```

So the issue I was having is that the dentition server needs to actually run a service on the specified port. I can't understand why. SSH normally doesn't care if a port is available or not. It may print a warning in the console such as `channel 2: open failed: connect failed: Connection refused`. Oh shit, is that it?! That message comes from the server?
