### ISSUE TITLE
Support "glob" pattern matching

### ISSUE THREAD

**Issue by lee-campbell** [mscdex/ssh2#1334]
When accessing a server via command-line SFTP, ls calls support glob pattern matches (e.g. **/*.txt to match all files with the extension .txt).

It would be good if the `sftp.lstat()` method, for example, would also support this behaviour for my use-case, where I require an SFTP client to poll for files that match a glob pattern that is defined by a remote, unknown user (I can't coach their input and they would expect a glob to work as per the command line).

**Comment by mscdex** [comment]
Higher level functionality like that is not a very good fit for `ssh2`. I prefer to keep things as close to the protocol as possible and if people want to build on top of that, then they can do that.
