### ISSUE TITLE
tcpip/openssh.streamlocal Event Not Firing

### ISSUE THREAD

**Issue by jasondalycanpk** [mscdex/ssh2#1335]
Hi,

When implementing the following code the local port forwarding SSH option (-L) does not generate a server event:

**Server Code Snippet**
<pre>
client.on("tcpip", (accept, reject, info) => 
    {   console.log("Info: ", info);
        accept();

    });

client.on("openssh.streamlocal", (accept, reject, info) => 
    {   console.log("Info: ", info);
        accept();

    });
</pre>

The SSH command I run is as follows:

<pre>
ssh -N -L 127.0.0.1:8080:my-ssh-server.com:22 -p 44498 foo@localhost
</pre>

The SSH connection starts fine with login, etc. but neither of the above server events are fired.  Should another event be listened to to implement support for this command?

**Comment by mscdex** [comment]
`openssh.streamlocal` is for UNIX sockets, not TCP/IP (which is what your ssh client command line is using), so I would not expect that event to fire.

Can you post a complete, minimal example of the server-side code that reproduces the issue?
