### ISSUE TITLE
Some commands fail to execute using .exec, but can succeed on their own using the shell directly.

### ISSUE THREAD

**Issue by aiyayou725** [mscdex/ssh2#1336]
Hello, I used .exec to execute some commands, and the following error message appeared:

awk: (FILENAME=- FNR=1) warning: error writing standard output (Broken pipe)
output open debug 
Neither the JAVA_HOME nor the JRE_HOME environment variable is defined
At least one of these environment variable is needed to run this program

However, it works fine when executing the same command using the shell

**Comment by mscdex** [comment]
Most likely because your shell profile contains lines that modify the environment. This shell profile is not executed when you use `exec()`. That's not an `ssh2`-specific thing, that's just how ssh generally works.

**Comment by aiyayou725** [comment]
Forgot to mention, this situation only occurs on one Client calls .exec multiple times. Is this related to ssh2?

**Comment by mscdex** [comment]
> Is this related to ssh2?

I don't see how. My previous comment was specifically about the message regarding environment variables. The awk warning I can't really help you with. I'm also not sure why the number of `exec()` calls would change anything, unless there is some state being saved somewhere server-side or something.
