### ISSUE TITLE
SSH Client sending environment variable

### ISSUE THREAD

**Issue by rgillan** [mscdex/ssh2#1337]
Server side (ssh2) we are processing the session.on 'env' and using it to transfer required information to our server.  This works well from a typical ssh command line.  We are trying to create a ssh2 client passing the key information (working) but do not see any methods or ways to send the environment key/value to the server (to emulate the -o  SendEnv=X_ENVIRONMENT_VARIABLE ssh option).  Is this possible using the ssh2/client?

**Comment by mscdex** [comment]
You pass them in the options object to `shell()` or `exec()` on the client side.

**Comment by rgillan** [comment]
so just confirming the format, to set an environment var X_ENVVAR to "abcd" would be:
`client.shell({"X_ENVVAR":"abcd"}, (error,stream) => {...`
do not see the session.on env on the server side.  Appreciate your help

**Comment by rgillan** [comment]
thanks, bit of trial and error and we are passing it correctly.  We needed to have:
`client.shell({"env":{"X_ENVIRONMENT_VARIABLE":"desiredvalue"}}, (error,stream) => {....`
for it to work correctly

**Comment by alanhe421** [comment]
<img width="995" alt="image" src="https://github.com/user-attachments/assets/7d923fcb-89c7-4d33-8b47-5ae4077b7270">


echo $X_LOGIN_IP not works.

**Comment by mscdex** [comment]
@alanhe421 The server may be restricting what environment variables you can send. For OpenSSH servers, this is controlled by their `AcceptEnv` config option which by default allows nothing at all for security reasons.

**Comment by alanhe421** [comment]
> @alanhe421 The server may be restricting what environment variables you can send. For OpenSSH servers, this is controlled by their `AcceptEnv` config option which by default allows nothing at all for security reasons.

Thank you very much. I just checked and confirmed that this was indeed the issue.
