### ISSUE TITLE
ssh.end (resource disposal) method throwing error after migrating to node 18

### ISSUE THREAD

**Issue by parth19** [mscdex/ssh2#1339]
Here's abstract code to read a file on SFTP server using node-ssh package which is a wrapper on ssh2.

It was working fine till I was using node 16. But the ssh.dispose statement (which calls ssh2's end method for resource release) started throwing error after I migrated to node 18.
It is still able to connect with server and read file, but throws error while disposing connection.

Received the same error even after I tried with few other wrapper packages which in turn uses ssh2 lib.

It seems upgrade is required on ssh2 library to make resource release compatible with node 18. Would you be able to help with it.
Thanks in advance for any info / support.

Apologies if code is not very useful as it is written using a wrapper package, but below error statement would help as the error is thrown from ssh2 package.

Error :

```
Error: No response from server
    at cleanupRequests (node_modules/ssh2/lib/protocol/SFTP.js:2730:15)
    at SFTP.push (node_modules/ssh2/lib/protocol/SFTP.js:191:7)
    at onCHANNEL_CLOSE (node_modules/ssh2/lib/utils.js:50:13)
    at ChannelManager.cleanup (/usr/src/app/node_modules/ssh2/lib/utils.js:200:7)
```

Code : 

```js
import { NodeSSH } from 'node-ssh';
async function readFile(path: string): Promise<string> {
     let ssh: NodeSSH | null = null;
    try {
     const ssh = new NodeSSH()
      await ssh.connect({
          host, username, password
       })
      const sftp = await ssh.requestSFTP();
      const fstream = sftp.createReadStream(path);

       return await convertStreamToString(fstream);   // local function to convert stream into a string format using chunks &  Buffer
     } catch() {
       // throw error
     } finally {
      await ssh?.dispose();
     }
}
```

**Comment by mscdex** [comment]
I can't really help you with downstream modules as I'm not familiar with those codebases. What I can tell you is that "No response from server" just means that you sent a request and the connection was severed before a response was received for that request.

**Comment by SagnikPradhan** [comment]
@parth19 Did you ever figure out what was causing it?
