### ISSUE TITLE
Difference between forwardout and manual net connect

### ISSUE THREAD

**Issue by ptorrent** [mscdex/ssh2#1343]
Hello there !

Thanks for you awesome job. I've a question about forwarding net connection:

(I'm acting as a ssh server)

```
client.on('tcpip', function(accept, reject, info) { 
		var opt = {
			host  			: info.destIP, //127.0.0.1
			port 			: info.destPort //3221
               }
		var downstream 		    = accept(); 
		var connect    				= require('net').connect(opt)
		downstream.pipe(connect).pipe(downstream);
})
```

and

```
client.on('tcpip', function(accept, reject, info) { 
   var downstream 				= accept(); 
   client.forwardOut(info.srcIP, info.srcPort, info.destIP, info.destPort, (err, clientStream) => {
	clientStream.pipe(downstream).pipe(clientStream)
})
```

Or maybe I'm wrong, forwardOut is only for client ? SHould I use forwardIn ?

Not talking about security aspect etc... just about best way to forward socket on local service ?

THanks a lot for your answer !

**Comment by mscdex** [comment]
The first example seems sensible and is more or less typical.

The second example doesn't make sense, unless the client has asked for connections to be forwarded to them AND you really want a fake connection that echoes everything in both directions.
