### ISSUE TITLE
[HELP] How can i convert private key .ppk to .pem.

### ISSUE THREAD

**Issue by tusher-das** [mscdex/ssh2#1346]
const fs = require('fs');
const ssh2 = require('ssh2'); 

const ppkFile = 'path/to/your/key.ppk';
const pemFile = 'path/to/save/key.pem'; 
const keyContent = fs.readFileSync(ppkFile, 'utf8'); 
const convertedKey = ssh2.utils.parseKey(keyContent, 'auto');
const pemKey = convertedKey.getPrivatePEM(); 
fs.writeFileSync(pemFile, pemKey); 
console.log('Conversion complete. PEM key saved to:', pemFile);

here I am facing an error: 
{
  name: 'GeneralError',
  message: 'convertedKey.getPrivatePEM is not a function',
  code: 500,
  className: 'general-error'
}

**Comment by mscdex** [comment]
Most likely `convertedKey` is an `Error`, since `parseKey()` does not throw. My additional guess is that the issue is the same as https://github.com/mscdex/ssh2/issues/1140.

**Comment by AbiAbdullah** [comment]
In console.log(ssh2.utils.parseKey(keyContent, 'auto');) 
It says "Error: Unsupported key format
    at Object.parseKey".
