### ISSUE TITLE
forwardOut method local port forward doesn't work?

### ISSUE THREAD

**Issue by aeastern** [mscdex/ssh2#1350]
I want to access the container port on the remote server, my local net can not access remtoe container port directly, So I want to use ssh2's forwardOut() method to implement it, but it did not work!  My code looks  like this：
```javascript
const fs = require('fs');
const path = require('path');
const { Client } = require('ssh2');

const privateKeyPath = 'path/to/private-key.pem'; 
const privateKey = fs.readFileSync(privateKeyPath, 'utf8');

const sshConfig = {
  host: 'example.com', 
  username: 'your-username', 
  privateKey: privateKey, 
};

const localForwardConfig = {
  fromPort: 3000, 
  toHost: 'localhost', 
  toPort: 8080, 

const sshClient = new Client();

sshClient
  .on('ready', function () {
    console.log('SSH connection established');

    sshClient.forwardOut(
      '127.0.0.1', 
      localForwardConfig.fromPort,
      localForwardConfig.toHost,
      localForwardConfig.toPort,
      function (err, stream) {
        if (err) throw err;
        console.log(`Local forwarding from ${localForwardConfig.fromPort} to ${localForwardConfig.toHost}:${localForwardConfig.toPort} established`);
      }
    );
  })
  .connect(sshConfig);
```
Is the method I used wrong? I can get "Local forwarding from xxx", but it did not work!  When I use linux command "netstat -tln | grep xxx" to check xxx port , there are nothing.  But when I use ssh -L xxx:portx:yyy:porty foo@blabla to implement it ,  it can work normally!  
And use "netstat -tln | grep xxx" to check xxx port alse works normally!

**Comment by mscdex** [comment]
`stream` _is_ your connection to that destination host and port. If you want to something outside of your process to be able to hook into that stream, then you need to create a TCP server that does so.

**Comment by kaspiyaa** [comment]
Спасибо

Скачайте Outlook для Android<https://aka.ms/AAb9ysg>
________________________________
