### ISSUE TITLE
How to pass parameters to ssh2?

### ISSUE THREAD

**Issue by Zibri** [mscdex/ssh2#1352]
I need to pass parameters to ssh2:

`-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -o ServerAliveInterval=10
`
How to do it with this?

**Comment by mscdex** [comment]
FWIW you're mixing up client and server settings here. Either way, you can set the client-side settings via the config object passed to [`connect()`](https://github.com/mscdex/ssh2#client-methods).
