### ISSUE TITLE
any method to execute command after ssh connected.

### ISSUE THREAD

**Issue by alanhg** [mscdex/ssh2#1358]
stream.write can do .

The disadvantage of this method is that the executed cd command will record in ~/.bash_history.
Moreover, the cd command will also be echoed back.

I don't know if there is a way to avoid this. thanks.

**Comment by mscdex** [comment]
The only two options you have are `.shell()` and `.exec()`. However, there is no way to know in advance whether commands you send are going to be recorded in one way or another, no matter which method you choose.

**Comment by alanhg** [comment]
My requirement is that the working directory after logging into the interactive shell can be controlled. The exec method is on different channels, and I understand it cannot affect the cwd (current working directory) of the interactive shell, right?

**Comment by mscdex** [comment]
> The exec method is on different channels, and I understand it cannot affect the cwd (current working directory) of the interactive shell, right?

Correct.

> My requirement is that the working directory after logging into the interactive shell can be controlled.

Good luck, that's not easy to do generally. This and the shell history thing are not `ssh2`-specific though, you will have the same problems with the OpenSSH client for example.

**Comment by alanhg** [comment]
I noticed that when we normally use the SSH command to log into a machine, we can execute a specific command directly. I'm wondering if SSH2 supports this, would that be possible?

This translation maintains the original context and technical nature of your query.
```
ssh [用户名]@[服务器地址] "cd [目录路径]; bash"
```

Of course, as you said, if it's not possible, then there's nothing that can be done about it at the moment.

**Comment by mscdex** [comment]
Doing `ssh foo@bar 'some command'` is equivalent to using `exec()` in `ssh2`.

**Comment by alanhg** [comment]
If we use exec to do it this way, I understand that it should solve the problem, right?

ssh -t root@110.53.238.80 -p 22 'ls /var; exec bash'

exec command and exec interact shell


I'm not sure if there is any problem.

**Comment by mscdex** [comment]
I'm not sure which problem you're trying to solve with that, but starting bash like that whether explicitly through `exec()` or implicitly through `shell()` will always record commands to the history file. There are different (bash-specific) ways of turning off recording to the history file, but that's beyond the scope of this project.

**Comment by alanhg** [comment]
I'm just wondering if I can enter a specific directory when connecting to a machine using 'connect'. Indeed, 'stream.write' works, but since it echoes back, I am thinking if there is a way to execute a command before entering the shell.

**Comment by mscdex** [comment]
There is no such thing as a connection-wide current working directory. Each `shell()`/`exec()` invocation has its own CWD and SFTP sessions have their own CWD.

SSH is a multipurpose protocol. For example, you could connect and only do port forwarding for example, which has no notion of CWD.

**Comment by alanhg** [comment]
thank you
@mscdex
