### ISSUE TITLE
Get remote port forwarding -R local port

### ISSUE THREAD

**Issue by LeoMartinDev** [mscdex/ssh2#1359]
Hello!
Is it possible to retrieve the local port option passed as -R parameter?
For example, in the `-R 0:localhost:8000` flag, I would like to be able to access `8000` in my ssh server.
Maybe it could be passed to the `request` event?

**Comment by mscdex** [comment]
Assuming you're implementing a server, the `localhost:8000` part is never sent to the server as that is only used by the OpenSSH client to know where to send incoming connections, it's not part of the underlying SSH protocol.

**Comment by LeoMartinDev** [comment]
Thanks :)
