### ISSUE TITLE
forwardIn binding to 127.0.0.1 instead

### ISSUE THREAD

**Issue by dexter4life** [mscdex/ssh2#1369]
I am trying to listen to all ipv4 request for this port 8000 but it appears that i get this 
![image](https://github.com/mscdex/ssh2/assets/10168414/85be2736-bdf5-4259-a933-1b880f209cc9)

**Comment by mscdex** [comment]
Assuming you're indeed requesting `'0.0.0.0'` for the `remoteAddr` parameter, then it's the server restricting what you're allowed to bind to. In the case of the OpenSSH server, that's controlled by the [`GatewayPorts` config option](https://man.openbsd.org/sshd_config#GatewayPorts), which defaults to `no` -- restricting you to binding to localhost only.

**Comment by dexter4life** [comment]
Thanks a lot
