### ISSUE TITLE
App stops on error timeout even if handled

### ISSUE THREAD

**Issue by carsiemundyahs** [mscdex/ssh2#1370]
I am trying to access several computers in succession via SSH. This is working until I reach a machine that does not connect and has a timeout. After many frustrating minutes reading the documentation, I have managed to get the error "handled", however my app still halts after encountering a timeout. How do I prevent this, I want my app to keep running if a connection times out. Below is the code I am using, I have promisified the function call but I am await'ing it for debugging
```
const connectViaSSH = async (connection, command) => {
    const conn = new Client();
    return new Promise((resolve, reject) => {
        conn.on('ready', () => {
            let allData = "";
            console.log(`${connection.ip_address}:${connection.port} connected as ${connection.user}`);
            conn.exec(command, (err, stream) => {
                if (err) {
                    console.log(`Unable to connect to ${connection.id}`)
                    reject(err);
                    conn.end();
                    throw err;
                }
                stream.on('close', () => {
                    resolve(allData);
                    conn.end();
                }).on('data', (data) => {
                    allData += data;
                });
                stream.end();
            });
        }).on('error', err => {
            console.log(err)
            conn.end()
        }).connect({
            host: connection.ip_address,
            port: connection.port,
            username: connection.user,
            privateKey: fs.readFileSync(connection.identity_file)
        });
    })
}
```

**Comment by mscdex** [comment]
You aren't rejecting the promise in case of an `'error'` event, that is probably why your app "halts".

Additionally, throwing the error after rejecting the promise is not useful if that's not part of your debugging and that could cause other problems. You're better off simply returning.

**Comment by carsiemundyahs** [comment]
Thanks for your help. While I've been a dev for years, I've only been working with js for a few months and the structure of this is confusing. I added a rejection to the error callback and that does seem to fix the issue, my app keeps running after failing to connect to a particular machine. I made the other changes you mentioned as well. Just to be comprehensive here's my new code in case someone encounters this in the future and finds this:
```
const connectViaSSH = async (connection, command) => {
    const conn = new Client();
    return new Promise((resolve, reject) => {
        conn.on('ready', () => {
            let allData = "";
            console.log(`${connection.ip_address}:${connection.port} connected as ${connection.user}`);
            conn.exec(command, (err, stream) => {
                if (err) {
                    console.log(`Encountered error executing on ${connection.id}`)
                    console.log(error)
                    reject(err)
                    conn.end()
                    return
                }
                stream.on('close', () => {
                    resolve(allData)
                    conn.end()
                }).on('data', (data) => {
                    allData += data
                })
                stream.end()
            })
        }).on('error', err => {
            console.error(`Could not connect to ${connection.id}`)
            reject(err)
            conn.end()
        }).connect({
            host: connection.ip_address,
            port: connection.port,
            username: connection.user,
            privateKey: fs.readFileSync(connection.identity_file),
            readyTimeout: 5000
        });
    })
}
```
Additionally I had to add a catch to my function call and since I don't want anything in particular to happen I just supplied an empty callback `connectViaSSH(blahblah).then(blahblah).catch(error => {})`

**Comment by mscdex** [comment]
Three other things you might consider remedying:

1. Using `async` is unnecessary for that function since you're not using `await` and you're already returning a `Promise`.
2. `allData` can be brought in one level scope-wise
3. Use `stream.setEncoding('utf8')` if you're expecting text output only. Doing this will ensure you get well-formed multi-byte characters if there are any. Without it, `data` is a `Buffer` and `data.toString()` will return malformed characters if the character's bytes are split across data chunks.
