### ISSUE TITLE
add support for TCP sockets from Cloudflare Workers

### ISSUE THREAD

**Issue by i18n-now** [mscdex/ssh2#1401]
https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases
Today, we are excited to announce a new API in Cloudflare Workers for creating outbound TCP sockets, making it possible to connect directly to any TCP-based service from Workers.

**Comment by mscdex** [comment]
I'm not really interested in supporting a non-node socket API. There's nothing stopping you from creating a module that wraps a Cloudflare Worker TCP connection in a standard node.js stream and passing that to `ssh2` as the underlying socket.
