### ISSUE TITLE
ssh server forwardout

### ISSUE THREAD

**Issue by alanhe421** [mscdex/ssh2#1403]
Currently, I am developing an SSH server, and I want to receive users' SSH port forward requests and then, based on the users' usernames and passwords, use SSH forwarding to the target machines.

However, during debugging, I found that it does not enter client.on('request'), so I am unable to perform forwardOut.

I am not sure where the problem lies or if my method is incorrect.

## Code

```js
const sshServer = new Server({
  hostKeys: [hostKey],
}, (client) => {
  console.log('Client connected!');
  client.on('authentication', (ctx) => {
    if (ctx.method === 'password' && ctx.username === 'alanhe' && ctx.password === '123456') {
      ctx.accept();
    } else {
      ctx.reject();
    }
  }).on('ready', () => {
    console.log('Client authenticated!');
    client.on('request', (accept, reject, name, info) => {
      console.log('进行',name);
      // if (name === 'tcpip-forward') {
      //   accept();
      //   console.log(`TCP/IP Forward request: bindAddr=${info.bindAddr}, bindPort=${info.bindPort}`);
      //   console.log(`TCP/IP Forwarding from ${info.srcIP}:${info.srcPort} to ${info.dstIP}:${info.dstPort}`);
      //   const conn = new Client();
      //   conn.forwardOut('127.0.0.1', 0, '127.0.0.1', REMOTE_PORT, (err, stream) => {
      //     if (err) {
      //       console.error('Forwarding error:', err);
      //       return;
      //     }
      //     const socket = accept();
      //     socket.pipe(stream).pipe(socket);
      //   }).connect({
      //     host: SSH_HOST,
      //     port: SSH_PORT,
      //     username: SSH_USER,
      //     password: SSH_PASSWORD
      //   });
      // } else {
      //   reject();
      // }
    }).on('session', (accept, reject) => {
      let session = accept();
      session.on('shell', function(accept, reject) {
        let stream = accept();
      });
    }).on('pty', function(accept, reject, info) {
      accept();
    }).on('end', () => {
      console.log('Client disconnected');
    });
  });
})
```

## Example

ssh -p 6666 -L 8888:localhost:8000 -N alanhe@127.0.0.1

**Comment by mscdex** [comment]
`-L` sends connections from client to server, so you need to listen for the `'tcipip'` event instead. `-R` sends connections from the server to client, which will show up under the `'request'` event.

**Comment by alanhe421** [comment]
> `-L` sends connections from client to server, so you need to listen for the `'tcipip'` event instead. `-R` sends connections from the server to client, which will show up under the `'request'` event.

<img width="738" alt="image" src="https://github.com/user-attachments/assets/2c7179a2-3b42-4751-a92b-5f5765df9145">

<img width="772" alt="image" src="https://github.com/user-attachments/assets/24e44544-7af0-47b5-8bb7-26625b2fe268">


When I tried adding TCP/IP listening, I still didn't receive the event trigger after entering the password on the client side.

## Code

```js

const {Server} = require('ssh2');
const fs = require('fs');
const hostKey = fs.readFileSync('/Users/alanhe/.ssh/id_rsa');


/**
 * ssh -L 8888:localhost:8000 -N root@43.128.242.200
 *
 * ssh -p 6666 -L 8888:localhost:8000 -N alanhe@127.0.0.1
 */
const sshServer = new Server({
  hostKeys: [hostKey],
}, (client) => {
  console.log('Client connected!');
  client.on('authentication', (ctx) => {
    if (ctx.method === 'password' && ctx.username === 'alanhe' && ctx.password === '123456') {
      ctx.accept();
      console.log('ctx accept');
    } else {
      ctx.reject();
    }
  });
  client.on('ready', () => {
    console.log('Client authenticated!');
  });
  client.on('request', function (accept, reject, name, info) {
    console.log('request name', name);
  });
  client.on('tcipip', function (...args) {
    console.log('tcipip', args);
  });
});
sshServer.listen(6666, '0.0.0.0', () => {
  console.log('Listening on port 6666');
});


```

**Comment by mscdex** [comment]
You have a typo: `'tcipip'` should be `'tcpip'` for the event name.

**Comment by alanhe421** [comment]
![image](https://github.com/user-attachments/assets/bcd5771d-6496-491b-99ef-374ced7d08d8)


> You have a typo: `'tcipip'` should be `'tcpip'` for the event name. I didn't realize I had the wrong name in my previous comment. It's all documented in the readme though.

![image](https://github.com/user-attachments/assets/f093ae35-536f-4f2d-9658-278cb388d3b9)

It's my fault, but it still didn't trigger when I tested it

**Comment by mscdex** [comment]
It works for me. Did you try making a connection to localhost:8888 (e.g. `telnet localhost 8888`) after being authenticated?

**Comment by alanhe421** [comment]
> It works for me. Did you try making a connection to localhost:8888 (e.g. `telnet localhost 8888`) on the client side after being authenticated?

thank you.

I solved it.

The tcpip has to be triggered by a request for the
