### ISSUE TITLE
ssh server forwardin not work?

### ISSUE THREAD

**Issue by alanhe421** [mscdex/ssh2#1408]
```js
const sshServer = new Server({
  hostKeys: [hostKey],
}, (serverClient) => {
  let connectOptions, conn;
  console.log('1. Client connected!');
  serverClient.on('authentication', (ctx) => {
    if (ctx.method === 'password') {
      connectOptions = getAuthorization(ctx);
      if (!connectOptions) {
        return ctx.reject();
      }
      createConnection(connectOptions).then((c) => {
        conn = c;
        ctx.accept();
        console.log('3. ctx accept');
      });
    } else {
      ctx.reject();
    }
  });
  serverClient.on('ready', () => {
    console.log('2. Client authenticated!');
  });
  serverClient.on('request', function (accept, reject, name, info) {
    console.log('4. Client request', name);
    accept();
    if (name === 'tcpip-forward') {
      conn.forwardIn(info.bindAddr, info.bindPort, (err) => {
        if (err) throw err;
        console.log(`Listening for connections on server on ${info.bindAddr}:${info.bindPort}!`);
      }).on('tcp connection', (forwardInfo, accept, reject) => {
        const clientStream = accept();
        serverClient.forwardOut(info.bindAddr, 6666, '127.0.0.1', 6666, (err, serverStream) => {
          if (err) {
            throw err;
          }
          serverStream.pipe(clientStream).pipe(serverStream);
        });
      });
    }
  });

  serverClient.on('close', () => {
    console.log('5. Client close!');
  });
  serverClient.on('end', () => {
    console.log('5. Client end!');
    conn?.end();
  });
});

```

## Exec command

```shell
 ssh -p 6666 -L 8000:localhost:8888 -N alanhe@127.0.0.1
```

I found forward in accept return undefined.

![image](https://github.com/user-attachments/assets/2718af5a-5d54-4eb4-ad59-bac1e43637f7)

I must forward the remote socket pipe to the ssh server's client socket.

**Comment by mscdex** [comment]
OpenSSH's `-L` is equivalent to `forwardOut()` on the client side and the `'tcpip'` event on the server side. It creates a TCP connection from the client to the server.

OpenSSH's `-R` is equivalent to `forwardIn()` and `'tcp connection'` event on the client side and the `'request'` event (when request name is `'tcpip-forward'`) and `forwardOut()` on the server side. It creates TCP connections from the server to the client.

**Comment by alanhe421** [comment]
```js
    if (name === 'tcpip-forward') {
      conn.forwardIn(info.bindAddr, info.bindPort, (err) => {
        if (err) throw err;
        console.log(`Listening for connections on server on ${info.bindAddr}:${info.bindPort}!`);
      }).on('tcp connection', (forwardInfo, accept, reject) => {
        const clientStream = accept();
        serverClient.forwardOut(info.bindAddr, 6666, '127.0.0.1', 6666, (err, serverStream) => {
          if (err) {
            throw err;
          }
          serverStream.pipe(clientStream).pipe(serverStream);
        });
      });
    }

```


Thank you very much for the explanation, but I would still like to ask you about forwarding in this case; I'm not quite sure what the values of the address and port parameters of server-client.forwardOut should be.

I built an ssh server; I hope to have SSH -R executed by the user to penetrate the service to the remote machine.

**Comment by alanhe421** [comment]
ssh -p 6666 -R 8888:localhost:8000 -N alanhe@127.0.0.1



Any method to get remoteAddr, remotePort?


This refers to `localhost:8000`



```js
on('tcp connection', (forwardInfo, accept, reject) => {
        console.log('5. Client tcp connection', forwardInfo);
        const clientStream = accept();
        serverClient.forwardOut(info.bindAddr, info.bindPort, '127.0.0.1', 8000, (err, serverStream) => {
          if (err) {
            throw err;
          }
          serverStream.pipe(clientStream).pipe(serverStream);
        });
      })
```

<img width="904" alt="image" src="https://github.com/user-attachments/assets/9db02600-1c34-4152-9da5-678c8692482a">

**Comment by mscdex** [comment]
The source and destination information for the incoming connection is already in `forwardInfo`.

**Comment by alanhe421** [comment]
<img width="828" alt="image" src="https://github.com/user-attachments/assets/2472d418-7225-4c86-a465-38b2cb6e3580">

<img width="588" alt="image" src="https://github.com/user-attachments/assets/7fc9fdd5-d90b-4fe1-877e-c2ee704392e3">

but it's not.

**Comment by mscdex** [comment]
It's right there: `srcIP` and `srcPort`, that is where the connection is coming from.

Let's break down what's happening here:

First the OpenSSH client command line: `-R 8888:localhost:8000`. This is requesting that the SSH server listen on `localhost:8888` and forward any connections made (server-side) to that address and port over to the OpenSSH client. When the OpenSSH client receives such a connection, it will then make an outbound connection to `localhost:8000` and essentially pipe the two together.

Now for server-side `forwardOut()`, as the documentation in the readme states:

> Alert the client of an incoming TCP connection on `boundAddr` on port `boundPort` from `remoteAddr` on port `remotePort`

So passing `info.bindAddr` and `info.bindPort` for the first two values is basically correct (although not 100% as it should really be `forwardInfo.destIP` and `forwardInfo.destPort` in certain cases such as when binding to a random port for example). For the next two values, you're specifying who is making the connection on the server side, which is `forwardInfo.srcIP` and `forwardInfo.srcPort`.

Once this is all set up, you need two things to test:
1. Something listening on the client side at `localhost:8000`
2. Something connecting to `localhost:8888` on the server side

**Comment by mscdex** [comment]
If you're still having problems or don't understand my breakdown, let me know.
