### ISSUE TITLE
Crash node application on timeout

### ISSUE THREAD

**Issue by hotfusion** [mscdex/ssh2#1409]
Hey,
I just wonder is there a way to prevent to stop crashing my nodejs app on timeout? I tried to catch the error using try catch but it's not working...

```
let conn = new Client();
try{
      conn.on('ready', () => {
             conn.end()
     }).connect({host:'',port:'',username:'',password:''})
}catch (e){
            
}
```

**Comment by mscdex** [comment]
Node uses [error events](https://nodejs.org/docs/latest/api/events.html#error-events) for async errors.
