### ISSUE TITLE
Naming convention: key vs privateKey

### ISSUE THREAD

**Issue by BarakBinyamin** [mscdex/ssh2#1413]
I'm having some difficulty shifting from connect to AuthHandler when using the client module

I used the type definitions from [@types/ssh2](https://www.npmjs.com/package/@types/ssh2) to help me through, idk how that's automatically downloaded when I install ssh2 but thats cool...

A [ConnectConfig](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e394678f22ef9380ac42512ffb19f1b42b30b2a6/types/ssh2/index.d.ts#L587) has `privateKey` field.
A [PublicKeyAuthMethod](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e394678f22ef9380ac42512ffb19f1b42b30b2a6/types/ssh2/index.d.ts#L667) has `key` field. 

Are they both private keys or is one supposed to be a public key?

Here's my code for reference:
```javascript
const Client   = require("ssh2").Client       
const sshClient = new Client()
sshClient.connect({
  host        :  myServer,
  port        :  22,
  username    : "milo",
  authHandler : function(methodsLeft, partialSuccess, doNextAuth){
    let  authConfig={
        type      : "publickey",
        host      : myServer,
        username  : "milo",     
        key       : key
      }
    doNextAuth(authConfig)
  }
})
```
vs
```javascript
const Client   = require("ssh2").Client       
const sshClient = new Client()
 sshClient.connect({
    type           : "publickey",
    host           : myServer,
    username       : "milo",     
    privateKey     : key        // privateKey ~/.ssh/id_rsa in plaintext
})
```

Thanks!

**Comment by mscdex** [comment]
The documentation in the README states about the `key` property:

> Can be a string, Buffer, or parsed key containing a private key
