### ISSUE TITLE
FEATURE REQUEST: Add support for pagination to readdir function

### ISSUE THREAD

**Issue by nylon22** [mscdex/ssh2#1414]
For directories that contain tens of thousands of files, it can take a _long_ time to pull back all of the files in one shot, leading to a dissatisfactory user experience. I think it would be beneficial to be able to pull back `n` number of files at a time in the `readdir` function. This would allow the developer to implement pagination, leading to improved response times and a better user experience for directories with large amounts of files.

**Comment by mscdex** [comment]
Duplicate of https://github.com/mscdex/ssh2/issues/623.
