### ISSUE TITLE
Vulnerability in Github Repository

### ISSUE THREAD

**Issue by sherli297** [mscdex/ssh2#1420]
I've discovered a potential security vulnerability in your Github Repository and would like to submit a report outlining the issue.

If your company has a bug bounty program, I would greatly appreciate it if you could provide me with the contact information for your security team so that I can submit my report and correspond with them regarding this matter. 

Additionally, could you please let me know the available methods of payment for rewards?

**Comment by mscdex** [comment]
Security issues can be submitted to: security at mscdex dot net.
