### ISSUE TITLE
forwardIn callback always receives port 0 when remotePort is set to 0

### ISSUE THREAD

**Issue by reijosirila** [mscdex/ssh2#1432]
In the documentation for forwardIn, it states that:

@param remotePort: The remote port to bind on the server. If this value is 0, the actual bound port is provided to callback.
However, when the remotePort is set to 0, the callback still receives 0 as the bound port instead of any non-zero value.

Here's example where console output should be any other number than 0. 

```
const { Client } = require('ssh2');
const net = require('net');

class SSH {
  constructor(client) {
    this.client = client;
    this.client.on('tcp connection', (info, accept, reject) => {
      if (!this.localHost || !this.localPort) return reject();
      const stream = accept();
      stream.pause();
      net.connect({ port: this.localPort, host: this.localHost, timeout: 10000 }, socket => {
        stream.pipe(socket).pipe(stream);
        stream.resume();
      });
    });
  }

  static async createConnection(config) {
    const client = new Client();
    await new Promise((resolve, reject) => {
      client.once('ready', resolve).once('error', reject).connect({
        ...config, tryKeyboard: true, timeout: 10000, readyTimeout: 10000
      });
    });
    return new SSH(client);
  }

  async remoteForward(localHost, localPort, remotePort = 0) {
    if (this.localHost || this.localPort) throw new Error('Port already forwarded');
    this.localHost = localHost;
    this.localPort = localPort;
    return new Promise((resolve, reject) => {
      this.client.forwardIn('', remotePort, (err, port) => err ? reject(err) : resolve(port));
    });
  }
}

SSH.createConnection({ host: 'serveo.net', username: 'test' })
  .then(server => server.remoteForward('localhost', 3000))
  .then(port => console.warn(port))
  .then(() => process.exit(0))
  ```

**Comment by mscdex** [comment]
Is this with an OpenSSH server or some other SSH server implementation? If it's the latter, perhaps it is erroneously passing `0` back instead of the allocated port number.

**Comment by mscdex** [comment]
The only other thing I can think of is maybe the server is sniffing the client banner during connection and is changing its behavior based on that. For example, if it doesn't see the OpenSSH banner maybe it doesn't send the allocated port for some reason.

Are you saying that the allocated port number is not returned even when connecting to a modern OpenSSH server from `ssh2`?

**Comment by reijosirila** [comment]
I conducted additional packet sniffing to investigate further. The reason why the SSH CLI client returns the port in this particular example, while ssh.js does not, is that the SSH CLI client defaults the bind host to "localhost." In my example, the bind host is set to an empty string ("") -- this is actually valid according to RFC 4254. 

if I add "localhost" or any other string to the remote bind address, the port is returned as expected.

This behavior seems to reveal a bug in the Go SSH implementation, where it fails to return the port when the bind host is an empty string. As a result, this issue is outside the scope of ssh.js and should be reported in the Go SSH2 repository instead.
