### ISSUE TITLE
Wrong type for HTTPSAgent -> agentOptions

### ISSUE THREAD

**Issue by SquirrelDeveloper** [mscdex/ssh2#1435]
Hi,
It seems there is a problem in the prototype of the HTTPSAgent function:

```ts
export class HTTPSAgent extends BaseHTTPSAgent {
    constructor(connectCfg: ConnectConfig, agentOptions: HTTPAgentOptions);
}
```

agentOptions should be of type HTTPSAgentOptions (allowing for `rejectUnauthorized` option without type error for example)

**Comment by mscdex** [comment]
I have nothing to do with TypeScript definitions, you'll have to go to the TypeScript repo for that kind of stuff instead.
