### ISSUE TITLE
Connection with two factor authentication failing

### ISSUE THREAD

**Issue by djw8605** [mscdex/ssh2#175]
I am using ssh2 to connect to a machine that runs Duo two factor authentication.  When it attempts to connect, it says: `ECONNRESET`.

ssh2 version: ssh2@0.3.6
node version: v0.10.22 (node-webkit 0.8.6)

The order of operations seems to be:
1. Call connect with username / password.
2. Receive Keyboard Interactive event with a prompt asking for the password again.
3. Receive another Keyboard Interactive, this time with the Duo prompt.
4. After successful duo authentication, `ECONNRESET`.

A gist with the debug output is here: https://gist.github.com/djw8605/90c30d3c7d3a168fe3e4

It should be noted, that ssh2 works just fine when Duo is not involved, on the same server version (SSH-2.0-OpenSSH_5.3).

Any help would be greatly appreciated.

**Comment by zhulduz** [comment]
I have the same problem. If I remove password from connect it works fine for me. But with password it doesn't work.

**Comment by zhulduz** [comment]
I guess this information can be useful.

```javascript
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function () {
    console.log('Client :: ready');

    conn.shell(function (err, stream) {
        if (err)
            console.log(err);
        stream.on('close', function () {
            console.log('Stream :: close');
            conn.end();
        }).on('data', function (data) {
            console.log('STDOUT: ' + data.toString());
        }).stderr.on('data', function (data) {
                console.log('STDERR: ' + data.toString());
            });
        stream.write('exit\n');
    });

}).on('keyboard-interactive', function(name,instructions,lang,prompts,finish) {
    if(prompts[0].prompt.indexOf("Password:") != -1) {
        finish(["password"])
    } else {
        finish(["verification_code"])
    };

}).on('error', function(err) {
    console.log("Error", err.message);
}).connect({
    host: 'address',
    port: 2124,
    username: 'user',
    tryKeyboard: true,
    password: "password",
    debug: console.log
    }
);

```

Also debug logs https://gist.github.com/zhulduz/88d14479c1cae81f3658

**Comment by mscdex** [comment]
@zhulduz Can you provide debug logs (with debug level turned all the way up) from the sshd process running on the server?

@djw8605 Looking at your sshd error log again, I noticed that something in PAM failed. You may need to add (at least) something like `auth required pam_unix_cred.so.1` to `/etc/pam.d/sshd` or similar. It seems like the appropriate PAM module(s) are not getting properly loaded when OpenSSH is interacting with PAM.

**Comment by zhulduz** [comment]
Of course

```sh
Dec  1 11:44:39 SAJSDev sshd(pam_google_authenticator)[31422]: Invalid verification code
Dec  1 11:44:40 SAJSDev sshd[31422]: Failed password for crystal from 'address' port 50355 ssh2
Dec  1 11:44:40 SAJSDev sshd[31422]: Accepted keyboard-interactive/pam for crystal from 'address' port 50355 ssh2
Dec  1 11:44:40 SAJSDev sshd[31422]: fatal: PAM: pam_setcred(): Permission denied
```

**Comment by mscdex** [comment]
@zhulduz Is `PermitEmptyPassword yes` set in `/etc/ssh/sshd_config` on the server?

**Comment by zhulduz** [comment]
I have checked ```PermitEmptyPassword``` parameter with ```yes``` and ```no``` values. It doesn't work yet.

**Comment by mscdex** [comment]
@zhulduz Can you try with the last version of `ssh2` and let me know if this still happens?

**Comment by zhulduz** [comment]
@mscdex it is ok now) Thanks

**Comment by mscdex** [comment]
Closing this for now. If this is still an issue with the most recent version of `ssh2` (and `ssh2-streams`), let me know if there is a way for me to reproduce the issue locally.

**Comment by InputOutputZ** [comment]
> Of course
> 
> ```shell
> Dec  1 11:44:39 SAJSDev sshd(pam_google_authenticator)[31422]: Invalid verification code
> Dec  1 11:44:40 SAJSDev sshd[31422]: Failed password for 'user' from 'address' port 50355 ssh2
> Dec  1 11:44:40 SAJSDev sshd[31422]: Accepted keyboard-interactive/pam for 'user' from 'address' port 50355 ssh2
> Dec  1 11:44:40 SAJSDev sshd[31422]: fatal: PAM: pam_setcred(): Permission denied
> ```

Set in sshd_config

```
UsePAM yes
AuthenticationMethods keyboard-interactive
```

Will fix the pam_setcred permission denied issue.
