### ISSUE TITLE
SFTP readdir() throws asynchronously

### ISSUE THREAD

**Issue by afri** [mscdex/ssh2#176]
I have the following situation:
- I perform several readdir() calls concurrently.
- From one of the readdir() calls I terminate the SFTP session by calling end(). Some of readdir() calls within the same session are still pending at this point.
The following asynchronous exception is thrown:

Uncaught: Error: write after end
Error: write after end
    at writeAfterEnd (_stream_writable.js:133:12)
    at ChannelStream.Writable.write (_stream_writable.js:181:5)
    at SFTP._send (c:\Users\Alexander\devel\conductance\node_modules\ssh2\lib\SF
TP\SFTPv3.js:1017:23)
    at SFTP.readdir (c:\Users\Alexander\devel\conductance\node_modules\ssh2\lib\
SFTP\SFTPv3.js:710:15)
    at reread (c:\Users\Alexander\devel\conductance\node_modules\ssh2\lib\SFTP\S
FTPv3.js:680:12)
    at c:\Users\Alexander\devel\conductance\node_modules\ssh2\lib\SFTP\SFTPv3.js
:694:9
    at c:\Users\Alexander\devel\conductance\node_modules\ssh2\lib\SFTP\SFTPv3.js
:717:5
    at SFTP._parse (c:\Users\Alexander\devel\conductance\node_modules\ssh2\lib\S
FTP\SFTPv3.js:1176:13)
    at ChannelStream.<anonymous> (c:\Users\Alexander\devel\conductance\node_modu
les\ssh2\lib\SFTP\SFTPv3.js:72:10)
    at ChannelStream.EventEmitter.emit (events.js:95:17)

Interpretation: After calling end(), there is still readable data from the socket, which the module passes to _parse(), and then, when while acting on that data, the module writes to the socket which is not happy to be written to.

**Comment by lchampagnie** [comment]
Did you find a solution for this? I'm having the same problem while trying to read from dir in a cascaded callbacks.

**Comment by mscdex** [comment]
@lchampagnie Can you try the [`rewrite`](https://github.com/mscdex/ssh2/tree/rewrite) branch and let me know if you still encounter this? If so, can you provide a simple test case that reproduces the issue?

**Comment by mAAdhaTTah** [comment]
FWIW, this doesn't sound like a problem with the module but with how you're managing the concurrency. Another option is to just `try`/`catch` and just let it throw errors when you terminate early, but I can't imagine the underlying systems react well to what you're trying to accomplish (sending requests to closed sockets) so the module _should_ be throwing an error.

**Comment by mscdex** [comment]
Closing this for now. If someone can come up with a reproducible example with the latest version of `ssh2`, let me know.
