### ISSUE TITLE
How to change working directory

### ISSUE THREAD

**Issue by dux** [mscdex/ssh2#186]
conn1.exec "dir -al" # some files
conn1.exec "cd ~/blah"
conn1.exec "dir -al" # exact same files

I would really appreciate tip how to accomplish this. I created full web shell using beautiful ssh2 and socket.io, but it is useless because I am always in host root.

**Comment by lanmolsz** [comment]
> ^ what @unknownbrackets said. If you are creating a "web shell" then you probably want to use `shell()` rather than `exec()`, unless your "web shell" is just for executing one-off commands and is not designed to provide a full shell session.

Can you provide an example? Very grateful.

**Comment by lanmolsz** [comment]
> I will try to use shell(), hope that will work well, thx

I have tried many times to solve it, but it doesn't work.
