### ISSUE TITLE
SSH Tunneling

### ISSUE THREAD

**Issue by indexzero** [mscdex/ssh2#19]
So starting to grok the underlying stream passing between `Connection`, `Channel` and `ChannelStream`, but still unsure how to implement this correctly.

My approach was to allow `Connection` instances to accept a stream to replace `this._sock` in `.connect()`, but that doesn't seem to be working as I expected: https://github.com/indexzero/ssh2/compare/proxy-command

This was how I was testing it. I'm really not sure if I should be calling `conn.exec()` or `conn.shell()` here to use stdio as a duplex pipe as is done in `ssh -o ProxyCommand ...` examples.

``` js
var fs = require('fs'),
    Connection = require('ssh2');

var conn = new Connection();

function logSsh(obj, name) {
  obj.on('connect', function ()    { console.log(name + ' :: connect'); });
  obj.on('error',   function (err) { console.log(name + ' :: error :: ' + err); });
  obj.on('end',     function ()    { console.log(name + ' :: end');   });
  obj.on('close',   function ()    { console.log(name + ' :: close'); });
}

function logStream(stream, conn, name) {
  stream.on('data', function(data, extended) {
    console.log(name + (extended === 'stderr' ? ' STDERR: ' : ' STDOUT: ')
                + data);
  });
  stream.on('end', function() {
    console.log(name + ' Stream :: EOF');
  });
  stream.on('close', function() {
    console.log(name + ' Stream :: close');
  });
  stream.on('exit', function(code, signal) {
    console.log(name + ' Stream :: exit :: code: ' + code + ', signal: ' + signal);
    conn.end();
  });
}

logSsh(conn, 'Connection')

conn.on('ready', function () {
  console.log('Connection :: ready');

  //
  // Use an interactive shell to nc
  //
  conn.exec('nc dest.host 22', function (err, tunnelStream) {
    if (err) throw err;
    logStream(tunnelStream, conn, 'Connection');

    var tunnel = new Connection();

    logSsh(tunnel, 'Tunnel')

    tunnel.connect({
      host: 'dest.host',
      port: 22,
      username: 'root',
      debug: function (msg) {
        console.log('Tunnel: ' + msg);
      },
      privateKey: require('fs').readFileSync('/path/to/key'),
      stream: tunnelStream
    });

    tunnel.exec('ls -la /root', function (err, stream) {
      if (err) throw err;
      logStream(stream, tunnel, 'Tunnel');
    })
  });
});

conn.connect({
  host: 'tunnel.dest',
  port: 22,
  username: 'root',
  debug: function (msg) {
    console.log('Connection: ' + msg);
  },
  privateKey: require('fs').readFileSync('/path/to/key'),
});
```

from: https://gist.github.com/4508734

The output to the above is (when using real `tunnel.host` and `dest.host` values):

```
Connection :: connect
Connection :: ready
Tunnel :: connect
Tunnel :: error :: Error: Disconnected by host (PROTOCOL_ERROR): protocol error: rcvd type 90
Tunnel :: end
Tunnel :: close
```

Would love to get this working. It's the only thing that it blocking us from using this in `pkgcloud`.

**Comment by johan13** [comment]
I am three years late to the game here, but did we establish that netcat is the only way to do this? I am trying to do a connection hop via a system that doesn't have `nc` installed.

I tried a similar approach to the one @indexzero did and got the same error message: `protocol error: rcvd type 90`.

**Comment by mscdex** [comment]
@johan13 Using `conn.forwardOut()` will probably be better.

**Comment by johan13** [comment]
Yes, you are right. I got it to work after a few more attempts. Thanks.

Do you think it'd be worth while to update README.md? It still suggests using netcat. I could try to make a PR if you're interested.

**Comment by syrnick** [comment]
+1 for a readme example.
