### ISSUE TITLE
Add support for compression (equivalent to ssh -C)

### ISSUE THREAD

**Issue by kurtkraut** [mscdex/ssh2#190]
I'm an advocate of the usage of compression during SSH connections. If the server is not in my LAN, I always use the flag -C in my ssh command. For SSH tunnels, it is a miracle maker: I could reduce the traffic between my application server and my MySQL server (both in different datacenters) from 45mbit/s to 7mbit/s.

I know implementing that here would be challenging but if anyone could do it, it is a performance achievement worth getting.

**Comment by jfenton** [comment]
@mscdex Hi, is compression supported now? I see some references to it in the codebase, but nothing in the documentation and not quite sure how to enable if it is available (specifically, interested for SFTP download). Thanks.

**Comment by mscdex** [comment]
No, it's not implemented fully yet.

**Comment by mscdex** [comment]
This is now implemented in master and will be available in v0.5.
