### ISSUE TITLE
SFTP.rename() failed with { [Error: Failure] lang: '' }

### ISSUE THREAD

**Issue by ye** [mscdex/ssh2#200]
I am running into issues with `SFTP.rename(srcPath, destPath, callback)` function. I am pretty sure it's not a permission issue because I can successfully sftp into SFTP server (opensshd configured with built-in internftp) and perform the equivalent command  `rename srcPath destPath` without any issue and is working in SFTP command line.

The error object from console.log is `{ [Error: Failure] lang: '' }`, any idea what that error means and why was it triggered?

Btw, SFTP.unlink(srcPath, callback) works with the exact same setup ( same location of files in the same server.) 

And this is reproducible.

**Comment by mscdex** [comment]
Did you ever manage to get more debug information on this using the Subsystem config entry I noted? Can you also try reproducing the issue on the master branch (`npm install https://github.com/mscdex/ssh2/tarball/master`)?

**Comment by ye** [comment]
@mscdex it's a temporary environment that I no longer has access to. But I will try to use the latest HEAD version you pointed out and see if I can reproduce this error.
