### ISSUE TITLE
Handling Connection Errors

### ISSUE THREAD

**Issue by TylerButh** [mscdex/ssh2#211]
How can I handle "Error: Timed out while waiting for handshake" so it doesn't stop my app every time. It is a normal occurrence with my internet speed for the ssh to timeout, so I want to have the code retry after timeout.

**Comment by mscdex** [comment]
Add an `error` event listener (like you would for any EventEmitter) on the connection instance:

```javascript
var SSH = require('ssh2');

var conn = new SSH();

// ...
conn.on('error', function(err) {
  // do something ...
});
// ...
```
