### ISSUE TITLE
TypeError: Object [object Object] has no method 'once'

### ISSUE THREAD

**Issue by iatalmid** [mscdex/ssh2#213]
at Connection.connect [as _onTimeout] (../ssh2/lib/Connection.js:203:10)

may be need 
this._sock.once('close', function() {

instead 
this.once('close', function() {

**Comment by mscdex** [comment]
Can you provide code that reproduces the issue? What node version are you using?

**Comment by iatalmid** [comment]
> 12 янв. 2015, в 16:03, Brian White <notifications@github.com> написал(а):
> 
> Can you provide code that reproduces the issue? What node version are you using?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mscdex/ssh2/issues/213#issuecomment-69573444>.
> 



I'm using node v0.10.35


It's too difficult to reproduce this problem. 

It has happened only once, I've looked at code and thought: 
probably just typo....






-- 


С ув. Игорь Алюшев

http://kemokiev.org

ICQ: 			312852229
skype: 			iatalmid
sipnet: 			2162395 ext. 2014
Home phone: 		+380(4572)7-57-19
Cell: 			+380(63)578-31-76
Ukraine phone: 	+380(44)374-02-43 ext. 2014
Ukraine mobile: 	+380(93)177-0-257 ext. 2014
USA phone:		+1(516)882-25-03 ext 2014 
Italy phone: 		+39(020)061-37-08 ext. 2014
Poland phone: 	+48(22)382-59-09 ext. 2014
Germany phone: 	+498972101074099 ext. 2014
Russian phone: 	+7(812)458-43-06  ext. 2014
France: 			+33(98)030-05-03

**Comment by mscdex** [comment]
Can you please re-try with the master branch? I'm curious to see if it still happens after the rewrite...
