### ISSUE TITLE
Unable to respond to Bash read

### ISSUE THREAD

**Issue by jonnyowenpowell** [mscdex/ssh2#214]
When connecting using 'shell', with { pty : true } to a server where commands can be executed fine, I am unable to pass any text to a bash script reading input. The only way I have found to close the shell following running such a script is to send \x03, and then exit as usual. Am I doing something wrong, or is this a genuine issue?

**Comment by mscdex** [comment]
Can you show a simple, minimal example that reproduces the problem?

**Comment by jonnyowenpowell** [comment]
Using the following Javascript:
```javascript
var Connection = require('ssh2');
var connection = new Connection();
var shell;
conn.on('ready', function () {
          conn.shell('uptime', { pty: true }, function (err, stream) {
            stream.setEncoding('utf8');
            if (err) { throw err; }
            stream.on('close', function() {
              connection.end();
            }).on('data', function(data) {
              console.log(data);
            });
              shell = stream;
          });
        }).connect(*VALID CONNECTION PROPERTIES*);
shell.write('./test\n');
shell.write('hello\n');
shell.end('exit\n');
```
With the following bash (with execution permissions) in the user directory for the SSH user:
```bash
read input
echo "Input: $input"
```
My expected output would of course be `Input: hello`, however the shell in fact never closes, and the output does not contain `hello`.

**Comment by mscdex** [comment]
Your usage of `shell()` is wrong. It should be `connection.shell(function(err, stream) {` because `shell()` doesn't take in a command (it's an interactive shell you type commands into, like PuTTY) and all calls to `shell()` set up a pty by default. However your example still works for me whether it's using `exec()` *or* `shell()`.

FWIW `exec()` might be a better solution anyway depending on your needs:

```javascript
  // could also be just './test' instead of the explicit commands here
  client.exec('read input; echo "Input: $input"', { pty: true }, function(err, stream) {
    if (err) throw err;
    stream.pipe(process.stdout);
    stream.stderr.pipe(process.stderr);
    stream.on('exit', function(code, signal) {
      console.log('::: STREAM EXIT', code, signal);
    }).on('close', function() {
      console.log('::: STREAM CLOSE');
      client.end();
    });
    stream.write('hello\n');
  });

// outputs:
// hello
// Input: hello
// ::: STREAM EXIT 0 undefined
// ::: STREAM CLOSE
```

**Comment by jonnyowenpowell** [comment]
Sorry, I have my code embedded in some messy async environment, and I butchered it when I tried to extract it and simplify it for this example! 
I have tested what you suggested, and found that the following outputs `Input: hello`:
```javascript
connection.exec('read input; echo "Input: $input"\n', { pty: true }, function (err, stream) {
		if (err) throw err;
		stream.pipe(process.stdout);
		stream.stderr.pipe(process.stderr);
		stream.on('exit', function(code, signal) {
		}).on('close', function() {
			connection.end();
		});
		stream.write('hello\n');
	});
```
However, the output is never seen when using shell, as in the following:
```javascript
connection.shell(function (err, stream) {
		if (err) throw err;
		stream.pipe(process.stdout);
		stream.stderr.pipe(process.stderr);
		stream.on('exit', function(code, signal) {
		}).on('close', function() {
			connection.end();
		});
		stream.write('read input; echo "Input: $input"\n');
		stream.write('hello\n');
	});
```
Due to how I need to send commands async from my other code, then using `shell()` is necessary, so that is why I am not using `exec()`, even though it works in this simple case.

**Comment by mscdex** [comment]
That `shell()` code snippet works just fine for me.
