### ISSUE TITLE
Download performance of SFTP is 50% of OpenSSH SCP

### ISSUE THREAD

**Issue by jfenton** [mscdex/ssh2#215]
As reported by others, I'm seeing a 0.5x performance of SFTP downloads using ssh2:

21 megabyte file over SFTP via scp: 20.3MB/sec
21 megabyte file over SFTP via ssh2: 11.42MB/sec
(downloading 5 files simultaneously via ssh2 == 2.26MB/s per file)

Also tested on larger corpus of files with same speeds.

Using sftp.fastGet with concurrency 25 chunkSize 32k (twiddled both, but this is best performance I could get)

sshd DEBUG3 output for SCP and SSH2 at https://gist.github.com/jfenton/fcc8cd0003a2a5e66d79

(one point of note is that SCP negotiates aes128, SSH2 negotiates aes256 but I'm not sure that would account for the performance decrease and can't find a way to change the cipher in ssh2).

**Comment by jfenton** [comment]
Corpus of 49 files, 994MB

scp *
	18s @ 20.3MB/s

ssh2 with 5 concurrent downloads
	1m49s @ 2.96MB/s per file * 5 concurrent downloads = 14.8MB/s

**Comment by mscdex** [comment]
Let's merge this in with #207 since it seems closely related.
