### ISSUE TITLE
Readme.md is for 0.4.x instead of 0.3.6+

### ISSUE THREAD

**Issue by jdarling** [mscdex/ssh2#220]
This threw me for a second when I jumped to the github pages instead of reading my local readme for a bit of API help.  The current readme seems to be for the changes that are coming out (soon?) regarding 0.4.x while the current NPM version is 0.3.6

Might make a note and a link to the current readme until 0.4.x is published.

**Comment by mscdex** [comment]
v0.4.x is going to be released very soon, so it won't be a problem for long :-)
