### ISSUE TITLE
SFTP readable stream EOF error

### ISSUE THREAD

**Issue by blackshadev** [mscdex/ssh2#225]
I was working with the SFTP submodule but I encountered a problem with the createReadableStream function. It raises an Error: End of file, which should emit the "end" event, but it doesn't.
I worked around this issue by subscribing an event listener to the "error" event and checking for the EOF error, but this isn't how readable streams should be used.

```javascript
var strm = sftp.createReadStream(fname);
strm.on("readable", function() { 
	var chunk;
	while( null !== (chunk = strm.read()) ) {
		console.log("Chunk of size " + chunk.length);
		buffs.push(chunk);
	}
});
strm.on("end", function() { 
	console.log("end");
	console.log("Data", Buffer.concat(buffs)); 
});
```

node v0.10.33
ssh2 v0.4.2

**Comment by over-flo** [comment]
It seems it also impact the sftp.fastPut feature : 

In my case the file is well created on the remote side, but it is never filled, and we keep blocked on an infinite wait :

```javascript
#!/usr/bin/env node

var Client = require('ssh2').Client;
var sys = require('sys');

var conn = new Client();
conn.on('ready', function() {
    conn.sftp(function(err, sftp) {
        if (err) throw err;
        sftp.fastPut("/home/mint/myLocalFile","/home/appuser/myRemoteFile",function(err){
            console.log('on end never called!');
            if(err)console.log(err);
            conn.end();
        })
    });
}).connect({
    host: 'localhost',
    port: 2222,
    username: 'appuser',
    privateKey:require('fs').readFileSync('/home/mint/.ssh/id_rsa')
});
```
node v0.10.29
ssh2 v0.4.2

**Comment by steelbrain** [comment]
I am having a similar problem, Just like @over-flo said, the file is touched but never filled.

**Comment by mscdex** [comment]
@blackshadev Your bug should now be fixed upstream in mscdex/ssh2-streams@1bc862aaf11

@over-flo @steelbrain Your bug should now be fixed upstream in mscdex/ssh2-streams@39609cd1b51

Try `npm install ssh2` again and that should pull in the latest `ssh2-streams`.

**Comment by sveale** [comment]
@mscdex I don't think you've published the latest update to npmjs. Would be much appreciated :)

**Comment by mscdex** [comment]
@sveale Oops. Done!

**Comment by blackshadev** [comment]
It works, thanks for the fast fix.
