### ISSUE TITLE
raw response to object

### ISSUE THREAD

**Issue by przemyslawpluta** [mscdex/ssh2#229]
Is there a way to get object response from: 

```js
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.forwardOut('xxx.xxx.xxx.xxx', xxxx, '127.0.0.1', 80, function(err, stream) {
    if (err) throw err;
    var response = '';

    stream.on('close', function() { conn.end(); });

    stream.on('data', function(data) { response += data.toString(); });

    stream.on('end', function () { console.log(response); });

    stream.end([
      'GET / HTTP/1.1',
      'User-Agent: curl/7.27.0',
      'Host: 127.0.0.1',
      'Accept: */*',
      'Connection: close',
      '',
      ''
    ].join('\r\n'));
  });
});
```

the `response` will be returned as raw string ... parse object would be useful instead.

```
'HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nDate: Tue, 10 Feb 2015 11:18:42 GMT\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\nd\r\ntest run\n\r\n0\r\n\r\n'
```

**Comment by mscdex** [comment]
That's outside the scope of this module. The forwarded connection could have easily been a connection to an IRC server, an echo server, an FTP server, etc. This particular use of HTTP is just a quick example.

**Comment by przemyslawpluta** [comment]
@mscdex thanks. Of the top you your head do you know of any `npm` modules that would turn this into a response object?

**Comment by mscdex** [comment]
Not really, you might poke around the node core code though and see if you can re-use some of that code by instantiating your own `http.IncomingMessage` and such.
