### ISSUE TITLE
Support partial authentication success

### ISSUE THREAD

**Issue by mikeosunajr** [mscdex/ssh2#231]
It looks like you support it in ssh2-streams but that it is not exposed to ssh2.

**Comment by mscdex** [comment]
Right. I left out support for it since I had never really come across any use cases for it. What kind of behavior would you expect? Just try the rest of the configured authentication methods until either there are no more methods left to try or partial success is false? Something other behavior?

**Comment by cbosuna** [comment]
The use case we have is our ssh servers require two-factor authentication. After the first authentication mechanism succeeds we do effectively a stream.authFailure(['keyboard-interactive'], true).  I would expect the client to then send a keyboard-interactive auth request.  As far as the behavior of this failing, I think going through the other authentication mechanisms is probably reasonable.

**Comment by cbosuna** [comment]
Is this something you are interested in supporting?

**Comment by mscdex** [comment]
I suppose, however the current behavior is already to try the next configured authentication method no matter if there was "partial success" or not. So for example if you have a `privateKey` set, you get a auth failure, and you also have `tryKeyboard: true`, then it should try keyboard-interactive next anyway.

I'm thinking about possibly just allowing manual ordering of authentication methods or maybe allowing some kind of authentication callback that passes the "partial authentication" value to the callback, allowing the user to decide how to proceed? I'm not sure yet...

**Comment by cbosuna** [comment]
The current behavior may be ok for my use case since I will own both the server and the client.  But other clients may not respond correctly to an auth failure in the 2fac scenario.

**Comment by mscdex** [comment]
You can now handle authentication method order via `authHandler` as of https://github.com/mscdex/ssh2/commit/fbea9a71b285a0a2591da6e4701d9181cd733366. This handler receives both 'authentications that can continue' as well as the partial success indicator.
