### ISSUE TITLE
Working examples ??

### ISSUE THREAD

**Issue by netmiller** [mscdex/ssh2#232]
Are you sure these __Client Examples__ are working properly?
I have just started using this module, and  got error:

````
var Client = require('ssh2').Client;
var conn = new Client();

and getting error:

var conn = new Client();
           ^
TypeError: undefined is not a function
````

so I tried with this  modification :

````
var ssh2 = require('ssh2');
var conn = new ssh2();
etc.-.........
````

and rest of examples works now ok.  But what am I missing with original examples??

I'm using __iojs v.1.2.0__.

**Comment by mscdex** [comment]
What does `npm ls` say? I'm betting you have ssh2 v0.3.x installed.

**Comment by netmiller** [comment]
Yes, true.  __ssh2@0.3.6__ .  But thats what I got by __npm install ssh2__.

Maybe some dependency problem :

````
Package        Current  Wanted  Latest  Location
ssh2             0.3.6   0.3.6   0.4.4  ssh2
.... also some others....
````

**Comment by netmiller** [comment]
Any advise how to find what is  holding __ssh2__ in v.0.3.6. 
I have quite a large bunch of packages (=real application), and I'm not very experienced with __npm__ ?

**Comment by mscdex** [comment]
Well, as the output you supplied suggests, some `package.json` (yours?) is looking either explicitly for 0.3.6 or possibly 0.3.x or similar.

**Comment by netmiller** [comment]
My own __package.json__ contains row: __"ssh2": "^0.3.6"__
and I found some __npm__ explanations :
````
The caret, on the other hand, is more relaxed. It will update you to the most recent major version
(the first number). ^1.2.3 will match any 1.x.x release including 1.3.0, but will hold off on 2.0.0.
````

Is it so that with caret, package should allow update from 0.3.6 -> 0.4.4.
If so, then it must be in some of my installed package dependency, and I'm lost how to find what is holding this at 0.3.6.

**Comment by netmiller** [comment]
Strange, but now I got update : edited __package.json__ and removed row __ssh2_.
Then __remove__ and __install_ again, and solved.
````
Esan-iMac:iris$npm remove ssh2
unbuild ssh2@0.3.6

Esan-iMac:iris$npm  i ssh2 --save
ssh2@0.4.4 node_modules/ssh2
├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── ssh2-streams@0.0.6 (streamsearch@0.1.2, jsbn@0.0.0, asn1@0.2.2)
````

But don't know why __npm__ reported __wanted: 0.3.6__
and does not allow package __npm update__ command.

Most other packages allows __npm update__ within major versions.
