### ISSUE TITLE
SSH2 Server fails to authenticate putty/winscp/filezilla

### ISSUE THREAD

**Issue by mofux** [mscdex/ssh2#235]
Unix-based clients like the ssh command or several sftp clients are able to connect against my own ssh server implementation, which currently only supports the "password" authentication method. However, using putty, winscp or filezilla, which are widely used in the windows world, fail to authenticate. The behaviour goes as follows:

`ssh` command:
The client connects, the different auth methods are tried ('none', 'keyboard-interactive', 'publickey'), which all get rejected with ctx.reject(), until the client finally ask for 'password' method, which then authenticates successfully with ctx.accept()

`putty`/`winscp`/`filezilla`:
The client connects, tries to authenticate with the "none" method. I ctx.reject() the "none" authentication method, which causes the client to fail directly with client error message `"Disconnected: No supported authentication methods available (server sent: )"`. The client will not try any more authentication methods.

I have tried to change several options in putty, but they all lead to the same behaviour.

Any ideas why this is happening?

**Comment by mscdex** [comment]
My guess is they are trying to parse the error message output to find out which authentication methods are valid. It's not a very good idea for clients to do this since there is no requirement for the server to send error messages in a particular format.

I'm not sure what to do about that. It seems silly to make this a configurable option. However not showing an error message with the available authentication methods could be a security "feature", but at the same time without it you lose compatibility with these fairly popular clients....

**Comment by mofux** [comment]
You were right. 

If I hack ssh2-streams https://github.com/mscdex/ssh2-streams/blob/master/lib/ssh.js#L1904
to reply with `methods='password'` it is working correctly.
It does also work partially (continues but hangs because no auth listeners exist afterwards) if instead of `ctx.reject()` I do `client._sshstream.authFailure(['password'])`.

I have checked the responses of an openssh server, and it does reply in the error message with the available authentication methods:

OpenSSH Server response (from putty log):
```
Outgoing packet #0x4, type 5 / 0x05 (SSH2_MSG_SERVICE_REQUEST)
  00000000  00 00 00 0c 73 73 68 2d 75 73 65 72 61 75 74 68  ....ssh-userauth
Incoming packet #0x4, type 6 / 0x06 (SSH2_MSG_SERVICE_ACCEPT)
  00000000  00 00 00 0c 73 73 68 2d 75 73 65 72 61 75 74 68  ....ssh-userauth
Outgoing packet #0x5, type 50 / 0x32 (SSH2_MSG_USERAUTH_REQUEST)
  00000000  00 00 00 04 75 73 65 72 00 00 00 0e 73 73 68 2d  ....user....ssh-
  00000010  63 6f 6e 6e 65 63 74 69 6f 6e 00 00 00 04 6e 6f  connection....no
  00000020  6e 65                                            ne
Incoming packet #0x5, type 51 / 0x33 (SSH2_MSG_USERAUTH_FAILURE)
  00000000  00 00 00 12 70 75 62 6c 69 63 6b 65 79 2c 70 61  ....publickey,pa
  00000010  73 73 77 6f 72 64 00                             ssword.
```

SSH2 Streams response (from putty log)
```
Outgoing packet #0x3, type 5 / 0x05 (SSH2_MSG_SERVICE_REQUEST)
  00000000  00 00 00 0c 73 73 68 2d 75 73 65 72 61 75 74 68  ....ssh-userauth
Incoming packet #0x3, type 6 / 0x06 (SSH2_MSG_SERVICE_ACCEPT)
  00000000  00 00 00 0c 73 73 68 2d 75 73 65 72 61 75 74 68  ....ssh-userauth
Outgoing packet #0x4, type 50 / 0x32 (SSH2_MSG_USERAUTH_REQUEST)
  00000000  00 00 00 04 75 73 65 72 00 00 00 0e 73 73 68 2d  ....user....ssh-
  00000010  63 6f 6e 6e 65 63 74 69 6f 6e 00 00 00 04 6e 6f  connection....no
  00000020  6e 65                                            ne
Incoming packet #0x4, type 51 / 0x33 (SSH2_MSG_USERAUTH_FAILURE)
  00000000  00 00 00 00 00                                   .....
```

I can see from your code that this has already been prepared, so the change would be minimal and would restore compatibility with these clients. Would you mind adding the auth methods to the error message?

**Comment by mofux** [comment]
FYI: I was able to work around this without modifying your code by overwriting the authFailure method :
```javascript
var server = new ssh2.Server({ privateKey: ...}, function(client) {

	// fix auth failure function to reply with the available authentication methods
	client._sshstream._authFailure = client._sshstream.authFailure;
	client._sshstream.authFailure = function() {
		client._sshstream._authFailure(['password', 'publickey']);
	}

	...

	client.on('authentication', function(ctx) {

		// now ctx.reject() works correctly and does cause putty to try the next auth methods
		if (ctx.method !== 'password' || ctx.method !== 'publickey') return ctx.reject();

		...
	});

});
```

Anyway, this still feels hacky and I would prefer if you were to implement this by default :)

**Comment by mscdex** [comment]
Ok, this should be fixed as of 568bb1326c. You can pass both an array of available methods and a partial success indicator. Let me know if this works for you.

**Comment by mofux** [comment]
Elegant patch, works perfectly, thanks for implementing this feature. You're the man!

**Comment by 131** [comment]
Same issue here, using ['password', 'publickey'], true works like a charm, do you want a PR to make this more explicit in the doc ?
