### ISSUE TITLE
Examples on keyboard-interactive

### ISSUE THREAD

**Issue by kevinsimper** [mscdex/ssh2#237]
I am trying to authenticate when i am doing an sudo command. Right now i am using an interactive shell and then listening for when i should send the password, like this: 
```
stream.on('data', function(data) {
        console.log('STDOUT: ' + data);
        if (data.toString().indexOf(':') >= data.toString().length - 2) {
          stream.write(password + '\n');
        }
      })
```

But it looks like there is something that can do that with the `keyboard-interactive`, but i can not understand how to use it and i searched for examples in the issues, but none came up.

**Comment by mscdex** [comment]
This is not related to `keyboard-interactive`. A simple solution for your problem would be to buffer `data` (strings) until you find a prompt, then once you find one, erase the buffer and write the password.
