### ISSUE TITLE
SSH2 module does not handling proper event(error event) when target device does not support SFTP

### ISSUE THREAD

**Issue by shivakumarpm** [mscdex/ssh2#240]
The ssh2 node module is not supporting in case of error condition like "sh: /usr/lib/openssh/sftp-server: not found" and this error is coming as a data event, but not as an error event. In this case stream is getting ended and stream end condition is not handled in sftp module of ssh2, so its not returning any callback.
Version checked : 0.4.4
https://www.npmjs.com/package/ssh2

**Comment by mscdex** [comment]
Can you provide the exact code you're using?

**Comment by sparkleholic** [comment]
This is producing with the simple code like the following when target sshd environment is not configured to use sftp-server. 
It hangs after calling `sftp()`
```
var ssh2 = require("ssh2"),
	fs = require('fs'),
	path = require('path');

var ssh = new ssh2();
ssh.on('connect', function() {
		console.log('connected');
});
ssh.on('ready', function() {
		console.log('ready');
		_transfile();
});
ssh.connect({
	host: 'xx.xxx.xx.xx',
	port: 22,
	username: 'root',
	password: ''
});

ssh.on('error', function(err) {
		console.error('err:', err);
});
ssh.on('close', function(err) {
		console.log('close#err:', err);
});

function _transfile() {
	ssh.sftp(function(err, sftp) {
			var rs = fs.createReadStream(path.join(__dirname,'test.txt'));
			var ws = sftp.createWriteStream('/tmp/test.txt');
			ws.on('close', function() {
				console.log("ws#close");
				sftp.end();
				ssh.end();
				process.exit();
			});
			ws.on('exit', function(err) {
				console.log("ws#exit#err:", err);
			});
			ws.on('error', function(err) {
				console.error("err:", err);
			});
			rs.pipe(ws);
	});
}
```

In previous ssh2@0.2.25 version(`lib/SFTP/SFTPv3.js`), this case can be captured in the following condition.
```
  47   stream.on('data', function(data, type) { 
  48     if (!type)
  49       self._parse(data);
  50   });
```
In this case, data was `sh: /usr/lib/openssh/sftp-server: not found` and type was `stderr`.

In recent ssh2@0.4.x, I'm not sure.

**Comment by mscdex** [comment]
I didn't see (at least) OpenSSH 6.6 send stderr data, but I did see it send an exit code. This should be resolved as of 71c225763f. Please test with master and let me know if this works for you too.

**Comment by sparkleholic** [comment]
@mscdex : :+1:  It's working fine with `https://github.com/mscdex/ssh2/commit/71c225763f5cbaa1e6dd2c8d40d7367069ccd318`.
In the error case, sftp function could get a error(`Received exit code 127 while establishing SFTP session`). It seems to be enough to handle the sftp unable case.  Thanks!!

**Comment by mscdex** [comment]
Thanks for the confirmation

**Comment by shivakumarpm** [comment]
@mscdex : I too tested the same and works well, it sending  error code 127.
Thank you.
