### ISSUE TITLE
setWindow get ignored in cisco ssh server

### ISSUE THREAD

**Issue by mkondath** [mscdex/ssh2#241]
Hello
calling setWindow on ssh session into cisco box, call returns true but I don't see the change in window.
  
             ret= stream.setWindow(23, 130, 0, 0);

but terminal settings doesn't change from default ( 24, 80)

Thanks
Madhu

**Comment by mscdex** [comment]
`setWindow()` just notifies the server that the *client*'s window dimensions have changed. Whether the server ignores the message or acts on it in some way is implementation dependent. So it's entirely possible the Cisco SSH server just ignores it, unless you have evidence of the same protocol message working with another SSH client.

**Comment by mscdex** [comment]
Closing this for now. Cisco is known to have buggy/"incomplete" ssh implementations, but if you can provide evidence that terminal window resizing works with other ssh clients (and you can provide debug information from those clients), let me know.
