### ISSUE TITLE
Option to force ipv4/ipv6

### ISSUE THREAD

**Issue by BenSower** [mscdex/ssh2#247]
I am looking for an option to force the connection to only use ipv4/ipv6 in the client.
Like this:
```
ssh -4 user@hostname
ssh -6 user@hostname
```

Since some of my servers are ipv4/ipv6, it would be nice to have an easy way of making sure the right connection is being used. Otherwise I sometimes have to wait up to a minute for a ipv6 timeout before the fallback ipv4 is being used. Would something like this be possible?

**Comment by mscdex** [comment]
This can be done manually using [`dns.lookup()`](https://nodejs.org/docs/latest/api/dns.html#dns_dns_lookup_hostname_options_callback) in node core, but I've gone ahead and added convenience options to do this in 91ea26ce97.

**Comment by BenSower** [comment]
http://e.asset.soup.io/asset/4179/4558_c340.gif

Thanks a lot!
