### ISSUE TITLE
Reverse tunnel

### ISSUE THREAD

**Issue by colinbes** [mscdex/ssh2#249]
Not really an issue, but a question non the less.

I am looking to create a reverse ssh tunnel from a specific remote server port to my local webservice port (port 80) same as if I had executed ```ssh -N -R 8080:localhost:80 username@somehost -i privatekey```
 where the local port 80 is handled via local embedded webserver.

I have looked at forwardIn and it is pretty close to what I want to do except I want to be able to assign my local destination port (80 in my example) and have data processed by web server and not ssh2 stream,

Is this doable with SSH2 library or do you have any other suggestions besides using exec command and running ssh directly?

Next, I am going to be looking at seeing if I can somehow pass received data "on ('data')" to my web server.

Much appreciated and a fine project BTW.

~Colin

**Comment by mscdex** [comment]
Yes this is possible. Look at the 4th example in the readme: `Authenticate using password and forward remote connections on port 8000 to us:`.

For your case inside the `tcp connection` event, you would basically just create a new `net.Socket`, connect it to your local port 80 server then pipe the two streams together in both directions. Example:

```javascript
var Socket = require('net').Socket;

// ...

conn.on('tcp connection', function(info, accept, reject) {
  var local = new Socket();
  var remote;

  // add any event handlers you want here, such as for `error` ...
  local.on('error', function() {
    // some kind of connection error?
    if (remote === undefined)
      reject();
    else
      remote.end();
  });

  local.connect(80, function() {
    // accepts all remote connections
    remote = accept();

    local.pipe(remote).pipe(local);
  });
});
```

**Comment by colinbes** [comment]
Gotcha. Much obliged.

**Comment by colinbes** [comment]
Thanks so much for the example, it's working like a charm - your pipe(remote).pipe(local) was my missing piece and was going in circles.

**Comment by tonidy** [comment]
@colinbes Could you provide me the sample of your code?
