### ISSUE TITLE
Question regarding verifying host against its fingerprint

### ISSUE THREAD

**Issue by prasunsultania** [mscdex/ssh2#250]
Why do we need to provide the hostHash in config while instantiating a client, cannot that be figured out automatically on the basis of "hostkey_format" in ssh.js?

**Comment by mscdex** [comment]
`hostkey_format` is unrelated. It's the host key type, such as `ssh-dsa` or `ssh-rsa`.

There is no standard hashing algorithm for generating host fingerprints, so the `hostHash` parameter simply allows you to choose what you want to use. SHA-1 and MD5 are the most common.

**Comment by prasunsultania** [comment]
Thanks for explaining, I was curious on how Filezilla shows the fingerprints without tasking any parameter,

**Comment by mscdex** [comment]
Software applications like that just force a hashing method. Some use MD5 and some use SHA-1.

**Comment by prasunsultania** [comment]
Great thanks, that explains it :)
