### ISSUE TITLE
using { pty: true} for conn.exec does not report error if there is an error

### ISSUE THREAD

**Issue by jptrivedi** [mscdex/ssh2#252]
```javascript
var SSHClient = require('ssh2').Client;

function executeCmd(cmd, options, callback) {
   var conn = new SSHClient();

    conn.on('ready', function() {
        conn.exec(cmd, options, function(err, stream) {
            if (err) throw err;
            stream.on('close', function(code, signal) {
                console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                conn.end();
            }).on('data', function(data) {
                console.log('STDOUT: ' + data);
            }).stderr.on('data', function(data) {
                console.log('STDERR: ' + data);
            });
        });
    }).connect({
        host: remote-server,
        port: 22,
        username: your-user',
        privateKey: require('fs').readFileSync('/path/to/your/key/file')
    });
}

executeCmd('sudo cmd does not exist', { pty: true} , function() {
     console.log('finished');
});
```

the error here gets printed to STDOUT instead of STDERR. This happens only if I use { pty: true} in options i.e. while executing commands with sudo. This is currently breaking my code which relies on the error before proceeding forward.

Am I missing something ? Is above not the correct way to run commands on remote server with sudo ?

Thank you in advance for any help into this.

**Comment by mscdex** [comment]
You are not missing anything, this is expected behavior.

TTYs have just one output. For example a TTY might be connected with a physical monitor, a serial port, a mouse, etc. They are devices you simply read from and/or write to. In the case of SSH, technically what is allocated is a "pseudo-TTY" because it's a virtual device (not physically connected or anything), but the same rules apply.

**Comment by jptrivedi** [comment]
Thank you very much @mscdex for the quick answer!
