### ISSUE TITLE
Connection timeout error

### ISSUE THREAD

**Issue by vivekgs2007** [mscdex/ssh2#253]
Hi,

I am able to connect through ssh via terminal, but when I try connect through ssh2 module I am getting timeout error. Out of 10 times it will connect 1-2 times, all others times  I am unable to connect.

         var conn = new Client();
                  conn.on('connect', function () {
                    console.log("- connected");
             });

            conn.on('ready', function () {
                console.log("- ready");
                conn.sftp(function (err, sftp) {
                    if (err) {
                        console.log("Error, problem starting SFTP: %s", err);
                    }
                    sftp.exists("dirname", function (res) {
                        console.log('Dir exists: ' + res);
                        if (res) {
                            sftp.fastPut(localpath, remotepath, {}, function (err) {
                                console.log('sftp upload err', err);
                                sftp.end();                               
                            });
                        } else {
                            sftp.mkdir("dirname", "0755", function (err) {
                                if (err) {
                                    console.log(err);
                                } else {
                                    sftp.fastPut(localpath, remotepath, {}, function (err) {
                                        console.log('sftp upload err', err);
                                        sftp.end();                                        
                                    });
                                }
                            });
                        }
                    });
                });
            });

            conn.on("end", function () {
                console.log("- connection end");
            });
            conn.on('error', function (err) {
                console.log("- connection error: %s", err);
            });
            conn.connect(OptionsForSFTP);

**Comment by mscdex** [comment]
What is the actual error that you're seeing? If it's the ready timeout (meaning `ready` isn't emitted), the default is 20 seconds but you can increase that by setting `readyTimeout` (in milliseconds) in your connection config object to something higher.

**Comment by BadLambdaJamma** [comment]
11:17:00 GMT-0500 (EST) DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.18'
11:17:00 GMT-0500 (EST) DEBUG: Client: Trying mfttisa.td.com on port 10022 ...
11:17:00 GMT-0500 (EST) DEBUG: Client: Connected
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_INIT
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_GREETING
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_HEADER
11:17:00 GMT-0500 (EST) DEBUG: Remote ident: 'SSH-2.0-Internet Server SSHD'
11:17:00 GMT-0500 (EST) DEBUG: Outgoing: Writing KEXINIT
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKET
11:17:00 GMT-0500 (EST) DEBUG: Parser: pktLen:628,padLen:11,remainLen:624
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATA
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
11:17:00 GMT-0500 (EST) DEBUG: Comparing KEXINITs ...
11:17:00 GMT-0500 (EST) DEBUG: (local) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
11:17:00 GMT-0500 (EST) DEBUG: (remote) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256
11:17:00 GMT-0500 (EST) DEBUG: KEX algorithm: diffie-hellman-group-exchange-sha256
11:17:00 GMT-0500 (EST) DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
11:17:00 GMT-0500 (EST) DEBUG: (remote) Host key formats: ssh-rsa
11:17:00 GMT-0500 (EST) DEBUG: Host key format: ssh-rsa
11:17:00 GMT-0500 (EST) DEBUG: (local) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
11:17:00 GMT-0500 (EST) DEBUG: (remote) Client->Server ciphers: aes128-cbc,3des-ctr,aes128-ctr,aes192-ctr,aes256-ctr,3des-cbc,blowfish-cbc,aes192-cbc,aes256-cbc,arcfour,arcfour128,arcfour256
11:17:00 GMT-0500 (EST) DEBUG: Client->Server Cipher: aes256-ctr
11:17:00 GMT-0500 (EST) DEBUG: (local) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
11:17:00 GMT-0500 (EST) DEBUG: (remote) Server->Client ciphers: aes128-cbc,3des-ctr,aes128-ctr,aes192-ctr,aes256-ctr,3des-cbc,blowfish-cbc,aes192-cbc,aes256-cbc,arcfour,arcfour128,arcfour256
11:17:00 GMT-0500 (EST) DEBUG: Server->Client Cipher: aes256-ctr
11:17:00 GMT-0500 (EST) DEBUG: (local) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
11:17:00 GMT-0500 (EST) DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha256,hmac-md5,hmac-sha1,hmac-md5-96,hmac-sha1-96,hmac-sha2-256,hmac-sha256@ssh.com
11:17:00 GMT-0500 (EST) DEBUG: Client->Server HMAC algorithm: hmac-md5
11:17:00 GMT-0500 (EST) DEBUG: (local) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
11:17:00 GMT-0500 (EST) DEBUG: (remote) Server->Client HMAC algorithms: hmac-sha256,hmac-md5,hmac-sha1,hmac-md5-96,hmac-sha1-96,hmac-sha2-256,hmac-sha256@ssh.com
11:17:00 GMT-0500 (EST) DEBUG: Server->Client HMAC algorithm: hmac-md5
11:17:00 GMT-0500 (EST) DEBUG: (local) Client->Server compression algorithms: none
11:17:00 GMT-0500 (EST) DEBUG: (remote) Client->Server compression algorithms: none,zlib
11:17:00 GMT-0500 (EST) DEBUG: Client->Server compression algorithm: none
11:17:00 GMT-0500 (EST) DEBUG: (local) Server->Client compression algorithms: none
11:17:00 GMT-0500 (EST) DEBUG: (remote) Server->Client compression algorithms: none,zlib
11:17:00 GMT-0500 (EST) DEBUG: Server->Client compression algorithm: none
11:17:00 GMT-0500 (EST) DEBUG: Outgoing: Writing KEXDH_GEX_REQUEST
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKET
11:17:00 GMT-0500 (EST) DEBUG: Parser: pktLen:148,padLen:8,remainLen:144
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATA
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_GROUP
11:17:00 GMT-0500 (EST) DEBUG: Outgoing: Writing KEXDH_GEX_INIT
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKET
11:17:00 GMT-0500 (EST) DEBUG: Parser: pktLen:444,padLen:8,remainLen:440
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATA
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_REPLY
11:17:00 GMT-0500 (EST) DEBUG: Checking host key format
11:17:00 GMT-0500 (EST) DEBUG: Checking signature format
11:17:00 GMT-0500 (EST) DEBUG: Verifying host fingerprint
11:17:00 GMT-0500 (EST) DEBUG: Host accepted by default (no verification)
11:17:00 GMT-0500 (EST) DEBUG: Verifying signature
11:17:00 GMT-0500 (EST) DEBUG: Outgoing: Writing NEWKEYS
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKET
11:17:00 GMT-0500 (EST) DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATA
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
11:17:00 GMT-0500 (EST) DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKET
11:17:00 GMT-0500 (EST) DEBUG: Parser: Decrypting
11:17:00 GMT-0500 (EST) DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATA
11:17:00 GMT-0500 (EST) DEBUG: Parser: Decrypting
11:17:00 GMT-0500 (EST) DEBUG: Parser: HMAC size:16
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAVERIFY
11:17:00 GMT-0500 (EST) DEBUG: Parser: Verifying MAC
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
11:17:00 GMT-0500 (EST) DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKET
11:17:00 GMT-0500 (EST) DEBUG: Parser: Decrypting
11:17:00 GMT-0500 (EST) DEBUG: Parser: pktLen:60,padLen:5,remainLen:48
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATA
11:17:00 GMT-0500 (EST) DEBUG: Parser: Decrypting
11:17:00 GMT-0500 (EST) DEBUG: Parser: HMAC size:16
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAVERIFY
11:17:00 GMT-0500 (EST) DEBUG: Parser: Verifying MAC
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_BANNER
11:17:00 GMT-0500 (EST) DEBUG: Parser: IN_PACKETBEFORE (expecting 16)

**Comment by BadLambdaJamma** [comment]
I changed the debug function to show getTime() instead, so it would be more meaning. It is now (and without relation to that change) connecting every time I run it in my efforts to show you getTime() as a log.  I will repost with getTime() once it resumes having the handshake issue.

**Comment by mscdex** [comment]
Are you still encountering this problem after increasing the `readyTimeout` value?

**Comment by BadLambdaJamma** [comment]
I punted entirely because of the timeout issue.  I think the issue I was having was very corner case as it involved connecting to an IBM mainframe with a wacky SFTP implementation.  In the end a recompiled curllib and using curl is what I did.

**Comment by mscdex** [comment]
Ok, if you run into the problem again and bumping up the `readyTimeout` doesn't work, feel free to post a new issue about it.

**Comment by BadLambdaJamma** [comment]
I think that my issue was specific to the SFTP host I was connecting to.  In the future, you may want to identify what host SFTP implementation is being targeted.  Thanks for all your help on this one.  People like you make open source shine.

**Comment by mscdex** [comment]
As far as SFTP goes, it should be compatible with any client/server that supports [SFTPv3](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02) (which is what OpenSSH currently supports).
