### ISSUE TITLE
How do i select a base directory ?

### ISSUE THREAD

**Issue by cjonagam** [mscdex/ssh2#255]
Can we add an option to select base directory to which shell is cd'ed like this.

```javascript
connect({
        host: host,
        port: 22,
       baseDir: ' /opt/projects',
        username: 'docker',
        password: password
    });
```

**Comment by mscdex** [comment]
That's beyond the scope of this module.

If you need that kind of functionality, you'll need to `cd /opt/projects` manually after you get the shell prompt. Otherwise you might look for a module that provides a (higher) layer on top of `ssh2` (there are many) that does what you want.
