### ISSUE TITLE
Unable to connect from Windows XP

### ISSUE THREAD

**Issue by Domnickprabhu** [mscdex/ssh2#257]
I am trying to connect using SSH2 library in Windows XP and I get the below mentioned error. But I am able to execute the same sample in Windows 7 and 8 successfully. Moreover I have also verified the connection on the non-working box with a putty client and it connects successfully there.

```
Error: This socket is closed.
    at Socket._writeGeneric (net.js:647:19)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:625:40)
    at SSH2Stream.ondata (_stream_readable.js:540:20)
    at SSH2Stream.emit (events.js:107:17)
    at SSH2Stream.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
```

Code sample:

```javascript
var Client = require('ssh2').Client;
console.log(Client);
var conn = new Client();
console.log(conn);
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.shell(function(err, stream) {
    if (err) throw err;
    stream.on('close', function() {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
    stream.end('ls -l\nexit\n');
  });
}).connect({
  host: '198.100.100.100',
  port: 22,
  username: 'usernamehere',
  password: 'passwordhere'
});
```

**Comment by mscdex** [comment]
When does the error happen? After you get the directory listing and the shell is exited? Before the `ready` event? Somewhere else?

**Comment by Domnickprabhu** [comment]
It happens even before ready event

**Comment by mscdex** [comment]
Can you set `debug: console.log` in your connection options object and post the output somewhere?

**Comment by Domnickprabhu** [comment]
This is what I get when I add debug option:
---------------------------------------------------------------------------------------
    DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.9'
    DEBUG: Client: Trying xxx.xxx.xxx.xxx on port 22 ...
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: This socket is closed.
        at Socket._writeGeneric (net.js:647:19)
        at Socket._write (net.js:700:8)
        at doWrite (_stream_writable.js:301:12)
        at writeOrBuffer (_stream_writable.js:288:5)
        at Socket.Writable.write (_stream_writable.js:217:11)
       at Socket.write (net.js:625:40)
       at SSH2Stream.ondata (_stream_readable.js:540:20)
       at SSH2Stream.emit (events.js:107:17)
       at SSH2Stream.Readable.read (_stream_readable.js:373:10)
       at flow (_stream_readable.js:750:26)

---------------------------------------------------------------------------------------
this is what I get from error event:
    DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.9'
    DEBUG: Client: Trying xxx.xxx.xxx.xxx on port 22 ...
    
    { [Error: This socket is closed.] level: 'client-socket' }
    { [Error: connect UNKNOWN]
      code: 'UNKNOWN',
      errno: 'UNKNOWN',
      syscall: 'connect',
      level: 'client-socket' }

**Comment by mscdex** [comment]
What version of node are you using?

**Comment by Domnickprabhu** [comment]
*node -v*
**v0.12.1**

**Comment by Domnickprabhu** [comment]
One more thing I would like to add. When I tried creating and connecting using 
a socket object directly using the below code, this socket object establishes a connection
successfully and I see that listed when i execute netstat -a -n

~~~~
	var Socket = require('net').Socket;
	var sc = new Socket({readable:true, writable:true});
	sc.connect(22,'xx.xxx.xx.xx');
~~~~
**TCP    xx.x.xx.xx:1465        xx.xxx.xx.xx:22        ESTABLISHED**

**Comment by mscdex** [comment]
I was able to reproduce the problem. It appears to happen in the various node v0.10.x, v0.12, and even iojs versions that I tried. However I believe d5faa07e7f should fix it.

So please try installing the master branch and see if it also works for you: `npm install https://github.com/mscdex/ssh2/tarball/master`.

**Comment by Domnickprabhu** [comment]
**AWESOME!!!!**  works like a charm... Thank u so much..
