### ISSUE TITLE
Random 'Signature could not be verified' messages in centos6

### ISSUE THREAD

**Issue by Enviii** [mscdex/ssh2#263]
npm version: 2.7.4
    node version: v0.12.2

I've been testing this for a few hours. I have tried 2 separate centos6.3 boxes logging in with passwords and private keys and sometimes it works, other times I get:

    DEBUG: Host accepted by default (no verification)
    DEBUG: Verifying signature
    DEBUG: Signature could not be verified
    DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)

I can post the full debug log if you want. I tried it on my centos7.1 box and it works 100% of the time. No issues. But whenever I try to run this on my other 2 boxes I get mixed results. Running it 10 times I get this error maybe 7 times, and then 3 times it executes just fine. Other times it will work fine 6 times, then error 4. I can't seem to find any reason why this would occur in such random fashion. 

I've also tried changing my origination. I switched from running this on my mac to my ubuntu box. Same results. SFTP'ing to my centos7.1 box works fine, while SFTP'ing to my centos6 boxes gives random errors.

openSSH versions:  

    mac: OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
    centos6.3: OpenSSH_5.3p1, OpenSSL 1.0.0-fips 29 Mar 2010
    centos7.1: OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013
    ubuntu: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2, OpenSSL 1.0.1f 6 Jan 2014

-- my code --

    var conn = new Client();
    conn.on('ready', function() {
      console.log('Client :: ready');
      conn.sftp(function(err, sftp) {
        if (err) throw err;
        sftp.fastGet('/logs/location/filename.txt', '/Users/user1/Downloads/filename.txt', function(err){
          if (err) {throw err};
          console.log('SFTP :: fastGet succeeded');
          conn.end();
        });
      });
    }).connect({
      host: '192.168.1.2',
      port: 22,
      username: 'user',
      password: 'pass',
      privateKey: require('fs').readFileSync('/file/location'),
      debug: function(txt){
        console.log(txt);
      }
    });

**Comment by mscdex** [comment]
Does `npm ls` show `ssh2-streams` v0.0.11?

**Comment by Enviii** [comment]
No, it's shows (empty). Improperly installed?

**Comment by mscdex** [comment]
When you did `npm install ssh2` it should have also installed `ssh2-streams` (v0.0.11) as a dependency.

**Comment by Enviii** [comment]
Ah yes sorry, I executed it in the wrong directory. I do see it there. 

    ssh2-streams@0.0.11

**Comment by mscdex** [comment]
What host key format was selected during the initial handshake? `ssh-rsa` or `ssh-dss`?

**Comment by Enviii** [comment]
My keys are rsa but I just checked the debug code and this is what it says: 

	DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
	DEBUG: (remote) Host key formats: ssh-dss
	DEBUG: Host key format: ssh-dss

**Comment by mscdex** [comment]
@Enviii Ah ok. Can you please try applying [this patch](https://gist.github.com/mscdex/4ee30b657425efa4db35) in your copy of `ssh2-streams`? I *think* that might fix it.

**Comment by Enviii** [comment]
Yep it worked. Ran it like 10 times on both centos6 boxes and they succeeded each time. Centos 7 box works fine just like before.

Thanks.

**Comment by mscdex** [comment]
Fixed in mscdex/ssh2-streams@acdc27a783.
