### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by przemyslawpluta** [mscdex/ssh2#264]
I'm getting `command not found` on `conn.exec`. Simple test with `conn.exec("npm --version", fn({}))` produces the error.

**Comment by przemyslawpluta** [comment]
This approach https://github.com/mscdex/ssh2/issues/214 worked.

**Comment by przemyslawpluta** [comment]
I'm getting the data back as expected but there is no `close` or `end` event emitted.

```js
...
  conn.shell(function (err, stream) {
      if (err) throw err;

      stream.pipe(process.stdout);
      stream.stderr.pipe(process.stderr);
      stream.on('exit', function exit(code, signal) {
        console.log('exit');
      });
      stream.on('close', function close() {
        console.log('close');  
        conn.end();
      });
      stream.write('uptime\n');
  });
```

**Comment by mscdex** [comment]
When you request a `shell()`, it's an interactive session. So if you no longer have any commands to send, you need to finally `stream.write('exit\n');`. This will cause the shell itself to exit and thus the underlying ssh shell session.

**Comment by przemyslawpluta** [comment]
Great worked. Thanks @mscdex.
