### ISSUE TITLE
Not returning disconnection control when device(client) executes "reboot -f"

### ISSUE THREAD

**Issue by shivakumarpm** [mscdex/ssh2#269]
Whenever ssh connection ends/disconnects forcibly(using reboot -f) by client (i,e device) node module “ssh2” is not returning channel disconnect message to requesting process.
Client.prototype.exec = function(cmd, opts, cb) {// whenever this invokes it will call "reqExec(chan, cmd, opts, cb);" and reqExec calls "chan._client._sshstream.exec(chan.outgoing.id, cmd, true);", then if cmd is "reboot -f" then it never returns to "openChannel" method.

Process is hanging (cannot get back to shell prompt, and CTRL + C also does not work )

Note : Same is working/handled for windows system.

**Comment by mscdex** [comment]
Try setting the `keepaliveInterval` connection config option, this is the same as OpenSSH's `ServerAliveInterval` setting, but in milliseconds. Also like OpenSSH, the default value for this setting is 0 by default (disabled).

**Comment by mscdex** [comment]
You may optionally adjust `keepaliveCountMax`, which is analogous to OpenSSH's `ServerAliveCountMax` (defaults to 3).

**Comment by shivakumarpm** [comment]
thank you @mscdex , now using keepaliveInterval, ssh.on('close'...) getting called. But when the ssh connection disconnects on the client side, then ssh.on('error'...) is getting called in windows, but in linux   ssh.on('error') is not getting called.

So could you tell how to handle ssh.on('error')  when the cleint ssh disconnects in linux.

**Comment by mscdex** [comment]
@shivakumarpm Do you have a simple, reproducible example I can use to test this with?
