### ISSUE TITLE
special characters in username while creating ssh connection

### ISSUE THREAD

**Issue by nikhiltyagi** [mscdex/ssh2#270]
can we use special characters in username while creating a connection. My requirement is username of format "abc\xyz" where abc is the domain name and xyz is the actual user. However with user of such nature I keep getting the below error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: All configured authentication methods failed
    at tryNextAuth (/node_modules/ssh2/lib/client.js:255:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/node_modules/ssh2/lib/client.js:432:5)

P:S: I am not sure if this is the issue, or if I am doing something wrong. My Apologies if this is not the correct way of filing issues. I could not find where do I post this question.

**Comment by mscdex** [comment]
How do you normally authenticate with this user with the OpenSSH client?

**Comment by nikhiltyagi** [comment]
From command line I just have to enclose the user in double or single quotes. something like "abc\xyz"@hostname. It doesn't work without quotes. Also I have already tried giving username as "'abc\xyz'" which would render the username in format mentioned in command line. and just to escape the \ character I did "abc\\xyz". None of these options work.

**Comment by mscdex** [comment]
Well, I suppose if the OpenSSH server is authenticating against LDAP or something special like that, you could try enabling the `keyboard-interactive` authentication method: set `tryKeyboard: true` in your connection config and handle the `keyboard-interactive` event.

**Comment by mscdex** [comment]
Did you also try to escape the backslash like `"abc\\xyz"`?

**Comment by micahfrederick** [comment]
We do a similar thing at my company using the abc\xyz and it works fine with escaping the backslash.

**Comment by mscdex** [comment]
@micahfrederick Awesome, thanks for the feedback!

**Comment by Rajasekhar1993** [comment]
ssh how to handle username & special character  &

example username : test_x&z-test@12.12.1.3
error :remote username contains invalid characters (error special character  &)
how  can i handle user name & i tired   ' ' and " " and  \  and %26 many ways still same .how can i  resolve the issue.

**Comment by theophilusx** [comment]
I don't think the & character is a permitted character under POSIX
standard, which I think SSH protocol also falls under.

On POSIX the set of valid user names is defined as lower and upper case
ASCII letters, digits, period, underscore, and hyphen, with the
restriction that hyphen is not allowed as first character of the user
name.
