### ISSUE TITLE
SFTP readdir() issue when using handle

### ISSUE THREAD

**Issue by gdraganic** [mscdex/ssh2#274]
When using directory handle and calling readdir function more times (as stated in the docs), first time when it is called, list is a populated array and err is undefined which is OK. But when calling next time I get an error object: { [Error: End of file] code: 1, lang: '' } and list is undefined, so it is never boolean false as it should be. The issue appeared for me after upgrading from 0.3 version to 0.4.

**Comment by mscdex** [comment]
Can you show how you're calling `sftp.readdir()`? Are you passing a handle or a string path for the first parameter?

**Comment by gdraganic** [comment]
```javascript
sftp.opendir(path, function (err, handle) {
  if(err) {
  // error handling
    return;
  }
  sftp.readdir(handle, function(err, list) {
    if (list === false)
      return parseList();
					
```

**Comment by gdraganic** [comment]
Any solution to this, or suggestions if I'm doing something the wrong way?

**Comment by mscdex** [comment]
It looks like I may have forgotten to add this to the list of backwards incompatibilities, but I cannot remember if this was intentional or not. I will probably fix it though.

In the meantime, with 0.4.x you can also pass a path string to `readdir()` and it will handle all the opening and closing and buffering of the entire directory list for you.

**Comment by gdraganic** [comment]
Does it need to be called multiple times to get the full directory listing like in the previous version when passing the directory handle, or does it retrieve full directory listing with one call?

**Comment by mscdex** [comment]
It retrieves the full listing with one call when you pass a string path.
