### ISSUE TITLE
Fastest way to connect to a local port on remote host?

### ISSUE THREAD

**Issue by Rush** [mscdex/ssh2#275]
I don't see a native method to do this, so I am thinking along the lines of:
```js
var Client = require('ssh2').Client;
var osenv = require('osenv');
var path = require('path');

var conn = new Client();
conn.on('ready', function() {
  // 8000 has a web socket server
  conn.exec('nc 127.0.0.1 8000', function(err, stream) {
    // pass the stream to a WebSocket client
  });
  console.log('client ready');
}).connect({
  host: 'remotehost',
  port: 22,
  username: osenv.user(),
  privateKey: require('fs').readFileSync(path.join(osenv.home(), '.ssh', 'id_rsa'))
});
```
Are there any drawbacks of this approach? Thanks for this awesome library and I appreciate any tips.

**Comment by mscdex** [comment]
There is a native method for this, it's `conn.forwardOut()`. It avoids having to spin up a process for each connection. However it may also be subject to possible connection limits defined in the SSH server's configuration (e.g. `AllowTcpForwarding` for OpenSSH's sshd_config).

**Comment by Rush** [comment]
Awesome, the `srcHost` and `srcPort` are what confused me! It works really well. I am amazed for the awesome job you did. Congrats.
