### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by rotatingJazz** [mscdex/ssh2#276]
I got this during an unsuccessful connection attempt:

````
/opt/s/test/node_modules/ssh2/lib/client.js:141
      sock.destroy();
           ^
TypeError: Cannot call method 'destroy' of undefined
    at null._onTimeout (/opt/s/test/node_modules/ssh2/lib/client.js:141:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
````

**Comment by mscdex** [comment]
@rotatingJazz Can you set `debug: console.log` in your connection config object and share the output?

**Comment by rotatingJazz** [comment]
@mscdex Nothing more appeared.

It seems that the problem is related to providing an absurdly invalid private key in the config object. I mistakenly `JSON.stringify()` the base64 encoded key instead of ... base64 decoding it (it's almost 5 in the morning here, I guess I deserve being hit by a trout :ocean: ). When I provide a proper key, it works fine.

**Comment by mscdex** [comment]
Huh... I'm not sure how that would have happened for an invalid key. If you can provide a simple, reproducible test that would be great.

**Comment by rotatingJazz** [comment]
Stripped down from a project, sorry for the extras

````
var Ssh = require('ssh2').Client,
    Promise = require("bluebird");

var sshopts =     {
        host: 'localhost',
        port: 22,
        username: 'aaaa',
        debug: console.log,
        privateKey: JSON.stringify('aa')
    };


function check(opts) {
    return new Promise(function (resolve, reject) {
        (new Ssh())
            .on('ready', function () {
                resolve('Authentication successful');
            })
            .on('error', function (err) {
                reject('Authentication failed');
            })
            .connect(opts);
    });
}

check(sshopts)
    .then(function (msg) {
        console.log(msg);
    })
    .catch(function (err) {
        console.log(err);
    });
````

-----

````
# node10 stest.js 

[Error: Cannot parse privateKey: Unsupported key format]
{ [Error: Timed out while waiting for handshake] level: 'client-timeout' }

/opt/s/mq-sshcheck/node_modules/ssh2/lib/client.js:141
      sock.destroy();
           ^
TypeError: Cannot call method 'destroy' of undefined
    at null._onTimeout (/opt/s/mq-sshcheck/node_modules/ssh2/lib/client.js:141:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

````

There is a wait between the console.log message and the TypeError (something times out I guess) and then the program ends.

Tested with node 0.10.38 and io.js

**Comment by mscdex** [comment]
Ok this should be fixed in 9e77c396af. Try the master branch and let me know if it works for you too.

**Comment by rotatingJazz** [comment]
Verified, thanks! :+1:

**Comment by florian-rossiaud** [comment]
Hi, could you bump your version on the npm registry ?
