### ISSUE TITLE
Error with SFTP fastPut

### ISSUE THREAD

**Issue by archa347** [mscdex/ssh2#278]
I'm trying to upload a file using the SFTP fastPut method.  Using the default arguments, I get this error

{ [Error: seek 327680 not supported with cursor 294912.] code: 4, lang: '' }

If I try different chunk sizes I get the same error with different seek and cursor numbers.  Can someone give me an insight into what might be going on here?

**Comment by mscdex** [comment]
What ssh/sftp software and version is the server running? Google seems to suggest it may be an IBM server of some kind and that there are patches available to fix this error if that is the case?

**Comment by mscdex** [comment]
Were you ever able to find a solution to this?

**Comment by dmaus2018** [comment]
The resume is allowed  "after" the idle connection timeout ...so wait for that time and then try to resume..
