### ISSUE TITLE
Additional KEX algorithms?

### ISSUE THREAD

**Issue by oliversalzburg** [mscdex/ssh2#279]
I was running into an issue with this library today. To make it short:

```
DEBUG: (local) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: (remote) KEX algorithms: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
DEBUG: No matching KEX algorithm
```

Any chance to get support for these algorithms?

**Comment by mscdex** [comment]
Group exchange support is available for node v0.12+ or io.js because node v0.10 and earlier did not have the right crypto functionality available.

Support for ECDH and other elliptic curve-based features will come when the OpenSSL bundled with node/io.js supports it (at least from the javascript side).

**Comment by oliversalzburg** [comment]
@mscdex Thanks for the quick reply. I'll try upgrading to 0.12 then and see if I get further :) Cheers

**Comment by oliversalzburg** [comment]
Working much better with 0.12. Thanks for the hint.

**Comment by gitmft** [comment]
I am on mac node 0.12 and hitting same/similar issue with ssh2 version": "0.5.0", see below. I should prob open a new issue. I didn't get this error on mac node .12.0 with  "ssh2" "version": "0.4.4" so it looks like something changed from ssh .4.4 to .5.0. I know diffie-hellman-group1-sha1 is deemed not secure but need to support it for one customer.

$ node --version
v0.12.0

DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: diffie-hellman-group1-sha1
DEBUG: No matching KEX algorithm

**Comment by gitmft** [comment]
Adding the following config items addressed my issue on current node .10 with latest ssh2.

  algorithms: {
    kex: ['diffie-hellman-group1-sha1',
          'ecdh-sha2-nistp256',
          'ecdh-sha2-nistp384',
          'ecdh-sha2-nistp521',
          'diffie-hellman-group-exchange-sha256',
          'diffie-hellman-group14-sha1'],
    cipher: ['aes128-cbc',
          '3des-cbc','blowfish-cbc',
          'aes128-ctr','aes192-ctr',
          'aes256-ctr','aes128-gcm',
          'aes128-gcm@openssh.com',
          'aes256-gcm',
          'aes256-gcm@openssh.com'],
  },
