### ISSUE TITLE
createReadStream & read it. Reading not returning data?

### ISSUE THREAD

**Issue by ganna-shmatova** [mscdex/ssh2#282]
I'm trying to read the first few bytes of a file, but it either doesn't initiate read or returns null?

```js
var size = f.attrs.size > 2000? 2000: f.attrs.size;
var absPath = path.join(cwd, f.filename);
console.log(absPath + ' size: ' + size);
var rs = sftp.createReadStream(absPath, {
	start: 0,
	end: size
});
rs.on('error', function(err){
	console.log(err);
});
rs.on('data', function(data){
	console.log('chunk read: ' + data);
});
rs.on('close', function(){
	console.log('closed read stream ' + absPath);
});
var buffer = rs.read(size);
rs.resume();
console.log(buffer);
```

output:
![image](https://cloud.githubusercontent.com/assets/7226694/8083700/8f228484-0f54-11e5-9fd1-1a6fcfc27fa3.png)

**Comment by mscdex** [comment]
You're mixing two methods for reading from a stream, which may be alright if you're using node v0.12+ or io.js. Anyway, if `read()` returns null then you should listen for the 'readable' event and then `read()` again.

Or just remove the `read()` and see if you get 'data' events.

**Comment by mscdex** [comment]
Also, your paths don't look quite right. You need to swap the `\` with `/`. If you're using node v0.12+ or io.js, you can use the `path.posix` namespace to force the use of `/` in all path operations (e.g. `path.posix.join()`).

**Comment by ganna-shmatova** [comment]
now other things make less sense...

```js
var size = f.attrs.size > 2000? 2000: f.attrs.size;
var absPath = path.posix.join(path.posix.normalize(cwd), f.filename);
console.log(absPath + ' size: ' + size);
var rs = sftp.createReadStream(absPath, {
	start: 0,
	end: size
});
rs.on('error', function(err){
	console.log(err);
});
rs.on('data', function(data){
	console.log('chunk read: ' + data);
});
rs.on('close', function(){
	console.log('closed read stream ' + absPath);
});
rs.on('readable', function(){
	console.log('readable');
	rs.read();
});
//var buffer = rs.read(size-1);
rs.resume();
//console.log(buffer);
//item.binary = isBinary(buffer, size);
```

output:
![image](https://cloud.githubusercontent.com/assets/7226694/8087289/f73d5888-0f67-11e5-8ad4-fd8af2f12413.png)

curious that `path.posix.normalize()` doesn't fix `\`

**Comment by mscdex** [comment]
Most likely you need to use `path.posix.*` when building your `cwd` too.

**Comment by ganna-shmatova** [comment]
yep that fixed the paths. Just peculiar normalize didn't work later on...
```js
sftp.realpath(dir, function(err, data){
	if(err) return doDone(err);
	cwd = path.posix.join(data, dir);
	doBuild();
});
```
![image](https://cloud.githubusercontent.com/assets/7226694/8087724/93247266-0f6a-11e5-9ffd-4aea986b7f69.png)


however, file is still not being read =S

**Comment by mscdex** [comment]
I'm not able to duplicate the problem. Can you set `debug: console.log` in your `connect()` config object and post the output somewhere?

**Comment by mscdex** [comment]
If you're still encountering this problem with the latest version of `ssh2`, please post debug output as previously noted.

**Comment by ganna-shmatova** [comment]
This was a very long time ago...

Looks like I omitted the file information and that fixed my problems (from my guess?):

```js
function download(conn, file, cb){
	file = path.normalize(file);

	var c = new ssh();
	var done = false;
	function doDone(err){
		if(!done){
			done=true;
			c.end();
		}
	}

	c.on('error', doDone).on('ready', function(){
		c.sftp(function(err, sftp){
			if(err) return doDone(err);
			var rs = sftp.createReadStream(file);
			rs.on('error', doDone);
			rs.on('close', doDone);
			cb(undefined, rs);
		});
	}).connect(conn);
}
```

**Comment by mscdex** [comment]
Ok, closing this for now. If you run into it again, let me know.
