### ISSUE TITLE
sftp.lstat/sftp.stat atime & mtime not date or milliseconds from epoche?

### ISSUE THREAD

**Issue by ganna-shmatova** [mscdex/ssh2#283]
lstat object

new Date()
new Date().getTime()

modified = new Date(stats.mtime);
accessed = new Date(stats.atime);

![image](https://cloud.githubusercontent.com/assets/7226694/8092881/18849ee8-0f8b-11e5-92e0-644acf1a699e.png)

---

what do the numbers mean?

**Comment by mscdex** [comment]
Those are the seconds since UNIX epoch, so you'll need to multiply it by 1000 if you want to pass it to `new Date()`.
