### ISSUE TITLE
Possible to do sftp with sudo ?

### ISSUE THREAD

**Issue by pratikd1** [mscdex/ssh2#287]
Is it possible to do a sudo with an sftp connection?

If there was someway to pass in the "substem" name for sftp, e.g. in the command line you can do this. 
sftp -s "/usr/bin/sudo /usr/libexec/openssh/sftp-server" xxx.yyy.zzz.aaa
that would help.

**Comment by mscdex** [comment]
SFTP itself does not provide a way to (temporarily) elevate permissions like `sudo`. My suggestion would be to either make the user the file owner or put the user in the owner group or use `sudo` straight up with `ssh2.exec()`.

**Comment by pratikd1** [comment]
There is a way to specify sudo with sftp.
Currently in your code, you are having the subsystem fixed as "sftp", Instead of that if you let one pass in the subsystem as an optional parameter, then one can pass something like "sudo -u <user> /usr/lib/openssh/sftp-server"   (sometimes the path is /usr/libexec/openssh/sftp-server). 

Note with this mechanism there is no way to enter the password for sudo, but one can open a ssh  connection first, do exec of  some command with sudo which will prompt for password, and then in the same connection, do an sftp with sudo. Since sudo tickets usually last for 5 minutes, the sftp will not prompt for password.

Here is link
http://unix.stackexchange.com/questions/111026/how-to-use-sftp-on-a-system-that-requires-sudo-for-root-access-ssh-key-based-a

**Comment by mscdex** [comment]
As far as I can tell that is an implementation detail specific to OpenSSH as the RFC specifically mentions the subsystem name for v3 being just `sftp`.

I'm a bit leery to add this kind of implementation-specific functionality. If you find you absolutely have to do it this way, then you can easily call `conn.subsys('sudo -u /usr/lib/openssh/sftp-server', ...)` and then just pipe between the resulting stream (if successful) and a new SFTPStream instance (from `ssh2-streams`), as this is essentially all that `conn.sftp()` does.

**Comment by alanhg** [comment]
> As far as I can tell that is an implementation detail specific to OpenSSH as the RFC specifically mentions the subsystem name for v3 being just `sftp`.
> 
> I'm a bit leery to add this kind of implementation-specific functionality. If you find you absolutely have to do it this way, then you can easily call `conn.subsys('sudo -u /usr/lib/openssh/sftp-server', ...)` and then just pipe between the resulting stream (if successful) and a new SFTPStream instance (from `ssh2-streams`), as this is essentially all that `conn.sftp()` does.

If you need to enter a password when using sudo, does that mean it can't be done this way?
