### ISSUE TITLE
Intermittent EPIPE Errors

### ISSUE THREAD

**Issue by ace234b** [mscdex/ssh2#290]
Hello, I am new to NodeJS so this may not be an issue but I would like to clarify what is occurring.

With the below code snippet I intermittently get "Error: write EPIPE" events. The stacktrace is;
Error: write EPIPE 
at exports._errnoException (util.js:746:11) 
at WriteWrap.afterWrite (net.js:775:14)

I don't think I'm performing stream.write twice so I'm not sure where the error is coming from.

I've ran with debugging enabled on .connect() and see the following;
DEBUG: Outgoing: Writing CHANNEL_CLOSE (85460946)
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
Connection Error: Error: write EPIPE

However this doesn't seem to affect application flow at all. Despite the error being emitted my program still functions as expected provided I handle the error.

Note: I'm using shell rather than exec due to the end device not supporting the exec subset of SSH.

```javascript
	    var sshconn = new ssh2();
            var sshconnoutput = '';
            var sentcount = 0;

            sshconn.on('ready', function () {
                sshconn.shell(function (err, stream) {
                    if (err) throw err;

                    stream.on('data', function (data) {
                        sshconnoutput += data.toString();

                        if (data.toString().search('>') !== -1) {
                            if (sentcount === 0) {
                                stream.write('show health\nexit\n');
                                sentcount = 1;
                            }
                        }
                    });

                    stream.on('close', function () {
                        var memberstatus = sshconnoutput.match(/State\t+([a-zA-Z]+)/);
                        callback(null, memberstatus[1]);
                        sshconn.end();
                    });
                });
            });

            sshconn.on('error', function(err) {
                console.log('Connection Error: ' + err);
                console.log(err.syscall);
            });

            sshconn.connect({
                host: member1.hostname,
                username: member1.username,
                password: member1.password,
                debug: console.log
            })
```

**Comment by mscdex** [comment]
You might be able to verify this with Wireshark or similar, but probably what is happening is that the server is abruptly severing the connection at the TCP level before the disconnect message, etc. can be sent to the server.

Your best bet is probably to just swallow errors like this.

**Comment by ace234b** [comment]
Thankyou, I was able to confirm that it was the session closing prematurely as a result of me sending the remote end an 'exit'.
