### ISSUE TITLE
Errors thrown due to outdated ssh2-streams in package.json

### ISSUE THREAD

**Issue by CodyPChristian** [mscdex/ssh2#293]
Hello,

I was having trouble using ssh2, I discovered that ssh2-streams was the wrong version in the package.json file for ssh2.

I updated it to "ssh2-streams": "~0.0.14" and that solved the errors I was getting.

This was the latest code as of 7/17/15 2 AM EST.

I hope that helps someone, thanks.

**Comment by mscdex** [comment]
Perhaps you had an old `ssh2` install? The tilde should allow any version before 0.1.0 IIRC, so updating the third set of digits should not matter.

I just did `npm install ssh2` and it picked up `ssh2-streams` 0.0.14. FWIW You can always re-install `ssh2` to pick up the latest `ssh2-streams`.
