### ISSUE TITLE
No events emitted, while executing command, after disconnect

### ISSUE THREAD

**Issue by korzhev** [mscdex/ssh2#294]
I have code example: https://github.com/korzhev/ssh2_test where I recieve data from remote server. If i  turn off my network while recieving data, I won`t get any event(error or close, or somethig), looks like stream is waiting for "data". I use centos 7 and node 0.12.

**Comment by mscdex** [comment]
By default the keepalive mechanism is disabled (just like OpenSSH). You can enable it by passing the appropriate [`keepalive*` settings to `connect()`](https://github.com/mscdex/ssh2#client-methods).
