### ISSUE TITLE
Public key comment not well parsed/exported

### ISSUE THREAD

**Issue by 131** [mscdex/ssh2#295]
I try to use a public key with comment (!) as server side acceptance (the comment is irrelevant, and can be stripped). For now, public key can be compared using .public buffer (see server Example). 
Is there a way to compare public key when they differs of a comment ?

Bonus, why is the public key "lost" in the following sample : 

```
var utils = require('ssh2').utils;
var fs = require('fs');

  //any key with a comment
var key = fs.readFileSync("server.rsa.pub");

key = utils.genPublicKey(utils.parseKey(key));

    //export it again
key = "ssh-rsa " + key.public.toString('base64');

var foo = utils.parseKey(key);
//foo.comment is null 
```

version ssh2/ssh2-stream : 2015-07-20 master/checkout

**Comment by 131** [comment]
RSA sample : ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAp8n62GoZeqjxGlhd++F8V1hiFd5BYi37dhywbSXrIBzZjNgUT7bCUxnhbnjTnPcyB+4fh8MrsYspdN2ZtJy8agmZ/yrVHPU3AanMzDypE0E0SOvzbrYE3Rama3tPcJPRAfUotD0z/q3BH2jP7vZEfLQGd2ffUnRMjVzGM9+Sf9RyBShlwZEoeADco6ymORRpZdwPSmk2X3uO4+PrBJ3i93dTUkPSIA/+L1Sqlm+fYMT3uLlxDzM5MoMAiUweFFJs75Z6jQk1ykTi/Y3zFYSReDNj+4P6UX3OHsxDUvwz+GfhblXHc3EzjTGhO/920lKbTF8EjHfxu1Lrrm7UAd36pQ== Leurent@IVS-SHURIKEN

**Comment by 131** [comment]
May i suggest 
    RE_HEADER_OPENSSH_PUB = /^(ssh-(rsa|dss)(?:-cert-v0[01]@openssh.com)?) ([A-Z0-9a-z\/+=]+)(?:$|\s+([\S].*)?)$/i,
?

**Comment by mscdex** [comment]
Try reinstalling `ssh2`, it should pick up a new `ssh2-streams` that should fix this.

**Comment by 131** [comment]
Fixed, thank you very much.
