### ISSUE TITLE
Set timeout of exec command

### ISSUE THREAD

**Issue by tgabi333** [mscdex/ssh2#296]
Currently i've got messages like this:
```The process "...." exceeded the timeout of 180 seconds.```
which is true, but i couldn't find how to setup higher timeout for a task.

**Comment by mscdex** [comment]
This has nothing to do with `ssh2` as that is not an error that we generate and it is not a protocol error. According to google it seems to be related to PHP or some PHP application, so I can't really help you there.

**Comment by tgabi333** [comment]
thanks
