### ISSUE TITLE
Basics

### ISSUE THREAD

**Issue by oculushut** [mscdex/ssh2#297]
Hi, if I have the following code in my index.js file:

```
var Client = require('ssh2').Client;
var conn = new Client();
conn.on('ready', function(){
  console.log('Hello!');
});
```

Then I guess I should get at least a "Hello!" when I run:

```
node index.js
```

Is that correct?  (I don't get anything at the moment, Node just exits back to the command line - am guessing I am missing a prerequisite?)

npm ls output:

```
8-ssh@1.0.0 /home/me/8-ssh
└─┬ ssh2@0.4.10
  ├─┬ readable-stream@1.0.33
  │ ├── core-util-is@1.0.1
  │ ├── inherits@2.0.1
  │ ├── isarray@0.0.1
  │ └── string_decoder@0.10.31
  └─┬ ssh2-streams@0.0.15
    ├── asn1@0.2.2
    ├── jsbn@0.0.0
    └── streamsearch@0.1.2
```

**Comment by mscdex** [comment]
You're not connecting to anywhere yet. You need to call `conn.connect()`, passing it a config object as documented in the readme.

**Comment by oculushut** [comment]
Thanks mscdex!  My bad!  What you said sorted the problem out.

I was trying to troubleshoot a problem I had with running the example, but I messed up some of the brackets so the connect() call was attached to the conn.exec() so was essentially doing this: conn.exec().connect()....

Closing this!
