### ISSUE TITLE
Error: Failure at SFTPStream._transform .../ssh2-streams/lib/sftp.js:338:27

### ISSUE THREAD

**Issue by jfenton** [mscdex/ssh2#300]
RHEL 6.6 on 2.6.32-504.16.2.el6.x86_64 

Running 4x or 16x simultaneous fastGet's with the following configuration against a Solaris target (sftp):
      'concurrency':25, 'chunkSize':32768, 'step':function(totalTransferred,chunk,total) { ...

ssh2@0.3.6 node_modules/ssh2
├── readable-stream@1.0.33 (inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1, isarray@0.0.1)
└── ssh2-streams@0.0.0 (streamsearch@0.1.2, jsbn@0.0.0, asn1@0.2.2)

We see the following exception thrown:

2015-07-24T19:55:08+1000 FATAL savvi-da-alu_sam_5620/9613 Error: Failure
    at SFTPStream._transform (/data/snpm/SNPM-hg/savvi/savvi-da-splunk/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:338:27)
    at SFTPStream.Transform._read (_stream_transform.js:179:10)
    at SFTPStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at SFTPStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Channel.pipeOnReadable (_stream_readable.js:642:5)
    at Channel.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)

This is in a production setting - any inkling if would likely be fixed upgrading to ssh2 1.4.28? (appreciate we are /way /behind!).

**Comment by mscdex** [comment]
The current version is v0.4.10, but the failure error message comes from the remote side and is more or less the default/generic error message that OpenSSH's sftp server sends when a syscall fails or similar.

To know what exactly is going wrong you could try to enable debug output for the sftp server and then execute your transfers again.

**Comment by jfenton** [comment]
Thanks, I have upgraded to 1.4.28 (why did I get that version with a version of "*" if 0.4.10 is the latest?).

I do see the same error with 1.4.28, which makes sense if it is the remote side.

Could be it an incompatibility between the remote Solaris sshd (SSH-2.0-Sun_SSH_1.1.6) and the fastGet method?

**Comment by mscdex** [comment]
I've never really used Solaris, much less the Sun sshd, so I'm not very familiar with how it operates. You might try one or more of the following:

* Splitting up some of the transfers so that they are executing on multiple ssh connections instead of all on the same one. That should tell us if it's some kind of per-connection or perhaps per-user limit.

* Checking if it's the same file(s) that fail and seeing what is different about those file(s). Are they stored under a different path? Different owner and/or group? Different permissions? Etc.

* Decreasing the `concurrency` by 1 at a time and see if the error eventually goes away. This could be another indicator of some sort of configured/hard coded server-side limit.

* Decreasing the `chunkSize` by a little at a time and see if the error eventually goes away. This could be another indicator of some sort of configured/hard coded server-side limit.

If none of those things help, I'm not sure what else to suggest, other than trying to enable server-side sshd debug output or installing and using OpenSSH server if you have appropriate access to the server.

**Comment by mscdex** [comment]
On a separate note, I'm not sure where 1.4.28 is coming from. Out of curiosity how did you install this module? What does `npm ls` show?

**Comment by jfenton** [comment]
Hah! Yes, I just assumed 'npm -v ssh2' gave me the version - led me utterly astray.

The Production instance has been upgraded to v0.4.10 but still seeing the same issue. Difficult to modulate the options in that environment - I haven't been able to reproduce against OpenSSH even with very high concurrency and chunk size.

I'm hunting for another Solaris target in a lower environment to test against. Will let you know.

**Comment by jfenton** [comment]
Good news, everyone! The issue was traced to the target Solaris sshd running out of File Descriptors. The root cause (well, there were several working in tandem) was READDIR sporadically taking more than 10 seconds to return on the remote filesystem.

Because of the multiplexed downloads, READDIR and STAT calls, plus our 'ls' polling was on a dumb timer that would emit yet another READDIR on the same cadence, sometimes we'd blow out all the FDs and the next call would result in an Error: Failure exception.

That was a fun one to figure out! Closing this issue. Thanks for your assistance, mscdex.

**Comment by mscdex** [comment]
Glad to hear you got it sorted out!

**Comment by neverlmore** [comment]
Hello am still receiveing the same issue in 2018 :)
guess the problem wasnt really solved

{ Error: Failure
    at SFTPStream._transform (/Users/Murad/Desktop/simon-hadoop-backend/node_modules/ssh2-streams/lib/sftp.js:410:27)
    at SFTPStream.Transform._read (_stream_transform.js:185:10)
    at SFTPStream._read (/Users/Murad/Desktop/backend/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:173:12)
    at doWrite (_stream_writable.js:388:12)
    at writeOrBuffer (_stream_writable.js:374:5)
    at SFTPStream.Writable.write (_stream_writable.js:291:11)
    at Channel.ondata (_stream_readable.js:642:20)
    at Channel.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12) code: 4, lang: '' }

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

**Comment by mofux** [comment]
This error comes from your server and you should catch it by adding an error handler to the stream. In other words, this behaviour is intended and not a bug. Unfortunately OpenSSH is not very good in telling you what the actual error was.

**Comment by ssuriyayuvan** [comment]
For Upload Try `sftp-upload` npm thats Work for me.:-)
