### ISSUE TITLE
Client: Password Change event not firing

### ISSUE THREAD

**Issue by blazedd** [mscdex/ssh2#301]
I'm having difficulty getting the 'password change' event to fire. I've tried digging around in the source to debug and I'm having similar difficulty finding what actually emits this event as well.

To replicate I simply created a new Ubuntu 14.04 x64 droplet on Digital Ocean. As apart of their initial configuration, their SSH configuration requires a password change.

If I listen to the shell I get the full output of the password request and can handle it from there, but that's not quite as optimal as the event might be.

As a side note is it intentional to be 'password change' without a hyphen? I've tried multiple combinations of the event with no success.

Code:

```javascript
var newPassword = 'newPassword';
var config = {
	host: 'x.x.x.x',
	username: 'user',
	passwordd: 'pass',
	debug: console.log
}


var	ssh2 = require('ssh2'),
	conn = new ssh2.Client();

conn.once('ready', function(){
	console.log('ready!');
	conn.shell(function(err, stream){
		if(err){
			return console.error(err);
		}
		stream.on('close', function(){
			console.log('closed stream');
		});
		stream.on('data', function(line){
			console.log('| %s', String(line));
		});
		stream.stderr.on('data', function(line){
			console.log('> %s', String(line));
		});
	});
});

conn.on('password change', function(msg, lang, done){
	console.log('Password change');
	console.log(msg);

	done(newPassword);
});

conn.on('error', function(err){
	return console.error(err);
});

conn.connect(config);
```

**Comment by mscdex** [comment]
Did you try `change password` for the event name?

**Comment by blazedd** [comment]
@mscdex Yes, I may have left a typo when I was trying to make sure the docs was not missing something. I've tried many differing variations of the event name.

**Comment by mscdex** [comment]
AFAIK the `change password` event will fire for expired passwords and the like. I'm not familiar enough with DigitalOcean but maybe they use a custom method for prompting for password change instead of expiring it at the OS level?

**Comment by blazedd** [comment]
I'm fairly certain that the password change is forced by either the sshd or PAM (forcing it to change by expiring the password) as apart of the configuration. In my code above I'll get the output as follows:

```
You are required to change your password immediately (root enforced)
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-57-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Mon Jul 27 10:30:02 EDT 2015

  System load:  0.0               Processes:           67
  Usage of /:   7.7% of 19.56GB   Users logged in:     0
  Memory usage: 11%               IP address for eth0: [REDACTED]
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

0 packages can be updated.
0 updates are security updates.

Last login: Mon Jul 27 10:30:03 2015 from [REDACTED]
Changing password for root.
(current) UNIX password: 
```

**Comment by mscdex** [comment]
As far as I can tell, it looks like it's forcing the password change at the shell level and not at the ssh protocol level (they are separate things). I'm not even sure if OpenSSH uses the protocol-level password changing mechanism (much like it doesn't use the ssh protocol's method for doing signals).

The output you've shown doesn't match the code you've originally posted since it seems like you are prepending `|` and `>` to output.
