### ISSUE TITLE
SSH2 exec client method

### ISSUE THREAD

**Issue by gdraganic** [mscdex/ssh2#302]
If I use exec method to execute a command on the server, each time the command finishes, 'exit' event is emitted and also the 'end' event that closes the stream. Is there a way to execute a command with exec method and leave the stream opened after the 'exit' event is emitted?

**Comment by mscdex** [comment]
You can try setting `stream.allowHalfOpen = true;` as [mentioned in the readme](https://github.com/mscdex/ssh2#channel) right inside your `exec()` callback, but technically the server is still free to close the process's streams whenever.

**Comment by mscdex** [comment]
`exec()` is designed to execute a single command line, which may include several commands like you can do at a shell prompt (e.g. `uptime && date && who`). So if you want to execute multiple commands, you'll need to do it that way, or just call `.exec()` serially for each command, or use `.shell()` and parse out the shell prompt and such (which is more work).
