### ISSUE TITLE
connection ends on stream.stdin.close() / end()

### ISSUE THREAD

**Issue by gfxmonk** [mscdex/ssh2#303]
To reproduce:

    var ssh2 = require('ssh2');
    var conn = new ssh2.Client();
    conn.on('ready', function() {
      console.log('Client :: ready');
      conn.exec('echo OUTPUT', function(err, stream) {
        if (err) throw err;
        stream.on('close', function(code, signal) {
          console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
          conn.end();
        }).on('data', function(data) {
          console.log('STDOUT: ' + data);
        }).stderr.on('data', function(data) {
          console.log('STDERR: ' + data);
        });

        stream.stdin.write("input", function() {
          console.log("input written; closing");
          stream.stdin.end();
        });
      });
    }).connect({
      port: 22,
      username: process.env.USER,
      agent: process.env.SSH_AUTH_SOCK
    });

output:

    Client :: ready
    input written; closing
    Stream :: close :: code: null, signal: SIGPIPE

If I comment out that `stream.stdin.end()` line, I instead get the expected:

    Client :: ready
    input written; closing
    STDOUT: OUTPUT
    
    Stream :: close :: code: 0, signal: undefined

Since it looks like `stream.stdin` is actually just an alias for `stream`, I'm assuming `stream.stdin.end()` is actually being interpreted as a request to end the entire connection. Is there a supported way to trigger EOF on the stdin stream without terminating the connection?

**Comment by gfxmonk** [comment]
Ahh. I've been looking for ages, but of course as soon as I file this bug I find `stream.eof()`. I'm closing this, although there may be an opportunity for better docs here - as far as I can tell `stdin` is merely documented as "a stream" (so this `.end()` behaviour is very surprising), and I can't find any docs mentioning `eof()`.

**Comment by mscdex** [comment]
As described in [the readme](https://github.com/mscdex/ssh2#channel), you can set `stream.allowHalfOpen = true;` to prevent `.end()` from closing both sides of the stream (just stdin).

**Comment by gfxmonk** [comment]
I see (althouth that does state that it's `true` by default, which doesn't seem to be the case). Presumably that prevents `end` from working the way it currently does on the `stream` object. What I think I want is something like:

    stream.stdin = Object.create(stream.stdin);
    stream.stdin.close = -> this.eof();
    stream.stdin.end = -> this.eof();

That way I can still forcefully kill the connection with `stream.end()` if I want, but can end `stdin` only by calling its `end`/`close` method.

**Comment by mscdex** [comment]
@gfxmonk Well, the master branch should have fixes for the default behavior now. So in `allowHalfOpen` mode, calling `.end()` will only `.eof()`, but `.close()` should always close the channel no matter if the channel is in `allowHalfOpen` mode or not.

Make a copy of the stream object seems like a waste of resources to me. Also the changes you suggested would cause backwards compatibility issues and I'm not sure it's worth that breakage (at least right now) after the default `allowHalfOpen` value has now been fixed.

**Comment by gfxmonk** [comment]
Ah, thanks - I sometimes forget the difference between `end`/`close`, it sounds like that covers what I want anyway :)
