### ISSUE TITLE
sudden ssh disconnection on rhel7 using key

### ISSUE THREAD

**Issue by korzhev** [mscdex/ssh2#304]
node 0.12.5
    ssh2 0.4.10
I connect using key to **rhel 7.1**  server (sshd version OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013). and execute several commands(emitted by setInterval), after 2-20 seconds of working I get disconnection (close connection event or **Error: read ECONNRESET**). But everything looks fine when I use password instead of key or connect using key to centos 6.6 (sshd version OpenSSH_5.3p1).

Before error/disconnection sshd debug shows:
```mm_request_receive_expect: read: rtype <some number, 125 or 123 for example> != type 115``` or ```mm_request_receive_expect: read: rtype 115 != type 125```

**Comment by mscdex** [comment]
Can you come up with a simple, minimal, reproducible example that I can use to duplicate the problem?

**Comment by korzhev** [comment]
https://github.com/korzhev/ssh2_rhel7 Also I found that using password instead of key didn`t help. There is still disconnection, but connection keeps little longer, that is why I thought it worked. I`m using centos 7

**Comment by mscdex** [comment]
If you're still experiencing this with the latest version of `ssh2` (e.g. v0.4.x), can you provide the debug output from `ssh2`?

**Comment by mscdex** [comment]
Also if you could provide more of the server-side debug output leading up to the disconnection that would be great.

**Comment by mscdex** [comment]
Closing this for now. If you can provide a reproducible example, even if it means providing access to a specific host for testing purposes, let me know.

**Comment by mohclips** [comment]
This might be it. https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/1334916 and https://bugzilla.redhat.com/show_bug.cgi?id=1308295
