### ISSUE TITLE
Determining the chosen Key Exchange, Cipher, and MAC

### ISSUE THREAD

**Issue by kevwilso** [mscdex/ssh2#308]
Hi,

For a client for a successful connection, is there a way to determine the following:
- Key Exchange Algorithm
- Cipher
- MAC

Thanks ahead of time for any info provided.

Regards,

Kevin Wilson

**Comment by mscdex** [comment]
Currently there is no way to get the names of the various parameters negotiated during a handshake.

The parameter lists and their orders are [fixed](https://github.com/mscdex/ssh2-streams/blob/ef8712a5eed10a1d2a1ea91ce3b13c33eb8efab4/lib/constants.js#L169-L209) though FWIW.

**Comment by kevwilso** [comment]
Thanks for the quick response.....  Too bad there's no API to get that info....  I would suggest that as a feature request. Its helpful from a security perspective to know what is negotiated, etc....

**Comment by mscdex** [comment]
I'm open to PRs that add either or both of those features.

**Comment by mscdex** [comment]
FWIW `ssh2` v0.5 will allow setting of desired algorithms (although there are no getters for the final negotiated algorithms yet).

**Comment by mscdex** [comment]
This should be resolved now with the `ssh2` rewrite. For more details see [here](https://github.com/mscdex/ssh2/issues/935).
