### ISSUE TITLE
ssh2 module doesn't load in strict and interative mode

### ISSUE THREAD

**Issue by felipeaf** [mscdex/ssh2#312]
I'm not sure if this is a problem, but i'm reporting for the developers become aware.

I don't have problems when i try load the module in files with "use strict"; string. But when I open the node interpreter with `node --use_strict`, and I try require ssh2 typing directly in the node.js interactive shell interpreter, i get a error.

It's easy to reproduce:
1 - Open node in strict and interactive mode:
`# node --use_strict`

2 - In the interpreter, Try require ssh2:
```
> require("ssh2")
/home/felipe_ferreira/node_modules/ssh2/lib/client.js:302
        function hostbasedCb(buf, cb) {
        ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
```

This error is only when typing directly in node.js interpreter. 

I tried in version 0.4.10 (from npm) and with node.js versions 0.12.2 and 0.10.25. (linux ubuntu and centos)

**Comment by mscdex** [comment]
I'm not sure anything will change regarding this anytime soon. Enabling a global `'use strict';` like that has the possibility of breaking many modules, not just this one.

FWIW I just tried this on the latest node v4 and v5 and did not run into this error. That almost leads me to believe that the version of v8 in the older node version (v0.12 and earlier) are at fault. At this point v0.10 and v0.12 are in maintenance mode, so I don't see a reason to cater to them.
