### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by garygreen** [mscdex/ssh2#315]
Does ssh2 provide any kind of basic command line interface support? Would be nice to use in `scripts` `package.json` as a basic way of connecting to server and deploying a set of commands.

```
ssh2 --host=192.168.100.100 --port 22 --username frylock --privateKey './id_rsa' < deploy_commands.txt
```

**Comment by mscdex** [comment]
No, it does not currently supply a CLI.

**Comment by minesworld** [comment]
hey garygreen - its open source ;-)
A new .js file begging you to be created...

**Comment by mscdex** [comment]
Closing this for now. If someone is interested they can create a separate module that provides such an interface.
