### ISSUE TITLE
Lingering KeepAlive Timers

### ISSUE THREAD

**Issue by ProTip** [mscdex/ssh2#317]
I've been running into a problem recently where under certain circumstances(new circumstances) my program will not exit.  To the best of my ability I have verified all my connections are cleaned however with a certain bit of code running the problem creeps up consistently random.  I resorted to inspecting the handlers at the end of my programs life and when the program hangs this pops up:

```
/node_modules/ssh2/lib/client.js:173:17 (setInterval)
function sendKA() {
    if (++kacount > kacountmax) {
      clearInterval(katimer);
      if (stream.readable) {
        var err = new Error('Keepalive timeout');
        err.level = 'client-timeout';
        self.emit('error', err);
        sock.destroy();
      }
      return;
    }
    if (stream.writable) {
      // append dummy callback to keep correct callback order
      callbacks.push(resetKA);
      stream.ping();
    } else
      clearInterval(katimer);
  }
```

It appears to me that a (the?) keepalive timer is not being cleared with the connections are cleaned up.

**Comment by mscdex** [comment]
Can you provide a simple, reproducible example? The keepalive timer is already cleared on socket end/close.

**Comment by mscdex** [comment]
You could also try [this patch](https://gist.github.com/anonymous/ff4a97d2be37ff8ae81f) to see if it makes any difference.

**Comment by mscdex** [comment]
@ProTip Did you ever get a chance to come up with a reproducible example and/or test the patch I linked to?
