### ISSUE TITLE
Channel.end() documentation missing.

### ISSUE THREAD

**Issue by 0xorial** [mscdex/ssh2#318]
In interactive shell demo you use stream.end('ls...') to write command. However the Channel.end() method is never mentioned in docs and it is unclear how to use it and why to use it and not, for example, .write() method. If I am missing some fundamental knowledge about ssh, please be kind and provide some links/search keywords.

**Comment by 0xorial** [comment]
Sorry, I figured out that .write() also works. Just had to be careful and not forget '\n' in the end.

**Comment by mscdex** [comment]
`Channel` is a [Duplex stream](https://nodejs.org/docs/latest/api/stream.html#stream_class_stream_duplex) and explicitly `end()`ing the stream closes `stdin` on the remote end.
