### ISSUE TITLE
handling sudo interactive password requests

### ISSUE THREAD

**Issue by focusaurus** [mscdex/ssh2#32]
Any guidance on how to go about executing sudo on the remote server and dealing with interactive password prompts? Ideally I'd like to do the prompting on the client side and allow interactive authentication to work (basically shooting for how Fabric does this in python), but I'm not sure if A) I need to force tty creation during the connection (and if so, how would I do that as I don't see any connection config option) or B) whether I can specify an "askpass" program on the remote side and somehow wire that up to the ssh2 session or C) something else entirely or D) this is sufficiently nontrivial that I should consider alternatives.

As I would mostly expect, currently running  a remote `sudo` results in:

```
sudo: no tty present and no askpass program specified
Sorry, try again.
sudo: no tty present and no askpass program specified
Sorry, try again.
sudo: no tty present and no askpass program specified
Sorry, try again.
sudo: 3 incorrect password attempts
```

**Comment by zhy1** [comment]
very good.
