### ISSUE TITLE
ssh2 blocking node.js execution thread while connecting?

### ISSUE THREAD

**Issue by tareks** [mscdex/ssh2#321]
This is more of a question than a confirmed issue at this point.

I'm using node.js and ssh2 to connect to various nodes and collect information from them. The same node code also uses express to serve information (collected from the nodes) over HTTP. 

It appears that for the duration when a ssh connection is being established, any GET requests that would be otherwise be served are blocked resulting in any AJAX code running in the browser to hang unless the ssh connection is either made or times out. This would not otherwise happen when using something like child_process to spawn an actual ssh client process from the CLI, grab the information, and exit. 

I've gotten around this by creating a connection once and keeping it open as long as possible using TCP KeepAlive as reconnecting frequently will result in a lot of blocking for client AJAX calls from a browser. 

It takes about 6 seconds for each connection to respond (on a LAN), so it appears node will just block all processing for that duration.

Below is the debug log of where the "pause"/blocking occurs:

```
DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.15'
DEBUG: Client: Trying host on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_6.0'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:956,padLen:5,remainLen:952
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: (remote) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: KEX algorithm: diffie-hellman-group-exchange-sha256
DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
DEBUG: Host key format: ssh-rsa
DEBUG: (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
DEBUG: Client->Server Cipher: aes256-ctr
DEBUG: (local) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
DEBUG: (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
DEBUG: Server->Client Cipher: aes256-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
DEBUG: (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: Client->Server HMAC algorithm: hmac-sha1
DEBUG: (local) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
DEBUG: (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: Server->Client HMAC algorithm: hmac-sha1
DEBUG: (local) Client->Server compression algorithms: none
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none
DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXDH_GEX_REQUEST
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:404,padLen:8,remainLen:400
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_GROUP


*** BLOCKING for 6 seconds - Can't even Interrupt (Ctrl + C) here ***

DEBUG: Outgoing: Writing KEXDH_GEX_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:956,padLen:8,remainLen:952
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format

```

Connect options are pretty straight forward:
```
 host: host,
  port: 22,
  tryKeyboard: false,
  forceIPv4: true,
  username: username,
  keepaliveInterval: 60000,
  keepaliveCountMax: 1,
  privateKey: require('fs').readFileSync(SSHkeyPath),
  debug: console.log
```

Is this blocking by design in ssh2?  Any advice or suggestions would be appreciated. Cheers.

**Comment by mscdex** [comment]
What node version are you using?

**Comment by mscdex** [comment]
Also, can you try the same script with node v0.10 to see if the same hangup occurs? I'm wondering if it's something to do with the DH group exchange.

**Comment by tareks** [comment]
Thanks. This is running on node v0.12.6. 

Will see if i can try this on v0.10.

**Comment by steelbrain** [comment]
:+1:

**Comment by mscdex** [comment]
It may also be worth trying on the latest stable version of node (v4.1.1 as of this writing) to see how it compares too.

**Comment by tareks** [comment]
Had a chance to look at this again briefly.

Was able to reproduced same "pause/delay" behavior with same code on v4.1.1 however, it appears that the delay is slightly less than v0.12.6. I'm guessing this is due to overall code performance enhancements in newer node js codebase?

On v0.12.6, if i try to establish more than 3 connections without staggering them, they seem to step on each others toes and they'll all time out waiting for handshake. On v4.1.1, there's still a 5-6 second pause when a connection is established, however, it seems to cope slightly better with about 8 simultaneous connections (with about 15 seconds of unresponsiveness) before they start timing out. Obviously, the workaround for this is to spread the connection attempts apart, but there's still a  a short period of unresponsiveness for each connection attempt regardless, but this appears to be much shorter on v4.1.1 (~ 1 second for a single connection) than v0.12.6. (~ 3 seconds for a single connection)

These results are quite rough, but there seems to be a bit of a pattern emerging. Let me know if you need anything more concrete. Still need to build v.10.0 and test on there. 

FYI - not sure if it makes any difference, but this is on debian PPC (big endian).

**Comment by mscdex** [comment]
I do know that PPC support is kind of new-ish, so it could be something specific to that arch that isn't optimized yet. One way to find out might be to try with debian on x86 using the same script, node version, and remote server to see if the same pause can be duplicated that way? That might rule out some things...

As far as the group exchange stuff goes, there's no number crunching going on in javascript land for that, it's all C/C++ just like the original DH algorithms. The only difference being that dynamic groups are exchanged instead of choosing static, predefined groups. The only thing that could possibly be at play here would be Buffers that contain large keys (e.g. 8192 bits) if the server sends one that large. That's just a wild guess though.

You may also try running some profiling tools against your script. At least something like the `--prof` option with a v8 tick processor, or [`node-inspector`](https://github.com/node-inspector/node-inspector) or perhaps some OS/system profiling utility.

**Comment by raffecat** [comment]
I noticed that ssh2-streams/lib/ssh.js uses crypto.randomBytes without a callback. It's actually possible for this to block the process for an unbounded amount of time if there isn't enough entropy available, so this is one place to look.

The node documentation says it should never block for more than a few milliseconds, however you mentioned this is on PPC where the implementation might be different. The implementation is not straightforward; see [here](https://github.com/nodejs/node/blob/master/src/node_crypto.cc) and [here](https://github.com/openssl/openssl/tree/master/crypto/rand) for details.

**Comment by mscdex** [comment]
@raffecat FWIW `ssh2` v0.5 will use the async `crypto.randomBytes()`.

**Comment by mscdex** [comment]
Closing this as v0.5 has been available for some time now.
