### ISSUE TITLE
Handling SFTP fastGet on ssh2 server

### ISSUE THREAD

**Issue by mitchellsimoens** [mscdex/ssh2#322]
As a test, I have the client trying a fastGet:

    var Client = require('ssh2').Client,
        conn   = new Client();

    conn.on('ready', function() {
        console.log('Client :: ready');

        conn.sftp(function(error, sftp) {
            if (error) {
                throw error;
            }

            sftp.fastGet(
                'someuser/somefile.txt',
                __dirname + '/test.txt',
                {},
                function() {
                    conn.end();
                }
            );
        });
    }).connect({
        host : '127.0.0.1',
        port : 3333
    });

So I'm trying to get a file on a remote SFTP server at the location `someuser/somefile.txt` and save it locally as `test.txt`. I'm trying to use the ssh2 SFTP server but am having a hard time with the FSTAT and READ events with how to get the requested file in order to handle those. FSTAT event has the request ID and handle buffer as arguments so I'm not sure how to get the filename from this.

This is what I have on the server side:

    var sftpStream = accept();

    sftpStream
        .on('OPEN', function(reqid, filename, flags, attrs) {
            var handle = new Buffer(4);

            sftpStream.handle(reqid, handle);
        })
        .on('FSTAT', function(reqid, handle) {
            //fake attrs
            var attrs = {
              size   : 10 * 1024,
              uid   : 9001,
              gid   : 9001,
              atime : (Date.now() / 1000) | 0,
              mtime : (Date.now() / 1000) | 0
            };

            sftpStream.attrs(reqid, attrs);
            sftpStream.status(reqid, STATUS_CODE.OK);
        })
        .on('READ', function(reqid, handle, offset, length) {
            //not here yet
        })
        .on('CLOSE', function(reqid, handle) {
            sftpStream.status(reqid, STATUS_CODE.OK);
        });

All I'm wanting to do is download a file via sftp right now.

**Comment by mscdex** [comment]
The answer depends on the application, but if you aren't using the handle to store a real file descriptor, then you could create your own table in memory that maps handle values to filenames, if you need to look up the original filename.

**Comment by mitchellsimoens** [comment]
The client will be repeating a file that is only one level deep like 'someuser/somefile'. On the server I want to get that requested file and I will then parse it to the real file and send that file back back. This is the first time using this module so I'm not sure what you mean by using the handle to store the file descriptor.

**Comment by mscdex** [comment]
Here's a simple example:

```javascript
var fs = require('fs');
// ...
var sftpStream = accept();
var fds = {}; // maps OS fd => filename

sftpStream
    .on('OPEN', function(reqid, filename, flags, attrs) {
        flags = SFTPStream.flagsToString(flags);
        if (flags === null)
          return sftpStream.status(reqid, SFTPStream.STATUS_CODE.FAILURE);
        fs.open(filename, flags, function(err, fd) {
          if (err)
            return sftpStream.status(reqid, SFTPStream.STATUS_CODE.FAILURE);
          var handle = new Buffer(4);
          handle.writeUInt32BE(lastId, 0);
          fds[fd] = filename;
          sftpStream.handle(reqid, handle);
        });
    })
    .on('FSTAT', function(reqid, handle) {
        var fd;
        if (handle.length !== 4 || !fds[fd = handle.readUInt32BE(0)])
          return sftp.status(reqid, SFTPStream.STATUS_CODE.FAILURE);

        console.log('FSTAT: original filename = %s', fds[fd]);
        //fake attrs
        var attrs = {
          size   : 10 * 1024,
          uid   : 9001,
          gid   : 9001,
          atime : (Date.now() / 1000) | 0,
          mtime : (Date.now() / 1000) | 0
        };

        sftpStream.attrs(reqid, attrs);
    })
    .on('READ', function(reqid, handle, offset, length) {
        var fd;
        if (handle.length !== 4 || !fds[fd = handle.readUInt32BE(0)])
          return sftp.status(reqid, SFTPStream.STATUS_CODE.FAILURE);

        //not here yet
    })
    .on('CLOSE', function(reqid, handle) {
        var fd;
        if (handle.length !== 4 || !fds[fd = handle.readUInt32BE(0)])
          return sftp.status(reqid, SFTPStream.STATUS_CODE.FAILURE);
        fs.close(fd, function(err) {
          if (err)
            return sftp.status(reqid, SFTPStream.STATUS_CODE.FAILURE);
          sftpStream.status(reqid, STATUS_CODE.OK);
        });
    });
```

**Comment by mitchellsimoens** [comment]
Thank you very much! Got it working. Thanks for your work on ssh2 and ssh2-streams!

One thing I noticed is your new flagsToString method. That will be handy! It seems ssh2 requires ~0.0.5 of ssh2-streams which doesn't have that method but also isn't the latest in npm.

**Comment by mscdex** [comment]
`ssh2-streams` is currently at v0.0.17, which you should get when you `npm install ssh2`.
