### ISSUE TITLE
ssh2 shell buffer/pipe data threshold?

### ISSUE THREAD

**Issue by fentas** [mscdex/ssh2#326]
Hey there,
I open a shell connection and execute a command which will return lots of data.
After some point, about 45s constant data streaming, it just stops and nothing happens anymore.
No disconnect, no data, no error - just idle. But the remote host is still pumping data to stdout.
After lots of redesigning (change encoding, produce smaller output of chunks, sleep between outputs) it still happens. My guess is that after a certain amount of data, a limit kicks in. Is this possible?
Like pipe limit, or buffer limit? If yes is there a way to reset?

I tried .on 'data' event and pipe: same result.
System: ubuntu 14.04 to ubuntu 14.04

**Comment by fentas** [comment]
Ah forgot to post debug data, here is tail before it *dies* (or do nothing more rather):
```log
{ '0': 'DEBUG: Parser: IN_PACKETBEFORE (expecting 16)' }
{ '0': 'DEBUG: Parser: IN_PACKET' }
{ '0': 'DEBUG: Parser: Decrypting' }
{ '0': 'DEBUG: Parser: pktLen:17036,padLen:7,remainLen:17024' }
{ '0': 'DEBUG: Parser: IN_PACKETDATA' }
{ '0': 'DEBUG: Parser: Decrypting' }
{ '0': 'DEBUG: Parser: HMAC size:16' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAVERIFY' }
{ '0': 'DEBUG: Parser: Verifying MAC' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)' }
{ '0': 'DEBUG: Parser: IN_PACKETBEFORE (expecting 16)' }
{ '0': 'DEBUG: Parser: IN_PACKET' }
{ '0': 'DEBUG: Parser: Decrypting' }
{ '0': 'DEBUG: Parser: pktLen:9964,padLen:7,remainLen:9952' }
{ '0': 'DEBUG: Parser: IN_PACKETDATA' }
{ '0': 'DEBUG: Parser: Decrypting' }
{ '0': 'DEBUG: Parser: HMAC size:16' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAVERIFY' }
{ '0': 'DEBUG: Parser: Verifying MAC' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)' }
{ '0': 'DEBUG: Parser: IN_PACKETBEFORE (expecting 16)' }
{ '0': 'DEBUG: Parser: IN_PACKET' }
{ '0': 'DEBUG: Parser: Decrypting' }
{ '0': 'DEBUG: Parser: pktLen:12,padLen:10,remainLen:0' }
{ '0': 'DEBUG: Parser: IN_PACKETDATA' }
{ '0': 'DEBUG: Parser: HMAC size:16' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAVERIFY' }
{ '0': 'DEBUG: Parser: Verifying MAC' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)' }
{ '0': 'DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_FAILURE' }
{ '0': 'DEBUG: Parser: IN_PACKETBEFORE (expecting 16)' }
```

**Comment by fentas** [comment]
whats curios is that it seems always this (exact same numbers)
```logs
{ '0': 'DEBUG: Parser: pktLen:4124,padLen:19,remainLen:4112' }
```
at the moment of *freezing*
And after that it seems that the connection is in someway lost judging from the not answered(?) pings.

**Comment by mscdex** [comment]
Do you have a minimal sample of your code that I can use to try to reproduce the problem?

**Comment by mscdex** [comment]
Also, what version of node and `ssh2` module are you using?

**Comment by mscdex** [comment]
Were you ever able to come up with a simple, reproducible example for the latest version of `ssh2`?

**Comment by fentas** [comment]
@mscdex Hey. Sorry for late response. I ended up to simply spawn/pipe to ssh. I try to reproduce this with some code if I have some spare time. I'll close this for now until I came up with some reproducible code. Tx for your effort.
