### ISSUE TITLE
X11 / xeyes with ssh2 (-X option missing)

### ISSUE THREAD

**Issue by lutzbickhardt** [mscdex/ssh2#328]
Hi!
tried your xeyes example between a MAC OS X 10.09, Ubuntu 15.04 kernel 4.1.8 and a RHEL 4.4.7.
In all cases I get a 
STDOUT: lutz@T5500:~$ 
xeyes :: ready
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

If I try with the shell example and xeyes I get: STDOUT: Error: Can't open display: , which is the same as when I login manually without the -X option to ssh.

Any Ideas?

**Comment by mscdex** [comment]
Are you sure you have X running? Is it running on a non-zero display number? what does `echo $DISPLAY` on the client side show?

**Comment by lutzbickhardt** [comment]
Hi Brian,


please see the attachment. It is a screenshot with 4 windows:

a) w. left top:         ssh lutz@192.168.1.33?

b) w. left middle:    ssh -X lutz@192.168.1.33?

c) w. left bottom:    ssh -Y lutz@192.168.1.33?


xeyes display with b) and c) and $DISPLAY is set, so the X-server on the MAC is running.

on a) the message is "Error: Can't open display:?" and xeyes is not running


on the right side I have the node/ssh2 session: message  is the same as with a)


the cmd_server.js is also attached.


What is the equivalent of login with -X or -Y? is it the on("X11, ...) event-handler?


Thanks!

Cordialement

**Comment by lutzbickhardt** [comment]
?

**Comment by mscdex** [comment]
I don't see your attachment. The example in the readme should work fine as-is, provided that `echo $DISPLAY` shows `:0` and not `:1` or something else.

**Comment by lutzbickhardt** [comment]
well, the attachments obviously never made it through. 

echo $DISPLAY yields: "localhost:10.0" when logging in with -X or -Y manually. With the shell-example (and supposedly the X11-example as well as when logging in manually w/o -X/-Y) it displays: 
STDOUT: /bin/bash

STDOUT: lutz@T5500:~$ ech
STDOUT: o
STDOUT:  
STDOUT: $
STDOUT: D
STDOUT: I
STDOUT: S
STDOUT: P
STDOUT: L
STDOUT: A
STDOUT: Y

STDOUT: 

STDOUT: lutz@T5500:~$ xe
STDOUT: y
STDOUT: e
STDOUT: s

STDOUT: Error: Can't open display:

**Comment by mscdex** [comment]
Ok, if your display is on `:10`, then you need to change the port number in the xeyes example from `6000` to `6010`.

**Comment by lutzbickhardt** [comment]
Hi Brian,


1) worked with 6011, but same thing:

...

STDOUT:


STDOUT: lutz@T5500:~$ xeye

STDOUT: s

STDOUT:


STDOUT: Error: Can't open display:


STDOUT: lutz@T5500:~$

xeyes :: ready

events.js:85

      throw er; // Unhandled 'error' event

            ^

Error: connect ECONNREFUSED

    at exports._errnoException (util.js:746:11)

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)



2) with 6010, I got:

xeyes :: ready

STDOUT: echo $SHELL

echo $DISPLAY

xeyes


events.js:85

      throw er; // Unhandled 'error' event

            ^

Error: connect ECONNREFUSED?




3) this is the code I am using:


var net = require('net');
var Client = require('ssh2').Client;

var conn = new Client();

conn.on('x11', function(info, accept, reject) {
  var xserversock = new net.Socket();
  xserversock.on('connect', function() {
    console.log("X11 connected");
    var xclientsock = accept();
    xclientsock.pipe(xserversock).pipe(xclientsock);
  });
  // connects to localhost:0.0
  xserversock.connect(6011, 'localhost');
});

conn.on('ready', function() {
  console.log('Client :: ready');


  conn.shell(function(err, stream) {
    if (err) throw err;
    stream.on('close', function() {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });

    stream.write('echo $SHELL\necho $DISPLAY\nxeyes\n');// 2>/dev/null\n');
  });

  setTimeout(function () {
    conn.exec('xeyes', { x11: true }, function(err, stream) {
        console.log('xeyes :: ready');
      if (err) throw err;
      var code = 0;
      stream.on('end', function() {
        if (code !== 0)
          console.log('Do you have X11 forwarding enabled on your SSH server?');
        conn.end();
      }).on('exit', function(exitcode) {
        code = exitcode;
      });
    });
  }, 1000)

}).connect({
  host: '192.168.1.33',
  port: 22,
  username: 'xx',
  password: 'yy'
});



Cordialement

--------------------------
Lutz BICKHARDT
lutz@bickhardt.fr

NEW COORDINATES !!!
(privat) Graumannsweg 42, D-22087 Hamburg, Germany
(Büro)  Borselstr. 3 - 7 (im Hof), D-22765 Hamburg, Germany

SKYPE: bickhardt

+49 172 3846086 (deutsches Handy / German cell phone)
+49 40 22758122 (privat Hamburg)
+49 40 39190921 (Büro Hamburg)
+33 6 18386906 (portable francais/ French cell phone)
________________________________
De : Brian White <notifications@github.com>
Envoyé : lundi 12 octobre 2015 17:25
À : mscdex/ssh2
Cc : Bickhardt, Lutz
Objet : Re: [ssh2] X11 / xeyes with ssh2 (-X option missing) (#328)


Ok, if your display is on :10, then you need to change the port number in the xeyes example from 6000 to 6010.

-

**Comment by mscdex** [comment]
If you do `netstat -nl` on your local machine, do you see port 6010 listed?

**Comment by lutzbickhardt** [comment]
Hi Brian,

thanks for your patience!


xeyes is running on a linux box: 192.168.1.33

your example is running on a MAC with X-Server: 192.168.1.20.


when I login manually or with the shell example (and do the "netstat -nl" before xeyes) ->


STDOUT: tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN


that points to localhost (as you describe in the doc), but I am running this across a LAN. As 6000 turned into 6010 for :10, where do I specify the IP-address? thought this was done when connecting ?!??



Cordialement

--------------------------
Lutz BICKHARDT
lutz@bickhardt.fr

NEW COORDINATES !!!
(privat) Graumannsweg 42, D-22087 Hamburg, Germany
(Büro)  Borselstr. 3 - 7 (im Hof), D-22765 Hamburg, Germany

SKYPE: bickhardt

+49 172 3846086 (deutsches Handy / German cell phone)
+49 40 22758122 (privat Hamburg)
+49 40 39190921 (Büro Hamburg)
+33 6 18386906 (portable francais/ French cell phone)
________________________________
De : Brian White <notifications@github.com>
Envoyé : lundi 12 octobre 2015 19:52
À : mscdex/ssh2
Cc : Bickhardt, Lutz
Objet : Re: [ssh2] X11 / xeyes with ssh2 (-X option missing) (#328)


If you do netstat -nl on your local machine, do you see port 6010 listed?

-

**Comment by mscdex** [comment]
If your X server is not running on the system you're connecting *from*, then you need to change `localhost` in the example to whatever host *is* listening on port 6010.

**Comment by lutzbickhardt** [comment]
Made it work ->
I. no matter whether x-client and x-server run on the same machine or not, you have to 
  a) add "-display :0"  ->     stream.write('xeyes -display :0\n');
  b) use xserversock.connect(6010, 'localhost');  with "X11DisplayOffset 10" in /etc/ssh/sshd_config.

II. (on the MAC) make sure to have "PasswordAuthentication yes" and "X11Forwarding yes" set (uncommented) in /etc/sshd_config.

Thanks again!

**Comment by zxdong262** [comment]
@mscdex 
Hi, recently I am trying to support x11 with ssh2, so I seached and got to this issue. The comments here do helps, but still I got stucked, come to the step connecting to localhost 6000/ or 6010, it seems no 6000/6010 port opened.

I tested `ssh -X xx@xx.xx` and `xeyes`  with terminal in mac/ubuntu 18.04,  all works, but seems it connected with random port.

```bash
netstat -lant | grep {my-server-ip}

## will show when xeyes running
tcp        0      0 192.168.3.121:40952     my-server-ip:22          ESTABLISHED
tcp        0      0 192.168.3.121:40957     my-server-ip:22          ESTABLISHED
```

With ssh2, I tried to conenct to every port(with a loop), or `info.srcPort`, all could not get `xeyes` running.

```bash
zxd@zxd-N550JV:~/dev/electerm$ node temp/s.js
Client :: ready
STDOUT: Last login: Sat Dec 15 09:44:19 2018 from xxx.xx.xxx.xx

STDOUT: echo $SHELL
echo $DISPLAY
xeyes

STDOUT: execapp@ubuntu:~$ echo $SHELL

STDOUT: /bin/bash
execapp@ubuntu:~$ e
STDOUT: cho $DISPLAY
localhost:11.0
execapp@ubuntu:~$ xeyes
 'info' { srcIP: '::1', srcPort: 56428 }
port 6000
connect ECONNREFUSED 127.0.0.1:56428

```

```js

var net = require('net');
var Client = require('ssh2').Client;

var conn = new Client();

conn.on('x11', function (info, accept, reject) {
  //var xserversock = new net.Socket();
  console.log(info)
  var start = 6000
  //var xclientsock
  function retry() {
    if (start >= 65536) {
      return
    }
    var xserversock = new net.Socket();
    xserversock.on('connect', function () {
      console.log("X11 connected");
      var xclientsock = accept();
      xclientsock.pipe(xserversock).pipe(xclientsock);
    })
    .on('error', (e) => {
      console.log(e.message)
      start ++
      xserversock.destroy()
      //retry()
    })
    console.log('port', start)
    xserversock.connect(info.srcPort, 'localhost');
  }
  retry()
});

conn.on('ready', function () {
  console.log('Client :: ready');

  conn.shell({x11:true},function (err, stream) {
    if (err) throw err;
    stream.on('close', function () {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function (data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function (data) {
      console.log('STDERR: ' + data);
    });

    stream.write('echo $SHELL\necho $DISPLAY\nxeyes\n');
  });

}).connect({
  host: myserver.com',
  username: 'xx',
  password: 'xx'
});
```

When trying to connecting to `info.srcPort`, aftering trying for around 6000 times, it will connect, but could not open xeyes still.

Any updates you can share with me on this topic? Thank you.

**Comment by zxdong262** [comment]
Update:  the whole script works when changes to `stream.write('echo $SHELL\necho $DISPLAY\nxeyes -display :10\n');`

**Comment by zxdong262** [comment]
@lutzbickhardt @mscdex Any way I could skip `-display :10`?

**Comment by mscdex** [comment]
@zxdong262 Change your `$DISPLAY` variable in your shell session appropriately. All X programs look at that shell variable. The `-display` command line argument is just for overriding `$DISPLAY`.

**Comment by zxdong262** [comment]
After several hours, I run the same script again, it just do not work any more, but `ssh -X` in terminal always work in my ubuntu. I doubt that I got it work by some accident action.

**Comment by mscdex** [comment]
This:

``js
xserversock.connect(info.srcPort, 'localhost');
```

is not correct. You want to connect to your *local* X server, whose port never changes. The base port number for X is 6000. So if your `$DISPLAY` is `:0`, then it's just 6000. If `$DISPLAY` is something like `:10` then your port number will be 6010. Connect to that port on localhost and it should work. For X11 forwarding, the information in `info` is typically not useful.

**Comment by zxdong262** [comment]
@mscdex I checked, no 6000, I tried every port is LISTENING, none works
```bash
netstat -lant | grep tcp | grep LISTEN

tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:5570          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:19714         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:3075          0.0.0.0:*               LISTEN     
tcp6       0      0 ::1:631                 :::*                    LISTEN
```

When I tested ssh -X xx@xx.xx and xeyes with terminal, it seems connect to random port. So I tried `info.srcPort`, it worked last night, but now I can not get it work any more.

```bash
netstat -lant | grep {my-server-ip}

## will show when xeyes running
tcp        0      0 192.168.3.121:40952     my-server-ip:22          ESTABLISHED
tcp        0      0 192.168.3.121:40957     my-server-ip:22          ESTABLISHED
```

**Comment by mscdex** [comment]
If your setup is not listening on inet, it may be using only unix sockets. Try connecting to the unix socket at `/tmp/.X11-unix/X${displayNum}` instead.

**Comment by zxdong262** [comment]
@mscdex Thank you, This works!

**Comment by zxdong262** [comment]
Hi, @mscdex, 

I have make it work in mac/windows/linux, but in mac I have to run `xhost +` first, or it will show  the error: `Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: localhost:10.0`, I noticed in iterm running `ssh -X` will just open `Xquartz` and running well, seems it calls `xhost +` internally or some auth process there, could I do this with `ssh2`?

**Comment by mscdex** [comment]
OpenSSH does [make calls out to xauth first](https://github.com/openssh/openssh-portable/blob/b5e412a8993ad17b9e1141c78408df15d3d987e1/clientloop.c#L305-L404) before possibly using a random X auth cookie value as a fallback. Currently `ssh2` always uses a random auth cookie, so that could be the difference.

I don't have a mac to test on, but you could try emulating that behavior and see if that works for you or not. Trying trusted connections (equivalent to OpenSSH's `-Y`) is probably easiest as it simply involves parsing the output of `xauth list ${process.env.DISPLAY}`. Specifically the last two values are used as the protocol name (which should almost always be just `'MIT-MAGIC-COOKIE-1'`) and then the cookie value. You will need to change [this function](https://github.com/mscdex/ssh2/blob/d770b424d1a5e2a738e4203a6181ad88b8f88a85/lib/client.js#L1230) to accept a custom cookie value (and maybe custom protocol name).

If the above ends up working for you, then we can look into supporting custom protocol name and cookie values.

**Comment by zxdong262** [comment]
@mscdex 
Thank you. I can get the cookie value/name from `xauth list`, and set it in reqx11 function for testing, but could not find how to do `Trying trusted connections`. Is there an option about this?

**Comment by mscdex** [comment]
Using the values from `xauth list ${process.env.DISPLAY}` would be allowing trusted connections (meaning you trust the remote X applications). To allow untrusted connections, the process is a little bit more involved.

**Comment by mscdex** [comment]
and you're connecting to the unix socket at `/private/tmp/com.apple.launchd.ymKEe044pX/org.macosforge.xquartz`?

**Comment by zxdong262** [comment]
@mscdex Oh no, I did not think that. I tryed `/private/tmp/com.apple.launchd.ymKEe044pX/org.macosforge.xquartz:0`, it works!
