### ISSUE TITLE
Client.forwardOut which fails will open a new session and not close it

### ISSUE THREAD

**Issue by Rush** [mscdex/ssh2#329]
I am trying to re-use a single SSH connection and do some multiple forwards on it, think of polling for a service that is gonna become available at one point. Today I uncovered a problem .. my server had around 5000 SSH sessions open .. all through a single connection. It seems that I cannot close the extra session cause I only get the error object when this forward fails (due to target port not listening):

```js
client.forwardOut('127.0.0.1', 22, '127.0.0.1', port, function(err, stream) {
  if(err) {
    console.log('CLIENT', channel);
    return self.emit('error', err);
  }
  /* ... */
});
```

`Error: (SSH) Channel open failure: Connection refused`

If `forwardOut` was done in a loop, my `ps aux|grep sshd` would show a growing list of sessions.

It is super easy to reproduce ... if you think test code would help, I can happily provide it.

**Comment by mscdex** [comment]
I'm not able to duplicate the issue. If the channel failed to open, there is nothing to close.

Here is what I used to test:

```javascript
function reExec(i) {
  if (i === 3000)
    return;
  client.forwardOut('127.0.0.1', 1234, '127.0.0.1', 12345, function(err, stream) {
    if (err)
      console.log(err);
    else
      stream.end();
    return reExec(++i);
  });
}
  reExec(0);
```

**Comment by Rush** [comment]
> If the channel failed to open, there is nothing to close.

This statement made me write a full fledged test case which proved I was wrong, then I spent time debugging my application and indeed it was re-doing full connection, so essentially my connection caching code was wrong. I am very sorry for this inappropriately opened issue. Thank you for this great library.
