### ISSUE TITLE
openssh_forwardOutStreamLocal compatibility

### ISSUE THREAD

**Issue by Rush** [mscdex/ssh2#330]
Am I right that this function is available only from OpenSSH 6.7?

I am getting the error with reason `ADMINISTRATIVELY_PROHIBITED`.

The workaround is to run an `.exec("socat STDIO UNIX-CONNECT:/tmp/app.socket")`

**Comment by mscdex** [comment]
Yes, I believe `direct-streamlocal@openssh.com` was available from OpenSSH 6.7+. It will also depend on if `AllowStreamLocalForwarding` in `sshd_config` is set to something other than the default too.
