### ISSUE TITLE
Using ssh2 in the browser with forge?

### ISSUE THREAD

**Issue by creationix** [mscdex/ssh2#331]
I know you're writing this for node using the built-in ssh bindings, but I wonder how much work it would be to have the option to work in the browser using the API provided by https://github.com/digitalbazaar/forge?

**Comment by mscdex** [comment]
As long as it provides all the necessary crypto pieces with the same API as node, it should work fine. However, `forge` doesn't seem to provide the same API and is also currently missing some needed functionality like DiffieHellman and Signing/Verifying support.

Another problem will be getting TCP socket support in the browser. This could be done with a Flash or WebSocket bridge I suppose, but such a bridge again would need to be node API compatible. I know someone had written a browserify module specifically for Chrome Apps that provided a `net` module, but I'm not sure if it's maintained and/or what the compatibility is like for that.

**Comment by creationix** [comment]
Right, implementing the node APIs in the browser would work, but that's a lot of work in some cases.  Node streams, for example, are incredibly complex.

It's probably not worth your trouble since this is an edge cases (ssh from the browser), but an easier method overall would be to design a simple abstraction layer used internally and write adaptors to consume both node and the other APIs.

**Comment by creationix** [comment]
See the comments at https://github.com/creationix/js-git/issues/122#issuecomment-148419370 for motivation in my use case.

**Comment by mscdex** [comment]
Doesn't `readable-stream` already work in the browser?

**Comment by creationix** [comment]
Right, there are probably already a couple implementations of node streams, but why include all that code weight and complexity when it's not visible to the end user and you only need a fraction of the capabilities anyway?

**Comment by calvinmetcalf** [comment]
judging from crypto-browserify/diffie-hellman#16 it is at least somewhat possible to use crypto browserify with it

**Comment by mscdex** [comment]
Closing this for now as this module's main focus is node. If third-party modules like `browserify` and others can make this module run in the browser, then great. This module even supports using a generic stream as its underlying socket (in case you want to do it over websockets or anything else), so it should be easy to use in the browser once you have the crypto API compatibility and node streams support.
