### ISSUE TITLE
Issue with using the ssh2  module in a Firefox add on.

### ISSUE THREAD

**Issue by owlowlgo** [mscdex/ssh2#335]
I am having trouble using the ssh2 module in a firefox add on. When requiring the ssh2 library, it chokes at below in ../ssh2/lib/client.js.
```
var crypto = require('crypto'),
```
Error is:
```
Message: Module `crypto` is not found at resource://gre/modules/commonjs/crypto.js
```

This is the entire output when trying to run the add on.
```  
~/my-addon❯ jpm run -b abrowser
JPM [info] Starting jpm run on My Jetpack Addon
Creating XPI
JPM [info] XPI created at /tmp/user/@my-addon-0.0.1.xpi (449ms)
Created XPI at /tmp/user/@my-addon-0.0.1.xpi
JPM [info] Creating a new profile
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error: my-addon: 
  Message: Module `crypto` is not found at resource://gre/modules/commonjs/crypto.js
  Stack:
    @resource://my-addon/node_modules/ssh2/lib/client.js:1:14
@resource://my-addon/index.js:13:12
run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise-backend.js:922:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:801:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:740:39

console.error: my-addon: 
  Message: Module `crypto` is not found at resource://gre/modules/commonjs/crypto.js
  Stack:
    @resource://my-addon/node_modules/ssh2/lib/client.js:1:14
@resource://my-addon/index.js:13:12
run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise-backend.js:922:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:801:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:740:39

~/my-addon❯ 
‘‘‘

Any advice on resolving this issue would be appreciated.

**Comment by mscdex** [comment]
The module was designed for node. As such, it is expecting certain node core modules to be available, so you cannot simply drop it in a different environment and expect it to work.

AFAIK not even Browserify has enough compatibility yet (especially crypto-wise) for this module to work in the browser.

**Comment by owlowlgo** [comment]
Hello mscdex,

thanks for confirming that the module is not compatible with the Firefox add on environment.

I found the below module, but apparently it's only a partial implementation.
https://github.com/crypto-browserify/crypto-browserify

Would it be your opinion that at this point in time, a module which can perform a remote ssh command execution from the browser does not exist?

**Comment by mscdex** [comment]
There was some Firefox addon for doing ssh (protocol and all), but I'm not sure what state it is in anymore. Also I think Google(?) had a Chrome addon for doing ssh too, but I am not completely sure.

I would guess that most people typically let the server act as a middleman that performs the actual ssh connection, handshaking, etc., where the browser simply sends commands to be executed on the ssh server.

**Comment by owlowlgo** [comment]
Thanks for the info.

> I would guess that most people typically let the server act as a middleman that performs the actual > ssh connection, handshaking, etc., where the browser simply sends commands to be executed on > the ssh server.
I guess that would be the case. The problem I was trying to resolve would have been simplified if ssh could be executed from the add on, but I guess I would have to work around this limitation in another way.

I'll be following this project in the case a crypto lib is developed to work in the browser :)
