### ISSUE TITLE
readyTimeout problem

### ISSUE THREAD

**Issue by Kurtas** [mscdex/ssh2#337]
Hi, 

I have problem that client doesn't destroy socket connection. When I have device where is enabled 22 port for SSH, but the device refuses a connection immediately after success connection, then client still "waiting" - socket isn't destroyed.

I'm using readyTimeout in config, but you have clearTimeout(self._readyTimeout); in end & close events and this events are fired before timeout.

I can listen for end and close and destroy it by myself, but I think that it's a bug. Can you confirm?

**Comment by mscdex** [comment]
I'm a bit confused as to what you mean. Can you set `debug: console.log` in your connection config object and post the output?

**Comment by Kurtas** [comment]
Linux console log - as you can see, remote device immediately refuses connection (ssh2 have emited close & end events in this case)
```
debian@debian:~/discovery/tools$ ssh admin15@10.33.255.4
ssh_exchange_identification: Connection closed by remote host
```

Here is log from ssh2
```
DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.17'
DEBUG: Client: Trying 10.33.255.4 on port 22 ...
DEBUG: Client: Connected
```

**Comment by mscdex** [comment]
The connection wasn't refused, it was closed. A connection was made but then the remote end closed it immediately after connection.

**Comment by Kurtas** [comment]
Ok, but socket connection remains open, it should be closed (destroyed) or no?
Now I must listen on end event and there call ssh.end(); ssh.destroy(); then node process is finished.

**Comment by mscdex** [comment]
It will only close when either you explicitly close it or the remote end does. For whatever reason the server is not immediately closing the connection like with OpenSSH. Not knowing anything about the server, perhaps it is explicitly disallowing OpenSSH clients?

If it should be automatically closing, can you come up with a reproducible setup that I can try locally?

**Comment by Kurtas** [comment]
I can set up forwarding for your IP, if you agree just send me your IP.

**Comment by mscdex** [comment]
I'd prefer to be able to set up something locally, that way I can write a proper test for this.

**Comment by Kurtas** [comment]
It's a Cisco device, I don't know if I can properly set up same behavior on linux ssh. I will try to find how to do it and let you know.

**Comment by mscdex** [comment]
Hrmm well, you can get verbose output from OpenSSH's client by adding `-vvv` to your options: `ssh -vvv admin15@10.33.255.4`. That might help show where exactly it's ending.

How are you verifying that the socket is still alive after you see the `end`/`close` events?

**Comment by Kurtas** [comment]
I'm sorry, I found the problem in my code. Your client works fine, socket is closed.
