### ISSUE TITLE
Create a usage / hints / FAQ or whatever document 

### ISSUE THREAD

**Issue by minesworld** [mscdex/ssh2#343]
so all "issues" related to the USAGE and BEHAVIOUR of ssh2 could be closed...

It should be sufficient to copy and paste the questions and your answers to those docs :-)

Nice "side effect": users having the same question wouldn't ask again if they don't look into closed issues...

**Comment by mscdex** [comment]
I don't entirely agree. However, I don't object to adding more to the wiki, including more examples of "here's a common thing using the OpenSSH client and here's how you do it in ssh2."
