### ISSUE TITLE
how i make port forwarding to 8000 and make php calling

### ISSUE THREAD

**Issue by hotboyconvoi** [mscdex/ssh2#345]
i had installed nodejs in xampp and  when i use script get error cant load module in nodejs.
script.js 
"var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.forwardIn('127.0.0.1', 1081, function(err) {
    // if (err) throw err;
    if (err) console.log(err);
    console.log('Listening for connections on server on port 1080!');
  });
}).on('tcp connection', function(info, accept, reject) {
  console.log('TCP :: INCOMING CONNECTION:');
  console.dir(info);
  accept().on('close', function() {
    console.log('TCP :: CLOSED');
  }).on('data', function(data) {
    console.log('TCP :: DATA: ' + data);
  }).end([
    'HTTP/1.1 404 Not Found',
    'Date: Thu, 15 Nov 2012 02:07:58 GMT',
    'Server: ForwardedConnection',
    'Content-Length: 0',
    'Connection: close',
    '',
    ''
  ].join('\r\n'));
}).connect({
  host: '67.214.224.157',
  port: 22,
  username: 'admin',
  password: 'default'
});" 

error: ">node xyz.js
ule.js:339
 throw err;
 ^

or: Cannot find module 'ssh2'
 at Function.Module._resolveFilename (module.js:33
 at Function.Module._load (module.js:287:25)
 at Module.require (module.js:366:17)
 at require (module.js:385:17)
 at Object.<anonymous> (C:\xyz.js:2:18)
 at Module._compile (module.js:435:26)
 at Object.Module._extensions..js (module.js:442:1
 at Module.load (module.js:356:32)
 at Function.Module._load (module.js:311:12)
 at Function.Module.runMain (module.js:467:10)
"
i must set local path
var Client = require('C:\\Program Files\\nodejs\\node_modules\\ssh2'); 
to solve but node cant listen port when i use php call to 127.0.0.1:1081 or i type on url.

php script:

<?php

$url = 'http://whereismyip.com/';
$ch = curl_init();
     
if($ch === false)
{
    die('Failed to create curl object');
}
     
$timeout = 5;
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 0);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
 
//proxy details
curl_setopt($ch, CURLOPT_PROXY, '127.0.0.1:1081');
curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);
 
$data = curl_exec($ch);
print_r($data);
curl_close($ch);

**Comment by mscdex** [comment]
You need to `npm install ssh2` and *not* `npm install -g ssh2`. The `-g` flag should only be used for modules that provide command-line utilities. It shouldn't be used in an attempt to make a module available from anywhere.

**Comment by hotboyconvoi** [comment]
yes, i do it, but still be problem. i use window server 2008.and i see module was installed in C:\Program Files\nodejs\node_modules\ssh2. i must use real path.

**Comment by mscdex** [comment]
If you're not using `-g` and it's still installing to that path, then you're either doing `npm install ssh2` in `C:\Program Files\nodejs` on accident, or there is some issue with npm on Windows (if this is the case, you should file an issue on the [npm issue tracker](https://github.com/npm/npm/issues)).

Either way, this is not an issue with this module.
