### ISSUE TITLE
Race condition when using Client.exec()

### ISSUE THREAD

**Issue by thrucker** [mscdex/ssh2#348]
I'm using `Client.exec()` for executing a command and getting its exit code like this
```
client.exec('some command', function(err, stream) {
  if (err) throw err;
  stream.on('close', function(code, signal) {
    console.log('stream closed, code = ' + code + ', signal = ' + signal);
    client.end();
  });
});
```
This usually works, but I noticed that sometimes the `close` event is never emitted by the `stream`.

I further investigated the issue and found that it's a race condition between actually executing the command and registering the event listener on the stream.

If you execute a command which runs really fast it may happen that the server already responed with the result before the `close` event listener is registered on the `stream`.

To reproduce this you can explicitly delay the registration of the listener like this
```
client.exec('some command', function(err, stream) {
  if (err) throw err;
  setTimeout(function() {
    stream.on('close', function(code, signal) {
      console.log('stream closed, code = ' + code + ', signal = ' + signal);
      client.end();
    });
  }, 200);
});
```
If the delay is big enough the event listener never gets called.

**Comment by unknownbrackets** [comment]
Well, it definitely makes sense that registering the close listener on a delay might cause it to never get called.  Are you sure if you register it synchronously, it's still sometimes not called?

-[Unknown]

**Comment by thrucker** [comment]
Yes, I'm sure that this also happens when registering the event listener synchronously. The `setTimeout` example should just demonstrate how to reproduce it.

But unless there is a guarantee that the command is not executed before the callback of `Client.exec()` there's a chance that this problem occurs.

By turning on debug logging in ssh2 I can see that there's already client-server communication between calling `Client.exec()` and execution of its callback.

**Comment by minesworld** [comment]
Nope. The timeout example isn't valid. Valid would be setImmediate() as this is in node semantics 'call after I/O events callbacks'...

**Comment by minesworld** [comment]
Also it would be useful if you could provide the log of when it failed...

**Comment by thrucker** [comment]
I can't seem to reproduce this with setImmediate() in this minimal example although the same issue occurs when using setImmediate() in my project. So it probably is caused by something else which needs further investigation on my side.
I'll close this issue for now.

PS: As a workaround for my specific problem I add a `sleep 0.2` to the command string which isn't nice but gets me rid of the problem.
