### ISSUE TITLE
When use wrong username, it just hang up and do nothing, no errors emitted.

### ISSUE THREAD

**Issue by MuFang** [mscdex/ssh2#349]
Hi, when I test my program and use a wrong username to login the remote server with password, I find there is no errors emitted. Then I tried debug mode and according to the debug info, it seems waiting for a packet come in, but there is none. 
These are parts  of debug info.
![in-packet](https://cloud.githubusercontent.com/assets/12620162/10902344/70650e12-8237-11e5-9bf9-9d40ad0d1a8c.png)
![no in-packet](https://cloud.githubusercontent.com/assets/12620162/10902345/70720f22-8237-11e5-83a6-8bbd3c2b1e32.png)

I tried conn.on('error',function) and conn.on('timeout', function) to get errors if there are, but I cannot get them.

So how can my program know I'm using a wrong username?

Thank you.

**Comment by mscdex** [comment]
The server should respond with an authentication failure message. What server software and version is this connecting to? Is this something I can duplicate on my end?

**Comment by minesworld** [comment]
Did you set the readyTimeout value?

**Comment by MuFang** [comment]
The server uses "SSH-2.0-OpenSSH_6.2 "(read from debug info)

**Comment by MuFang** [comment]
So you mean it's server's problem?

**Comment by MuFang** [comment]
Yes, I set 10 seconds. But I didn't get 'timeout' emitted :(

Date: Tue, 3 Nov 2015 00:11:03 -0800

**Comment by mscdex** [comment]
So you don't see an `error` event after 20 seconds (the default `readyTimeout`)?

**Comment by MuFang** [comment]
@mscdex  No, there is no errors at 20 seconds, but after 2 minutes, it will connect the server again.
When it connect again, there is no error received in my program, but the browser get `ERR_EMPTY_RESPONSE`

**Comment by mscdex** [comment]
Do you have administrative access to this server? If so, it might be beneficial to start the ssh server with debugging turned all the way up so we can see what it's seeing/doing. If you do not have admin access, I do not know what else to suggest as I cannot duplicate the problem with a vanilla OpenSSH 6.2 installation on Linux.

However, the ready timer should fire as long as it's still connected and there is no successful authentication method yet. I am not sure why you are not seeing that. Did you attach a `close` event listener just to be sure there wasn't an abrupt disconnection or something?

**Comment by MuFang** [comment]
Ah...  I forgot to add `close` event listener before, after added, I can see the connection indeed closed in this case.

I will try to run ssh in debug mode later, it's the company's server, so it may be a little more complicated (and I'm not very familiar with ssh).

Also I find that when log in with wrong username and an empty string `""` password, there is indeed an error, but with a password except `""`, there is no errors.

**Comment by mscdex** [comment]
Typically a well-behaved SSH implementation (like OpenSSH) will send an actual disconnect message instead of just abruptly terminating the connection like that. I'm surprised that you're not seeing that in the debug output. Hopefully there isn't something in between that is mitm'ing...

**Comment by mscdex** [comment]
I'm not able to duplicate the wrong username with a non-empty password issue you mentioned. If you can come up with a server-side configuration that I can use to duplicate that particular issue, please open a new issue about it.
