### ISSUE TITLE
ed25519 keys not working

### ISSUE THREAD

**Issue by brianmhunt** [mscdex/ssh2#352]
Not sure if this is an issue here or upstream, but I just wanted to give a heads up that `ed25519` host keys do not appear to be supported.

When running e.g.

``` javascript
conn = new require('ssh2')()
conn.connect({
  host: 'host.local',
  port: "22",
  username: "bmh",
  agent: process.env['SSH_AUTH_SOCK'],
  debug: console.log})
```

The output includes:

> DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
> DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519

I doubt there's anything on my end (Mac OS X 10.11.1; node 5.0.0; fresh package install of `ssh2@04.12`); it looks like the support is simply not yet in [ssh2-streams](https://github.com/mscdex/ssh2-streams).  I can re-file a bug there, if that is preferable.

:beers:

**Comment by brianmhunt** [comment]
Notable link on ed25519 support in Node: https://github.com/nodejs/node/issues/2144

Two options:

- https://github.com/paixaop/node-sodium
- https://github.com/dazoe/ed25519

**Comment by mscdex** [comment]
Yes, this is a known issue. The problem though is that the pure js implementations for some of these algorithms that OpenSSL currently does not support are slow.

I think I would only want to start incorporating these pure js algorithm solutions once there is the ability to override the hard-coded list of algorithms, ciphers, etc. This way if someone doesn't want to use the pure js algorithms (for performance reasons), then they can (easily) opt out of that. However, I haven't had time to work on this.

**Comment by brianmhunt** [comment]
Thanks @mscdex 

I appreciate the concerns over performance issue and opting-out.

As host key algorithm itself is only run once per connection, the performance of that particular implementation should not be a big concern. That said, I understand why you might want to make sure an opt-out scheme of some sort would be in place before going down this road.

Cheers.

**Comment by mscdex** [comment]
FWIW I've just landed ECDSA support in `ssh2`/`ssh2-streams` and it works, but will need to write tests for it yet.

I'm still not sure when/if OpenSSL will support ed25519 though. There is an ed25519 issue on OpenSSL's repo [here](https://github.com/openssl/openssl/issues/487) and [here]() FWIW. There is also another OpenSSL github issue for curve25519 [here](https://github.com/openssl/openssl/issues/309) that is supposedly "in progress" and a related node issue [here](https://github.com/nodejs/node/issues/1495).

I should also note I would be open to the possibility of having an `optionalDependency` on a compiled addon that implemented ed* key support.

**Comment by stefreak** [comment]
https://github.com/openssl/openssl/issues/309 says "x25519 is in [OpenSSL] 1.1"

Can this be implemented now? I would appreciate it enormously :)

**Comment by mscdex** [comment]
It won't be supported at least until OpenSSL 1.1.x is included in a version of node. See [this PR](https://github.com/nodejs/node/pull/11828) for more information.

**Comment by karlhorky** [comment]
I suppose #18770 is the more updated issue now.

**Comment by karlhorky** [comment]
Oh wait, reading a bit deeper, in that issue there is the line:

> We currently have 1.1.0 support in Node

Looks like this is supported after all now:

Node.js 10: https://github.com/nodejs/node/pull/16130#issuecomment-343652986
Node.js 8 backport: https://github.com/nodejs/node/pull/18622#issuecomment-366545596

**Comment by mscdex** [comment]
Nothing has changed, node doesn't have OpenSSL 1.1.1 yet.

**Comment by themarkymark-steem** [comment]
> Nothing has changed, node doesn't have OpenSSL 1.1.1 yet.

Looks like it's about to happen.
https://github.com/nodejs/node/pull/25381

**Comment by mscdex** [comment]
Right, but it will still take time before it makes it into a release and then into the hands of end users :)

**Comment by silverwind** [comment]
Is this fixed by https://github.com/mscdex/ssh2/commit/e40ca05354caf8266dc208dbe4eacc1a20c772c7?

**Comment by mscdex** [comment]
Kind of, but support in node only exists in node master currently.

**Comment by mscdex** [comment]
Full Ed25519 support now available in `ssh2` v0.8.3 when used with node v12.0.0.

**Comment by zxdong262** [comment]
根据这个应该可以，但是仍然不行，我还没有找到原因，不过用默认方式创建的key还是支持的
 https://github.com/mscdex/ssh2/issues/352

**Comment by AlexandrKravchuk** [comment]
Hello! I just was wondering if it's possible to use ed25519 based connection with the node version lower than 12?

**Comment by mscdex** [comment]
@AlexandrKravchuk Not without adding some sort of JavaScript-only ed25519 implementation, which I prefer not to do.

**Comment by Ayfri** [comment]
Any update ?
