### ISSUE TITLE
how to implement to clone session

### ISSUE THREAD

**Issue by CharellKing** [mscdex/ssh2#354]
how to implement to clone session like SecureCrt:
we have built a session to a host; then we can clone the session without input the password; when ssh server's password is dynamic, it's very convenient

**Comment by CharellKing** [comment]
i find the solution.
https://www.npmjs.com/package/ssh-config

**Comment by mscdex** [comment]
I've never used SecureCrt but my guess is that they're simply just reusing the existing connection. If this in fact the case, then all you have to do is just keep making requests using the same connection object or even the same sftp object. Both SSH and SFTP protocols are multiplexed so there is no problem performing different requests in parallel.
