### ISSUE TITLE
Saving data from SCP sink mode

### ISSUE THREAD

**Issue by hmngwy** [mscdex/ssh2#355]
On an SSH server, is it possible to catch the file/data that is sent in SCP sink mode within the 'exec' event?

```
session.once('exec', function(accept, reject, info) {
  var stream = accept();
  # somehow get the file contents here
  stream.end();
});
```

The argument `info` is only populated with the command itself `{ command: 'scp -t /' }` when I run something like `scp -P 51414 hello.txt foo@localhost:/`. I'm not sure where to collect the contents of hello.txt from. 

Does the library catch the file contents somewhere or is it not supported?

**Comment by mscdex** [comment]
Well, `scp` (and not `sftp`, which some systems have `scp` aliased to `sftp`) uses a special protocol itself for doing file transfers, but in general `stream` is just a bidirectional stream. So you can `.write()` to it and read from it using `.read()` or listening for `data` events on it. Calling `.end()` will close the stream.

**Comment by hmngwy** [comment]
I see, ok that makes sense.

I just realized, the client waits for the server to send a binary 0/1 to begin the `sink`. So, it doesn't really send the file immediately after successful authentication, it waits for an 'OK' message.

How do I make the stream respond with a binary 0? `.write` only accepts strings.

**Comment by mscdex** [comment]
`.write()` does not accept only strings, it can accept Buffers too just like any normal Writable stream in node. So you could do either `stream.write('\x00', 'binary');` or `stream.write(new Buffer([0]));`

**Comment by hmngwy** [comment]
Awesome, thanks. 

This gets the job done for me:

```
session.once('exec', function(accept, reject, info) {
  var stream = accept();

  if (info.command.indexOf('scp -t')===0) {
    stream.write('\x00', 'binary');

    var StringDecoder = require('string_decoder').StringDecoder;
    var buffersEqual = require('buffer-equal-constant-time');
    var dec = new StringDecoder('utf8');

    var head, payload='', last;
    stream.on('data', function(buffer){
      if(head === undefined) {
        head = dec.write(buffer); // mode length filename
        stream.write('\x00', 'binary');
      } else if(buffersEqual(buffer, new Buffer('\x00', 'binary'))) {
        // make sure to verify payload.length with announced length before using it
        stream.end();
      } else {
        payload += dec.write(buffer);
        stream.write('\x00', 'binary');
      }
    });
  }

});
```

**Comment by medecau** [comment]
@hmngwy thanks for sharing the snippet.

In my tests the file transfers but then hangs.
If I call `stream.end()` after completing the transfer then the client will exit with return code 1.

pinging @mscdex 
Do you know what might be required of the server to signal the end of the session other than terminating the stream?
Also tried a selection of escape characters but nothing worked. Please share the required incantation If you can.

I'm testing with the builtin mac OSX SCP client. I tested the builtin SCP client against the builtin SSH server and it works fine. Thus I am assuming the fault is on my side.

**Comment by mscdex** [comment]
@medecau If the only problem is the exit code, did you try explicitly setting the exit code (`stream.exit(0)`) before ending the stream (`stream.end()`)?

**Comment by medecau** [comment]
It works.
Thank you so very much.
