### ISSUE TITLE
Maintain connection ?

### ISSUE THREAD

**Issue by Aewil** [mscdex/ssh2#357]
Hello !

I think all is in the title. I have some issues to create a chanel all the time and maintain it.

Can you help me please ?

BR,

Aewil

**Comment by mscdex** [comment]
I don't understand what you mean. You can set `keepaliveInterval` and `keepaliveCountMax` in your connection config object, which are disabled by default and represent OpenSSH's `ServerAliveInterval` and `ServerAliveCountMax` client settings respectively.

**Comment by Aewil** [comment]
Actually, i want to let users send new requests all the time. In my app, i have a console that returns ssh responses, the user should send few commands through it.

Best Regards,

Aewil

**Comment by mscdex** [comment]
If you're referring to `.exec()` not maintaining state like the current working directory, then there is no easy way around that. You might look into using `.shell()` instead, but parsing command output will be more difficult. Some of that can be minimized by changing the shell prompt to something more easily parseable of course.

**Comment by mscdex** [comment]
Closing this for now. If my previous comment did not accurately describe what you're after, let me know.
