### ISSUE TITLE
error cause crash of app

### ISSUE THREAD

**Issue by zerr0s** [mscdex/ssh2#359]
Hi,

Forgive me for my bad english. I'm trying to connect to several servers to execute a command and get the results. If the connection is ok, no problem, I can get the results and display it on my app.

But if the connection is KO (key exchange problem, or firewall issue), the connection cause this error and crash nodejs:

 >events.js:141
 >     throw er; // Unhandled 'error' event
 >     ^
>
>Error: All configured authentication methods failed
 >   at tryNextAuth (/USR/mut/apache2-mut/htdocs/dev/testSSH/node_modules/ssh2/lib/client.js:293:17)
>    at SSH2Stream.onUSERAUTH_FAILURE (/USR/mut/apache2-mut/htdocs/dev/testSSH/node_modules/ssh2/lib/client.js:472:5)
>    at emitTwo (events.js:87:13)
>    at SSH2Stream.emit (events.js:172:7)
>    at parsePacket (/USR/mut/apache2-mut/htdocs/dev/testSSH/node_modules/ssh2-streams/lib/ssh.js:3650:10)
>    at SSH2Stream._transform (/USR/mut/apache2-mut/htdocs/dev/testSSH/node_modules/ssh2-streams/lib/ssh.js:555:13)
>    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
>    at SSH2Stream._read (/USR/mut/apache2-mut/htdocs/dev/testSSH/node_modules/ssh2-streams/lib/ssh.js:213:15)
>    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
>    at doWrite (_stream_writable.js:292:12)
>[nodemon] app crashed - waiting for file changes before starting...

My code is:
```javascript
ar conn = new Client();
      conn.on('ready', function() {
        conn.exec('uptime', function(err, stream) {
          stream.on('close', function(code, signal) {
            conn.end();
          }).on('data', function(data) {
            console.log(data);
            res.send(data);
          }).stderr.on('data', function(data) {
            console.log('STDERR: ' + data);
            res.send(data);
          }).on('error', function(err) {
            console.log(err);
          })
        });
      }).connect({
        host: req.body.server,
        port: 22,
        username: user,
        privateKey: require('fs').readFileSync(mykey)
      }).on('error', function(e) {
        console.log(e);
      });
```
I don't know what I do wrong. I use the master of ssh2 : 
"ssh2": "https://github.com/mscdex/ssh2/tarball/master"

**Comment by mscdex** [comment]
I'm not sure how your code is actually connecting at all since `.connect()` currently does not return anything, so there should be a `TypeError` with your `.on('error', ...)` at the very end there.

However, adding an `error` handler like that is what you need. Try adding it separately like:

```javascript
conn.on('error', function(e) {
  console.dir(e);
});
```

**Comment by zerr0s** [comment]
ohhhhh. right !!

I have to catch the event like this i think:

```javascript
}).on('error', function(error) {
        console.log('[ERROR]: '+error);
}).connect({
...
...
```

Thanks !!!
