### ISSUE TITLE
TERM environment variable not set.

### ISSUE THREAD

**Issue by zerr0s** [mscdex/ssh2#360]
Hi,

Forgive me for my bad english. I have this result on some commands:
"TERM environment variable not set."

I tried to put { pty: true } on my exec:
conn.exec(req.body.cmd, { pty: true }, function(err, stream) {
...

But when I put this option, nodejs crash when executing the commands. I trie to execute a command that was running well (ls /) before the option, and it's not working any more with pty. Is there a way to fix the results of ssh commands using the pty option ?

I'm sending all results to a frontend to populate a div.

**Comment by mscdex** [comment]
Can you explain more about what happens when you say node "crashes?"

Did you try prepending something like `'TERM=xterm '` to `req.body.cmd`?

**Comment by zerr0s** [comment]
Yess I tried to put "TERM=xterm "+req.body.cmd without pty, and the result is:
top: failed tty get

The command was "top -n 1"

If I put pty:
> conn.exec("TERM=xterm "+req.body.cmd, {pty: true}, function(err, stream) {...

nodejs crash with:
>_http_outgoing.js:346
>    throw new Error('Can\'t set headers after they are sent.');
>    ^
>
>Error: Can't set headers after they are sent.
 >   at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)

And I get a partial output:
>[?1h=[H[2J[?25l(B[mtop - 16:47:01 up 6 days, 1:34, 3 users, load average: 0,00, 0,01, 0,05(B[m[39;49m(B[m[39;49m[K

The whole code:
```javascript
var conn = new Client();
      conn.on('ready', function() {
        var cmdDate = format.asString('yyyyMMdd_hhmmss_SSS', new Date());
        conn.exec("TERM=xterm "+req.body.cmd, {pty: true}, function(err, stream) {
          stream.on('close', function(code, signal) {
            conn.end();
          }).on('data', function(data) {
            var fs = require('fs');
            fs.writeFile('./data/'+req.body.server+'_'+cmdDate+'.log', data, function(err) {
              if(err) {
                console.log(err);
              }
            })
            res.send(data);
          }).stderr.on('data', function(data) {
            console.log('STDERR: ' + data);
            res.send(data);
          });
        });
      }).on('error', function(error) {
        console.log('[ERROR]: '+error);
        res.send(JSON.stringify(error));
      }).connect({
        host: req.body.server,
        port: 22,
        username: config.sshUser,
        privateKey: require('fs').readFileSync(config.sshKey)
      });
```

**Comment by mscdex** [comment]
The problem is you're calling `res.send()` inside your `data` event handlers. `res.send()` internally attempts to write response headers, write the chunk of data you pass to it, and then closes the connection. Since the `data` events can fire more than once, that means you may be trying to send response headers more than once. To fix this particular issue, you will probably want to buffer the output of the command and then `res.send(buffer)` inside your `close` event handler.

Secondly, if you don't have a fancy front-end that can interpret the special escape (in this case, xterm) sequences, then you can use `TERM=dumb` instead to get plain/unstyled text output.

Lastly, you should be careful about blindly passing arbitrary commands like that to your server.

**Comment by zerr0s** [comment]
ok, I'll search how to buffer ans put the res.send after closing connection. Do you have an exemple about it ?

This app is not for a public use and will be use juste for one sudo command finally, but on a lot of servers.

**Comment by mscdex** [comment]
```javascript
var buffer = '';
stream.on('data', function(d) {
  buffer += d;
}).on('close', function() {
  res.send(buffer);
});
```

**Comment by zerr0s** [comment]
lol. I've already done that. Thanks a lot for your help It's working now :)
