### ISSUE TITLE
Interactive-keyboard doesn't work

### ISSUE THREAD

**Issue by zhulduz** [mscdex/ssh2#361]
Hi everyone!

I found a bug when I was trying to connect to a vagrant without setting a password: event 'keyboard-interactive' doesn't work. When I send the password to a method ```client.connect```:
```javascript
client.connect({
    host: '127.0.0.1',
    port: 2200,
    username: 'vagrant',
    tryKeyboard: true,
    password: 'some_password',
    debug: console.log
})
```
 it works perfectly.  

Here code, that I use:

 ```javascript
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function () {
    console.log('Client :: ready');
    conn.shell(function (err, stream) {
        if (err) throw err;
        stream.on('close', function () {
            console.log('Stream :: close');
            conn.end();
        }).on('data', function (data) {
            console.log('STDOUT: ' + data.toString());
        }).stderr.on('data', function (data) {
                console.log('STDERR: ' + data.toString());
            });
        stream.write('exit\n');
    });
}).on('keyboard-interactive', function() {
    console.log("I work")
}).connect({
    host: '127.0.0.1',
    port: 2200,
    username: 'vagrant',
    tryKeyboard: true,
    password: null,
    debug: console.log
    }
);
```
Here debug logs: https://gist.github.com/zhulduz/88d14479c1cae81f3658#file-ssh2-log-md
Node version = v0.12.2

Thanks in advance)
Looking forward to hearing from you any idea)

**Comment by zhulduz** [comment]
Here my vagrant config file:

```sh
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2200
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/zhulduz/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

Vagrant version = Vagrant 1.7.4
OS = Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic-pae i686)

**Comment by mscdex** [comment]
Are you sure the server supports `keyboard-interactive` authentication? It looks like it's rejecting that request immediately. That is why you're not seeing the event fire.

**Comment by mscdex** [comment]
If you're using the stock `sshd_config` provided Ubuntu Precise, then `keyboard-interactive` is disabled by default. You can enable it by setting `ChallengeResponseAuthentication yes`.

**Comment by zhulduz** [comment]
You are absolutely right.
It works fine when I set the correct settings.
Thanks a lot.
