### ISSUE TITLE
ssh2 server disconnect client after 1 minute of login

### ISSUE THREAD

**Issue by mmis1000** [mscdex/ssh2#381]
I tried it with both windows and linux.
With the example.
My client always got disconnect after 1 minute of login.
With `Received disconnect from 127.0.0.1: 11:` message

Is there any addition requirement to make persistent connection work?

**Comment by mscdex** [comment]
Try re-installing `ssh2`. I pushed out a new version of `ssh2-streams` (v0.0.20) which should fix it (I think).

**Comment by mscdex** [comment]
@mmis1000 Are you still encountering this issue with the latest versions of `ssh2` and `ssh2-streams`?

**Comment by mmis1000** [comment]
@mscdex
No, it works fine now.
