### ISSUE TITLE
Mechanics of closing a long running client process

### ISSUE THREAD

**Issue by johnnyman727** [mscdex/ssh2#382]
Hi there! I'm using the `ssh2` lib as a dependency of the [tessel CLI](github.com/tessel/t2-cli) project. It's been working marvelously so far except for one anomaly. When I create an SSH client, run an `exec` call, and then call `.end` on the client (or `signal("KILL")` on the stream), to kill a long running process (like `node`) the remote process stays alive. Is that the intended behavior? 

For example, in this simplified example, I can send the process the kill command and even get the `close` event to be fired, but the process continues running on the device:
```.js
var ssh = require('ssh2');
var fs = require('fs');
var path = require('path');
var osenv = require('osenv');
var shellescape = require('shell-escape');


var authPath = path.join(osenv.home(), '.tessel');
var idrsa = 'id_rsa';
var authKey = path.join(authPath, idrsa);
var key = fs.readFileSync(authKey);

client = new ssh.Client();

client.on('ready', function() {
  console.log('Device ready:');

  client.exec(shellescape(['node', '/tmp/remote-script/__tessel_program__.js']), function(err, stream) {
      if (err) {
          throw err;
      }
      else {
          stream.on('close', function(code, signal) {
              console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
              client.end();
            })
          // Give the process enough time to load
          var i = 7;
          console.log('will close in', i, 'seconds');
          var countdown = setInterval(() => {
            console.log(i);
            if (i === 0) {
                console.log('closing the stream!');
                stream.signal('KILL');
                clearInterval(countdown);
            }
            i--;
          }, 1 * 1000);
      }
  })
}).connect({host: 'Hen.local', username: 'root', port: 22, privateKey: key});
```
I recognize that this could be an issue stemming from the SSH implementation on `dropbear` (the OpenWRT SSH lib) but I wanted to make sure I was using the `ssh2` library properly first.

Thanks!

**Comment by johnnyman727** [comment]
Ah I figured it out. I need to add the `{pty: true}` to my exec calls.

**Comment by mscdex** [comment]
Ah ok, glad you found a solution!

**Comment by johnnyman727** [comment]
Thanks @mscdex - it doesn't really works properly yet. Is there an alternative method you might recommend?

Adding that option seems to have more effects than I was expecting. For example, something changed about the way data is written over `stdin`. I'm not exactly sure how yet, but I was writing JavaScript files over stdin to a device and running them with node - once I added the `pty` option, those files had incorrect syntax.

**Comment by mscdex** [comment]
All `stream.end()` does is close stdin. Many programs exit when this happens, but it's not required.

As far as sending signals to processes, it can be tricky. For example, OpenSSH does not currently implement the official way of sending signals to processes (`ssh2`'s `signal()` method). So for those servers typically you could try to to send an appropriate ASCII character. For example to send SIGINT, you would `stream.write('\x03')`. I'm not sure about other signals. If worse comes to worse, you could always try to `ssh.exec()` with `kill` or `pkill`.

**Comment by johnnyman727** [comment]
Thanks for the advice @mscdex. I went ahead and just added the `pty` option only on the `exec` that starts the node process instead of all of them (including the one that writes the JS over `stdin`). It seems to do the trick.

Keep up the great work!

**Comment by jt3k** [comment]
another solution:

I used `&` after the command, and now I can close the programs by `stream.close()` methods.

my code:
![](https://i.imgur.com/jP4JjaN.png)

it works!

**Comment by johnnyman727** [comment]
Thanks for the hint @jt3k! That's a bit cleaner than setting `pty` to `true`. Maybe, one day, I'll understand why these two workarounds actually fix it :)
