### ISSUE TITLE
OPEN event never fired

### ISSUE THREAD

**Issue by codebudo** [mscdex/ssh2#383]
I'm trying to use the server example from the README.md and connect to it with a command-line sftp client like so `sftp -oPort=2223 foo@localhost:/tmp/foo.txt`. The goal is to create a server that an sftp client can connect to and interact with as though it were a filesystem. The example connects and authenticates as expected, but I'm not sure what even is supposed to fire next. Is it 'OPEN'? It appears as though the sftp client is sending it when I ask for verbose output but the event never fires on the server.

<pre>
    $ sftp -vv -oPort=2223 foo@localhost:/tmp/foo.txt
    <snip>
    foo@localhost's password:
    debug2: we sent a password packet, wait for reply
    debug1: Authentication succeeded (password).
    Authenticated to localhost ([::1]:2223).
    debug2: fd 6 setting O_NONBLOCK
    debug1: channel 0: new [client-session]
    <b>debug2: channel 0: send open</b>
    debug1: Entering interactive session.
    <snip>
    Connected to localhost.
    debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
</pre>

The server portion looks like this:

    var fs = require('fs');
    var ssh2 = require('ssh2');
    var OPEN_MODE = ssh2.SFTP_OPEN_MODE,
        STATUS_CODE = ssh2.SFTP_STATUS_CODE;

    // test with `sftp -oPort=2223 foo@localhost` and use password 'bar'
    var port = 2223;

    new ssh2.Server({
      privateKey: fs.readFileSync('host.key')
    }, function(client) {
      console.log('Client connected!');
  
      client.on('authentication', function(ctx) {
        if (ctx.method === 'password'
            && ctx.username === 'foo'
            && ctx.password === 'bar')
        {
          console.log('accept');
          ctx.accept();
        } else{
          console.log('reject', ctx.method);
          ctx.reject();
        }
      }).on('ready', function() {
        console.log('Client authenticated!');
  
        client.once('session', function(accept, reject){
          console.log('session');
          var session = accept();

          session.once('sftp', function(accept, reject) {
            console.log('Client SFTP session');

            var sftpStream = accept();
            console.log('accepted stream');
            sftpStream.on('OPEN', function(reqid, filename, flags, attrs) {
              console.log(' OPEN');
              // NEVER GETS HERE
            
              var handle = new Buffer(4);
              sftpStream.handle(reqid, handle);
              return sftpStream.status(reqid, STATUS_CODE.OK);
            }).on('REALPATH', function(reqid, path) {
              console.log(' REALPATH');
              // BUT I GET THIS
            
              //return sftpStream.status(reqid, STATUS_CODE.OK);
            });

          }).once('pty', function(accept, reject, info){
            console.log('pty');
          }).on('window-change', function(accept, reject, info){
            console.log('window-change');
          }).once('shell', function(accept, reject){
            console.log('shell');
          });
        }).on('error', function(err) {
          console.log('error', err);
        }).on('continue', function() {
          console.log('continue');
        });

      }).on('error', function(err) {
        console.log('error', err);
      }).on('end', function() {
        console.log('Client disconnected');
      });
    }).listen(port, function() {
      console.log('Listening on port ' + port);
    });

The output from this code looks like this:

    Listening on port 2223
    Client connected!
    reject none
    reject publickey
    reject keyboard-interactive
    accept
    Client authenticated!
    session
    Client SFTP session
    accepted stream
     REALPATH
    Client disconnected

Any ideas?

**Comment by mscdex** [comment]
"sending open" could be a higher level "open" that evidently includes using `realpath()` first to get a resolved path of the file (e.g. in case of symlinks, `.` or `..`, etc.).

Did you try responding to the realpath request to see if it then tries to open the file?

**Comment by codebudo** [comment]
Thanks for the fast response! That does change the error but still doesn't fire the OPEN event. 

    $ sftp -oPort=2223 foo@localhost:/tmp/foo.txt
    foo@localhost's password:
    Connected to localhost.
    buffer_get_ret: trying to get more bytes 4 than in buffer 0
    buffer_get_int: buffer error

I'm not sure how the server is expected to respond from this event. Can you point me in the right direction?

**Comment by codebudo** [comment]
Ah, 'attrs' needs to be set:

            var name = [{
              filename: '/tmp/foo.txt',
              longname: '-rwxr--r-- 1 bar bar 718 Dec 8 2009 foo.txt',
              attrs: {}
            }];

... which lets the LSTAT event to be fired. I can't find any examples of how to respond to that event. Hints?

**Comment by mscdex** [comment]
Huh... ok that's a bug then, `attrs` should be completely optional for at least `STAT`/`LSTAT`. `LSTAT` is the exact same as `STAT` except that the former does not follow symlinks but the latter does.

**Comment by codebudo** [comment]
I figure out LSTAT and updated the previous comment. The OPEN event still isn't being fired though.

    Listening on port 2223
    Client connected!
    keyboard-interactive
    accept
    Client authenticated!
    Client SFTP session
    accepted stream
     ready
     REALPATH
    /Users/mikkel/icracked/sftp-proxy
     LSTAT
    stats: object { dev: 16777220,
      mode: 33188,
      nlink: 1,
      uid: 502,
      gid: 0,
      rdev: 0,
      blksize: 4096,
      ino: 13335162,
      size: 0,
      blocks: 0,
      atime: Mon Jan 11 2016 16:02:58 GMT-0800 (PST),
      mtime: Mon Jan 11 2016 16:02:58 GMT-0800 (PST),
      ctime: Mon Jan 11 2016 16:02:58 GMT-0800 (PST),
      birthtime: Mon Jan 11 2016 16:02:58 GMT-0800 (PST) }
    Client disconnected

**Comment by mscdex** [comment]
Here is a complete example that works with your `sftp` client usage:

```javascript
var constants = require('constants');
var fs = require('fs');

var ssh2 = require('ssh2');
var OPEN_MODE = ssh2.SFTP_OPEN_MODE,
    STATUS_CODE = ssh2.SFTP_STATUS_CODE;

new ssh2.Server({
  privateKey: fs.readFileSync('host.key')
}, function(client) {
  console.log('Client connected!');

  client.on('authentication', function(ctx) {
    if (ctx.method === 'password'
        && ctx.username === 'foo'
        && ctx.password === 'bar')
      ctx.accept();
    else
      ctx.reject();
  }).on('ready', function() {
    console.log('Client authenticated!');

    client.on('session', function(accept, reject) {
      var session = accept();
      session.on('sftp', function(accept, reject) {
        console.log('Client SFTP session');
        var openFiles = {};
        var handleCount = 0;
        // `sftpStream` is an `SFTPStream` instance in server mode
        // see: https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md
        var sftpStream = accept();
        sftpStream.on('OPEN', function(reqid, filename, flags, attrs) {
          console.log('OPEN', filename);
          // only allow opening /tmp/foo.txt for writing
          if (filename !== '/tmp/foo.txt' || !(flags & OPEN_MODE.READ))
            return sftpStream.status(reqid, STATUS_CODE.FAILURE);
          // create a fake handle to return to the client, this could easily
          // be a real file descriptor number for example if actually opening
          // the file on the disk
          var handle = new Buffer(4);
          openFiles[handleCount] = { read: false };
          handle.writeUInt32BE(handleCount++, 0, true);
          sftpStream.handle(reqid, handle);
          console.log('Opening file for read')
        }).on('READ', function(reqid, handle, offset, length) {
          if (handle.length !== 4 || !openFiles[handle.readUInt32BE(0, true)])
            return sftpStream.status(reqid, STATUS_CODE.FAILURE);
          // fake the read
          var state = openFiles[handle.readUInt32BE(0, true)];
          if (state.read)
            sftpStream.status(reqid, STATUS_CODE.EOF);
          else {
            state.read = true;
            sftpStream.data(reqid, 'bar');
            console.log('Read from file at offset %d, length %d', offset, length);
          }
        }).on('CLOSE', function(reqid, handle) {
          var fnum;
          if (handle.length !== 4 || !openFiles[(fnum = handle.readUInt32BE(0, true))])
            return sftpStream.status(reqid, STATUS_CODE.FAILURE);
          delete openFiles[fnum];
          sftpStream.status(reqid, STATUS_CODE.OK);
          console.log('Closing file');
        }).on('REALPATH', function(reqid, path) {
          var name = [{
            filename: '/tmp/foo.txt',
            longname: '-r--r--r-- 1 foo foo 3 Dec 8 2009 foo.txt',
            attrs: {}
          }];
          sftpStream.name(reqid, name);
        }).on('STAT', onSTAT)
          .on('LSTAT', onSTAT);
        function onSTAT(reqid, path) {
          if (path !== '/tmp/foo.txt')
            return sftpStream.status(reqid, STATUS_CODE.FAILURE);
          var mode = constants.S_IFREG; // Regular file
          mode |= constants.S_IRWXU; // read, write, execute for user
          mode |= constants.S_IRWXG; // read, write, execute for group
          mode |= constants.S_IRWXO; // read, write, execute for other
          sftpStream.attrs(reqid, {
            mode: mode,
            uid: 0,
            gid: 0,
            size: 3,
            atime: Date.now(),
            mtime: Date.now()
          });
        }
      });
    });
  }).on('end', function() {
    console.log('Client disconnected');
  });
}).listen(0, '127.0.0.1', function() {
  console.log('Listening on port ' + this.address().port);
});
```

**Comment by codebudo** [comment]
This was gloriously helpful. I have a working prototype now. Thanks so much!
