### ISSUE TITLE
cd ptah

### ISSUE THREAD

**Issue by lilijialiang** [mscdex/ssh2#384]
```js
conn.exec('cd ..')
conn.exec('ls', function(err, stream) {
        if (err) throw err;
        stream.on('data', function(data) {
            console.log('output: ' + data);
        })
    });
```
why this data is incorrect ? 

exec('pwd')  alway get the path =  '/home/user/'

**Comment by mscdex** [comment]
You can think of `conn.exec()` as starting a new interactive session (for example what you get by default when you log into a server with the OpenSSH or PuTTY clients), but with less overhead (no shell is invoked, like `child_process.spawn()`).

So every time you call `conn.exec()`, any non-permanent information such as the current working directory and environment will be new/defaults. If you want to keep using `conn.exec()` you will have to append commands so they get executed within the same session, for example: `'cd ..&& ls'`.

Another alternate solution is to actually use `conn.shell()` where you write the commands to the stream as if they were being typed at a terminal (e.g. `stream.write('cd ..\n'); stream.write('ls\n');`), but then you have to deal with the shell prompt and other things, which can make scraping/parsing command output  or checking command exit codes difficult.
