### ISSUE TITLE
Unable to respond to SFTP REALPATH request - get "do_realpath: buffer error: incomplete message"

### ISSUE THREAD

**Issue by uberbrady** [mscdex/ssh2#385]
Sorry to finally have to open an issue for this, but I've been combing through source code and examples and everything I can find to try and just get it so that I can respond to a REALPATH request.

I've got authentication working correctly, and the basic setup seems to be working.

```js
        // ... 
        sftpStream.on('REALPATH', function (reqid,filename) {
          console.warn("REALPATH Request for filename: '"+filename+" has REQ ID: "+reqid);
            sftpStream.name(reqid, {filename: "/fribblefargz", longname: "/fribblefargz"});
            sftpStream.end(); //I've tried with and without this, still doesn't work...
        });
        // ...
```

Then if I try to connect to this server:

```sh
sftp -v  -P 8022 brady@localhost
```

As soon as I input my correct password, the REALPATH debug info will show (from above), and then sftp will exit with this error (including debug output from sftp):

```sh
debug1: Authentication succeeded (password).
Authenticated to localhost ([127.0.0.1]:8022).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending subsystem: sftp
Connected to localhost.
do_realpath: buffer error: incomplete message
```

Am I missing something? Am I invoking the `.name()` method the wrong way?

I also would love to help update the documentation in this area to help make this clearer for first-time users.

Thank you for making a module that looks like it will single-handedly save my project!!!

**Comment by mscdex** [comment]
Add `attrs: {}` to your object passed to `.name()`. This is a bug as it's really supposed to be completely optional.

If you are looking for a more complete, simple sftp server example that just supports sending a file, look [here](https://github.com/mscdex/ssh2/issues/383#issuecomment-171892610).

**Comment by uberbrady** [comment]
BINGO! That worked! Thank you so much!

Would you be willing to accept a Pull Request with that example added to the 'examples' directory, and maybe a separate pull request for your https://github.com/mscdex/ssh2-streams with more details on the REALPATH parameters? I'm sure it'd help other people too. I'd love to find some way of giving back to this project, it's going to be invaluable for me!

**Comment by mscdex** [comment]
@uberbrady Sure.

**Comment by mscdex** [comment]
Closing this as the example addition to `ssh2-streams` has been merged now.
