### ISSUE TITLE
Timeout event not able to capture .

### ISSUE THREAD

**Issue by rajegit** [mscdex/ssh2#387]
Hi 

In the ssh2 connection I have written 3 events 
...
                    .stderr.on('data', function(data) {
                        conn.end();
                    })
                    .on('timeout', function() {
                        conn.end();
                    })
                    .on('error', function(err) {
                         conn.end();
                    })
..

And I know there is a SSH Timeout error . But the above events are not just captured. What I am doing wrong ? There is not documentation for event capturing . 

Error is 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Timed out while waiting for handshake
    at null._onTimeout (/etc/node_modules/ssh2/lib/client.js:564:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by mscdex** [comment]
The handshake timeout error is emitted on the main connection object. It means it took too long to connect to the server, negotiate session parameters, and authenticate. This usually means incorrect port or the server is *really* slow. For the latter case you can adjust the default `readyTimeout` of 20 seconds by setting `readyTimeout` in the object you pass to `connect()`.

**Comment by rajegit** [comment]
Thanks for the reply, I want to capture this error . Is there anyway it is passed to the module and its captured ? Setting readyTimeout will increase the time. If the server is down it (main conn obj) will still throw this error. So 20 sec or later will not resolve the issue. 
Please let me know if there is anyway to capture this error .

**Comment by mscdex** [comment]
As I said, the timeout erorr is emitted on the main connection object, so just add an `error` event handler on the connection object:

```javascript
conn.on('error', function(err) {
  console.log(err);
});
```

**Comment by mscdex** [comment]
Closing this for now. If you find that adding an `error` event handler as previously shown does not catch the timeout error, please let me know.

**Comment by mohanen** [comment]
how do i get the conn object to capture  the err, if i am using a node module that uses your ssh2
