### ISSUE TITLE
Higher-level SFTP Server Wrapper?

### ISSUE THREAD

**Issue by uberbrady** [mscdex/ssh2#392]
Hi there - loving this library and really coming up with some good stuff with it.

I decided to split up some of the functionality of my program into a high-level wrapper, and my own code. This wrapper makes it so that  can write less code to implement your own SFTP Server. It uses Node.js `readableStreams` and `writableStreams` for file reads and writes, and puts together a closure-style interface to be able to generate a directory listing. It also abstracts away having to make references to the `reqId` of each request.

It's not done yet at all, but I was wondering if you would be interested in making it available with the rest of your module? If not, I will probably make it available on my own. I don't really want to do that - not only because I'm very, very lazy, but also because I am a little uncomfortable with too many layers floating around, or making too many too many modules show up in `npm ls`. And when I get it to you, I imagine you would make it a hell of a lot better than I would ever be able to.

Anyways, here's a sample of what code that _uses_ the wrapper looks like:

```js
var fs = require('fs');

var SFTPServer = require("./wrapper");

var srv = new SFTPServer();

srv.listen(8022);

srv.on("authentication", function(ctx) {
  console.warn("authentication attempted");
  if (ctx.method === 'password' && ctx.username === "brady" && ctx.password === "test") {
    ctx.accept();
  } else {
    ctx.reject();
  }
});

srv.on("readdir", function(path, responder) {
  console.warn("Readdir request for path: " + path);
  var dirs = [];
  for(var j = 1; j < 10000; j++){ dirs.push(j); }
  var i = 0;
  responder.on("dir", function() {
    if (dirs[i]) {
      responder.file(dirs[i]);
      i++;
    } else {
     responder.end();
    }
  });
});

srv.on("readfile", function(path, req) {
  var something = fs.createReadStream("/tmp/grumple.txt");
  return req(something);
});

srv.on("writefile", function(path, req) {
  var something = fs.createWriteStream("/tmp/garbage");
  return req(something);
});
```

**Comment by mscdex** [comment]
IMHO higher level abstractions like this are better suited in a separate module. Also I'd rather not have to maintain another abstraction in this repo.

**Comment by uberbrady** [comment]
Not a problem! Thanks for looking it over.
