### ISSUE TITLE
SFTPWrapper usage

### ISSUE THREAD

**Issue by tedx** [mscdex/ssh2#395]
I've got some pre .4 sftp client code that I'd like to use with the latest version what's the easiest way to get my code to work with it SFTPWrapper? If so could you give me a quick example of what I'd need to change. Thanks

Ted

**Comment by mscdex** [comment]
Did you just try it? Is there a particular problem/error you're running into?

**Comment by tedx** [comment]
No I'm not sure how to use it and was looking for an example. My old code looks very much like:

var Connection = require('ssh2');

var conn = new Connection();
conn.on('ready', function() {
  console.log('Connection :: ready');
  conn.sftp(function(err, sftp) {
    if (err) throw err;
    sftp.readdir('foo', function(err, list) {
      if (err) throw err;
      console.dir(list);
      conn.end();
    });
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  password: 'nodejsrules'
});

How would you change this to use the SFTPWrapper?

**Comment by mscdex** [comment]
That code should work fine as-is. `SFTPWrapper` is an internal implementation detail and not something end users generally need to be concerned with.

**Comment by tedx** [comment]
Ok thanks.
