### ISSUE TITLE
KEY_EXCHANGE_FAILED

### ISSUE THREAD

**Issue by tedx** [mscdex/ssh2#396]
I'm trying to sftp to a Windows box running Cygwin ad follows:

var fs = require('fs');
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('error', function(err) {
  console.log('error ' + err);
    });
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.sftp(function(err, sftp) {
    if (err) throw err;
    sftp.readdir('.', function(err, list) {
      if (err) throw err;
      console.dir(list);
      conn.end();
    });
  });
    });
console.log('connect');
conn.connect({
  host: 'xxx.xxx.xxx.xxx',
  port: 22,
  username: 'test',
            debug: function(s) { console.log(s); },
  privateKey: require('fs').readFileSync('/home/test/.ssh/id_rsa')
});

Here's the debug output:
DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.21'
DEBUG: Client: Trying 192.168.25.231 on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_7.1'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:236,padLen:10,remainLen:232
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha256
DEBUG: No matching KEX algorithm
DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)

One thing is that I'd have expected my 'error' function to be called am I doing something wrong? What do I need to do to resolve the "No match" issue? Thanks.

Ted

**Comment by mscdex** [comment]
Upgrade your version of node. node 0.10.x or older do not support the underlying crypto functionality to be able to do group exchange.
