### ISSUE TITLE
Request feature - Disable colour codes

### ISSUE THREAD

**Issue by WHK102** [mscdex/ssh2#398]
When launch $ls -la the server says in raw format:

    total 128
    dr-xr-x--- 12 root root  4096 Feb 11 10:17 [0m[01;34m.[0m
    dr-xr-xr-x 23 root root  4096 Feb 11 09:53 [01;34m..[0m
    -rw-------  1 root root 27250 Feb 19 17:21 .bash_history
    -rw-r--r--  1 root root    18 May 20  2009 .bash_logout
    ....

Need a option "strip-style" to strip all tag styles in bash and process only the real string and not all buffer.

**Comment by WHK102** [comment]
I solved it processing all buffer: 
    all_buffer = all_buffer.replace(/.\[[0-9;]+?m/g, '');

**Comment by mscdex** [comment]
Disable or change your `pty` option.

**Comment by mscdex** [comment]
@WHK102 Did my suggestion help you any?

**Comment by mscdex** [comment]
Closing this for now. One additional solution is to either change `term` in the `pty` object or set `$TERM` at the shell prompt to something simpler that doesn't use colors and such, like `dumb` or `linux`.

If you find that neither of those solutions work, let me know.
