### ISSUE TITLE
SSH forwardOut Question

### ISSUE THREAD

**Issue by rawberg** [mscdex/ssh2#40]
Is it possible setup forwardOut so all TCP traffic is forwarded from the local port to the remote one or does everything have to be written to the channel in order for the forwarding to work?

I'm trying to use the library inside node-webkit (mix of node and client-side javascript). I'd like to setup ssh port forwarding and then forward web socket traffic through the tunnel.

**Comment by sidorares** [comment]
I was confused as well with 'local stream' vs local ip:port
Here is my understanding what forwardOut does:
- ask remote ssh server to establish tcp connection to rip:rport
- create local stream, pipe it to ssh 'tcp local' protocol

So what's the purpose of local ip / local port arguments?

**Comment by sidorares** [comment]
I think I found the answer here - https://github.com/mscdex/ssh2/issues/99#issuecomment-31871947
