### ISSUE TITLE
Error: shell request failed on channel 0

### ISSUE THREAD

**Issue by WHK102** [mscdex/ssh2#400]
Use the first server example from github but does not access:

    me@machine:~$ ssh foo@localhost -p 51249
    The authenticity of host '[localhost]:51249 ([127.0.0.1]:51249)' can't be established.
    RSA key fingerprint is xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx.
    Are you sure you want to continue connecting (yes/no)? yes
    Warning: Permanently added '[localhost]:51249' (RSA) to the list of known hosts.
    PTY allocation request failed on channel 0
    shell request failed on channel 0

Output of example:

    me@machine:~/$ node main.js
    Listening on port 51249
    Client connected!
    Client authenticated!
    Client disconnected

**Comment by mscdex** [comment]
The server example in the readme is for executing commands, not starting an interactive shell. For interactive shell sessions, you will need to instead add `shell` and `pty` event handlers:

```javascript
session.on('pty', function(accept, reject, info) {
  accept();
});
session.on('shell', function(accept, reject) {
  var stream = accept();
  // Now read from and write to `stream`
});
```

**Comment by WHK102** [comment]
Works fine, thanks :)

**Comment by freekmurze** [comment]
Hi,

thank you for your work on this. Could you give a full example where you show where the

```js
session.on('pty', function(accept, reject, info) {
  accept();
});
session.on('shell', function(accept, reject) {
  var stream = accept();
  // Now read from and write to `stream`
});
```

bit should be used?

**Comment by freekmurze** [comment]
Got it, sorry for the noise 😄

**Comment by iusmanzaman** [comment]
> Got it, sorry for the noise 😄

let me know where did you use it. I am also having trouble here.
