### ISSUE TITLE
interactive passphrase

### ISSUE THREAD

**Issue by sonnyp** [mscdex/ssh2#402]
Is there an eqauivalent to tryKeyboard/keyboard-interactive for passphrase?

**Comment by mscdex** [comment]
Assuming you mean passphrase for a private key, then no. The passphrase isn't stored or anything, it is used immediately to decrypt the private key. If you're still concerned about that, there's always ssh key agents.

**Comment by mscdex** [comment]
It may be possible that a third-party module could implement (or already has) support for interactive entering of private key passphrases, but that is outside the scope of this module.
