### ISSUE TITLE
Best way to detect Channel write progress

### ISSUE THREAD

**Issue by johnnyman727** [mscdex/ssh2#404]
I'm using the `ssh2` library to write data to a remote file. Sometimes the bundles that I'm deploying can be on the order of 10s of MB so it can take a few seconds. I'd like to implement a progress bar to improve the user experience of my application.

My application writes data into the stream via a `channel.end(bundle)` call so if I attempt to hook a through stream between the channel and the destination, I just see the entire bundle written at once but obviously, it's back-pressured so not all the data is actually written to the socket at once. 

Do you have any suggestions for how I might be able to inspect the true progress of writing data to the socket? 

Much appreciated!

**Comment by mscdex** [comment]
Streams in general don't have any way to hook into that. What about either streaming the bundle from the source or explicitly chunking it afterwards? For the latter I know there are modules on npm that will do this for you (creating a stream from a Buffer) such as [`stream-buffers`](https://github.com/samcday/node-stream-buffer).

**Comment by johnnyman727** [comment]
@mscdex thanks for the suggestion. It seems like `stream-buffers` aren't ideal because if you specify a stream rate that's too slow, you're artificially throttling the transfer and if you pick a stream rate that's too fast, you're back to the same issue where you can't actual display the true transfer rate because it's being back pressured in the destination stream. Does that sound accurate or am I misunderstanding how to use `stream-buffers`?

**Comment by mscdex** [comment]
I'm not entirely sure as I haven't used the module myself. The better solution is to stream the data from the source.
