### ISSUE TITLE
No err, when subsystem can not opened

### ISSUE THREAD

**Issue by wisotzky** [mscdex/ssh2#406]
I am just testing with a network element, which support SSH interactive shell, SFTP and SCP on port 22 - while subsystem netconf is supported on 830. If I am trying to open subsystem netconf on port 22, callback is never called - so I don't get any error on application level.

Cross testing with various python libraries shows, that the nodal behavior is as expected - but ssh2 js framework seems to be incomplete.

**Comment by mscdex** [comment]
Can you set `debug: console.log` in your connection config and post the output when you try to open the subsystem?

**Comment by mscdex** [comment]
FWIW when I try to open a `netconf` subsystem channel, I get an error passed to my callback as expected: `Unable to start subsystem: netconf`.

**Comment by wisotzky** [comment]
I am still struggling to understand, what library version of ssh2 I am using. It is my first steps in programming for the Atom editor. To make my life easy, I’ve just copied the ssh2 library including all node_modules from an ATOM package called “remote-edit”. Project homepage is: https://github.com/sveale/remote-edit

Somehow strange, the version of the contained ssh2-lib is calling itself “0.4.14” while the ssh2-main version on GITHUB is currently “0.4.13”. Checking the lib dependencies there are some major differences between both versions. I have now tried to download 0.4.13 from GITHUB to embed this into my package – but it is not calling the conn.on(‘ready’) callback as needed…


/wiso

**Comment by wisotzky** [comment]
Output received:
  DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_SUCCESS
  DEBUG: Outgoing: Writing CHANNEL_OPEN (0, session)
  DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
  DEBUG: Parser: IN_PACKET
  DEBUG: Parser: Decrypting
  DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
  DEBUG: Parser: IN_PACKETDATA
  DEBUG: Parser: Decrypting
  DEBUG: Parser: HMAC size:16
  DEBUG: Parser: IN_PACKETDATAVERIFY
  DEBUG: Parser: Verifying MAC 
  DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
  DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN_CONFIRMATION
  DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, subsystem: netconf)
  DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
  DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)

Using this version Key Exchange is okay:
  DEBUG: (local) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
  DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
  DEBUG: KEX algorithm: diffie-hellman-group-exchange-sha1
  DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
  DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
 DEBUG: Host key format: ssh-rsa

With the latest version from GITHUB KEX is failing:
  DEBUG: Local ident: 'SSH-2.0-ssh2js0.0.21'
  DEBUG: Client: Trying 192.168.33.5 on port 22 ...
  DEBUG: Client: Connected
  DEBUG: Parser: IN_INIT
  DEBUG: Parser: IN_GREETING
  DEBUG: Parser: IN_HEADER
  DEBUG: Remote ident: 'SSH-2.0-OpenSSH_3.5p1'
  DEBUG: Outgoing: Writing KEXINIT
  DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
  DEBUG: Parser: IN_PACKET
  DEBUG: Parser: pktLen:596,padLen:9,remainLen:592
  DEBUG: Parser: IN_PACKETDATA
  DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
  DEBUG: Comparing KEXINITs ...
  DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
  DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
  DEBUG: No matching KEX algorithm
  DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)

**Comment by mscdex** [comment]
You are better off using `ssh2` v0.4.14 from npm for the time being.

The master branch actually represents the upcoming v0.5, which has some "breakage" as you can see due to the change in default algorithms offered to the server (this was done to align `ssh2` more with the defaults used in recent versions of OpenSSH), although there is a way in v0.5 to use custom algorithm lists to get back to the old defaults.

**Comment by wisotzky** [comment]
As indicated before, 0.4.14 does not work with subsystem for me (debug trace as provided before)…

Started to play around with 0.4.13 now by adding algorithm, such as:
    myAlgorithms =
      kex: ["diffie-hellman-group-exchange-sha256","diffie-hellman-group14-sha1","diffie-hellman-group-exchange-sha1"],
      kexBuf: undefined,
      cipher: undefined,
      cipherBuf: undefined,
      serverHostKey: undefined,
      serverHostKeyBuf: undefined,
      hmac: undefined,
      hmacBuf: undefined,
      compress: undefined,
      compressBuf: undefined

Still getting an error about signature verification...
  DEBUG: Parser: IN_INIT
  DEBUG: Parser: IN_GREETING
  DEBUG: Parser: IN_HEADER
  DEBUG: Remote ident: 'SSH-2.0-OpenSSH_3.5p1'
  DEBUG: Outgoing: Writing KEXINIT
  DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
  DEBUG: Parser: IN_PACKET
  DEBUG: Parser: pktLen:596,padLen:9,remainLen:592
  DEBUG: Parser: IN_PACKETDATA
  DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
  DEBUG: Comparing KEXINITs ...
  DEBUG: (local) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
  DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
  DEBUG: KEX algorithm: diffie-hellman-group-exchange-sha1
  DEBUG: (local) Host key formats: ssh-rsa
  DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
  DEBUG: Host key format: ssh-rsa
  DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
  DEBUG: (remote) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se
  DEBUG: Client->Server Cipher: aes128-ctr
  DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
  DEBUG: (remote) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se
  DEBUG: Server->Client Cipher: aes128-ctr
  DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
  DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
  DEBUG: Client->Server HMAC algorithm: hmac-sha1
  DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
  DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
  DEBUG: Server->Client HMAC algorithm: hmac-sha1
  DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
  DEBUG: (remote) Client->Server compression algorithms: none
  DEBUG: Client->Server compression algorithm: none
  DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
  DEBUG: (remote) Server->Client compression algorithms: none
  DEBUG: Server->Client compression algorithm: none
  DEBUG: Outgoing: Writing KEXDH_GEX_REQUEST
  DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
  DEBUG: Parser: IN_PACKET
  DEBUG: Parser: pktLen:148,padLen:8,remainLen:144
  DEBUG: Parser: IN_PACKETDATA
  DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
  DEBUG: Outgoing: Writing KEXDH_GEX_INIT
  DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
  DEBUG: Parser: IN_PACKET
  DEBUG: Parser: pktLen:444,padLen:9,remainLen:440
  DEBUG: Parser: IN_PACKETDATA
  DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_REPLY
  DEBUG: Checking host key format
  DEBUG: Checking signature format
  DEBUG: Verifying host fingerprint
  DEBUG: Host accepted by default (no verification)
  DEBUG: Verifying signature
  DEBUG: Signature could not be verified
  DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)

What's the trick behind this?

/wiso

**Comment by mscdex** [comment]
The subsystem callback issue should be fixed now in c1ec523ce00649fa6a5ae069529b94295babc869 (master)/0567cc8113f93ce9ffbcfef97de6244f04a3beaf (v0.4). Can you try the v0.4 branch and let me know if it works for you as well?

**Comment by wisotzky** [comment]
I’ve just verified this correction (v0.4).
Error callback is now working as expected.

Thx for the fast response!

/wiso

**Comment by mscdex** [comment]
Thanks for the feedback. This fix is now available on npm in v0.4.15.
