### ISSUE TITLE
repack and forwad

### ISSUE THREAD

**Issue by htle2101** [mscdex/ssh2#408]
I have A、B、C、D computers.  now A is local, the other are remote. I want to send command to B  by ssh from A. if the command is 'ls', B will repack the command and forward to C, and if the command is 'pwd', B will forward the command to D and also by ssh. Is there any way to do it excuse me?

**Comment by mscdex** [comment]
If I understand correctly, I think you're describing connection hopping? There is an example of this in the readme.

**Comment by htle2101** [comment]
Thanks, but i want to make hop at server,  the example may hop in client.

**Comment by mscdex** [comment]
I don't follow. The hop in the example goes from client -> server -> server. Do you mean something else by hopping at the server?

**Comment by htle2101** [comment]
Sorry, my description is not clear. Now, there are many clients will connect the server, and the client is used openssh,and the command is fixed. So I cannot realize as the example. My target seems load balance in ssh.

**Comment by mscdex** [comment]
Ok, so you want to create an ssh2.Server that proxies commands from connected clients to another server (e.g. an OpenSSH server)?

**Comment by htle2101** [comment]
Yes, is any way to do it?

**Comment by mscdex** [comment]
Sure, it's basically just combining the first server example with the first client example. Just `pipe()` the exec streams from the server to the client and back. Then when the client's exec exits, pass the exit code and/or signal to the server exec stream and close the server exec stream when the client's exec closes.

It would roughly look something like (untested):

```javascript
session.on('exec', function(accept, reject, info) {
  //console.log('Client wants to execute: ' + inspect(info.command));
  var stream = accept();
  var proxyCfg = {
    port: 22,
    username: '...',
    // TODO: determine how to authenticate
  };
  if (info.command === 'ls')
    proxyCfg.host = 'serverC';
  else if (info.command === 'pwd')
    proxyCfg.host = 'serverD';
  var proxyClient = new ssh2.Client();
  proxyClient.on('ready', function() {
    this.exec(info.command, function(err, upstream) {
      if (err) throw err;

      upstream.on('exit', function(code, signal) {
        stream.exit(signal || code);
      }).on('close', function() {
        stream.end();
      });

      upstream.pipe(stream).pipe(upstream);

      // Only pipe stderr in one direction
      upstream.stderr.pipe(stream.stderr);
    });
  });
  // TODO: handle proxyClient errors (better)
  proxyClient.connect(proxyCfg);
});
```

**Comment by htle2101** [comment]
very good！I get，thanks very much！
