### ISSUE TITLE
few files work, hundreds of files don't

### ISSUE THREAD

**Issue by amthenia** [mscdex/ssh2#409]
My code works for a few files, but doesn't work if I process hundreds :(

I get this:

>     Error: Failure
>     at SFTPStream._transform (/Applications/nodejs-5.9.0-0/Miranda/node_modules/ssh2-streams/lib/sftp.js:384:27)
>     at SFTPStream.Transform._read (_stream_transform.js:167:10)
>     at SFTPStream._read (/Applications/nodejs-5.9.0-0/Miranda/node_modules/ssh2-streams/lib/sftp.js:170:15)
>     at SFTPStream.Transform._write (_stream_transform.js:155:12)
>     at doWrite (_stream_writable.js:301:12)
>     at writeOrBuffer (_stream_writable.js:287:5)
>     at SFTPStream.Writable.write (_stream_writable.js:215:11)
>     at Channel.ondata (_stream_readable.js:536:20)
>     at emitOne (events.js:90:13)
>     at Channel.emit (events.js:182:7)

```
conn.on('ready', function ()
    {
        console.log('auth success');
        conn.sftp(function (err, sftp)
        {
            if (err) throw err;
            sftp.readdir(le_dir, function (err, le_ftp_dir_file_list)
            {
                if (err) throw err;
                async.each(le_ftp_dir_file_list, function (currentfile, callback)
                {
                    var filename = currentfile.filename;
                    console.log('sftp success get file: ' + filename);
                    var sourceFile = sftp.createReadStream(le_dir + filename);
                    s3bucket.createBucket(function ()
                    {
                        var params = {
                            Bucket: le_bucket,
                            Key: le_folder + '/' + filename,
                            Body: sourceFile
                        };
 s3bucket.upload(params, function (err, data)
                        {
                            if (err)
                            {
                                console.log("Error uploading data: ", err);
                                callback();
                            }
                            else
                            {
                                console.log('upload success: ' + filename);
                                //sftp.unlink(le_dir + filename);
                                console.log('delete success: ' + filename);
                                callback();
                            }
                        });
                        
                    });
                }, function (err)
                {
				    // if any of the file processing produced an error, err would equal that error
				    if (err) {
				      console.log('A file failed to process');
				    } else {
				      console.log('All files have been processed successfully');
				      conn.end();
				    }
                });
            });
        });
    }).connect(
    {
```

**Comment by amthenia** [comment]
help :)

**Comment by amthenia** [comment]
"ssh2": "^0.5.0"

**Comment by mscdex** [comment]
Do you encounter the same problem with v0.4.15?

**Comment by amthenia** [comment]
I will try

**Comment by amthenia** [comment]
There are 14000 small files. Just found out myself.

**Comment by amthenia** [comment]
same error

**Comment by amthenia** [comment]
could have to do with async?

**Comment by mscdex** [comment]
@amthenia It could very well be since `async.each()` executes the code for each array element *in parallel*. I think the server would have some sort of limit imposed for outstanding requests? You might try using `eachLimit()` instead to limit the concurrency and see what value works best for the servers you're connecting to. Another variant of that solution would be to open multiple ssh connections to the same host and split the transfers up that way (again with some kind of upper bound on number of connections).

**Comment by amthenia** [comment]
You solved it. How do you do it? Thank you so much!
