### ISSUE TITLE
Signature could not be verified

### ISSUE THREAD

**Issue by zhulduz** [mscdex/ssh2#410]
Hi everyone,

After updating ssh2 to version 0.5.0 I haven't an ability to connect to OS X.
I have tried to connect by password (keyboard-interactive) and by ssh-key(RSA) to my server, but I get always the same error "Signature could not be verified". I have attached logs:
https://gist.github.com/zhulduz/ddf16c01993067fd046c

When I used version 0.4.15, it works perfectly.

Could you please clarify, what I do wrong?
Thanks in advance.

**Comment by mscdex** [comment]
Does it happen every time or only every so often?

**Comment by mscdex** [comment]
I'm able to duplicate it now, working on a fix ...

**Comment by zhulduz** [comment]
Thanks a lot)

**Comment by mscdex** [comment]
Fixed by mscdex/ssh2-streams@b3090d4217074db0fa2513a23d386a1c9a530d79.

**Comment by mscdex** [comment]
Reinstall `ssh2` to pick up the new `ssh2-streams` version.
