### ISSUE TITLE
Expected 0x2: got 0xea

### ISSUE THREAD

**Issue by zhulduz** [mscdex/ssh2#411]
I get also another error when I try to connect to Ubuntu 15.04 by private key with passphrase:
https://gist.github.com/zhulduz/661d2d0fe24c5b444518

I used the same key in a previous version of ssh2 (0.4.15), it worked perfectly.

I have seen that utils.js has been changed or maybe I do something wrong?

Thanks in advance.

**Comment by mscdex** [comment]
Fixed in mscdex/ssh2-streams@6b9a6407c57695838f0f93a3467097576d745d03.

**Comment by mscdex** [comment]
Reinstall `ssh2` to pick up the new `ssh2-streams` version.
