### ISSUE TITLE
rsync implementation

### ISSUE THREAD

**Issue by 131** [mscdex/ssh2#415]
Is there an implementation of a rsync (client ? server ?) based on ssh2 (in pure nodejs that is) known to anyone ?
Any recommendation if i were to start working on this ?

**Comment by mscdex** [comment]
I don't know offhand, you'd have to search npm. rsync is a totally separate thing from ssh though and would be out of the scope of this project.

**Comment by 131** [comment]
Actually someone is already on it https://www.npmjs.com/package/sftp2sync (and use ssh2 for SSH transport), i'll start from here
