### ISSUE TITLE
best way to test for directory existence

### ISSUE THREAD

**Issue by tedx** [mscdex/ssh2#416]
Should I use 'exists' or 'stat'? What are the parameters to the 'exists' callback?

Ted

**Comment by mscdex** [comment]
`sftp.exists()` is just a wrapper around `sftp.stat()`. `sftp.exists()` takes a string path, just like `fs.exists()`, but you may as well just use `sftp.stat()` directly. If you're trying to recursively create a directory structure, you might consider just calling `ssh.exec('mkdir -p foo/bar/baz', ...)`.
