### ISSUE TITLE
mkdir mode

### ISSUE THREAD

**Issue by tedx** [mscdex/ssh2#419]
I can't get mkdir to create a directory with the mode I need. The directory gets made 0755 when my code specified 0775 am I calling mkdir wrong? The parent directory is 0775 and the user is in the group.

sftpstream.mkdir(dirname, {mode: 0775}, function(err) {

**Comment by mscdex** [comment]
Is it possible the server is applying a umask? Did you try explicitly using `sftpstream.chmod()` on the directory afterwards?

**Comment by tedx** [comment]
I'll try chmod

**Comment by tedx** [comment]
Ok that worked.
