### ISSUE TITLE
Get no output from shell after one Minute

### ISSUE THREAD

**Issue by lkathke** [mscdex/ssh2#420]
Hello guys,
I am runnning ssh2 on windows and open a shell to my rasperry pi (raspian).
In my code I'm executiving airodump-ng (a wireless sniffer) and after one minute,
I'm getting no more data.

After that, I've set the  keepaliveInterval to 1000 and keepaliveCountMax to 1000,
on my Raspberry Pi I've set also the clientaliveinterval to 60.

```
var data2 = "";
var shell = conn.shell(function(err, stream) {
    if (err) throw err;
    stream.setWindow(150, 150, 800, 600);
    stream.on('end', function() {
      console.log("end reached");});
      
    stream.on('close', function() {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function(data) {
      if(String(data).indexOf( "[1;1H") >= 0) {
        parseNetworkdataFromAirodump(String(data2));
        // console.log(data2);
        data2 = "";
        data2 = String(data).substr(String(data).indexOf("[1;1H") +6 );
      } else {
        data2 += String(data);
      }     
    }).stderr.on('data', function(data) {
      printdata('STDERR: ' + data);
    });
    
    conn.on('end', function() {
      console.log('Client disconnected');
    });
     
    stream.end('sudo airodump-ng mon0 -c 13\n');
   
    
  });
  
}).connect({
  host: '10.0.100.223',
  port: 22,
  username: 'pi',
  password: "raspberry",
  //debug: console.log,
  keepaliveInterval : 1000,
  keepaliveCountMax : 1000
  //privateKey: require('fs').readFileSync('/here/is/my/key')
});
```

The stream isn't disconnected, when I'm removing the network cable, the close event raises.

When I'm using Putty, nothing like that happend.
Do you have any idea?

**Comment by mscdex** [comment]
Did you try adding `console.log(data.toString())` right inside your `data` event handler, just in case your `if ()` isn't being hit anymore? Also, what if you change `stream.end()` with just `stream.write()`?

If neither of those suggestions help, can you set `debug: console.log` in your connection config and post the output leading up to when the data appears to stop?

**Comment by lkathke** [comment]
Thank you, you are my hero! - After changing stream.end() to stream.write() it finally works :+1: 
:) Thank you
