### ISSUE TITLE
cannot read client stdin stream when running exec

### ISSUE THREAD

**Issue by mmis1000** [mscdex/ssh2#424]
I am currenty trying to make a ssh proxy into a docker container.
But the channel instance i got from exec event seems does not send data correctly, make any exec attempt with stdin fail
The code part i used to listen to stdin
```

	        var commandProcess = container.spawnInDocker(commandToRun);
	        
	        var stdinLogFilePath = path.resolve(logFolder, connectionId + '-exec-stdin-' + Date.now() + '.log')
	        var logFilePath = path.resolve(logFolder, connectionId + '-exec-' + Date.now() + '.log')
	        
	        
	        
	        console.log('log file at ' + stdinLogFilePath + '\r\nand ' + logFilePath)
	        // stream.stdin.pipe(fs.createWriteStream(stdinLogFilePath));
	        // stream.stdin.pipe(process.stdout)
	        stream.pipe(fs.createWriteStream(stdinLogFilePath + '.2'));
	        // stream.pipe(process.stdout)
	        
	        fs.writeFile(logFilePath, info.command);
	        
	        stream.pipe(commandProcess.stdin)
	        commandProcess.stderr.pipe(stream.stderr);
	        commandProcess.stdout.pipe(stream, {end: false});
	        
	        commandProcess.stdout.pipe(process.stdout);
	        commandProcess.stderr.pipe(process.stdout);
	        commandProcess.stdout.on('end', function(e) {
	      		console.log('command finished')
		        stream.exit(0);
		        stream.end();
	        })
	        commandProcess.on('error', function (e) {
	      		console.log('command failed ' + inspect(e))
	        	try {
	        		stream.exit(0);
	        		stream.end();
	        	} catch (e) {
	        		console.log('bad exit ' + inspect(e))
	        	}
	        })
```
https://github.com/mmis1000/node_docker_honeypot/blob/master/index.js#L203-L263

Is this some kind of intended behavior, or I use it in a wrong way?
`stream.pipe(fs.createWriteStream(stdinLogFilePath + '.2'));`
this line seems didn't write any data at all, the file didn't exist

**Comment by mscdex** [comment]
You have it backwards. On the server, the `stdin` is a Readable stream and the `stdout` and `stderr` are Writable streams since the server is the one "executing" the command (if you were call `.exec()` from the ssh2 client, the streams' roles would be flipped). So try this instead:

```js
stream.stdin.pipe(commandProcess.stdin);
commandProcess.stderr.pipe(stream.stderr);
commandProcess.stdout.pipe(stream.stdout, {end: false});
commandProcess.on('error', function (e) {
  console.log('command failed ' + inspect(e))
});
commandProcess.on('close', function(code, signal) {
  stream.exit(code || signal);
  stream.close();
});
```

**Comment by mscdex** [comment]
How are you testing this on the client side?

Also, I think it would be better to move the calls to `stream.exit()` and `stream.end()` to inside the child process's `close` event handler:

```js
commandProcess.on('close', function(code, signal) {
  stream.exit(code || signal);
  stream.end();
});
```

**Comment by mmis1000** [comment]
I test this with a real sshd(on a ubuntu) and it works perfectly
also test this without stdin, and it also works perfect
but if I use the ssh2 with exec and stdin. it sudden didn't work at all.

**Comment by mmis1000** [comment]
Hello, any progress yet?
Or if the server and client log is required to adress this issue?

**Comment by mscdex** [comment]
Sorry, I didn't see your edit with the specific commands to reproduce this. I will try to look at it this weekend.

**Comment by mscdex** [comment]
I just tried your example command lines and I cannot reproduce the problem. It works the same for me with both OpenSSH server and `ssh2.Server` (both output "i got" and exit).

What does `nodejs -v` output? I tried with both node v6.1.0 and v5.10.1 on the server side FWIW.

**Comment by mmis1000** [comment]
I use 4.3 lts, since most of my program does not support newet build, I may update nodejs and try again later.

**Comment by mmis1000** [comment]
By the way, how do you setup the ssh2 server with shell? 
If there is some different that can cause this problem?

**Comment by mscdex** [comment]
`shell()` is for interactive sessions instead of executing one-off commands like `exec()` if that's what you're asking.

I just tried with v4.4.4 and it works fine there too.

FWIW here is the `ssh2.Server` code I am using to test with:

```js
var fs = require('fs');
var inspect = require('util').inspect;
var spawn = require('child_process').spawn;

var ssh2 = require('ssh2');

new ssh2.Server({
  hostKeys: [
    fs.readFileSync('my-host-key'),
  ]
}, function(client) {
  console.log('Client connected!');
  var procs = [];

  client.on('authentication', function(ctx) {
    ctx.accept();
  }).on('ready', function() {
    console.log('Client authenticated!');

    client.on('session', function(accept, reject) {
      var session = accept();
      session.on('exec', function(accept, reject, info) {
        console.log('Client wants to execute: ' + inspect(info.command));
        var stream = accept();
        var proc;
        // node versions pre-v5 do not have the `shell` option, so do it manually
        if (/^v[0-4]\./.test(process.version))
          proc = spawn('/bin/sh', [ '-c', info.command ]);
        else
          proc = spawn(info.command, { shell: true });

        procs.push(proc);

        stream.stdin.pipe(proc.stdin);
        proc.stdout.pipe(stream.stdout);
        proc.stderr.pipe(stream.stderr);

        proc.on('exit', function(code, signal) {
          stream.exit(code, signal);
        }).on('close', function() {
          stream.writable && stream.end();
          var idx = procs.indexOf(proc);
          if (idx !== -1)
            procs.splice(idx, 1);
        });
      });
    });
  }).on('end', function() {
    console.log('Client disconnected');
    // cleanup any spawned processes that may still be open
    for (var i = 0; i < procs.length; ++i)
      procs[i].kill('SIGKILL');
    procs.length = 0;
  });
}).listen(43177, '127.0.0.1', function() {
  console.log('Listening on port ' + this.address().port);
});
```

**Comment by mmis1000** [comment]
I think I found the cause.
It's because I call `accept()` in a async manner.
The ssh2 didn't cache the input between the connection start and i start to read the stream
and neither throw any error at all.
cause the stream wait forever. (because the input is gone, and the process will never got it.

**Comment by mscdex** [comment]
It shouldn't matter when `accept()` is called. Even if you `accept()` early, the stream mechanism should do its thing (buffering until you start reading so as not to lose data and preventing the client from sending more data until the current buffer is read).

**Comment by mmis1000** [comment]
```
    client.on('session', function(accept, reject) {
      var session = accept();
      session.on('exec', function(accept, reject, info) {
        console.log('Client wants to execute: ' + inspect(info.command));
        console.log('delay 0.1 seconds')
        
        setTimeout(function () {
        
        var stream = accept();
```

this result in a undefined behavior
while this work as intend

```
    client.on('session', function(accept, reject) {
      var session = accept();
      session.on('exec', function(accept, reject, info) {
        console.log('Client wants to execute: ' + inspect(info.command));
        console.log('delay 0.1 seconds')
        
        var stream = accept();
        
        setTimeout(function () {
```

I think there should be a more clear error message to tell that we can't call it in this way

**Comment by mscdex** [comment]
@mmis1000 I still cannot reproduce the problem you're describing, even after including a (long) timeout like you mentioned. Do you have a simple, reproducible example that you can provide?

**Comment by mmis1000** [comment]
The above example is actually the one I used to reproduce the problem, i think maybe there is some different between your and my setting that cause that issue.

**Comment by mscdex** [comment]
Unfortunately there's not much I can do until I can reproduce the problem. If you are able to narrow down a potential cause, let me know.
