### ISSUE TITLE
ssh2 for long run command

### ISSUE THREAD

**Issue by poioit** [mscdex/ssh2#425]
I am using ssh2 for repo sync command. It is time consuming command. And I set the keepaliveInterval=100. But it always end up with no response. Do you have any idea how can we use ssh2 for long time-consuming command.

**Comment by mscdex** [comment]
Can you show the code you're using?

**Comment by mscdex** [comment]
Also, can you set this in your connection config object?:

```js
debug: function(s) {
  console.log('[%s] %s', new Date(), s);
}
```

and post the resulting output?

**Comment by poioit** [comment]
STDOUT:  * [new tag]        

Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKET
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Decrypting
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: pktLen:108,padLen:18,remainLen:96
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATA
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Decrypting
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: HMAC size:32
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAVERIFY
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Verifying MAC
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
STDOUT:  * [new tag]        
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKET
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Decrypting
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATA
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: HMAC size:32
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAVERIFY
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Verifying MAC
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_FAILURE
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKET
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Decrypting
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATA
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: HMAC size:32
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAVERIFY
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Verifying MAC
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_FAILURE
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKET
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Decrypting
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATA
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: HMAC size:32
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAVERIFY
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: Verifying MAC
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
Tue May 10 2016 14:49:21 GMT+0800 (台北標準時間)DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_FAILURE

**Comment by poioit** [comment]
I use the code:

        
        conn.shell( function(err, stream) {
            if (err) 
                throw err;
            stream.on('close', function() {
                console.log('Stream :: close');
                conn.end();
            }).on('data', function(data) {
                console.log('STDOUT: ' + data);
            }).on('end', function() {
                console.log('end');
            }).stderr.on('data', function(data) {
                console.log('STDERR: ' + data);
            });
            stream.end(cd ' + path + '\nrepo sync -f --no-clone-bundle\nexit\n');
           
        });
        }).connect({
        host: 'test_server',
        port: 22,
        username: "xxxxxx",
        password: terminal_password,
        debug: function(str){var date = new Date();console.log(date + str);}, 
        keepaliveInterval: 100
        });

**Comment by poioit** [comment]
It seems to get the IN_PACKETDATAAFTER, packet: REQUEST_FAILURE
and there is no more in packet?

**Comment by mscdex** [comment]
I don't see anything wrong. 100ms for keepalive might be a bit too frequent, but the server seems to be responding to them quickly. The server literally is not sending any more data, I'm not sure there's anything that can be done client side. You could try using `exec()` instead of `shell()`:

```js
conn.exec('cd ' + path + ' && repo sync -f --no-clone-bundle', function(err, stream) {
  if (err) 
      throw err;
  stream.on('close', function(exit, signal) {
    console.log('stream closed. exit=%j signal=%j', exit, signal);
    conn.end();
  }).on('data', function(data) {
    console.log('STDOUT: ' + data);
  }).on('end', function() {
    console.log('stdout end');
  }).stderr.on('data', function(data) {
    console.log('STDERR: ' + data);
  });
});
```

**Comment by poioit** [comment]
Dear mscdex,
I found out a point. the ssh command I really used is 
**stream.end('ssh username@test_server\ncd ' + path + '\nrepo sync -f --no-clone-bundle\nexit\n');**
I have login to another server and trigger the repo sync command.
is the the "keepalive" issue on this test_server?

**Comment by mscdex** [comment]
If that's the case, you *can* do connection hopping with `ssh2`, there is an example in the readme.

Otherwise if you want to stick to using the OpenSSH client, you should be able to instead use this `exec()` command line:

```js
'ssh username@test_server "cd ' + path + ' && repo sync -f --no-clone-bundle"'
```

**Comment by poioit** [comment]
Dear mscdex,
I use the code above, it works well. Thanks for your great help
