### ISSUE TITLE
forwardIn to local SOCKSv5 Proxy (ala Reverse Dynamic Port Forwarding)

### ISSUE THREAD

**Issue by t3chguy** [mscdex/ssh2#432]
I have a sort of strange requirement as described by the title, it should be achievable by using a combination of forwardIn and your SOCKSv5 Server, I just can't figure out how to have forwardIn proxy to a local port, the example just shows a static set of HTTP headers being sent back through.

I failed getting there myself with the following:
```javascript
var Client = require('ssh2').Client;
var Net = require('net');

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.forwardIn('127.0.0.1', 8000, function(err) {
    if (err) throw err;
    console.log('Listening for connections on server on port 8000!');
  });
}).on('tcp connection', function(info, accept, reject) {
  console.log('TCP :: INCOMING CONNECTION:');
  console.dir(info);
  var Sock = accept().on('close', function() {
    console.log('TCP :: CLOSED');
  }).on('data', function(data) {
    console.log('TCP :: DATA: ' + data);
  });/*.end([
    'HTTP/1.1 404 Not Found',
    'Date: Thu, 15 Nov 2012 02:07:58 GMT',
    'Server: ForwardedConnection',
    'Content-Length: 0',
    'Connection: close',
    '',
    ''
  ].join('\r\n'));*/
  var SocksConn = Net.createConnection(1080, 'localhost');
  Sock.pipe(SocksConn).pipe(Sock);

}).connect({
        host: 'xxx.xxx.xxx',
        password: 'xxxxxxxxx',
        username: 'root',
        port: 22
});


var Socks = require('socksv5');
var SocksServer = Socks.createServer((info, accept, deny) => {

}).listen(1080, 'localhost', () => {
        console.log('SOCKS Server listening on port 1080');
}).useAuth(Socks.auth.None());
```

Currently this fails with the following outputs:
SOCKS Side:
```
t3chguy@Admin-Laptop:~/Desktop/tmp$ node proxy.js
SOCKS Server listening on port 1080
Client :: ready
Listening for connections on server on port 8000!
TCP :: INCOMING CONNECTION:
{ destIP: '127.0.0.1',
  destPort: 8000,
  srcIP: '127.0.0.1',
  srcPort: 39237 }
TCP :: DATA: 
TCP :: DATA: �qX�P
^C
```

Server Side:
```
root@phoenix:~# curl --socks 127.0.0.1:8000 ifconfig.co -vvv
* Rebuilt URL to: ifconfig.co/
*   Trying 127.0.0.1...
* 188
* 113
* 88
* 193
```

188.113.88.193 is the IP of ifconfig.co - no idea why its being returned like that. The curl command doesn't seem to get past that point. I tested the example with the static HTTP return and that worked fine.

Any tips or pointers are very much appreciated.
Great module - Many thanks!

**Comment by t3chguy** [comment]
Oh my, looks like my only error was in the configuration of SOCKSv5 itself, forgetting to add any condition for `accept()`
I believe this to be solved but the example above may be useful to others

**Comment by atteia** [comment]
it works fine with HTTP but with HTTPS not working 

gives and error for curl command 
curl: (7) Failed to receive SOCKS5 connect request ack.
but no error from the code !
