### ISSUE TITLE
SSH Tunnel Port Forwarding

### ISSUE THREAD

**Issue by shivasrk8** [mscdex/ssh2#435]
I have a client SSH sever written in Java using JSCH lib which is forwarding Port from client to ssh server like ThisJSCH client ,

```
package in.cts.localtesting;

import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import com.jcraft.jsch.JSch;
import com.jcraft.jsch.ProxyHTTP;
import com.jcraft.jsch.Session;
import com.jcraft.jsch.UIKeyboardInteractive;
import com.jcraft.jsch.UserInfo;

public class Main {
	public static void main(String[] arg) throws IOException {
		int rport;
	    String lhost;
	    int lport;
	    int proxy_port;
	    String proxy_host;
	    Properties properties = new Properties();
		FileInputStream inputStream = new FileInputStream("project.properties");
	    //InputStream inputStream = this.getClass().getResourceAsStream("project.properties");
		properties.load(inputStream);
		inputStream.close();
	    try{
	      JSch jsch=new JSch();
	      String host=null;
	      String user=properties.getProperty("server_host_name");
	       host=properties.getProperty("server_ip");
	      Session session=jsch.getSession(user, host, Integer.parseInt(properties.getProperty("server_ssh_port")));
	      //setting proxy
	      proxy_host=properties.getProperty("proxy_server");
	      proxy_port=Integer.parseInt(properties.getProperty("proxy_port"));
	      rport=Integer.parseInt(properties.getProperty("remote_port"));
	      lhost=properties.getProperty("local_host");
	      lport=Integer.parseInt(properties.getProperty("local_port"));
	      java.util.Properties config = new java.util.Properties(); 
	      config.put("StrictHostKeyChecking", "no");
	      session.setConfig(config);
	     // session.set
	      session.setPassword("asdfg");
	      session.connect(3000);
	     // session.setProxy(new ProxyHTTP(proxy_host, proxy_port));
	      session.setPortForwardingR("127.0.0.1",rport, lhost, lport);
	      
	      System.out.println(lhost+":lport"+lport+"Forwarded To->"+host+":rport"+rport+"host "+session.isConnected());
	     // session.getHostKey();
	    } 
	    catch(Exception e){
	      System.out.println(e);
	    }
	  }

	  

}
```
 Now I want a ssh server which will accept the Port forwarded from client in NODEJS!(I have read documentation on SSH2 and SSH modules but there is nothing regarding server which accepts the port), I am able to create a server(using ssh2 module Nodejs) and client also connecting but not accepting the forwarded Port.Below is the Code for server.
```
Server Code:
   var webSocketPort=20;
var fs = require('fs'),
crypto = require('crypto'),
inspect = require('util').inspect;
var buffersEqual = require('buffer-equal-constant-time'),
ssh2 = require('ssh2'),
utils = ssh2.utils;

var pubKey = utils.genPublicKey(utils.parseKey(fs.readFileSync('C:\\Program         Files\\OpenSSH\\etc\\ssh_host_rsa_key.pub')));

new ssh2.Server({
hostKeys: [fs.readFileSync('C:\\Program   Files\\OpenSSH\\etc\\ssh_host_rsa_key')]
 }, function(client) {
console.log('Client connected!',client);
client.on('authentication', function(ctx) {
if (ctx.method === 'password'
    || ctx.username === '418374'
    || ctx.password === 'hiandroid8@3') {
  ctx.accept();
  console.log("inside userpwd")
}
else if (ctx.method === 'publickey'
         && ctx.key.algo === pubKey.fulltype
         && buffersEqual(ctx.key.data, pubKey.public)) {
    console.log("inside publicKey")
  if (ctx.signature) {
      console.log("inside signature")
    var verifier = crypto.createVerify(ctx.sigAlgo);
    verifier.update(ctx.blob);
    if (verifier.verify(pubKey.publicOrig, ctx.signature))
      ctx.accept();
    else
      ctx.reject();
  } else {
      console.log("inside nthing")
    // if no signature present, that means the client is just checking 
    // the validity of the given public key 
    ctx.accept();
  }
} else
  ctx.reject();
  }).on('ready', function() {
 console.log('Client authenticated!');
 client.on('session', function(accept, reject) {
    console.log('Client Sssio!');
   var session = accept();
  session.once('exec', function(accept, reject, info) {
    console.log('Client wants to execute: ' + inspect(info.command));
    var stream = accept();
    stream.stderr.write('Oh no, the dreaded errors!\n');
    stream.write('Just kidding about the errors!\n');
    stream.exit(0);
    stream.end();
  });
});
client.on('request', function(accept, reject, name,info,a) {
    console.log('accept',accept)
    console.log('reject',reject)
    console.log('info',info)
    console.log('name',name)
    if(name==="tcpip-forward"){
        //info.bindAddr='localhost';
    }
    console.log('infoafgter',info)
  var session = accept();
    console.log('tcpIp');
  })
   function reExec(i) {
    if (i === 3)
     return;
       client.forwardOut('127.0.0.1', 3000, 'ip_of_localhost', 8080, function(err,          stream) {
      if (err)
        console.log(err);
      else
        stream.end();
      reExec(++i);
    });
  }
  reExec(0);
  }).on('error',function(e){
  console.log("error occcured",e)
  }).on('end', function() {
   console.log('Client disconnected');
  });
 }).listen(webSocketPort, '0.0.0.0', function() {
console.log('Listening on port ' + webSocketPort);
});
```

Getting error as { [Error: (SSH) Channel open failure: open failed] reason: 'ADMINISTRATIVELY_PROHIBITED', lang: '' }

**Comment by shivasrk8** [comment]
Still t the same error Brian.. My aim to run my local server running on port 3000 to run on 8081

**Comment by shivasrk8** [comment]
@msc

**Comment by mscdex** [comment]
You'll also probably need to change `'localhost'` to an IP address.

**Comment by shivasrk8** [comment]
Still same error
Logs:
`Server is listening on port: 443

ssh Listening on port 20
Client connected! Client {
  domain: null,
  _events: { ready: { [Function: g] listener: [Function] } },
  _eventsCount: 1,
  _maxListeners: undefined,
  _sshstream: 
   SSH2Stream {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 32768,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        prefinish: [Object],
        DISCONNECT: [Function],
        KEXINIT: [Function],
        NEWKEYS: [Object],
        KEXDH_INIT: [Function],
        close: [Object],
        error: [Object],
        drain: [Object],
        continue: [Function],
        SERVICE_REQUEST: [Function],
        USERAUTH_REQUEST: [Function: onUSERAUTH_REQUEST],
        GLOBAL_REQUEST: [Function],
        CHANNEL_OPEN: [Function],
        unpipe: [Function: onunpipe],
        finish: [Object],
        data: [Function: ondata] },
     _eventsCount: 17,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 32768,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 20,
        writing: true,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: [Function: nop],
        writelen: 20,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 1,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _transformState: 
      TransformState {
        afterTransform: [Function],
        needTransform: true,
        transforming: true,
        writecb: [Function],
        writechunk: <Buffer 53 53 48 2d 32 2e 30 2d 4a 53 43 48 2d 30 2e 31 2e 35 33 0a>,
        writeencoding: 'buffer' },
     _needContinue: false,
     bytesReceived: 20,
     bytesSent: 0,
     debug: [Function: DEBUG_NOOP],
     server: true,
     maxPacketSize: 35000,
     remoteBugs: 1,
     config: 
      { hostKeys: [Object],
        ident: 'SSH-2.0-ssh2js0.1.1srv',
        algorithms: [Object] },
     _state: 
      { authsQueue: [],
        hostkeyFormat: undefined,
        kex: undefined,
        kexdh: undefined,
        incoming: [Object],
        outgoing: [Object] } },
  _channels: {},
  _curChan: -1,
  _sock: 
   Socket {
     _connecting: false,
     _hadError: false,
     _handle: 
      TCP {
        _externalStream: {},
        fd: -1,
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        onconnection: null,
        writeQueueSize: 0 },
     _parent: null,
     _host: null,
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Object],
        _socketEnd: [Function: onSocketEnd],
        close: [Object],
        error: [Object],
        data: [Function: ondata],
        unpipe: [Function: onunpipe],
        drain: [Function] },
     _eventsCount: 8,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: false,
     destroyed: false,
     bytesRead: 20,
     _bytesDispatched: 24,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: false,
        pauseOnConnect: false,
        _connectionKey: '4:0.0.0.0:20' },
     _server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: false,
        pauseOnConnect: false,
        _connectionKey: '4:0.0.0.0:20' },
     read: [Function],
     _consuming: true,
     _peername: { address: '127.0.0.1', family: 'IPv4', port: 53040 } },
  noMoreSessions: false,
  authenticated: false }
Client authenticated!
inside userpwd
accept function (chosenPort) {
          if (replied)
            return;
          replied = true;
          var bufPort;
          if (name === 'tcpip-forward'
              && data.bindPort === 0
              && typeof chosenPort === 'number') {
            bufPort = new Buffer(4);
            bufPort.writeUInt32BE(chosenPort, 0, true);
          }
          setReply('SUCCESS', bufPort);
        }
reject function () {
          if (replied)
            return;
          replied = true;
          setReply('FAILURE');
        }
info { bindAddr: '127.0.0.1', bindPort: 8081 }
name tcpip-forward
infoafgter { bindAddr: '127.0.0.1', bindPort: 8081 }
tcpIp
{ [Error: (SSH) Channel open failure: open failed] reason: 'ADMINISTRATIVELY_PROHIBITED', lang: '' }
{ [Error: (SSH) Channel open failure: open failed] reason: 'ADMINISTRATIVELY_PROHIBITED', lang: '' }
{ [Error: (SSH) Channel open failure: open failed] reason: 'ADMINISTRATIVELY_PROHIBITED', lang: '' }`

**Comment by mscdex** [comment]
So you're now doing:

```js
client.forwardOut('127.0.0.1', info.bindPort, '127.0.0.1', 8080, function(err, stream) {
  // ...
});
```

right?

**Comment by shivasrk8** [comment]
@mscdex Yes Yes , thats I tried and also directly putting Ip address also tried

**Comment by mscdex** [comment]
Do you have something listening on `lhost:lport` on the client machine? I'm not sure what else to suggest, I'm not very familiar with JSch. Did you try an OpenSSH client instead?

**Comment by shivasrk8** [comment]
No nothing running. I tried same JSch code as client and OpenSSH as a server. Port is getting forwarded successfully and 3000 site running with 8080 on server machine(which is my ultimate goal)

**Comment by mscdex** [comment]
I would think you would have to have something running at `lhost:lport` so that JSch has something to forward the incoming connection to, otherwise it may reject it.

**Comment by shivasrk8** [comment]
ok but ssh server is already running where client is connecting otherwise.Is their any way to write ssh client same as JSCH(code mentioned above which will forward port using tunnel ) using this module   which  will forward port to OpenSSH server./?

**Comment by mscdex** [comment]
I can't really help you with JSCH as I'm not familiar enough with it, but FWIW here is a complete working remote port forwarding example that uses the OpenSSH client to initiate the ssh connection and netcat to receive a forwarded remote connection:

**server.js:**
```js
var fs = require('fs');

var ssh2 = require('ssh2');

new ssh2.Server({
  hostKeys: [ fs.readFileSync('my-host-key') ]
}, function(client) {
  console.log('Client connected!');

  client.on('authentication', function(ctx) {
    if (ctx.method === 'password'
        && ctx.username === 'foo'
        && ctx.password === 'bar') {
      ctx.accept();
    } else {
      ctx.reject();
    }
  }).on('ready', function() {
    console.log('Client authenticated!');

    client.on('request', function(accept, reject, name, info) {
      if (name === 'tcpip-forward') {
        accept();
        // Simulate an incoming connection
        setTimeout(function() {
          console.log('Sending incoming tcpip forward');
          client.forwardOut(info.bindAddr,
                            info.bindPort,
                            '127.0.0.1',
                            45678,
                            function(err, stream) {
            if (err)
              return;
            stream.end('hello world\n');
          });
        }, 1000);
      } else {
        reject();
      }
    });
  }).on('end', function() {
    console.log('Client disconnected');
  });
}).listen(43177, '127.0.0.1', function() {
  console.log('Listening on port ' + this.address().port);
});
```

1. Open 3 terminals
  1. `node server.js`
  2. `nc -l 127.0.0.1 8888`
  3. `ssh -N -R127.0.0.1:12345:127.0.0.1:8888`
2. After the ssh connection is made and authentication is successful, netcat should print "hello world" and exit about 1 second after authentication finishes.

**Comment by kvanstee** [comment]
hi, I'm trying to build a ssh tunnel using the dynamic port forwarding client, get through authorisation but get stuck on what to do with the channel. Here's the relevant code:

}).on('tcpip', function(accept, reject, info) {      
        accept();       
        console.log('sending incoming tcpip forward');
        client.forwardOut( info.destIP, info.destPort, '127.0.0.1', 7777, function(err, stream) {
          if (err) {console.log('not working'); return;}
          stream.end('helloworld\n');
        });      
    }); 

I get "sending incoming ...". Any ideas?

**Comment by mscdex** [comment]
@kvanstee Just pipe between the stream passed to the `forwardOut()` callback and the stream returned by `accept()`. For example:

```js
}).on('tcpip', function(accept, reject, info) {      
  var downstream = accept();       
  client.forwardOut(info.destIP, info.destPort, '127.0.0.1', 7777, function(err, upstream) {
    if (err) {
      downstream.end();
      return console.error('not working: ' + err);
    }
    downstream.pipe(upstream).pipe(downstream);
  });
});
```

**Comment by kvanstee** [comment]
nice. I'm still having trouble grasping forwardOut(). I tried this: 
`client.forwardOut(info.srcIP,` info.srcPort, info.destIP, info.destPort, function(err, upstream) {`

but get:
"not working: Error: (SSH) Channel open failure:"

**Comment by mscdex** [comment]
@kvanstee The upstream server may not be configured to allow forwarding or at least the source/dest ip and/or port.

**Comment by kvanstee** [comment]
I have the server and client on localhost so I assume there should be no forwarding issues. Could it be overlapping channel requests. The client forwards a connection to dst and then the server forwards this connection to dest. The files are [here](https://github.com/kvanstee/ssh2/examples/).

**Comment by mscdex** [comment]
Ok, that does clear things up. Your server is trying to redirect an outbound connection back to itself. The client isn't expecting that because it never asked for remote connections to be forwarded to them (it asked for the reverse -- an outbound connection to/through the server). Assuming you want to just pass the request through, you just need to do a normal `net.connect()` and pipe between the created socket and the `downstream`.

Also, you will want to make sure you don't accidentally create global variables (like is currently the case with `downstream`).
