### ISSUE TITLE
sftp client doesn't work with sftp server on centos 7.2

### ISSUE THREAD

**Issue by volkmarbuehringer** [mscdex/ssh2#439]
Hi,

I created a sftp-server with the code-example.
I tried to connect with the example-client to the server on the same machine.
The client never came to the authentication-event. I tried authentication with password and with 
the private key. Neither worked.
The client always disconnected immediately.

I used node 4.5 and centos 7.2

**Comment by volkmarbuehringer** [comment]
I tried to connect to server with the sftp client from linux and it worked perfectly.
So the problem is the client.

**Comment by volkmarbuehringer** [comment]
It works now.
I needed to generate a rsa-key, not a dsa-key

**Comment by mscdex** [comment]
Yes, newer versions of OpenSSH (server at least) removed support for weaker algorithms and ciphers, including dss/dsa.

**Comment by mscdex** [comment]
The reason for this is that starting with `ssh2` v0.5.0, the default handshake options were more aligned with OpenSSH for better security. You can override these default lists via the `algorithms` configuration option. In particular, you would need to enable the `ssh-dss` value for `serverHostKey`. For example:

```js
var server = new ssh.Server({
  hostKeys: ...,
  algorithms: {
    serverHostKey: [
      'ssh-rsa',
      'ecdsa-sha2-nistp256',
      'ecdsa-sha2-nistp384',
      'ecdsa-sha2-nistp521',
      'ssh-dss'
    ]
  }
});
```
