### ISSUE TITLE
Trouble connecting to WinSSHD

### ISSUE THREAD

**Issue by Meowts** [mscdex/ssh2#441]
Hey, I'm not super familiar with the ins and outs of SSH, but from reading I think I've figured out that the issue might be the version of SSH used on the remote host.

Here is the debug info:

DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.4'
DEBUG: Client: Trying ***.*****.*** on port ** ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-9.99 FlowSsh: Bitvise SSH Server (WinSSHD)'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:748,padLen:11,remainLen:744
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: ecdh-sha2-1.3.132.0.10,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==,gss-group14-sha1-toWM5Slw5Ew8Mqkay+al2g==,gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==
DEBUG: KEX algorithm: ecdh-sha2-nistp256
DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
DEBUG: (remote) Host key formats: ssh-dss,ssh-rsa
DEBUG: Host key format: ssh-rsa
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,3des-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,3des-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha1-96,hmac-md5-96
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha1-96,hmac-md5-96
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none
DEBUG: (remote) Client->Server compression algorithms: zlib,none
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none
DEBUG: (remote) Server->Client compression algorithms: zlib,none
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXECDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:636,padLen:9,remainLen:632
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Signature could not be verified
DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)

So everything -up until- the signature not verifying, to the untrained eye, looks perfectly fine. Also when I connect using the same credentials via Cyberduck (MacOS sftp gui) it works fine. 

Is it WinSSHD that's causing the issue? Is it not? Thanks in advance for taking a look at this!

Almost forgot:
Node : 5.6.0
ssh2 : 0.5.0
- used through ssh2-sftp-client : 1.0.5

**Comment by mscdex** [comment]
What node and `ssh2` module versions are you using? Does this happen every time or only sometimes?

**Comment by Meowts** [comment]
Sorry just updated the comment with the versions.

Happens every time - I've used this module before, connecting to another server... I just verified that the other server was using OpenSSH though, not WINSSHD (FlowSsh: Bitvise SSH Server). The client's SSH server is out of my control, I'm afraid.

**Comment by mscdex** [comment]
I just installed Bitvise SSH server 6.47 (Personal edition) in a VM and was able to connect to that many times just fine (using the same algorithms). I'm curious if Cyberduck is selecting `ssh-dss` for the host key format instead of `ssh-rsa`.

**Comment by Meowts** [comment]
Wow thanks for going through that to test!

Okay in this case I'm stumped. I also tried forcing ssh2 to use ssh-dss, and got the same result.

**Comment by mscdex** [comment]
You wouldn't happen to know what version of Bitvise SSH server they have installed would you? In the past I have seen others that had connected to a Bitvise SSH server where the actual product version number was included in the identification string, but that does not seem to be the case here.

I should have also noted I used node v6.1.0 and used `ssh2` directly, but I don't think that should matter...

**Comment by Meowts** [comment]
Unfortunately I don't - there are 3 levels of indirection between me and the end client, and I don't have the time right now to swim upstream :p 

Question though (noob warning) : when you're authenticating, are you simply using the username / password method, or are you doing anything else with the private key? Just skimmed through Bitvise's docs and saw mention about private keys being used, and this is where the noob part comes in - I'm actually not totally sure if that means I need to be 'doing' something here or not! Any advice?

**Comment by mscdex** [comment]
No, the problem occurs during the handshake, before the user authentication begins. FWIW though for my testing I was just using password-based authentication.

**Comment by mscdex** [comment]
Unless it would be possible for me to debug this remotely, I'm not sure what else I can do to find out what is wrong.

**Comment by kryysler** [comment]
@Meowts did you ever solve this? I'm now facing the same issue
