### ISSUE TITLE
 What is the meaning of the variable 'code' in 'stream.on' cb? 

### ISSUE THREAD

**Issue by arfaWong** [mscdex/ssh2#442]
What is the meaning of the variable `code` in `stream.on`'s cb? 
Is there a constants for it ?

```javascript
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('uptime', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  privateKey: require('fs').readFileSync('/here/is/my/key')
});
```

**Comment by unknownbrackets** [comment]
When you run `uptime`, it returns an exit code (in its `main` function, usually, or via `exit(N);`)

It's pretty much arbitrary, but the convention is that 0 means success and other values mean some kind of failure.

For example, in bash if you can use:

```bash
uptime && echo "Uptime succeeded"

uptime || echo "Uptime failed"
```

These are also just based on the return code - `&&` will only run the next command if the exit code of `uptime` was 0.  It's not some special SSH thing - it's just a standard process exit code.

-[Unknown]

**Comment by mscdex** [comment]
As @unknownbrackets said, it's the exit code of the (last) executed process.

There are no universal definitions for these values, although the shell used to execute the command(s) usually has some predefined exit codes (e.g. bash uses 127 for "command not found"). 0 is almost always used as a "success" indicator and non-zero (commonly a value of 1) as a "failure" indicator.
