### ISSUE TITLE
Error: Authentication failure.

### ISSUE THREAD

**Issue by hellboy81** [mscdex/ssh2#446]
Trying to use  `grunt-sftp-deploy` on windows platform with password auth

Got following message:

```
Error: Authentication failure. Available authentication methods: publickey,password

Fatal error: Connection :: error
```

Running "sftp-deploy:xxx" (sftp-deploy) task
Verifying property sftp-deploy.xxx exists in config...OK
Files: ./my/local/dir -> /out/my/remote/dir
>> Logging in with username 'rightUserName'
>> Concurrency : 4
Connection :: connect
>> Error: Authentication failure. Available authentication methods: publickey,password
Fatal error: Connection :: error

**Comment by mscdex** [comment]
I'm not familiar with `grunt-sftp-deploy`, but assuming you have your authentication configuration set up properly with that module, then your username/password isn't correct.
