### ISSUE TITLE
SSH2 interactive shell

### ISSUE THREAD

**Issue by nitishrai** [mscdex/ssh2#449]
I am unable to create a interactive shell using ssh2 . Each time i execute conn.shell() the command i pass through stream.write() appears to be line breaked in the console. Even i dont know how to autocomplete command when i press tab as that in linux . can u help me in to do so

**Comment by mscdex** [comment]
Can you show the code you're currently trying/using?

**Comment by nitishrai** [comment]
var conn = new Connection();

        conn.connect(login);

        var onShell = function() {};
        conn.on('ready', function() {
            conn.shell(onShell)
        })
        
        var onShell = function(err, stream) {
            if (err != null) {
                console.log('error: ' + err);
            }

            stream.on('data', function(data) {
                socket.emit('reply', data);
                console.log('' + data);
            });
            stream.end('ls -l\nexit\n');
        }
        socket.on('new message', function(data) {

        })``

**Comment by mscdex** [comment]
`console.log()` automatically appends a newline to the text that you pass to it. Use `process.stdout.write()` instead to write to the console without the automatic newline.

**Comment by nitishrai** [comment]
how to autocomplete the command when user press tab i want to have pure interactive shell. 
And plz can u tell me how to resuse the connection i am unable to do it ..

**Comment by mscdex** [comment]
All you have to do is make sure the tab (`\t`) gets sent to the shell stream. If you're sending this from the browser, it may be tricky since tab typically changes webpage element focus. I don't know what you're using on the front end, but you might look into something like the [`xterm`](https://github.com/sourcelair/xterm.js) module. The `xterm` repo also includes a full websocket-based example (frontend and backend) for doing a remote terminal. In that demo they use the `pty.js` module to spawn a *local* shell, but you could just as easily replace that code with a connection to an ssh server and a call to `conn.shell()` and writing between the shell stream and the websocket.

For reusing an ssh connection, just move the `conn` object into a sufficient parent scope so that it can be accessible from wherever you need it. Be aware though that most ssh servers have limits on how many sessions (technically "channels") you can have open per connection, so reusing a connection may not really get you very far (unless of course you have control over the server and can increase the limits appropriately).

**Comment by nitishrai** [comment]
i am using express as front end. and i have about 50 of ssh login all accessible to the user so when the user click on the server a new terminal is displayed in the popup and from here he can use the server . want to achieve this .

**Comment by mscdex** [comment]
Like I suggested, I would start with the [`xterm` demo](https://github.com/sourcelair/xterm.js/tree/master/demo). Then once you have that working, swap out the `pty.js` code in the demo's backend with code that uses the `ssh2` module instead. It's that easy.

**Comment by nitishrai** [comment]
i have totally blank ....

**Comment by nitishrai** [comment]
can u give it from ur side ??

**Comment by mscdex** [comment]
I don't understand what you're asking for. Did you look at the `xterm` demo I linked to?

**Comment by nitishrai** [comment]
Yes sir i watched it .. is there a way that i contact u directly ?

**Comment by nitishrai** [comment]
As u told i have integrated xterm but unable to intergrate this part of code ..
```
  * Open bash terminal and attach it
   */
  var term = pty.spawn(process.platform === 'win32' ? 'cmd.exe' : 'bash', [], {
    name: 'xterm-color',
    cols: 80,
    rows: 24,
    cwd: 'process.env.PWD',
    env: process.env
  });
  term.on('data', function(data) {
    try {
      ws.send(data);
    } catch (ex) {
      // The WebSocket is not open, ignore
    }
  });
  ws.on('message', function(msg) {
    term.write(msg);
    console.log(term);
  });
  
  ws.on('close', function () {
    console.log('close');
    process.kill(term.pid);
  });
```
Can u help me ?

**Comment by nitishrai** [comment]
Hi i have used ssh2 instead of pty using this code can u tell this is right or not 
```

                            conn.on('ready', function() {

                                conn.shell(function(err, stream) {

                                    stream.on('data', function(data) {
                                        try {
                                            ws.send('' + data);
                                        } catch (ex) {
                                            // The WebSocket is not open, ignore
                                        }
                                    });

                                    ws.on('message', function(msg) {
                                        console.log(msg);
                                        stream.write(msg);
                                    });

                                    ws.on('close', function() {
                                        stream.end('exit');
                                        conn.end();
                                        console.log('close');
                                        //process.kill(conn.pid); this makes terminal close..
                                    });

                                });
                            });
```

**Comment by mscdex** [comment]
That looks about right. You may or may not need to append a `\n` after 'exit' to simulate the enter key.

**Comment by nitishrai** [comment]
Is there a way to directly login in to a specific directory as that same in pty where we mentioned the `cwd`
i am doing in ssh2 as `stream.write('cd  directorypath \n')`  is this the right way ?

**Comment by mscdex** [comment]
`conn.shell()` gives you a plain old shell session, like what you get by default when you do `ssh foo@bar.com` or use PuTTY, so anything you write to the stream is as if you typed it from your keyboard. So if you want to change directories, you just do what you mentioned: `stream.write('cd /foo/bar/baz\n')`.

**Comment by nitishrai** [comment]
Ok got it !!  Now there is one more issue that my current code is running on 3030 and i am sending socket request to 3000 port on changing to 3000 i am getting the error `connection closed before receiving a handshake response` do u know why its happening ?

**Comment by mscdex** [comment]
No idea. The `xterm` demo simply [uses whatever port you use in your browser](https://github.com/sourcelair/xterm.js/blob/e0c0fb6917cae9bf0d6dca45167170166f1afa1a/demo/main.js#L23) to connect to the demo's Express/WebSocket server.

**Comment by nitishrai** [comment]
Ok sir !! i will be asking few more doubts later on for regarding SFTP . Thank You sir
