### ISSUE TITLE
successive connect/end causing a maxListeners error

### ISSUE THREAD

**Issue by shlomitgillo** [mscdex/ssh2#451]
My code is calling Client.prototype.connect(). When the connection is aborted (get a 'close' or 'end' event), Client.prototype.end() is called, and then try to connect again (by calling Client.prototype.connect() again). 
I tested this code by connecting and disconnecting the ssh target machine. On the third connect/disconnect session, I got the following:

**_$ (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Client.addListener (events.js:160:15)
    at Client.once (events.js:185:8)
    at Client.connect (/Tmp/node_modules/ssh2/lib/client.js:73:10)
    at _connectAttemptIntervalExpired (/Tmp/src/test.js:233:26)
    at null.<anonymous> (/Tmp/src/test.js:122:17)**

I looked into ssh2/lib/client.js, and there, in Client.prototype.connect, it adds a listener. I'm not sure it removes this listener upon calling to Client.prototype.end. This might cause the issue. How to get this listener removed, so in the next Client.prototype.connect() call I will not get this error?

Thanks.

**Comment by mscdex** [comment]
I'm not able to reproduce this problem. Can you provide a simple, reproducible example?

**Comment by mscdex** [comment]
@shlomitgillo Were you able to come up with a reproducible example?
