### ISSUE TITLE
google authenticator

### ISSUE THREAD

**Issue by deppli** [mscdex/ssh2#453]
My company is use google authenticator for ssh ,  before input the password,I must input the Verification code,what can I do?Look forward to your reply.

**Comment by mscdex** [comment]
Set `tryKeyboard: true` in your connection config and add a `keyboard-interactive` event handler. The signature for the `keyboard-interactive` event is in the readme.

**Comment by deppli** [comment]
![image](https://cloud.githubusercontent.com/assets/10197277/17137687/09f9ca8c-536f-11e6-8a24-5e91a8aca541.png)
why console isn't log error but the test isn't log

**Comment by deppli** [comment]
![image](https://cloud.githubusercontent.com/assets/10197277/17137723/4418fca6-536f-11e6-9442-f5c25a73894f.png)

why the console  has not  log error and the ready function has no executive?

**Comment by mscdex** [comment]
Can you change `console.log(prompts[0].prompt)` to `console.log(prompts)` and also set `debug: console.log` in your connection options and post the output?

**Comment by deppli** [comment]
DEBUG: Connection: Trying xxxx.xxx.xxx on port 22 ...
POST /ns/connect 200 10ms
DEBUG: Parser: STATE_INIT
DEBUG: Parser: STATE_GREETING
DEBUG: Parser: STATE_HEADER
DEBUG: Connection: Server ident: 'SSH-2.0-OpenSSH_5.3'
DEBUG: Parser: STATE_PACKETBEFORE (expecting 8)
DEBUG: Parser: STATE_PACKET
DEBUG: Parser: pktLen:836,padLen:10,remainLen:832
DEBUG: Parser: STATE_PACKETDATA
DEBUG: Parser: STATE_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Parser: STATE_PACKETBEFORE (expecting 8)
DEBUG: Connection: Sending KEXINIT
DEBUG: Connection: Comparing KEXInits...
DEBUG: (local) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
DEBUG: (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
DEBUG: Connection: Server->Client Cipher: aes256-ctr
DEBUG: (local) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc,arcfour256,arcfour128,cast128-cbc,arcfour
DEBUG: (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
DEBUG: Connection: Client->Server Cipher: aes256-ctr
DEBUG: (local) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: Connection: KEX: diffie-hellman-group-exchange-sha256
DEBUG: (local) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG: Connection: Client->Server HMAC: hmac-md5
DEBUG: (local) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-sha1-96,hmac-md5-96
DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG: Connection: Server->Client HMAC: hmac-md5
DEBUG: (local) Client->Server compression algorithms: none
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Connection: Client->Server Compression: none
DEBUG: (local) Server->Client compression algorithms: none
DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com
DEBUG: Connection: Server->Client Compression: none
DEBUG: (local) Host key formats: ssh-rsa,ssh-dss
DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
DEBUG: Connection: Host key format: ssh-rsa
DEBUG: Connection: Sending KEXDH_GEX_REQUEST
DEBUG: Parser: STATE_PACKET
DEBUG: Parser: pktLen:404,padLen:8,remainLen:400
DEBUG: Parser: STATE_PACKETDATA
DEBUG: Parser: STATE_PACKETDATAAFTER, packet: KEXDH_GEX_GROUP
DEBUG: Connection: Sending KEXDH_GEX_INIT
DEBUG: Parser: STATE_PACKETBEFORE (expecting 8)
DEBUG: Parser: STATE_PACKET
DEBUG: Parser: pktLen:956,padLen:9,remainLen:952
DEBUG: Parser: STATE_PACKETDATA
DEBUG: Parser: STATE_PACKETDATAAFTER, packet: KEXDH_GEX_REPLY
DEBUG: Connection: Checking host key format
DEBUG: Connection: Checking signature format
DEBUG: Connection: Verifying signature
DEBUG: Connection: Sending NEWKEYS
DEBUG: Parser: STATE_PACKETBEFORE (expecting 8)
DEBUG: Parser: STATE_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: STATE_PACKETDATA
DEBUG: Parser: STATE_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Connection: Sending SERVICE_REQUEST
DEBUG: Parser: STATE_PACKETBEFORE (expecting 16)
DEBUG: Parser: STATE_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: STATE_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: hmacSize:16
DEBUG: Parser: STATE_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: STATE_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Connection: Sending USERAUTH_REQUEST (keyboard-interactive)
DEBUG: Parser: STATE_PACKETBEFORE (expecting 16)
DEBUG: Parser: STATE_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:60,padLen:18,remainLen:48
DEBUG: Parser: STATE_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: hmacSize:16
DEBUG: Parser: STATE_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: STATE_PACKETDATAAFTER, packet: USERAUTH_INFO_REQUEST
DEBUG: Connection: Sending USERAUTH_INFO_RESPONSE
DEBUG: Parser: STATE_PACKETBEFORE (expecting 16)
DEBUG: Parser: STATE_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:11,remainLen:32
DEBUG: Parser: STATE_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: hmacSize:16
DEBUG: Parser: STATE_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: STATE_PACKETDATAAFTER, packet: USERAUTH_INFO_REQUEST
DEBUG: Connection: Sending USERAUTH_INFO_RESPONSE
DEBUG: Parser: STATE_PACKETBEFORE (expecting 16)


console.log(prompts):
[ { prompt: 'Verification code: ', echo: false } ]
[ { prompt: 'Password: ', echo: false } ]


This's debug log output 。If you have free time,can you help me to see it?Thank you

**Comment by deppli** [comment]
Thank you ,it's my code mistake.
