### ISSUE TITLE
Re-open stream?

### ISSUE THREAD

**Issue by paul-bell** [mscdex/ssh2#456]
Hello,

This isn't a real issue, i.e., it's not any kind of defect. Rather, I am just trying to see if I can get ssh2 to behave in a certain way. I don't really understand ssh2 very well and that is a large part of the problem here. Also, if this isn't the right forum to raise a confusion, I do apologize.

Having established a connection, is there a way to close its stream (after sending some data back to the client) and then re-open the stream? I here assume that the connection (this is done via 'shell', not 'exec') is still open. I know how to close the stream; it's the re-open part that I can't figure out.

Thank you.

-Paul

**Comment by mscdex** [comment]
Re-opening a stream is not possible, at the node streams layer or at the ssh2 protocol layer (once a channel is closed it's closed). The only thing you can do is create another stream by calling out to `.shell()`/`.exec()`/etc.

Why do you need to "re-open" a stream?

**Comment by paul-bell** [comment]
Thanks very much for the reply.

I was afraid you might ask me why I needed to re-open the stream. I am running out the door in a few mins. and can't really do it justice now. But, briefly, I have a terminal emulation in a browser. You enter a shell command, e.g., 'ps -ef' and it goes to the node.js web service who establishes your ssh2 (very cool, BTW) connection to a Linux host.

I've noticed an "accumulating effect" where, when commands were slow to execute because of load on the host, they'd eventually all fire in quick succession. That was fine.

The odd part was that after all of these commands had finished, if I entered a simple command in my terminal emulation, e.g., 'pwd', I would see displayed on the host console (via my console.log call) not only the result of the pwd I just entered, but also all the previous commands. So...I reasoned that some stuff wasn't getting flushed properly. That's why I wanted to close/open the stream. Simply trying to avoid the overhead of establishing/destroying TCP connections with each command.

-Paul

**Comment by mscdex** [comment]
When you get time, post your code somewhere. Something doesn't sound right.

If you're wanting to do ssh access via the browser, you might look at [this example](http://stackoverflow.com/a/38690242/2050455) if you haven't already.

**Comment by moonlitSpider** [comment]
Hi,

I got it working by replacing my use of .shell with one of your examples for .exec(); thanks.

But I have another question about how to handle authentication failures. When I deliberately provide bad credentials (userid/password) to the conn.connect() call, I observe error message "All configured authentication methods failed" followed by my node.js server program's termination (this server program is acting like an SSH client).

I suspect that I am missing something obvious, but is there a way to handle authentication failures? I have the usual listeners defined and I've wrapped .connect() in try/catch (here assuming, perhaps wrongly, that it's *synchronous* ).

Thanks again.

-Paul

**Comment by mscdex** [comment]
@moonlitSpider Add an `error` event handler on your ssh connection object:

```js
ssh.on('error', function(err) {
  // ...
});
```

The `error` event is special in node, if no handlers exist for that event the error will be thrown (see the [node docs](https://nodejs.org/docs/latest/api/errors.html#errors_error_propagation_and_interception) for more information).

**Comment by moonlitSpider** [comment]
Cool; thanks. Will try it right now.

-Paul

**Comment by moonlitSpider** [comment]
Thanks again.

-Paul
