### ISSUE TITLE
sshtunnel as unikernel

### ISSUE THREAD

**Issue by kvanstee** [mscdex/ssh2#457]
Hi, 
I got the tunnel working after your astute comments. It works on a remote server but does not work after baking into a unikernel. For some reason the client's public key fails. Can you think of a reason for this?
The repo is [here](https://github.com/kvanstee/sshtunnel/)

**Comment by mscdex** [comment]
I'm assuming you mean that the `verifier.verify()` is what returns `false`?

Does the failure happen every single time or does it succeed sometimes?

Is the same node version and `ssh2`/`ssh2-streams` module versions being used in both scenarios? If so, I don't know why it would work in one place and not the other. I'm not familiar enough with unikernels to really suggest anything.

**Comment by mscdex** [comment]
@kvanstee Did you end up getting this issue resolved or ?
