### ISSUE TITLE
Error event not emit when key exchange failed

### ISSUE THREAD

**Issue by xiulunlin** [mscdex/ssh2#458]
![8776d7ea-7d09-494b-806b-4386959093c5](https://cloud.githubusercontent.com/assets/7201022/17735979/e1094f12-64b7-11e6-8d2f-194aacde9342.png)

**Comment by nhhoang** [comment]
I got this bug too, please fix it

**Comment by mscdex** [comment]
This is fixed now in `ssh2-streams` v0.1.11. A simple `npm install ssh2` should pick up the new dependency version.
