### ISSUE TITLE
How to handle a stream reaching the MAX_WINDOW limit

### ISSUE THREAD

**Issue by clickstreammedia** [mscdex/ssh2#460]
If you have...

```
conn.forwardOut( '', null, host, port, ( error, stream ) => {
    const buffers = [];
    stream.on( 'data', buffer => buffers.push( buffer ) );
} );
```

Right now the stream stalls with no more data events after `Channel.MAX_WINDOW` bytes have been read. How do you handle this case so that you can continue reading more bytes?

**Comment by mscdex** [comment]
You shouldn't need to do anything. All of the window handling is linked with the `stream`'s backpressure mechanism.

What version of `ssh2` are you using? I just tweaked the window adjustment behavior the other day in v0.5.1. If you are still experiencing issues with that version, can you set `debug: console.log` in your connection config object and post the resulting output?

**Comment by clickstreammedia** [comment]
This was human error :trollface:

**Comment by clickstreammedia** [comment]
This behavior happens when you do something like:

```
conn.forwardOut( '', null, host, port, ( error, stream ) => {
    const buffers = [];
    stream.on( 'data', buffer => buffers.push( buffer ) );
    stream.end( "Some data I want to send" );
} );
```

It started working correctly when I did `stream.write( "Some data I want to send" );` instead.
