### ISSUE TITLE
Is it possible to use SSH2 inside async?

### ISSUE THREAD

**Issue by Syavne** [mscdex/ssh2#461]
Good day.

I've been trying to use ssh2 to connect and execute commands on remote servers using it inside async calls, however, it's not a perfect world and sometimes the SSH key is not working or the user does not exists or it takes too much time for the server to respond or the connection is closed  unexpectedly... and it seems I'm unable to send the callback() in some of these situations.

To make things easy, I reduced the code to the following example:
```
var Client = require('ssh2').Client;

var ips []; // a list with many IP addresses (over 200)
var username = 'its_me';
var key = fs.readFileSync('key.pem');

async.each(ips, (function(ip, callback) {

  var ssh = new Client;

  ssh.on('end', function() {
    return callback();
  }).on('error', function(error) {
    console.log(error);
    return callback();
  }).on('ready', function() {
    console.log(ip);

    ssh.exec('uname', function(error, stream) {
      var buffer;
      if (error) {
        console.log(error);
        ssh.end();
      } else {
        buffer = '';
        stream.on('data', function(data) {
          buffer += data.toString();
        });
        return stream.on('close', function(code, signal) {
          console.log(code);
          console.log(signal);
          console.log(buffer);
          ssh.end();
        });
      }
  }).connect({
    host: ip,
    username: username,
    privateKey: key
  });

}), function() {
  console.log('Done!);
});

```

I've been playing with the callback() in every event (including 'close'), sometimes the execution completes and sometimes it gets frozen.

Is this possible/supported? Where can the callback() be set in order to finish the async call every time even if unknown errors occurred? I've been unable to get this working reliably even with the use of promises and wrappers like node-ssh or ssh-promise.

**Comment by mscdex** [comment]
You should put it in a `close` event handler on the connection object.

**Comment by Syavne** [comment]
I've been doing some more tests and the problem I'm stuck with has to do with the message:
"Error: Callback was already called."

If I remove the callback() from `error` or `end` the execution gets frozen and if I use `close` (either using it instead of `end` or putting both) I got the same results.

**Comment by mscdex** [comment]
You could try something like this:

```js
  var err;
  ssh.on('close', function() {
    callback(err);
  }).on('error', function(error) {
    err = error;
  }).on('ready', function() {
  // ...
```

**Comment by Syavne** [comment]
It seems I got confused at some point with the events and got some kind of tunnel vision.

Thank you very much @mscdex, now it is working great!
