### ISSUE TITLE
keyboard-interactive and standard password

### ISSUE THREAD

**Issue by sagorshkov** [mscdex/ssh2#462]
Hi,

I'm trying to distinguish the standard password authentication method and the keyboard-interactive. Could you clarify is it possible?

I found the keyboard-interactive Client event. But what if this method is disabled on the server? Let's suppose there is only one enabled method on the server. This method is standard password. Is there any opportunity to handle this case?

**Comment by mscdex** [comment]
The plain 'password' auth method is exactly what it sounds like, it merely transmits a password to be used for user authentication.

'keyboard-interactive' is a much more (potentially) complex mechanism in that it can be a multi-step of back and forth questions and answers between the server and client. They are questions that are meant to be presented in an interactive manner, so short of trying to parse the prompts/questions, it is hard to tell (programmatically) what kind of input the server is seeking. This method could simply consist of a 'Password:' prompt, but it could be more involved such as a two-factor auth mechanism (e.g. [duo.com](https://duo.com/docs/duounix)).

Any methods you provide *will* be attempted, it's just the order that is fixed currently. So if you provide a `password` value *and* you also set `tryKeyboard: true`, then both of those methods will be tried. So if the server rejects one or the other, it won't matter if it succeeds with the other method.
