### ISSUE TITLE
help needed: sftp readdir and stat efficiently

### ISSUE THREAD

**Issue by CragVFX** [mscdex/ssh2#466]
Hello,

I am trying to find all directories inside of some directory let's call it /base, and I can do that with sftp.readdir() and then calling sftp.stat on every filename in the list from the readdir, but this is very slow when working with say 500 files and 1 dir inside /base.  Is there another way to do this that I am missing or is it possible to enhance readdir so that we can get the type in the attrs as well without having to stat every file.

Thanks!

**Comment by mscdex** [comment]
The obvious alternative would be to execute a remote command, for example:

```js
ssh.exec('find /base -type d 2>/dev/null', function(err, stream) {
  // Parse `stream` line by line ...
});
```

**Comment by CragVFX** [comment]
I will only have sftp access unfortunately, so that wouldn't work for me in this case.

**Comment by unknownbrackets** [comment]
Is `info.attrs.mode & 16384` (aka `fs.constants.S_IFDIR`) true for any of the entries?

Note that this wouldn't be forwards compatible with sftp v5+, but I believe those versions would have a `type` set to 4 instead.  Might be ideal for ssh2 to do this compatibility for you, but that probably belongs in a higher level library.

-[Unknown]

**Comment by mscdex** [comment]
@unknownbrackets It should already be possible to do that with `stats.isDirectory()`

@CragVFX Unfortunately there isn't really any other option then. (If you aren't already) You could improve things a bit by sending readdir/stat requests in parallel since the ssh2 protocol supports that.
