### ISSUE TITLE
Unable to download '~/.bash_profile' using sftp

### ISSUE THREAD

**Issue by metabench** [mscdex/ssh2#469]
I get `Error: No such file`.

Is this expected behaviour? If so, why does it not work?

Is SFTP the wrong tool to use to read and write bash profiles?

I know I can download the `bash_profile` using `cat ~/.bash_profile`, and downloading the output, but I'm interested in knowing why SFTP will not work for this, and think it's possibly a bug but I'm not sure.

I have not tried uploading the `bash_profile` using SFTP, but by the looks of things I'm more certain to get it done using a bash command over SSH. Any thoughts on if this can be done using SFTP through this module?

**Comment by mscdex** [comment]
Did you try removing the `~` and substituting it with `/home/<username>`? Most SFTP servers do not perform shell expansions, so tildes and shell variables are taken literally.

**Comment by metabench** [comment]
I had not tried it before, but I just tried it (`'/home/root/.bash_profile'`) and I got the same `Error: No such file`.

**Comment by mscdex** [comment]
If you're logging in as root, then I don't know what to suggest. I should also point out that just using `'.bash_profile'` typically works as well since most SFTP servers resolve relative paths from the user's home directory.

**Comment by metabench** [comment]
@mscdex Thanks, that's solved the issue to do with downloading that file. Thanks for the explanation.
