### ISSUE TITLE
Disable StrictHostKeyChecking?

### ISSUE THREAD

**Issue by emmyboy** [mscdex/ssh2#471]
Inheriting some backend code that utilizes your module. However remote ssh authentication requirements require strict host key checking to be disabled and the connection is now failing in production.

Is there a way to disable this similar to the "-o StrictHostKeyChecking=no" option of a ssh cli?

**Comment by mscdex** [comment]
The default is already "no." You have to handle host key checking yourself.

**Comment by emmyboy** [comment]
You are absolutely right, it does. I just caught that in the debug info

Thanks
