### ISSUE TITLE
Low keep alive interval and disconnection problems

### ISSUE THREAD

**Issue by Rush** [mscdex/ssh2#474]
What I'm doing:
* Setting keepAliveInterval to 1000 on the client side
* Setting SSH connection over a 350ms latency link (no packet loss, high bandwidth)
* Streaming VNC protocol using direct tcp-ip link.

It mostly works fine but when the stream starts getting more data (as much as VNC can send at 1024x768) then I'm getting disconnects with the following error:
```
Error: No response from server
at Socket.<anonymous> (/opt/app/node_modules/ssh2/lib/client.js:229:15)
```

I  found a workaround which is to set the `keepAliveInterval` to something higher like `10000`. Everything works fine now.

Could you explain how does the keep alive timeout logic works? Does it send a new probe before the old one returns? Does it work fine with multiplexing lots of data?

**Comment by mscdex** [comment]
The keepalive mechanism works the same way as with the OpenSSH client. You can specify the interval in which keepalive requests are sent (`keepAliveInterval`) and how many unanswered requests before considering the connection dead (`keepaliveCountMax`). So those are two knobs you can fiddle with.

The keepalive requests are sent like any other request, immediately without entering into any kind of queue locally.
