### ISSUE TITLE
Problems connecting from .NET Framework SSH.NET client

### ISSUE THREAD

**Issue by darkpixel** [mscdex/ssh2#476]
I opened up a bug at sshnet/SSH.NET#90 about problems connecting from the SSH.NET client, and @drieseng provided some information on what he thought was happening.  The low-level protocol stuff is beyond me, but I figured I would loop everyone in.

**Comment by mscdex** [comment]
When you reject an authentication attempt, you can pass back an array of authentication methods if you want, for example:

```js
ctx.reject(['publickey', 'password']);
```

IMHO ultimately this is a bug in SSH.NET, since you can pass back any auth methods you want, even if those methods will never be accepted/valid. For example, you could pass back the two methods in the example above, but you may only ever allow `'publickey'`. One benefit to keeping the user in the dark about supported auth methods is "security through obscurity."

**Comment by darkpixel** [comment]
Thanks @mscdex.  I'll give that a shot this evening and report back.

**Comment by drieseng** [comment]
I agree that SSH servers are not REQUIRED to pass back the authention methods supported.
[RFC 4252](https://www.ietf.org/rfc/rfc4252.txt) clearly states this:

> It is RECOMMENDED that servers only include those 'method name'
   values in the name-list that are actually useful.  However, it is not
   illegal to include 'method name' values that cannot be used to
   authenticate the user.
> Already successfully completed authentications SHOULD NOT be included
   in the name-list, unless they should be performed again for some
   reason.

This is actually the first SSH server that I know of, that does not pass back the list of authentications.
Actually, how would multi-factor authentication work ?
How can a client know if **mscdex** expects it to authenticate using password authentication twice?  What if the server wants the SSH client to first authenticate using either password authentication or publickey, and that - in case of password authentication - the SSH client subsequently must authenticate using publickey authentication (or whatever)?
Do you expect the admin of the SSH server to provide that information to clients out-of-band?
Should a SSH client try whatever authentication methods it has to its disposal (and even multiple times, as we could be dealing with a server that requires multi-factor authentication)?

Note:
I'm not criticizing how **mscdex** work, I'm just wondering how **SSH.NET** should deal with this (and how other SSH clients currently deal with this).

**Comment by mscdex** [comment]
@drieseng It's entirely dependent upon the 2fa implementation. Some services like Duo use `'keyboard-interactive'` for the secondary, external auth. It's possible that other implementations merely use a combination of the built-in ssh auth methods. Yet other implementations might solely use `'keyboard-interactive'` (imagine typing a password and an access code via the same auth method).

There's many variables and there is no standard way to detect 2fa, unless you count the "partial success" field that can be set when "rejecting" an auth request (this flag can also be set by passing a boolean as the second argument to `.reject()` in `ssh2`).

**Comment by darkpixel** [comment]
Passing back ```ctx.reject(['publickey'])``` causes SSH.NET to connect successfully.  I appreciate the help @mscdex and @drieseng.
