### ISSUE TITLE
Keep alive event?

### ISSUE THREAD

**Issue by darkpixel** [mscdex/ssh2#478]
I have some information and stats on connections that I am storing in REDIS that I would like to keep up to date every so often (i.e. anywhere between a few seconds to 10 minutes is not a problem).  It seems like it might be handy to tap into a keepalive event on the server to do that.

**Comment by mscdex** [comment]
What about using a repeating timer? It seems like that would give you better control over when stats are updated rather than relying on sending/receiving of (keepalive) packets.

**Comment by darkpixel** [comment]
I thought about that, but if I use something like setTimeout, then I have to make sure it gets torn down if the ```client.end``` or ```client.error``` events are thrown.  I don't see an easy way to pass a timer that was created in the ```client.ready``` out of scope to those events.

**Comment by mscdex** [comment]
AFAIK something like this should work:

```js
function setupTimer(client) {
  // `client` is the ssh connection object ...

  var statsTimer;
  client.once('ready', function() {
    statsTimer = setInterval(updateRedis, 5 * 1000);
  });
  client.once('close', function() {
    clearInterval(statsTimer);
  });
}
```

**Comment by darkpixel** [comment]
Urk.  I'm an idiot.  I don't know what I was thinking at the end of a 16-hour day.  Additionally the shift from Python, Perl, Bash, etc to NodeJS still occasionally throws me for a loop.  Sorry for the noise.
