### ISSUE TITLE
Troubles trying to create SSH server with dynamic forwarding

### ISSUE THREAD

**Issue by Rommero** [mscdex/ssh2#479]
I've encountered a major problem when implementing SSH server capable of dynamic forwarding (capable of processing client connection described in example (Dynamic (1:1) port forwarding using a SOCKSv5 proxy...).
I've managed to discover, that the followind code allows the successfull socks protocol conversation, but after the socks connection is established, I get no incoming data on the socket.

Here's some code:
```
new ssh2.Server({
	hostKeys: [fs.readFileSync('host.key')]
}, function (client) {	
	client.on('authentication', function (ctx) {
		if (ctx.method === 'password' &&
			ctx.username === 'foo' &&
			ctx.password === 'bar')
			ctx.accept();
		else
			ctx.reject();
// Following code ensures the SOCKS protocol conversation to succeed
	}).on('tcpip', function(accept,reject, data){
		var session = accept();
	}).on('end', function () {
		// console.log('Client disconnected');
	});
}).listen(sshServerPort, sshServerIP, function () {
	console.log('Listening on port ' + sshServerPort);
});
```
After the server is launched, I user the dynamic port forwarding example
```
socks.createServer(function(info, accept, deny) {
  var conn = new Client();
  conn.on('ready', function() {
    conn.forwardOut(info.srcAddr,
                    info.srcPort,
                    info.dstAddr,
                    info.dstPort,
                    function(err, stream) {
      if (err) {
        conn.end();
        return deny();
      }
      var clientSocket;
      if (clientSocket = accept(true)) {
        stream.pipe(clientSocket).pipe(stream).on('close', function() {
          conn.end();
        });
      } else
        conn.end();
    });
  }).on('error', function(err) {
    deny();
  }).connect(ssh_config); // ssh_config contains sshServerPort, sshServerIP used for ssh server
}).listen(1080, 'localhost', function() {
  console.log('SOCKSv5 proxy server started on port 1080');
  //Here I try to establish a new SOCKS connection via the freshly obtained SOCKs server.
  lookup(dstHost, dstPort, 'localhost', 1080, function(res) {
      console.log(res);
  });
}).useAuth(socks.auth.None());
```
lookup is a function, which establishes socks connection to dstHost:dstPort via the newly acquired proxy. It returns socket data (banner) on the given connection if the latter one is established. 
The trouble is I get not "data" on lookup's socket. 

The host on dstHost and dstPort has a banner and the lookup function works perfectly well, when called using dynamic forwarding via ubuntu's default ssh service. 

I suppose i am missing some sort of a tiny step, which will solve my problem, but cannot understand what the problem

**Comment by mscdex** [comment]
On the server side all you're doing is accepting the connection forwarding request, but you're not doing anything with the returned (inbound) stream (this also means that a more appropriate variable name would be `stream` instead of `session`), that is why you're not seeing any traffic. It's up to you to actually make a TCP connection to the request destination address and port (both of which are available in your `data` argument in the `'tcpip'` event handler) and pipe between the two. For example:

```js
var net = require('net');

// ...

var src;
var dest = new net.Socket();
dest.on('connect', function() {
  src = accept();
  if (!src)
    return dest.end();
  src.pipe(dest).pipe(src);
});
dest.on('error', function() {
  if (!src)
    reject();
});
dest.on('close', function() {
  if (!src)
    reject();
});
dest.connect(data.destPort, data.destIP);
```

**Comment by Rommero** [comment]
Sorry I bothered you with such a nonsense. You have done a great job, thank you for your help.
