### ISSUE TITLE
Exec not working correctly with & every now and then.

### ISSUE THREAD

**Issue by arianitu** [mscdex/ssh2#48]
I'm running this command specifically:

cd ~/dir1/dir2 ; LD_LIBRARY_PATH=../lib/ ../bin/node app.js run &

This seems to work 50%ish of the time. When it doesn't work, I get no stdout or stderr. When it does work, I get stdout as expected.

It always seem to work without &

If I run it through ssh directly, the command with & works 100% of the time.

Essentially I get

stream: exit (no signal name set, only program return value, and it's 0)
stream: close

instead of

stream:data (expected data.)
stream:exit (no signal name set, only program return value, and it's 0)
stream:close

Got any idea's to why this happens? (is & suppose to work properly?)

**Comment by przemyslawpluta** [comment]
Trying to run bash script in the background with `ssh2` with `nohup bash_script &` but it exits every time on connection close ... any suggestions?

**Comment by mscdex** [comment]
@przemyslawpluta Do you have a simple bash script that I can use to reproduce the issue with?

**Comment by przemyslawpluta** [comment]
@mscdex simple example where I'm starting a process with `forever` over the ssh. Running `forever start myProcess` via cli works without any issues but doing the same command via ssh starts and stops it pretty much straight after. Same goes for the `bash` scripts that suppose to be dropped into the background.

```js
var Client = require('ssh2').Client,
   conn = new Client();

conn.connect({
  host: 'xxx.xx.xxx.xxx',
  port: 22,
  username: 'user',
  passphrase : 'pass',
  privateKey: require('fs').readFileSync('private_key')
});

conn.on('ready', function ready() {

  console.log('Client ready');

  conn.exec('forever start myProcess', function exec(err, stream) {
    if (err) throw err;

    stream.on('close', function close(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    });

    stream.on('data', function out(data) {
      console.log('STDOUT: ' + data);
    });

    stream.stderr.on('data', function err(data) {
      console.log('STDERR: ' + data);
    });

  });

});
```

**Comment by mscdex** [comment]
@przemyslawpluta Well, if you are getting errors about opening the terminal, you will need to allocate a pty, like:

```javascript
// allocate a pty (using defaults) for the command
conn.exec('forever start myProcess', { pty: true }, function exec(err, stream) {
  // ...
});
```

**Comment by przemyslawpluta** [comment]
@mscdex running bash script
```bash
#!/bin/bash
userInput=$1
nohup watch -n1 "find ./ -mmin -$userInput" &
```
this way doesn't produce `err` but script doesn't get dropped in the background either.

```js
conn.exec('/path/bash_script 1', { pty: true }, function exec(err, stream) {
  // ...
});
```

**Comment by mscdex** [comment]
@przemyslawpluta I don't know about `forever`, but using nohup works for me and the sleep is still running after the client has exited:

```javascript
  conn.exec('nohup sleep 180 > /dev/null 2>&1 &', function(err, stream) {
    if (err) throw err;
    stream.pipe(process.stdout);
    stream.stderr.pipe(process.stderr);
    stream.on('close', function(code, signal) {
      console.log('::: stream close', code, signal);
      conn.end();
    });
    stream.end();
  });
```

**Comment by przemyslawpluta** [comment]
@mscdex have you tried the same with `bash` script? 

```bash
#!/bin/bash
userInput=$1
nohup watch -n1 "find ./ -mmin -$userInput" > /dev/null 2>&1 &
```

**Comment by zl730** [comment]
"&" is not working with "pty=true"

**Comment by zyf0330** [comment]
I meet this problem too, even if I use `nohup`.

> "&" is not working with "pty=true"

**Comment by zyf0330** [comment]
wrap with sh -c works, like `nohup sh -c "DISPLAY=:1 google-chrome &"`
