### ISSUE TITLE
Documentation Request: How to execute multiple commands

### ISSUE THREAD

**Issue by wjozefssrf** [mscdex/ssh2#480]
I want to execute more than one command like bash , how to ?

**Comment by mscdex** [comment]
You can pass multiple comments to `.exec()` just like you would normally, with semicolons and/or ampersands.

If you want an interactive shell session, use `.shell()`.

**Comment by wjozefssrf** [comment]
i dont wanna use the semicolons because i have about 30 commands to execute and isn't a good solution , and by using async i get this error 

`(node) warning: possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit`

by looking around I found someone use this code ?

```javascript
var stream = exec('bash', 'ubuntu@my-remote.com')
stream.write('mkdir -p folder\n')
stream.write('do something')
stream.pipe(process.stdout)
```
if it's possible how to implement it in this code ?

```javascript

var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('uptime', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  privateKey: require('fs').readFileSync('/here/is/my/key')
});
```

**Comment by mscdex** [comment]
You could execute bash, but then you lose reliability when it comes to detecting exit codes and parsing output when executing commands.

If the commands are not directly dependent upon the previous commands (think changing the working directory for example), then using something like the `async` module should work. I'm not sure why you would be getting EventEmitter warnings. Perhaps you might post the code you were trying.

**Comment by wjozefssrf** [comment]
I corrected some lines in async and its work now but i got the problem how to use the sudo password ? by using {pty:true} correct ? but where to put the password ???

```javascript

var cmds = {
    cmd1: 'sudo commande1',
    cmd2: 'sudo commande2',
    cmd3: 'sudo commande3',
    cmd4: 'sudo commande4',
...
};

async.eachSeries(cmds, function iteratee(onecmd, callback) {

           var conn = new Client();
            conn.on('ready', function() { // Authentication was successful.

                console.log('Client :: ready');
                conn.exec(onecmd,{pty:true}, function(err, stream) {

                    if (err) throw err;
                    stream.on('close', function(code, signal) {
                        console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                        conn.end();
                        callback();

                    }).on('data', function(data) {
                        console.log('STDOUT: ' + data);
                    }).stderr.on('data', function(data) {
                        console.log('STDERR: ' + data);
                        
                    });
              });

           }).connect({
                    host: conf.hostname,
                    port: '22',
                    username: conf.username,
                    password: conf.password
            });
```

**Comment by mscdex** [comment]
You have to write to your `exec()` `stream` since `sudo` prompts interactively for the password (you will see it appear on the readable portion of `stream`): `stream.write('password\n')`.

Another option to avoid having to write the password is to add your user to the sudoers list for that particular command such that no password is required to execute that command via `sudo`.

**Comment by wjozefssrf** [comment]
Thanks for your help it should be after 

 ```javascript
....
.on('data', function(data) {
console.log('STDOUT: ' + data);
....
```
So the code become

 ```javascript
var cmds = {
    cmd1: 'sudo commande1',
    cmd2: 'sudo commande2',
    cmd3: 'sudo commande3',
    cmd4: 'sudo commande4',
...
};

async.eachSeries(cmds, function iteratee(onecmd, callback) {

           var conn = new Client();
            conn.on('ready', function() { // Authentication was successful.

                console.log('Client :: ready');
                conn.exec(onecmd,{pty:true}, function(err, stream) {

                    if (err) throw err;
                    stream.on('close', function(code, signal) {
                        console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                        conn.end();
                        callback();

                    }).on('data', function(data) {
                        console.log('STDOUT: ' + data);
                        stream.write('password\n')
                    }).stderr.on('data', function(data) {
                        console.log('STDERR: ' + data);

                    });
              });
           }).connect({
                    host: conf.hostname,
                    port: '22',
                    username: conf.username,
                    password: conf.password
            });
```

**Comment by mscdex** [comment]
Yes that looks about right, although you don't need to create and tear down a new connection for every command, you could reuse the same connection and only disconnect after the last command.

**Comment by wjozefssrf** [comment]
thank you i will do it and im glad to know more about any other suggestions for optimizing the code

**Comment by mscdex** [comment]
There are many ways to go about it of course. Since you're still performing one command per connection, you could perform the commands in parallel (perhaps up to some concurrency limit -- which `async` does support). Other than that, reusing ssh connections and/or modifying the sudoers are about the only other optimizations that you could really take advantage of in this case.

**Comment by wjozefssrf** [comment]
how can i reuse the ssh connections ?

**Comment by wjozefssrf** [comment]
thank you for the suggestions , but i cant use async parallel because the client server has limit on the number of connections that i can make simultaneously " MaxStartups " and even i cant change the sudoers " security policy " , thank you again for your help and i wish give it back
