### ISSUE TITLE
Question: Executing global modules?

### ISSUE THREAD

**Issue by vernak2539** [mscdex/ssh2#481]
I've been trying to execute commands of global modules. Examples being npm and pm2. Both are installed on the host.

I've tried all of the following commands, but none have worked. When logging into the machine, these commands work

`npm install --production`, `pm2 start`, `$(which pm2) start`

Errors: 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: bash: npm: command not found
```

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: bash: pm2: command not found
```

**Comment by mscdex** [comment]
Are you executing them via `.exec()`? If so, most servers do not execute the user's shell init scripts (e.g. `.bash_profile`/`.bashrc`) when executing commands via `.exec()`. You will need to call those scripts manually if your `$PATH` is being modified there.

**Comment by vernak2539** [comment]
I am using `.exec`, sorry I didn't include that. Thanks for the info, I'll try that and report back

**Comment by vernak2539** [comment]
Great, that worked. Thanks @mscdex
