### ISSUE TITLE
Server banner

### ISSUE THREAD

**Issue by medecau** [mscdex/ssh2#486]
Server banner is not being displayed to clients.
I can see it if I use the `-v` flag:

    debug1: ssh_exchange_identification: XXX SERVER BANNER XXX
    
    
    debug1: Remote protocol version 2.0, remote software version XXX SERVER IDENT XXX
    debug1: no match: XXX SERVER IDENT XXX

I'm not sure If I am doing something wrong or fi this is the expected behaviour.

I'd like to be able to send some text before prompting users for login information.

**Comment by mscdex** [comment]
This should be fixed now. Just re-install `ssh2`.

**Comment by medecau** [comment]
Confirmed.
Thank you.
