### ISSUE TITLE
ssh2 doesn't work for ipv6 host address

### ISSUE THREAD

**Issue by devdil** [mscdex/ssh2#487]
I was trying to connect to a ipv6 address from my host.
It failed with error:
ERROR: connect EINVAL

**Comment by mscdex** [comment]
Do you have a network interface with a valid IPv6 address?

**Comment by mscdex** [comment]
Also, if you pass the IPv6 address string to `require('net').isIP()` in a repl, what is the result?

**Comment by devdil** [comment]
yeah it does have a valid network interface with valid ipv6 address, the
ipv6 referred here is the host i m trying to connect to
I also tried address%eth0 as the host string but didn't work.

**Comment by mscdex** [comment]
What result do you get when calling `isIP()` on the address?

**Comment by devdil** [comment]
returns 6 . Is this library tested for ipv6 as well?

**Comment by mscdex** [comment]
It should be transparent.

What version of node is this?

Does connecting to the IPv6 address with the OpenSSH client work?

**Comment by devdil** [comment]
yeah connecting via open ssh works

**Comment by mscdex** [comment]
Node.js version?

**Comment by devdil** [comment]
node verison is : 6.7.0

**Comment by mscdex** [comment]
Is the IPv6 address you're trying to connect to a link-local address (starts with fe80::)?

**Comment by devdil** [comment]
correct its a link local address

**Comment by mscdex** [comment]
For link-local addresses you will probably need to append the interface name, like: fe80::2acf:daff:fedd:342a%eth0

**Comment by devdil** [comment]
tried that too, reports same error

**Comment by devdil** [comment]
is it tested for ipv6 as well?

**Comment by mscdex** [comment]
As previously stated there are no explicit IPv6 tests because node handles that, not `ssh2`.

FWIW I just tried this locally and it worked for me when I appended a `%` and then the network interface name the connection should be routed through to the end of the IPv6 address.

**Comment by devdil** [comment]
did you pass this string (ipv6%interface)as a hostname?

**Comment by mscdex** [comment]
Yes, like the example link-local address I mentioned earlier.

**Comment by devdil** [comment]
could you paste the code snipped you used just now?

**Comment by mscdex** [comment]
There is nothing special about the code, you can use any of the examples in the readme. The only change from those examples is the `host` config value, which is the IPv6 address followed by `%` and the network interface name the connection should go through.

**Comment by mscdex** [comment]
If adding that extra part after the IPv6 address does not work for you, and you are sure you have the correct network interface name, then you might need to post an issue to the node.js issue tracker.

**Comment by devdil** [comment]
thanks a lot  Brian ,,, i will try and close this

**Comment by devdil** [comment]
I tried with this code:
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('uptime', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: 'fe80:0:0:0:9f18:e22a:e52e:1ae6%eth0',
  port: 22,
  username: 'root',
  password:'hpvse1'
});


but it reported with following error:
Error: connect EINVAL
    at errnoException (net.js:901:11)
    at connect (net.js:764:19)
    at net.js:842:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by mscdex** [comment]
Do you have a network interface named 'eth0'?

**Comment by devdil** [comment]
Yes I do have

**Comment by mscdex** [comment]
Out of curiosity, try this little code example and see if you get the same error:

```js
require('net').connect(22, 'fe80:0:0:0:9f18:e22a:e52e:1ae6%eth0').on('connect', function() {
  console.log('Connected');
  this.end();
});
```

**Comment by devdil** [comment]
same error

**Comment by mscdex** [comment]
I would say submit an issue on the node.js issue tracker then. You will probably want to post that minimal code example in the issue (the one that I just posted).

**Comment by devdil** [comment]
but I still wonder how you are able to connect to your machine with same
ipv6 address

**Comment by devdil** [comment]
wouldn't the code snippet you sent require a private key or password field
in the arguments sent across ?

**Comment by mscdex** [comment]
This last code snippet I posted is just to test the IPv6 connectivity, which is the issue here. If you cannot connect to the server, then there's no point in worrying about authentication or anything else.

**Comment by devdil** [comment]
raised a new issue : https://github.com/nodejs/node/issues/9441 and cc'd you

**Comment by devdil** [comment]
tested and is working fine now with node version v 6.7.0
Thanks
