### ISSUE TITLE
i can't listen any event but 'open' after writing a sftp.createWriteStream

### ISSUE THREAD

**Issue by legolasNg** [mscdex/ssh2#489]
````javascript
var stream = sftp.createWriteStream(remotePath, { flags: 'w', encoding: 'utf-8', autoClose: false});
stream.on('error', function () {
    sftp.end();
    callback(null, 'Client ' + serverObj.host + ':: finish ' + remotePath);
});
stream.on('close', function () {
    sftp.end();
    callback(null, 'Client ' + serverObj.host + ':: finish ' + remotePath);
});
var buffer = new Buffer(fileData, 'utf-8');
stream.write(buffer);
````

Did the sftp have ended the stream or removed the listener?

**Comment by mscdex** [comment]
What events are you expecting? You're just performing a single write and not ending the stream, so you won't see `'close'` or `'finish'`.

**Comment by legolasNg** [comment]
how can i know whether or not the single write has finished?

**Comment by mscdex** [comment]
Just like with node's `fs` streams, you can pass a callback function to the `write()` method. That callback is called once that particular write has actually completed.

**Comment by mscdex** [comment]
Also, you don't need to explicitly create a Buffer before calling `write()`, you should be able to do this:

```js
stream.write(fileData, 'utf8', function(err) {
  if (err)
    console.log('Uh oh, an error: ' + err.stack);
  else
    console.log('Write finished');
});
```

**Comment by legolasNg** [comment]
thank you sincerely!
the mannual of node-ssh2 and sftp just is too little.

**Comment by mscdex** [comment]
FWIW the [sftp API](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md#sftpstream-methods) was designed to mimic node's `fs` module to be as identical as possible, so if in doubt, there is always [that documentation](https://nodejs.org/docs/latest/api/fs.html) as well.

**Comment by legolasNg** [comment]
how can i read data from ReadStream ? just like this api, rather than listen 'data' event: 
```js
stream.write(fileData, 'utf8', function(err) {
  if (err)
    console.log('Uh oh, an error: ' + err.stack);
  else
    console.log('Write finished');
});
```
