### ISSUE TITLE
something wrong when i use fastGet

### ISSUE THREAD

**Issue by zhangwilling** [mscdex/ssh2#493]
enviroment: mac os
nodejs-version: 6.2

```
sftp.fastGet('/home/testSSH2/test.txt','/Users/zhangweilin/',{},function(error){
	if(error) throw error;
	console.log('download done!');
});

```
throw error!

Error: EISDIR: illegal operation on a directory, open '/Users/zhangweilin/'

i don't know why

**Comment by mscdex** [comment]
Add a filename: `''/Users/zhangweilin/test.txt''`

**Comment by zhangwilling** [comment]
i found this problem and wanna to close this issue, but you have given me the answer. Anyway, thx a lot!
