### ISSUE TITLE
Help with getting ssh to fire of an event that will send notifications to irc that it is connected

### ISSUE THREAD

**Issue by paladox** [mscdex/ssh2#496]
Hi I'm wondering if you could help me please?

I am trying to get ssh2 to tell irc to send a comment when it is connect (only when connected and successfully connected to the gerrit stream-event)

See https://gerrit.wikimedia.org/r/#/c/320214/2/src/relay.js

please?

**Comment by mscdex** [comment]
There's lots of possible solutions for this. A really simple one would be to just emit a custom event on `sshConn` (inside your `.exec()` callback, if `err` is not set) and add an event handler for that event using `sshConn.once()` inside your irc message handler, after your optional call to `.end()`.

**Comment by paladox** [comment]
Oh, how do I do the custom event in sshConn please?

**Comment by joeyhub** [comment]
This seems like a hand holding exercise.

The simplest approach:

Make a global EventEmitter, after ssh_connected = true; should emit an irc connected event. IE. em.emit('ssh_connected');

After irc_connected = true; you want to register a callback there to the connected event on your emitter. IE. em.on('ssh_connected', function() {ircClient.getItDone();});

In a more structured setup though you might encapsulate SSH/IRC client and then have a module or class that contains one or more of each.
