### ISSUE TITLE
'close' event not triggering unless 'data' listener is defined

### ISSUE THREAD

**Issue by D7Torres** [mscdex/ssh2#498]
I am using ssh2 to execute a `touch myFile` command, a command that does not return data. The command is correctly executed. However, the 'close' event is no longer triggered since I updated ssh2 (from 0.4.11 to 0.5.4).

After adding the 'data' listener, the 'close' event is called again. Even if the 'data' event is not being triggered. This is what I added to make the 'close' event to work again:

```
stream.on('data', function(data) {
    console.log('This is not being printed out');
});
```

**Comment by soyuka** [comment]
Had the same problem here:

```
  let promise = new Promise(function(resolve, reject) {
    conn.on('ready', function() {
      conn.exec(`mkdir -p ${location.path}`, function(err, stream) {
        if (err) {
          return reject(err)
        }

        stream.on('end', function(code, signal) {
          conn.end()
          return resolve()
        }).on('data', () => {}) //without data event listener, no end?
      })
    })
    .on('error', function(err) {
      reject(err)
    })
  })
```

**Comment by mscdex** [comment]
I believe this is just a normal "feature" of node streams in general. If you don't care about the output, you can always do `stream.resume()` (and possibly `stream.stderr.resume()`).

**Comment by D7Torres** [comment]
What if you don't care about the output but you want to know when it has finished.

**Comment by mscdex** [comment]
@D7Torres If you don't want to explicitly discard the stream, then there is always the 'exit' event (much like node's `child_process`'s `'exit' event.
