### ISSUE TITLE
RangeError: length > kMaxLength when trying to SFTP a big file

### ISSUE THREAD

**Issue by vdudouyt** [mscdex/ssh2#499]
I'm getting the following issue when trying to get a file with SFTP:

$ nodejs test_sftp.js 

buffer.js:194
      this.parent = new SlowBuffer(this.length);
                    ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at tryStat (sftp.js:1219:16)
    at SFTPStream._transform (sftp.js:496:15)

But with small files, it's working fine. Could you let me know how can I overcome this issue and, if it's possible, show me an example?

I have already tried googling, but found only the similar questions and no answers

Thanks

**Comment by mscdex** [comment]
Can you show your code?

**Comment by vdudouyt** [comment]
Yes, sure:

var Client = require('ssh2').Client;
var client = new Client;

client.connect({
	host: 'localhost',
	port: 22,
	username: 'myuser',
	password: 'mypass',
});

client.on('ready', function() {
   client.sftp(function(err, sftp) {
	   sftp.readFile('/storage/1gb.bin', {}, function(err, buffer) {
	      console.log(buffer);
	   });
   });
});

**Comment by mscdex** [comment]
Just like with node's `fs.readFile()`, the `sftp.readFile()` function buffers the entire file into memory. You won't be able to do that with such really large files.

Depending on your needs, you could use `sftp.fastGet()` to download a file directly to local disk or you could use (the slower) `sftp.createReadStream()` which gives you a node Readable stream that you can pipe to anywhere you want.

**Comment by vdudouyt** [comment]
Nuts, I really wasn't realizing that it loads the whole file into memory :/

Yes, sftp.createReadStream() is working fine. Thank you very much!
