### ISSUE TITLE
Call back error not working with invalid password. 

### ISSUE THREAD

**Issue by jsirney** [mscdex/ssh2#501]
The SSH2 works correctly with a valid password. If I invalidate the password the call back does not work correctly. 
Code:
      var ssh2Conn = new Ssh2Client();
      ssh2Conn.on('ready', function() {
      console.log('Client :: ready');
      ssh2Conn.shell(function(err, stream) {
        if (!err) -- the breakpoint is not hit with invalid password. break point hits with valid password. 

if the password is 1234Pass and I send 1234Pas it fails as above.  

node version: v6.7.0
npm version: 3.10.3
ssh2 README - 
[Changes from v0.3.x-v0.4.x](https://github.com/mscdex/ssh2/wiki/Changes-from-0.3.x-to-0.4.x)

STACK TRACE:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at tryNextAuth (c:\MCS\mcs-server\node_modules\ssh2\lib\client.js:294:17)
    at SSH2Stream.onUSERAUTH_FAILURE (c:\MCS\mcs-server\node_modules\ssh2\lib\client.js:473:5)
    at emitTwo (events.js:106:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (c:\MCS\mcs-server\node_modules\ssh2-streams\lib\ssh.js:3647:10)
    at SSH2Stream._transform (c:\MCS\mcs-server\node_modules\ssh2-streams\lib\ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (c:\MCS\mcs-server\node_modules\ssh2-streams\lib\ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)

Error in code execution 
level:"client-authentication"
message:"All configured authentication methods failed"
stack:"Error: All configured authentication methods failed\n    at tryNextAuth (c:\\MCS\\mcs-server\\node_modules\\ssh2\\lib\\client.js:294:17)\n    at SSH2Stream.onUSERAUTH_FAILURE (c:\\MCS\\mcs-server\\node_modules\\ssh2\\lib\\client.js:473:5)\n    at emitTwo (events.js:106:13)\n    at SSH2Stream.emit (events.js:191:7)\n    at parsePacket (c:\\MCS\\mcs-server\\node_modules\\ssh2-streams\\lib\\ssh.js:3647:10)\n    at SSH2Stream._transform (c:\\MCS\\mcs-server\\node_modules\\ssh2-streams\\lib\\ssh.js:551:13)\n    at SSH2Stream.Transform._read (_stream_transform.js:167:10)\n    at SSH2Stream._read (c:\\MCS\\mcs-server\\node_modules\\ssh2-streams\\lib\\ssh.js:212:15)\n    at SSH2Stream.Transform._write (_stream_transform.js:155:12)\n    at doWrite (_stream_writable.js:307:12)"
__proto__:Error {name: "Error", message:

**Comment by mscdex** [comment]
You have to add an `'error'` event handler on the connection object.

**Comment by jsirney** [comment]
OK, that did the trick. 
Guess I need to look at the How do section. 

    ssh2Conn.on('error', function(err) {
    console.log('Connection :: error :: ' + err);
  });
