### ISSUE TITLE
Closing shell sessions

### ISSUE THREAD

**Issue by mofux** [mscdex/ssh2#504]
Hi Brian,

first of all, thanks for providing this lib and your great support throughout all the years. I am watching many projects on github, but yours stands out because of your continuous support and your technical vision for this project. 

I am using a single connection to establish multiple shell sessions through it. After opening 9 or 10 of them, I get an error (`ADMINISTRATIVELY_PROHIBITED`), which is totally expected because this seems to be the OpenSSH server's limit for concurrent sessions through the same connection.

Now, if I want to close a shell session, I run `stream.end()` on the shell stream. This seems to terminate the ssh channel, but leaves the actual shell session idle, so any subsequent attempts to launch a new shell session will still throw `ADMINISTRATIVELY_PROHIBITED`. The problem I am having is that I cannot simply run `stream.end("exit\n")` (which does indeed end the current shell session immediately) because I cannot know in which state the session is currently. Maybe there is a nano editor open at the time of closing the session, so the command would just be written into the editor. 

Can you think of any other way to reliably close the actual session? (I'm hoping the designers of the shell subsystem have thought about this case)

**Comment by mscdex** [comment]
What about `stream.close()` instead of `stream.end()`?

**Comment by mofux** [comment]
Yes, that's working! It might be worth to mention the `close` method in the docs as it seems favourable over `end`, at least for the shell streams.
