### ISSUE TITLE
Several exec's at the same time

### ISSUE THREAD

**Issue by shaleynikov** [mscdex/ssh2#505]
Hello,

I'm developing an app which handles multiple connections to various servers, using ssh2 in 'exec' mode, not 'shell'.

After adding a bit of load I see 'ADMINISTRATIVELY_PROHIBITED' errors to pop up. I assume it's due to restrictions of a number of simultaneous sessions (MaxSessions sshd config value, which is 10 by default).

Is there an effective way of controlling number of opened sessions from a client?

The code I'm using to test this behaviour is the following:

```
var sshManager = require('./sshManager');
var _ = require('lodash');

describe('10+ commands at the same time should work one by one', () => {
  it("should do fine with multiple running commands", (done) => {
    setTimeout(() => {
      sshManager.getConnection().then((conn) => {
        console.log("connection reserved");
        var bombCmd = 'sleep 5';
        var numOfCmd = 15;
        _.times(numOfCmd, (i) => {
            conn.execAsUser(bombCmd, (err, stream) => {
              if ( err ) { console.error(err); return; };
              console.log("command " + i + " executed");
              stream.on('close', () => {
                console.log("command " + i + " delivered");
                if ( i == numOfCmd - 1 ) {
                  conn.execAsUser(bombCmd, () => {
                    console.log("last command delivered");
                    done();
                  });
                }
              })
            });
        });
        console.log("session bomb sent");
      });

    }, 7000)
  })
})
```

I put the output there 
https://gist.github.com/shaleynikov/8c9681224b11bf9e3df76bb421bd9855

**Comment by mscdex** [comment]
Pretty much any action uses a single session/channel: `exec()`, `shell()`, `sftp()`, `forwardOut()`, etc.

The server limit is only for concurrent sessions, so you just have to monitor how many active `exec()`, `shell()`, `sftp()`, etc. actions you have at any given time.

**Comment by shaleynikov** [comment]
Is there any api allowing me to subscribe to channel create/destroy events?

**Comment by mscdex** [comment]
There is no public API for that.
