### ISSUE TITLE
Using the ssh-agent protocol

### ISSUE THREAD

**Issue by danielepolencic** [mscdex/ssh2#506]
I tried to look for an answer in the closed issues but I couldn't find anything relevant.

Is it possible to implement an ssh-agent on top of this library?

I'd like to have my own ssh-agent so that I can load private keys on demand from a keepass file. This is very similar to what [KeeAgent](http://lechnology.com/software/keeagent/) offers at the moment.

Does ssh2 support the ss-agent protocol?

**Comment by mscdex** [comment]
For *nix, as long as you have some server listening on a unix socket that speaks the [agent protocol](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/PROTOCOL.agent?annotate=HEAD), you can use it with `ssh2` via the `agent` connection configuration property.

**Comment by danielepolencic** [comment]
> For *nix, as long as you have some server listening on a unix socket that speaks the agent protocol

ssh2 in server mode can do that?

**Comment by mscdex** [comment]
I thought you were referring to using it with a client. For server there is no such support currently.

**Comment by danielepolencic** [comment]
Thanks
