### ISSUE TITLE
Using a single connection for forward and reverse tunnels

### ISSUE THREAD

**Issue by nikhilk** [mscdex/ssh2#507]
Is it possible to implement this using ssh2?

    ssh -N \
      -L localPort:127.0.0.1:remotePort \
      -R remotePort2:127.0.0.1:localPort2 \
      -i keyfile user@host

I've looked at various issues and forwardIn/Out methods, and being new to this its unclear if I can combine both directions on the same SSH connection. Can someone confirm yes?

If there is a sample doing so that I can use to grok the mechanics of this, even better.
Thanks!

**Comment by mscdex** [comment]
`-L` is equivalent to `forwardOut()`, `-R` is equivalent to `forwardIn()`, `-i` is equivalent to setting `privateKey` in `connect()`. There are examples of each of these in the readme.
