### ISSUE TITLE
How to transfer a file over sftp?

### ISSUE THREAD

**Issue by G047** [mscdex/ssh2#510]
I'm using this sample code
`			conn.once('ready', function() {
				console.log('SSH_Connection')
			})
			conn.connect({
			  host: '192.168.1.24',
			  port: 22,
			  username: user,
			  password: pass
			})`

There doesn't seam to be any documentation to upload a file to the remote server, [this](https://www.npmjs.com/package/node-ssh) library has the `putFile` function that does it. The library is also a wrapper for ssh2 so it should be possible to do the same.

**Comment by mscdex** [comment]
There is an [`sftp()` method](https://github.com/mscdex/ssh2#client-methods) that starts an SFTP session. In the linked documentation there is a link to the various SFTP methods.
