### ISSUE TITLE
Color Console

### ISSUE THREAD

**Issue by nitishrai** [mscdex/ssh2#512]
Hi sir,
Can u tell how to spawn a color terminal and to open tty of specfic size currently i am unable pass conn.shell({option}). If i am doing wrong can u tell me the exact way

**Comment by mscdex** [comment]
The first argument to `shell()` can be an object containing [pty settings](https://github.com/mscdex/ssh2#pseudo-tty-settings) as noted in the documentation. Example:

```js
conn.shell({ term: 'xterm-256color', rows: 48, cols: 160 }, function(err, stream) {
  // ...
});
```

**Comment by nitishrai** [comment]
i got the desired number of rows but didn't get the color terminal ...

**Comment by nitishrai** [comment]
is there way to dynamically set the rows and coloumn value ? according to the screen size?

**Comment by mscdex** [comment]
For `shell()`, there is a [`setWindow()`](https://github.com/mscdex/ssh2#channel) that you can use to dynamically notify the server of window size changes. You can get notifications of tty dimensions changing (provided stdout is a tty) by listening on the [`'resize'` event](https://nodejs.org/docs/latest/api/tty.html#tty_event_resize) on `process.stdout`. `process.stdout` also has `columns` and `rows` properties so you can get the current values.

As for the color, it works for me so I'm not sure why it wouldn't be working for you. Perhaps the server does not support the terminal type you've set? If I connect to an Ubuntu server for example, the terminal type `'xterm-256color'` works there and I can execute the `colortest-256` command (provided the `colortest` package is installed on the server beforehand) and it displays all 256 colors.

**Comment by nitishrai** [comment]
confused can u provide sample for setWindow() ?

**Comment by mscdex** [comment]
The link I provided gives an example:

```js
process.stdout.on('resize', () => {
  console.log('screen size has changed!');
  console.log(`${process.stdout.columns}x${process.stdout.rows}`);
});
```

**Comment by mscdex** [comment]
@nitishrai That's something you'd have to set up on the server (e.g. chroot).

**Comment by nitishrai** [comment]
No sir suppose I have a directory A that contain 50 directory AA,AB.... now I want to assign a directory AA to a user at shell console without creating users such that when the shells open the user would be in the desired directory but when user try to change directory he would not be able to that. Means he can traverse the directory AAA,AAB but can't traverse AB,AC,.. so on

**Comment by mscdex** [comment]
As long as the user is able to enter any arbitrary command line into the shell session, you're not going to be able to limit this without changes on the server.

**Comment by nitishrai** [comment]
Ok sir

**Comment by nitishrai** [comment]
Hi sir, there is a think i need to ask you , sir i have a list of approx 10 servers ssh login now i want real time ram usage how i should i achive this ? will websocket be a good idea and if yes then in your conn.shell(function(err,stream)) how should i parse the strem data to the nodejs ?

**Comment by wdavidw** [comment]
you can used websocket and HTTP push between you're nodejs application and the web client but not between your remote server and your nodejs application. You'll have to pull that information periodically with a shell command:

```
[web client] <<< push <<<< [app] >>> pull >>> [remote node]
```

You nodejs application might look like (not tested but that shall give you an idea):

```js
io = require('socket.io')(80);
Client = require('ssh2').Client;
eacho = require('each');
connections = [];
each([server1, server2])
.call( function(server1, callback){
  conn = new Client();
  conn.on('ready', function() {
    connections.push(conn);
  }).connect({...});
})
.then(function(){
  setInterval(function(){
    for(connection in connections){
      connection.exec('cat /proc/meminfo', function(err, stream) {
        if (err) throw err;
        stream.on('data', function(data) {
          io.emit(connection.config.host, data);
        }).stderr.on('data', function(data) {
          io.emit(connection.config.host, data);
        });
      });
    }
  }, 5000);
});
```
