### ISSUE TITLE
My nodejs app never exit while executing on a remote linux box a bash script that spawn background processes

### ISSUE THREAD

**Issue by lukka** [mscdex/ssh2#513]
- Using MacOS 10.12 (but reproduced it on Windows 10 as well);
- I exec() on a remote Linux machine a bash script (as shown below) that starts background processes;
- I am using the a nodejs app to reproduce it, using ssh2 v0.5.0;
- My nodejs app never exit, I need to kill explicitly the background process started by the script in order to make it exit;
- OTOH, if I explicitly call  `clientSsh.end()` in the 'exit' handler of my app, then the app properly exit.

**Question**: is calling clientSsh.end() on the  'exit' event required? Or has my simple app any flaw?

Bash script that spawn a background process:
```
#!/bin/bash
echo "starting"
/Users/username/tmp/a.out &disown
disown -a
echo "terminating"
exit 0

```

SSH2 nodejs based app to reproduce the issue:

```js
var YOURUSERNAME="..."
var YOURPWD="..."
var SCRIPTPATH='/Users/username/tmp/x.sh'
//######################
var sshConfig = {
 hostname:"localhost",
 port:"22",
 username:YOURUSERNAME,
 password:YOURPWD,
 debug: console.log
}


function test(sshClient)
{
    return sshClient.on('ready', function testDisown()
      {
          sshClient.exec(SCRIPTPATH, (err, stream) => {
        if (err) {
            console.log('err='+err);
            throw err;
        }

        stream.on('exit', (code, signal) => {
          console.log('exit: code=' + code + ', signal= ' + signal);
          //sshClient.end();//<<<<==== WITHOUT THIS STATEMENT IT WILL NEVER EXIT!
        });
        stream.on('close', (code, signal) => {
            console.log('close code = ' + code + ', signal = ' + signal);
            if (code && code != 0) {
                throw 'errr';
            }
            else {
              console.log("execution 0");
              sshClient.end();
            }
        });
        stream.on('data', (data) => {
            var msg = "stdout="+data;
            console.log(msg.substring(0,10));
        });
        stream.stderr.on('data', (data) => {
            console.log('stderr = ' + data);
        });
      });
      }
  );
}


console.log("Hey starting up a node app ...");
var Ssh2Client = require('ssh2').Client;
var client = new Ssh2Client();
test(client).connect(sshConfig);

```

a.out source code is just this silly C code:
```
#include <unistd.h>
#include <stdlib.h>

int main()
{
while(1)
{
for(int i = 0; i < 450; i++)
  printf("hello world\n");
  sleep(3);
  }
}

```

**Comment by lukka** [comment]
is my issue clear? Or is it not an issue? :)

**Comment by mscdex** [comment]
`disown` does not disconnect the process from the tty and `'close'` (like node's child process's `'close'` event) is only emitted once the stdout/stderr streams are closed, which happens *after* the process has exited. So while you may have placed it in the background and the shell script exited with 0, the `a.out` process is still connected to the shell's stdout/stderr. You may consider use `nohup` or something similar instead to redirect the process's streams elsewhere so that the main process (shell script in your case) can *actually* end.
