### ISSUE TITLE
"su" when logged in as "root" causes timeout

### ISSUE THREAD

**Issue by dsgill** [mscdex/ssh2#514]
I have been able to use ssh2 successfully to execute multiple commands with the exception of one. If I am logged in to the system as root and try to su to a known user, I get the following error:
     Error: function timed out after 5000 milliseconds
         at Timeout.<anonymous> (/usr/lib/node_modules/cucumber/lib/user_code_runner.js:51:28)
         at tryOnTimeout (timers.js:232:11)
         at Timer.listOnTimeout (timers.js:202:5)
I am able to execute this command manually on the same system via manual ssh connection. So I must be missing something in the setup of my connection with ssh2. Any ideas?

**Comment by mscdex** [comment]
Can you provide a reproducible example that uses just `ssh2`?

**Comment by dsgill** [comment]
This is the routine that uses ssh2. As it is, it will get that error. But if I remove only the 'su dgillespie', it succeeds.

var check = function(system, uname, pword, callback) {
    var config = {
      host: system,
      port: 22,
      username: uname,
      password: pword,
//      debug: console.log
    }
    var commands = [
        'su dgillespie',
        'ls -al /mysystem/logs/current',
        'pwd',
        'ls -al'
    ];
    var ssh = new Client(config);
    ssh.exec(commands)
        .then(function() {
            console.log("All done!");
            callback();
        })
        .catch(function(err) {
            console.log("Got error!");
            throw err;
        })
        .done();         
};

**Comment by mscdex** [comment]
It looks like you're using some other module (which may/may not be used `ssh2` underneath), since `ssh2` does not allow an array of commands nor does it use Promises.

Besides that, perhaps `su` is prompting for a password? If so, that would probably be why it's timing out because no password is being entered.

**Comment by dsgill** [comment]
Oh sorry! I'm using ssh-promise which is a wrapper for ssh2. It's not prompting for a password; I know because I can do the same thing from a manually established ssh session and no password is required.

**Comment by mscdex** [comment]
But did you verify that is the case by logging stdout and stderr from the command when doing it programmatically?

**Comment by dsgill** [comment]
All I did was use debug:console.log. Is there a different way to log those?

**Comment by dsgill** [comment]
Ok, I logged stdout & stderr to a file from that command: 'su dgillespie >out 2>&1'. The file out was created and was empty. To me that means it's not prompting for a password.

**Comment by mscdex** [comment]
Ok, are you able to duplicate the issue using `ssh2` directly, to rule out any issues with `ssh-promise`?

**Comment by dsgill** [comment]
I eliminated ssh-promise and here is the version of the code using just ssh2. I get an identical result. If the command I exec is "ls -al" it succeeds. If it is "su <account>" it times out exactly the same way.

var Client = require('ssh2').Client;

var checkSsh2 = function(system, uname, pword, callback) {
    var conn = new Client();
    conn.on('ready', function() {
        console.log('Client :: ready');
        conn.exec('su xshen', function(err, stream) {
            if (err)
                throw err;
            stream.on('close', function(code, signal) {
                console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                conn.end();
                callback();
            }).on('data', function(data) {
                console.log('STDOUT: ' + data);
            }).stderr.on('data', function(data) {
                console.log('STDERR: ' + data);
            });
        });
    }).connect({
        host: 'a8.qa.footprint.net',
        port: 22,
        username: uname,
        password: pword,
    });
};

**Comment by mscdex** [comment]
I don't know what to tell you then. I tried it locally and it works just fine for me, although I had to allocate a pty (adding `{ pty: true }` as the second argument to `exec()`) to avoid the 'su: must be run from a terminal' error that normally gets printed to stderr.

**Comment by dsgill** [comment]
I added the {pty: true} to my exec call and it got farther. I actually got an STDOUT print from ssh2:

Client :: ready
STDOUT: $

The $ is the prompt the user receives after a successful su, so this time the su worked. After that it still times out. It looks like it's waiting for something to be typed, like it's interactive, but the $ is the same thing I get when I su manually. Am I unintentionally making this an interactive connection? Or is there some other setting that might terminate the su properly?

**Comment by mscdex** [comment]
Right, with just plain `su username`, it will act as if you had logged in as that user, so if the user has a shell (e.g. bash) set up on their account, it will start it (and that's what you're seeing). If you just want to execute a particular command as a user, you will need to add the `-c` argument to specify a command, for example: `su -c 'ls -al /mysystem/logs/current' dgillespie`. Be aware though that there is no state between `exec()` calls, so if `ssh-promise` is not implicitly joining all of the commands with `';'` or `'&&'` then you may have to do that manually if you change state, such as changing directories when the following commands depend on that current directory.

**Comment by dsgill** [comment]
Adding a -c option to my su did the trick, By stringing multiple commands together I can get the effect I want. Thank you for your help!
