### ISSUE TITLE
How to properly rate throttle client connections & close them off properly

### ISSUE THREAD

**Issue by developer94404** [mscdex/ssh2#515]
Hello - I have noticed a new, severe issue, that I hope you may kindly help me with.

I have noticed a huge # of hack attempts to the server.  Literally, thousands of username ('root', 'admin') & password attempts per second; so many that, upon my own programmatic simulation, the server can only write 50 log file entries for every 2000 failed connection attempts.

There are 2 issues I would like to ask:

1) How to reject a client super quickly? Something like:

     new ssh2.Server( {privateKey: },
      function(client) {
          
           if (myIpCounter[client._sock_.address] > MAX_ALLOWED_FAILED_LOGINS) {
               // both of these seem to be effectively the same?
               client.end(); 
               //    or 
               client.emit('end');  
               
               // is it safe/ok to immediately return out of this function(client) {} ?
               return;
           }
           
            // rest of typical code for conn.connect(events)

2) Is there a recommended way to rate throttle connecting clients?  Ie, one connection per second, etc.

3) If authentication fails, ie, I call:  ctx.reject([], false),   does this close the current connection with the client, or does the connection stay open, but the client can continue to keep trying new password attempts?

Thanks for any help on this issue!

**Comment by mscdex** [comment]
1. First off, you can access the IP using the object passed as the second argument to your `'connection'` event handler: `function(client, info) { /* info.ip === socket.remoteAddress, info.header contains client-supplied information */ }`. Secondly, `client.end()` *should be* fine. It does end the connection according to the RFC (sending a 'disconnect' message and then closing the socket). Currently there is no public `.destroy()` method for abrupt socket termination.

2. This module does not make any such decisions for you, so how you want to limit connections is entirely up to you. If you want to use a sliding window for connection attempts, there are modules on npm to help you with that. There are other generic throttling modules on npm as well, it just depends on what strategies you want to use.

3. Rejecting an authentication attempt does not close the connection, it just tells the client that that attempt failed. The client is free to try again or disconnect.

**Comment by joeyhub** [comment]
Use a non-standard port if you can.
