### ISSUE TITLE
Different carriage return when using {pty: true}

### ISSUE THREAD

**Issue by Modaphukka** [mscdex/ssh2#517]
Question :
I sent the command 'echo lol' and expected the result 'lol\n' but it returns 'lol\r\n'
 ✖ Failed [equal]: ('lol\r\n' == 'lol\n')

Why when I doesn't mention {pty: true} :
```
conn.exec(command, function(err, stream) {
```
the carriage return is "<somedata>\n" and if I do :
```
conn.exec(command, {pty: true}, function(err, stream) {
```
the carriage return is "<somedata>\r\n" ?

I though it was a Windows carriage return and was not used on Unix ?

**Comment by mscdex** [comment]
Probably because "real" terminals need both: one to explicitly reset the position (`\r`) and the other to go to the next line (`\n`), whereas when there is no "real" terminal (no pty) the resetting of the position is implied with `\n`.

**Comment by Modaphukka** [comment]
Ok, it seems logical, thank you for your fast reply.
