### ISSUE TITLE
How to Log output of commands executed in remote system

### ISSUE THREAD

**Issue by Breme** [mscdex/ssh2#518]
```js
client.on('session', function(accept, reject) {
            var session = accept();
            session.once('exec', function(accept, reject, info) {
                console.log('Client wants to execute: ' + inspect(info.command));
                var stream = accept();
                stream.stderr.write('Oh no, the dreaded errors!\n');
                stream.write('Just kidding about the errors!\n');
                stream.exit(0);
                stream.end();
            });
        });
```
After creating a session, my client code will send commands to be executed to the above code.How to log the output of the commands executed in the Stream from client code.
My client code is
```js
var SSH = require('simple-ssh');

var ssh = new SSH({
    host: 'localhost',
    user: 'foo',
    pass: 'bar',
    port: '55793'
});
ssh
    .exec('ipconfig', {
        out: console.log.bind(console)
    })
    .exec('echo "is"', {
        out: console.log.bind(console)
    })
    .exec('echo "awesome!"', {
        out: console.log.bind(console)
    })
    .start();
```
Kindly help

**Comment by mscdex** [comment]
I don't understand what you're asking. The `ssh2` server doesn't execute any commands (in child processes), you have to do that yourself (e.g. using the `child_process` node core module) if that is what you want to do, and then pipe between the child process's streams and the streams you get from `accept()`. An example of this might look something like:

```js
var spawn = require('child_process').spawn;
// ...
var stream = accept();
var cp = spawn(info.command, { shell: true });
cp.on('exit', function(code, signal) {
  stream.exit(signal || code);
}).on('close', function(code, signal) {
  stream.close();
});
stream.stdin.pipe(cp.stdin);
cp.stdout.pipe(stream.stdout);
cp.stderr.pipe(stream.stderr);
```

However if you're going to blindly start child processes like this, you may want to utilize some protections such as chroot and the like, depending on your needs.

**Comment by Breme** [comment]
Hi Thank you so much,Actually my requirement is I want to create a ssh server in remote PC and fire 5 commands sequentially from client side.Mainly the commands will enter into a CLI mode eg. (XXXcli ip_address) is the first command.then next command will load configuration and so on.The code you have given is working but it only executes the fires command,Please see to that any changes can be made in order to execute all command sent from  client code. Thanks for you help :)

**Comment by mscdex** [comment]
That's because you're only listening for the `'exec'` event once (`.once()`). The default behavior is to reject requests when there are no event handlers for that type of request.

**Comment by Breme** [comment]
Thank you, But I tried `.on()` method instead of `.once()` even though only the first command is getting executed.Should I set timers between each commands or will there be any other problem.

**Comment by Breme** [comment]
Thanks for your help!! Its done!! timeout between each commands is what I missed out :)
