### ISSUE TITLE
SFTP Compression causes error (filezilla)

### ISSUE THREAD

**Issue by joeyhub** [mscdex/ssh2#519]
TypeError: Cannot read property 'length' of null
    at send_ (/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:5280:19)
    at /node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:5260:7
    at afterWrite (_stream_writable.js:354:3)
    at onwrite (_stream_writable.js:345:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:615:5)

The problem is here:

    var compress = outstate.compress.instance;
    if (compress) {
        compress.write(payload);
        compress.flush(Z_PARTIAL_FLUSH, function() {
            if (self._readableState.ended || self._writableState.ended)
                return;
            send_(self, compress.read(), cb);
        });
        return true;
    }

When a lot is written presumably in a loop it gets buffered up. To see it in action you need to send something large over the wire. You can test this with your own sftp sample if you for example just make a directory that returns a large array of made up files to .name() in the response (make it a thousand items).

When it's lots of small (probably intermittent as well) packets it's fine. It will:

1. write(a), flush, read(a)
2. write(b), flush, read(b)

With big packets it seems to result in:

1. write(a), flush, write(b), flush, read(a + b), read()

I didn't look closely but it's most likely that writable is calling before the previous flush command gets to run or something like that.

wrote 27
flush callback [ok]
wrote 27
flush callback [ok]
wrote 27
flush callback [ok]
wrote 153
flush callback [ok]

Versus:

wrote 16393
wrote 16393
wrote 16393
wrote 1834
flush callback [ok]
flush callback [null]

You can just check that read returns null and that should work although I'm not sure what you're actually supposed to do regarding the stream states. In this case the stream wont be ended. It will just be waiting for more data.

Side note, personally in my own implementations using zlib I use Z_SYNC_FLUSH instead. I assume Z_PARTIAL_FLUSH is left here for compatibility though.

Also I guess this should have gone to streams :/.

**Comment by cloudtracer** [comment]
Nice analysis @joeyhub.

I've got the exact same issue with sending large output results to the clients STDOUT.

I fixed the issue by doing the following, don't ask me if this is the right way to do it, but I just figured if the callback will be null, might as well try it again.
```javascript
 if (compress) {
    compress.write(payload);
    compress.flush(Z_PARTIAL_FLUSH, function() {
      if (self._readableState.ended || self._writableState.ended)
        return;
      var compress_read = compress.read();
      if(compress_read == null){
        return send(self, payload, cb, bypass);
      }
      send_(self, compress_read, cb);
    });

    return true;
```

**Comment by mscdex** [comment]
If this is still an issue with `ssh2` v1.0.0 let me know and I can reopen this.
