### ISSUE TITLE
Create *adhoc* ssh agent and use it to ssh from remote1 to remote2

### ISSUE THREAD

**Issue by soichih** [mscdex/ssh2#521]
I see that ssh2 supports agent forwarding. I can use this to ssh from local to remote1 and remote1 to remote2, and so on.. However, if I am using a private key based authentication (and not using ssh-agent locally), then I can't use ssh2 forwardAgent feature because there is no agent to forward to begin with.

Is there a way to 
1) Create an `adhoc` ssh agent (running as part of the same local process that ssh2 is running) from my pub/private keys.
2) Tell ssh2 to use the adhoc agent (instead of process.env.SSH_AUTH_SOCK?)
3) ssh to remote1 using ssh2 as I do normally.
4) ssh from remote1 to remote2 using ssh2's `forwardAgent: true` functionality.

I am not sure if I am making sense.. but I have somewhat of a unique use-case.. I have to manage our user's encrypted ssh private keys stored in our D,B but currently I have to temporary store the passphrase-less private key on remote1 in order to ssh from remote1 to remote2 - and remove it after it's done. If I can create the adhoc agent, then I can eliminate the storing of the key.

**Comment by mscdex** [comment]
What about writing your own ssh agent in node? The protocol is documented on OpenSSH's website and you can look at the agent client code in `ssh2` as a partial guide.

You'll want to take appropriate precautions though so that you do not leave private keys in memory for example. Provided the private key is only ever stored as a Buffer, you should be able to do `buf.fill(0)` to zero out its memory after you are done with it.

**Comment by soichih** [comment]
I just realized that this issue is closely related to #506 

As far as writing my ssh agent goes, I *believe* this package does this already
> https://github.com/131/ssh-agent-js

However, I just realized (learned) that I could do following instead.
1) Run the native ssh-agent under the same user that I am running my nodejs server (root?) Like "ssh-agent -a /root/agent.sock"
2) Use something like https://github.com/joyent/node-sshpk-agent to talk to this agent, and install private keys that I need to use prior to opening connection via ssh2
3) Run ssh2/connect with agent set to "/root/agent.sock"

At the moment, I am wondering what the security implication of this is. I am dealing with multiple user accounts, so sharing a single ssh-agent server means hacker can steal the agent and access my keychain for all other users. I am trying to mitigate this by setting the expiration date of the private key very short and/or removing the key as soon as ssh2 makes connections to remote server.

Soichi

**Comment by mscdex** [comment]
> At the moment, I am wondering what the security implication of this is. I am dealing with multiple user accounts, so sharing a single ssh-agent server means hacker can steal the agent and access my keychain for all other users. I am trying to mitigate this by setting the expiration date of the private key very short and/or removing the key as soon as ssh2 makes connections to remote server.

It's hard to say, but as long as the user permissions on the socket are set appropriately, no other OS user should be able to access your ssh-agent.

Once your keys are loaded into an agent, there is no way to get them back out of that process, so there would be no risk of exposing the private keys themselves, however someone could try using the keys in your agent to connect to servers (provided they know the usernames and addresses of these servers) from the same process/host.

As you mentioned, you can also set lifetimes for keys added to an ssh-agent process. You could also simply only keep the keys in the agent for the duration of the ssh connection handshake (add right before connect and then remove once authentication has succeeded/failed).

However, a better idea might be to have separate agents to avoid any potential problems in a mixed user environment.
