### ISSUE TITLE
keyboard-interactive failing for no apparent reason

### ISSUE THREAD

**Issue by cnsumner** [mscdex/ssh2#522]
I have a linux host set up that I routinely connect to through PuTTY using keyboard-interactive method, and I've been messing around with making my own ssh terminal client in electron.

I'm using pretty standard stuff here:

```
var ssh_client = require('ssh2').Client;
var conn = new ssh_client()

conn.connect({
  host: '192.168.1.103',
  port: 22,
  username: 'pi',
  tryKeyboard: true,
  readyTimeout: 99999999,
  debug: console.log
})
```

I didn't include my `on('keyboard-interactive', function)` bause here's the weird part: it never gets there.

As you can see, I turned on debug logging and I get this: 

```
DEBUG: Outgoing: Writing USERAUTH_REQUEST (keyboard-interactive)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
Client: keyboard-interactive auth failed
```

I also turned on verbose logging on the host's sshd service and get this:

```
Set /proc/self/oom_score_adj to 0
Connection from 192.168.1.100 port 1990 on 192.168.1.103 port 22
Received disconnect from 192.168.1.100: 11:  [preauth]
```

No other info or errors show up anywhere. It just disconnects without ever firing the `keyboard-interactive` event.

If you want to see any other code let me know, but like I said, none of my other code ever executes (I put in debug statements, breakpoints, you name it. Nothing.).  Also, I tried simple user/pass authentication and it works flawlessly, so I know it's just something to do with the keyboard-interactive auth method (and yes, my callback has all the correct parameters).

I hate putting these kinds of problems in "Issues" on a repo, because this is probably my fault and not your library, but I don't know where else to ask.

Hope someone can offer some insight!

**Comment by mofux** [comment]
I think you have to add the keyboard-interactive listener, otherwise it will be rejected immediately. I got it working just fine, using the latest ssh2 version.

**Comment by cnsumner** [comment]
I am using the latest version of ssh2, and I do have it defined:

```
conn.on("keyboard-interactive", function listener(name, instructions, lang, prompts, finish) {
    console.log('keyboard-interactive user input begin')
    answers = answers || [];
    if (answers.length < prompts.length) {
        rl.question(prompts[answers.length].prompt, function(answer) {
            answers.push(answer);
            redo(name, instructions, instructionsLang, prompts, finish, answers)
        });
    } else
        finish(answers);
})
```

Can you see anything wrong with that?  I don't actually know if the code inside for getting user input works, because it's never reached that code, but I have tried simply passing a hard-coded answers array, since I know exactly what prompts my host will give me.

**Comment by mofux** [comment]
Not sure what your redo function does, but instead of calling redo, you should probably be calling finish(answers) or replace "redo" with "listener" because listener is the name of your callback function

**Comment by cnsumner** [comment]
You're right, that code would have failed (I had adapted some example code to try and fix the problem), but again the reason I didn't realize that code was wrong is because that code never ever gets executed.  The console.log line I have at the beginning of `conn.on("keyboard-interactive"` **never** gets called.  After stepping through everything line-by-line, it seems to be failing somewhere deep within `ssh.js` which contains all the lower level code that ssh2 uses.

**Comment by mofux** [comment]
Can you post a working example of your code? I can test it against my server just to make sure.

**Comment by mofux** [comment]
Btw I also use the lib from inside electron (main process), so it can't be that.

**Comment by mscdex** [comment]
Judging by the debug output, your server most likely does not have keyboard-interactive enabled/set up, since it's rejecting the authentication method immediately. If your `password` mechanism works just fine, why are you trying to use keyboard-interactive?

**Comment by cnsumner** [comment]
@mscdex That's what I thought, however, I am currently using PuTTY to connect to the host using keyboard-interactive (unless they have some way of faking it?).  And the reason I'm wanting to use keyboard-interactive is because I wanted to support all of the different authentication methods, and not fake keyboard-interactive by coding my own username/pass dialog and passing the input to the user/pass method.

**Comment by mscdex** [comment]
Some clients may sniff keyboard interactive prompts for 'Password:' or similar and use that as an alternative to the plaintext password auth method. Also, having that option enabled in PuTTY probably just means it'll attempt that auth method as a fallback, not that it enforces its use?

Anyway, glad to hear you got it resolved now.

**Comment by zxdong262** [comment]
Hi, @mscdex, thank you for the great work. I have encountered same situation recently, after reading your post, I set `ChallengeResponseAuthentication yes`, the `keyboard-interactive` works now.

But after Checking `man  sshd_config` in ubuntu 16.04 and ubuntu 18.04 server, it is set to `no` by default, I tried ssh from bash, it will ask for the password even it is set to `no`, I wonder if there is a way to  make the `keyboard-interactive` works with `ssh2` when `ChallengeResponseAuthentication no`.

**Comment by zxdong262** [comment]
@mscdex
Thank you for the reply.

Just detailed my situation:
In ubuntu server, I set 
```
ChallengeResponseAuthentication no
Match User someUserName
        AuthenticationMethods publickey,password publickey,keyboard-interactive
```
I just use normal `bash command line` in mac, like `ssh -i .ssh/id_rsa someUserName@xxx.xx`, it will ask for password. And `ssh -V` shows `OpenSSH_7.6p1, LibreSSL 2.6.2`. I tested `ssh -i .ssh/id_rsa someUserName@xxx.xx` in ubuntu 18.04 too with `OpenSSH_7.6p1 Ubuntu-4ubuntu0.1, OpenSSL 1.0.2n`, same behavior, ask for password.

**Comment by zxdong262** [comment]
@mscdex 
From code, seems password will be test first, and will fail, to confirm it, I tested with password option, it do act so. 

https://github.com/mscdex/ssh2/blob/master/lib/client.js#L375-L378

```
  if (this.config.password !== undefined)
    auths.push('password');
  if (this.config.publicKey !== undefined)
    auths.push('publickey');
```

**Comment by mscdex** [comment]
Correct, the order is documented in the readme.
