### ISSUE TITLE
on .shell mode, stdout and stderr are merged

### ISSUE THREAD

**Issue by bibulle** [mscdex/ssh2#523]
Is it a "normal" feature ?

Launching the command 'sdfsdf\nls -l\nexit\n' in both example mode I got :

.exec (OK, got STDERR)
`Client :: ready`
`STDERR: bash: sdfsdf: command not found`
`STDOUT: total 0`
`Stream :: close :: code: 0, signal: undefined`   

.shell (KO, only STDOUT)
`...`
`STDOUT: `
`STDOUT: sdssgd: command not found`
`STDOUT: `
`...`

**Comment by mscdex** [comment]
Yes, this is probably to be expected since most interactive shells typically just use one stream for all output.
