### ISSUE TITLE
How to Handle CLI sessions in SSH

### ISSUE THREAD

**Issue by Breme** [mscdex/ssh2#524]
I used SSH2 to execute commands in remote PC and logged the output of the commands in local PC console successfully.But I have a issue that this is working fine for only simple commands like 'ipconfig', my first command is 'XXXCLI ip_address' which connects me to the third party CLI. Once this command is executed I couldn't execute any other commands since the control is getting into this third party CLI session.I want to execute some commands inside this CLI session .I couldn't do it by spawning a child process since it creates a separate child process for each command

```js
client.on('session', function(accept, reject) {
            var session = accept();
            session.on('exec', function(accept, reject, info) {
           var spawn = require('child_process').spawn;

var stream = accept();
var cp = spawn(info.command, { shell: true });
cp.on('exit', function(code, signal) {
  stream.exit(signal || code);
}).on('close', function(code, signal) {
  stream.close();
});
stream.stdin.pipe(cp.stdin);
cp.stdout.pipe(stream.stdout);
cp.stderr.pipe(stream.stderr);
            });
        });
```
Kindly help me , how to handle the CLI stream after executing my first command and how to execute other commands inside third party CLI session.
Thanks!

**Comment by mscdex** [comment]
I don't really understand what it is you're trying to accomplish.

**Comment by Breme** [comment]
When I manually type the first command 'XXXCLI ip_address' in my command prompt and press enter,I will get a output "Connected to CLI...."  .Once I get this connection successful, I need to execute my second command i.e "Lmc sample" which will load the master config and I will get the output as "Message sent..", third command will execute a script,will get output as "Message sent.." .This is what happens when I enter these commands manually in cmd prompt and execute.

What is happening is once I execute my first command i.e "XXXCLI 10.21.254.12" manually in cmd, The path where we actually execute the commands i.e( **C:\users\CLI>**) will not be visible. This happens because now it got connected with the above mentioned ip (10.21.254.12) .And Only after connecting to this ip ,I can able to execute my other commands.i.e command to load master config ,cmd to execute script etc.

So I want to execute my first command and get its input stream and should execute forthcoming commands inside its stream and log the output it gives. 

Thanks!

**Comment by Breme** [comment]
Hi , Its done now Thanks!
