### ISSUE TITLE
how to interactive shell 

### ISSUE THREAD

**Issue by hktalent** [mscdex/ssh2#525]
1、if i will use remote metasploit,so i will exec:
nc 192.168.10.243 2323
workspace

2、see out info，and go on input:

workspace allwaiwang 

3、db_nmap -sS -A -O 192.168.28.0/24  --host-timeout=300m  --max-rtt-timeout=3000ms --initial-rtt-timeout=1000ms --min-rtt-timeout=1000ms --max-retries=2 --stats-every 10s --traceroute --min-hostgroup=64 -PS1-65535 --min-rate=500 
see out info，and go on input:
hosts 222.209.254.55
services 222.209.254.55

4、or exec cmd：top
see info long time，and input 'q' exit top cmd

**Comment by mscdex** [comment]
It's not clear what you're asking for here.

If you're asking how to send to a process's stdin after calling `.exec()`, just write to the `stream.stdin` stream (just like `child_process.spawn()` gives you).

**Comment by hktalent** [comment]
thanks
