### ISSUE TITLE
Interactive password auth

### ISSUE THREAD

**Issue by sagorshkov** [mscdex/ssh2#526]
Hello. I can't find a logic to check server's allowed auth methods. Could you please describe the reasons why there is no possibility to prompt the password if the server is allowed standard password auth, but the password was not passed to a Client.connect method. 
There is no logic to check the allowed server methods?

Let me clarify my issue. 
There is a server with "public key, password" allowed methods. When I trying to connect without key and password in Client.connect method it's failed with the error. But any default CLI ssh client will prompt you to pass the password. It will be something like Next authentication method: password message and prompt below. You can pass the password and continue. I need something like this in my app.

It looks like this behavior: If all previous methods in the server's allowed method list failed and next method is password we have to have any callback to ask the password from the user and continue (the same behavior as in keyboard-interactive, but we use the server allowed methods list instead teyKeyboard flag). But right now if there is not a password attribute in the Client.continue method the this method will not be trying at all (but the server allowed this method).

Could you please shed any light on this behavior and help me to find ways for resolving my case.

Thanks in advance.

**Comment by mscdex** [comment]
Prompting for a password is not something that should be handled by this module, that should be left to the application. The list of "allowed methods" (actually just a free-form string) returned by a server is merely a suggestion and should not be relied upon. So your best bet if you're doing this interactively and do not know what the correct authentication method is, just retry the connection with the new/next authentication method.

Also, I'm not sure what you're referring to with `Client.continue`, there is no such method in this module.

**Comment by sagorshkov** [comment]
@mscdex Ohh, sorry. I mean Client.connect method. It's my mistake. 

> Prompting for a password is not something that should be handled by this module, that should be left to the application.    

You are right. But I mean something like event or callback.

Yeah. The first idea I've got was to make a connection without password in Client.connect method and if it fails, ask the password from the user and tries to connect again with password method only in attributes. But there is awkward moment - If the user is not allowing the standard password method on his server, I'll ask him anyway. 

It's possible, I have to think about realise something like get_allowed_auths in [Paramiko](http://docs.paramiko.org/en/2.1/api/server.html#paramiko.server.ServerInterface.get_allowed_auths) and make the second connection only if the password exists in that list.

**Comment by mscdex** [comment]
As I mentioned, you cannot rely on those lists because a server can send whatever they want -- even a blank string. So either way you could be sending an unsupported authentication method and not even know it.

**Comment by sagorshkov** [comment]
@mscdex Ok, thanks a lot for your help. 
Could you please clarify, can I make the second connection with the password  (if all other methods failed with my first connection without password in Client.connect method) so that the user does not notice two different tries to connect to his server? If I execute the Client.connect method secondary It will be so, am I right?

**Comment by mscdex** [comment]
No, this module currently only tries the configured authentication methods in the order listed in the readme for a connection. You would need to connect a second time for your particular use case.
