### ISSUE TITLE
how config or set the charset

### ISSUE THREAD

**Issue by hktalent** [mscdex/ssh2#528]
[root@appserver ~]# df -h
ÎÄ¼þÏµÍ³ ÈÝÁ¿ ÒÑÓÃ ¿ÉÓÃ ÒÑÓÃ%% ¹ÒÔØµã
/dev/mapper/VolGroup-lv_root
507G 153G 328G 32% /
tmpfs 16G 1.2M 16G 1% /dev/shm
/dev/xvda1 485M 52M 408M 12% /boot
192.168.10.123:/MyWork
985G 223G 712G 24% /MyWork

the “¹ÒÔØµã” cannot display，is china word

**Comment by mscdex** [comment]
Can you share the ssh2-specific code you're using?
Also, what are the `LANG` and `LC_*` environment variables set to on the remote server?
