### ISSUE TITLE
how control input cmd?

### ISSUE THREAD

**Issue by hktalent** [mscdex/ssh2#530]
how control input cmd?
1、record
all input、and all output to database
2、control
filter unsafe input and unsafe output
3、interface
where is the interface api，how use api to monitor and control

thank you

**Comment by mscdex** [comment]
This is a pretty broad set of non-ssh2-specific questions and this issue tracker isn't really the place for that. Try stackoverflow.com or the [nodejs/help issue tracker](https://github.com/nodejs/help/issues) for such general questions.
