### ISSUE TITLE
 client exec  Set env not successful

### ISSUE THREAD

**Issue by Mr1024** [mscdex/ssh2#538]
conn.exec('ossdownload',{env:{'ossdownload':'pythons'}},function(){})

**Comment by mscdex** [comment]
The server probably isn't allowing the environment variable to be set. For example, by default, OpenSSH's server does not allow *any* environment variables to be set. However some distros will have an explicit default set of allowed variables, such as Ubuntu allowing only `LANG` and `LC_*`.

**Comment by Mr1024** [comment]
conn.shell({
        env: {
            'ossdownload': 'python'
        }
    }, function(err, stream) {});
setting env by using conn.shell is successful,but conn.exec not

**Comment by mscdex** [comment]
Out of curiosity, what is the server ident string shown in the console if you set `debug: console.log` in your `connect()` options?

**Comment by Mr1024** [comment]
SSH-2.0-ssh2js0.1.16

**Comment by mscdex** [comment]
My guess is that there is some sort of server limitation in place. I cannot reproduce it with a vanilla OpenSSH installation. If `AcceptEnv` is set appropriately in the server's `sshd_config` file, the environment variable is shown in both `exec()` and `shell()` for me.

**Comment by Mr1024** [comment]
thank sir very much
