### ISSUE TITLE
ssh connection hopping: streams/prints to STDERR

### ISSUE THREAD

**Issue by markus-spark** [mscdex/ssh2#542]
Hi there
I'm trying to connection hop via ssh, also the unix system I'm using does not have nc.
I cannot connect to the unix server directly, I have to go through an intermediate server.
I can connect to this intermediate server fine and run commands and execute commands however,
when I run the ssh command the output is immediately printed to the STDERR. I'm not able to ssh hop to the server I want.

Would you happen to know why?
Thanks!

`

	var Client = require('ssh2').Client;

	var pw = require('./pw.js');

	var conn1 = new Client();
	var conn2 = new Client();

	conn1.on('ready', function () {
		console.log('FIRST :: connection ready');
		conn1.exec('ssh -tt serverB', function (err, stream) {

			if (err) {
				console.log('FIRST :: exec error: ' + err);
				return conn1.end();
			}

			stream.on('data', function (data) {
				console.log('stream~~~~~: ' + data);
			})
			.stderr.on('data', function (data) {
				console.log('STDERR====: ' + data);
				//return conn1.end();
			})

			conn2.connect({
				sock: stream,
				username: pw.username,
				password: pw.password,
			});
		});
	}).connect({
		host: 'serverA',
		username: pw.username,
		password: pw.password,
	});

	conn2.on('ready', function () {
		console.log('SECOND :: connection ready');
		conn2.exec('uptime', function (err, stream) {
			if (err) {
				console.log('SECOND :: exec error: ' + err);
				return conn1.end();
			}
			stream.on('end', function () {
				conn1.end(); // close parent (and this) connection
			})
			.on('data', function (data) {
				console.log(data.toString());
			})
			.stderr.on('data', function (data) {
				console.log('STDERR CONN2====: ' + data);
				//return conn1.end();
			});
		});
	});
`

![capture](https://cloud.githubusercontent.com/assets/26699508/24338014/6872d3a2-12fe-11e7-8437-70ea06eef4b6.PNG)

the "dubug: console.log" on conn1 after the conn1 is statblished:

FIRST :: connection ready
DEBUG: Outgoing: Writing CHANNEL_OPEN (0, session)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN_CONFIRMATION
DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exec)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:18,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_WINDOW_ADJUST (0, 198560)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_SUCCESS (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:508,padLen:11,remainLen:496
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EXTENDED_DATA (0)
STDERR====: -----------------------------------------------------------
 Use of this system is restricted to authorized users.
 User activity may be monitored and recorded by system personnel.
 Anyone using this system expressly consents to
 such monitoring and recording.

 BE ADVISED: if possible criminal activity is detected,
 system records, along with certain personal information
 may be provided to law enforcement officials.
-----------------------------------------------------------

DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:60,padLen:8,remainLen:48
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EXTENDED_DATA (0)
STDERR====: Permission denied, please try again.

DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:60,padLen:8,remainLen:48
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EXTENDED_DATA (0)
STDERR====: Permission denied, please try again.

DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:18,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_REQUEST (0, exit-status)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:92,padLen:16,remainLen:80
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EXTENDED_DATA (0)
STDERR====: Permission denied (publickey,password,keyboard-interactive).

DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EOF (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_CLOSE (0)
DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)

**Comment by mscdex** [comment]
You shouldn't use the `ssh` client for hopping to the second server if you want more control over the second ssh connection. Instead you can use `conn1.forwardOut()` to create an outbound connection from the first server to the second server. Then pass *that* resulting stream to `conn2.connect()` as the `sock` value.

Alternatively if the server is restricting such outbound connections via `.forwardOut()`, you can instead use a raw connection setup program such as `netcat`/`nc` or `socat` (if available) with `conn1.exec()` and use that resulting stream for `sock`.

**Comment by markus-spark** [comment]
Hmmmmm, I did what you said and it sort of works.
I can get a command across to ServerB and it prints back. It also prints a whole lot of other stuff.

(I am running node.js from windows CMD, ServerA & B are both unix)
`

	var Client = require('ssh2').Client;

	var pw = require('./pw.js');

	var conn1 = new Client();
	var conn2 = new Client();

	conn1.on('ready', function () {
		console.log('Client :: ready');
		conn1.forwardOut('127.0.0.1', 8000, 'ServerB', 22, function (err, stream) {
			if (err)
				throw err;

			stream.on('close', function () {
				console.log('TCP CONN1 :: CLOSED');
				conn1.end();
			}).on('data', function (data) {
				console.log('TCP CONN1 :: DATA: ' + data);
			});

			conn2.connect({
				sock: stream,
				username: pw.username,
				password: pw.password
			});
		});
	}).connect({
		host: 'ServerA',
		port: 22,
		username: pw.username,
		password: pw.password
	});

	conn2.on('ready', function () {
		console.log('SECOND :: connection ready');
		conn2.exec('uname -a', function (err, stream) {
			if (err) {
				console.log('SECOND :: exec error: ' + err);
				return conn2.end();
			}
			stream.on('close', function () {
				console.log('TCP CONN2 :: END: ');
				conn2.end();
			})
			.on('data', function (data) {
				console.log('TCP CONN2 :: DATA: ' + data);
			})
			.stderr.on('data', function (data) {
				console.log('TCP CONN2 :: STDERR: ' + data);
				return conn2.end();
			});
		});
	});
`

![untitled](https://cloud.githubusercontent.com/assets/26699508/24382998/80574530-13b6-11e7-94f4-938aa077b036.png)




"debug: console.log" on conn2.connect

Client :: ready
DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.16'
TCP CONN1 :: DATA: SSH-2.0-OpenSSH_6.0

DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_6.0'
DEBUG: Outgoing: Writing KEXINIT
TCP CONN1 :: DATA:   ���>M0b����x<��   �ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1   ssh-rsa,ssh-dss   �aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se   �aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se   �hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96   �hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96   none,zlib@openssh.com   none,zlib@openssh.com                  
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:956,padLen:5,remainLen:952
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: KEX algorithm: ecdh-sha2-nistp256
DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
DEBUG: Host key format: ssh-rsa
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXECDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
TCP CONN1 :: DATA:   |     ssh-rsa       �(fwz {@F�ٛx�b�|�
L�}��-��Nr5(��)0D@��VR������G�8�ଧ����,��	�i!�
c=�b����f���@~~b�E���Zͪ���'ʞV�S{Ad�W����St���^�'�v�:AF!�|����K��S�w�9��<S��<��~� ��:nR��&^��_G�O�<���� ���Ŋ���Rh:也�ͫ���;jz�^q��=y	�$�VP�S�{�MBLk!�m4�DQK�   A��(vp'�h�l7�럑�����߅y,I����Դ�D�a��L���s|�1��B*�P�	(p�2v     ssh-rsa   ����G�i�e��M}��E�_o=�D�@ꔙ1�
�N]C��J���&�����f��?v`6sH����U��o�l��e�V%��#��n�����c����.�q�%��x�bKEg���)����H�Oh�t����C��G��S���(tjQVrg��lEc'�1v"d5 dH��@,��z�9�lx�Cu��� ۩��S����T���nU��p�j�Vo��ېu��A��W&H{*4SJ,-�|�7�4*�2^���vI�          
          
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:636,padLen:7,remainLen:632
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Outgoing: Writing NEWKEYS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
TCP CONN1 :: DATA: @�5�5���A1?u����$'K�?<g��l��=��P�jQsz��I����Q~B"������]����
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
TCP CONN1 :: DATA: Y�O�(�=�?���ff�_W��J�Cź�TxY���$�'6ڢ��#I�d`�lu1��#�*zN?����H���2߀|t���lS���kӯ�	�R�5�+��0�&���~Et\���u�N�@NB;@�ӖR1�X����2�S�u-ͩ���v_�C,���F�$��>��rB����^�<�4R�����
r�����.5��rKL�9��@�'���Sf���c@�=Q��J��������&2��Y⏇�3A��o�;+7�B��3
��v�����4�����ג�����-/�Ja���U�U�ԫ�����f��Hk�mˊ��w�G�K�j��K�4���	�Mt)5Q1���x@�u��� �[⪷J�S�'����n00�>`�6��ݭ���4���e��7nߍr�O\�bM���d<�|-J"�1l�
*rR,����k��<�3��rV>�Ņb���Ѷ�@�/�R*~��Vjζ�i���?+L��Dc��FVǅ���-�zm3{��u1�{+�HE ���c�����/�:�m��kG���ߺ]�FYU�� ����*�Q�R�&W²,5���ā��g�-��4�
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:508,padLen:15,remainLen:496
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_BANNER
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_SUCCESS
SECOND :: connection ready
DEBUG: Outgoing: Writing CHANNEL_OPEN (0, session)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
TCP CONN1 :: DATA: Q�zN�u� =�ן3§,���O���+B�E�����w�R�(���7\Xuy
��%��~����"Ʋ�
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN_CONFIRMATION
DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exec)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
TCP CONN1 :: DATA: ~��6��#��}�����o���Q�h
�U#�Nx���Qr��N���>�F��˟���Pb�����	�_�JJ=������|�[�&K`9��&��?���h3#�\vS
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:18,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_WINDOW_ADJUST (0, 2097152)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_SUCCESS (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
TCP CONN1 :: DATA: �\�C��j+@p9�p�{�֋ܬZ9ܻey�\��!S[`x�H!��������u՚�R׃��M���ؓ�g+-a�Ե��J$���3|�v��LR��=#�L��%ݙ����L
&y��$:S�I$
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:6,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
TCP CONN2 :: DATA: AIX iv4179 1 7 00F746334C00

DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_EOF (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
TCP CONN1 :: DATA: O�K���[�x�\Nc�a��Q�4�%~IØ#)0/�'���I�"�
������D]ܖ� �CE�L.3E�ǣ`JS\oX��܉̯�i` ��6u��W�@��Ү� ����rpߴذ i`_*
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:18,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_REQUEST (0, exit-status)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:6,remainLen:0
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_CLOSE (0)
DEBUG: Outgoing: Writing CHANNEL_CLOSE (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
TCP CONN2 :: END: 
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
TCP CONN1 :: CLOSED

**Comment by mscdex** [comment]
You shouldn't do anything with `stream` when you pass it to `conn2.connect()`, as that represents the underlying TCP connection for the ssh connection and so as such you will see a bunch of "garbage" because it's the binary ssh protocol that you're seeing.

**Comment by markus-spark** [comment]
oh yea, that makes sense =)

Everything works now.
thanks man XD
