### ISSUE TITLE
How to Execute command in a particular directory in a  SSH connection

### ISSUE THREAD

**Issue by Breme** [mscdex/ssh2#544]
Hi,
1)I want to SSH a server
2)I want to execute a command to enter configuration mode ("Config terminal")
3)After successful login I need to locate a particular directory ( "cd /my/path")
4)Then I want to execute a command in that location ("get config")

All I did now is logged in to my server successfully, 

```js
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
    console.log('Client :: ready');
    conn.shell('Config terminal', function(err, stream) {
        if (err) throw err;
        stream.on('close', function(code, signal) {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
        }).on('data', function(data) {
         
            console.log('STDOUT: ' + data);
        }).stderr.on('data', function(data) {
            console.log('STDERR: ' + data);
        });
    });
}).connect({
    host: '10.77.55.41',
    port: 22,
    username: 'sshconf',
    password: 'sshconf'
});
```

How to modify this code to achieve this. Kindly help

Thanks

**Comment by mscdex** [comment]
`stream.write('config terminal\r\ncd /my/path\r\nget config\r\n');`

Or if your Cisco hardware supports it, use `conn.exec()` instead, replacing the CRLFs with `&&`. The benefit of that method is that you don't see your own input echoed back to you like you will with `shell()` (unless the remote shell supports disabling of such echoing, such as `stty -s echo` on Linux).
