### ISSUE TITLE
Keep Process Running After Disconnecting

### ISSUE THREAD

**Issue by michaelalhilly** [mscdex/ssh2#545]
Hi,

I'm having trouble keeping a bash script running after I disconnect the client. In the example below I'm attempting to run the script in the background and disowning it before ending the session.

Is this supported?

```
const client = new ssh.Client()

client.on("ready", () => {

	client.exec("/tmp/install.sh &/ndisown")

	client.end()

}).connect(options)
```

**Comment by mscdex** [comment]
Your newline syntax isn't correct, it should be `\n` instead of `/n`. However, I traditionally use something like 'nohup' FWIW.

**Comment by michaelalhilly** [comment]
@mscdex Thanks! nohup works perfect.
