### ISSUE TITLE
New release to commit changes for mscdex/ssh2#494 and mscdex/ssh2#497

### ISSUE THREAD

**Issue by wisotzky** [mscdex/ssh2#546]
Hi Brian,
Could you please push a new release of ssh2 for those changes you've made regarding mscdex/ssh2#494 and mscdex/ssh2#497? Using apm/npm as an installer, I can not reference to the current latest/development branch. As those issues are already from Nov 2016, I want to make people benefit from those compatibility fixes added.

Thx
Sven

**Comment by wisotzky** [comment]
@mscdex 
Any update on this?

**Comment by mscdex** [comment]
I'm working on it. There are a few other things I want to fix yet. I hope to make a release soon.

**Comment by mscdex** [comment]
New version released. Thank you for your patience.
