### ISSUE TITLE
ssh client connect to server err:privateKey value does not contain a (valid) private key

### ISSUE THREAD

**Issue by KingYoung87** [mscdex/ssh2#547]
flow the example. this is my code:
var client = require('ssh2').Client;
var conn = new client();
var key = require('fs').readFileSync('/Users/Young/.ssh/id_rsa.pub');
console.log(key);
conn.on('ready', function() {
	console.log('client::ready');
	conn.exec('uptime', function(err, stream) {
		if (err) {
			throw err;
		}
		stream.on('close', function(code, signal) {
			console.log('stream :: close :: code :' + code + ',signal: ' + signal);
			conn.end();
		}).on('data', function(data) {
			console.log('STDOUT: ' + data); 
		}).stderr.on('data', function (data) {
			console.log('STDERR: ' + data);
		});
	});
}).connect({
	host: '10.19.164.103',
	port: 22,
	username: 'root',
	privateKey : key
});

then i run the file. err come.
![image](https://cloud.githubusercontent.com/assets/9124243/25001416/071e19ea-2078-11e7-8c81-5a8e04f321a4.png)

please help me.

**Comment by KingYoung87** [comment]
ok , my fault . it is ok now. thank for your open source

**Comment by rezaamya** [comment]
then what was your fault?
