### ISSUE TITLE
Unable to request a pseudo-terminal

### ISSUE THREAD

**Issue by emrahtunc** [mscdex/ssh2#550]
Help Please !

Error: Unable to request a pseudo-terminal
    at C:\Users\EMRAH\WebstormProjects\yeni\node_modules\ssh2\lib\client.js:1294:21
    at SSH2Stream.<anonymous> (C:\Users\EMRAH\WebstormProjects\yeni\node_modules\ssh2\lib\Channel.js:205:24)
    at emitNone (events.js:86:13)
    at SSH2Stream.emit (events.js:185:7)
    at parsePacket (C:\Users\EMRAH\WebstormProjects\yeni\node_modules\ssh2-streams\lib\ssh.js:3503:10)
    at SSH2Stream._transform (C:\Users\EMRAH\WebstormProjects\yeni\node_modules\ssh2-streams\lib\ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\EMRAH\WebstormProjects\yeni\node_modules\ssh2-streams\lib\ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:334:12)

**Comment by mscdex** [comment]
Just as the error says, the server did not allocate a pty as requested. You may/may not be able to get by without using one depending on what you're trying to accomplish. Having a pty is more or less required to have an interactive shell session (`shell()`), but for `exec()` it's optional and only needed for executing commands that require a "real" terminal.

**Comment by emrahtunc** [comment]
What is the part that needs to be fixed? Or the code to add?

**Comment by emrahtunc** [comment]
Şu dil olarak değiştir: Türkçe
This project is my finishing project.
But I do not know very well.
I need to connect to a firewall with ssh and display the data on the web page.
What do I need to do to get images to appear on a regular basis on the web page?
Thank you.

**Comment by mscdex** [comment]
Well, if you have access to the server you might be able to change the server configuration (e.g. for OpenSSH it's the `PermitTTY` option in sshd_config, which is set to `yes` by default).

Otherwise you'll have to just use `exec()` to get whatever you need.

**Comment by emrahtunc** [comment]
How do I use the Exec () operation?

**Comment by mscdex** [comment]
There are example in the readme.

**Comment by emrahtunc** [comment]
I get a "Unable to exec" error.

Commands to send commands to the device eg: get interface or get ssh

**Comment by emrahtunc** [comment]
var ssh_config = {

    host: ipNo,
    port: 22,
    username: username,
    password: password,
    readyTimeout: 4000,
    algorithms: {
        kex: ['diffie-hellman-group1-sha1',
            'ecdh-sha2-nistp256',
            'ecdh-sha2-nistp384',
            'ecdh-sha2-nistp521',
            'diffie-hellman-group-exchange-sha256',
            'diffie-hellman-group14-sha1'],
        cipher: ['aes128-cbc',
            '3des-cbc', 'blowfish-cbc',
            'aes128-ctr', 'aes192-ctr',
            'aes256-ctr', 'aes128-gcm',
            'aes128-gcm@openssh.com',
            'aes256-gcm',
            'aes256-gcm@openssh.com'],
        serverHostKey: ['ssh-rsa', 'ssh-dss'],
        hmac: ['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-sha1-96']

    }
}


function ubunut(command,callback) {


//bağlantıyı açıyoruz
    conn.on('ready', function () {
        console.log('"Bağlandı...."'); //bağlantı olduğunu çıktı veriyoruz
        conn.shell(function(err, stream) {
            if (err) throw err;
            var gelenveri=stream.stdout.pipe(process.stdout);


            callback(gelenveri.toString('hex'))
            stream.stderr.pipe(process.stderr);
            stream.stdin.write(command);

            stream.end();

        });
 


    }).connect(ssh_config)}

----------------------------------------------------------------------------------------
How can I change this code?

**Comment by mscdex** [comment]
You could try `shell(false, {}, function(err, stream) { ... })`, which should not try to allocate a pty...

**Comment by emrahtunc** [comment]
I solved my problem using "ssh2shell". Thank you.
