### ISSUE TITLE
HELP......ssh2, ssh2shell command output format

### ISSUE THREAD

**Issue by emrahtunc** [mscdex/ssh2#552]
What do I need to do to display properly on a web page?

Format shift is occurring.

**Comment by mscdex** [comment]
I don't understand the question.

**Comment by emrahtunc** [comment]
thank you. no need anymore.

iPhone'umdan gönderildi

Brian White <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (15 Haz 2017 18:47):


I don't understand the question.

**Comment by carterwu** [comment]
@emrahtunc hello, how did u solve this problem:display properly on a web page.

mainly seperated the lines
