### ISSUE TITLE
Sftp Server - Handling fastGet method

### ISSUE THREAD

**Issue by harkinj** [mscdex/ssh2#554]
Hi,
Thanks for the great lib.
We have successfully implemented a partial Sftp server handling operations such as readdir etc.
We now want to extend it to handle the fastGet method but having trouble working out what event to handle. Any pointers as to what event we should be handling or how to work it out?
Thanks for your time.
John

**Comment by mscdex** [comment]
There is nothing special about `fastGet()`, it's just doing parallel read requests. So all you need to implement for that are the open, fstat/stat, read, and close requests.

**Comment by harkinj** [comment]
Thanks for the info an quick response.
John
