### ISSUE TITLE
How to send commands to same shell session with different instance?

### ISSUE THREAD

**Issue by Breme** [mscdex/ssh2#555]
Hi ,
I have a http server running , I'm using ssh2 package for interactive shell session which is serving as a rest API inside HTTP server. First I will send a http request, to start a command (http://localhost:8080?TC=start)
Now the ssh shell is created command executed and I will get some data in realtime on my console.

Next I want to send a command to stop the data which is currently running. (http://localhost:8080?TC1=stop). 

Now I want this stop command to interact with the same shell that we used for start command.
Is this possible? Kindly help

`dispatcher.onGet("/executessh", function(req, res) {
    var str = '';
    var url = require('url');
    var url_parts = url.parse(req.url, true);
    console.log(url_parts);
    var TC = url_parts.query.TC;
    var TC1 = url_parts.query.TC1;
    var sleep =require('system-sleep');
    var process=require('process');
    var CtrlC = require("ctrl-c");
/*if(TC==='stop')
{
    process.exit(1);
}*/
 if(TC==='start')
{

    conn.on('ready', function() {
        console.log('Client :: ready');
        conn.shell('sampleWindow', function(err, stream) {
            if(TC1==='stop')
            {
               //How to stop 

            }
            stream.write('startCommand\n\r');

            if (err) throw err;
            stream.on('close', function(code, signal) {
                console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                conn.end();
            }).on('data', function(data) {
                
                
                console.log('STDOUT: ' + data);
                fs.appendFile('D:\\Breme\\sample.txt',data,function(err){
                    if(err)
                    {
                        console.log(err);
                    }
                    //console.log('file saving..')
                });
                // setTimeout(function(){
                //     process.exit(1);
                // }, 20000);

            }).stderr.on('data', function(data) {
                console.log('STDERR: ' + data);

            });

        });
    }).connect({
        host: 'x.x.x.x',
        port: 22,
        username: '123',
        password: '123'
    });
}

});`

**Comment by mscdex** [comment]
You'd have to store your connection object somewhere that is reachable between requests (perhaps in an object that is keyed on some sort of session id so that you can easily find it later). That'll work as long as requests come to the same server.

If you need to kill it from a separate server (e.g. you are using the `cluster` module or similar), then to stop you would have to either send a message to the other server (perhaps using redis or something similar) *or* start a new ssh connection to kill the remote process (this requires you to obtain the pid in some way though).

**Comment by Breme** [comment]
Thanks !! I will try it.
