### ISSUE TITLE
Display international character (utf8)

### ISSUE THREAD

**Issue by guiguan** [mscdex/ssh2#557]
I was using `ssh2` `shell` to list remote directory which contained a folder with a Chinese name. That directory was displayed as ?????????????????? in final result instead of the correct Chinese name. I tried to set encoding with `stream.setEncoding('utf8')`, but it didn't work. Any idea?

**Comment by mscdex** [comment]
Can you post the relevant code that uses `.shell()`?

**Comment by guiguan** [comment]
@mscdex thanks for the fast response. here is my code:

```js
import { Client } from 'ssh2';
import byline from 'byline';

class SshClient {
  constructor(options) {
    this.options = options;
    this.client = new Client();
  }

  connect() {
    return new Promise((resolve, reject) => {
      this.client
        .on('ready', resolve)
        .on('error', reject)
        .connect(this.options);
    });
  }

  close() {
    this.client.end();
  }

  shell(cmd) {
    return new Promise((resolve, reject) => {
      this.client.shell((err, stream) => {
        if (err) {
          return reject(err);
        }

        stream.setEncoding('utf8');

        const bylineStream = byline.createStream(stream); // with or without this `byline`, the problem exists

        bylineStream.on('data', (line) => {
          console.log(line);
        });

        stream.on('close', (code) => {
          if (code !== 0) {
            return reject();
          }

          resolve();
        });

        stream.end(`set -e;${cmd};exit $?\n`);
      });
    });
  }
}

const sshClient = new SshClient({
  host: '172.16.0.1',
  port: 22,
  username: 'guiguan',
  privateKey: process.env.SSH_PRIVATE_KEY
});

sshClient
  .connect()
  .then(() => sshClient.shell('ls'))
  .then(() => sshClient.shell('pwd'))
  .then(() => sshClient.close());
```

**Comment by mscdex** [comment]
I'm not sure about `byline`, but this simple example worked fine for me (tested with node v6.9.1 and latest `ssh2`):

```js
client.shell(function(err, stream) {
  if (err) throw err;
  stream.on('close', function() {
    client.end();
  });
  stream.pipe(process.stdout);
  stream.stderr.pipe(process.stderr);
  stream.write('ls -l test\nexit\n');
});
```

where 'test' was a directory containing a subdirectory with a chinese name.

**Comment by guiguan** [comment]
I still got ???? with your simple example.

**Code**:
```js
const { Client } = require('ssh2');

const client = new Client();

client.on('ready', () => {
  client.shell(function(err, stream) {
    if (err) throw err;
    stream.on('close', function() {
      client.end();
    });
    stream.pipe(process.stdout);
    stream.stderr.pipe(process.stderr);
    stream.write('ls -l\nexit\n');
  });
}).connect({
  host: '172.16.0.1',
  port: 22,
  username: 'guiguan',
  privateKey: process.env.SSH_PRIVATE_KEY
});
```

**Expected**:

<img width="467" alt="screen shot 2017-05-15 at 4 18 09 am" src="https://cloud.githubusercontent.com/assets/940189/26036689/f245fe72-3925-11e7-888e-88a1473e8144.png">

**Got**:

<img width="462" alt="screen shot 2017-05-15 at 4 17 37 am" src="https://cloud.githubusercontent.com/assets/940189/26036692/f9a3908a-3925-11e7-901a-f940018f2431.png">

**Env**:
OS: macOS 10.12.4
Node: v7.5.0

Node version problem? or os?

**Comment by mscdex** [comment]
If you add `'echo $LANG\n'` in the shell(), does it show the correct language setting? I'm wondering if a necessary environment variable isn't set when executing the remote shell.

FWIW I tried on Linux.

**Comment by mscdex** [comment]
Actually, according to [this post](https://unix.stackexchange.com/a/16784), it might be that you need to send the `LC_CTYPE` environment variable. You can pass environment variable using the `env` option like so:

```js
client.shell({ env: { LC_CTYPE: process.env.LC_CTYPE } }, function(err, stream) {
  // ...
});
```

**Comment by guiguan** [comment]
Wow, you are right. The `LANG` wasn't set correctly. So I did `stream.end('export LANG=en_AU.UTF-8; ls; exit')`, then it worked!

However, I tried with both:
```
client.shell(
  {  rows: 100, cols: 100, env: { LC_CTYPE: process.env.LC_CTYPE } },
  (err, stream) => {
```
and
```
client.shell(
  { rows: 100, cols: 100, env: { LANG: 'en_AU.UTF-8' } },
  (err, stream) => {
```
They didn't work. I think the env variables didn't get set in this way. Any idea?

**Comment by mscdex** [comment]
Ok, the `env` support for `shell()` is now supported in dd1e4684f0f8930423accb2e914c7f86e4bf55ba.

If you want to specify window options, those are separate and come before the general options. So with the new changes, you would do something like:

```js
client.shell({rows: 100, cols: 100},
             {env: { ... }},
             (err, stream) => { ... });
```

**Comment by guiguan** [comment]
Awesome, thanks a lot for the help 👍
