### ISSUE TITLE
[question]how to start ssh server？

### ISSUE THREAD

**Issue by zhangjianpinghik** [mscdex/ssh2#562]
i have installed ssh2, but how to start ssh server?

**Comment by mscdex** [comment]
You have to write one using the API. There is no pre-built command line server available that you can just start like OpenSSH.

**Comment by zhangjianpinghik** [comment]
@mscdex 
is it mean that i only have to  install a ssh server(such as OpenSSH-Win64), and then use your ssh2 clinet to access?

**Comment by mscdex** [comment]
It depends on what your goal is. If you want to write an SSH client or server, you can do that with this module, but you will have to code it yourself (or find a third-party module on npm that builds on top of `ssh2` that provides a higher level interface for whichever end you need -- client or server).

**Comment by zhangjianpinghik** [comment]
@mscdex 
i only want to remote acccess windows system and obtain system resource by node.js

**Comment by mscdex** [comment]
That sounds like you want a client then if you're wanting to connect to an *existing* SSH *server*. There are examples in the readme that show how to perform various kinds of client requests.

**Comment by zhangjianpinghik** [comment]
if my ssh server is  OpenSSH-Win64,  can use "mscdex/ssh2" to aceess it?

**Comment by zhangjianpinghik** [comment]
@mscdex 
i don not known when i have installed  "mscdex/ssh2" by command "npm install ssh2 -g",  and use your example about Server Examples, but  how to start it?

**Comment by zhangjianpinghik** [comment]
@mscdex
what is wrong?
D:\share\ssh2-0.5.4>dir
 驱动器 D 中的卷没有标签。
 卷的序列号是 D4BB-B235

 D:\share\ssh2-0.5.4 的目录

2017/05/24  11:58    <DIR>          .
2017/05/24  11:58    <DIR>          ..
2017/05/24  11:58    <DIR>          node_module
2017/05/24  11:50             2,140 ssh-server.
2017/05/24  09:24    <DIR>          ssh2-0.5.4
               1 个文件          2,140 字节
               4 个目录 106,399,580,160 可用字节

D:\share\ssh2-0.5.4>node ssh-server.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'buffer-equal-constan
    at Function.Module._resolveFilename (module
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\share\ssh2-0.5.4\
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by mscdex** [comment]
I guess there is a misunderstanding here. I thought you were connecting to an existing server not creating a server for clients to connect to.

There is no point in installing the module globally (with `-g`) because there are no command-line scripts supplied by this module.

If you want to create a server for others to connect to and you're using the server example in the readme, then you will need to either also install the `buffer-equal-constant-time` module *or* if you are using node v6.6.0+ there is a built-in way to safely compare Buffers with [`crypto.timingSafeEqual()`](https://nodejs.org/docs/latest/api/crypto.html#crypto_crypto_timingsafeequal_a_b) instead of needing a third-party module such as `buffer-equal-constant-time`.

**Comment by zhangjianpinghik** [comment]
@mscdex
i want to know whether i can use ssh server such as OpenSSH-Win64

**Comment by zhangjianpinghik** [comment]
@mscdex 
the hostKeys is necessary? when i use usename and password to access ssh server . if not necessary, what can i disable it?

new ssh2.Server({
  hostKeys: [fs.readFileSync('host.key')]
}, function(client)

**Comment by zhangjianpinghik** [comment]
@mscdex 
how to execute windows cmd command by ssh2 clinet?
why the ssh2-server ipaddress  is 127.0.0.1,the client can not connect to server?

**Comment by mscdex** [comment]
Sorry, I'm not sure I can help you. It's not clear whether you're wanting to write a server or client.

**Comment by zhangjianpinghik** [comment]
@mscdex 
I have write a server and clinet refer to your exzample ,but i do not know how to execute a windows cmd command from client

**Comment by mscdex** [comment]
Unfortunately you're probably better off asking on stackoverflow.com or similar places where your question will be seen by more people. As previously stated I cannot help you as there seems to be a language/terminology barrier here that prevents me from making any useful suggestions.
