### ISSUE TITLE
openssh_streamLocalForward error

### ISSUE THREAD

**Issue by igor-lemon** [mscdex/ssh2#563]
Hi. I have an error during calling openssh_forwardInStreamLocal method.
```
buffer.js:362 Uncaught TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:362)
    at SSH2Stream.openssh_streamLocalForward (VM2233 ssh.js:1085)
    at Client.openssh_forwardInStreamLocal (client.js:1053)
```
![image](https://cloud.githubusercontent.com/assets/14764799/26527908/529c4d46-43a6-11e7-9644-71752eabdbc4.png)

**Comment by igor-lemon** [comment]
I think that instead the `pathlen` param should be `socketPath` param.

**Comment by mscdex** [comment]
Thanks for the heads up, this is now fixed in `ssh2-streams`. Further unix socket forwarding support fixes will land in here soon.
