### ISSUE TITLE
Malformed private key (expected integer for e)

### ISSUE THREAD

**Issue by EugeneKostrikov** [mscdex/ssh2#564]
Getting this error for one of private keys. The key works perfectly fine with regular command-line ssh, but throws with ssh2. Two other keys generated exactly same way work seamlessly with both cli and ssh2. TBH i'm not even sure how to gather more details :) Any suggestions what might help understanding the problem? Maybe there's some test covering the error? Tried searching for one, but didn't find any.

**Comment by mscdex** [comment]
Is the key encrypted? If not, are you able to generate an unused key that reproduces the issue?

**Comment by EugeneKostrikov** [comment]
Seems that's something to do with my own code. Not entirely sure what's happening yet, but cannot reproduce this in isolation with simple example. Closing the issue for now, sorry.
