### ISSUE TITLE
Unable to bind socket | openssh_forwardInStreamLocal

### ISSUE THREAD

**Issue by igor-lemon** [mscdex/ssh2#565]
Hi. I can't bind an socket via openssh_forwardInStreamLocal method.
Alway say me that. I logged as root user and I have full access. Also I tried to bind many others sockets and I didn't have any success result
![image](https://cloud.githubusercontent.com/assets/14764799/26542571/1814ecba-4463-11e7-9b5f-465a7b6c6fff.png)

**Comment by mscdex** [comment]
Does /var/run/docker.sock already exist? If not, does the user have sufficient permissions to create a socket there? If so, what version is the OpenSSH server?

**Comment by igor-lemon** [comment]
Sure. Docker socket exists.
OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016

**Comment by mscdex** [comment]
The `forwardIn()` functions (both TCP and UNIX socket versions) ask the server to start listening on a socket on the server for incoming connections. So if the UNIX socket already exists on the server, then that would explain why it's not working.

It sounds like you are wanting to instead make an outbound connection to a UNIX socket on the server? I see you have already opened an issue about that.

**Comment by igor-lemon** [comment]
Yep. You're right I need tunneling from remote socket to local. 
Sorry, I retried to use forwardIn and it works ok. You can close that issue. Need to move to #566

With forwardOut I can't do that because can't connect to my remote server but any other ssh connections works correctly.
