### ISSUE TITLE
Authentication method priorities should put password last

### ISSUE THREAD

**Issue by hrimhari** [mscdex/ssh2#567]
When providing multiple authentication methods, the last one to be tried should be password. Currently, password is being tried first.

One problem with this order is that password authentication using an invalid password may trigger 'Invalid password' events on the server that can lock the account. This could be avoided by the successful key authentication.

In the opposite case where an invalid key is presented along with a valid password, the invalid key authentication is not usually registered as an authentication error by the system that triggers an account lock.

Another reason for putting password last is that it's the least secure method to authenticate a user. From a security perspective, more secure methods should be tried first.

Preferring key authentication over password authentication is also the default in OpenSSH.

**Comment by popey456963** [comment]
@mscdex Being able to define the order using configuration would probably be useful to a number of use cases, including my own.  Perhaps similar to how OpenSSH allows you to configure it?

**Comment by mscdex** [comment]
You can now handle authentication method order via `authHandler` as of https://github.com/mscdex/ssh2/commit/fbea9a71b285a0a2591da6e4701d9181cd733366. This handler receives both 'authentications that can continue' as well as the partial success indicator.
