### ISSUE TITLE
[question] Storing ctx.username inside function(client, info) { ... }

### ISSUE THREAD

**Issue by developer94404** [mscdex/ssh2#568]
[question]

Hi,

I'm trying to access ctx.username (ie, for connection tracking); so need ctx.username inside of client.on('ready', function() { ... } 

Is it safe to do something like:
```

// a custom class for tracking connections, declared outside
var myConnTracker = new ConnTracker();

new ssh2.Server( {privateKey: ... },
    function(client, info) {
       var username;  // store username here in this scope
       client.on('authentication', function(ctx) {
          // ...
          // save the username and password here, since ctx is only given in this callback
          username = ctx.username;
       }).on('ready', function() {
          myConnTracker.register(username); // register the stored username
          // ...
          client.on('session', function(accept, reject) {
             var session = accept();
             session.on('sftp', function(accept, reject) {
                    var sftpStream = accept();
                    sftpStream._connId = myConnTracker.getConnId(username); // again, access username here
                     // now, inside various sftpStream listern callbacks, I will call console.log(sftpStream._connId) to print out the connection info
             });
           }
       })
     }
```

This worked for most of the time, but I am seeing strange behavior very sporadically in my logs; sometimes I see a sftpStream._connId that does not match the actual user that is logged in and invoking the sftpStream callback (ie, a realpath called by user 'a' is printing with a sftpStream._connId that matches username 'c')

Thanks for any insight / suggestions you can shed on this.

**Comment by mscdex** [comment]
There is nothing wrong with what you're doing. I don't know why you'd be seeing a mismatch. If you can come up with a simple example to reproduce the problem, let me know.

**Comment by developer94404** [comment]
Thanks for the feedback!

I'm working on debugging it, but since it's a little obscure, it may take a while. I will definitely post back when I figure out what's going on :)
