### ISSUE TITLE
calling ssh connection settings in config.js file

### ISSUE THREAD

**Issue by dpresence** [mscdex/ssh2#569]
I am trying to use ssh2 to request data from a server. I formerly did everything inside a graphql schema. Now i seperated the ssh2 client code from the schema. and I want to have the connection settings in a config.js file in a local directory which I call in the call in server.js. How do I implement this?

**Comment by mscdex** [comment]
Just export your settings in config.js and `require()` them wherever you need them?

**Comment by dpresence** [comment]
I have it like this exported like so:
How do I require it?

module.exports ={
  conf: {
    host: '#.#.#.#',
    port: 25,
    username: '####',
    password: '####',
    tryKeyboard: true,
    command: '#/#/#/#',
  }
}

**Comment by mscdex** [comment]
With `require()` like you would any other module.

**Comment by dpresence** [comment]
the issue is I want to require it in my index.js server file but also use it in the ssh connection code in a seperate file. using the code below, how do i move the connection settings there to a config file, require it in my index.js server file and import it to be used in the ssh connection code.

so I want to move what is in the braces aftre .connect, so its not hard coded anymore. Thanks, giving me a sort of guide will help as this is not mentioned in the docs.

var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.shell(function(err, stream) {
    if (err) throw err;
    stream.on('close', function() {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
    stream.end('ls -l\nexit\n');
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  privateKey: require('fs').readFileSync('/here/is/my/key')
});
so I want to move what is in the braces aftre .connect, so its not hard coded anymore. Thanks, giving me a sort of guide will help as this is not mentioned in the docs.

**Comment by mscdex** [comment]
It's not mentioned in the docs because it's out of the scope for this project and is more of a general question/topic.

You already had it correct in your previous example: place the object in a separate file and export it. Then just `require()` that file wherever you need that object:

```js
var config = require('./config.js');
conn.connect(config);
```

**Comment by dpresence** [comment]
thanks I tried but its not working maybe because I have more than one object in the export like so:

module.exports ={
conf: {
host: '#.#.#.#',
port: 25,
username: '####',
password: '####',
tryKeyboard: true,
command: '#/#/#/#',
},
conf1: {
host: '#.#.#.#',
port: 25,
username: '####',
password: '####',
tryKeyboard: true,
command: '#/#/#/#',
},
conf2: {
host: '#.#.#.#',
port: 25,
username: '####',
password: '####',
tryKeyboard: true,
command: '#/#/#/#',
}
}
what do I do in this case, pls pardon my ignorance still new to node and react

**Comment by mscdex** [comment]
The `fs.readFileSync()` has no use, so you can remove them. Your `require()` usage looks just fine as long as the path is correct. From there just use `localConfig.conf`, `localConfig.conf1`, etc. That's all there is to it.
