### ISSUE TITLE
More malformed packet errors

### ISSUE THREAD

**Issue by StefanoDeVuono** [mscdex/ssh2#572]
I'm creating a proxy and just as in issue 203 (https://github.com/mscdex/ssh2/issues/203), I get 'malformed packet' errors. Specifically, the `readString` method from `utils.js` gets `len = buffer.readUInt32BE(start, true);` and finds that `len > maxLen` where len is 34000 maxLen is 32768. I'm able to fix this by asking for a higher maxLen on line 3433 (ie changing `data = readString(payload, 5, self, callback, 32768);` to `data = readString(payload, 5, self, callback, 65536);`), but this doesn't make sense as your comment mentions that packet size should be 32KB or 32768 bytes)

My debug info is as follows. This is being sent by my command line sftp client.
```
< [233229.477710493] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
< [233229.477710493] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
< [233229.477710493] DEBUG: Parser: IN_PACKET
< [233229.477710493] DEBUG: Parser: Decrypting
< [233229.477710493] DEBUG: Parser: pktLen:34028,padLen:18,remainLen:34016
< [233229.477710493] DEBUG: Parser: IN_PACKETDATA
< [233229.477710493] DEBUG: Parser: Decrypting
< [233229.477710493] DEBUG: Parser: HMAC size:32
< [233229.477710493] DEBUG: Parser: IN_PACKETDATAVERIFY
< [233229.477710493] DEBUG: Parser: Verifying MAC
< [233229.477710493] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
```

Also, of note I console.logged the packet number:
```
console.log('+++ sending packet type %d', payload[0]);
```
And I get:
```
< +++ sending packet type 94
```

I've put a debugger in the `readString` method to get more info, I can provide that if you find it's helpful.

**Comment by mscdex** [comment]
Can you provide a short, reproducible example and what sftp client you're using?

**Comment by StefanoDeVuono** [comment]
Hmm. I tried to reproduce the error locally and I couldn't. It appears to be coming from a server I'm connecting to.

I'm using the mac command line sftp client (basically the BSD version), my proxy then connects to another server. If I run the final server locally, I don't have problems, if I connect to the final server I'm actually trying to use this proxy with I get errors.

I'm using the same key exchange and ciphers for my local version of the final server as the real final server. Although, I'm not sure how that would effect packet size. And I'm transmitting the same file.

I've dug in a little deeper and the packet length as assigned by `instate.pktLen = r;`, `34028`, is value higher than `32768`, but lower than the calculated `maxPayloadLen of 35000`. I hope that helps. Is it possible that this final server (my non-local, non testing one) is creating a channel with larger packet lengths? There's a `TODO` around line 3435 that mentions the maximum channel data length should depend on the channel's packet size. Does the SSH server set that?
```
// TODO: MAX_CHAN_DATA_LEN here should really be dependent upon the
//       channel's packet size. The ssh2 module uses 32KB, so we'll hard
//       code this for now ...
```

Thanks for your help.

**Comment by mscdex** [comment]
It's defined in `ssh2` in the higher-level client and server implementations, yes.

Can you share the ident of the final server you're proxying to? It should show up in the debug output near the top when you set `debug: console.log` in the client connection config.

**Comment by StefanoDeVuono** [comment]
Hmm. The ident is a private company's server: I've redacted the company's information:
`SSH-2.0*** SFTP SERVER. ***_SFTP_1_10022. You are attempting to connect to a restricted server. It is confidential and may be legally privileged. If you do not have business on this server, please exit this connection`.

**Comment by StefanoDeVuono** [comment]
Another thought, could a cipher type of `aes256-cbc` change the payload size and the way we extract the packet from the payload?

**Comment by mscdex** [comment]
I think that's the longest ssh ident I've ever seen. Anyway, unfortunately that ident doesn't really help as it sounds like something possibly custom.

RE: cipher choice, it shouldn't matter.

**Comment by StefanoDeVuono** [comment]
Yeah. The problem only occurs with this server and it's not consistent. This morning my client wasn't sending any long packets to it. I don't know what to make of it. I ended up doing the less-than-great practice of widening the `MAX_CHAN_DATA_LEN` to `35000`. Everything seems to work now, but it's not a solution I particularly like.

**Comment by mscdex** [comment]
If this is still an issue with `ssh2` v1.0.0 let me know and I can reopen this.
