### ISSUE TITLE
How to send same command to shell session with different instance?

### ISSUE THREAD

**Issue by sriramulavinaykumar** [mscdex/ssh2#576]
Hi ,
I have a http server running , I'm using ssh2 package for interactive shell session which is serving as a rest API inside HTTP server. First I will send a http request, to start a command (http://localhost:8080?TC=start)
Now the ssh shell is created command executed and I will get some data in realtime on my console.

Next I want to send same command after sometime (http://localhost:8080?TC=start).

Now I want this start command to open a new ssh2 connection,but when i try for second time it is opening two connections . kindly help

```js
dispatcher.onGet("/executessh", function(req, res) {
 var str = '';
 var url = require('url');
 var url_parts = url.parse(req.url, true);
 console.log(url_parts);
 var TC = url_parts.query.TC;
 var TC1 = url_parts.query.TC1;
 var sleep =require('system-sleep');
 var process=require('process');
 var CtrlC = require("ctrl-c");
 if(TC==='start')
 {
 conn.on('ready', function() {
     console.log('Client :: ready');
     conn.shell('sampleWindow', function(err, stream) {
        stream.write('startCommand\n\r');
        if (err) throw err;
        stream.on('close', function(code, signal) {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
        }).on('data', function(data) {
            console.log('STDOUT: ' + data);
            fs.appendFile('D:\\Breme\\sample.txt',data,function(err){
                if(err)
                {
                    console.log(err);
                }       
            });
        }).stderr.on('data', function(data) {
            console.log('STDERR: ' + data);
        });
    });
}).connect({
    host: 'x.x.x.x',
    port: 22,
    username: '123',
    password: '123'
});
}
});
```

**Comment by mscdex** [comment]
> Now I want this start command to open a new ssh2 connection,but when i try for second time it is opening two connections

This isn't quite clear to me. Are you saying there are two connections total open after the second http request, or that it's somehow opening two new connections for a second http request?

**Comment by sriramulavinaykumar** [comment]
when i send this url (http://localhost:8080?TC=start) for the second times ssh shell is opening two times and so on..my problem here is if i send a url for mutlple times start command is also opening for multple times i want it to open for single time each time i send a url..

**Comment by mscdex** [comment]
Then just store your `stream` somewhere in the parent scope where you can get to it between requests. Just make sure to set the variable to `null` when `stream` ends (at which point end the connection) so you don't try to use a closed stream in a future request. If the variable is `null`/false-y, then just create a new connection and re-assign the `stream`. It's a little more involved than that if you want to make it more foolproof (e.g. making sure you only creating one connection at any given time, etc.).

You should also be aware that parsing a `.shell()` stream is difficult, especially when you're reusing the stream between requests. You might instead consider requests adding their command to a queue, which you regularly process and execute commands with `.exec()` for better output handling.
