### ISSUE TITLE
Webpack 2.0 + Babel

### ISSUE THREAD

**Issue by igor-lemon** [mscdex/ssh2#578]
After simple pack with Webpack module doesn't work.
![image](https://user-images.githubusercontent.com/14764799/27111765-08d34684-50bb-11e7-9a95-b840f46b8ce7.png)

**Comment by mscdex** [comment]
I have no idea. I've never used webpack or babel. If I had to guess it's probably a webpack/babel configuration issue.

**Comment by igor-lemon** [comment]
It resolve with simple wrapper
```
define(function (require, exports, module) {
  module.exports ...
});
```

If you want I can make PR.

**Comment by mscdex** [comment]
Honestly I believe this is something that should be resolved outside of this module. If it's not a webpack/babel configuration issue, then I would say it's a bug in one of those packages.
