### ISSUE TITLE
forward issue: (SSH) Channel open failure: Connection refused

### ISSUE THREAD

**Issue by wantg** [mscdex/ssh2#580]
I want connect DATABASE_HOST by ssh connect to SSH_HOST
the SSH_HOST is a bridge

I can build a bridge in bash:
$ ssh  -N  -L  127.0.0.1:3306:DATABASE_HOST:3306  SSH_USER@SSH_HOST  -p  22
after this I can access database_host by connected 127.0.0.1:3306 

with ssh2, my bridge is

```
const net = require('net');
const sshClient = require('ssh2').Client;

const sshConfig = {
    host: 'SSH_HOST',
    port: 22,
    username: 'root',
    password: '1'
};
const forwardConfig = {
    srcHost: 'DATABASE_HOST',
    srcPort: 3306,
    dstHost: '127.0.0.1',
    dstPort: 3306,
};
const dbServer = net.createServer(function(netConnection) {
    const sshConnection = new sshClient();
    sshConnection.on('ready', function() {
        sshConnection.forwardOut(
            forwardConfig.srcHost,
            forwardConfig.srcPort,
            forwardConfig.dstHost,
            forwardConfig.dstPort,
            function(err, sshStream) {
                if (err) {
                    throw err;
                }
                netConnection.pipe(sshStream).pipe(netConnection);
            }
        );
    }).connect(sshConfig);
});

dbServer.listen(forwardConfig.dstPort, forwardConfig.dstHost, function(error, result) {
    if (error) {
        console.log(error);
    } else {
        console.log('success');
    }
});
```

when bridge is finished, I connect 127.0.0.1:3306 with database ueser.
I got
```
Error: (SSH) Channel open failure: Connection refused
    at SSH2Stream.onFailure (/Users/Clint/Projects/xinyi/new/customer-service/node_modules/ssh2/lib/client.js:1195:13)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at SSH2Stream.emit (events.js:210:7)
    at parsePacket (/Users/Clint/Projects/xinyi/new/customer-service/node_modules/ssh2-streams/lib/ssh.js:3707:10)
    at SSH2Stream._transform (/Users/Clint/Projects/xinyi/new/customer-service/node_modules/ssh2-streams/lib/ssh.js:668:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/Users/Clint/Projects/xinyi/new/customer-service/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:371:12)
```

**Comment by wantg** [comment]
It always connect SSH_HOST:3306 whether srcIP in forwardOut function.
I got error in my code because SSH_HOST did not enable 3306 port.

**Comment by mscdex** [comment]
I think you have 'src' and 'dst' swapped. 'dst' is where you're connecting *to*, 'src' is where you're connecting *from*.

'src', isn't typically a configured thing, it's just whatever you want to put in there. When you have a local TCP server, you could just use the local connection's address and port for 'src' (available via [`netConnection.address()`](https://nodejs.org/docs/latest/api/net.html#net_socket_address)).

'dst' would be the address and port of your database server relative to the ssh server. So if you use '127.0.0.1' for the address, then that's saying that the database server is on the ssh server. If it's actually on some other system on the LAN, then you would use that LAN address for the 'dst' address instead.
