### ISSUE TITLE
Keys from agent are loaded in reverse order

### ISSUE THREAD

**Issue by rmccue** [mscdex/ssh2#581]
I have 6 keys loaded into my agent. When connecting with ssh2, these are tried in reverse order, which causes me to hit the authentication attempt limit before being able to connect, since the right key is the first one.

I can verify this by changing [client.js#449](https://github.com/mscdex/ssh2/blob/ba5fd57f802deb37a550d54b6bc73355617d0462/lib/client.js#L449) to `agentKeys = keys.reverse()`, which causes them to be attempted in the correct order.

**Comment by mscdex** [comment]
Keys are attempted in the order that the agent gives them. As of `ssh2` v1.0.0 there is more flexible authentication handling, which should allow you to customize the behavior of agent key handling for example (should you want to reverse or filter the keys returned by the agent).
