### ISSUE TITLE
SFTP fastGet appends absolute path

### ISSUE THREAD

**Issue by c100k** [mscdex/ssh2#582]
Hi,
I'm trying to get a file from a SFTP server :

```javascript
sftp.fastGet('my-file.csv', '/tmp/my-file-local.csv', {}, (error) => {
    client.end();
    if (error) {
        console.log(error);
        return error;
    }
    console.log('success');
    return 'success';
});
```

I have the following error :

> Error: Internal NoSuchFileException: /dir1/dir2/my-file.csv

The problem is that when I connect to the SFTP server, I'm already in `/dir1/dir2` and I don't have the permissions to go back. All the operations must be done within this directory.

Is there a way of avoiding to append the full absolute path on the server when trying to get the file ?
Because currently, I think it tries to find the file `/dir1/dir2/dir1/dir2/my-file.csv`, that obviously does not exist.

Note that `readdir` works well and does not behave the same. Not also that adding `./my-file.csv` does not work neither.

Not sure if this is a bug or not.
Thanks

**Comment by mscdex** [comment]
It's not a bug, paths are sent as-is to the server. The goal of this module and `ssh2-streams` are to provide a foundation that others can build on. There are other modules on npm that do build on this and I wouldn't be surprised if there was one that kept track of the current working directory and such (as much as possible).
