### ISSUE TITLE
How to conn setMaxListeners?

### ISSUE THREAD

**Issue by dev-juyoung** [mscdex/ssh2#583]
Hello,
I'm developing sftp related function using ssh2 module.
There is a problem using the ssh module. So create issues.

This Error Log
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 
11 ready listeners added. Use emitter.setMaxListeners() to increase 
  | process.on | @ | internal/process/warning.js:21
  | emitOne | @ | events.js:96
  | emit | @ | events.js:191
  | process.nextTick | @ | internal/process/warning.js:47
  | _combinedTickCallback | @ | internal/process/next_tick.js:73
  | _tickCallback | @ | internal/process/next_tick.js:104


```

The code that is currently experiencing the problem.
```
// other code...
import { Client } from 'ssh2';

const conn = new Client();
const config = {
  host: database.sftpURL,
  port: database.sftpPORT,
  username: database.sftpUsername,
  password: database.sftpPassword,
};

// connect conn and return sftp object using Promise Patterns
function connectSFTP() {
  return new Promise((resolve, reject) => {
    conn.on('ready', () => {
      conn.sftp((err, sftp) => {
        if (err) reject({ error: err, message: 'Blah Blah' });
        resolve(sftp);
      });
    }).connect(config);
  })
}

// cllas connectSFTP()
function methodName(cb, errorCb) {
  connectSFTP()
  .then(sftp => Promise.resolve(otherMethod(sftp)))
  .then((data) => {
    conn.end();
    cb(data);
  })
  .catch((err) => {
    conn.end();
    errorCb(err)
  });
}

function otherMethod(sftp) {
  return new Promise((resolve, reject) => {
    sftp.readdir('.', (err, files) => {
      if (err) reject({ error: err, message: 'Blah Blah' });
      resolve(files);
    });
  });
}
```
I'm using code similar to the above.
The problem is that up to ten Listeners register on the node is the default, an error occurs on the 11th call.

So, to solve this problem,
I set `conn.setMaxListeners(0)` but the problem is not solved.

**How can i solve this problem**
**Please help us solve the problem!**

**Comment by mscdex** [comment]
You're creating a single connection object once *and* using `.on()` which does not remove the event handler after the first time. So you will need to either not reuse the connection object (probably a better idea since repeated calls to functions that call `connectSFTP()` could disrupt commands currently being executed) *or* use `.once()` so that the `'ready'` event handler is removed once the event is emitted.

**Comment by dev-juyoung** [comment]
I have tested it.
on() to once() changed confirm that it works.
Thanks for suggesting a solution.
