### ISSUE TITLE
reverse SSH tunnel destination IP & port

### ISSUE THREAD

**Issue by skunkwerk** [mscdex/ssh2#584]
The forwardIn method doesn't seem to allow for a destination IP & port:
https://github.com/mscdex/ssh2/blob/master/lib/client.js#L916

Example use case:
Forward port 3000 on the server, through my SSH client, to the IP & port of my database which is behind the firewall.

I can do this with the built-in ssh command in my shell like so:
ssh -f -N -T -R3000:database.rds.amazonaws.com:5432 -i aws-key ec2-user@IPaddress

Is it possible to do this with the ssh2 library?  Thanks

**Comment by mscdex** [comment]
Providing local TCP/SOCKS connections is not one of the goals of this module.

So for `forwardOut()` that means you will need to use `net.createServer()` locally and use `forwardOut()` for each incoming local socket.

For `forwardIn()` that means you will need to use `net.connect()` locally to forward the incoming remote connection to wherever it should go.

**Comment by skunkwerk** [comment]
Got it @mscdex - that makes sense.  But is there a way to specify the local port that forwardIn should use?

**Comment by mscdex** [comment]
@skunkwerk I don't understand what you're asking. There is no "local" port, you have to do that part yourself. When you get a `'tcp connection'` event after calling `forwardIn()`, you just do `net.connect()` to the correct (local) destination host and port based on the remote address and port, and then pipe between the two streams.

**Comment by skunkwerk** [comment]
Got it.  Used this code to get it working:

`var conn = new Client();
conn.on('ready', function() 
{
  console.log('Client :: ready');
  conn.forwardIn('127.0.0.1', 8000, function(err) 
  {
     if (err)
     {
    	errors.push(err);
    	throw err;
  	 }
     console.log('Listening for connections on server on port 8000!');
  });
}).on('tcp connection', function(info, accept, reject) 
{
  console.log('TCP :: INCOMING CONNECTION:');
  console.dir(info);

  var srcSocket = new Socket();

  srcSocket.connect(remote_port, 'remote_url', function()
  {
	  remote = accept();
	  console.log('accept remote connection');
	  srcSocket.pipe(remote).pipe(srcSocket);
	  if (errors.length === 0)
	  {
	    console.log('no errors');
	  } else 
	  {
	    console.log('errors');
	  }
  });
}).connect(
{
  host: 'yourIP',
  port: 22,
  username: 'username',
  privateKey: require('fs').readFileSync('tunnel.key')
});`

**Comment by Trickfilm400** [comment]
@mscdex 

> Providing local TCP/SOCKS connections is not one of the goals of this module.
> 
> So for outbound forwarding (OpenSSH's '-L') that means you will need to use `net.createServer()` locally and use `forwardOut()` for each incoming local connection.
> 
> For inbound forwarding (OpenSSH's '-R') that means you will need to use `net.connect()` locally to forward the incoming remote connection to wherever it should go.

well, I am using `ssh -N  -p 20 -R8080:localhost:4002 user@SSH2-SERVER-IP` 
I had to use `net.createServer` 
```javascript
net.createServer(info.bindAddr, info.bindPort, function(socket) {
      client.forwardOut( info.bindAddr, info.bindPort, socket.remoteAddress, socket.remotePort,
        (err, upstream) => {
          if (err) {
            socket.end();
             return console.error('not working: ' + err);
          }
	  console.log('forward data', socket.remoteAddress, socket.remotePort, info.bindAddr, info.bindPort);
         upstream.pipe(socket).pipe(upstream);
         });
}).listen(info.bindPort);
```

so, are the OpenSSL "-R" and "-L" are exchanched or am I doing something wrong?

My plan was to tunnel ports from my pc over the ssh2 server and I am executing the SSH command on my PC

**Comment by mscdex** [comment]
@Trickfilm400 Your code is performing the equivalent of `-L` in OpenSSH.

In OpenSSH, `-L` tunnels from client to server and `-R` tunnels from server to client.
