### ISSUE TITLE
Can't Login using this module ssh2

### ISSUE THREAD

**Issue by ronovar** [mscdex/ssh2#585]
I im using this code:

```js
var client 		   = require('ssh2').Client;		// USE - ssh2
var conn 		   = new client();					// USE - conn
conn.on('error', function(err) {
  console.log('SSH - Connection Error: ' + err);
});

conn.on('end', function() {
  console.log('SSH - Connection Closed');
});

conn.on('ready', function() {
  // code to work with SSH
  console.log('connected...');
});

conn.connect({
  host: '209.239.122.182',
  port: 22,
  username: 'root',
  tryKeyboard: true,
  debug: console.log
});

conn.on('keyboard-interactive', function(name, instructions, lang, prompts, cb){
  cb(['myserverpass']);
});
```

I can't login to my ssh server using this module...using putty it works fine and my server is using password user auth. method...this is log:

```
DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.19'
DEBUG: Client: Trying 209.239.122.182 on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:972,padLen:10,remainLen:968
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: KEX algorithm: ecdh-sha2-nistp256
DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
DEBUG: (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
DEBUG: Host key format: ssh-rsa
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXECDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:636,padLen:7,remainLen:632
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Outgoing: Writing NEWKEYS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (keyboard-interactive)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: keyboard-interactive auth failed
SSH - Connection Error: Error: All configured authentication methods failed
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
SSH - Connection Closed
```

What i should do next to find where i im making mistake?

**Comment by mofux** [comment]
With your config, you are only dealing with the `keyboard-interactive` method for authentication (which is not widely used), which seems to fail. Are you sure the server is not simply asking for `password` authentication instead? Try to add the `password` option to your config like this:

```javascript
conn.connect({
  host: '209.239.122.182',
  port: 22,
  username: 'root',
  password: 'myserverpass',
  tryKeyboard: true,
  debug: console.log
});
```

**Comment by ronovar** [comment]
Thanks for replaying...error is the same...do you have idea what to try next? Using putty it works...here is login from putty:
    Trying 209.239.122.182 (PORT: 22)...
Connected to 209.239.122.182.
Requesting SSH2 session...
Trying 'password' user auth. method...
'password' user auth. method succeeded!
SSH2 session started.

Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-042stab123.1 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Thu Jul 13 11:43:24 2017 from 185.168.116.51
root@usve255723:~#

**Comment by mofux** [comment]
Could you post the ssh2 client log output with the updated password authentication method?

**Comment by ronovar** [comment]
Here is it using config code above:
     DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.19'
DEBUG: Client: Trying 209.239.122.182 on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:972,padLen:10,remainLen:968
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: KEX algorithm: ecdh-sha2-nistp256
DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
DEBUG: (remote) Host key formats: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
DEBUG: Host key format: ssh-rsa
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXECDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:636,padLen:7,remainLen:632
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Outgoing: Writing NEWKEYS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: password auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (keyboard-interactive)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: keyboard-interactive auth failed
SSH - Connection Error: Error: All configured authentication methods failed
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
SSH - Connection Closed

If you need ssh password so that you can try please write your mail and i will send it to you.This way will be easy to you to track where error is...thanks

**Comment by mofux** [comment]
Does your password contain a `\` (backslash)? If so, you have to terminate the password string by replacing `\` with `\\`

**Comment by ronovar** [comment]
This is example of my password:

    Py5XpykNPVPc7UUr

It does not contains any \ or \\ or any special characters..above example of password is how long password is and what character it contains....

**Comment by mofux** [comment]
Try to check the /var/log/auth.log file on the server, maybe it has more information on why the authentication failed. You should also remove the keyboard interactive code from your example as it should not be needed.

**Comment by ronovar** [comment]
keyboard code removed and this is the log from /var/log/auth.log

    Jul 13 14:16:09 usve255723 sshd[5072]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=116.31.116.24  user=root
Jul 13 14:16:09 usve255723 sshd[5074]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=221.194.47.236  user=root
Jul 13 14:16:10 usve255723 sshd[5072]: Failed password for root from 116.31.116.24 port 23053 ssh2
Jul 13 14:16:11 usve255723 sshd[5074]: Failed password for root from 221.194.47.236 port 54735 ssh2
Jul 13 14:16:12 usve255723 sshd[5072]: Failed password for root from 116.31.116.24 port 23053 ssh2
Jul 13 14:16:13 usve255723 sshd[5076]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=5.189.191.78  user=root
Jul 13 14:16:13 usve255723 sshd[5074]: Failed password for root from 221.194.47.236 port 54735 ssh2
Jul 13 14:16:15 usve255723 sshd[5072]: Failed password for root from 116.31.116.24 port 23053 ssh2
Jul 13 14:16:15 usve255723 sshd[5072]: Received disconnect from 116.31.116.24 port 23053:11:  [preauth]
Jul 13 14:16:15 usve255723 sshd[5072]: Disconnected from 116.31.116.24 port 23053 [preauth]
Jul 13 14:16:15 usve255723 sshd[5072]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=116.31.116.24  user=root
Jul 13 14:16:15 usve255723 sshd[5076]: Failed password for root from 5.189.191.78 port 50931 ssh2
Jul 13 14:16:15 usve255723 sshd[5076]: Received disconnect from 5.189.191.78 port 50931:11:  [preauth]
Jul 13 14:16:15 usve255723 sshd[5076]: Disconnected from 5.189.191.78 port 50931 [preauth]
Jul 13 14:16:16 usve255723 sshd[5074]: Failed password for root from 221.194.47.236 port 54735 ssh2
Jul 13 14:16:16 usve255723 sshd[5074]: Received disconnect from 221.194.47.236 port 54735:11:  [preauth]
Jul 13 14:16:16 usve255723 sshd[5074]: Disconnected from 221.194.47.236 port 54735 [preauth]
Jul 13 14:16:16 usve255723 sshd[5074]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=221.194.47.236  user=root
Jul 13 14:16:19 usve255723 sshd[5078]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=221.194.47.236  user=root
Jul 13 14:16:21 usve255723 sshd[5078]: Failed password for root from 221.194.47.236 port 36325 ssh2
Jul 13 14:16:25 usve255723 sshd[5078]: message repeated 2 times: [ Failed password for root from 221.194.47.236 port 36325 ssh2]
Jul 13 14:16:26 usve255723 sshd[5078]: Received disconnect from 221.194.47.236 port 36325:11:  [preauth]
Jul 13 14:16:26 usve255723 sshd[5078]: Disconnected from 221.194.47.236 port 36325 [preauth]
Jul 13 14:16:26 usve255723 sshd[5078]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=221.194.47.236  user=root

I did not understand this maybe you have idea what is going on using this log above posted?

**Comment by ronovar** [comment]
i think that password is not send correctly to the server..you see that my ip is: 5.189.191.78 so i see port 50931 

Jul 13 14:16:15 usve255723 sshd[5076]: Failed password for root from 5.189.191.78 port 50931 ssh2

why is port 50931 and i include this code;

    conn.on('error', function(err) {
					  console.log('SSH - Connection Error: ' + err);
					});

					conn.on('end', function() {
					  console.log('SSH - Connection Closed');
					});

					conn.on('ready', function() {
					  // code to work with SSH
					  console.log('connected...');
					});

					conn.connect({
						host: rows[0].ip,
						port: 22,
						username: 'root',
						password: decrypt(rows[0].pass),
						debug: console.log
					});

You see here is defined port 22 and this port must be using and i see above in log file 50931

**Comment by mscdex** [comment]
50931 is the ephemeral port, not the port sshd is listening on.

Since PuTTY works with the 'password' auth, then using the `password` property in the connection config is correct. However, is it possible that `decrypt()` is not returning the correct password?

**Comment by ronovar** [comment]
decrypt() is returning correct password without space or any special characters..for testing i put now password in 'Py5XpykNPVPc7UUr' and try and error is the same.

I now put manually password 'Py5XpykNPVPc7UUr' and will be testing for futher notes...does your module have some console log to output what is sending to ssh server (user and password) and what is returned from server.

**Comment by mscdex** [comment]
No it does not log that information. I doubt it's being sent wrong though.

Have you tried using a key for authentication (for the same user) to see if that works? Have you tried connecting to other systems with a `password` set?

**Comment by ronovar** [comment]
It works on another server (dedicated) on VPS server it failed...thanks...this works now and problem is in VPS server...on another server i connect and execute uptime and i get this:

    STDOUT:  18:12:17 up 13:11,  0 users,  load average: 2.79, 3.64, 3.61

So all is working now..thanks for your help.
