### ISSUE TITLE
Whats the correct way to cleanup a call to forwardOut

### ISSUE THREAD

**Issue by clickstreammedia** [mscdex/ssh2#586]
I'm experiencing a memory leak when calling `forwardOut` many times on the same ssh connection.
Is there anyway to clean up a call that looks like this:

```
	var result = sshClient.forwardOut( '127.0.0.1', null, host, port, function( error, stream ) {
		
	} );
```

Is there anything I can call on `result` or `stream` to prevent a memory leak?

Sorry for the vague example

**Comment by clickstreammedia** [comment]
cc @mscdex

**Comment by mscdex** [comment]
You can `stream.close()` to forcibly close the stream.
