### ISSUE TITLE
Handle invalid source IP

### ISSUE THREAD

**Issue by qq351844** [mscdex/ssh2#587]
Hi,
I will use the POST method to get the source IP.
But I want to handle the invalid source IP that I don't give the ssh_key.
First, I use the try catch to handle the error, but this method can't use.
The following is my error message.
Thanks~

`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect EHOSTUNREACH 10.217.137.192:22
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)`

**Comment by mscdex** [comment]
I think there's some context missing here. I don't understand what it is you're trying to do code-wise. Whatever it is, you're trying to connect to an IP address that is not reachable using your current OS routing table.

**Comment by qq351844** [comment]
I design a simple system to use  interface to login the server and do some command line instruction.
So the service allow user to login the server IP they want.
If the user give the IP that I don't add the key or some invalid IP, it will get some error.
First, I use the try catch to avoid this this situation.  But this method is useless and the back-end  server will crash. I can't get other error information if the user give the invalid IP.
Thanks.
