### ISSUE TITLE
Question: List folders on openDir

### ISSUE THREAD

**Issue by ddibiase** [mscdex/ssh2#588]
I'm wondering how I should be structuring the handle() method to display subfolders. This is what I currently have:

      stream.name(
        reqid,
        [{
          filename: file.ID,
          longname: `-rwxrwxrwx ${session.openFiles[handle].length} dfx dfx ${file.Created} /${file.ID}/`,
          attrs: {}
        }]
      );
But I need each file to read as a folder :-/ the documentation doesn't seem to make that clear unless I missed it.

Thanks!

**Comment by mscdex** [comment]
I don't understand what you're asking. The question and the code snippet you've posted don't seem to match. As shown in [the SFTPStream documentation](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md#sftpstream-events) the `'OPENDIR'` event should be responded to using `handle()` in the success case or `status()` in the failure case. The `'READDIR'` event should be responded to using `name()` in the success case or `status()` in the failure case.

For `'READDIR'`, you should only be replying with the immediate files/subdirectories in the directory that was opened (according to the passed handle). For the `longname`, you *should* make sure that the file/directory mode bits, size, ownership/group, last modified date, etc. are properly shown (according to `ls -l` output on a *nix system).

**Comment by ddibiase** [comment]
Heh, very sorry about that. I posted the question in haste. I'm returning the results with name() in the READDIR callback and need to set the values properly to display as folders. In the previous example I forgot `d` as the first field flag but now it's in there and not displaying as folders :-/ here's a sample of what I'm sending:

      stream.name(
        reqid,
        [{
          filename: file.ID,
          longname: `drwxrwx--- 1 dfx dfx 500 ${file.Created} ${file.ID}`,
          attrs: {
            mode: 755,
            uid: 'dfx',
            gid: 'dfx',
            mtime: 1500479191,
            atime: 1500479191,
            size: 500
          }
        }]
      );
Sorry I'm not used to dealing with this protocol, learning as I go.

**Comment by mscdex** [comment]
For directories, you need to also include any relevant file type bits. In the case of a directory, it would be `S_IFDIR`, which is 16384 (or `0o40000` in octal). Additionally, you must use octal format to get the correct permission values, since `755` is treated as a decimal. Use the literal `0o755` instead. Together you could do `0o755 | 0o40000` or `0o755 | fs.constants.S_IFDIR` to get the appropriate `mode` value for a directory with those permissions.

**Comment by ddibiase** [comment]
Ahhhhaaaaa. Ok that makes much more sense now. Thank you very much for your help.
