### ISSUE TITLE
Can we connect to FTP server (not sftp) using SSH2? 

### ISSUE THREAD

**Issue by dsouzamanish** [mscdex/ssh2#591]
I want to connect to FTP server. Since i am already using this module in my project can i use it to connect to ftp server instead of adding one more dependency to the project.
When i try to connect to FTP server it returns with the error
**Error: Timed out while waiting for handshake**
Please Help

**Comment by mscdex** [comment]
SFTP is not the same thing as FTP or FTPS. It's a *completely* different protocol (SFTP is much more sane). Therefore there will be no FTP/FTPS support for this module.
