### ISSUE TITLE
[solved] using ssh agent (was: ssh key format?)

### ISSUE THREAD

**Issue by gregfr** [mscdex/ssh2#598]
Greetings
I'm trying to use ssh2 to connect with my openssh key, and get an error:

```InvalidAsn1Error: Expected 0x2: got 0x34```

I've tried to use other format available to me by openssh: PEM, PKCS8, and RFC4716. They all give an error:

```Error: Cannot parse privateKey: Unsupported key format```

What format should I use and how can I convert my openssh key?

Thanks in advance

**Comment by mscdex** [comment]
PEM is simplest. What type of key were you trying initially that resulted in the `InvalidAsn1Error`? Was it encrypted?

**Comment by gregfr** [comment]
Thanks for you answer. I'm trying to use an encrypted openssh private rsa key with key agent running. The header is:
```-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,4921477C5DD06F31BC03AB2998F8ED92
```

**Comment by mscdex** [comment]
If you're passing an encrypted key to `privateKey`, then you need to also set `passphrase` to be able to decrypt the key.

The other option is to use an ssh-agent, which only stores the unencrypted copy in memory (this is why it prompts for the passphrase when adding an encrypted key to an ssh-agent). If you want to do this, then you should not use `privateKey`, but instead the `agent` option, set to the path of the ssh-agent's unix socket (typically `process.env.SSH_AUTH_SOCK`).

**Comment by gregfr** [comment]
Thanks for you answer. I added:
```agent: process.env.SSH_AUTH_SOCK```
to the connect parameters object.

If I don't give a passphrase, I get:
```Error: Encrypted private key detected, but no passphrase given```

With an empty passphrase:
```InvalidAsn1Error: Expected 0x2: got 0x1a```

With a bogus passphrase:
```InvalidAsn1Error: encoding too long```

**Comment by mofux** [comment]
But have you also tried without `privateKey` set?

**Comment by mscdex** [comment]
Something also to keep in mind is that you can get the `InvalidAsn1Error` if the passphrase is incorrect.

**Comment by ChristianDavis** [comment]
same issue, can connect through SFTP CLI with the private key generated from openssh, but SSH2 gives: Unsupported key format

**Comment by mscdex** [comment]
@ChristianDavis Are you explicitly setting `privateKey`? If so, what type of key is it (what header does it have)? For example, ed25519 keys are not supported due to lack of support on OpenSSL's side (although I believe that will change or has already changed in upcoming OpenSSL versions -- which are not merged into node yet).

**Comment by gregfr** [comment]
> But have you also tried without privateKey set?

I'm confused, if I don't set the private key, it doesn't seem to find it:

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
```

>Something also to keep in mind is that you can get the InvalidAsn1Error if the passphrase is incorrect.

No passphrase here, since I'm (trying to) using the agent.

Here is my code:

```
connect({
    host: 'my.host.name',
    port: 122,
    username: 'root',
    agent: process.env.SS_AUTH_SOCK
});
```

If I tried direct CLI:

```
ssh -p 122 -l root my.host.name
```

I get connected right away.

**Comment by gregfr** [comment]
Also if I used node's "exec" method it's working too:

```
const exec = require('child_process').exec;
var child = exec('ssh -p 122 -l root my.host.name');
```

**Comment by mscdex** [comment]
@gregfr It's `process.env.SSH_AUTH_SOCK`, not `process.env.SS_AUTH_SOCK`.

**Comment by gregfr** [comment]
wow how did the H disappear? I even have a `console.log(process.env.SSH_AUTH_SOCK);` which is a copy&paste.
You have hawk eyes thanks a lot it's working!

**Comment by gregfr** [comment]
So to sum up, in order to use agent:

- set `agent: process.env.SSH_AUTH_SOCK`
- don't set the privateKey
- don't set the passphrase

**Comment by mscdex** [comment]
@gregfr Glad to hear you got it working.

@ChristianDavis Please open a new issue about the problem you're facing if it's still occurring.
