### ISSUE TITLE
Firefox triggers ECONNRESET error on SFTP server

### ISSUE THREAD

**Issue by ameliusg** [mscdex/ssh2#600]
When running the sftp server example on port 50000, and using an "sftp://example.com:50000" style url in the address bar of Firefox 54.0.1, I'm getting an ECONNRESET error on the server. (Using a normal command-line sftp client, the server works normally.) See error below:

    SFTP EXCEPTION: { Error: read ECONNRESET
        at exports._errnoException (util.js:1026:11)
        at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by mscdex** [comment]
I don't think Firefox has a built-in sftp client. Is this perhaps an extension/addon providing this functionality, or is it actually opening up an OS-provided sftp client?

**Comment by mscdex** [comment]
Additionally, it may help to provide the resulting output when adding `debug: console.log` to the server config object.

**Comment by ameliusg** [comment]
I just tested again, and I have it working now. I think I did something wrong with the authentication methods.

This issue can be closed.
