### ISSUE TITLE
Bypass .bashrc on remote server using shell()?

### ISSUE THREAD

**Issue by fuchsm** [mscdex/ssh2#601]
I'm having a situation where I want to bypass the processing of .bashrc on a remote server. 

I achieved this by using exec('bash --norc --noprofile', { pty: true }, ...) , but the problem is that this way, I won't get a continuous r/w stream into the callback -  which I need for using expectly-stream.  

I also tried using shell() (which would give me such a stream), but since this mechanism creates an interactive terminal session and then waits for commands instead of executing a command via SSH directly, there is no way to bypass .bashrc - at least not one that I'm aware of. It would already help if I could continue the session with a r/w stream where the exec() left off.

Is there a way to achieve what I want?

**Comment by mscdex** [comment]
The stream passed to `exec()` callbacks definitely is a duplex stream. What problem in particular are you having with that?

**Comment by fuchsm** [comment]
Oh, Indeed! The problem was elsewhere - namely trying to write to the stream that got accidentally closed by the on-closed event before trying to write to it - which is kind of stupid. But thanks for the response anyway - at least it helped me sorting out the issue. Sorry!
