### ISSUE TITLE
How to connect without private key

### ISSUE THREAD

**Issue by JenneyJ** [mscdex/ssh2#602]
HI,

Im running my App inside cloud and I want to connect to other app via ssh (inside the cloud- this is possible via CMD),
In your lib you need to provide the privateKey otherwise you **get an erro****r**, when using the SSH client there is a way to avoid it? 

something like this? 

}).connect({
    host: 'ssh.cf.mycompany.com',
     port: 2222,
     username: 'cf:181crrr2-7096-45b6-3ae6-1df4dbd74772/0'
 });

**Comment by mscdex** [comment]
Are you using an ssh-agent? If so, you typically just need to set `agent: process.env.SSH_AUTH_SOCK` in your connection config object. If not, you will need to set `privateKey` if you're not using a password or other method. OpenSSH automatically tries keys in certain paths (e.g. '~/.ssh/id_rsa') but `ssh2` will not do this for you.

**Comment by JenneyJ** [comment]
Im using this flow
Application SSH Access **without** cf CLI
as you can see I Dont need to add private key
https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html

I prefer to use your Lib but it's required 
https://stackoverflow.com/questions/45592193/how-to-use-cf-ssh-in-diego
Can you please provide some hint ?

**Comment by mscdex** [comment]
That document clearly says you should be using a password, provided by `cf ssh-code` (see the section titled "Application SSH Access without cf CLI").

**Comment by JenneyJ** [comment]
So for private key I should put the password ?

**Comment by mscdex** [comment]
No, for passwords you use the `password` connection config option.

**Comment by JenneyJ** [comment]
I try it like this and I got error 

017-08-16T16:09:35.11+0300 [APP/PROC/WEB/0] ERR       throw er; // Unhandled 'error' event
   2017-08-16T16:09:35.11+0300 [APP/PROC/WEB/0] ERR       ^
   2017-08-16T16:09:35.11+0300 [APP/PROC/WEB/0] ERR Error: All configured authentication methods failed   2017-08-16T16:09:35.11+0300 [APP/PROC/WEB/0] ERR     at tryNextAuth (/home/vcap/app/node_modules/ssh2/lib/client.js:380:17)
   2017-08-16T16:09:35.11+0300 [APP/PROC/WEB/0] ERR     at SSH2Stream.onUSERAUTH_FAILURE (/home/vcap/app/node_modules/ssh2/lib/client.js:591:5)

This is the code
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
    console.log('Client :: ready');
    conn.exec('uptime', function(err, stream) {
        if (err) throw err;
        stream.on('close', function(code, signal) {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
        }).on('data', function(data) {
            console.log('STDOUT: ' + data);
        }).stderr.on('data', function(data) {
            console.log('STDERR: ' + data);
        });
    });
}).connect({
    host: 'ssh.cf.mydomain.com',
    port: 2222,
    username: 'cf:181c32e2-7096-45b6-9ae6-1df4dbd74782/0',
    password:'qG4Ztpu1Dh'

});


Do you have an suggestion what is missing ?

Thanks for your support!!!

**Comment by mscdex** [comment]
Sorry, I'm not familiar enough with CloudFoundry. All I can go on is what I read in that document. Are you able to connect using the OpenSSH client using the exact same connection configuration?

**Comment by JenneyJ** [comment]
Yes when I use cf ssh <appName> in the command line I was able to connect immediately ... 
So you think that my configuration is valid ?

**Comment by mscdex** [comment]
No, using the *OpenSSH client* (just `ssh2`, not `cf ssh`). They show examples in steps 4 and 5 in the previously referenced section.

**Comment by JenneyJ** [comment]
In section 4 there suggestion to use ssh -p 2222 cf:abcdefab-1234-5678-abcd-1234abcd1234/0@ssh.MY-DOMAIN.com 
when I try it I got after 1 min 
ssh: connect to host ssh.mydomain.com port 2222: Operation timed out

is it related ? does it what you mean...

**Comment by mscdex** [comment]
If connecting with the OpenSSH client doesn't work, then `ssh2` won't work either. Sorry, as previously mentioned I've never used CloudFoundry before, so I cannot really help with the connection/authentication issue. All I can tell you is that according to that guide you will be using a password for authentication, not a private key.
