### ISSUE TITLE
SSH agent forwarding test with 2 servers

### ISSUE THREAD

**Issue by calvinlcz** [mscdex/ssh2#603]
Hi,

I am testing out on implementing SSH agent forwarding on 2 servers. I manage to connect and run the command 'hostname' on the first connection to the first server, but I can't seem to connect to the second server despite enabling agent forwarding. Is there something wrong with my code implementation?

My code:

```
var Client = require('ssh2').Client;

var conn1 = new Client();
var conn2 = new Client();
conn1.on('ready', function () {
	conn1.exec('hostname', function (err, stream) {
		if (err) throw err;
		stream.on('data', function (data, stderr) {
			if (stderr)
				console.log('STDERR: ' + data);
			else
				console.log('STDOUT: ' + data);
		}).on('exit', function (code, signal) {
			console.log('Exited with code ' + code);
		});
		conn2.on('ready', function () {
			conn2.exec('hostname', function (data, stderr) {
				if (err) throw err;
				stream.on('data', function (data, stderr) {
					if (stderr)
						console.log('STDERR: ' + data);
					else
						console.log('STDOUT: ' + data);
				}).on('exit', function (code, signal) {
					console.log('Exited with code ' + code);
				});
			});
		}).connect({
			host: 'IP of second server',
			username: 'myUsername',
		});
	});
}).connect({
	host: 'IP of first server',
	username: 'myUsername',
	privateKey: require('fs').readFileSync('/path/to/private/key'),
	agent: '/path/to/agent/socket',
	agentForward: true,
});
```

Any suggestions/help would be appreciated!

**Comment by mscdex** [comment]
If `privateKey` is being used to successfully authenticate, then `agent` will never be used and thus agent forwarding won't happen.

**Comment by calvinlcz** [comment]
Thanks for the clarification! Is there anyway that I can make SSH agent forwarding to work? Basically what I mentioned is that I want to connect my local machine to the first server using my machine's SSH key, and from that server it'll use my local machine's SSH key to try to connect to the second server by SSH agent forwarding.

**Comment by mscdex** [comment]
The ssh-agent is being used both times right? If so, then just remove `privateKey` from the connection config object.

**Comment by mscdex** [comment]
So you're wanting to do connection hopping? If so, then that won't work with your current code. Currently you're making two outbound ssh connections from your local machine.

To connection hop, see the [Connection Hopping](https://github.com/mscdex/ssh2#connection-hopping) example in the readme. Note you will probably be better off using `conn1.forwardOut()` instead of `conn1.exec('nc ...')` in that example to create the connection to the second server.

To add the agent forwarding, just set `agent` and `agentForward` for both connections.

**Comment by calvinlcz** [comment]
Thanks for the advice! It finally worked!
