### ISSUE TITLE
Method to detect unexpected disconnection between two endpoints

### ISSUE THREAD

**Issue by calvinlcz** [mscdex/ssh2#605]
During connection hopping from first instance to another, is there any way/method by the ssh2 library to detect which connection to a server instance is disconnected unexpectedly?

Example: local terminal -> instance-1 -> instance-2, -> is connection. The connection between instance-1 and instance-2 is disconnected unexpectedly. The program throw an error when exec() is invoked stating connection between instance-1 and instance-2 is disconnected.

**Comment by mscdex** [comment]
Add an `'error'` event handler on the connection object.

**Comment by calvinlcz** [comment]
It works for my first connection, but it doesn't work for my second connection.

**Comment by calvinlcz** [comment]
When I shut down my instance-2, the connection that's connecting between instance-1 to instance-2 doesn't throw an error. But when I shut down my instance-1, the connection that's connecting between local terminal to instance-1 does throw an error.

**Comment by mscdex** [comment]
Can you show the code you're using?

**Comment by calvinlcz** [comment]
`var Client = require('ssh2').Client;

var conn1 = new Client();
var conn2 = new Client();
conn1.on('ready', function () {
	console.log('FIRST :: connection ready');
	conn1.exec('nc some IP', function (err, stream) {
		if (err) throw err;
		conn2.connect({
			sock: stream,
			username: 'something',
			agent: process.env.SSH_AUTH_SOCK,
			agentForward: true,
		});
	});

}).connect({
	host: 'some IP',
	username: 'something',
	agent: process.env.SSH_AUTH_SOCK,
	agentForward: true,
}).on('error', function (err) {
	throw err;
});

conn2.on('ready', function () {
	console.log('SECOND :: connection ready');

}).on('error', function (err) {
	throw err;
});`

The conn1 will throw error when I shut down my my first server, but conn2 will not throw error when I shut down my second server.

**Comment by mscdex** [comment]
If this is still an issue with `ssh2` v1.0.0 let me know and I can reopen this.
