### ISSUE TITLE
Copy file content got some error

### ISSUE THREAD

**Issue by JenneyJ** [mscdex/ssh2#606]
HI,

I've tried the following code to copy file from server to local file
i've created the local file (with the same name)  on my root project
And use the following 

var conn = new Client();
        conn.on('ready', function () {
            conn.sftp(function (err, sftp) {
                if (err) throw err;

                var moveFrom = "/home/app/html";
                var moveTo = "/Users/i034665/WebstormProjects/apptest/index.html";

                sftp.fastGet(moveFrom, moveTo, {}, function (downloadError) {
                    if (downloadError) throw downloadError;

                    console.log("Succesfully uploaded");
                });
            });
        }).connect({

The error is:

 if (downloadError) throw downloadError;
   2017-08-24T23:18:56.85+0300 [APP/PROC/WEB/0] ERR Error: ENOENT: no such file or directory, open '/Users/i034665/WebstormProjects/apptest/index.html'

But I've created the file in the path that I've provided , Do you have an idea what it could be ?

I try to chmod the file but it doesnt help...

**Comment by JenneyJ** [comment]
When I change the moveTO
`var moveTo = "/index.html";`

I got error of permission denied 

so I use this code 

 ```
console.log("open tunnel");
var conn = new Client();
conn.on('ready', function () {
            conn.sftp(function (err, sftp) {
                if (err) throw err;

                console.log("start chmod");
                sftp.chmod("/index.html", 777, function (err) {
                    if (err) {
                        console.log("Error, problem starting SFTP: %s", err);
                    }
                    else {
                        console.log("Mode changed");
                        var moveFrom = "/home/app/html";
                 
                        var moveTo = "/index.html";

                        sftp.fastGet(moveFrom, moveTo, {}, function (downloadError) {
                            if (downloadError) throw downloadError;

                            console.log("Succesfully uploaded");

                        });

                    }
                }).connect({


But I see in the log just 

`2017-08-25T00:32:15.95+0300 [APP/PROC/WEB/0] OUT open tunnel`
Any idea why the program not proceed to the mode changed & start chmod

```


and I dont get any error now in the log...

**Comment by mscdex** [comment]
You have the path arguments swapped. For `fastGet()` it's `remotePath, localPath`. Also, you need to make sure the local path includes the filename (not just the directory).

**Comment by JenneyJ** [comment]
This is what I did local path is `"/index.html"` which is created on root folder on my project...

**Comment by mscdex** [comment]
In your second code example, you're trying to download what appears to be a directory (`'/home/app/html'`) instead of a file.

Also, `'/index.html'` is pointing to your root directory on your local machine. Unless you're running the script as root (on *nix), then you won't have permission to write to that directory typically.

**Comment by JenneyJ** [comment]
1 . Im using a mac, I can use it to transfer a file from remote to my mac?
2. Regard directory , is it possible to transfer it ?

**Comment by mscdex** [comment]
1. Yes, platform does not matter, you just have to make sure your paths are valid.

2. `fastGet()` and `fastPut()` operate on files *only* (for both local and remote paths). If you want to transfer an *entire directory* instead of just a single file, then you will need to either:

    * Manually traverse the local or remote directory and transfer each file, creating directories as necessary
    * Use a module on npm that may do the above for you
    * Use ssh instead of sftp for transferring entire directories. This requires the appropriate tools be available on both sides, such as tar or an equivalent archiving program. Using tar for example, you can actually stream the archive over the ssh connection so that you do not need to either save the file first and/or load the entire tarball into memory first.

**Comment by JenneyJ** [comment]
Ok thanks , so when I try it for only for file I still get permission denied and when I do the chmod I do see any output except open tunnel,there is some example how should I use the chmod with fastGet() probably I miss someting...

**Comment by mscdex** [comment]
I cannot answer that, if the connection isn't being made (the `'ready'` event) then obviously you won't be able to make any ssh requests. If you want to see what's happening behind the scenes, you can see debug information by setting `debug: console.log` in the connection config object.

**Comment by JenneyJ** [comment]
Just to be sure that Im using ssh2 lib ok... does  my code with the `sftp.chmod` and `sftp.fastGet` is Ok? 

Thanks!

**Comment by mscdex** [comment]
Well, the mode you're passing to `chmod()` is not going to be what you're probably expecting since the literal number `777` is a base-10 integer when you probably meant it to be an octal number. The correct, modern way to use literal octal numbers is to prefix with `0o`, like `0o777`.

As far as `fastGet()` goes, like I said, all you have to do is make sure that both paths are valid and are absolute according to your filesystem. The remote file path should exist and the local file path should include parent directories that already exist.
