### ISSUE TITLE
Trying to run conn in for loop but asynch javascript tries to create multiple connections at once

### ISSUE THREAD

**Issue by HarounAns** [mscdex/ssh2#609]
this is the basic structure of the code

 ```  couch.get(dbName, serverViewURL).then(
	function(data, headers, status){
		data.data.rows.forEach(function(rowsI){	
			conn.on('ready', function() {
			console.log('Client :: ready');
			conn.sftp(function(err, sftp) {

                        // does connection stuff
			});  				
		}).connect({
				host: data.data.rows[rowsI].value.auth.host,
				port: data.data.rows[rowsI].value.auth.port,
				username: data.data.rows[rowsI].value.auth.username,
				password: data.data.rows[rowsI].value.auth.password
		});

		}); // end foreach	
		
	},function(err){
		console.log(err);
	});
```
// please disregard data function it has nothing to do with code error
// the values contain the auth information and works when not in the forEach loop, however once in the //loop it tries to establish all connections at once. What is the work around to make it establish a single
//connection at a time. and waiting to finish the first connection before moving to the next.

**Comment by mscdex** [comment]
This isn't really `ssh2`-specific. More general questions like this should be directed at the [nodejs/help repo](https://github.com/nodejs/help/issues) or perhaps [StackOverflow](https://stackoverflow.com/).

In short though, there are many helper libraries for this kind of task. If your want a DIY solution though, consider placing your connection logic inside a function that takes in the rows and a row index as parameters. Have the row index parameter default to zero if it's not supplied. Using the data at the current index in the rows to connect and then call the function again from within the connection's `close` event handler if the next row index is less than the length of the rows array.
