### ISSUE TITLE
Connection error throws (premature) end event but not error event

### ISSUE THREAD

**Issue by ottokruse** [mscdex/ssh2#610]
An internal SSH server we use has a rate limiter that limits us to max 10 parallel connections.

Every time our code reached this max and tried to get the 11th connection node would just crash without any error message or stack trace.

After two days of agony and pulling hairs we finally discovered this was because after the Client.connect call the Client threw neither 'ready' nor 'error' but an 'end' event. We did not expect this so we did not subscribe to the end event, which apparently can have nasty results (node crashing hard)

I think this is a bug. Upon connect it seems reasonable to subscribe to 'ready' and 'error' events but who would expect that you should also subscribe to the 'end' event?

Propose to publish also an 'error' event in that case.

**Comment by mscdex** [comment]
The emitting of the `'end'` should not crash node. Only `'error'` will throw an exception if no handler for it exists.

**Comment by ottokruse** [comment]
This script reproduces the issue:

`const Client = require('ssh2');
const fs = require('fs');

const doSsh = async (path, txt) => {
    return new Promise((resolve, reject) => {
        const conn = new Client();
        conn.on('ready', () => {
            console.log(`READY :) Let's pretend I'll now write ${txt} to ${path} and this succeeds`);
            resolve();
            conn.end();
        });
        conn.on('error', (err) => { console.log('got error' + err); reject(err); });
         conn.on('end', () => { 'Did not expect to get here'; reject('premature end'); });
        conn.connect({
            host: 'mn210.mn-services.nl',
            username: 'svc_oapi',
            privateKey: fs.readFileSync('.\\keys\\id_rsa_stream_serve_mn210'),
            algorithms: { serverHostKey: ['ssh-rsa', 'ssh-dss'] },
        });
    });
}

const runTest = async () => {
    const promises = [];
    let c = 11;
    while (c-- > 0) {
        promises.push(doSsh(`/tmp/${c}.txt`, 'DUMMY DATA :)'));
    }
    console.log(`Awaiting ${promises.length} promises`);
    await Promise.all(promises).catch(err => console.error('Promise.all() rejected because:', err));
    console.log('DONE');
}

runTest();
`

If we run this with c = 10 (so just fitting the connection cap) the output is:
Awaiting 10 promises
`READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/9.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/7.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/3.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/6.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/4.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/5.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/1.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/8.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/2.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/0.txt and this succeeds
DONE
`

If we run this with c = 11 (so 1 above the connection cap) the output is:
`Awaiting 11 promises
Promise.all() rejected because: premature end
DONE
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/8.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/2.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/7.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/10.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/3.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/4.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/6.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/5.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/1.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/9.txt and this succeeds
`

Now if we comment out the line that captures 'end' (so conn.on('end') is not called) the output is:
Awaiting 11 promises
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/8.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/10.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/7.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/0.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/6.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/5.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/4.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/3.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/2.txt and this succeeds
READY :) Let's pretend I'll now write DUMMY DATA :) to /tmp/9.txt and this succeeds

It does not reach the line anymore that outputs 'DONE' to the console. But we catch all errors so why not.

**Comment by mofux** [comment]
To summarise: If you run into a server imposed connection limit, the server will not allow any further connections and just close any new client connection immediately. For `ssh2` this is not an error, but simply the end of the stream, hence it emits the `end` event, without `error` or `ready` events. From a code path perspective, that makes sense to me, but I agree that a premature end of the connection should probably emit an `error` event.

**Comment by theophilusx** [comment]
I am also running into this issue. The big problem is that for some reason, when you run into the connection limit, something is causing node to exit. I wouldn't necessarily say it is crashing as there are no errors, it just seems to exit (with exit code 0). This prevent scripts from being able to handle the issue cleanly and take appropriate action.
