### ISSUE TITLE
SB2Bi SFTP Server with extractability count 1 reporting "Message not extractable"

### ISSUE THREAD

**Issue by scoolen** [mscdex/ssh2#611]
**Long story short:**
fastGet does a STAT _after_ OPEN to determine the filesize before commencing download. This will fail for FTP servers that've capped the number of read handles at 1.

I ran into this issue while trying to download a file from an IBM sFTP server, that had ``ExtractableCount`` set to 1 (the default). The stat inside open will fail with "The message [...] is not extractable!"

Possible fixes:
- Do ``stat()`` _before_ ``open()``
- Allow filesize to be passed to ``fastGet()``, so it doesn't need to do a stat itself.

Workaround (ugly):

1. Do a stat before calling ``fastGet()``
2. Temporarily overwrite ``fstat()`` so it returns the already fetched stats

See:
https://www.ibm.com/developerworks/community/blogs/SterlingB2B/entry/sftp_server_not_extractable?lang=en

Similar issue in a Python sFTP client:
https://github.com/paramiko/paramiko/issues/576

**Comment by mscdex** [comment]
I don't understand why an `fstat()` call would cause a second "extraction" since there should be no implicit `open()` occurring with that, and `fstat()` is even tried first before falling back to `stat()`.

**Comment by scoolen** [comment]
I think that's why most resources regarding this issue speak of an off-spec FTP server.

From the 1st link I provided:
> Between SSH_FPX_OPEN & SSH_FPX_CLOSE operations, Client must just attempt to read file content.
> 
> Any attempt from client to issue other SFTP operations like SSH_FXP_STAT (reading attributes) makes server to validate extractability count > 0. If found 0, download would be reported as "not extractable"

**Comment by mscdex** [comment]
Fixed in mscdex/ssh2-streams@9941932a2a5e88048c8386ee2bfa451578994b99.
