### ISSUE TITLE
Check if the ssh client is still connecting to the remote server

### ISSUE THREAD

**Issue by hanct** [mscdex/ssh2#612]
Is there any api to check if the ssh client is still connecting to the remote server? The api should return true or false (or something similar) , in this case.  

I ask this, cos sometime, the remote server could be down suddenly, but the ssh client is still not aware of its down, hence it does not receive any event of 'end' or 'close'.  in that case, i will like my code to check if the ssh client is still connected to the remote server before the client send whatever commands to the remote server.

**Comment by mscdex** [comment]
You need to explicitly opt-in to the keepalive mechanism by setting the `keepaliveInterval` connection option (and `keepaliveCountMax` if you want to change its default value). The keepalive behavior mimics that of OpenSSH, so when a dead socket/connection is detected, you *will* get an `'error'` and `'close'` event.

**Comment by hanct** [comment]
Some remote server will timeout when there is inactivity from the client side. I need to preserve this feature, hence i cannot use keep alive. I think the alternative way is to try to catch exception around the api which send the command to remote server. if the remote server is down, exception is thrown

**Comment by hanct** [comment]
I realize the try..catch don't work. Even if the remote server is adruptly power down, the stream.write api just run normally without exception thrown

**Comment by mscdex** [comment]
> Some remote server will timeout when there is inactivity from the client side. I need to preserve this feature, hence i cannot use keep alive.

You can't have both. TCP keepalive probes *might* work, but you're typically at the mercy of the OS as far as the behavior of the probes. On most operating systems you'd have to wait on the order of hours before the connection would be detected as dead. This is why OpenSSH and others use application-level (at the SSH protocol level) keepalive messages, because it's much more reliable.

**Comment by hanct** [comment]
Ok. Thanks! In the end, I adopt the method you suggest - the keepalive
message. The detection of connection dead works. 😊😊,
