### ISSUE TITLE
on Open returns flag = 26

### ISSUE THREAD

**Issue by adonisv79** [mscdex/ssh2#613]
It is nowhere on documentation, however the flag returns 26

ftpStream.on('OPEN', (req_id, filename, open_mode, attrs) => {
switch(open_mode) {
								case OPEN_MODE.READ:
									break;
								case OPEN_MODE.WRITE:
									break;
								case OPEN_MODE.APPEND:
									break;
								case OPEN_MODE.CREAT:
									break;
								case OPEN_MODE.TRUNC:
									break;
								case OPEN_MODE.EXCL:
									break;
								default:
									sftpStream.status(req_id, STATUS_CODE.OP_UNSUPPORTED, 'Invalid open mode');
									break;
})

this hits the default where I get the unknown flags value. Client is filezilla and I did a new file creation in the remote folder. If this exists can what is the full list of acceptable values for flag?

**Comment by unknownbrackets** [comment]
Hmm, it should be using these flags in a more bitwise manner.  Is this your code, or is it in some server code you're using?

The flagsToString is meant to help with mapping the bitwise flags.  26 would be WRITE | CREAT | TRUNC, I suppose... not sure if it's covered by that helper or not.

-[Unknown]

**Comment by mscdex** [comment]
As @unknownbrackets said, `open_mode` is a bitfield, so multiple `OPEN_MODE` values can be present. `SFTPStream.flagsToString()` can help you transform the bitfield to a string (e.g. 'w') that node's `fs.open()`/`fs.openSync()` understands for example. Otherwise you can simply just use a bitwise AND (`&`) to check which flags/bits are set.

**Comment by adonisv79** [comment]
hmmm.. so since this is the bitwise values

var OPEN_MODE = {
  READ: 0x00000001,
  WRITE: 0x00000002,
  APPEND: 0x00000004,
  CREAT: 0x00000008,
  TRUNC: 0x00000010,
  EXCL: 0x00000020
};

Do we mean that 3 things happen at the same time?
EXCL (20) + APPEND (4) + WRITE (2) = 26

not sure how we should be handling such request. btw I hope this becomes part of the documentation

**Comment by adonisv79** [comment]
ah, nvm. I think i get it. 

```
flags is a bitfield containing any of the flags defined in SFTPStream.OPEN_MODE. Use the static method SFTPStream.flagsToString() to convert the value to a mode string to be used by fs.open() (e.g. 'r').
```

the confusion came because I am not actually working on fs but simulating a virtual directory or file. this is more of access rights then. so a read and write flag means opening a resource with readwrite access.. 👍

**Comment by mscdex** [comment]
@adonisv79 You could check for read and write access by checking:

```js
if ((open_mode & OPEN_MODE.READ) && (open_mode & OPEN_MODE.WRITE))
  // ...
```

or perhaps:

```js
const readWriteFlags = OPEN_MODE.READ | OPEN_MODE.WRITE;
if ((open_mode & readWriteFlags) === readWriteFlags)
  // ...
```

**Comment by adonisv79** [comment]
cool! thanks!
