### ISSUE TITLE
is there any way to upload a folder to server, but not traversal, if has please give an example

### ISSUE THREAD

**Issue by misshy** [mscdex/ssh2#614]
and i have another question:
when i upload a file to remote ,exp:   server path is : a/b/c/d/demo.txt    but if remote doesnot have dir a/b/c/d   there will throw err ,why i must confirm remote have this dir ?

**Comment by mscdex** [comment]
That's just how sftp works. If you want to recursively upload a directory, there are a few options:

1. Implement a recursive directory check manually
2. Use a module from npm that implements this (using sftp only)
3. Stream a tarball that's created on-the-fly over ssh, skipping sftp altogether
