### ISSUE TITLE
SSH2 library and Node JS Error: Callback was already called.

### ISSUE THREAD

**Issue by ronovar** [mscdex/ssh2#618]
I im using this SSH2 library and all is working fine...but i have problem when i call first time function all is working and only one callback is called...when i call second time function i get error that function was already called..so i put console.log text to see what is going on in background and i see that every time i call function i get one more console.log text called so i think it is bug in SSH2 library or what i need to call it correctly?

Here is my code:

```js
switch(data.type) {
   case 1:
     console.log('blablabla');
     break; 
   case 2:
     console.log('calling ssh...')
     /* SSH - login */
     pool.query('SELECT INET_NTOA(ip) AS ip, pass, server FROM servers WHERE id=?',[data.id], function(err, rows, fields){
       /* SSH - connection */
       conn.on('ready', function() {
         console.log('ready to execute terminal commands...')
       }).on('error', function(err) {
         /* SSH - connection failed */
         /*if(err) return callback('Login To <b>'+rows[0].server+'</b> Failed!');*/
         console.log('error connecting to server...')
         res.end()
       }).on('end', function() {
         /* SSH - closed */
         console.log('ssh closed...')
       }).connect({
         host: rows[0].ip,
         port: '22',
         username: 'root',
         password: decrypt(rows[0].pass, password)
       })
     })
     break;
    })
}
```

First time called this function i get:

```
calling ssh...
error connecting to server...
ssh closed...
```

Second calling function:

```
calling ssh...
error connecting to server...
error connecting to server...
ssh closed...
ssh closed...
```

Third time calling function:

```
calling ssh...
error connecting to server...
error connecting to server...
error connecting to server...
ssh closed...
ssh closed...
ssh closed...
```

So you see that every time i call function again i get one more time called event error and close by SSH2 library and if i put return callback(err) i get above error that function was already called because of multiple called events close and end by SSH2 library.

I read your documnetation on front page and could not find some parameter for example set call event only one time...so if you can please try above code and tell me what i im doing wrong or is bug in SSH2 library to call each time new error and close event.

Thanks

**Comment by ronovar** [comment]
I just added:

conn = new client();

so that each time function is called to create new connection and now is all working perfect...now question is do i need to delete previous conn from memory or is ok to create each time function is called to create new conn locally?

**Comment by mscdex** [comment]
I don't know where the 'Callback was already called' error is coming from, but it's definitely not `ssh2`/`ssh2-streams`.

Creating a new client object is fine and probably simplest since it will guarantee you're not continually adding event handlers to the same object every time for example. You don't have to delete the previous object from memory because it's being overwritten by `conn = new client()` and javascript is a garbage-collecting language, so the old instance will be collected at some point by V8.

One last thing, your second `break` statement seems to be inside a callback instead of right after the `pool.query()` call.

**Comment by ronovar** [comment]
Thanks...i will leave it without to delete new conn...working perfectly..and thank for your detail description,
