### ISSUE TITLE
Where are the cypher suites implemented?

### ISSUE THREAD

**Issue by kuwze** [mscdex/ssh2#619]
I looked at the code and I couldn't figure out where the cypher suites are implemented. Could someone point me at that? Thanks!

**Comment by mscdex** [comment]
All of the actual crypto is done via node's OpenSSL binding. The `ssh2-streams` module is where the actual protocol implementation lives.

**Comment by kuwze** [comment]
@mscdex So OpenSSH is a requirement for this library?

**Comment by mscdex** [comment]
No. `ssh2-streams` contains the ssh2 network protocol implementation and the crypto work (encrypting, decrypting, hashing, DiffieHellman computations, etc.) is done by Open**SSL**. OpenSSH is not involved in any way.

You don't need to install anything except node and `ssh2`. It should work on any platform supported by node (that includes Windows).

**Comment by kuwze** [comment]
Er, I'm sorry, I meant OpenSSL is a requirement? I guess so considering your answer.

**Comment by mscdex** [comment]
No, it's already bundled with node in one way or another, depending on your platform/distro.
