### ISSUE TITLE
privateKey value contains an invalid private key

### ISSUE THREAD

**Issue by adonisv79** [mscdex/ssh2#620]
I am confused. (Note I am new to FTP stuffs so still its a work in progress for me.) Anyway, as I understand, SSH security, it is often that the client who wants to be granted access must provide their public key, which the host will store. client contains the private key (and these should not be transmitted via the internet).

CLIENT: owns PPK
Host : has public key

but with this module, it seems that host.key should contain private public key else it does not work.
```
Error: privateKey value contains an invalid private key
    at new Server (D:\2312131212213\node_modules\ssh2\lib\server.js:51:13)
```

so how do we use such a thing if both the client (filezilla, winscp) and also the service (SSH2) should both possess the private key? isn't this a security breach somehow?

**Comment by adonisv79** [comment]
this is kind of relevant to the issue
https://github.com/mscdex/ssh2/issues/620

MSCDEX stated : "Alright well the key you pass to ssh has to be the private key (host.key), not the public key (host.key.pub). The public key is only needed by the server (and not the private key)."

I am not understanding this. I am trying to create an SFTP server. server as in the machine that hosts the service. It uses SSH (which is part of the server and service). Why is the private key and public key possessed by the server and service???

what will the client (those that do not belong to the server) use? the private key right? but I do not get it. why does the SSH2 need the private key and not just the public key?

**Comment by mscdex** [comment]
The user's private key is not required on the server. A private key is only needed by the *client* when doing key-based authentication.

When the client attempts key-based authentication, you use the information provided in the authentication request to validate the user. See [this example in the readme](https://github.com/mscdex/ssh2#password-and-public-key-authentication-and-non-interactive-exec-command-execution) for how you might go about that. One thing to note is that recent node versions now have [`crypto.timingSafeEqual()`](https://nodejs.org/docs/latest/api/crypto.html#crypto_crypto_timingsafeequal_a_b), so you do not need the `buffer-equal-constant-time` module used in that example anymore.

**Comment by BobbieAtanasov** [comment]
Is this an question actually closed? I was having the same problem, copied the exact code from the example link in the response from mscdex, still got the same error:
Error: privateKey value contains an invalid private key

**Comment by BobbieAtanasov** [comment]
I actually have to read a private key when creating the Server object, interesting. My bad, need to read up on SSH more.
