### ISSUE TITLE
 no matching key exchange algorithm

### ISSUE THREAD

**Issue by rawat011** [mscdex/ssh2#621]
I am trying to connect to one of storage machine using ssh2. Here is the debug error messages that i got

DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:588,padLen:6,remainLen:584
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
DEBUG: No matching key exchange algorithm

I understand the issue by looking at above messages, but dont know how to fix it.

 I can ssh to storage machine using putty from windows.

**Comment by mscdex** [comment]
`ssh2` tries to match OpenSSH's defaults when it comes to ciphers, hashing algorithms, etc. You can set the various lists via the `algorithms` configuration object. See the `algorithms` documentation in the `ssh2-streams` documentation [here](https://github.com/mscdex/ssh2-streams#ssh2stream-methods) for the defaults and the other supported values.
