### ISSUE TITLE
How can I execute multiple commands inside a connection ?

### ISSUE THREAD

**Issue by Scobee** [mscdex/ssh2#622]
I have something like this, but it does not seem to work, it exists after the first exec.
I could do them separately, but I need the first exec result before I run the second one.

```
conn.on('ready', function() {
    console.log('Client :: ready');
    conn.exec('something 1', function(err, stream) {
            if (err) throw err;
            stream.on('close', function(code, signal) {
                console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            }).on('data', function(data) {
                    // do stuff

                    conn.exec('something 2', function(err, stream2) {
                            if (err) throw err;
                            stream2.on('close', function(code, signal) {
                                console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                            }).on('data', function(data) {

                                    conn.exec('something 3', function(err, stream) {
                                        if (err) throw err;
                                        stream.on('close', function(code, signal) {
                                            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                                            conn.end();
                                        }).on('data', function(data) {

                                            //stuff
                                        }).stderr.on('data', function(data) {
                                            console.log('STDERR: ' + data);
                                        });
                                    });
                                }

                            }).stderr.on('data', function(data) {
                            console.log('STDERR: ' + data);
                        });
                    });

            }).stderr.on('data', function(data) {
            console.log('STDERR: ' + data);
        });
    });
}).connect({
    host: 'host',
    port: p,
    username: 'u',
    password: 'p'
});
```

**Comment by mscdex** [comment]
The first issue is that you shouldn't make assumptions about how many `'data'` events you will receive. With your current code, you could accidentally cause additional parallel `exec()`s to occur if you receive multiple chunks of data. Instead, only call the next `exec()` from the `'close'` event, which will only happen once.

As far as the premature closing goes, are you referring to the entire connection or are you saying the first `exec()` completes without any `'data'` events or something else?

**Comment by Scobee** [comment]
Hmm, you have a point with the `data` stuff. Although I am positive it wont return more than 1 result, I'll move the code to the close event.

As for my issue, the first exec() completes with data, but it does not go to the second one, 3rd one, etc.
I get:
```
Client :: ready
<My console.log stuff..>
Stream :: close :: code: 0, signal: undefined
```

And that's it

**Comment by mscdex** [comment]
Try setting `debug: console.log`, which should show what's happening behind the scenes.

**Comment by Scobee** [comment]
Wow, that's a lot of debug :)
Anyway, I moved the code in the 'close' event and it seems to work now. I might of had a wrong call or something that the script didn't like, and I removed it by accident.

So all good now, thank you for your help, and plugin!
