### ISSUE TITLE
issue while multiple parallel connection, connection not 'ready'

### ISSUE THREAD

**Issue by gyranjan** [mscdex/ssh2#624]
HI,

I am facing issue while multiple parallel connection, here I am trying to make 30 connection at one go, however only 24 connection are becoming 'ready'. rest connection are showing as end before becoming 'ready'

sample program:

var Client = require('ssh2').Client;
var tmp=0;
function ssh_try(temp) {
  var conn = new Client();
  conn.on('keyboard-interactive',
    function(name, instructions, instructionsLang, prompts, finish) {
      finish(['xxxxxx']);
    }).on('ready', function() {
      console.log("connected with " + temp );     

      conn.exec('cd /root;pwd', function(err, stream) { //Sample command
        stream.on('close', function(code, signal) {
          console.log("on close ");
          conn.end();
        }).on('data', function(data) {
          console.log('STDOUT: >>' + data);
        }).stderr.on('data', function(data) {
          console.log('STDERR: ' + data);
          console.log("on std error "+ data.message);
        });
      });

    }).on('error', function(e) {
      console.log("on error, temp = " + temp + ' error message '+ e.message);
    }).on('end', function(e) {
      console.log("on end, temp = " + temp);
    }).connect({
      host: 'x.x.x.x', //IP Address
      port: 22,
      username: 'root',  //Username
      password: 'xxxxx', //Password for RHEL
      tryKeyboard: true
    });
}

for(tmp=0;tmp<30;tmp++){
  ssh_try(tmp);
}

**Comment by mscdex** [comment]
The server is most likely terminating those connections early on in the handshaking process to avoid unnecessary computation (most likely limiting max connections by IP address). The lack of an `'error'` event in such cases is a [known issue](https://github.com/mscdex/ssh2/issues/610).

**Comment by mscdex** [comment]
Closing in favor of the linked issue.
