### ISSUE TITLE
Can we open sftp session with sudo mode

### ISSUE THREAD

**Issue by sanketbajoria** [mscdex/ssh2#626]
This is not really a issue. But, i am currently stuck with it. And, pulling out my hair, from last couple of days.
I am trying to create the Electron based FileManager using ssh2. I am currently opening sftp connection, and doing all file based operation through that. 
But, I am stuck with a problem, since, user through which i am connecting to machine is non root user, and has privilege to do "sudo su", without password prompt. 
How do i open the sftp session with sudo privilege? 

Thanks a lot for your great library.

**Comment by mscdex** [comment]
You can't do that with sftp, you can only perform sftp actions under the user you logged in as. If you need to perform 'sudo' operations, you will need to do them with `exec()`/`shell()`.

**Comment by sanketbajoria** [comment]
Thanks a lot for your response, 

I can emulate most of the functionality of sftp via exec()/shell(). But, how can i emulate createReadStream and createWriteStream functionality of sftp via exec()/shell()?

**Comment by mofux** [comment]
The readStream is basically the output of `cat /path/to/file.txt`, and writeStream would be similar to `tee > path/to/file.txt`. Anything you write to the steam will then be written to that file.

**Comment by sanketbajoria** [comment]
Thanks a lot.. worked like a charm. Only limitation i am facing right now, when i try to recursively upload folder, if opening connection more than 10, then it fails sometime. 
I think, i should start piping request, to overcome this limitation

**Comment by mscdex** [comment]
Most servers place session/channel limits on each connection (each `sftp()`, `exec()`, `shell()`, etc. uses a separate session/channel), so you could very well hit such limits. Some sftp clients use one transfer per connection to avoid such issues, but that's up to you.

**Comment by sanketbajoria** [comment]
Thanks a lot.. for your valuable support. Things are looking pretty good in my project. Able to manage & stream files efficiently, using this great library. 
Closing this question.

**Comment by mofux** [comment]
@sanketbajoria Out of curiosity, do you have some code to share where you implemented this feature using `exec`? I have a similar use-case (without ssh2) where I would like to interact with the filesystem inside a docker instance using `docker run`...
