### ISSUE TITLE
[Question] Do I need to verify the file after sftp.fastPut

### ISSUE THREAD

**Issue by chanphillip** [mscdex/ssh2#631]
If there is no errors at the fastPut callback, does it mean that the file should probably be proper?
I'm mainly concerning about corruption issues in normal use.
Any advice?

**Comment by mscdex** [comment]
If the `err` argument is `false`-y, then yes, it should have been transferred just fine. You can perform some kind of hash afterwards if you want, and if that is an option (if you have `ssh.exec()` access for example).
