### ISSUE TITLE
Continuous SSh session

### ISSUE THREAD

**Issue by sankarnair123** [mscdex/ssh2#633]
I would like to have a continuous ssh session so that anything that shows up on stdout is avalable to my code. Is this even possible ?
I am able to receive the first time login success messages that are in stdout but how to get subsequent messages that show up on STDOUT ?

**Comment by mofux** [comment]
Can you share some code? Are you sure there is any more output generated (I assume you are using the `shell` method)? Have a look at the examples in the README

```javascript
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.shell(function(err, stream) {
    if (err) throw err;
    stream.on('close', function() {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
    stream.end('ls -l\nexit\n');
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  privateKey: require('fs').readFileSync('/here/is/my/key')
});
```

**Comment by sankarnair123** [comment]
Yes Stdout generates console log messages that i d like to relay back to my code. I am using shell.

conn.on('keyboard-interactive', function(name, instructions, lang, prompts, cb){
  cb(['xxxxxxxxx']);

});


conn.on('ready', function() {
  console.log('Client :: ready');
  
  conn.shell(function(err, stream) {
    if (err) throw err;
    stream.on('data', function(data) {
      console.log('STDOUT: ' + data);
      
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  })
 
 
  

}).connect({
  host: 'xxxxxx',
  port: 22,
  username: 'xxx',
  password: 'xxxx',
  tryKeyboard: true
});

**Comment by sankarnair123** [comment]
Also please note that in the above examples listed, you are closing the connection to the destination. Is it possible to leave this connection on and anything that shows on stdout be relayed back ?

**Comment by mofux** [comment]
Yes, just call `stream.end('exit\n')` whenever you want to close the session. So you are receiving data from the stream, and console.log prints out that data. Your shell session will sit idle and does nothing if you don't run a command or anything on that session. For example, if you `stream.write('ls -alh\n')`, you should get a data event with the output of that command.

**Comment by sankarnair123** [comment]
Awesome, thats what i was missing, thank you that works perfect.
