### ISSUE TITLE
client.exec: Stream closes before command has ended running, emitting 'close'-event twice

### ISSUE THREAD

**Issue by sokraflex** [mscdex/ssh2#637]
Greetings!

I'm using ssh2 to automatically install required packages via apt-get. Recently I'm running into problems because the returned stream ends before the installation has finished: One of the installation steps takes several minutes until the next line of output is printed. Before the next line is printed, the stream emits the 'close' - event - and then prints the next data, and emits the close-event again. So my question is: How can I increase the timeout the stream waits for a next line to be printed in the output before automatically closing itself? Or are there better ways to catch the end of the command then listening to the streams 'close'-event?

My code looks simplified like the following:

    let client = new ssh2.Client();
    //[establishing a connection and so on...]
    client.exec('apt-get install -y requiredpackages', (err, stream) => {
        if (err) return callback(err);

        stream.on('close', (code, signal) => {
            console.log('close', code, signal);
            callback();
        });
        stream.on('data', (data) => {
            console.log('stdout', data.toString('utf8'));
        });
        stream.stderr.on('data', (data) => {
            console.log('stderr', data.toString('utf8'));
            callback(data);
        });
    });

When connecting to the server and executing the command, the output has the following schema:

1. A lot of stdout - outputs.
2. The close output, the callback gets called.
3. A few minutes later, again stdout outputs.
4. The close output, the callback gets called again.

The close-signal becomes emitted with the code "0" and the signal `undefined` both times.

**Comment by mscdex** [comment]
Can you set `debug: console.log` and post the resulting output?

**Comment by mscdex** [comment]
If you can still reproduce this with the latest `ssh2`/`ssh2-streams` and a more reliable server-side command that I can test with, let me know.
