### ISSUE TITLE
Compression causes fastPut to fail

### ISSUE THREAD

**Issue by pqvst** [mscdex/ssh2#639]
I'm trying to transfer a `tar` file from client to server using `sftp.fastPut`.
- 6 KB file + `compress: true` works ✅
- 2.2 MB file + `compress: false` works ✅
- 2.2 MB file + `compress: true` doesn't work ❌

The following occurs immediately after invoking `fastPut`:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
```

If I try changing the `concurrency` option to `1`, then the following happens:

```
 pktLen = payload.length + 9;
                  ^

TypeError: Cannot read property 'length' of null
    at send_ (.../node_modules/ssh2-streams/lib/ssh.js:5291:19)
    at .../node_modules/ssh2-streams/lib/ssh.js:5271:7
    at afterWrite (_stream_writable.js:430:3)
    at onwrite (_stream_writable.js:421:7)
    at afterTransform (_stream_transform.js:102:3)
    at TransformState.afterTransform (_stream_transform.js:75:12)
    at Zlib.callback (zlib.js:485:5)
```

Other notes:

* I've tested two different tar files (2.2 MB and 3.1 MB).

* I've tested two different taring methods (using the mac `tar` command and using the `tar` npm package).

Minimal example to reproduce the issue:

```
const ssh2 = require("ssh2");

const src = "my_tar_file.tar"; // 2.2 MB
const dst = "test.tar";

const conn = new ssh2.Client();
conn.once('ready', () => {
  console.log("connected!");
  conn.sftp((err, sftp) => {
    if (err) return;
    sftp.fastPut(src, dst, { }, (err) => {
      console.log(err || "ok!");
    });
  });
});

conn.connect({ 
  host: "...",
  username: "...",
  password: "...",
  compress: true
});
```

**Comment by mscdex** [comment]
If this is still an issue with `ssh2` v1.0.0 let me know and I can reopen this.
