### ISSUE TITLE
Executing multiple commands

### ISSUE THREAD

**Issue by theunreal** [mscdex/ssh2#641]
I'm trying to execute the following series of commands:

1. Connect through SSH (easy, well-documented)
2. Execute a command: "en"
[the device outputs now: "password:]
3. Execute a command (input): my-password
4. Execute a command: dir

I'm unable to find a way to execute a series of commands in the documentation, I'm unable to runmore than one command at a time

Any help?

This is what I tried:

```
conn.on('ready', function() {
        console.log('Client :: ready');
        conn.exec('en', function(err, stream) {
            if (err) throw err;
            stream.on('close', function(code, signal) {
                console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                conn.end();
            }).on('data', function(data) {
                conn.exec('my-password', function (err2, stream2) {
                    console.log('got here');
                    console.log(stream2);
                })
            }).stderr.on('data', function(data) {
                console.log('STDERR: ' + data);
            });
        });
```

stream2 is undefined

**Comment by mscdex** [comment]
There are at least two issues here:

1. You're closing the connection when the first `conn.exec()` stream closes, this might happen before your second `conn.exec()` has a chance to start on the server.

2. You're calling `conn.exec()` for *each* `'data'` event from `stream`, which *could* occur multiple times. *Never* make any assumptions about the number of `'data'` events for a readable stream in node in general.

**Comment by theunreal** [comment]
Thanks @mscdex !
but I still can't figure out how to execute muiltple commands which one of them has an input.

Connect through SSH --> works
Execute a command: "en" --> works
enter Input: "lab" --> doesn't work
Execute a command: dir --> doesn't gets here

How I can enter an input after running the "en" command and then executing "dir"?

**Comment by mscdex** [comment]
Are you trying to send input to the 'en' process?

**Comment by theunreal** [comment]
@mscdex Yes, After I type "en" I am requested to enter a password as input, after I type the password I can run any command I want.

When I access my device through SSH I need to enable it. Enabling it takes 2 steps:

- executing "en"
- the command line requests an input
- the input should be "lab"
- I can execute commands now, like "dir" etc

**Comment by mscdex** [comment]
If you want to send data to the process's `stdin`, then you just `stream.write()` as necessary (possibly adding `\n` to simulate pressing the enter key if it's more of an interactive program).

**Comment by theunreal** [comment]
So I used .write('lab') to enter lab as a password input as follows:

```
conn.on('ready', function() {
        console.log('Client :: ready');
        conn.exec('en', function(err, stream) {
            if (err) throw err;
            stream.on('close', function(code, signal) {
                console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                conn.end();
            }).on('data', function(data) {
                console.log('' + data);
            }).write('lab\n')
        });
    }
```

This is what I get:

![image](https://user-images.githubusercontent.com/6171883/33238019-7fe1adda-d28c-11e7-94ea-ea7c79735c64.png)

I'm still unable to find a way to enter a password as input so I can execute or write other commands

**Comment by mscdex** [comment]
You could try creating a pty in case the program is expecting one. For example: `conn.exec('en', { pty: true }, function(err, stream) { ... })`

Also, you should be checking `err` first in case the server rejected the `exec()`.

**Comment by theunreal** [comment]
@mscdex I also tried pty:

```
conn.on('ready', function() {
        console.log('Client :: ready');
        conn.exec('en', { pty: true }, function(err, stream) {
            stream.write('lab');
            stream.write('\n');
            stream.on('data', function(data) {
                console.log(''+data);
            });
            stream.on('close', function(data) {
                console.log('Stream closing: '+data);
            });
            stream.on('err', function(data) {
                console.log('Stream error: '+data);
            });
        });
```

This is the output:

```
Example app listening on port 3000!
Client :: ready

Password:
Strean closing: 0
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)
```

This is how I expect it to work: (the screenshot taken on Putty ssh client)

![image](https://user-images.githubusercontent.com/6171883/33269168-67659530-d388-11e7-9379-f300d28cfc48.png)

**Comment by mscdex** [comment]
For `'keyboard-interactive'` events to be emitted, you need to set `tryKeyboard: true` in your connection config object.

However, if you're already seeing the `'ready'` event then that means the server has already accepted your (SSH level) user authentication.

As far as the (higher-level) secondary authentication goes, you might try waiting for the password prompt first before writing `'lab\n'` (or `'lab\r\n'`) to the stream in case the server-side process is picky. Otherwise if none of that works you can directly simulate what PuTTY is doing by using `.shell()` instead of `.exec()`, but that can make retrieving output and exit codes of executed commands more difficult.

**Comment by hygortc** [comment]
for the purpose of documentation

the only solution I found for a similar problem was:

on('data', (data) =>{
            const newdata = ''+data;
            newdata == 'password: ' ? stream.write(`${password}\n`) : 
            console.log(''+data); 
}

is there any other solution?
