### ISSUE TITLE
[Request] Documentation: Document Connection Stream Events

### ISSUE THREAD

**Issue by 3DEsprit** [mscdex/ssh2#643]
For anyone trying to extract data from the stream in certain circumstances without knowing about the `end` and `error` events on the connection, this can make for issues in asynchronous applications. Is there any possibility that the documentation can reference these events? 

```
conn.on('ready', () => {
   // shell/exec
}).on('error', error => {
  throw error; // catches connection errors
}).on('end', () => {
  // catches the end event, so and data can be passed
}).connect(options);
```

I'm sure there are other events as well, but these are the two I've been able to dig out of the source so far. If needed I would be happy to create a PR for the README to mention these.

Anyways, thanks for the module! It has been a life-saver!

**Comment by mscdex** [comment]
You can just listen for `'close'` (instead of `'end'`), which will get emitted no matter what when a TCP connection closes, whether it was due to error or not. Everything else should already be documented.

**Comment by 3DEsprit** [comment]
Great to know, and thanks for the reply!  

Sure enough, these are certainly mentioned in the API, but as you said `close` isn't mentioned. 

I remember seeing these options in the small amount of docs I looked at covering the server (something I didn't have much use for, yet), so I didn't dive into the server portion enough to know they were both using the same Client. Even so, I always have more fun tearing through the source. My main concern is future users, and not my own personal gain, because let's face it this is an amazing module to have on hand for anyone needing SSH.

To build upon that, the reason I mentioned adding more context to the documentation is based on the way I incorporate ssh2 in my own React/Redux app, by using a similar approach to the above so it can be used in a Redux action within a React app. When using the two separate events `end` & `error` you can satisfy the resolve/reject for a promise, or any other async action within a custom API, which makes it easy to return a success/failure for redux.

If you feel this is something better covered in a developer blog I certainly understand, and will do exactly that. Even so, I wanted to at least bring it up to suggest adding such event catches to help those coming from React/Redux (sometimes with limited CommonJS) to see an easy way for implementation ssh2 into their own apps. I don't think it would take anything specific to React/Redux itself, but possibly showing these events being caught in the examples (not just in the Server examples). I would think most would want to catch Client connection errors anyways, no?

Anyways, thanks for the time, and anticipate your response.

**Comment by mscdex** [comment]
> Sure enough, these are certainly mentioned in the API, but as you said close isn't mentioned.

The `'close'` event for `Client` is already documented.

> I would think most would want to catch Client connection errors anyways, no?

That's the case for any `EventEmitter` in node. Whether it's node core, `ssh2`, or any other third-party module that uses an `EventEmitter`.

I'm still not quite sure what you're asking/requesting.

**Comment by 3DEsprit** [comment]
My apologies for the lack of clarity, it looks like you have it covered and I just overlooked it. 

My request was to add a use-case for these events in the Client section of the documentation, and not just in the API, and server. While it is later made apparent that the client and server use the same object, it's not clear at first glance, making the connection events like this seem specific to ssh2 servers. 

Overall it's just an ignorant oversight, but I was requesting to add more context to the client section to show the overlap to new users. Realistically its redundant, so it may not be something worth adding. 

Anyways, closing this ticket.
