### ISSUE TITLE
Example with PuTTY client

### ISSUE THREAD

**Issue by HarelAshwal** [mscdex/ssh2#644]
LK"I

Hi,
Is there any working example on how to use the SSH2 server against PuTTY client (for user/pass authentication)?
I tried the provided example and it doesn't work.

Harel

**Comment by mscdex** [comment]
"Doesn't work" does not tell us anything. What did you try? Were there errors? Did it partially work? etc.

**Comment by HarelAshwal** [comment]
LK"I

When I try to login with PuTTY (with user/pass) ctx.method set to "none", so it can't get to authentication stage.
you can simply reproduce it by running the below code, and try to login with PuTTY to localhost.

here is the Putty console, and the NodeJS process (running on Windows 7, NodeJS 8.7)

![putty](https://user-images.githubusercontent.com/6409714/33551731-f6b4f628-d8fa-11e7-89c6-c18eff3ee037.jpg)


Code:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs = require("fs");
var crypto = require("crypto");
var inspect = require('util').inspect;
var buffersEqual = require("buffer-equal-constant-time");
var ssh2 = require("ssh2");
var utils = ssh2.utils;
var pubKey = utils.genPublicKey(utils.parseKey(fs.readFileSync('c:\\user.pub')));
new ssh2.Server({
    hostKeys: [fs.readFileSync('c:\\host.key')]
}, function (client) {
    console.log('Client connected!');
    client.on('authentication', function (ctx) {
        if (ctx.method === 'password'
            && ctx.username === 'foo'
            && ctx.password === 'bar')
            ctx.accept();
        else if (ctx.method === 'publickey'
            && ctx.key.algo === pubKey.fulltype
            && buffersEqual(ctx.key.data, pubKey.public)) {
            if (ctx.signature) {
                var verifier = crypto.createVerify(ctx.sigAlgo);
                verifier.update(ctx.blob);
                if (verifier.verify(pubKey.publicOrig, ctx.signature))
                    ctx.accept();
                else
                    ctx.reject();
            }
            else {
                // if no signature present, that means the client is just checking
                // the validity of the given public key
                ctx.accept();
            }
        }
        else
            ctx.accept();
    }).on('ready', function () {
        console.log('Client authenticated!');
        client.on('session', function (accept, reject) {
            var session = accept();
            session.once('exec', function (accept, reject, info) {
                console.log('Client wants to execute: ' + inspect(info.command));
                var stream = accept();
                stream.stderr.write('Oh no, the dreaded errors!\n');
                stream.write('Just kidding about the errors!\n');
                stream.exit(0);
                stream.end();
            });
        });
    }).on('end', function () {
        console.log('Client disconnected');
    });
}).listen(0, '127.0.0.1', function () {
    console.log('Listening on port ' + this.address().port);
});
```

**Comment by mofux** [comment]
I think it happens because you are only listening for the `exec` event on the client, but putty (and any other ssh command line client) does not invoke exec, it probably invokes `pty` and likely `shell`. Try to implement them, that should get you a bit further:

https://github.com/mscdex/ssh2#session-events

**Comment by mscdex** [comment]
@mofux is correct. PuTTY starts an interactive 'shell' session instead of the more basic 'exec' session. It also requests a pty, so you will want to handle that request to avoid the error you see on PuTTY's side.

**Comment by HarelAshwal** [comment]
LK"I

Can you give more detail? what need to be implemnted under "shell" and "pty" to make it work?

 ```
   session.once('pty', function (accept, reject, info) {
        console.log('Client wants to execute: ' + inspect(JSON.stringify(info)));
        var stream = accept();       
      });
      session.once('shell', function (accept, reject, info) {
        console.log('Client wants to execute: ' + inspect(JSON.stringify(info)));
        var stream = accept();
        stream.write('Just kidding about the errors!\n');
        stream.exit(0);
        stream.end();
      });
```

**Comment by mofux** [comment]
What are you trying to archive? What is the output with the code added above? Does putty get any further? Your code looks ok to me (although calling accept() in the pty handler does not provide you with a stream, but for this example it is not critical because you are not operating on it) and I would expect putty to see 'Just kidding about the errors!' and then to quit.

**Comment by HarelAshwal** [comment]
LK"I

How do I capture the input stream? 
So I can get the user input?

**Comment by mofux** [comment]
I think you should listen to the `data` event on the stream:

```javascript
stream.on('data', function(data) {

  // user input happened
  console.log('user wrote: ' + data.toString());

  // echo the input back to the client, so it can see its own input
  stream.write(data);

});
```

Note that you would have to echo that data back to the client if you want the client to see the input...
