### ISSUE TITLE
Question about PTY implementation

### ISSUE THREAD

**Issue by zhaoyi0113** [mscdex/ssh2#645]
This is not an issue. I have a question regard to PTY implementation in ssh2 library. I read the `Pseudo-TTY settings` from the README but I didn't find any implementation relates to PTY. As far as I know, many nodejs application uses `node-pty` to handle pty stream which has a native dependency. Could you please share how `ssh2` implement PTY in javascript?

**Comment by mscdex** [comment]
`ssh2`/`ssh2-streams` doesn't implement pseudo TTYs. Clients just request them and have nothing to do with setting up or maintaining PTYs. For servers, you will need to handle that yourself if you want to actually create a PTY for clients.

**Comment by zhaoyi0113** [comment]
Alright, I understand. Thanks.

**Comment by lancemao** [comment]
any idea how to implement it on server side?
