### ISSUE TITLE
Fingerprint capture

### ISSUE THREAD

**Issue by brigand** [mscdex/ssh2#649]
I'm doing some ssh automation, and I'd like to add the fingerprint to known_hosts on the first connection, and then assert it's correct on future connections.

When I connect via the ssh cli I get the accept prompt and it says the fingerprint is like this:

```
ECDSA key fingerprint is SHA256:wRxdjHfaDS/zFnn...
```

It seems ssh2 only supports `md5` and `sha1` in `hostHash`. Is it possible to make this work with the current ssh2 client, or would it require making changes to ssh2 to make this possible? Also I'm guessing `sha1` is a less secure option, even if it works.

I don't really know cryptography stuff, but if I can help with any code changes, I will. Otherwise, please point me in the right direction for accomplishing this.

Thanks for the great tool!

**Comment by mscdex** [comment]
You can use any valid hash name supported by node in recent `ssh2` versions.
