### ISSUE TITLE
How to check if a ssh subsystem is supported

### ISSUE THREAD

**Issue by mofux** [mscdex/ssh2#650]
After creating a ssh client connection I'd like to check if a certain subsystem (like `sftp` or `shell`) is available. I was wondering if there is a **fast way** to test for it without actually initialising the full subsystem yet. For example, I could of course just request that subsystem and wait for it to either accept or reject, but that would mean that in case of a successful test it would create that subsystem which can take multiple seconds. I've been digging through the `ssh2-streams` sources but couldn't find a way to do it. Any help or pointers would be very appreciated.

**Comment by mscdex** [comment]
The only way to know if a subsystem is available is to try to request it. The server does not announce a supported subsystem list during handshake or anything like that.
