### ISSUE TITLE
How to connect ssh through identity_file?

### ISSUE THREAD

**Issue by zhaoyi0113** [mscdex/ssh2#651]
This may not be an issue but I couldn't find a way to connect through ssh with an identity file.  I am using `ssh -i MY_IDENTITY_FILE user@hostname` to connect to a ssh server from command line. How should I use `ssh2` to do the same connection?

**Comment by mscdex** [comment]
The OpenSSH `-i` option is for specifying an explicit private key. You can specify a `privateKey` when connecting. You can find docs and examples of that option in the readme.

**Comment by zhaoyi0113** [comment]
Yes, you are right, it is documented in the readme. Thanks.
