### ISSUE TITLE
[question] How to specify (force) server to text or binary mode?

### ISSUE THREAD

**Issue by developer94404** [mscdex/ssh2#652]
I'm having weird issues with ^M in text files from certain people. 

- Issue: certain other people's files, when they send to my ssh2-sftp server, seem to have the ^M remaining.

- Replication: In Notepad++ in Windows, I set the line-ending mode to CRLF, and send this text file over to this project's ssh2-sftp server; however, the CRLF don't seem to appear in my received file when I open it on the Linux server.

I'm not sure what I'm doing wrong to be unable to send a file with ^M CRLF characters over to the ssh2-sftp server (hosted in Linux).

Is this to do with text/binary mode settings for the server? 
If so, is there a way to make the server use binary or text mode?
If not, is there some other thing I am not seeing?

Thanks for any insight you may kindly provide.

**Comment by mscdex** [comment]
Neither the ssh protocol nor sftp have any kind of text/binary mode like ftp. It's all binary and everything is sent as-is.

**Comment by developer94404** [comment]
Gotcha. 

I got the notion of there being a mode fro sftp because I was reading off this post:  https://stackoverflow.com/questions/29226647/how-to-transfer-binary-file-in-sftp 

Is that post misinformed then?

**Comment by unknownbrackets** [comment]
I believe that refers to SSH_FXF_TEXT_MODE (v4 and higher):
https://tools.ietf.org/id/draft-ietf-secsh-filexfer-13.txt

Which would be similar to opening a file with flag 't'.

-[Unknown]

**Comment by developer94404** [comment]
Thanks - good to know the server is in binary mode only. It must be something else I am doing wrong. I think this can be closed.
