### ISSUE TITLE
Can an SFTP server capture the source/remote IP of its client(s)?

### ISSUE THREAD

**Issue by matthewbordas** [mscdex/ssh2#657]
Hi,

Love the library. I'm currently using it for an SFTP server. Is there anyway an SFTP server implemented with this library can know/capture the source/remote IP of its client(s)? For security reasons, it'd be nice to check the IP addresses that its receiving requests from. I couldn't find any relevant documentation on this in the sftp examples or in the other parts of the docs. Maybe I'm missing an additional parameter that gets passed back to an event's callback? Thanks!

Best,
Matt

**Comment by mscdex** [comment]
The SSH server's [`'connection'` event](https://github.com/mscdex/ssh2#server-events) provides this information.

**Comment by matthewbordas** [comment]
Totally missed that in the docs, thanks a lot!
