### ISSUE TITLE
[Solved] SSH + Key unable to Auth - Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by nitingautam** [mscdex/ssh2#658]
Below is my code....i tested it work fine if i use either key or password but not working for both.

What could be issue?

Error: All configured authentication methods failed

let Client = require('ssh2-sftp-client');
let sftp = new Client();
sftp.connect({
host: '104.197.5.23',
port: '22',
username: 'nits',
privateKey: require('fs').readFileSync('id_rsa'),
password: 'test'
}).then(() => {
return sftp.list('/home/nis');
}).then((data) => {
console.log(data, 'the data info');
}).catch((err) => {
console.log(err, 'catch error');
});

**Comment by nitingautam** [comment]
Looks like I got answer. Auth method priority is Password and then Key. 
So i switched to same on server and it working now fine.

Not sure if we can do priority as Key and then password

**Comment by mscdex** [comment]
Authentication method priority is currently not configurable.
