### ISSUE TITLE
How do I know when a shell session finished streaming a command and got a response?

### ISSUE THREAD

**Issue by barakav** [mscdex/ssh2#662]
Hi,
Out of efficiency, I need to change a code that is based on ".exec" so it won't disconnect every time it sends a single shell command, so It will enable the user to send many commands at once. The interface surrounding this code is being used by a large mass of code so I can't change the behaviour too much.

So, I chose to use ".shell" instead, but there is a problem that I still need to solve: 

After I send a command and my nodejs code continues executing I don't know when the command finished streamming. The event handler of ".data" seems to return every single letter being streamed from and to my pc (can you change that?).  It's a little bit messy but I can solve that  by measuring the times "enter" was pressed  in the command and continue after all those "enters" were streamed as data .

It isn't a very elegant solution and I won't be a able to read the response but it is a solution...

 Isn't there an event being sent after the command was sent or the response being recieved? the 'close' event served the same purpose with ".exec", so I knew that after it was recieved, both the shell command and the response were finished but here I want to keep the connection alive so "close" is not a good choice.

Another possibility is to add a dummy command with a known response like "echo @! "   after the barrage of user commands and when the response returns to the stream "@!" I know I can exit the function... 

Again this solution isn't very elegant and it will create a problem when the remote server will take a long time to get the response from the user commands, in that case my dummy command will be lost.

**Comment by mscdex** [comment]
There is no way to know when a command inside a shell ends for sure. It ultimately depends on what you're executing. I suppose you could use a custom shell prompt and just look for that, but nothing is going to be 100% fool-proof with `shell()`.

I'm not sure what you mean by "so it won't disconnect every time it sends a single shell command." You don't have to end the ssh connection after you use `exec()`. You could just call `exec()` again if you wanted. Using `exec()` is going to be the best way to know when the command has completely finished without having to do any tricky output checking/filtering.

**Comment by barakav** [comment]
Thank you for your answer,

So from what I understand, all I need to do is to keep the client object without using ".end" after the close signal, like in your example?

and if I want to change my user mode to sudo, will it keep it for the next command? (I can't check this out  untill I am back in my office...)

**Comment by mscdex** [comment]
`connection.end()` closes the connection. If you're not done with the connection, then don't close it.

'sudo' executes whatever command you supply after it, as root. If you execute another command without 'sudo', it will run as the current user.

**Comment by barakav** [comment]
thank you!

**Comment by barakav** [comment]
Alright I still have a problem, It turned out that the machine I am connecting to, doesn't allow me to use the sudo command directly. I have to use su to turn into root indirectly (for security reasons ,so I shouldn't change that).

I also need to save the response from the server for further use.
I used:
conn.exec('su', { pty: true },..
and then stream.on('readable',function({
stream.read()..
stream.write() etc...
})
but again I am stuck with the same problem as with  'shell',
I don't have any clear indication when the response ends.

Is there a way around this without using some tricky output filtering?

**Comment by mscdex** [comment]
Can't you do `su -c 'my command'`?

**Comment by zjleon** [comment]
I facing the same problem, this is my solution:
1. connect using ``shell``
``conn.shell(function(err, stream) {``
2. change to su after connect
``stream.write('sudo -i')``
3. using the ``stream.write`` to input command when meet specify output, end with \n
```
stream.on('data', function(data) {
if (data.indexOf('[sudo] password for') > -1) {
stream.write('Password\n')
```
4. then you can use the same pattern to input other commands you want, and when you done, quit sudo and shell ``stream.end('exit\nexit\n')``

**Comment by mohitgith** [comment]
I have tried to do this but am getting an error `Fatal error: write after end`. I have executed the code below:
conn.shell(function (err, stream) {
                    stream.write(command);
                    if (err) throw err;
                    stream.on('close', function () {
                        console.log("In Close");
                       logger.info('Command execution completed ');
                        conn.end();
                        return resolve();
                    }).on('data', function (data) {
                        logger.debug(data);
                        fs.appendFileSync(filePath, data);
                        console.log("In data");
                        if (data.indexOf('[cli] > ') > -1) {
                            stream.write('help\n', function(err) {
                                stream.end('exit\n');    
                            });  
                        }              
                    });
                });

If I try to remove the end it goes on to execute the `stream.write('help\n)` as the data is coming after every execution of help command.

**Comment by gavin1970** [comment]
The easy workaround, which I found today...  When sending a ShellStream.WriteLine, just append an "; echo this-is-the-end" to the backside of the command.  That will be the last thing sent back as a response, so you know your at the end of your stream.
