### ISSUE TITLE
can i use ssh2 to connect windows server?

### ISSUE THREAD

**Issue by rzhang228** [mscdex/ssh2#665]
the server's os is windows server 2008
can i use ssh2 to connect the server, and put file to it or execute some command?
if it is possible, which port should i take in?

thanks~

**Comment by mofux** [comment]
No, Windows server 2008 does not provide a built-in SSH server. You might be able to install one, see here: http://techgenix.com/install-ssh-server-windows-server-2008/

**Comment by rzhang228** [comment]
@mofux thanks~~
I will try to install the freeSSHd in the server.

**Comment by oxygen** [comment]
https://www.zdnet.com/article/openssh-arrives-in-windows-10-spring-update/
