### ISSUE TITLE
SSH stream emits `end` before all `data` is read

### ISSUE THREAD

**Issue by ardoramor** [mscdex/ssh2#666]
# Versions 
ssh2: 0.4.10
ssh-streams: 0.0.23
ssh-exec: 2.0.0

# Problem
I have used ssh-exec and later ssh2 directly to execute a remote command. I am running into a problem where the `end` event is received before all `data` events are emitted.

# Details
On my server, I have a 53Mb file. I `cat` it and expect to receive all of the data through `data` events before `end` event is received. However, a good number of lines is never received and my parsing stops short.

I placed several console output statements tied directly into `ssh2` client, just as in the README.md sample:

```javascript
conn.exec('cat ~/sample.log', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
```

**Comment by mscdex** [comment]
Can you please try with the latest version of `ssh2`?

**Comment by ardoramor** [comment]
Ok, let me re-run the tests and I will let you know. My initial guess is that `cat` might be pushing more data than otherwise expected. The file that I `cat` contains output of an execution, which returns data at a slower pace, relative to how `cat` just dumps the contents. This might be a factor. I'll let you know that as well.

**Comment by ardoramor** [comment]
I've just updated code and ran the sample against ssh2@0.5.5 and can reproduce the same result. It is about a 54Mb file. Maybe the connection closes before the buffers are read?

**Comment by mscdex** [comment]
I don't have any problem. Here is the code I used with a 55MB file (`dd if=/dev/urandom of=sample.dat bs=1024 count=56320`):

```js
  conn.exec('cat ~/sample.dat', (e, s) => {
    if (e) throw e;
    const h = require('crypto').createHash('sha1');
    function onData(d) {
      h.update(d);
    }
    s.on('close', () => {
      conn.end();
    }).on('data', onData)
      .on('end', () => {
      // be extra sure all data is received by 'end'
      s.removeListener('data', onData);

      console.log(h.digest('hex'));
    }).stderr.on('data', (d) => {});
  });
```

The logged hash and the one produced by `sha1sum sample.dat` on the remote end match every time for me.
