### ISSUE TITLE
User path is not set correctly when connecting to AWS ec2 instance

### ISSUE THREAD

**Issue by zhaoyi0113** [mscdex/ssh2#668]
I am using `ssh2` to connect to a AWS ec2 instance. The connection works fine but the user PATH environment variable doesn't look correct. Below is the source code.

```
var conn = new Client();
conn.on('ready', function() {
  // the connection is ready
  // will get command not found if I send commands here
}).connect({
  host: hostName,
  port: 22,
  username: 'ec2-user',
  privateKey: myKeyFile
});
```
I can see the connection is ready but when I send a command which is under `/sbin/`, I will get command not found error. After some debugging I found that the `/sbin` is not set in user's PATH environment variable. But it is set if I connect to that server through terminal command line. I wonder what the default bash script the ssh2 library use after a connection.

**Comment by mscdex** [comment]
Are you using an interactive session when you connect from the command line? If so, that would make sense why that works because interactive sessions are a bit more involved (they do more shell initialization and such) than just executing a command string, which goes through a different part of the ssh protocol.

**Comment by mscdex** [comment]
OpenSSH is pretty restrictive about what environment variables are allowed to be set, at least by default in most distributions. You could try prepending `cmd` with `'export PATH=$PATH:/sbin;'`

**Comment by zhaoyi0113** [comment]
Ok, thanks for your explanation. As you mentioned about different part of ssh protocol, do you have any article or link about this part of the protocol for more detailed information?

**Comment by mscdex** [comment]
The SSH2 Connection RFC does not explicitly state the exact behavior of `shell` vs `exec`, so it's up to individual implementations. For example, on the server side you could even program `shell` to output something other than a shell, like a multi-user chat for example (which there is an example of this in this repo). So what environment/setup the server executes an `exec` command string in is totally up to the server implementation.
