### ISSUE TITLE
connection hopping: streams to STDERR

### ISSUE THREAD

**Issue by xu8511831** [mscdex/ssh2#669]
I am trying to run some command for connection hopping, For example:
````js
var Client = require('ssh2').Client;
 
var conn1 = new Client();
var conn2 = new Client();
 
conn1.on('ready', function() {
  console.log('FIRST :: connection ready');
  conn1.exec('nc 192.168.1.2 22', function(err, stream) {
    if (err) {
      console.log('FIRST :: exec error: ' + err);
      return conn1.end();
    }

    stream
      .on('close', function (code, signal) {
        console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
        springboardConnect.end();
      })
      .on('end', function (data) {
        console.log('end: ' + data);
      })
      .stderr.on('data', function (data) {
        console.log('STDERR: ' + data);
      })

    conn2.connect({
      sock: stream,
      username: 'user2',
      password: 'password2',
    });
  });
}).connect({
  host: '192.168.1.1',
  username: 'user1',
  password: 'password1',
});
 
conn2.on('ready', function() {
  console.log('SECOND :: connection ready');
  conn2.exec('uptime', function(err, stream) {
    if (err) {
      console.log('SECOND :: exec error: ' + err);
      return conn1.end();
    }
    stream.on('end', function() {
      conn1.end(); // close parent (and this) connection 
    }).on('data', function(data) {
      console.log(data.toString());
    });
  });
});
````

This output:

````html
STDERR:  * Found existing ssh-agent: 10933

STDERR:  * Found existing gpg-agent: 13566

STDERR:  * Known ssh key: /home/****/.ssh/id_dsa

STDERR:

: command not found 1: SSH-2.0-ssh2js0.1.19
````

I don't know why, How can I do it?

**Comment by mscdex** [comment]
Try using `conn1.forwardOut()` to connect to the second host instead of `conn1.exec('nc ...')`.

**Comment by xu8511831** [comment]
It doesn't work.

`conn1.forwardOut('127.0.0.1', 8888, dstIP, 80, function (err, stream) {})`

Here is  the error message.

`Error: (SSH) Channel open failure: unknown channel`

**Comment by mscdex** [comment]
The stderr output you're seeing is coming from some program called 'keychain'. Are you sure you're not calling `.shell()` or something instead of `.exec()`? 'command not found' is what I would expect if you were using `shell()` or `exec()` to start a shell session. This would also make sense because of the stderr output, which seems to be from a program called 'keychain' which is probably in the user's shell startup script.

**Comment by xu8511831** [comment]
Yes. It's really to be from a shell startup script on the connection hop, but why `conn1.exec('nc ...', function(err, stream){})` stream will output stderr ?

**Comment by mscdex** [comment]
There are no other ways besides `.forwardOut()` (which apparently is not implemented on the server -- which I'm guessing is not OpenSSH) or `.exec()` with a program like netcat or socat. It seems the server is meddling with the `.exec()` requests that makes that solution impossible. In that case there's not much that can be done.
