### ISSUE TITLE
Question: encapsulate entire connection in function?

### ISSUE THREAD

**Issue by coreyman** [mscdex/ssh2#672]
I'm trying to make a new ssh connection over and over in a loop to test to see if some ip addresses in our company have an active ssh server and return me a banner. For some reason I never get a banner message but I can test some ips manually and I get one. I'm mainly getting the error Error: connect ECONNREFUSED. What am I doing wrong?

var Client = require('ssh2').Client;

function testSSHResponse(ip, originalRecord){
  var conn = new Client();
  conn.on('banner', function(ctx){
    console.log('we got an ssh banner message');
  }).on('error', function(err) {
//do stuff on error
 }).connect({
      host: ip,
      port: 22,
      username: 'test',
      password: 'pass'
      //readyTimeout: 7000,//we only want to wait 2 seconds for a response
      //privateKey: require('fs').readFileSync('/here/is/my/key')
    });
}

**Comment by mscdex** [comment]
To be clear the `'banner'` event is a notice that only occurs after the handshake has completed but before a successful authentication and even then it's only if the server is configured to send one. The only time anything is emitted during the initial connection is a potential `'greeting'` event if the server supplies a greeting message with the initial protocol identification string, but again that is optional. There is no event emitted currently for when the initial protocol identification string is received.

However, the error you're receiving is unrelated as it's telling you the server refused the TCP connection completely, so there is no chance to receive any data. Are you sure you are able to connect to the particular `ip` directly using the OpenSSH client or even `netcat` from that same machine?

**Comment by coreyman** [comment]
Yes I am using openssh for windows and I am able to connect to the particular ip directly. I am also running this node application on windows.

**Comment by mscdex** [comment]
If you do `telnet <ip> 22` from the machine you are encountering the ECONNREFUSED, do you see 'SSH-2.0-.....' in the output?

If so, then I do not know what to suggest. In that case, something is blocking node from making the TCP connection.

If you don't see it, then perhaps your OpenSSH client is using a jump host or something similar to reach the intended host?

**Comment by coreyman** [comment]
Yes it says SSH-2.0-OpenSSH_5.9 when tel netting from the same machine.

**Comment by coreyman** [comment]
I think the issue is that I'm giving the wrong password on the first attempt and the server wants me to try again with another password, is there an event I can attach to for this case?

**Comment by mscdex** [comment]
You already have an 'error' event handler, that is all you'd need for detecting authentication issues.

**Comment by coreyman** [comment]
You're right I would get "Error: All configured authentication methods failed".

So I did a test. I created a new js file and removed the .forEach loop that contained my connection logic and I am able to get the desired results for the host in question of 'Error: All configured authentication methods failed'. If I run this in a .forEach to connect to multiple targets it's acting very weird. I turned on debug output and this is all I get -


```
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
DEBUG: Client: Trying <IPHIDDEN> on port 22 ...
DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.0'
```

**Comment by mscdex** [comment]
Are you (re-)using the same connection object? If so, you're better off using a new connection object per host.

**Comment by coreyman** [comment]
I have this basically -

> var Client = require('ssh2').Client;
> fs.readFile('myfile', 'utf8', function(err, contents) {
>   let customerRecord = contents.split(/\n/);
>   customerRecord.forEach(function(currentRecord){
>   let ipAddress =  currentRecord[currentRecord.length-1].match(/\d+\.\d+\.\d+\.\d+.*$/i)[0];
>   let conn = new Client();
>    conn.on('banner', function(ctx){
>         console.log('we got an ssh banner message');
>       }).on('keyboard-interactive', function(name, instructions, instructionsLang, prompts){
>         console.log('keybaord interactive');
>       })
>       .on('error', function(err) {
>         //console.log(err.stack);
>         if(err.stack.match(/Error:\sThis\ssocket\sis\sclosed/i) !== null){//we matched //Error: This socket is closed
>           console.log("\""+originalRecord+"\"" + ", NO, "+err.stack);
>         }
>         else if(err.stack.match(/Error:\sHandshake\sfailed:\sno\smatching\skey\sexchange\salgorithm/i) !== null){
>           console.log("\""+originalRecord+"\"" + ", YES, "+err.stack);
>         }
>         else if(err.stack.match(/Error:\sconnect\sECONNREFUSED/i) !== null){//we matched //Error: connect ECONNREFUSED
>           console.log("\""+originalRecord+"\"" + ", NO, "+err.stack);
>         }
>         else if(err.stack.match(/Error:\sTimed\sout\swhile\swaiting\sfor\shandshake/i) !== null){//we matched //Error: Timed out while waiting for handshake
>           console.log("\""+originalRecord+"\"" + ", NO, "+err.stack);
>         }
>         else if(err.stack.match(/Error:\sAll\sconfigured\sauthentication\smethods\sfailed/i) !== null){//we matched //Error: All configured authentication methods failed //this is the one we want
>           console.log("\""+originalRecord+"\"" + ", YES");
>         }
>         else if(err.stack.match(/Error:\sconnect\sECONNREFUSED/i) !== null){//we matched //Error: Handshake failed: no matching key exchange algorithm //we like this one too
>           console.log("\""+originalRecord + ", YES");
>         }
>         else{
>           console.log("Unknown Error Signature. Please contact developer." + err);//we have not seen this error, need to create a support request to dev
>         }
>         }).connect({
>           host: ipAddress,
>           port: 22,
>           username: 'test',
>           password: 'pass',
>           readyTimeout: 20000,//we only want to wait 2 seconds for a response
>           hostHash: 'md5',
>           hostVerifier: function(hashedKey){ return true},
>           debug: function(debugInfo){
>             console.log(debugInfo);
>           }
>           //privateKey: require('fs').readFileSync('/here/is/my/key')
>         });
>

**Comment by mscdex** [comment]
The code you've shown is not in a loop, which is where you said you are having problems.

Also, your `readyTimeout` is 2**0** seconds, not 2 seconds.

**Comment by coreyman** [comment]
The loop is here on line 5 -

> customerRecord.forEach(function(currentRecord){

I set the readyTimeout back to default for testing.

**Comment by mscdex** [comment]
As long as the debug output matches the number of connections you're trying to make, then I don't see anything wrong. Did you try adding a `'close'` event handler to check that the connections are being closed? Does anything happen after the configured `readyTimeout` amount of time passes?

**Comment by coreyman** [comment]
Haven't added close yet. Well it processes all hosts very fast. Seems to be too fast. I'm never getting an  'Error: All configured authentication methods failed' for ANY hosts. If I take a host that I know I should get auth failed for and run a one off connection outside of the loop I do indeed get auth failed. If I run this same host among many others I get "Error: Timed out while waiting for handshake".

**Comment by coreyman** [comment]
What version of node are you working with when running parallel connections?

**Comment by coreyman** [comment]
I'd like to add that this works flawlessly on Ubuntu 16.04.2 LTS with node v9.8.0 but not on Windows 10 Pro with node v8.9.4

**Comment by mscdex** [comment]
I've used all kinds of node versions on *nix.

If the problem is only on Windows and not related to node version there, perhaps there is some sort of security or similar software getting in the way?

**Comment by coreyman** [comment]
I'm not running anything special. Windows defender is active, windows firewall is turned off.

**Comment by mscdex** [comment]
I don't know what to tell you then if it's working fine on Linux and you've tried the latest version of different node branches (v4.x, v6.x, v8.x, etc.) without success. There is nothing platform specific with this module except some of the ssh key agent handling, which involves supporting Pageant natively and ssh-agent under cygwin. However those things never come into play because those happen after the ssh handshake is completed, which is not even starting in your case.

**Comment by mscdex** [comment]
If this is still an issue with a modern version of node, it would be interesting to run a packet capture to see if any of the connections are actually made and if anything is sent by the server on any of the connections.
