### ISSUE TITLE
Question: SFTP best practice for reading files in a directory one at a time?

### ISSUE THREAD

**Issue by leosco** [mscdex/ssh2#674]
``` JavaScript
import { Client } from 'ssh2';
import _ from 'underscore';

/*
  Given an sftp stream, directory path, and file object,
  get file contents and print them
*/
function ingestFile(stream, dir, file) {
  const enc = 'utf8';
  const buf = Buffer.from('', enc);
  const path = `${dir}/${file.filename}`;

  console.log(`> opening ${path}`);
  stream.open(path, 'r', (err, handle) => {
    if (err) throw err;
    stream.readData(
      handle,
      buf,
      0,
      file.attrs.Stats.size,
      0,
      (err, bytesRead, newBuf) => {
        if (err) throw err;
        console.log(`> read ${bytesRead} bytes, got contents: ${newBuf.toString(enc)}`);
      },
    );
  });
}

function importFtpOrders(servers) {
  const conn = new Client();

  servers.forEach((serv) => {
    const cOpts = _.pick(serv, ['host', 'port', 'username', 'password', 'algorithms']);

    conn.on('ready', () => {
      console.log('> connection ready');
      conn.sftp((err, sftp) => {
        if (err) throw err;
        sftp.readdir(serv.dir, (err, list) => {
          if (err) throw err;
          console.log(`> discovered ${list.length} files in ${serv.dir}, first file:`);
          console.dir(list[0]);

          list.forEach((f) => {
            ingestFile(sftp, serv.dir, f);
          });

          conn.end();
        });
      });
    });

    conn.connect(cOpts);
  });

  return servers.length;
}
```

Hi there, I'm having some trouble with the above code.

I'm trying to connect to a list of servers, and for each of them: iterate through the files in a directory and extract their contents into memory. These are small text files that I need to parse and finally insert into a database.

I'm able to connect and list the contents of the directory, but when I try to open the file using the absolute path and `sftp.open` (or `stream.open` in my top function), it fails silently. No errors are thrown and nothing gets printed to the console. I read all the [docs](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md) on the sftp-stream methods and I *think* this is the way I need to do it, but I could be missing something.

Any help would be greatly appreciated.

**Comment by mscdex** [comment]
What does/doesn't get printed to the console? Is the `sftp.readdir()` callback being called? Is `ingestFile()` being called? Is the `sftp.open()` callback being called? Any other place?

Also, `file.attrs.Stats.size` is not correct. It should be `file.attrs.size`.

You should be checking `file.attrs.mode` to make sure it's a regular file you're trying to open first, and not some other type such as a directory, UNIX socket, etc. You can do this using values from node's built-in `fs.constants` object: `if ((file.attrs.mode & fs.constants.S_IFMT) === fs.constants.S_IFREG)`

**Comment by leosco** [comment]
Thanks for the response!
- you're right, it should be `file.attrs.size`, it looked nested in Stats for some reason when I saw it printed in the console
- `conn.end()` was being called before the call to `ingestFile()` was even able to take place, so I need to refactor that a bit
- it's great advice for to check if it's a regular file, as well, before I even try to open it

I'll update my code above to reflect those changes

**Comment by mscdex** [comment]
What versions show for `ssh2` and `ssh2-streams` when you do `npm ls --depth=0`?

Also, you could use `sftp.readFile()` if you want to make it simpler to read an entire file into memory. Be careful about reading very large files into memory though. If you're just wanting to download the file to local disk, consider using `sftp.fastGet()` instead, or if you can/need to stream the contents somewhere you can use `sftp.createReadStream()` (but will be slower than `sftp.fastGet()`).

**Comment by leosco** [comment]
I can't stream the contents because the files are of variable sizes, albeit not too large, so reading them into memory one at a time would be ideal. I would rather avoid saving them to disk, since it's an unnecessary extra step. 

Thanks for pointing out `sftp.readFile()`, I don't think it's documented [here](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md) though...

Why doesn't opening the file using `sftp.open()` and then passing `handle` from the callback to `sftp.readData(handle, ...)`?

**Comment by mscdex** [comment]
Did you check the module versions? `stream.open()` works but an exception is thrown for `stream.readData()` saying it's not a function? Is that still correct?

**Comment by leosco** [comment]
Correct, it's only in the nested call to `sftp.readData()` is throwing the undefined error. 

Either way, I'm going to get the whole process working with just *one* file for now, and then figure out the best way to iterate through them.

**Comment by leosco** [comment]
Okay, @mscdex so I condensed the function to a far more basic version, just getting the first file from the first server. And I'm still getting the:
``` Bash
TypeError: sftp.readData is not a function
```

Here's the code:
``` JavaScript
  const conn = new Client();
  const serv = servers[0];

  const cOpts = _.pick(serv, ['host', 'port', 'username', 'password', 'algorithms']);

  conn.on('ready', () => {
    console.log('> connection ready');
    conn.sftp((err, sftp) => {
      sftp.readdir(serv.dir, (err, list) => {
        console.log(`> discovered ${list.length} files in ${serv.dir}, first file:`);
        console.dir(list[0]);

        // list.forEach((f, i) => {
        //   ingestFile(conn, sftp, serv.dir, f, list.length - i - 1);
        // });

        const file = list[0];
        const path = `${serv.dir}/${file.filename}`;
        console.log(`> opening ${path}...`);

        sftp.open(path, 'r', (err, handle) => {
          const buf = Buffer.from('', 'utf8');
          sftp.readData(handle, buf, 0, file.attrs.size, 0, (err, bytesRead, newBuf) => {
            console.log(newBuf.toString('utf8'));
            conn.end();
          });
        });
      });
    });
  });

  conn.connect(cOpts);
```

**Comment by mscdex** [comment]
Ah, I see the issue. You should be using `sftp.read()` and not `sftp.readData()`. In the readme it's noted (under `conn.sftp()`) that for `ssh2`, `sftp.readData()`/`sftp.writeData()` are `sftp.read()`/`sftp.write()` respectively. This is to more closely mirror the node `fs` API.

**Comment by leosco** [comment]
Oh wow, I see what you mean now by "mirroring the `fs` API" that's why `sftp.readFile()` is supported. That's pretty awesome, I've gotten the single file reading to work properly now:
``` JavaScript

  conn.on('ready', () => {
    console.log('> connection ready');
    conn.sftp((err, sftp) => {
      sftp.readdir(serv.dir, (err, list) => {
        console.log(`> discovered ${list.length} files in ${serv.dir}, first file:`);
        console.dir(list[0]);

        // list.forEach((f, i) => {
        //   ingestFile(conn, sftp, serv.dir, f, list.length - i - 1);
        // });

        const file = list[0];
        const path = `${serv.dir}/${file.filename}`;
        console.log(`> opening ${path}...`);

        sftp.readFile(path, { encoding: 'utf8', flag: 'r' }, (err, data) => {
          console.log(data.toString('utf8'));
        });
      });
    });
  });
```
