### ISSUE TITLE
Question:  how forward local service to remote service ssh -N -R localhost:3322:172.17.1.2:22 poser@123.15.29.165 -p 29156

### ISSUE THREAD

**Issue by hktalent** [mscdex/ssh2#675]
ssh -N -R localhost:3322:172.17.1.2:22 poser@123.15.29.165 -p 29156

local: 172.17.1.2:22
remote: 3322

remote  ssh: poser@123.15.29.165 -p 29156

**Comment by cztomsik** [comment]
```
const net = require('net')
const ssh2 = require('ssh2')

const { Client } = ssh2

const conn = new Client()

conn.on('ready', () => {
  const s = net.createServer(c => {
    conn.forwardOut('127.0.0.1', 8088, '127.0.0.1', 8088, (err, stream) => {
      if (err) { throw err }

      c.pipe(stream)
      stream.pipe(c)
    })
  })

  s.listen(8088)
})

conn.connect({
  host: '192.168.0.120',
  port: 22,
  username: 'user',
  password: 'pwd'
})
```

**Comment by hktalent** [comment]
# 1、how local use remote host service
rhost:rport 
run ssh code
lhost:lport == rhost:rport 

# 2、in remote server use local lan services
lanIp:lanPort
run ssh code
rhost:rport === lanIp:lanPort 

sorry can not work 
@cztomsik

**Comment by dmbarry86** [comment]
> This worked for me
> 
> ```
> const net = require('net')
> const ssh2 = require('ssh2')
> 
> const { Client } = ssh2
> 
> const conn = new Client()
> 
> conn.on('ready', () => {
>   const s = net.createServer(c => {
>     conn.forwardOut('127.0.0.1', 8088, '127.0.0.1', 8088, (err, stream) => {
>       if (err) { throw err }
> 
>       c.pipe(stream)
>       stream.pipe(c)
>     })
>   })
> 
>   s.listen(8088)
> })
> 
> conn.connect({
>   host: '192.168.0.120',
>   port: 22,
>   username: 'user',
>   password: 'pwd'
> })
> ```

Thanks for this. This also worked for me (although I swapped around as I was doing local forward rather than remote). Would be nice to have such an example in the doc as it took me a while to get this working. The connection hopping example is close but not exactly what is needed.
