### ISSUE TITLE
seek 65536 not supported with cursor 32768 error while uploading File

### ISSUE THREAD

**Issue by sunilthamban** [mscdex/ssh2#678]
Hi,

Versions
  
"ssh2-sftp-client": "2.0.1",
"ssh2-utils": "1.0.28"
"ssh2-streams": 0.1.20
"ssh2":"0.5.5"

I am getting a seek error while uploading files to the server resulting in partial uploads of the file.

Pasting the code snippet used. Also attaching the debug log for your reference. 

Kindly suggest.

const lSFTPConfig = {
  url: 'xxx.xxx.xx.xx',
  port: 4045,
  username: 'username',
  password: 'password',
  from_local_folder: 'Encrypted',
  // in to the sftp server folder
  to_server_folder: '/inbound',
}

function debugLog(debuString)
{
  console.log(debuString)
}

function* getSFTPObject() {
  try {
    const sftp = new Client()
    const connectionObject = {
      host: lSFTPConfig.url,
      port: lSFTPConfig.port,
      username: lSFTPConfig.username,
      password: lSFTPConfig.password,
      debug: debugLog,
      readyTimeout: 100000,
    }
    yield sftp.connect(connectionObject)
    console.log(`SFTP_CONNECTED-${connectionObject.host}:${connectionObject.port}`)
    return sftp
  } catch (e) {
    console.log('SFTP-CONNECT_ERROR', e.message)
    return false
  }
}

function* putPayoutFileToRemoteServer(filename) {
  let sftp = ''
  try {
    console.log(`UPLOADING-${filename}`)
    sftp = yield getSFTPObject()
    yield sftp.put(path.resolve(`${filename}`), `/${lSFTPConfig.to_server_folder}/${filename}`, true)
    console.log(`UPLOADED-REQ-${filename}`)
    return true
  } catch (error) {
    if (sftp) {
      sftp.end()
    }
    console.log('SFTP-PUT-ERROR', error.message)
    return false
  }
}

function* testPut() {
  try {
    yield putPayoutFileToRemoteServer('H2HAPS10388120180327103001.txt')
  } catch (error) {
    console.log(error)
  }
}

co(testPut())

[out.txt](https://github.com/mscdex/ssh2/files/1871449/out.txt)

**Comment by mscdex** [comment]
Closing this as this seems to have been resolved in https://github.com/jyu213/ssh2-sftp-client/issues/59#issuecomment-379637330.
