### ISSUE TITLE
What's new in 0.6.0?

### ISSUE THREAD

**Issue by soichih** [mscdex/ssh2#680]
I just noticed that v0.6.0 is released recently but I can't find any release note about it. I am still using 0.5.5. What's changed, and should I upgrade it?

**Comment by mofux** [comment]
You can see it in the commits here:
https://github.com/mscdex/ssh2/commits/master

I think it contains all the commits from Mar 11, 2018

**Comment by soichih** [comment]
OK. Thanks. I've upgraded to 0.6.0.
