### ISSUE TITLE
readdir sort

### ISSUE THREAD

**Issue by MrMoronIV** [mscdex/ssh2#681]
sftp.readdir gives kind of a funky sort back. folders in between everywhere and filenames seem to be in a random order.

Is it possible to get something back like `ls -l --group-directories-first`? Or do I have to sort things myself inside the nodejs server? I'd rather not of course.

**Comment by MrMoronIV** [comment]
In addition, is it possible to get human readable file sizes or is that a nodejs as well?

**Comment by mscdex** [comment]
The protocol does not define an order for readdir entries, so you'd have to sort it yourself or use `.exec()` to obtain a directory listing and have it sorted server-side. However with the latter, you'd have to manually parse whatever output you end up getting, whether you choose to try to parse raw `ls` output or you pipe it through some other program on the server that can produce more easily parseable output.

**Comment by mscdex** [comment]
If you want human-readable file sizes, you would have to do that kind of conversion yourself. The file sizes used in SFTP are always in bytes.

**Comment by MrMoronIV** [comment]
Thank you for the answers. Instarted with a manual exec but its output got cut off when there were many files. It only received something like the last 50 rules of output back.

But I sorted it manually and converted the filesizes to human readable ones and the loop is still fast. Better yet, I receive all my files instead of being cut off (which happened on two different servers)

**Comment by MrMoronIV** [comment]
*I started
(I can't edit my post on mobile apparently)
