### ISSUE TITLE
Search remote server best practice

### ISSUE THREAD

**Issue by MrMoronIV** [mscdex/ssh2#684]
What would be the best practice to search on a remote server for certain text in files?

Trying to perform a grep command via interactive shell but I get mixed results per server. Any suggestions?

**Comment by mscdex** [comment]
I'm not sure what you're looking for/asking here, but it seems out of scope for this project and is probably better suited for the [nodejs/help repo](http://github.com/nodejs/help) and/or a place like StackOverflow.

If what you're really asking about is parsing the output of a command, all I can suggest is not using an interactive shell to avoid having to check for and remove shell prompts in the output.

**Comment by MrMoronIV** [comment]
does exec give live output in the data event as the grep command searches?
And how do I cancel that exec if a user requests that?

**Comment by mscdex** [comment]
Output from either `.exec()` or `.shell()` is always "live" in the sense that it's passed on to the user as soon as we receive it from the server. Whether the command you're executing performs some kind of (implicit) buffering is a separate matter and is outside the control of this module.

You can explicitly close a stream using `.close()`, but that may/may not kill the process on the server, however it should definitely close the communication channel for that command.

**Comment by mscdex** [comment]
Not easily like with `.exec()` (which does not start an interactive shell). As I mentioned previously, you would have to search for a shell prompt in the stream output and there is no foolproof way of doing that.

**Comment by MrMoronIV** [comment]
yeah the thing is, I don't want to close my connection since I want to use it for other execs as well. The only thing I can't figure out is how to be able to stop a running command just executed.

I don't want to run an endless grep on a server for example, it's should be stoppable.
Any other suggestion that just closing the connection or is that my best bet?

**Comment by MrMoronIV** [comment]
I'm sorry, I think I mixed `conn` and `stream`, where the latter is returned by the `exec`, closing the `stream` will not close the connection as far as I understand
