### ISSUE TITLE
Username and password should not be required by the library

### ISSUE THREAD

**Issue by ch-andrewrhyne** [mscdex/ssh2#686]
Some use cases of SFTP don't require a username/pass and only require that the public key is registered with the server before connections are made (similar to how you auth with Github when cloning repos with SSH2).

Is there a reason that usernames/passwords are strictly required by this lib?  I would love to put in a PR to make them optional if that is acceptable

**Comment by mscdex** [comment]
A password is not required. A username however is, because the protocol requires it. Perhaps you're referring to some clients that default to the current user's username? If so, I'd rather not have to maintain a cross-platform username detection algorithm that works for everyone.
