### ISSUE TITLE
Feature Request: allow configuration of local IP for the ClientConfiguration

### ISSUE THREAD

**Issue by FalkNisius** [mscdex/ssh2#687]
Use Case: The host has many Interfaces, the SFTP Server allows only connections from some Ips, only one IP of my host is allowed.
Proposal:
Adding a `localAddress` - config option to the client config,
Use in doConnection instead of
```
self._sock.connect(self.config.port, host);
```
better
```
if (self.config.localAddress) {
self._sock.connect({port: self.config.port, host: host, localAddress: self.config.localAddress});
} else {
self._sock.connect(self.config.port, host);
}
```
Thanks

**Comment by mscdex** [comment]
`localAddress` and `localPort` are now supported as of a3c9768b4d3e787f23305356b87b35b4884bd371.

**Comment by FalkNisius** [comment]
Thank You
