### ISSUE TITLE
Intermittant sftp.fastput failures - no such file or directory

### ISSUE THREAD

**Issue by BionanoDev** [mscdex/ssh2#689]
We are using fastput to move selected files between servers.   We are getting intermittent failures.  Sometimes it fails and if we try the same operation again (with no code changes) it works.   We verified the files are present and the time stamp is prior to the log output where the file not found error occurs.  We are running centos 7.3 on both systems.

Unhandled rejection Error: ENOENT: no such file or directory, open ...

**Comment by mscdex** [comment]
It's hard to say, the only thing I can say is that you could check with server logs to see if there is any more information and/or if the error you're receiving indeed matches what the server says it's sending back.

I would've said maybe it was a concurrent request/connection issue, but I would not expect an error message like that for that kind of issue, but who knows...
