### ISSUE TITLE
I have try this code,i got the below result, and i don't further....how to start the remote access.  

### ISSUE THREAD

**Issue by jeganbalu** [mscdex/ssh2#693]
I have try this code, i got the below result. I am fresher , i don't no how to start the remote access. 
 Kindly give me the step by step process to start.

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.forwardIn('127.0.0.1', 8000, function(err) {
    if (err) throw err;
    console.log('Listening for connections on server on port 8000!');
  });
}).on('tcp connection', function(info, accept, reject) {
  console.log('TCP :: INCOMING CONNECTION:');
  console.dir(info);
  accept().on('close', function() {
    console.log('TCP :: CLOSED');
  }).on('data', function(data) {
    console.log('TCP :: DATA: ' + data);
  }).end([
    'HTTP/1.1 404 Not Found',
    'Date: Thu, 15 Nov 2012 02:07:58 GMT',
    'Server: ForwardedConnection',
    'Content-Length: 0',
    'Connection: close',
    '',
    ''
  ].join('\r\n'));
}).connect({
  host: '123.123.123.13',
  port: 22,
  username: 'username',
  password: 'password@123'
});

I have try this code, curl -I http://127.0.0.1:8000 from the curl in got this output.

[root@senora ssh2]# curl -I http://127.0.0.1:8000
HTTP/1.1 200 OK
Content-type: text/plain
Date: Thu, 10 May 2018 08:27:55 GMT
Connection: keep-alive

I don't no how start the remote access, in browser.

**Comment by mscdex** [comment]
`forwardIn()` forwards incoming connections to a port on the remote server to your local machine. You would need to use curl on the remote server, not locally.
