### ISSUE TITLE
Feature request: Support tunnelled/proxied SSH connections

### ISSUE THREAD

**Issue by DeeHants** [mscdex/ssh2#694]
I'm using this library as part of the [SSH FS](https://github.com/SchoofsKelvin/vscode-sshfs) plugin to VS Code.
However our organisation's setup requires that all our SSH connections go via a jump host.
This is setup with a PuTTY connection to the jump host that has a "dynamic" (SOCKS) tunnel configured.
Each PuTTY connection to the actual servers is then set to use a SOCKS proxy on localhost.

It looks like this library doesn't yet honour the proxy setting as it tries to connect directly to the specified hostname.

How feasible is it to support SOCKS proxying of connections?
Supporting this would make things massively easier for my workflow.

Associated ticket in the plugin project: https://github.com/SchoofsKelvin/vscode-sshfs/issues/4

**Comment by mscdex** [comment]
This module doesn't have built-in SOCKS support as I see that has being beyond the scope of the project. This module does not even have built-in support for tunneling local connections.

Making SSH connections through a jump host is easy to do if you're just needing to make connections from within your process. It's only when you want to support tunneling local connections from outside your node process that you will need to use SOCKS. For that you can easily just mix in any of the various SOCKS modules on npm.

**Comment by DeeHants** [comment]
Understood, thanks.
Support has been added to the original project as well using the socks module and the upstream sock.
Closing this down.
