### ISSUE TITLE
How to debug this library

### ISSUE THREAD

**Issue by jefferybai** [mscdex/ssh2#695]
hellow,
I use it like this,

node -v: v8.11.1
ssh2 -v: 0.6.1

var Client = require('ssh2').Client;
var conn = new Client();

conn.on('error', (err) => console.log(err));

conn.on('ready', function() {
    console.log('Client :: ready');
  })

conn.connect({
    readyTimeout: 5000,
    host: '192.168.6.1',
    port: 5000,
    username: 'leapflow',
    password: 'P@ssw0rd!'
  });

 I run it without error,  using filezilla connect is good， but also The ready event does not respond。

**Comment by mscdex** [comment]
What does `npm ls --depth=0 | grep ssh` show?

You can view debug output by setting `debug` to a function in your connection config object (e.g. `debug: console.log`).

**Comment by mscdex** [comment]
I cannot duplicate the issue of not receiving an `'error'` event after `readyTimeout` milliseconds, using that version of node.

What type of server is it set as in Filezilla? Are you sure it's SFTP and not FTP or FTPS?

**Comment by jefferybai** [comment]
oh, i'm sorry
Filezilla type is ftp and port is empty.
Soo i corrected the configuration code,

conn.connect({
    readyTimeout: 10000,
    host: '192.168.6.1',
    port: 21,
    username: 'leapflow',
    password: 'P@ssw0rd!',
    debug: (debug) => {
        console.log(debug)
    }
  });

Output information is as follows:

"DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.1'"
index.client.js:38 "DEBUG: Client: Trying 192.168.6.1 on port 21 ..."
index.client.js:38 "DEBUG: Client: Connected"
index.client.js:38 "DEBUG: Parser: IN_INIT"
index.client.js:38 "DEBUG: Parser: IN_GREETING"
index.client.js:38 "DEBUG: Parser: IN_HEADER"
index.client.js:38 "DEBUG: Remote ident: 'SSH-2.0-SSH2JS0.2.1: command not understood.'"
index.client.js:38 "DEBUG: Outgoing: Writing KEXINIT"

  The error event response is as follows：
Error: Timed out while waiting for handshake

**Comment by mscdex** [comment]
The `ssh2` module is for ssh/sftp connections *only*. If you need ftp/ftps, you will need another module.

**Comment by jefferybai** [comment]
Okey, think you
