### ISSUE TITLE
Setting extra options

### ISSUE THREAD

**Issue by lghamie** [mscdex/ssh2#700]
Hi, 
I'm sorry if i'm asking something that's already covered in the docs but I couldn't find it.
Does this client use .known_hosts file?? I that case, I'd like to set the ssh client option:  UserKnownHostsFile, because id' like to set it to /dev/null .

**Comment by mscdex** [comment]
No, this module does not read from any default locations like that.

**Comment by lghamie** [comment]
thanks!
