### ISSUE TITLE
::Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by thomasfaller** [mscdex/ssh2#702]
Hey guys,

I'm writing a node app to query a SSH SQL database. After launching the app, nothing happens. I get `forwardOut: ready` logged into the console but no timeout message, no `err`, nothing.
After a while I get a message saying the server got disconnected (`Connection lost: The server closed the connection`).
Something in my query is blocking the script somehow.
I heard that pooling queries could help out but since I need the stream for my SSH, I haven't found a way to make pooling work with ssh2 :/

```
const mysql = require('mysql2');
const Client = require('ssh2').Client;

const ssh = new Client();

process.on('uncaughtException', function (error) {
  console.log(error.stack);
});

ssh.on('ready', function () {
  ssh.forwardOut(
    '127.0.0.1',
    12345,
    '217.78.5.141',
    2200,
    function (err, stream) {
      if (err) {
        console.error('forwardOut Error: ' + err);
      }
      console.log('forwardOut: ready!');
      const db = mysql.createConnection({
        host: '10.26.0.160',
        user: 'xxxxx',
        password: 'xxxxxxxxxxxx',
        database: 'xxxxxxxxxx',
        port: 1234,
        stream: stream
      });
      db.connect(function (err) {
        if (err) {
          console.error('error connecting: ' + err.stack);
          return;
        }
        console.log('connected as id ' + connection.threadId);
      });
      db.query('SELECT * FROM comms WHERE action = 6', function (err, results) {
        if (err) {
          console.log("Error while querying the database");
          console.error(err)
        }
      });
    });
}).connect({
  host: 'xxx.xxx.xxx.xxx',
  user: 'xxxxxxxxxxxx',
  password: 'xxxxxxxxxxxxxxxxxx',
  port: xxxx
});
```

Sorry had to remove all the data since it's rather sensitive (work) lol

**Comment by mscdex** [comment]
Currently what's happening is you are logging into the ssh server and from there, making a *plain TCP connection* to 217.x.x.x:2200, which you are then using as your database connection. When you pass `stream` to `mysql2.createConnection()`, the `host` and `port` values are ignored.

If 217.x.x.x:2200 is actually an ssh jump host, you will have to ssh to that one first, by first creating another ssh client and passing `sock: stream` to its `connect()` and then from that second client do another `forwardOut()` to 10.26.0.160 and pass *that* resulting `stream` to `mysql2.createConnection()`.

**Comment by thomasfaller** [comment]
Thanks @mscdex !
So basically, shall I keep my "first" `createConnection` and create another one nested into that one ?
Would `sock: stream` need to be passed to both connections ?
Sorry for the dumb questions, I'm just very new at this, and thanks for your time.

**Comment by mscdex** [comment]
It depends, is the host used in the second connection to port 2200 another ssh server or?

**Comment by thomasfaller** [comment]
I have the following:

MySQL Host: 10.26.0.160
MySQL Port: 3306

SSH Host: 217.78.5.141
SSH Port: 2200

(+ the corresponding usernames and passwords of course)

How would I go about writing my script you think ?

**Comment by mscdex** [comment]
Ok, so the host and port you pass to the *first* `.connect()` are not 217.78.5.141:2200?

**Comment by thomasfaller** [comment]
I thought the specs used to create the first connection (the one that starts with `const db = mysql.createConnection({....`) should be the 'normal' MySQL ones and the SSH specs should be used for the "closing" `}).connect({...` at the end.
Should it be the other way around?:

<img width="672" alt="script" src="https://user-images.githubusercontent.com/23104176/40628939-fc92537a-62bf-11e8-82cb-44c94b27d572.png">

**Comment by mscdex** [comment]
What I was asking was is the `host` at the very bottom of your code something other than `''217.78.5.141''`?

Your current code is making 3 connections here, one to an SSH server, one to '217.78.5.141:2200' (your `forwardOut()`), and one to a server at '10.26.0.160:1234'.

I'm just trying to sort out what you're actually trying to do connection-wise so I know what to suggest.

**Comment by thomasfaller** [comment]
Thanks @mscdex !
Currently, my connection at the end is using the 


```
const mysql = require('mysql2');
const Client = require('ssh2').Client;

const ssh = new Client();

process.on('uncaughtException', function (error) {
  console.log(error.stack);
});

ssh.on('ready', function () {
  ssh.forwardOut(
    '127.0.0.1',
    12345,
    '217.78.5.141',
    2200,
    function (err, stream) {
      if (err) {
        console.error('forwardOut Error: ' + err);
      }
      console.log('forwardOut: ready!');
      const db = mysql.createConnection({
        host: '217.78.5.141',
        user: 'sshUser',
        password: 'sshPassword',
        port: 2200,
        debug: true
      });
      db.connect(function (err) {
        if (err) {
          console.error('error connecting: ' + err.stack);
          return;
        }
        console.log('connected as id ' + connection.threadId);
      });

      db.query('SELECT * FROM comms WHERE action = 6', function (err, results) {
        if (err) {
          console.log("Error while querying the database");
          console.error(err)
        }
      });
    });
}).connect({
  host: '217.78.5.141',
  user: 'sshUser',
  password: 'sshPassword',
  port: 2200
});
```

Basically I have  my SQL credentials and my SSH credentials, I'm just not too sure how I need to lay them out.

The app just needs to be able to query the database (like SELECT* FROM customer blabla)

**Comment by thomasfaller** [comment]
I made another attempt on this, without success so far :/

## Here's the file connecting to the db:
```
const mysql = require('mysql2'),
  Connection = require('ssh2');
const config = require('./config');
const c1 = new Connection();

c1.connect(config.ssh);

c1.on('ready', function () {
  c1.forwardOut(
    '127.0.0.1',
    12345,
    '217.78.5.141',
    2200,
    function (err, stream) {
      if (err) {
        console.error('forwardOut Error: ' + err);
      }
      console.log('forwardOut: ready!');

      const c2 = new Connection();

      c2.connect(config.mysql);

      c2.on('ready', function () {
        console.log('Connected (c2)')
      })

      c2.on('error', function (err) {
        console.log('C2 :: error ::' + err);
      });
      stream.emit('connect');
    })
});

c1.on('ready', function (err) {
  console.log('C2 :: error ::' + err);
});

```

## Here's my config:
```
const config = {
  ssh: {
    host: '217.78.5.141',
    user: 'sshUser',
    password: 'sslPassword',
    port: 2200
  },
  mysql: {
    host: '10.26.0.160',
    user: 'sqlUser',
    password: 'sqlPassword',
    database: 'healthwave_master',
    port: 3306
  }
}

module.exports = config;

```

So I think I'm on the right track but perhaps not writing that properly just yet.
The result I get is:
```
$ node db_ssh_connect
C2 :: error ::undefined
forwardOut: ready!
C2 :: error ::Error: Timed out while waiting for handshake
```

So the second connection is giving an error for some reason.

**Comment by thomasfaller** [comment]
hmmmmm
lots of typing errors in there, I think I'm getting there:
```
c1.on('ready', function () {
  c1.forwardOut(
    '127.0.0.1',
    12345,
    '217.78.5.141',
    2200,
    function (err, stream) {
      if (err) throw err;
      console.log('forwardOut: ready!');
      const c2 = new Connection();
      c2.connect({
        sock: stream,
        host: config.mysql.host,
        username: config.mysql.user,
        password: config.mysql.password
      });
      c2.on('ready', function () {
        console.log('Connected (c2)');
      });
      c2.on('error', function (err) {
        console.log('C2 :: error ::' + err);
      });
      stream.emit('connect');
    })
});

c1.on('error', function (err) {
  console.log('C1 :: error ::' + err);
});
```

I'm getting a
```
C2 :: error ::Error: All configured authentication methods failed
```

probably meaning that something in my credentials (mysql) is not right?

**Comment by thomasfaller** [comment]
Still not working sadly. I enabled `debug: console.log` in the connection and got this:

```
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: password auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (keyboard-interactive)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: keyboard-interactive auth failed
```

**Comment by thomasfaller** [comment]
Hey guys, any thoughts on what could be the issue?

**Comment by mscdex** [comment]
Let me ask what I was asking for previously in a different way, do you have an OpenSSH client command line example that you could share that accomplishes what you want?

**Comment by thomasfaller** [comment]
I would normally use [Sequel Pro](https://www.sequelpro.com) to query in the mySQL databases through the SSH tunnel.

We do have a PHP app doing the whole thing just fine (PHP is so easy for this type of backend thing) but I wanted to craft an app of my own in Javascript (using Node).

Regarding the Command Line, to be honest, I know how to connect to the SSH:
```
$ ssh samp@217.78.5.141 -p 2200
```
This will prompt the password and connect me then but then I don't know how to query a mySQL from there.
Not sure this helps

**Comment by mscdex** [comment]
Do you have screenshot(s) of the Sequel Pro connection settings?

**Comment by thomasfaller** [comment]
Sure:

<img width="472" alt="screenshot 2018-05-31 13 08 49" src="https://user-images.githubusercontent.com/23104176/40781455-dbb1b98c-64d3-11e8-8035-e67c47b470d8.png">

**Comment by mscdex** [comment]
Ok, then it appears you are only dealing with 2 hosts. In that case your original code was almost correct. The following should work:

```js
ssh.on('ready', function () {
  ssh.forwardOut(
    '127.0.0.1',
    12345,
    '10.26.0.160',
    3306,
    function (err, stream) {
      if (err) {
        console.error('forwardOut Error: ' + err);
        return;
      }
      console.log('forwardOut: ready!');
      const db = mysql.createConnection({
        user: 'xxxxx',
        password: 'xxxxxxxxxxxx',
        database: 'xxxxxxxxxx',
        stream: stream
      });
      db.connect(function (err) {
        if (err) {
          console.error('error connecting: ' + err.stack);
          return;
        }
        console.log('connected as id ' + connection.threadId);
      });
      db.query('SELECT * FROM comms WHERE action = 6', function (err, results) {
        if (err) {
          console.log("Error while querying the database");
          console.error(err)
        }
      });
    });
}).connect({
  host: '217.78.5.141',
  user: 'xxxxxxxxxxxx',
  password: 'xxxxxxxxxxxxxxxxxx',
  port: 2200
});
```

**Comment by thomasfaller** [comment]
Thanks so much! Now I get how this works and it makes sense that the host and port should only go into the forwardOut method.
Thanks!
