### ISSUE TITLE
USERAUTH_FAILURE when attempting to connect to an SFTP server

### ISSUE THREAD

**Issue by ch-andrewrhyne** [mscdex/ssh2#703]
Trace:
```
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Local ident: 'SSH-2.0-ssh2js0.2.1'
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Client: Trying 52.44.134.39 on port 22 ...
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Client: Connected
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_INIT
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_GREETING
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_HEADER
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Remote ident: 'SSH-2.0-2.0'
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Outgoing: Writing KEXINIT
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKET
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: pktLen:796,padLen:5,remainLen:792
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATA
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Comparing KEXINITs ...
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (remote) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: KEX algorithm: ecdh-sha2-nistp256
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (remote) Host key formats: ssh-rsa
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Host key format: ssh-rsa
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (remote) Client->Server ciphers: aes128-cbc,rijndael128-cbc,3des-cbc,blowfish-cbc,aes192-cbc,rijndael192-cbc,aes256-cbc,rijndael256-cbc,rijndael-cbc@lysator.liu.se,cast128-cbc,rijndael-cbc@lysator.liu.se,aes128-ctr,aes192-ctr,aes256-ctr
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Client->Server Cipher: aes128-ctr
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (remote) Server->Client ciphers: aes128-cbc,rijndael128-cbc,3des-cbc,blowfish-cbc,aes192-cbc,rijndael192-cbc,aes256-cbc,rijndael256-cbc,rijndael-cbc@lysator.liu.se,cast128-cbc,rijndael-cbc@lysator.liu.se,aes128-ctr,aes192-ctr,aes256-ctr
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Server->Client Cipher: aes128-ctr
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha1-96,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-sha1-96,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (remote) Client->Server compression algorithms: zlib,none
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Client->Server compression algorithm: none
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: (remote) Server->Client compression algorithms: zlib,none
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Server->Client compression algorithm: none
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Outgoing: Writing KEXECDH_INIT
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKET
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: pktLen:380,padLen:7,remainLen:376
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATA
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Checking host key format
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Checking signature format
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Verifying host fingerprint
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Host accepted by default (no verification)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Verifying signature
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Outgoing: Writing NEWKEYS
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKET
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATA
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKET
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Decrypting
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATA
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Decrypting
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: HMAC size:32
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAVERIFY
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Verifying MAC
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKET
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Decrypting
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATA
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Decrypting
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: HMAC size:32
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAVERIFY
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Verifying MAC
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Client: none auth failed
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Outgoing: Writing USERAUTH_REQUEST (publickey -- check)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKET
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Decrypting
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: pktLen:556,padLen:4,remainLen:544
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATA
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Decrypting
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: HMAC size:32
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAVERIFY
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Verifying MAC
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_PK_OK
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Outgoing: Writing USERAUTH_REQUEST (publickey)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKET
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Decrypting
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: pktLen:44,padLen:19,remainLen:32
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATA
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Decrypting
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: HMAC size:32
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAVERIFY
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: Verifying MAC
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
info: [SFTPConnectionManager - SSH2 Debugger] DEBUG: Client: publickey auth failed
```

Attempting to connect with a username + private key (and a pre-generated public key, although it seems like this lib generates it's own public key from the private key so not sure if that's an issue)

The final error that pops out is `All configured authentication methods failed`

**Comment by mscdex** [comment]
The server said the public key was ok, but then the actual authentication failed. You might have to check the server logs to see what went wrong.

**Comment by laxmikanta415** [comment]
I am facing the same problem , the connection works if i am trying from a non ssl site , when i moved to ssl i am unable to connect and getting the same error:

EBUG: Parser: Decrypting                                                                            │
│                                              ││ index > DEBUG: Parser: HMAC size:32                                                                          │
│                                              ││ index > DEBUG: Parser: IN_PACKETDATAVERIFY                                                                   │
│                                              ││ index > DEBUG: Parser: Verifying MAC                                                                         │
│                                              ││ index > DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)                                                      │
│                                              ││ index > DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE                                          │
│                                              ││ index > DEBUG: Client: none auth failed                                                                      │
│                                              ││ index > DEBUG: Outgoing: Writing USERAUTH_REQUEST (publickey -- check)                                       │
│                                              ││ index > DEBUG: Parser: IN_PACKETBEFORE (expecting 16)                                                        │
│                                              ││ index > DEBUG: Parser: IN_PACKET                                                                             │
│                                              ││ index > DEBUG: Parser: Decrypting                                                                            │
│                                              ││ index > DEBUG: Parser: pktLen:44,padLen:7,remainLen:32                                                       │
│                                              ││ index > DEBUG: Parser: IN_PACKETDATA                                                                         │
│                                              ││ index > DEBUG: Parser: Decrypting                                                                            │
│                                              ││ index > DEBUG: Parser: HMAC size:32                                                                          │
│                                              ││ index > DEBUG: Parser: IN_PACKETDATAVERIFY                                                                   │
│                                              ││ index > DEBUG: Parser: Verifying MAC                                                                         │
│                                              ││ index > DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)                                                      │
│                                              ││ index > DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE                                          │
│                                              ││ index > DEBUG: Client: publickey auth failed                                                                 │
│                                              ││ index > error block                                                                                          │
│                                              ││ index > { Error: All configured authentication methods failed                                                │
│                                              ││ index >     at doNextAuth (/home/ubuntu/ssh-server/node_modules/ssh2/lib/client.js:412:17)                   │
│                                              ││ index >     at tryNextAuth (/home/ubuntu/ssh-server/node_modules/ssh2/lib/client.js:483:5)                   │
│                                              ││ index >     at SSH2Stream.onUSERAUTH_FAILURE (/home/ubuntu/ssh-server/node_modules/ssh2/lib/client.js:596:5  │
│                                              ││ index >     at emitTwo (events.js:126:13)                                                                    │
│                                              ││ index >     at SSH2Stream.emit (events.js:214:7)                                                             │
│                                              ││ index >     at parsePacket (/home/ubuntu/ssh-server/node_modules/ssh2-streams/lib/ssh.js:3728:10)            │
│                                              ││ index >     at SSH2Stream._transform (/home/ubuntu/ssh-server/node_modules/ssh2-streams/lib/ssh.js:694:13)   │
│                                              ││ index >     at SSH2Stream.Transform._read (_stream_transform.js:186:10)                                      │
│                                              ││ index >     at SSH2Stream._read (/home/ubuntu/ssh-server/node_modules/ssh2-streams/lib/ssh.js:253:15)        │
│                                              ││ index >     at SSH2Stream.Transform._write (_stream_transform.js:174:12) level: 'client-authentication' }    │
│                                              ││ index > DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)                                                 │
│                                              ││ index > ===== CLOSE ======

**Comment by mscdex** [comment]
SSL has nothing to do with SSH. It sounds like you might have the wrong client configuration.

**Comment by laxmikanta415** [comment]
@mscdex I have verified my connection to the instance from another server with same code , where i dont have SSL , and that works. But when i try to do the connection from the SSL added server i am getting this error. Currently the same code is running on 3 servers where with same code i dont have any errors .Only facing this issue on the server with SSL.

**Comment by mofux** [comment]
@laxmikanta415 I got the feeling that you are confusing `SFTP` with `FTPS`. `SFTP` uses SSH as the underlying transport protocol, `FTPS` is a totally different protocol which is basically `FTP` with SSL encryption on top. You won't be able to connect to `FTPS` servers with this module, it only supports `SFTP`. Can you explain what you mean when saying "server with SSL"? Do you mean a FTPS server?

**Comment by laxmikanta415** [comment]
@mofux I really understand the difference between : SSL and SSH and here. Sorry for not providing the complete info of my implementation.

The application i have created is used to create an interactive shell by connecting to an remote instance using ssh. 

conn
            .on('ready', function() {
              ws.write('\n*** SSH CONNECTION ESTABLISHED ***\n');
              conn.shell(function(err, stream) {
                if (err) {
                  console.log('eer');
                  ws.write('\n*** SSH SHELL ERROR: ' + err.message + ' ***\n');
                  ws.write('\n*** ERROR IN CONNECTION DETAILS ***\n');
                  conn.end();
                  return;
                }
                stream.setEncoding('binary');
                stream
                  .pipe(ws)
                  .pipe(stream)
                  .on('close', function() {
                    conn.end();
                  });
              });
            })
            .on('close', function() {
              ws.write('\n*** SSH CONNECTION CLOSED ***\n');
              ws.close();
            })
            .connect({{
          host: "IP_ADDRESS",
          port: 22,
          username: 'USER_NAME',
          privateKey: "STRING PRIVATE KEY"
        };);

This code  i have hosted in a linux server with domain : example.com on port 3000  with ws this works .
Then i have added SSL to same working server and made it https://example.com and now with wss i can able to call the websocket but getting error on connection point . The log is what provided at the top.

**Comment by mofux** [comment]
Oh I see, so you are using websockets to relay the ssh stream to the client browser. It works if the websocket connection is unencrypted (HTTP), but fails if the websocket connection is  served via an encrypted SSL connection (HTTPS). I don't think the SSL connection is the problem here.

From reading your log, the connection already fails before you get the actual shell stream (before relaying it to the websocket), because the `none` and `publickey` auth methods get rejected by the SSH server. Have you verified that with the private key you are using in your code, and on that failing server, the connection works using the `ssh` command?

**Comment by laxmikanta415** [comment]
Yes @mofux i have verified the ssh connection using the private key it works , and i have verified it multiple times. So thats not the issue.

**Comment by mofux** [comment]
Not sure how to help further with this then. One last thought: how do you get the `user` and `privateKey` that you pass to the ssh `connect` method? Do you also get it via the websocket connection? Just thinking, maybe the connection properties differ between environments (maybe you receive different values if the websocket is using SSL). You should log the privateKey and user that is used for the connection and compare them between the working and not working environment.

**Comment by laxmikanta415** [comment]
will check that, thanks for your quick response.
