### ISSUE TITLE
SFTP Server: How to correctly allow uploading folders

### ISSUE THREAD

**Issue by P4sca1** [mscdex/ssh2#708]
At the moment I'm doing this:
```
// Open a new file handle.
sftpStream.on('OPEN', (reqId, fileName, flags, attrs) => {
    helper.queueTask(fileName, next => {
        // Transform cyberduck flag to overwrite an existing file.
        if (flags === 18) {
            flags = OPEN_MODE.TRUNC | OPEN_MODE.CREAT | OPEN_MODE.WRITE;
        }

        // Transform Filezilla flag to resume an upload.
        if (flags === 2) {
            flags = OPEN_MODE.APPEND | OPEN_MODE.CREAT | OPEN_MODE.WRITE;
        }

        const flag = SftpStream.flagsToString(flags);
        if (!flag) {
            console.log('Unsupported flag ' + flags);
            sftpStream.status(reqId, STATUS_CODE.OP_UNSUPPORTED);
            return next();
        }

        const isWriter = flag.includes('w') || flag.includes('a')

        async.waterfall([
            callback => {
                // If we are writing (or appending) to a file, we need to
                // ensure, that the file (and all subdirectories) exist. 
                if (isWriter) {
                    fs.ensureFile(gameServer.fb.path(fileName), callback);
                } else {
                    callback();
                }
            },
            callback => {
                fs.open(gameServer.fb.path(fileName), flag, 0o666, callback);
            }
        ], (err, fd) => {
            if (err) {
                console.log('failed to open file' + err);
                sftpStream.status(reqId, STATUS_CODE.FAILURE);
                return next();
            }

            let handle = helper.makeHandle({
                location: fileName,
                fd
            });

            sftpStream.handle(reqId, handle);
            next()
        });
    });
```

```
// Write to the file descriptor.
sftpStream.on('WRITE', (reqId, handle, offset, data) => {
    const handleInfo = helper.getHandleInfo(handle);

    helper.queueTask(handleInfo.location, next => {
        fs.write(handleInfo.fd, data, 0, data.length, err => {
            if (err) {
                console.log('Failed to write file ' + err);
                sftpStream.status(reqId, STATUS_CODE.FAILURE);
                return next();
            }

            sftpStream.status(reqId, STATUS_CODE.OK);
            next();
        });
    });
});
```

This allows uploading folders by just creating all subdirectories when a file is written.
However I do not know if this is the correct way of doing this.
When using Filezilla, it works, but gives me an error, because it is doing a READDIR on the folder that the file should be placed in (maybe to find out, whether it should be overwritten, because it already exists). This folder does not yet exist, because it is created later in the OPEN event.
Even though the approach pasted above works, it feeld kinda hacky and I would like to know the correct way of doing this without producing an error.

I hope you can explain this to me or link me some ressources! :)

**Comment by mscdex** [comment]
Directories should only be created with a `MKDIR` request.

`OPEN` is for opening a file (for use with `READ`/`WRITE`, `FSTAT`, `FSETSTAT`, and/or `CLOSE`).

`OPENDIR` is for opening a directory (for use with `READDIR`, `FSTAT`, `FSETSTAT`, and/or `CLOSE`).

All of these requests should be independent and not cause side effects for each other (e.g. opening a file should not implicitly create directories, requests for one handle should not affect another handle, etc.).

**Comment by P4sca1** [comment]
Okay, that makes sense.
I changed my code, so that `OPEN` does no longer create subdirectories and `OPENDIR` gives a `NO_SUCH_FILE` when the directory does not exist.
Filezilla now detects that the folder does not exist when uploading and creates it with`MKDIR`.
However it still gives a red error before. Is there any way to work around this?

Here's the log when uploading a folder with files in it (some german parts in it, but they are not that important). I marked the red line with stars:
```
Status:      	Starte Upload von /Users/pascal/code/egmrp/starwarsrp/entities/effects/effect_sw_laser_blue_glow_dual/init.lua
Befehl:      	cd "/effect_sw_laser_blue_glow_dual"
*Fehler:      	Directory /effect_sw_laser_blue_glow_dual: no such file or directory*
Befehl:      	cd "/"
Antwort:    	New directory is: "/"
Befehl:      	mkdir "effect_sw_laser_blue_glow_dual"
Antwort:    	mkdir /effect_sw_laser_blue_glow_dual: OK
Befehl:      	cd "/effect_sw_laser_blue_glow_dual"
Antwort:    	New directory is: "/effect_sw_laser_blue_glow_dual"
Status:      	Empfange Verzeichnisinhalt für "/effect_sw_laser_blue_glow_dual"...
Befehl:      	ls
Status:      	Listing directory /effect_sw_laser_blue_glow_dual
Befehl:      	put "/Users/pascal/code/egmrp/starwarsrp/entities/effects/effect_sw_laser_blue_glow_dual/init.lua" "init.lua"
Befehl:      	local:/Users/pascal/code/egmrp/starwarsrp/entities/effects/effect_sw_laser_blue_glow_dual/init.lua => remote:/effect_sw_laser_blue_glow_dual/init.lua
Status:      	Dateiübertragung erfolgreich, 2766 Bytes in 1 Sekunde übertragen
Status:      	Empfange Verzeichnisinhalt für "/"...
Status:      	Listing directory /
Status:      	Anzeigen des Verzeichnisinhalts für "/" abgeschlossen
```

**Comment by mscdex** [comment]
Is the file successfully uploaded? If so, the red "error" can probably be ignored, unless somehow you are returning a non-existent directory in response to a `READDIR` or something for example.

**Comment by P4sca1** [comment]
Yes everything is being uploaded just fine. Guess I'm going to ignore the error then.
I do have another problem with Cyberduck and my custom sftp server. Is it okay to ask it here, because it has something to do with my implementation not working and not with your library.
