### ISSUE TITLE
How to properly handle upload resumes, client crashes and errors?

### ISSUE THREAD

**Issue by P4sca1** [mscdex/ssh2#710]
I need some more hints on these  things. I know I already asked a ton of things but I hope somebody can still help me out here.

My first question is how upload resumes should be handled. In FileZilla for example you can pause the upload and continue it later. With my implementation, it currently asks whether to overwrite the file and it does not continue the upload. When interrupting the upload, it just leaves the not finished file on the server and the client then thinks that the file already exists on the server. What needs to be done to support upload resumes?

My second question is how I should handle errors. At the moment I'm just using the error listener to prevent the application from crashing:
```
client.on('error', err => {
    console.log('An error occured: ' + err);
});
```
However what if an error on a `WRITE` operation occurs? I guess I need to close the open file handle and descriptor manually afterwards, but how can I detect this? The same goes for client crashes. Should I check for open handles on the `end` event?

Another thing I noticed when connecting with FileZilla for Windows without a password or username is that I do get this error in console:
`An error occured: Error: Unable to authenticate`
I don't get this error when connecting from mac, it just silently rejects the connection.
Why is that the case and do I need to handle something different here?

**Comment by mscdex** [comment]
> What needs to be done to support upload resumes?

There is nothing special to support resuming uploads. Clients and get file sizes and simply start writing at any offset they want.

> However what if an error on a WRITE operation occurs? I guess I need to close the open file handle and descriptor manually afterwards, but how can I detect this?

I'm not sure what you mean here, but if you are doing `fs.write()`, then if the `fs.write()` callback is passed an error, you would send back an error status instead of an 'ok' status.

> The same goes for client crashes. Should I check for open handles on the end event?

Yes, although listening on the `'close'` event on the underlying ssh client object would be better in case of an abrupt connection shutdown.

> Another thing I noticed when connecting with FileZilla for Windows without a password or username is that I do get this error in console:
> An error occured: Error: Unable to authenticate
> I don't get this error when connecting from mac, it just silently rejects the connection.

Differences in behavior with FileZilla across platforms is beyond me. That's probably something those developers would know better.

**Comment by P4sca1** [comment]
Okay, then this should work fine I guess.
```
// Close all open file descriptors on connection close.
client.on('close', hadError => {
    if (helper) {
        _.forEach(helper.handles, handleInfo => {
            if (handleInfo.fd) {
                fs.close(handleInfo.fd);
            }
        });
    }
});
```
Thank you again for your help!

**Comment by P4sca1** [comment]
I'm supporting both, so that should not be a problem.
