### ISSUE TITLE
Cannot transfer files larger than 1GB

### ISSUE THREAD

**Issue by kamesh95** [mscdex/ssh2#711]
I am trying to transfer files larger than 1 GB from a source SFTP to a destination SFTP but the file always stalls around 0.99 GB even if the connection is alive. This happens with individual files of size greater than 1 GB and also if I transfer multiple files that together make up more than 1 GB in a single connection.

Here's my code:-

[transfer.txt](https://github.com/mscdex/ssh2/files/2083117/transfer.txt)

**Comment by kamesh95** [comment]
I debugged this a but and it seems that the problem is with the sftp.createReadStream method because when I try to transfer a local file to remote sftp, it works well but streaming from a source sftp and then transferring to remote sftp, does not work!

**Comment by mscdex** [comment]
Beware of performing uploads for multiple files at once as servers (SFTP server itself and/or the underlying OS) may have a limit on that sort of thing.

Does this still happen with a modern version of node (e.g. v10.x or v12.x) and the latest `ssh2`/`ssh2-streams`? If so, if you set `debug: console.log` in your connection config objects, what are the server ident strings for the source and destination? I can try to look into reproducing this on my end.
