### ISSUE TITLE
getting client ip from ssh server

### ISSUE THREAD

**Issue by amitgilad3** [mscdex/ssh2#714]
i set up an ssh server, and i would like to validate the srcIp every time a  user establishes a connection, is there a way to get the srcIp of the user ???
i am running my ssh server just like in the example 
**Server Examples Password and public key authentication and non-interactive (exec) command execution**

thanks in advance

**Comment by mscdex** [comment]
The client IP is available as shown [here](https://github.com/mscdex/ssh2#server-events).

**Comment by amitgilad3** [comment]
thanks for the quick reply , works :)
