### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by rdvnkrtl** [mscdex/ssh2#715]
Hello,
I've been trying run the following code.It runs for my own sftp server but it doesn't run for another sftp server. Although I can't reach this server via my code, I can reach it by Filezilla.

Error is:All configured authentication methods failed.

What can be differences between these two servers? Or Is it about options configuration in code? Thanks...
```node.js
var Client = require('ssh2').Client;`
   var connSettings = {
        host:'host_name',
        user:'user_name',
        port:22,
        password:"user_pass",
    };
    var remotePathToList = '/folder';
    var conn = new Client();
    conn.on('ready', function() {
        conn.sftp(function(err, sftp) {
         if (err) throw err;
         sftp.readdir(remotePathToList, function(err, list) {
                if (err) throw err;
                console.dir(list);
                conn.end();
         });
    });
}).connect(connSettings);
```

**Comment by mscdex** [comment]
Perhaps a different authentication method is expected, such as `keyboard-interactive` if you are in fact using a password, or possibly a private key is being used (either implicitly or explicitly).

**Comment by rdvnkrtl** [comment]
Thanks for response, mscdex. If 'keyboard-interactive' authentication method is used, is it possible to handle this error with configuration in code?

**Comment by mscdex** [comment]
I'm not sure what you're asking. There is no way to know that the wrong authentication method was used for any arbitrary server and end user. If you're given a password though, you could just try `password` first and if you get an all methods failed error, try the connection again with `tryKeyboard: true` and have the appropriate event handler for that.

Currently this module does not support customizing the authentication behavior, so there is just a fixed order of methods that are tried once.

**Comment by rdvnkrtl** [comment]
Thank you @mscdex , it was about my bad. I edited sftp pass.
