### ISSUE TITLE
Connections not being closed after conn.end()

### ISSUE THREAD

**Issue by BioNanoScott** [mscdex/ssh2#719]
Hello, 

We have a method to write a text string to a file.  The operation completes successfully.  We see the connection open, connection closed, and connection closing messages in the console.  However, we are monitoring the number of connections (centos 7.3) with the following command (watch "netstat -n | grep :22 | wc -l" and we can see that the number of connections on port 22 climbs each time we call this method.  the connections are not being released.   I have included the inerds of our method below.  Are we missing something?

----

        const deferred = Q.defer();
        let conn = new Client();
        conn.on('ready', () => {
            conn.sftp((err, sftp) => {

                if (err) {
                    console.log("- sftp failed to open");
                    conn.end();
                    deferred.reject(err);
                    return;
                }

                var writeStream = sftp.createWriteStream(targetFile);
                writeStream.on('close', () => {
                    console.log('connection closed');
                    conn.end();
                    deferred.resolve(targetFile);
                });
                writeStream.write(dataContent);
                writeStream.end();

            })
        }).on('close', () => {
            console.log('connection closing');
        }).connect(this.connSettings);

        return deferred.promise;

**Comment by mscdex** [comment]
* What state are the sockets in (after `.end()` is called), as reported by netstat?

* What output do you see in the console?

* This is just a suggestion, but if you're just writing a single chunk as the contents of the file, you can simplify things by instead using `sftp.writeFile()` (API is similar to `fs.writeFile()`)

**Comment by BioNanoScott** [comment]
Here is the state of the sockets: 

--before--
bionano@iryssolve05:~/access/web/Server/Config$ netstat -n | grep :22
tcp        0     64 192.168.49.41:22        192.168.50.1:50846      ESTABLISHED
tcp        0      0 192.168.49.41:22        192.168.48.136:7451     ESTABLISHED
tcp        0      0 192.168.49.41:22        192.168.48.178:35258    ESTABLISHED
tcp        0      0 192.168.49.41:22        192.168.48.146:59700    ESTABLISHED


--after--
tcp        0     64 192.168.49.41:22        192.168.50.1:50846      ESTABLISHED
tcp        0      0 192.168.49.41:22        192.168.49.41:43334     TIME_WAIT
tcp        0      0 192.168.49.41:22        192.168.49.41:43332     TIME_WAIT
tcp        0      0 192.168.49.41:43318     192.168.49.41:22        TIME_WAIT
tcp        0      0 192.168.49.41:22        192.168.49.41:43330     TIME_WAIT
tcp        0      0 192.168.49.41:22        192.168.49.41:43338     TIME_WAIT
tcp        0      0 192.168.49.41:43324     192.168.49.41:22        TIME_WAIT
tcp        0      0 192.168.49.41:22        192.168.49.41:43326     TIME_WAIT
tcp        0      0 192.168.49.41:22        192.168.48.136:7451     ESTABLISHED
tcp        0      0 192.168.49.41:22        192.168.48.178:35258    ESTABLISHED
tcp        0      0 192.168.49.41:22        192.168.48.146:59700    ESTABLISHED
tcp        0      0 192.168.49.41:22        192.168.49.41:43328     TIME_WAIT
tcp        0      0 192.168.49.41:43320     192.168.49.41:22        TIME_WAIT
tcp        0      0 192.168.49.41:22        192.168.49.41:43336     TIME_WAIT

**Comment by mscdex** [comment]
TCP sockets in a TIME_WAIT state are a normal part of the TCP connection lifecycle. The TCP stack will eventually transition these sockets to the CLOSED state after a period of time.

**Comment by BioNanoScott** [comment]
Okay, but these connections are not clearing.  The system is pretty active.  It sends a file over scp every 2 seconds.   After a few hours there are a few thousand connections are open and the system stops accepting scp and becomes unresponsive.   Any idea how to get these TIME_WAIT connections?

**Comment by BioNanoScott** [comment]
Found this article.  Will give it a try on Monday.

http://www.fromdual.com/huge-amount-of-time-wait-connections

**Comment by mscdex** [comment]
If you're making a new connection that often and it's to the same destination, consider just keeping the connection open and reusing it? That would be more efficient anyway.

**Comment by BioNanoScott** [comment]
Is there an accepted pattern or example of how to keep a connection open or pooling connections?

**Comment by mscdex** [comment]
I'm not sure what you mean by accepted pattern, but there are examples of generic pooling elsewhere. The gist of it is to keep connections in some kind of map (e.g. `Map`, plain object, or some other data structure) where you look up an existing connection by some minimum common attributes, probably IP, port, and authentication config for example. If you find a match, then use that existing connection, otherwise create a new one and add it to the pool.

It would probably also be wise to implement a queue per connection for commands, since servers can limit the number of concurrent "channels" (this includes things like `exec()`, `shell()`, `sftp()`, etc.). I believe OpenSSH's server defaults to 10, but you never know if the default has been overridden for any arbitrary server.

Alternatively, there are existing modules on npm like [`generic-pool`](https://github.com/coopernurse/node-pool) that implement these kinds of features already if you're interested.

**Comment by mscdex** [comment]
You'll probably want to unset those properties when `this.conn` disconnects. There's also a race condition where `this.conn` is set but `this.sftp` is not yet set, when duplicate connections would be made.

**Comment by BioNanoScott** [comment]
Thanks for the feedback.  I will make those adjustments.
