### ISSUE TITLE
SFTP not working

### ISSUE THREAD

**Issue by waqasraz** [mscdex/ssh2#724]
```
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG[SFTP]: Parser: Response: STATUS
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
{ Error: Failure
    at SFTPStream._transform (/home/waqas/Downloads/fix scp/node-scp2/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/home/waqas/Downloads/fix scp/node-scp2/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:413:12)
    at writeOrBuffer (_stream_writable.js:397:5)
    at SFTPStream.Writable.write (_stream_writable.js:295:11)
    at Channel.ondata (_stream_readable.js:672:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12) code: 4, lang: '' }
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
DEBUG: Parser: IN_INIT
DEBUG: Outgoing: Writing CHANNEL_CLOSE (1)```
```

**Comment by mofux** [comment]
The error you are seeing is a very generic error thrown from your STP server. SFTP error messages are usually very unprecise to what the real problem is (`Failure`). You can check more on that error here: https://winscp.net/eng/docs/sftp_codes

**Comment by waqasraz** [comment]
no way to debug this issue?

**Comment by mofux** [comment]
Does the operation you are performing work with another SFTP tool?

**Comment by waqasraz** [comment]
yes, everything works fine if do sftp on the terminal.

**Comment by waqasraz** [comment]
Also, if use the same idea but different server it works fine. Like if I sftp a linux server no problem, but when I change it to this server I get this problem.

**Comment by waqasraz** [comment]
only when you do sftp.fastput

**Comment by mscdex** [comment]
Perhaps the server has a concurrent write limit. Try passing a custom, lower `concurrency` value (default is `64`) in the options object. For example: `sftp.fastPut(localFile, remoteFile, { concurrency: 32 }, callback);`

Try different values to see what the server accepts. It could very well be that it only accepts one outstanding SFTP request at any given time, per connection.

**Comment by waqasraz** [comment]
no, it didn't work no matter what I do I end up at this line

https://github.com/mscdex/ssh2-streams/blob/55fd9c36b6dca8dbf0588a1d6f450b85c784dc72/lib/sftp.js#L412

**Comment by mscdex** [comment]
Can you post a debug log (set `debug: console.log` in the connection config object)?

**Comment by waqasraz** [comment]
I will send the log shortly. But please note that all other commands on SFTP work fine. Like if I connect and get directory items etc. The problem happens when trying to upload a file.

**Comment by vsTianhao** [comment]
I have the same problem

**Comment by MrZsxForJAVA** [comment]
I have the same err, code: 4
