### ISSUE TITLE
Readme needs an example on how to run a user interactive ssh connection.

### ISSUE THREAD

**Issue by SephReed** [mscdex/ssh2#726]
Assuming ssh2 is capable of such functionality, it would be nice if there was an example of opening up an ssh connection which uses process.stdio for it's interaction.  The use case for this is a command line tool which opens ssh connections for the user.

I can imagine ways of rolling my own, but it seems like there must be a very straightforward way, and an example of it would help a ton.

**Comment by mscdex** [comment]
Not every possible scenario can be placed in the readme as it would get way too large, there are already quite a few examples.

As far as the interactive session goes, you just use the streams however you want. If you want to be able to type directly into the session, just pipe the necessary streams together. It's that simple. Other than that, it really depends on just how much of a fleshed out client you want to build. See [this recent simple interactive shell example](https://github.com/mscdex/ssh2/issues/718#issuecomment-406823236) that handles things like allocating a pty and window resize events.
