### ISSUE TITLE
Shut down sftp server programmatically

### ISSUE THREAD

**Issue by uladkasach** [mscdex/ssh2#727]
Hi! 

I am using the ssh2 library to create a sftp server for testing during my testing suite. The server starts successfully and tests run as expected - all is great.

However, after all of the tests have been conducted the testing script does not exit as the sftp server process is still listening/executing.

Is there a method by which I can programmatically shutdown the sftp server? e.g., `server.terminate()`?

**Comment by mscdex** [comment]
You can call `server.close()` with an optional callback.
