### ISSUE TITLE
Shut down sftp server automatically after half an hour,

### ISSUE THREAD

**Issue by vishnusinghchauhan** [mscdex/ssh2#732]
i am using ss2 library  my server automatically shutdown.

var stream, currentUserId, filepath;
        let sftp = new Client();
        sftp.connect({
            host: hostname,
            port: 22,
            username: test,
            password: test
        }).then(() => {
            return sftp.fastGet(filename, locaion);
        }).then((data) => {
            console.log(data, 'the data info');
            filepath = filepath;
            fs.readFile(filepath, 'utf8', function(err, data) {
                //if (err) throw err;
                if (err) {
                    console.log(err);
                    throw err
                } else {
                    stream = data;
                    foo()
                }
                sftp.close();
            }));

        }).catch((err) => {
            console.log(err, 'catch error');
            sftp.close();
        })

**Comment by mscdex** [comment]
I don't understand what you're asking exactly, however there are some things I see wrong with the code you've shown so far:

1. `ssh2` does not utilize Promises, so unless you're using some other library that provides them on top of `ssh2`, that `.connect()` will not work
2. I don't see the sftp session being explicitly started, which also makes me think another library is being used here
3. You're not waiting for the file to be transferred before reading it from disk
