### ISSUE TITLE
Missing close event and keepalive timeout storm

### ISSUE THREAD

**Issue by magnusjt** [mscdex/ssh2#740]
Hi,

I'm using the client close event to create a new connection when it is disconnected. I've also setup client keepalive messages.

version: 0.6.1
keepaliveInterval: 10000 
keepaliveCountMax: 1

The issue:
After some time (>10 minutes), sftp.readdir (and probably other methods) stops responding.
Some time after that (several hours), I get a storm of keepalive timeouts, all within a few seconds.
Finally, the close event is received.

Is there any logical reason for why the keepalives are delayed like this?

ps: This seems to only happen with some specific ssh servers / ssh server settings, though I'm not sure what they are

Edit:
I'm wondering if this is because the sftp connection is still technically up, but the server has just stopped responding, so keepalives are just hanging indefinitely or until the server closes for some reason. Unless I'm mistaken, there are no timeout checks on the keepalive messages?

**Comment by zxdong262** [comment]
@magnusjt 
Thank you for the feedback.
Please try the lastest version(0.25.1), sometimes I experirence connection lost too, there are some issure report about this. I will try to fix this.

**Comment by mscdex** [comment]
If you can provide code and any additional information needed to reproduce this, I can look into it.
