### ISSUE TITLE
Question: why promisifyAll can work for SFTPWrapper while promisify a single function will fail ?

### ISSUE THREAD

**Issue by qiulang** [mscdex/ssh2#741]
Hi,
I try to promisify SFTPWrapper functions and find that if I just promisify one SFTPWrapper function, say `readdir`, both using `util` and `bluebird` will have `unhandledRejection` :` "Cannot read property 'readdir' of undefined"`

I have to use bluebird's promisifyAll(SFTPWrapper) and it work as expected. But why is that ?

Thanks.

**Comment by mscdex** [comment]
I'm not familiar with those promisifying libraries/APIs, so you'd probably have to ask the developers of those tools for an answer instead.

**Comment by qiulang** [comment]
Hi I got the answer from https://stackoverflow.com/questions/53076334/bluebird-promise-promisifyall-can-work-while-promisify-a-function-of-that-object

Thanks for replying my question.
