### ISSUE TITLE
1 sftp frontend to N sftp backends

### ISSUE THREAD

**Issue by websitesca** [mscdex/ssh2#742]
We'd like to have 1 main sftp server that users connect to. But when they cd into a particular directory, the server will pipe/connect/shunt (not sure the correct term here) input/output via a backend sftp server. We do this because a particular user will have files distributed across several servers.

USER > SFTPSERVER (only 1) > SFTPBACKEND (N of these)

I'm wondering how to connect the streams or sockets of the USER to the SFTPBACKEND stream or socket via SFTPSERVER.

So basically I have 1 server, this is working ok. It needs to pull all the various directories for a user from an etcd server. Then I have N clients. The clients connect to their various servers on startup like this:

```javascript
var remoteNodeSftpStream;
var remoteNodeClient = new ssh2.Client();
remoteNodeClient
.on('ready', function() {
  console.log('remoteNodeClient :: ready');
  remoteNodeClient.sftp(function(err, sftpStream) {
    if (err) console.log(err);
    else remoteNodeSftpStream = sftpStream;
  });
})
.connect(ssh_config)
```

Then when the SFTPSERVER starts an sftp session with a user, I try to connect them:

```javascript
function onSftp(accept, reject) {
  console.log("new sftp session on SFTPSERVER");
  var sftpStream = accept();
  sftpStream.pipe(remoteNodeClient._sock).pipe(sftpStream); // I tried this
  process.stdin.pipe(remoteNodeStream._stream) // I tried this
  sftpStream.pipe(remoteNodeStream).pipe(sftpStream); // I tried this
  sftpStream.pipe(remoteNodeStream._stream).pipe(sftpStream); // I tried this
}
```

I know I have a big gap in my understanding somewhere and was hoping someone could point me in the right direction. 

I *thought* it seemed logical that whatever the USER sends, the SFTPSERVER could just forward along to the SFTPBACKEND and vice-versa.

**Comment by websitesca** [comment]
Also would like to add that kinda connecting the client and server methods together works. It just seems like a lot of work to implement all of the server and client methods for sftp when I could just connect the streams.

But for example, this does work when I have `sftpStream` for the USER and `client1Sftp` for the SFTPBACKEND.

```javascript
function onREADDIR(sftpStream, reqid, handle) {
  client1Sftp.readdir(handle, (err, list) => {
    if (err) {
      if (err.code == STATUS_CODE.EOF)
        sftpStream.status(reqid, STATUS_CODE.EOF);
      else
        sftpStream.status(reqid, STATUS_CODE.FAILURE);
    }
    else if (list) sftpStream.name(reqid, list);
    else sftpStream.status(reqid, STATUS_CODE.EOF);
  })
}
```

**Comment by mscdex** [comment]
The SFTPStream you get is not meant to be used like a traditional stream because it's already set up to communicate between the client and server sockets/streams. You're instead meant to handle the SFTPStream events and use the SFTPStream methods to receive requests and send responses. There is currently no official support for automatic proxying between SFTPStream instances.

**Comment by websitesca** [comment]
Gotcha, I'll implement the server then. Thanks!
