### ISSUE TITLE
Allow ssh-password in server SSH2

### ISSUE THREAD

**Issue by ryan-rez** [mscdex/ssh2#744]
Hi, I would like to know how to receive the links by sending a password next to the login. To activate the `'interactive keyboard'`, was it just insert `tryKeyboard: true` in the server configuration, and password? how do I do?

**Comment by mscdex** [comment]
Can you explain a bit more what you're asking? Passwords are supported in either the client or server context.

**Comment by ryan-rez** [comment]
> Hi, I would like to know how to receive the links by sending a password next to the login. To enable 'interactive keyboard', enter the keyboard in the server settings.

Sorry, my keyboard bugou

**Comment by ryan-rez** [comment]
> Can you explain a bit more what you're asking? Passwords are supported in either the client or server context.

Server context.

**Comment by mscdex** [comment]
There's an example of a server accepting password authentication in the readme.

**Comment by ryan-rez** [comment]
It does not accept, ctx.method receives 'none'. :/

**Comment by mscdex** [comment]
You can return a list of accepted methods if you want for clients that rely on it being returned by the server. Just pass an array of the authentication methods to `ctx.reject()`, for example: `ctx.reject(['password'])`.

**Comment by ryan-rez** [comment]
Almost made it. Because I want to accept password and not reject. But when I put `reject (['password'])`, the password method appeared but did not accept it. See in print. https://imgur.com/a/yLKpajH

**Comment by mofux** [comment]
It's because you are always rejecting before you can accept the password method. The authentication handler is called multiple times with different authentication methods, so it will first ask for 'none', and then after that it should hopefully ask for 'password'

**Comment by ryan-rez** [comment]
> It's because you are always rejecting before you can accept the password method. The authentication handler is called multiple times with different authentication methods, so it will first ask for 'none', and then after that it should hopefully ask for 'password'


If I remove ctx.reject (['password']), the method is 'none', and it is not possible to read the password. https://imgur.com/a/L10jvln

**Comment by ryan-rez** [comment]
https://imgur.com/a/rEU9A2W <-- client ssh of Ubuntu, password in command-line not working!

**Comment by mofux** [comment]
It's hanging after the 'none' authentication because you are not calling 'ctx.reject(['password'])'. Try it like this:

```javascript
client.on('authentication', function(ctx) {
  if (ctx.method === 'password') {
    ctx.accept();
  } else {
    ctx.reject(['password']);
  }
});
```

**Comment by ryan-rez** [comment]
Okay, that helped me.
