### ISSUE TITLE
SSH2 Server, get remote client port

### ISSUE THREAD

**Issue by ryan-rez** [mscdex/ssh2#745]
Is it possible to get the remote client port connected?

**Comment by mscdex** [comment]
Not currently, just the client IP.

**Comment by malixsys** [comment]
it's on _peername:
```new ssh2.Server({
    hostKeys: [{
        key: KEY,
        passphrase: '...'
    }]
}, function (client) { 
const info = client._sock._peername
})```

**Comment by mscdex** [comment]
@malixsys I meant via official, documented API. However, this was actually already added earlier this year in 93ea76be99b62c876cd93d6d74b5b27cb9e74cd9.
