### ISSUE TITLE
SSH2 support for RFC4716 format keys (OPENSSH) 

### ISSUE THREAD

**Issue by njpanderson** [mscdex/ssh2#746]
I recently had a bug report for a dependent of this package:
https://github.com/njpanderson/push/issues/37

It looks like `ssh-keygen` on Mac OS (Mojave, possibly older?) is now by default creating key pairs with the `-t rsa` flag in the newer RFC4716 format. I advised the user to use `-m PEM` to switch back to the older PEM format, but I can foresee this becoming more of a problem as adoption rises.

Is the RFC4716 format supported by the latest available ssh2 or its dependencies, and if not, will it be in any near future?

Thanks!

**Comment by mscdex** [comment]
RFC4716 defines a *public* key format. Are you sure you're not referring to the [newer OpenSSH key format](https://cvsweb.openbsd.org/src/usr.bin/ssh/PROTOCOL.key?annotate=HEAD) instead?

**Comment by njpanderson** [comment]
Yes, apologies - my mistake!

**Comment by mscdex** [comment]
A little while back I started adding support for the newer OpenSSH key format as part of an overhaul of the key parsing/handling code, but it's not quite ready yet.

**Comment by njpanderson** [comment]
That's great news, @mscdex - any idea if you'll manage to find time to get it done in the near future?

Thanks for the module as it stands, it's been critical for my work!

**Comment by ethanhungle** [comment]
Could you please add support for all hosts key encryption formats supported by FlowSSH https://www.bitvise.com/flowssh (Bitvise SSH Client). Many connections can be done by Bitvise SSH client but not by ssh2 package. I'm willing to donate when you add all the hosts key format.

**Comment by mscdex** [comment]
@ethanhungle it's not that easy. for example, support for ed25519 key will require OpenSSL 1.1.1, which has not made its way into node core yet.

As far as the "new" OpenSSH private key format goes, that should now be supported as of `ssh2` v0.7.0.
