### ISSUE TITLE
ssh jump host

### ISSUE THREAD

**Issue by soichih** [mscdex/ssh2#749]
I need to do something similar to the following using ssh2.

```
ssh -J jump.myserver.com myserver.com
```

@mscdex 

On issue #694,  you mention this.

> Making SSH connections through a jump host is easy to do if you're just needing to make connections from within your process. 

Could you explain how I can do this? I was hoping I could do something like ..

```

var ssh_config = {
  host: 'myserver.com',
  port: 22,
  username: 'nodejs',
  password: 'rules',

  jumphost: 'jump.myserver.com',
  jumpost: 22,
  jumpusername: 'myjump',
  jumppassword: 'jumppass',
};
```

**Comment by mscdex** [comment]
There's an example [here](https://github.com/mscdex/ssh2#connection-hopping). Although instead of spinning up netcat, you can typically just use `forwardOut()` to get an outbound stream.

**Comment by mscdex** [comment]
Do you have `agentForward: true` set? Can you post the code you have currently?

**Comment by soichih** [comment]
Yes, I've set `agentForward: true`.

Here is my test code

```
const ssh2 = require('ssh2');
const fs = require('fs');

let conn = new ssh2();
let conn2 = new ssh2();
conn.connect({
    host: "jump.server.com",
    post: 22, 
    username: "hayashis",
    privateKey: fs.readFileSync("/home/hayashis/.ssh/id_rsa"),
    passphrase: "mypassword",

    agent: process.env.SSH_AUTH_SOCK,
    agentForward: true,
});

conn.on('ready', ()=>{
    
    conn.exec("nc real.server.com 22", (err, stream)=>{
        conn2.connect({
            sock: stream,
            username: "hayashis",
            debug: console.log,
        });
    })  
    
})

conn2.on('ready', ()=>{
    con2.exec("hostname", (err, stream)=>{
        console.log(err);
        stream.on('data', data=>{
            console.log(data.toString());
        });
        stream.on('end', ()=>{
            console.log("ended");
        })
    }); 

});

```

When I run this, I get following output.

```
...
DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:12,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at tryNextAuth (/home/hayashis/test/ssh2/node_modules/ssh2/lib/client.js:392:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/hayashis/test/ssh2/node_modules/ssh2/lib/client.js:599:5)
    at emitTwo (events.js:126:13)
    at SSH2Stream.emit (events.js:214:7)
    at parsePacket (/home/hayashis/test/ssh2/node_modules/ssh2-streams/lib/ssh.js:3930:10)
    at SSH2Stream._transform (/home/hayashis/test/ssh2/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/home/hayashis/test/ssh2/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)

```

**Comment by mscdex** [comment]
Actually, I was wrong on that, you don't need `agentForward` for this scenario. It should be just enough to set `agent` in your second connection config.

**Comment by soichih** [comment]
Yes, I tried setting "agent" also, but I couldn't figure out what to set it to. For one thing, I can't use the same agent path on my local machine. It needs to be set to the agent socket on the jump host.

I tried the following, but it doesn't work.

```javascript
conn.on('ready', ()=>{
    let auth_sock;
    conn.exec("echo \$SSH_AUTH_SOCK", (err, stream)=>{
        stream.on('data', data=>{
            auth_sock = data.toString();
        });
        stream.on('finish', ()=>{
            conn.exec("nc monitor.brainlife.io 22", (err, nc_stream)=>{
                conn2.connect({
                    sock: nc_stream,
                    username: "hayashis",
                    agent: auth_sock,
                    debug: console.log,
                });
            })
        });
    }); 
})
```

I get the following error message.

```
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ENOENT /tmp/ssh-kxZiMBcgWY/agent.567

    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

```

**Comment by mscdex** [comment]
If you're wanting to use an agent on the jump host, then there is no easy way to do that currently.

As a workaround for now, you could set up a local unix socket that forwards connections over to the jump host, and use that local unix socket as the agent path for your second connection. As far as making a connection to the jump host's ssh-agent, if the jump host is a recent OpenSSH server, you can do this easily with `openssh_forwardOutStreamLocal()`. Otherwise you will need to `exec()` a command like netcat or socat to be able to connect to the ssh-agent unix socket on the jump host.

**Comment by soichih** [comment]
I am really not sure if I *want* to use agent on the jump host or not.. to be honest. I am just trying to do the equivalent of this.

```
hayashis@xps15 $ ssh -J jump.server.com root@real.server.com hostname -f
real.server.com
```

Do you know how ssh cli is accomplishing this? I am guessing it has to be forwarding the agent to jump and using it on jump to ssh to the real.server.com... right? Could you give describe the psudo-code using openssh_forwardOutStreamLocal? I am not sure how to use it.

**Comment by Junkern** [comment]
@soichih I had the same problem and got it to work and decided to make a small library which wraps `ssh2` and e.g. adds jump host support: https://github.com/Stocard/node-ssh-forward

Check it out, not sure if it fits your use case :)

**Comment by mscdex** [comment]
All that `-J` does is implicitly [builds a ProxyCommand](https://github.com/openssh/openssh-portable/blob/9e34e0c59ab04514f9de9934a772283f7f372afe/ssh.c#L1179-L1218) that spins up an (OpenSSH) ssh client on the jump host to connect to the next server (either jump or destination host).

Without knowing the entire configuration settings being used (e.g. being pulled from .ssh/config), it's hard to say how the authentication is happening.

**Comment by YxxY** [comment]
@mscdex  thanks for your explanation.  And I have read many other issues, I still can't find a implement to achieve connection hopping. 
I have tried the example code, but it didn't work.(prompts connect refused)

In my situation, I have to login the jump host via hostname1, username1, password1 and then login the reomte server via hostname2, username2 and password2. 

I wonder is there a appropriate way to execute command on the remote server and get the response only with the user/password  mechanism. 

hope for your reply, many thanks

**Comment by soichih** [comment]
@YxxY You tried this > https://github.com/mscdex/ssh2#connection-hopping and it didn't work? If you are using user/pass, I believe existing ssh2 code can handle that. It doesn't, however, handle ssh agent authentication. ssh2's internal working needs to be updated for this to work, I believe.

**Comment by YxxY** [comment]
yes, the example code didn't work for me, I manually executed the `nc` command in the jump host, it prompts Connection refused, and  `ssh` command  with interactive password works fine. 
I think there should be another general way to get the sock of second connection beyond the `nc`, `socat` command, but I just can't get it……

**Comment by mscdex** [comment]
You can use `forwardOut()` instead of a third-party program like netcat or socat to connect to another server from the current server.

**Comment by YxxY** [comment]
solve this problem, refer to #764

**Comment by mscdex** [comment]
I believe this is solved now? If not, we can reopen it.
