### ISSUE TITLE
Calling channel.end() block stdout for command output > 1Mo

### ISSUE THREAD

**Issue by Congelli501** [mscdex/ssh2#753]
If stdin is closed `stream.end()`, stdout stream will be blocked after 1MB.

To reproduce, just run this code. Only the first 1MB of the command output (2.8MB) will be piped to stdout, and the process will be blocked.
This only happend if the stdin is closed (`stream.end()`)

Tested with latest stable version of ssh2 (0.6.1) with node v11.6.0 under Ubuntu Bionic.

```
var Client = require('ssh2').Client;

var sshConfig = {/* ... */};
var conn = new Client();
conn.on('ready', function() {
	console.log('Client :: ready');
	conn.exec('cat /root/tmp.json', function(err, stream) {
		if (err) throw err;
		stream.on('close', function(code, signal) {
			console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
			conn.end();
		});

		stream.pipe(process.stdout);
		stream.end(); // End stdin
	});
}).connect(sshConfig);
```

Happy new hear :)

**Comment by mscdex** [comment]
Fixed in v0.6.2.
