### ISSUE TITLE
unable to connect to ssh agent

### ISSUE THREAD

**Issue by Srikanta** [mscdex/ssh2#757]
I am trying to connect to a ssh to a switch with following code

var Client = require('ssh2').Client;
 
var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('show system-information', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
	  host: '192.168.1.162',
	  port: 22,
	  username: 'admin',
	  password: '1234',
	  algorithms: 
					{
							  kex: ['diffie-hellman-group1-sha1'],
							  cipher: [
										'3des-cbc',
										'aes256-cbc',
										'aes192-cbc',
										'aes128-cbc'
										
									  ]
					}
		
	});

and it returns an error

sudo node s1.js
Client :: ready
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: invalid command system-information.
    at onDISCONNECT (/home/sri/node_modules/ssh2-streams/lib/ssh.js:2234:15)
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2-streams/lib/ssh.js:204:5)
    at SSH2Stream.emit (events.js:188:13)
    at parsePacket (/home/sri/node_modules/ssh2-streams/lib/ssh.js:3599:10)
    at SSH2Stream._transform (/home/sri/node_modules/ssh2-streams/lib/ssh.js:693:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/home/sri/node_modules/ssh2-streams/lib/ssh.js:252:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
Emitted 'error' event at:
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2/lib/client.js:357:10)
    at SSH2Stream.emit (events.js:193:15)
    at onDISCONNECT (/home/sri/node_modules/ssh2-streams/lib/ssh.js:2236:10)
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2-streams/lib/ssh.js:204:5)
    [... lines matching original stack trace ...]
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)

please help

**Comment by Srikanta** [comment]
Client :: ready
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: invalid command system-information.
    at onDISCONNECT (/home/sri/node_modules/ssh2-streams/lib/ssh.js:2234:15)
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2-streams/lib/ssh.js:204:5)
    at SSH2Stream.emit (events.js:188:13)
    at parsePacket (/home/sri/node_modules/ssh2-streams/lib/ssh.js:3599:10)
    at SSH2Stream._transform (/home/sri/node_modules/ssh2-streams/lib/ssh.js:693:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/home/sri/node_modules/ssh2-streams/lib/ssh.js:252:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
Emitted 'error' event at:
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2/lib/client.js:357:10)
    at SSH2Stream.emit (events.js:193:15)
    at onDISCONNECT (/home/sri/node_modules/ssh2-streams/lib/ssh.js:2236:10)
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2-streams/lib/ssh.js:204:5)
    [... lines matching original stack trace ...]
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)

**Comment by mscdex** [comment]
The error is coming from the server, the command you're trying to execute is not valid.

As far as authentication goes, you're supplying a password and not using an agent (`agent` is not set, and it needs to be set to an appropriate value).

**Comment by Srikanta** [comment]
for the following code

var Client = require('ssh2').Client;
 
var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('show system-information', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
          host: '192.168.1.162',
          port: 22,
          username: 'admin',
          password: '1234',
          debug: console.log,
          algorithms: 
                                        {
                                                          kex: ['diffie-hellman-group1-sha1'],
                                                          cipher: [
                                                                                '3des-cbc',
                                                                                'aes256-cbc',
                                                                                'aes192-cbc',
                                                                                'aes128-cbc'

                                                                          ]
                                        }

        });


the debug output is 

sri@Cranium3:~/node$ sudo node s1.js
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.2'
DEBUG: Client: Trying 192.168.1.162 on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-1.99-OpenSSH_3.9p1'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:636,padLen:11,remainLen:632
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: diffie-hellman-group1-sha1
DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG: KEX algorithm: diffie-hellman-group1-sha1
DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
DEBUG: (remote) Host key formats: ssh-rsa,ssh-dss
DEBUG: Host key format: ssh-rsa
DEBUG: (local) Client->Server ciphers: 3des-cbc,aes256-cbc,aes192-cbc,aes128-cbc
DEBUG: (remote) Client->Server ciphers: aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se,aes128-ctr,aes192-ctr,aes256-ctr
DEBUG: Client->Server Cipher: 3des-cbc
DEBUG: (local) Server->Client ciphers: 3des-cbc,aes256-cbc,aes192-cbc,aes128-cbc
DEBUG: (remote) Server->Client ciphers: aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se,aes128-ctr,aes192-ctr,aes256-ctr
DEBUG: Server->Client Cipher: 3des-cbc
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG: Client->Server HMAC algorithm: hmac-sha1
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG: Server->Client HMAC algorithm: hmac-sha1
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Server->Client compression algorithms: none,zlib
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:444,padLen:10,remainLen:440
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Outgoing: Writing NEWKEYS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:24
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:20,padLen:5,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_SUCCESS
Client :: ready
DEBUG: Outgoing: Writing CHANNEL_OPEN (0, session)
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:24
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_OPEN_CONFIRMATION
DEBUG: Outgoing: Writing CHANNEL_REQUEST (0, exec)
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:60,padLen:11,remainLen:56
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: DISCONNECT (PROTOCOL_ERROR)
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: invalid command system-information.
    at onDISCONNECT (/home/sri/node_modules/ssh2-streams/lib/ssh.js:2234:15)
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2-streams/lib/ssh.js:204:5)
    at SSH2Stream.emit (events.js:188:13)
    at parsePacket (/home/sri/node_modules/ssh2-streams/lib/ssh.js:3599:10)
    at SSH2Stream._transform (/home/sri/node_modules/ssh2-streams/lib/ssh.js:693:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/home/sri/node_modules/ssh2-streams/lib/ssh.js:252:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
Emitted 'error' event at:
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2/lib/client.js:357:10)
    at SSH2Stream.emit (events.js:193:15)
    at onDISCONNECT (/home/sri/node_modules/ssh2-streams/lib/ssh.js:2236:10)
    at SSH2Stream.<anonymous> (/home/sri/node_modules/ssh2-streams/lib/ssh.js:204:5)
    [... lines matching original stack trace ...]
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)

**Comment by Srikanta** [comment]
I have working version of ssh written in php which works perfectly as follows

<?php

//error_reporting(E_ALL);
//ini_set('display_errors', 1);

$user_name = 'admin';
$password = '1234';
function power_on_off($ip, $user_name, $password, $port, $status)
{
        try {

                        $connection = ssh2_connect($ip,22);
                }
        catch (Exception $e) {
                        echo 'Caught exception: ',  $e->getMessage(), "\n";
                }
        try {
                        ssh2_auth_password($connection, $user_name, $password);
                }
        catch (Exception $e) {
                        echo 'Caught exception: ',  $e->getMessage(), "\n";
                }
    $stdio = ssh2_shell($connection,"xterm");
   
    
	
	$command = 'configure'."\n";
	fwrite($stdio,$command);
	usleep(60000);
	
	if($status=='on')
	{
		$command = 'pwr interface '.$port."\n";
		fwrite($stdio,$command);
		usleep(60000);
	}
	if($status=='off')
	{
		$command = 'no pwr interface '.$port."\n";
		fwrite($stdio,$command);
		usleep(60000);
	}
	
        $result = '';
        while($line = fgets($stdio)){
                flush();
                $result =  $result.$line. "<br />";
        }

        fclose($stdio);
        return $result;

}

if(($_POST['port']!='') && ($_POST['ip']!='') && ($_POST['status']!=''))
{
	$ip = $_POST['ip'];
	$port = $_POST['port'];
	$status = $_POST['status'];
	$result = power_on_off($ip, $user_name, $password, $port, $status);
	//$start = microtime(true);
	//print_r($result);
	print_r($_POST);
	header('Content-Type: application/json');
	echo '{"status":"success"}';
	//echo $time_elapsed_secs = microtime(true) - $start;
}



//header('Content-Type: application/json');

?>

please help

**Comment by mscdex** [comment]
Judging by your OpenSSH client and PHP usage, it seems you will have to use `.shell()` and not `.exec()`.

You may also need to not use `.end()` when writing your command, but instead execute some kind of exit command like `'exit\n'` or whatever you would use to exit the shell session normally. So try something like `stream.write('show system-information\nexit\n');`

None of this is not very surprising since many routers/embedded devices have stripped down/limited SSH implementations and can be very brittle from what I've seen over the years. However in this particular case, the abrupt TCP connection reset *could* be a bug in OpenSSH that was fixed at some point later on since that is quite an old OpenSSH release (3.9p1).

**Comment by mscdex** [comment]
Closing for now, if you're still encountering problems after the suggestions I've made, we can reopen this.
