### ISSUE TITLE
stderr seems to be empty

### ISSUE THREAD

**Issue by Coding-Kiwi** [mscdex/ssh2#758]
I have a working connection with an ssh server
in my client code I have
```
stream.on('data', (data) => {
   console.log("STDOUT",data);
}).stderr.on('data', (data) => {
   console.log("STDERR",data);
});
```

when I trigger output to stderr using `echo errortest >&2` or `echo errortest > /dev/stderr`
I get the output "STDOUT errortest", not "STDERR errortest"
any idea why stderr is piped into out instead of err?

**Comment by mscdex** [comment]
Both work for me as expected.

Can you set `debug: console.log` in your config object and post the output (censoring remote IP address if necessary)? That way we can verify what kind of data we're receiving.

**Comment by mscdex** [comment]
Also what does `npm ls --depth=0` show for `ssh2`/`ssh2-streams` ?

**Comment by Coding-Kiwi** [comment]
> Both work for me as expected.
> 
> Can you set `debug: console.log` in your config object and post the output (censoring remote IP address if necessary)? That way we can verify what kind of data we're receiving.

when I type in `echo error> /dev/stderr` and press enter I get the following output:

```
DEBUG: Outgoing: Writing CHANNEL_DATA (0)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:108,padLen:15,remainLen:96
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
```

**Comment by Coding-Kiwi** [comment]
> Also what does `npm ls --depth=0` show for `ssh2`/`ssh2-streams` ?

npm ls --depth=0 ssh2
`-- ssh2@0.8.0

npm ls --depth=0 ssh2-streams
`-- ssh2@0.8.0

**Comment by mscdex** [comment]
> and press enter

Ah, are you using `.shell()`? If so, then everything will come through as stdout. I've never seen an SSH implementation use the 'stderr' data packets for interactive shell sessions, mostly because it's supposed to represent an actual terminal (whether there is a pty allocated or not), which have no notions of separate output streams.

If you use `.exec()` though with one of the two commands you mentioned, the server should send output as 'stderr' data packets.

**Comment by Coding-Kiwi** [comment]
Yes I am using `.shell()` sorry for not mentioning that
I understand what you are saying, I just wanted to find out if it was possible to me to handle sdtout differently (for optional fancy stuff). I opened this issue because the example in the [README](https://github.com/mscdex/ssh2#start-an-interactive-shell-session) has the `stderr.on(` line in it

thank you!
