### ISSUE TITLE
Detect whether server supports password auth

### ISSUE THREAD

**Issue by roblourens** [mscdex/ssh2#760]
Does this library give any way to detect whether password auth is enabled on the server? It seems that I can only pass in a password or not, but I only want to ask the user for their password if I know that the server allows password auth.

If I connect from the command line and there is no key, I get a password prompt. If password auth is disabled, there is no password prompt.

I'm aware of keyboard-interactive auth, but it's disabled on this server, I'm just using

`PasswordAuthentication yes`

**Comment by roblourens** [comment]
Thanks for the response -

> It can send a list of authentication methods that the client can continue to use/try after an authentication failure

If it is sent, would this list tell us whether the server supports password auth?

Otherwise, I don't quite understand what's happening when I do this in a terminal and get

```
$ ssh username@x.x.x.x
username@x.x.x.x's password:
```

but if password auth is not enabled, I don't get that prompt.

**Comment by mscdex** [comment]
> If it is sent, would this list tell us whether the server supports password auth?

Possibly, but like I said, a server can send any kind of list it wants, including an empty list.

> Otherwise, I don't quite understand what's happening when I do this in a terminal

If you enable verbose/debug output for the OpenSSH client you will probably see it trying various authentication methods depending on what information is available (private keys available, options specified in .ssh/config, flags specified on the command line, etc.).

**Comment by roblourens** [comment]
I do see that, and in this case it seems to also be considering the list from the server.

It sounds like the reason that you don't want to use this list or expose it from the library is that it can't be depended on because it may not be accurate, or not sent at all, is that basically correct?

**Comment by mscdex** [comment]
> It sounds like the reason that you don't want to use this list or expose it from the library is that it can't be depended on because it may not be accurate, or not sent at all, is that basically correct?

Generally, yes, that is why I never bothered exposing it before. However as previously mentioned, recent versions of `ssh2` *do* expose this list (along with the partial success indicator) if you pass in an `authHandler` callback, which is used to determine which authentication method to perform next.

**Comment by roblourens** [comment]
Oh, I see now. I misunderstood what you said earlier. Thanks for taking the time to explain it to me!
