### ISSUE TITLE
Expose host's public key

### ISSUE THREAD

**Issue by roblourens** [mscdex/ssh2#762]
Is there any way to get the host's actual public key, not just the hashed fingerprint, when connecting? I ask because I want to write it to the user's `known_hosts` file if they accept the fingerprint, same as what openssh does.

I see the `hostVerifier` option, my understanding is that it gives a hashed fingerprint of the host's key but `known_hosts` contains the actual public key.

**Comment by mscdex** [comment]
Not currently

**Comment by roblourens** [comment]
Would you accept a PR for it?

I'm not sure of the best way to expose it. Maybe adding a new callback option besides hostVerifier. Adding a new argument to hostVerifier in front of its callback would be a breaking change. I would want both the hash and the key at once.

**Comment by shangchengxiang** [comment]
May I ask a question? 
I get the figers from cmd and hostVerifier . But they are different.  
figer from cmd:
ssh-keygen -q -l -f .ssh/known_hosts -F hostname
hostname ECDSA SHA256:YuukV3vH+XwiDNtp62MvZsDr0XeIOmzNKOyPW/kLkQk
figer from  hostVerifier :
693994cdf1f576fea93ea184d668fa1bdb20d650dc78a44206bd4a0cf8fa7298
So if change the format to compare them?

**Comment by mscdex** [comment]
This should be resolved now with the `ssh2` rewrite. For more details see [here](https://github.com/mscdex/ssh2/issues/935).
