### ISSUE TITLE
parseKey can return array

### ISSUE THREAD

**Issue by thompsa** [mscdex/ssh2#766]
As of v0.3.0 of ssh2_streams the utils.parseKey function may return an array of key objects, rather than the object itself.

> ./node_modules/ssh2/lib/server.js:49
>     if (privateKey.getPrivatePEM() === null)
>                    ^
> 
> TypeError: privateKey.getPrivatePEM is not a function
>     at new Server (./node_modules/ssh2/lib/server.js:49:20)
>     at Object.<anonymous> (./index.js:11:1)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Function.Module.runMain (module.js:694:10)
>     at startup (bootstrap_node.js:204:16)
>     at bootstrap_node.js:625:3

ssh2 needs to catch up with the API change.

**Comment by mbodge** [comment]
Any solutions to fix this?

**Comment by Tarjei400** [comment]
I have same issue, I think I will fork repo and just add to server.js 
`    if (privateKey[0].getPrivatePEM() === null)
      throw new Error('privateKey value contains an invalid private key');

    if (hostKeys[privateKey[0].type])
      continue;
    hostKeys[privateKey[0].type] = privateKey[0];`

Around line 50 I have no idea why this is returned in array though

**Comment by Tarjei400** [comment]
I think it returns array always when hostKeys tries to load private key: 
       ` { key: fs.readFileSync('./keys/key_ssh_rsa'), passphrase: ''},`

I decided for now to use almost empty ssh config:

```
    const sshConfig = {
      hostKeys: [
       // { key: fs.readFileSync('./keys/key_ssh_rsa'), passphrase: ''},
      ],
    };
```

**Comment by Tarjei400** [comment]
I dug through documentation and added some code to prevent crash, hopefully its going to be reviewed soon, if no here is a forked repo with a fix :
https://github.com/Tarjei400/ssh2

**Comment by RayeesMir** [comment]
@mscdex  I am still getting this error.  I installed package using npm. I think you haven't published new version on npm. can you please check?
