### ISSUE TITLE
executing command in an opened shell (ssh -t command or pseudo-tty allocation)

### ISSUE THREAD

**Issue by Utopiah** [mscdex/ssh2#769]
I'm trying to reproduce `ssh shell -t "screen -raAD"` but can't seem to find the right way to do so despite searching in the documentation (including Pseudo-TTY settings) and issues.

I tried `client.connect(); conn.shell();` then `client.exec()` which perfectly for non interactive commands like uptime.

When I try `screen -raAD` though it's failing with `Must be connected to a terminal.` which makes sense. I don't find in the documentation a way to interact back to an opened shell as the call back function provides no interface and `conn.shell()` returns only a boolean. I briefly checked how `Client.prototype.shell` was defined but noticed nothing related.

**Comment by mscdex** [comment]
See [this example](https://github.com/mscdex/ssh2/issues/718#issuecomment-406823236) on how to do a proper interactive session. If you don't need to start an actual shell session, you can change the `.shell()` to a `.exec('screen -raAD', { pty: { /* term, rows, cols go here */ } }, /* same callback here */)`

**Comment by Utopiah** [comment]
Thanks for the clarification, checking.

I'm trying to have `screen -raAD` executed once I'm connected via WebSSH2, checking in https://github.com/billchurch/WebSSH2/blob/master/app/server/socket.js#L51

**Comment by Utopiah** [comment]
Just added `stream.write("screen -raAD\n")` which worked. Thanks!
