### ISSUE TITLE
Is there a way to make channel.on('data') callback return buffer?

### ISSUE THREAD

**Issue by zxdong262** [mscdex/ssh2#771]
I am trying to support encoding like GBK, but channel's on('data') callback return string, not buffer, I can not decode it use custom decode method.

```js
  conn.shell(
    shellOpts,
    (err, channel) => {
      if (err) {
        return reject(err)
      }
      this.channel = channel
      this.channel.on('data', chunk => {
        assert(typeof chunk === 'string')
      })
      resolve(true)
    }
  )
})
```

**Comment by mscdex** [comment]
`ssh2` does not automatically convert the incoming data to strings, so I'm not sure why you're seeing that.

**Comment by zxdong262** [comment]
Oh, my mistake, it is buffer
