### ISSUE TITLE
Error loading buffer-helpers with Electron

### ISSUE THREAD

**Issue by caique0202** [mscdex/ssh2#774]
Hi

I'm writing one app that uses Electron and ssh2 and everything is working just fine in development.

When I build the electron for production I get the following error: Uncaught Error: Cannot find module APP_NAME/Contents/Resources/app.asar/buffer-helpers

I've tried to install the buffer-helpers but the build seems to ignore the module installed.

Any ideas how to fix this?

Thanks

**Comment by mscdex** [comment]
`buffer-helpers` is not an external module, [it's a file within this project](https://github.com/mscdex/ssh2/blob/8304dc7cdc43c3e7984bc6732358db7d83977312/lib/buffer-helpers.js). I don't know why Electron has issues with loading it, you'd be better off asking in one of their support channels.

**Comment by caique0202** [comment]
> `buffer-helpers` is not an external module, [it's a file within this project](https://github.com/mscdex/ssh2/blob/8304dc7cdc43c3e7984bc6732358db7d83977312/lib/buffer-helpers.js). I don't know why Electron has issues with loading it, you'd be better off asking in one of their support channels.

I've found the fix. Updated the ssh2-streams/lib/keyParser.js

From:
var bufferHelpers = require(__dirname + '/buffer-helpers');
var constants = require(__dirname + '/constants');

To:
var bufferHelpers = require('./buffer-helpers');
var constants = require('./constants');

Thanks
