### ISSUE TITLE
Pause execution (SIGTSTP signal)

### ISSUE THREAD

**Issue by vdiez** [mscdex/ssh2#776]
Hello, 

I'm trying to implement a pause/resume feature, which I can do with subprocess.kill(signal) with child_process on local executions. I see on the list of available signals ('ABRT', 'ALRM', 'FPE', 'HUP', 'ILL', 'INT', 'KILL', 'PIPE', 'QUIT', 'SEGV', 'TERM', 'USR1', and 'USR2') that none of them is to pause the process. Is there any way to achieve this with ssh2?

Thanks

**Comment by mscdex** [comment]
The list comes from the RFC. It's entirely possible that the intention was to include all POSIX signals, but those were explicitly listed in the RFC. However not all clients/servers may support signals as sent through the ssh2 protocol, so you shouldn't rely on it. If you need to send signals reliably, you will need to find some other way, such as calling `.exec('kill -SIGNALNAME someprocesspid')` on *nix systems.

**Comment by vdiez** [comment]
Thanks for the fast answer @mscdex 

Is there any way to get the pid reliably from current session? from the exec stream or so? I don't consider grepping and piping the pid to be 100% reliable depending on how many processes are running on the server. I would rather avoid it unless it's the only option

**Comment by mscdex** [comment]
You would have to obtain that through some method, the ssh2 protocol does not provide that information. For example, if it's a background command you're starting from `.exec()`, you could append `'; echo $!'` and parse the pid from the resulting output. Otherwise you might read a pid file or something else.

**Comment by vdiez** [comment]
ok, I will sort it out then. thanks!

**Comment by vdiez** [comment]
for anyone who may end up in the same issue, this seems the best way to get the PID of a process if you cannot launch it in the background (in my case I need to parse output):

```
sh -c 'echo $$; exec myCommand'
```

[source](https://serverfault.com/a/903631)
