### ISSUE TITLE
Using with Serveo

### ISSUE THREAD

**Issue by jaruba** [mscdex/ssh2#777]
I'm trying to figure out how to use ssh2 with [Serveo](http://serveo.net/)

Basic usage would presume:
```
ssh -o ServerAliveInterval=60 -R incubo:80:localhost:8888 serveo.net
```

It would also need to reconnect on any failure.

Any help would be appreciated.

**Comment by mscdex** [comment]
The keepalive options are documented in the readme. See also [this SO question](https://stackoverflow.com/questions/55547703/nodejs-reverse-ssh-tunnel-unable-to-bind-to-serveo-net80).

**Comment by jaruba** [comment]
Thanks, works great.
