### ISSUE TITLE
Are sessionless servers possible?

### ISSUE THREAD

**Issue by Wasabichicken** [mscdex/ssh2#778]
Hi all,

I'm implementing a server that needs to be capable of handling client requests to set up a reverse tunnel/port forwarding (the `-R` option for the OpenSSH client), but not request a shell (the `-N` option) and I'm wondering how to go about it.

When I leave out `-N`, the ssh2 server receives a 'session' event, I can call `accept()` to receive a session, I can acquire a channel to the client, choose whether to launch a shell, and so forth. When the client specifies `-N`, the only event I am getting is the 'request'-event, with name being either "tcpip-forward" or "streamlocal-forward@openssh.com" as appropriate. Calling `accept()` here yields neither a channel nor a session, leaving me a bit lost as how to acquire a handle to the actual tunnel.

All advice welcome. Have I missed to implement some event hook, or does ssh2 not support this?

**Comment by mscdex** [comment]
`-R` means the client is requesting that the *server* forward connections to the client (whereas `-L` is the client requesting that the *client* forward connections through the server). So `accept()` here tells the client that their request succeeded. After that (as long as they have not canceled their forwarding via a `cancel-tcpip-forward` request) you can just use the [`forwardOut()` method on the client connection object](https://github.com/mscdex/ssh2/tree/3b3a7a7ccb0736b8b89012d85f19ad7d1c1e1329#connection-methods) to send it an incoming connection.

**Comment by Wasabichicken** [comment]
Bingo! `forwardOut()` works splendidly to initiate a connection from server, through the tunnel, to client!

Thank you mscdex!
