### ISSUE TITLE
Dynamic dependency won't work with Parcel.

### ISSUE THREAD

**Issue by ryasmi** [mscdex/ssh2#780]
Any reason you used a dynamic import in the code below @mscdex instead of a static import? It prevents your package and any package that uses your package from working with Parcel.

```js
var EXEPATH = path.resolve(__dirname, '..', 'util/pagent.exe');
```

https://github.com/mscdex/ssh2/blob/master/lib/agent.js#L350

**Comment by ryansmith94** [comment]
Just realised this isn't a require which makes this even more complicated.
