### ISSUE TITLE
Fastget Buffer limit?

### ISSUE THREAD

**Issue by apopper000** [mscdex/ssh2#782]
if (state.read)
                        //Set dataBuff as a buffer with the data from the file being called
                        var dataBuff = fs.readFileSync('./test.txt', 'utf8');
                        //console.log(dataBuff);
                        sftpStream.data(reqid, dataBuff);
Being familiar with C and not java script, I was writing my files to buffer(server side), but ran into an issue. My server reads the files using the code above. (Just a Big buffer) And when I use fast get to try to get my file I get the Issue below I was wondering if there was another preferred way to have my server read files (larger then 2mb)?

I know that this is more an issue with fs and feel free to close this issue I know i'm out of place on this one.

s.js:702
    return binding.writeBuffer(fd, buffer, offset, length, position, req);
RangeError: length out of bounds
    at Object.fs.write (fs.js:702:20)   
at onread (C:\ssh2-streams\lib\sftp.js:1120:29)
    at cb (C:\s\ssh2-streams\lib\sftp.js:899:13)
    at SFTPStream._transform (C:\ssh2-streams\lib\sftp.js:444:33)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (C:\ssh2-streams\lib\sftp.js:183:17)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)

**Comment by mscdex** [comment]
FWIW you can avoid the conversion to string by leaving out the `, 'utf8'` part of your `fs.readFileSync()`.

Out of curiosity, what is returned by `Buffer.byteLength(dataBuff, 'utf8')` ?

**Comment by apopper000** [comment]
"6319547" is printed out 3 times

**Comment by mscdex** [comment]
Do you have a minimal example of both sides that I can use to reproduce this?

**Comment by apopper000** [comment]
Minimal? The issue occurs on my client side, but my server side is currently in a state of restructuring
Client side:
var Client = require('ssh2').Client;
var fs = require('fs');
var conn = new Client();
conn.on('ready', function () {
    console.log('Client :: ready');
    conn.sftp(function (err, sftp) {
        if (err) throw err;
        sftp.fastGet('test.txt', './test.txt', {}, (err) => {
        });
    });
}).connect({
    host: '',
    port: ,
    username: '',
    password: '',
    privateKey: require('fs').readFileSync('./server.key')
});

**Comment by apopper000** [comment]
There really isnt a minimal serverside, but here is what I have for file read (put into the ssh2 example), I could try only writing portions of the buffer at a time, but I think this will just make smaller issues

session.on('READ', function (reqid, handle, offset, length) {
                    if (handle.length !== 4 || !openFiles[handle.readUInt32BE(0, true)])
                        return sftpStream.status(reqid, STATUS_CODE.FAILURE);
                    var state = openFiles[handle.readUInt32BE(0, true)];
                    if (state.read)
                        //Set dataBuff as a buffer with the data from the file being called
                        var dataBuff = fs.readFileSync('./test.txt');
                        console.log(Buffer.byteLength(dataBuff, 'utf8'));
                        sftpStream.data(reqid, dataBuff);

**Comment by mscdex** [comment]
I think I see what's going on here. The server is not respecting the `length` from the client's read request and the client is not expecting to receive data in response that is larger than that `length`.

It looks like OpenSSH's sftp client will just abort the moment it sees more data than it asked for. I guess we should do something similar, except just cleanup and execute the callback with an error.

**Comment by mscdex** [comment]
FWIW on the server, you can do the reads more appropriately by using `fs.open()`/`fs.read()`/`fs.close()` because the client can ask for different offsets and lengths into the requested file.

**Comment by mscdex** [comment]
The extra data check is now in mscdex/ssh2-streams@8e1f60da689d59fcb66cfd165f2a2d27672884b4 and the (opposite scenario) less data check is now in mscdex/ssh2-streams@1b8424db25e9ac1350774082ea76f68eb5254d81.

**Comment by apopper000** [comment]
I made a few changes now there are erratic offset values being passed into my 'read' call

**Comment by apopper000** [comment]
Also I get depreciation warnings that crash my server if I use fs.read(), so I have been trying to you synchronous functions only.

**Comment by apopper000** [comment]
I solved all of my issues except 1. When I download a file it downloads the buffer a couple hundred times. If I were to try to transfer a 1kb file its download is 2,000 kb. how do I prevent this

**Comment by apopper000** [comment]
I found my issue. It was server side: i was missing section below, can you explain how to set this up for large files?      
              sftpStream.attrs(reqid, {
                        //mode: WritableStream,
                        //size: 255,
                        atime: Date.now(),
                        mtime: Date.now()
                    });

**Comment by apopper000** [comment]
I solved all my Issues thank you so much for your support.
