### ISSUE TITLE
ssh2 programmatic interactive shell to send multiple commands

### ISSUE THREAD

**Issue by informvisu** [mscdex/ssh2#783]
In the shell, I am having multiple commands to send based on previous command responses like 'press any key to continue...' etc. I am trying to parse the response in the while loop but haven't received any response in this case. Please help

Connecting to a cisco switch through a jumppoint.

		dConn.on('ready', function() {
			logger.info(logPrefix+'Device logged in');
			dConn.shell(function(err, stream) {
				if (err) {
					jConn.end();
					logger.error('*** SSH EXEC ERROR: ' + err.message + ' ***');
					return res.send('\r\n*** SSH EXEC ERROR: ' + err.message + ' ***\r\n');
				}
				
				//Send commands to device and logout finally
				var resp = '', buffer = ''
				stream.write(cliCommand+'\r\n')
				var count = 0
				/*while(true) {
					if(++count % 10000000 == 0) logger.info('while: '+count+': '+buffer)
					
					if(buffer.includes('>')) break;
					if(buffer.includes('--More--')) {
						buffer = ''
						stream.write('\r\n');
					}
				}
				buffer = ''*/
				
				//Send next command
				//Process the response
				
				stream.write('exit\r\n')
				
				stream.on('end', function() {
					jConn.end(); // close parent (and this) connection
				}).on('close', function() {
					logger.info(logPrefix+'stream.close');
					res.send('<pre>'+resp+'</pre>');
				}).on('data', function(data) {
					logger.info(logPrefix+'stream.data: '+data);
					buffer += data.toString('binary')
					resp += data.toString('binary')					
				}).stderr.on('data', function(data) {
					logger.info(logPrefix+'stream.stderr.data: ' + data);
					buffer += data.toString('binary')
					resp += data.toString('binary')					
				});
			});//End shell
		})

2019-04-23T22:17:53.761Z info [network.js     ]: 142.174.4.1 - GET /network/device/name/cisco_switch_1/command/show%20version: Device logged in
2019-04-23T22:17:54.101Z info [network.js     ]: while: 10000000: 
2019-04-23T22:17:54.317Z info [network.js     ]: while: 20000000: 
2019-04-23T22:17:54.542Z info [network.js     ]: while: 30000000: 
2019-04-23T22:17:54.754Z info [network.js     ]: while: 40000000: 
2019-04-23T22:17:54.963Z info [network.js     ]: while: 50000000:

**Comment by mscdex** [comment]
A loop like that will block the event loop, which means node can't do anything else, including receive data over a socket. Get rid of the loop and move your `buffer` checking inside your stdout `'data'` event handler.

**Comment by informvisu** [comment]
This helps beginners. Thank you very much @mscdex 

var events = require('events');
var sender = new events.EventEmitter();
var receiver = new events.EventEmitter();

		var commands = ['term len 0', 'show version', 'show vlan', 'exit']
		var cmdCount = 0
		sender.on('next', function() {
			if(++cmdCount == 1)
				sender.emit('clear')
			if(commands.length > 0)
				sender.emit('command', commands.splice(0, 1))			
		})


				var resp = '', buffer = ''
				//Send commands to device and logout finally
				sender.on('clear', function() {
					resp = ''
				})
				sender.on('command', function(command) {
					logger.info('sender.command: '+command);
					stream.write(command+'\n');
				})
				receiver.on('data', function(data) {
					//logger.info('receiver.data: '+data);
					buffer += data
					if(buffer.includes('>')) {
						logger.info('buffer: '+buffer)
						resp += buffer
						buffer = ''
						sender.emit('next')						
					} else if(data.includes('--More--')) {
						stream.write('\n');
					}
				})
