### ISSUE TITLE
Support for ed25519 key format

### ISSUE THREAD

**Issue by takase1121** [mscdex/ssh2#785]
I was using `ssh2-promise` and it uses this module under the hood. Can support for ed25519 key format be added? I am using those type of keys on my production server. It'll be nice if it is supported

**Comment by mscdex** [comment]
You need `ssh2` v0.8.3+ and (currently) node v12.0.0+.

**Comment by takase1121** [comment]
I'm still relying on v10 LTS for my projects. Is there no other way?

**Comment by mscdex** [comment]
Only if node v10 gets both OpenSSL 1.1.1 _and_ the necessary `crypto` changes.

**Comment by igor-lemon** [comment]
I have Node v12.0.0 and ssh2 v0.8.4 and I still have an error:
```
handling ssh connection error.Error: Cannot parse privateKey: Unsupported OpenSSH private key type: ssh-ed25519
```

**Comment by mscdex** [comment]
Closing this for now, if node v10.x ever gets all of the proper functionality backported it will automatically get used by `ssh2`.
