### ISSUE TITLE
Setting dstHost to internal host fails to resolve and throws ENOTFOUND

### ISSUE THREAD

**Issue by steadweb** [mscdex/ssh2#786]
Using the following config, if I set the `dstHost` to something that the SSH server knows about, but locally, doesn't resolve, `node` throws a `ENOTFOUND` error.

Code:

```javascript
const sshClient = require('ssh2').Client;
const sshConnection = new sshClient();
const sshConfig = {}; // omitted 
const forwardConfig = {
  srcHost: host,
  srcPort: port,
  dstHost: `foo.internal`,
  dstPort: port,
};

sshConnection.on('ready', () => {
  sshConnection.forwardOut(
    forwardConfig.srcHost,
    forwardConfig.srcPort,
    forwardConfig.dstHost,
    forwardConfig.dstPort,
    (err, sshStream) => {
      if (err) {
        throw new Error(err);
      }

      // ...
    }
  );
}).connect(sshConfig);
```

Error thrown:

```
Error: getaddrinfo ENOTFOUND foo.internal at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

If I resolve this within my local `/etc/hosts` file, so that it resolves, it'll work. Is there a way to stop `ssh2` (or indeed, `node`) trying to resolve `foo.internal`?

**Comment by steadweb** [comment]
In fact, this isn't an `ssh2` issue, it's a `net` issue, apologies. Closing.

**Comment by mscdex** [comment]
FWIW the client doesn't try to resolve `.dstHost`, that's the server's job. The source and destination hosts are passed as-is to the server.
