### ISSUE TITLE
Scaling SSH2 on a cloud server

### ISSUE THREAD

**Issue by mbodge** [mscdex/ssh2#787]
Thanks so much for this library, I couldn't have done this project without it!

I have a question about scaling the sessions in a cloud environment. I could potentially have thousands of users connecting to my SSH server at any given time. For this reason I want to scale the service horizontally with many server instances. I've done this with Node.js and Express by saving the client session into Redis so it doesn't matter what server the user hits. So currently if a user opens a session to Computer A and the next request hits Computer B, computer B will have no knowledge of what is going on in that session.

So I guess I'm asking, how do I share a connected SSH user session/connection over a few different machines?  Is it possible?

**Comment by mscdex** [comment]
I'm not entirely sure what situation/scenario you have there, but a more general (architecture/design) question like this might fare better elsewhere like stackoverflow for example.

**Comment by mbodge** [comment]
Thanks for your quick response! I'll post something on StackOverflow. 

I guess my main question is: is there a way to serialize the session to keep some sort of "session affinity" going or is that not possible with the library?

**Comment by mscdex** [comment]
SSH is a very different beast compared to HTTP. There are no session cookies you can have the client set that get sent on the next connection or anything. That severely limits your ability to link sessions across different servers.

Probably the best you could do is use IP, client identification string, username, password/key, etc. together to try and form a unique enough identifier to use when storing whatever session-specific information in Redis.
