### ISSUE TITLE
How to catch a timeout error while use client.connect ? 

### ISSUE THREAD

**Issue by Kisarigi** [mscdex/ssh2#788]
When my server have no response, I want to return an error message in router.
here is my code.
```
router.get(/shutdowncon/,function(req,res,next){
    let conn2 = new Client();
        conn2.connect({
            host: 'xxxxxxxxxxxx',
            port: 9222,
            readyTimeout: 5000,
            username: 'xxxxx',
            password: 'xxxxxx',
            algorithms:
                {
                    kex: ['diffie-hellman-group1-sha1'],
                    cipher: ['3des-cbc'],
                }
        })
        conn2.on('ready', function () {
            res.json({
                status: "1",
                msg: 'suc',
            })

        });
        
});
```

When my server is closed, this code shows 

> events.js:174
>      throw er; // Unhandled 'error' event
> Error:` Timed out while waiting for handshake

then it shut down.
I wonder how to catch a timeout error while use client.connect ?

**Comment by mscdex** [comment]
See the [node documentation](https://nodejs.org/docs/latest/api/events.html#events_error_events) for more information on this.
