### ISSUE TITLE
Failing auth due to authenticity

### ISSUE THREAD

**Issue by mattapperson** [mscdex/ssh2#79]
When connecting to a remote server for the first time. If the authenticity of host can't be established, login just fails when connecting via a password. I have to login first using the normal ssh commands from the cli, and add the remote server to the list of known hosts. After that all works correctly.  

Is there a way to avoid this annoying step?

**Comment by shangchengxiang** [comment]
> 确定要使用此模块吗？该模块根本不与known_hosts文件或其他任何东西交互。

Can I get the hashedkey which in hostVerifier from others.  I don't konw how to get it from cmd to compare them to return ture or false.
