### ISSUE TITLE
How to connect through bastion host ?

### ISSUE THREAD

**Issue by anandsiddharth** [mscdex/ssh2#795]
I want to connect through bastion host. I am trying to use following way :

```js
let conn = new ssh2.Client();
let conn2 = new ssh2.Client();
conn.connect(config);
conn.on("ready", () => {
        console.log("first ready");
        conn2.connect({
            sock: conn,
            username: 'ubuntu',
        });
});
```
the error is -> ` dest.write is not a function`

**Comment by anandsiddharth** [comment]
figured out... required to execute and get stream https://github.com/mscdex/ssh2#connection-hopping

**Comment by mscdex** [comment]
Alternatively you can use `conn1.forwardOut()` instead of `conn1.exec()`.

**Comment by anandsiddharth** [comment]
@mscdex I am not able to do agent forwarding.. 
I have enabled agent forwarding it asks for agent file.. 

what would be alternative of command line : ssh -A user@hostname in this lib

thanks in advance

**Comment by mscdex** [comment]
Agent forwarding is done by setting both `agent` to the appropriate ssh-agent path and `agentForward: true` on your destination connection (`conn2.connect({ ... })`).

**Comment by anandsiddharth** [comment]
I have added this in my config file

            agent: process.env.SSH_AUTH_SOCK,
            agentForward: true


error: All configured authentication methods failed

Am I doing something wrong ?

**Comment by anandsiddharth** [comment]
I am trying to establish a connection via bastion host with  agent forwarding
```
      let conn = new ssh2.Client();
      let config = session.buildConfig(serverConfig);
      conn.connect(config); // config has agent set to true and path to ssh aiuth socket
      conn.on("ready", () => {
        let conn2 = new ssh2.Client();
        conn.connect({
              sock: stream,
              username: "ubuntu",
        });
      });
```

**Comment by mscdex** [comment]
This is what you tried?:

```js
conn2.connect({
  sock: stream,
  username: "ubuntu",
  agent: process.env.SSH_AUTH_SOCK,
  agentForward: true
});
```

**Comment by mscdex** [comment]
Actually scratch that, you shouldn't need `agentForward` at all, just `agent`, so:

```js
conn2.connect({
  sock: stream,
  username: "ubuntu",
  agent: process.env.SSH_AUTH_SOCK
});
```

**Comment by anandsiddharth** [comment]
Got this working now! 
I have 3 more questions please help me out with these.
1. When using agent I need to manually add the key to ssh-add from the command line.. is their a way I can do that from js programmatically ?
2.  Will process.env.SSH_AUTH_SOCK work on windows? 
3. What if ssh is not installed on system and ssh-agent is not running?

**Comment by mscdex** [comment]
1. Possibly, but it's outside the scope of this project. If you are always just using a single key and know the path to it, then you can just use `privateKey` instead of `agent`.

2. With WSL or cygwin possibly, otherwise you can use the special string of `'pageant'` on Windows to use pageant as the agent

3. It doesn't matter if the OpenSSH client itself is installed, all you need is `ssh-agent`. If it's not running and you supply an `agent`, then obviously that authentication method can't be tried and will be skipped.

**Comment by anandsiddharth** [comment]
Thank you @mscdex !
