### ISSUE TITLE
What's the point of SFTPWrapper?

### ISSUE THREAD

**Issue by jeffrson** [mscdex/ssh2#797]
As I understand it, SFTPWrapper should keep some compatibility - it passes all methods but `readData` and `writeData`, which will be "replaced" by `read` and `write`, respectively.

However, ssh2-streams documents `readData` and `writeData`, so it's not quite understandable, why there is such difference. And in the end, why the SFTP subsystem of ssh2.Client has `read`, whereas it should have `readData` (or `write` and `writeData`...).

Is there any way to get rid of SFTPWrapper?

There is a package called ssh2-promise, which dynamically "promisifies" most, if not all, methods from ssh2. But it uses `readData` and `writeData` (according to the documentation, I suppose), which of course fails. Is it wrong? Should it use `read` and `write`?

**Comment by mscdex** [comment]
It exists to more easily mirror the node `fs` API. As the comment in the `SFTPWrapper` source file explains, we can't use `read`/`write` on the `SFTPStream` because it's a stream and streams already have those methods defined. The `SFTPWrapper` works around this by wrapping the stream, since access to `stream.read()` and `stream.write()` is not needed by userland.

**Comment by jeffrson** [comment]
Okay, thanks!

So it should be considered a bug, when ssh2-promise uses `readData`/`writeData`, right?

**Comment by mscdex** [comment]
That's completely up to that project. FWIW it seems they have custom methods as well (e.g. `writeFileData()`, `changeOwner()`, etc.), so perhaps they have different goals?

**Comment by jeffrson** [comment]
`writeFileData` a.s.o. should be convenience methods that collect a couple of others (like implicit open, close, stat, ...).

The problem is, that they use ssh2.sftp() internally. So they cannot use `readData` because sftp() doesn't have it.

**Comment by mscdex** [comment]
If they're using `SFTPWrapper`, then yes that would be a bug that would need to be brought to their attention.
