### ISSUE TITLE
How to set highWaterMark for ssh.sftp()?

### ISSUE THREAD

**Issue by jeffrson** [mscdex/ssh2#800]
Hi,

I have a server based on `ssh2`. And I have a client written with `ssh2-promise` on top of `ssh2`. Although the `ssh2-promise` part should not matter for this issue...

How can I get ssh.sftp() (which is an SFTPWrapper) to init with a certain value for `highWaterMark`? Adding this option to connection options does not help.

BTW, when, under which circumstances, does a stream decide, it needs 'continue'? Is is related to `highWaterMark`?

Thank you for your support!

**Comment by mscdex** [comment]
There is no way to control the `highWaterMark` for `SFTPStream` from `ssh2` currently.

`'continue'` should be emitted whenever calling an API method that writes data to the underlying `SSH2Stream` and the stream indicates we should stop writing for now.
