### ISSUE TITLE
SSH2 Interactive Session

### ISSUE THREAD

**Issue by mohitgith** [mscdex/ssh2#801]
I am trying to execute a shell script which asks for authentication and opens a kind of a new terminal inside the original. I have automated it into selenium using nodejs. I have used the ssh2 modules for that and what it does is, it is loggin in after running the command but not being allowed to enter further new inputs after the new terminal opens up. How to automate it using ssh2 or anything else?

**Comment by mscdex** [comment]
Can you show the relevant code that uses `ssh2` that you already have?

**Comment by mohitgith** [comment]
I have used the same code as mentioned in https://www.npmjs.com/package/ssh2. Below is used code:
var Client = require('ssh2').Client;
 
var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.shell(function(err, stream) {
    if (err) throw err;
    stream.on('close', function() {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function(data) {
      console.log('OUTPUT: ' + data);
    });
    stream.end('ls -l\nexit\n');
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  privateKey: require('fs').readFileSync('/here/is/my/key')
});

**Comment by mscdex** [comment]
If you're actually using `stream.end()` like that, then that's probably the issue. That will end the input.

**Comment by mohitgith** [comment]
I have tried stream.write() to continue the input, but still facing the same issue. After the new terminal gets opened, it is not taking the further inputs provided.

**Comment by mscdex** [comment]
No idea then unless it's something I can easily reproduce on my end.

**Comment by mohitgith** [comment]
I have tried doing something like this just to check if the code is detecting the new batch. Have a look at the code below:
 return new Promise((resolve, reject) => {
            let conn = new Client();
            fs.writeFileSync(filePath, "");
            conn.on('ready', function () {
                logger.info('Client :: ready');
                conn.shell(function (err, stream) {
                    if (err) throw err;
                    stream.on('close', function () {
                        console.log("In Close");
                       // logger.info('Command execution completed ');
                        //conn.end();
                        //return resolve();
                    }).on('data', function (data) {
                        logger.debug(data);
                        fs.appendFileSync(filePath, data);
                        console.log("In data");
                    stream.write(command);                  
                    });
                    stream.end('exit\n');
                });
            }).connect({
                host: hostname,
                port: 22,
                username: username,
                password: password
            });
        })

So, my command is getting executed on the new batch, but executing every single time the data is coming, which is the correct behavior. So, is there any way that helps me to execute the command only once the data stops coming? Please bear with me as I am new to this technology. Thanks.

**Comment by mscdex** [comment]
That's a problem inherent to programmatic use of interactive shells. You more or less have to search for the shell prompt in your output to know when the command has finished, which is not only not easy, but is not foolproof. This is why `.exec()` exists, as it is designed more for this kind of programmatic use.
