### ISSUE TITLE
connect hang at IN_INIT

### ISSUE THREAD

**Issue by forKnowYou** [mscdex/ssh2#802]
local: win10X64
remote: centos7.6

connect hang at IN_INIT

DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.4'
DEBUG: Client: Trying 10.10.xx.246 on port 5950 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
nothing follow..

**Comment by mscdex** [comment]
You should get an `'error'` event after 20 seconds (the default `readyTimeout`). Anyway, it seems the other side is not responding and is not a valid SSH server.

**Comment by forKnowYou** [comment]
no.. I dont get an error event. it just hang there.
and I can connect my server via mobaxterm.
can u give me more suggest?

**Comment by forKnowYou** [comment]
there is main code:

let conn = new ssh2.Client()

conn.on("error", (err) => {
    throw err
})

conn.on("ready", () => {
    console.log(`ssh client ready`, "green")
    conn.sftp((err, sftp) => {
        if(err) throw err
        
    })
}).connect({
    host: "xxx.xxx.xxx.xxx",
    port: 5950,
    username: "xxxx",
    password: "xxxx",
    readyTimeout: 8000,
    debug: console.log
})

**Comment by mscdex** [comment]
What version of node and what version of `ssh2` are you using? If you're setting `readyTimeout: 8000` then it should happen after 8 seconds. Out of curiosity, what if you add a `setTimeout(() => { console.log('timer') }, 8000)` after the `.connect()`? Does that timer fire after 8 seconds?

**Comment by forKnowYou** [comment]
node version is v10.16.0
ssh2 version is v0.8.5
timer fired after 8s

**Comment by forKnowYou** [comment]
use other way to do my job.
