### ISSUE TITLE
Using simple username and password with custom authentication

### ISSUE THREAD

**Issue by arthurvaverko** [mscdex/ssh2#803]
I'm trying to get a simple ssh server example with some custom authentication ..
i want the user to provide a username and password 
i will verify them using my own logic (external service)
but i can get the password from a keyboard-interactive method .. and the ctx.password is empty .. 
what am i missing here ? 

What i finally want is to allow sftp to list files and directories,
and also to upload a file to a sepcifc directory..

```javascript
var fs = require('fs');
var ssh2 = require('ssh2');

var server = new ssh2.Server({
    banner: "Welcome to my server...",
    //debug: function(msg){console.log("debug:",msg);},
    hostKeys: [fs.readFileSync('C:\\Keys\\OTT-STG.pem')]
}, function (client) {
    console.log('Client connected!');

    client.on('authentication', function (ctx) {
        console.log("auth started", ctx.username, ctx.method);

        switch (ctx.method) {
            case 'keyboard-interactive':
                console.log("keyboard interactive:");
                ctx.prompt({ prompt:'Password: ', echo: false}, function(err,resp){
                    console.log("got password response from keyboard: ", resp);
                    console.log("error", err);
                    return true;
                });
                break;
            case 'password':
                // This always empty :(
                //var password = Buffer.from(ctx.password);
                console.log("password entered:");
                break;
            default:
                return ctx.reject();
        }

        ctx.accept();
    });

    client.on('ready', function () {
        console.log('Client authenticated!');
        client.on('session', function (accept, reject) {
            var session = accept();
            console.log('Session started!');

        })

    });

    client.on('end', function () {
        console.log('Client disconnected');
    });
});


server.listen(22, '127.0.0.1', function () {
    console.log('Listening on port ' + this.address().port);
});
```

**Comment by mscdex** [comment]
What's the actual problem here? You're attempting the `'password'` authentication method on the client but the server is not seeing the password? Are you sure the client is using that method and not something else (e.g. `'keyboard-interactive'`)? If so, can you show how you are authenticating with the client?

**Comment by arthurvaverko** [comment]
Thanks! .. I never new the details of SSH protocol .. 
understood now that there are multiple methods that the client tries .. and i can reject with my prefered method like this
`ctx.reject(["password"])`
this made the client to attempt a password authentication .. 
thans @mscdex
