### ISSUE TITLE
Escape Sequence removal or reformat

### ISSUE THREAD

**Issue by YeeP79** [mscdex/ssh2#810]
While using 'pty' mode, I see all of the escape sequences.
Example:
`\u001b[1mcentos-release.x86_64\u001b[m\u000f`

Is there a terminal mode where these can be translated? Or do I need to write a regex to parse the string and remove it myself?

Thank you

**Comment by mscdex** [comment]
You can try passing a specific `term` value (e.g. `'dumb'`) for your `pty` config object. Otherwise you will have to look at forcing whichever program you're using to disable them.
