### ISSUE TITLE
Can I create custom channels in the client?

### ISSUE THREAD

**Issue by Fransebas** [mscdex/ssh2#811]
Hi, I want to add other functionalities and I was wondering if I could create my custom Channel using the client. 

The server is created on Golang and the Go library does accept the creation of custom channels but I'm trying to figure out the client.

I could also use a Unix socket as a replacement of my custom socket, but I don't know if they are supported.

By looking at the code is found that this function `openChannel(self, type, opts, cb)` does that  but I think it's not exposed and I don't think I should tinker with that.

**Comment by mscdex** [comment]
There is no support for explicit channel creation like that. You can however invoke custom subsystems from the client via the `subsys()` method.

**Comment by Fransebas** [comment]
But if both a `shell()` and `subsys()` use the same channel, namely `session` how I'm to discriminate between the two in the server?

Also, do you know of any documentation I can read about the "channels protocol"? I know how the ssh protocol works with the sessions and the encryption, but I don't exactly know how it works at higher level.

**Comment by mscdex** [comment]
> But if both a `shell()` and `subsys()` use the same channel, namely `session` how I'm to discriminate between the two in the server?

They don't use the same channel.

> Also, do you know of any documentation I can read about the "channels protocol"?

In the SSH Connection Protocol RFC.

**Comment by Fransebas** [comment]
Thanks! the documentation help me a lot, I was confusing channels with channels types, both `shell()` and `subsys()` use the same channel type but different channels!

Just to be sure and close the issue, the library doesn't support custom channel types right?

**Comment by mscdex** [comment]
No, only those defined by the SSH RFCs.
