### ISSUE TITLE
Use ed25519 key in Electron

### ISSUE THREAD

**Issue by igor-lemon** [mscdex/ssh2#812]
Hi. Thanks for the lib it's awesome!

I have a question. Electron uses not `OpenSSL`, it uses `BoringSSL` 
BoringSSL supports ed25519 but doesn't work with your lib. 
Do we have any chances to run ed25519 on Electron via your's lib?

**Comment by mscdex** [comment]
`ssh2`/`ssh2-streams` supports whatever node supports. I can't speak for Electron, but ed25519 keys should be supported in (normal) node v12.x.

**Comment by igor-lemon** [comment]
It's sad because they don't use native NodeJS, they have some custom build.
