### ISSUE TITLE
How to change working directory, Who can provide an example? Very grateful

### ISSUE THREAD

**Issue by lanmolsz** [mscdex/ssh2#813]
> ^ what @unknownbrackets said. If you are creating a "web shell" then you probably want to use `shell()` rather than `exec()`, unless your "web shell" is just for executing one-off commands and is not designed to provide a full shell session.
>
> _Originally posted by @mscdex in https://github.com/mscdex/ssh2/issues/186#issuecomment-61919227_

**Dear author, can you provide a simple example?**

**Comment by mscdex** [comment]
An example of `shell()` is in the readme. Changing directories in that case would be done by typing/writing 'cd <directory>' to the shell stream.

**Comment by lanmolsz** [comment]
> An example of `shell()` is in the readme. Changing directories in that case would be done by typing/writing 'cd ' to the shell stream.

Since I am not familiar with the ssh protocol, my previous attempts to make a mistake have been unsuccessful. Your tips have solved it for me, again, thank you very much.

**Comment by alanhg** [comment]
> An example of `shell()` is in the readme. Changing directories in that case would be done by typing/writing 'cd ' to the shell stream.

The disadvantage of this method is that the executed cd command will record in  `~/.bash_history`.

I don't know if there is a way to avoid this.
