### ISSUE TITLE
Error on connection: "connect ECANCELED at TCPConnectWrap.afterConnect"

### ISSUE THREAD

**Issue by v0wels** [mscdex/ssh2#816]
I'm trying to build a small Electron app, and I'm running into an issue trying to connect to my host.

Code:
```
let Client = require('ssh2').Client, 
    conn
ipcMain.on('send-path', (event, arg) => {
    conn = new Client()
    conn.on('ready', () => {
        console.log('Client :: ready')
    }).connect({
        host: hostIP,
        port: 22,
        username: hostUser,
        password: hostPass
    })
})
```

Error that I'm getting:
```
Uncaught Exception:
Error: connect ECANCELED [hostIP:22]
    at TCPConnectWrap.afterConnect [as oncomplete]
(net.js:1061:14)
```

When I try adding `conn.on('error', function(err){ console.log(error) })`, the app just freezes and logs nothing to the console.

**Comment by v0wels** [comment]
My own dumb fault. The script that was triggering the SSH2 connection was, in essence, inadvertently quitting the app before the connection could even start, which was why that error was occurring, and also why it was beachballing.

**Comment by mscdex** [comment]
Ah yes, I've been bitten by that before with Electron.
