### ISSUE TITLE
Can't connect when I get password from sql request

### ISSUE THREAD

**Issue by cahobaut** [mscdex/ssh2#817]
Hello, when i try to do ssh connection with password hardcoded I'm good but when I try to use password from sql request I get Error: All configured authentication methods failed

```js
var Client = require('ssh2').Client;
var mysql = require('../db.js');
var conn1 = new Client();
var conn2 = new Client();
var Crypt = require('../encryption.js');
var pwdngn= '';
var pwdalv ='';
mysql.query("SELECT * FROM login where id = ?",['13'], function (err, res) {
  if (err){
    console.log("error: ", err);
  }
  else{
    console.log(res);
    var pwdngn = Crypt.decrypt(res[0].Password);
    console.log(pwdngn);
  }
});
mysql.query("SELECT * FROM login where id= ?", ['200'], function (err,res){
  if(err){
    console.log("error: ", err);
  }
  else {
    console.log(res);
    var pwdalv = Crypt.decrypt(res[0].Password);
    console.log(pwdalv);
    //Connection on 10.69.115.158 via 10.69.115.169
    conn1.on('ready', function() {
    console.log('FIRST :: connection ready');
    conn1.forwardOut('127.0.0.1',12345 , '10.69.115.158', 22, function(err, stream) {
      if (err) {
        console.log('FIRST :: forwardOut error: ' + err);
        return conn1.end();
      }
      conn2.connect({
        sock: stream,
        username: 'supportngn',
        password: pwdngn,
      });
    });
    }).connect({
      host: '10.69.115.169',
      username: 'alvin',
      password: pwdalv,
    });
    conn2.on('ready', function() {
      console.log('SECOND :: connection ready');
      conn2.exec('ls',function(err, stream) {
        if (err){
          console.log('SECOND :: exec error: ' + err);
          return conn1.end();
        }
        stream.on('end', function() {
          conn1.end(); //Close parrent (and this) connection
        }).on('data', function(data) {
          console.log(data.toString());
        });
      });
    });
  }
});
```

can someone help please ?

**Comment by mscdex** [comment]
You should move your second query into the callback of the first one to ensure `pwdngn` is actually set by the time you use it.

**Comment by cahobaut** [comment]
Hello thank you for considering my request. After Moving my sencond query into the callback of the firt, I got the same error. 
`
var Client = require('ssh2').Client;
var mysql = require('../db.js');
var conn1 = new Client();
var conn2 = new Client();
var Crypt = require('../encryption.js');
var pwdngn= '';
var pwdalv ='';
mysql.query("SELECT * FROM login where id = ?",['13'], function (err, res) {
  if (err){
    console.log("error: ", err);
  }
  else{
    console.log(res);
    var pwdngn = Crypt.decrypt(res[0].Password);
    console.log(pwdngn);

mysql.query("SELECT * FROM login where id= ?", ['200'], function (err1,res1){
  if(err1){
    console.log("error: ", err);
  }
  else {
    console.log(res1);
    var pwdalv = Crypt.decrypt(res1[0].Password);
    console.log(pwdalv);
    //Connection on 10.69.115.158 via 10.69.115.169
    conn1.on('ready', function() {
    console.log('FIRST :: connection ready');
    conn1.forwardOut('127.0.0.1',12345 , '10.69.115.158', 22, function(err, stream) {
      if (err) {
        console.log('FIRST :: forwardOut error: ' + err);
        return conn1.end();
      }
      conn2.connect({
        sock: stream,
        username: 'supportngn',
        password: pwdngn,
      });
    });
    }).connect({
      host: '10.69.115.169',
      username: 'alvin',
      password: pwdalv,
    });
    conn2.on('ready', function() {
      console.log('SECOND :: connection ready');
      conn2.exec('ls',function(err, stream) {
        if (err){
          console.log('SECOND :: exec error: ' + err);
          return conn1.end();
        }
        stream.on('end', function() {
          conn1.end(); //Close parrent (and this) connection
        }).on('data', function(data) {
          console.log(data.toString());
        });
      });
    });
  }
});
}});`

**Comment by mscdex** [comment]
I would carefully check that the values match your hardcoded values and that `typeof pwdalv === 'string'` and `typeof pwdngn === 'string'`. If all of that checks out, I don't know what else to suggest.

**Comment by cahobaut** [comment]
Thank you for this suggestion. I've  try console.log (pwdalv == 'hardcoded') and it's false . I'll add quote to see if it's good

**Comment by cahobaut** [comment]
It's good now I close the issue sorry because it was not related to your Library. Hope you'll help me on my second issue. And really nice work
