### ISSUE TITLE
Execcommand and keyboard interaction

### ISSUE THREAD

**Issue by simonlt** [mscdex/ssh2#824]
Hi, 

I would like to know if it possible to have a keyboard interaction on execCommand like the connect mode?

I connect on a bastion and after that, i do an execcommand like ssh user@server 'command'.

I would like to fill the passphrase but i didn't find how to do that.

Thanks in advance for your help.

SImon

**Comment by mscdex** [comment]
If you're connection hopping, you can already do that with `ssh2` without executing `'ssh ...'` on the intermediary host. There is an example of doing just this in the readme.

As far as using keyboard-interactive authentication for the second host, you can also do that with the `tryKeyboard` option.
