### ISSUE TITLE
ShellOptions missing env

### ISSUE THREAD

**Issue by cowwoc** [mscdex/ssh2#826]
The readme states that the `shell` command may set two options: `x11` and `env` as discussed in the `exec` documentation.

But `ShellOptions`, as defined in the typescript bindings, only contains `x11`.

Please allow `env` to be set as well.

**Comment by mscdex** [comment]
I'm not in control of anything typescript, so I think you should file an issue with whoever maintains the typescript bindings.

**Comment by cowwoc** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38096. Thank you.
