### ISSUE TITLE
Is there a custom encoding function for the Chinese code display problem returned by the server?

### ISSUE THREAD

**Issue by ai930** [mscdex/ssh2#827]
Chinese display problems, is there any good solution? Or increase the encoding parameter definition?

**Comment by mscdex** [comment]
There is nothing really encoding-specific in `ssh2`. Perhaps you can explain more about the problem you're running into?

**Comment by zxdong262** [comment]
@ai930 I believe it is not related to ssh2, since we can transfer binary data, we can choose encode/decode, here is a example from electerm: https://github.com/electerm/electerm/blob/83070538ebf738be5cc3945b157fc3f65d8a453d/src/client/components/terminal/index.jsx#L703-L723
