### ISSUE TITLE
How to copy another ssh connection

### ISSUE THREAD

**Issue by ZG-frank** [mscdex/ssh2#829]
Hi, I have connected to the server using the Client methods（connect method）. But I want to copy another window，like xshell -- copy ssh channel. So I don't have to open a browser tab and enter my password again.

**Comment by mscdex** [comment]
I don't understand what you're wanting to accomplish exactly.

**Comment by ZG-frank** [comment]
![image](https://user-images.githubusercontent.com/15084040/65226180-fe051000-daf8-11e9-8db2-d1c1219c7459.png)

copy the first tab,  I don't have to enter password again. Second Tab and the first tab use the same channel ? That is what i am wanting to accomplish.

**Comment by ZG-frank** [comment]
is OpenSSH Multiplexing ?

**Comment by mscdex** [comment]
As far as multiplexing goes, you can open as many channels per connection as the server allows.

**Comment by ZG-frank** [comment]
yes, sir. But Is there any API or suggestions for me to implement multiplexing? Thank you
