### ISSUE TITLE
User input blocked when adding pty event to session.

### ISSUE THREAD

**Issue by luukhoeben** [mscdex/ssh2#831]
Hey,

I'm trying to create a server for reverse tunneling. Now, everything works and I return the link to the session, I'm just trying to get rid of this message:
`PTY allocation request failed on channel 0`

So I've added the `.on('pty' (accept, reject) => accept());` on the session and now I can't use ctrl-c to end the connection.. I have tried to add the signal event and check if it is `SIGINT` but that didn't work. After trying to console log the info object in the signal event, I saw that it doesn't trigger when pressing ctrl-c.

Am I missing something here?

Here is what I have in the session:
```js
    this.client.on('session', (accept, reject) => {
      let session = accept();

      session.on('pty', (accept, reject) => accept());

      session.on('signal', (accept, reject, info) => {
        console.log(info);
        accept();
      });

      session.on('shell', (accept, reject) => {
        this.stream = accept();

        let domain = `${this.subdomain}.${global.options.domain}`;

        if (global.options.httpPort !== 80) {
          domain += `:${global.options.httpPort}`;
        }

        this.stream.write(colors.green(`Your link is: https://${domain}\r\n`));
        this.stream.write('Press ctrl-c to quit.\r\n\r\n');
      });
    });
```

**Comment by mscdex** [comment]
Since the client is sending raw input, you have to handle that appropriately. Specifically, ctrl-c will send `'\x03'`, so you could add something like this:

```js
this.stream.on('data', (chunk) => {
  if (chunk.length === 1 && chunk[0] === 0x03)
    this.stream.end();
});
```

**Comment by luukhoeben** [comment]
@mscdex Thanks! That works :D
