### ISSUE TITLE
Keys not working in a shell connection with ncurses

### ISSUE THREAD

**Issue by KodeStar** [mscdex/ssh2#834]
```
  client.on('ready', () => {
    client.shell({ rows: config.rows, cols: config.cols }, (err, stream) => {
      if (err) {
        throw err
      }
      stream.on('close', () => {
        client.end()
      }).on('data', (data) => {
        console.log(data)
        term.write(data.toString('utf8'))
      })

      term.onKey((e) => {
        console.log(e)
        stream.write(e.key)
      })

    })
  }).connect(config.connection)
```
I have the above set, when I press F10 the term.onKey logs the key press, then the stream.on('data') logs the key. However, if I start midnight commander with `mc` then press F10 (to quit), the term.onKey logs the key press, but I get nothing from the stream.on('data'). Additionally, I've been told the arrow keys don't work in mc on linux as well, though they seem to work on windows and mac, but the function keys don't appear to work on any of them. Any ideas?

**Comment by KodeStar** [comment]
I've put a console.log in `ssh2-streams/lib/ssh,js` in `SSH2Stream.prototype.channelData = function(chan, data) {` and that is being hit while in mc and hitting F10, so it's at least receiving it, it just crashes out somewhere along the way I guess.

**Comment by KodeStar** [comment]
It might not be anything to do with ncurses. I get the issues when connecting to an Unraid system (which is based on slackware). If I connect to an ubuntu system and the unraid system and type `l` then `s` then `backspace` console logging the terminal input returns the same for both, but console logging:
```
.on('data', (data) => {
  console.log(data.toString())
  term.write(data.toString())
})
```
returns something different on the unraid system
```
l
l
s
s


```
vs
```
l
l
s
s

[K
```

**Comment by mscdex** [comment]
The latter just includes a control code that seems to tell the terminal to clear the screen.

Be aware that by default a VT100 terminal type is sent when starting `.shell()`. I don't know what the `term` object is exactly, but if it's expecting a different type you will need to change the terminal type in one place or the other.

Also doing `data.toString('utf8')` is not really safe from within a `'data'` event, because you could get garbage if `data` doesn't contain all the bytes for a multi-byte character. The best solution is going to be to preserve the binary data and have `term` or whatever properly convert the data at the correct point in time.

**Comment by KodeStar** [comment]
Thanks for getting back to me. I think you may have solved the mystery, it doesn't look like vt100 is listed in `toe` for unraid. I'll try xterm and see if that results in any better results.

**Comment by KodeStar** [comment]
When would be the correct point in time to output the data then if not on data? I'm using xterm.js to output the data from the stream and passing the binary data to write wont work.

**Comment by mofux** [comment]
@KodeStar xterm.js v4 added support for writing binary data, see:

https://xtermjs.org/docs/api/terminal/classes/terminal/#write

**Comment by KodeStar** [comment]
thanks @mofux I'm already using v4 and it didn't like me passing data straight to it, but I'll investigate more

**Comment by KodeStar** [comment]
Ahh, I might not be on a recent enough version, it looks like Uint8Array was only added recently

**Comment by mscdex** [comment]
> When would be the correct point in time to output the data then if not on data?

I was referring specifically to the use of `.toString('utf8')` inside the `'data'` event handler. You would still want to pass the chunk of data directly (as-is) to the other side before decoding.

**Comment by mofux** [comment]
@KodeStar Yeah the support for `Uint8Array` just came in recently with 4.1.0:
https://github.com/xtermjs/xterm.js/releases/tag/4.1.0

**Comment by mscdex** [comment]
The default `term` setting for `shell()` is `'vt100'`. So you need to make sure that `e.key` contains the appropriate escape code that simulates a function key press for that terminal type. Perhaps whatever terminal type `term` is emulating does not match up with the `term` setting being used by `shell()`. If it does, you might try different terminal types.
