### ISSUE TITLE
node http subdomain pipe

### ISSUE THREAD

**Issue by luukhoeben** [mscdex/ssh2#835]
Hey,

I'm trying to build tunneling app and it is working okay but now I'm making a `net.createServer()` for each request (`ssh -R something:80:localhost:8000 domain.com`) and using the `forwardOut()` method piping the data to the net server. then using http-proxy to connect when you try to connect to the something.domain.com.

Now I would like to take out the middle man (the proxy and net server) if that is possible, but I don't know how.. `forwardOut()` hangs the request, because I don't send a response specifically..

Here is the request method I have:
```js
  handleRequest (request, response) {
    let parsedHost = tldjs.getSubdomain(request.headers.host);
    let subdomain = parsedHost !== '' ? parsedHost : null;

    if (!subdomain || !ActiveClients.has(subdomain)) {
      response.writeHead(404, {
        'Content-Type': 'text/plain'
      });

      return response.end('404: Not Found!');
    }

    let client = ActiveClients.get(subdomain);

    client.client.forwardOut(
      client.requestInfo.bindAddr, client.requestInfo.bindPort,
      request.connection.remoteAddress, request.connection.remotePort,
      (err, upstream) => {
        if (err) {
          request.connection.end();
          return console.error('not working: ' + err);
        }
        upstream.pipe(request.connection).pipe(upstream);
      });
  }
```
`ActiveClients` is just a class I made to store the clients like:
`subdomain: Client`

the `Client` class is just a class where I save the connection (`client`) and some other things like the `requestInfo`.

Does anybody have an idea how I can achieve this?

Thanks :)

**Comment by mscdex** [comment]
I'm not sure what you're trying to do here, but `ssh -R` is analogous to `forwardIn()`, both of which ask for the remote server to forward TCP connections to the client. `forwardOut()` is analogous to `ssh -L`, where the client is asking the remote server to create a TCP connection from the remote server to some arbitrary destination server.

If you're trying to proxy an incoming HTTP request to an HTTP server accessible by the remote server, then what you have isn't going to work as node is already parsing your HTTP request and properly formatting your response. You would be better off just using the built-in http/https agents provided by `ssh2`, then you could just make a new outgoing request to whatever server on the other end (copying the relevant bits from the original request -- url, headers, body, etc.) and then pass the response from that request back to the response for the original request (e.g. status code, headers, body, etc.).
