### ISSUE TITLE
Authentication method issue

### ISSUE THREAD

**Issue by kapilgurnani** [mscdex/ssh2#836]
I am getting Authentication method none everytime.
I test server by filezilla on linux

I am getting below value on ctx parameter

domain:null
method:"none"
service:"ssh-connection"
user:"abc"
username:"abc"

**Comment by mscdex** [comment]
Assuming you mean you're writing a server with `ssh2`, that's entirely possible for the client to request the `'none'` authentication method. That just means it's requesting access without providing any credentials. It's sometimes used by clients to determine what methods are actually usable. You can pass such a list of methods as an array to `ctx.reject()`.

**Comment by kapilgurnani** [comment]
I am taking the credentials from filezilla so what can be the solution for this?

**Comment by kapilgurnani** [comment]
I tried by sending password from filezilla but didn't get any password in ctx.

I were getting this parameters on ctx -
domain:null
method:"none"
service:"ssh-connection"
user:"abc"
username:"abc"

**Comment by xMarkusSpringerx** [comment]
I have the same probelm as @kapilgurnani . I try to connect to the FTP Server with filezilla providing username and password within filezilla. but the SFTP Server responds with none as authentication type. Do you know how to avoid this?

**Comment by mscdex** [comment]
I don't have any suggestions other than the ones I've already given @xMarkusSpringerx.

**Comment by P4sca1** [comment]
The following code snippet might be useful if you only want to allow login through passwords.
Filezilla will still try to login via 'none' one time but then sends another request using the password.
```ts
if (authContext.method !== 'password') {
  return authContext.reject(['password'])
}
```

**Comment by whatl3y** [comment]
I felt this needed to be documented since I spent >1 hour trying to figure it out to finally find this issue buried in the issues list. https://github.com/mscdex/ssh2/pull/993
