### ISSUE TITLE
Unsupported operation in server download only 

### ISSUE THREAD

**Issue by kapilgurnani** [mscdex/ssh2#840]
Hi,

I used this example https://github.com/mscdex/ssh2/blob/master/examples/sftp-server-download-only.js but getting error
I tried through filezilla for test SFTP server

Screenshot attached below
![Screenshot from 2019-10-18 15-18-31](https://user-images.githubusercontent.com/53506960/67084599-e3d35600-f1ba-11e9-890a-2338c7f0f9d6.png)

Please assist me how can I run this example and atleast will seeing all files and folder through filezilla.

**Comment by mscdex** [comment]
You can set `debug: console.log` in your server config object to see what ssh/sftp requests the client is sending. It's most likely sending a request that is not implemented in the example.
