### ISSUE TITLE
sftp readdir no such file error for accented directory name 

### ISSUE THREAD

**Issue by AZZB** [mscdex/ssh2#844]
I tried to list all files inside directory but the name of the folder has an accented characters so when I try to access it I get the error no such file.

any idea for this encoding problem ?

**Comment by mscdex** [comment]
All I can tell you is that paths are sent to the ssh server as UTF-8. Beyond that it's up to the ssh server to do the right thing.

Does OpenSSH's sftp client work (executing `ls <pathname>` from the interactive prompt) when connected to the same server?

**Comment by AZZB** [comment]
I tried it and yeah it doesn't work . but I don't know how such sftp applications like winscp can deal with this encoding problem.

when I type ls using openSSH sftp client or this module I get this character � replacing accented character

**Comment by mscdex** [comment]
I'm not able to duplicate the issue. Here's the simple example I tried that worked:

```js
client.sftp(function(err, sftp) {
  if (err) throw err;
  sftp.readdir('/tmp/cumpleaños', (err, items) => {
    if (err) throw err;
    console.dir(items);
    client.end();
  });
});
```

The server I tested with was OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 and the account's environment has `LANG="en_US.UTF-8"`.
