### ISSUE TITLE
Passing around auth context in SFTP handler

### ISSUE THREAD

**Issue by riston** [mscdex/ssh2#847]
Question mostly about SFTP example located here https://github.com/mscdex/ssh2#password-and-public-key-authentication-and-non-interactive-exec-command-execution. In the `authenticate` callback has `ctx` value. Is it possible to pass additional context to in SFTP handling callback? Using higher level variable in client callback isn't the correct way to do it.

```session.on('sftp', function(accept, reject) { ... }```

**Comment by mscdex** [comment]
I'm not able to view that link, but I'm not quite sure what you mean by

> Using higher level variable in client callback isn't the correct way to do it

**Comment by riston** [comment]
Ty corrected link, so the problem is fairly simple how I can pass auth context + additional details in the 'sftp' callback? 
`   session.on('sftp', function(accept, reject) {`

**Comment by mscdex** [comment]
Using the shared parent scope is the easiest and most natural way to do that. I don't understand why that is not a correct way to do it.

**Comment by riston** [comment]
I provide pseudocode for my example, the `authenticate` could be some DB call which in return provides some additional user context which could be used in SFTP handler. WDYT of this approach?

```
// Imports removed
new ssh2.Server({
  hostKeys: [fs.readFileSync('host.key')]
}, function(client) {
  console.log('Client connected!');

  var authContext = {};
  client.on('authentication', function(ctx) {
    switch (ctx.method) {
      case 'password':
        authenticate(username, password)
          .then((user) => {
            authContext = user;
            ctx.resolve();
          })
          .catch(() => ctx.reject());
        break;

      default:
        return ctx.reject();
    }

    ctx.accept();
  }).on('ready', function() {
    console.log('Client authenticated!');

    client.on('session', function(accept, reject) {
      var session = accept();

      // SFTP handling ....

      console.log('Access auth context here', authContext);
    });
  }).on('end', function() {
    console.log('Client disconnected');
  });
}).listen(0, '127.0.0.1', function() {
  console.log('Listening on port ' + this.address().port);
});
```

**Comment by mscdex** [comment]
That was what I was suggesting. I do not see anything wrong with it.
