### ISSUE TITLE
It doesn't support OpenSSH 7.9?

### ISSUE THREAD

**Issue by uniorder** [mscdex/ssh2#849]
My mac os x default ssh version is 7.9 now:
```shell
ssh -V
OpenSSH_7.9p1, LibreSSL 2.7.3
```
When I use this lib, I got an error: 
```
SSH-2.0-openssh_7.9
Protocol mismatch.
```

What can I do now?

**Comment by mscdex** [comment]
Connecting to/from OpenSSH 7.9 works fine for me. Perhaps you can post more details, like debug output on client and server, client and server OS and version, other configurations tested with same OpenSSH version, etc.

**Comment by mofux** [comment]
FWIW: my Mac runs on the same OpenSSH version, and I have no problems connecting to it via `ssh2@latest`.

**Comment by uniorder** [comment]
> FWIW: my Mac runs on the same OpenSSH version, and I have no problems connecting to it via `ssh2@latest`.

wired, but now I don't care this message, maybe just a warning.
