### ISSUE TITLE
How to execute a sequence of commands?

### ISSUE THREAD

**Issue by OwenMelbz** [mscdex/ssh2#851]
Hi,

Is it possible to execute a sequence of commands, keeping the previous session state active? e.g.

```
exec('su userx');
exec('whoami'); // userx
exec('mkdir test');
exec('cd test');
exec('pwd'); // /home/userx/test
```

So far I've tried it a few ways with not much success, I'm pretty new when it comes to anything more than SSHing in normally via terminal.

This is what I've got so far:

```js
#!/usr/bin/env node
const { Client } = require('ssh2');

const connection = new Client;

const command = command => {
    return new Promise((success, fail) => {
        connection.exec(command, { pty: true }, function (error, stream) {
            if (error) {
                return fail(error);
            }

            stream.on('data', response => success(response.toString()))
        });
    });
};

connection.on('ready', async () => {
    await command('whoami');
    await command('su user');
    await command('whoami');
});

connection.connect({
    host: 'XXXX',
    username: 'XXXXXXX',
    port: 'XXXXXXXX',
    privateKey: require('fs').readFileSync('/Users/owen/.ssh/id_rsa'),
});

```

**Comment by mscdex** [comment]
Your options are basically:

1. Chain the commands together
2. Use `.shell()` instead and deal with a shell prompt in output and a loss of a separate `stderr` stream (everything comes through the `stdout` stream)

**Comment by markspcs** [comment]
The "chain the commands" is not necessarily going to work for what I'm trying to do. My commands are dynamic based on the output. I'm trying to do the same with .shell as owenmelbz was doing with .exec. But that is not working for me. Would you/anyone have a working example for sequencing commands together?

**Comment by mscdex** [comment]
@markspcs For longer lived processes like interactive shell sessions, you could also get the symlink target for `/proc/<pid of shell session>/cwd` from another `exec()`/connection to get that process's current working directory.

Either way, this is really outside the scope of this module and I've already outlined a few possible solutions.
