### ISSUE TITLE
Is it possible to follow "su"?

### ISSUE THREAD

**Issue by Coding-Kiwi** [mscdex/ssh2#861]
Hi, first of all: great project!

I create a client, connect it and open a shell and parallel to that I download some files via sftp, everything works perfectly.
````
var conn = new Client();

conn.on('ready', () => {
     conn.shell(pty_settings, (err, stream) => {...});
     conn.sftp((err, sftp) => {...});
}).connect(sshdata);
````

When I now switch users in the shell using `su otheruser` the shell is acting as otheruser, while the sftp channel still uses the original user passed in `sshdata`. Even if I run `conn.sftp((err, sftp) => {...});` again after switching to `otheruser` in the shell, the sftp stream still only has the permissions of the original user because the user change of course only takes effect inside the shell and not on the whole client instance (`conn`).

**Question**: Is it somehow possible to use sftp as `otheruser` after `su otheruser` has been successfully executed in the shell?

**Comment by mscdex** [comment]
It might be technically allowed by the SSH protocol, but for example [OpenSSH servers explicitly reject changing users after a successful authentication](https://github.com/openssh/openssh-portable/blob/edd1d3a6261aecbf9a55944fd7be1db83571b46e/auth2.c#L314-L319).

Also SFTP does not support changing users either.

**Comment by mscdex** [comment]
It should also be noted that `conn.shell()` and `conn.sftp()` open totally separate channels on the connection, so switching to a different user in an interactive session will not alter the behavior of the SFTP channel.
