### ISSUE TITLE
How to live auth with sms code

### ISSUE THREAD

**Issue by zxdong262** [mscdex/ssh2#862]
Hi @mscdex

I am developing a ssh app with ssh2([electerm](https://github.com/electerm/electerm)), some user told me that some server has live auth, when login, besides the password, will ask for live sms code, is there a common protocol/practice for this, can you give some guide or example about how to deal with this situation with ssh2?

![ ](https://camo.githubusercontent.com/09ad42788e5a6e07435fce5d82f1ec9d47488089/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f70616e7869616f6775616e672f4d79496d6167652f696d672f32303230303130383134353931372e706e67)

**Comment by mscdex** [comment]
The secondary ("verification code") is most likely done with `keyboard-interactive` authentication. So without seeing debug information, my guess is the password is entered first and fails, then `keyboard-interactive` is attempted.

**Comment by zxdong262** [comment]
@mscdex Thank you, I would try it
