### ISSUE TITLE
`env` option doesn't work in `exec()`

### ISSUE THREAD

**Issue by thesmart** [mscdex/ssh2#865]
I can't seem to get the env option to work when using the `exec()` function.

Here's source modified from the example, where I set `FOOBAR` and `echo` it:
```js
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('echo "This should be foobar: $FOOBAR"', {
    env: {
      FOOBAR: "HELLO WORLD!"
    }
  }, function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  privateKey: require('fs').readFileSync('/here/is/my/key')
});
```

Here's the output when connecting to Debian 9:
```
Client :: ready
STDOUT: This should be foobar: 

Stream :: close :: code: 0, signal: undefined
```

**Comment by mscdex** [comment]
The server typically limits what can be set. In OpenSSH servers for example, the list of accepted environment variable names is determined by the `AcceptEnv` server setting. If you're not in control of the server, then you'd have to set the variable inside the command string (e.g. `export FOOBAR='HELLO WORLD!'; echo "This should be foobar: $FOOBAR"`).

**Comment by thesmart** [comment]
Thanks! This is the same workaround I came up with.
