### ISSUE TITLE
Memory leak on 'Timeout' error ?

### ISSUE THREAD

**Issue by ctoesca** [mscdex/ssh2#866]
Hello,

when host is not reachable, it seems Ssh2 client create a memory leak.
You can see it with the sample code below (NODEJS v12.14.1, SSH2 version:  0.8.7).

After one hour, memory used is about 400 mo and never goes down.
![image](https://user-images.githubusercontent.com/3381450/72684153-68957f00-3ade-11ea-8066-182748f8329f.png)

```
const Ssh2 = require("ssh2");
let count = 0;
let runningCount = 0;
console.log("PID=" + process.pid);

function connect(host) {
    count++;
    runningCount++;
    let client = new Ssh2.Client();
    client.on('error', (err) => {
        runningCount--;
        client.end();
        client.removeAllListeners();
        client.destroy();
        console.log("ERROR " + count + " - runningCount = " + runningCount + " " + err.toString());
    })
    .on('ready', () => {
        runningCount--;
    })
     .connect({
        host: host,
        username: 'root',
        password: '',
        readyTimeout: 500
    });
}

setInterval(() => {
    connect("fakehost55555");
}, 100);
```

**Comment by ctoesca** [comment]
I propose path: 
https://github.com/mscdex/ssh2/compare/master...ctoesca:patch-1

**Comment by mscdex** [comment]
Which kind of memory are you measuring exactly?

**Comment by mscdex** [comment]
I'm betting this is just the GC being lazy as `ssh2`/`ssh2-streams` do not use global maps or anything that could leak across instantiations of `Client`.

FWIW I ran a simpler version of the code you posted and set a small heap limit (40 MB). The rss and total heap remained stable over the course of running for an hour. This seems to verify my suspicion that this is GC-related since if it weren't, the (rss) memory would continue to expand despite the heap limit. Here's the code I used:

```js
var Ssh2 = require('ssh2');
var lastRSS;
var lastHeap;

function connect(host) {
  var client = new Ssh2.Client();
  client.on('error', (err) => {
    var mem = process.memoryUsage();
    if (mem.rss !== lastRSS || mem.heapTotal !== lastHeap) {
      lastRSS = mem.rss;
      lastHeap = mem.heapTotal;
      process.stderr.write(mem.rss + ' ' + mem.heapTotal + '\n');
    }
    connect('fakehost55555');
  })
  .on('ready', () => {})
   .connect({
      host: host,
      username: 'root',
      password: '',
      readyTimeout: 500
  });
}

connect('fakehost55555');
```

**Comment by ctoesca** [comment]
Thank you for your response.

I measure 'Private Bytes' memory with ProcExp (Windows tool).
In your code, you make one connection at a time and there is not a memory leak.

Whene I make 2 connections/sec with setInterval(), with a readyTimeout of 500ms, you can see that heapUsed and rss keep increasing.

- count=40 runningCount=0 rss=26095616 heapUsed=7704808
- count=500 runningCount=0 rss=28573696 heapUsed=9477864
- count=1000 runningCount=0 rss=33128448 heapUsed=13769776


```
const Ssh2 = require("ssh2");
let count = 0;
let runningCount = 0;
function connect(host) {
    count++;
    runningCount++;
    let client = new Ssh2.Client();
    client.on('error', (err) => {
        runningCount--;
        var mem = process.memoryUsage();
        if (count % 2 == 0) {
            process.stderr.write("count=" + count + " runningCount=" + runningCount + " rss=" + mem.rss + ' heapUsed=' + mem.heapUsed + '\n');
        }
    })
    .on('ready', () => {
        runningCount--;
    })
    .connect({
        host: host,
        username: 'root',
        password: '',
        readyTimeout: 500
    });
}
setInterval(() => {
    connect("fakehost55555");
}, 500);
```

**Comment by mscdex** [comment]
I switched back to using `setInterval()` but for me the end result is the same after letting the process run for a long time -- max memory usage stabilizes.

FWIW here is the code I used:

```js
var Ssh2 = require('ssh2');
var maxRSS = 0;
var maxHeap = 0;

function connect(host) {
  var client = new Ssh2.Client();
  client.on('error', (err) => {
    var mem = process.memoryUsage();
    if (mem.rss > maxRSS || mem.heapTotal > maxHeap) {
      if (mem.rss > maxRSS)
        maxRSS = mem.rss;
      if (mem.heapTotal > maxHeap)
        maxHeap = mem.heapTotal;
      process.stderr.write((''+maxRSS).replace(/(\d)(?=(\d{3})+$)/g, '$&,') + ' ' + (''+maxHeap).replace(/(\d)(?=(\d{3})+$)/g, '$&,') + ' ' + (new Date()) + '\n');
    }
  })
  .on('ready', () => {})
  .connect({
    host: host,
    username: 'root',
    password: '',
    readyTimeout: 500
  });
}

setInterval(() => {
  connect('fakehost55555');
}, 100);
```

I've already tried doing memory diffs with the inspector and I do not find anything leaking. This is also a pure JS module, so there are no C++ addons to leak anything, so everything should be garbage collected at some point by V8.
