### ISSUE TITLE
First example in readme is wrong.

### ISSUE THREAD

**Issue by Timmmm** [mscdex/ssh2#867]
It has this code:

         stream.on('close', function(code, signal) {

But the `code`/`signal` parameters get sent to the `exit` event, not `close` (*cough* dynamic types are rubbish *cough*).

**Comment by mscdex** [comment]
They should be sent to both. Are you finding otherwise?

**Comment by Timmmm** [comment]
Ah, no I was basing it on [the Typescript typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ssh2/index.d.ts#L102). I guess they are wrong? Or maybe out of date?

**Comment by mscdex** [comment]
I suppose so, I don't use Typescript.

**Comment by Timmmm** [comment]
Good time to start! There's not really any good reason not to (apart from the effort of learning it I guess, but it's pretty easy). Maybe upgrade to slightly more modern Javascript at the same time (i.e. `let` and arrow functions instead of `var` and `function` - they're much less insane).

**Comment by Timmmm** [comment]
Just as a little motivation, I've only been using this library for 1 day and already run into one type error:

![image](https://user-images.githubusercontent.com/376842/72831536-fe661100-3c7a-11ea-9653-33e8a98008bd.png)

TypeScript more or less solves these issues (unless you're using Javascript and people get the types wrong, which happens a lot and is annoying).
