### ISSUE TITLE
How to use hostVerifier [client] 

### ISSUE THREAD

**Issue by Fransebas** [mscdex/ssh2#869]
Hi, I wanted to use the hostVerifier function to validate the host to which I'm connecting and I have two questions:

1.  How to find out the valid hash algorithms strings? I use this code snippet but I use the given strings and it doesn't work `/Users/fransebas/Documents/work/GUIS/electronUIreact/node_modules/ssh2/lib/client.js:366 Uncaught (in promise) Error: Invalid host hash algorithm: sha254`

```javascript
let crypto = require('crypto');
let listOfSupportedHashes = crypto.getHashes();
console.log('listOfSupportedHashes ', listOfSupportedHashes);
```

2. If I want to use the file `~/.ssh/know_hosts` do I only need to do is `ssh-keygen -HF 192.168.1.78` and compare the given string to the one returned by `hostVerifier `? something like this: ( btw I don't know which hash algorithm ssh-keygen uses 🙁 )
```
hostVerifier(hashKey){
    var localHash = exec("ssh-keygen -HF " + ip);
    return hashKey === localHash;
}
```

Thanks!

**Comment by mscdex** [comment]
You have a typo in the hash algorithm name: `'sha254'` should be `'sha256'`. The list of supported hashes is found via `crypto.getHashes()` as you noted.

known_hosts does not store hashes of the public key, it only optionally stores a hash of the hostname. You can compute hashes of hosts stored in known_hosts using something like:

```
ssh-keygen -q -l -f ~/.ssh/known_hosts -F somehostname
```

The output includes the hostname, key type, hash algorithm, and the hash itself base64-encoded.

**Comment by Fransebas** [comment]
Thanks! and sorry for the typo 😅 I was sure I copy-pasted the name (But I didn't).

I think `ssh-keygen -q -l -f ~/.ssh/known_hosts -F somehostname` will be sufficient as `crypto.getHashes()` is very likely to have all the hashes that `ssh-keygen` uses

**Comment by Fransebas** [comment]
Hi it's me again, I have only one more question regarding this, I already compare the given hash with the stored hashed keys but I have one question, How do I know which key type the server is using? Because `ssh-keygen -q -l -f ~/.ssh/known_hosts -F somehostname` gives me multiple hashes, one for each different key the server supports.

Right now I'm comparing the given key hash with all the stored hashes and if it's equal to one of them I'm good to go but if none match I can't know if the server is trying to fool me or I haven't registered that specific key.

So I don't know if there is a way to know which key the server decided to use because I know that the client internally knows that.

**Comment by shangchengxiang** [comment]
> You have a typo in the hash algorithm name: `'sha254'` should be `'sha256'`. The list of supported hashes is found via `crypto.getHashes()` as you noted.
> 
> known_hosts does not store hashes of the public key (it stores the public key itself instead), it only optionally stores a hash of the hostname. You can compute hashes of hosts stored in known_hosts using something like:
> 
> ```
> ssh-keygen -q -l -f ~/.ssh/known_hosts -F somehostname
> ```
> 
> The output includes the hostname, key type, hash algorithm, and the hash itself base64-encoded.
> 
> The hash algorithm used can be specified by passing `-E` to `ssh-keygen`, however the algorithm support is limited (only md5 and sha256 on my machine).
ssh-keygen -E sha256 -q -l -f .ssh/known_hosts -F host 
host ECDSA SHA256:YuukV3vH+XwiDNtp62MvZsDr0XeIOmzNKOyPW/kLkQk

I do like this , it  output the base64-encoded.  How can I compare the output and hashedkey? I found they are having different format.
