### ISSUE TITLE
how to wait for the execution of a command with exec

### ISSUE THREAD

**Issue by degoya** [mscdex/ssh2#874]
I'd like to make a mysqldump via ssh and download the file after it got dumped. But i don't know how i can wait until the mysql dump command has been finished. The SFTP will start with the download even when the dump is not completed.

my code looks so far like his.

        var conn = new Client();
        conn.on('ready', function() {
        console.log('Client :: ready');
        
        console.log('Client :: start Shell');
        var filename = configSQL.name + '.sql';
        var remotepath = '/private/';
        conn.exec('cd ' + remotepath + ' ; rm ' + filename + ' ; mysqldump -h 127.0.0.1 -u '+ configSQL.user +' -p'+ configSQL.pass +' ' + configSQL.name + ' > ' + filename , function(err, stream) {
            if (err) throw err;
            stream.on('close', function(code, signal) {
                console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
                conn.end();
            }).on('data', function(data) {
                console.log('STDOUT: ' + data);
            }).stderr.on('data', function(data) {
                console.log('STDERR: ' + data);
            });
        });

        console.log('Client :: start SFTP');
        conn.sftp(function(err, sftp) {
            if (err) throw err;
            var moveFrom = remotepath + filename;
            var moveTo = 'src/sql/' + filename;
            console.log('Client :: start downloading');
            sftp.fastGet(moveFrom, moveTo, {}, function(downloadError) {
                if (downloadError) throw downloadError;
                console.log("Succesfully downloaded");
                conn.end();
                process.exit();
            });
        });
    }).connect({
        tryKeyboard: true,
        forceIPv4: true,
        agent: 'pageant',
        host: configSSH.host,
        port: configSSH.port,
        username: configSSH.username,
        privateKey: require('fs').readFileSync('./' + configSSH.privateKeyFile)
    });

**Comment by mscdex** [comment]
You're treating asynchronous tasks (`conn.exec()` and `conn.sftp()`) as though they are synchronous. I think this kind of generic question is best suited for a place like stackoverflow or the [nodejs/help repo](https://github.com/nodejs/help/issues).

**Comment by uwe72** [comment]
I have a very similar topic. Do you have already an idea how to solve this?
