### ISSUE TITLE
Channel open failure when connection hopping more than once

### ISSUE THREAD

**Issue by Reprovo** [mscdex/ssh2#876]
Hi. Great module by the way. Very useful. Thank you !

I am having an issue however when connection hopping more than once. 

I am only running a show command on a cisco router that is connecting from another server device.
The first connection works without issue. I have the connection running on an interval of 5 minutes. 
It never connects again after the initial connection. Receiving below error.
I have to restart the application to get it working again.

**SECOND :: exec error: Error: (SSH) Channel open failure: 
SECOND :: exec error: Error: Unable to exec**

**Comment by mscdex** [comment]
Can you show the code you're using?

I'm not sure what you mean by:

> I have the connection running on an interval of 5 minutes. It never connects again after the initial connection.

**Comment by Reprovo** [comment]
Hello. Thanks for the quick response. I've just changed the event  listeners to .once and seems to have resolved the issue.

Running the connection hopping as a function within setInterval

```
setInterval(() => {

    hopSSH((output)=>{
        var outputSearch = output.search("Community")
        if(outputSearch) {
            console.log('Active link: VSAT')
            active_FX.textContent="Active link: VSAT"
        } else {
            console.log('Active link: FBB')
        }
 
     })

},100000)
```
