### ISSUE TITLE
Shell -> STDOUT with continuous output not readable

### ISSUE THREAD

**Issue by borsTiHD** [mscdex/ssh2#877]
Hi all,

first of all, this package is amazing, so thank you so much and keep it up. :)
I'm still learning and I have a problem. I don't know how I could solve it and hope you can help me.
The connection to a remote host works perfectly and I can send commands and receive them.
Everything works fine... I visualize the output in an html textarea field.

So far so good... my problem starts with a special command for monitoring an interface.
This command makes the host send a continuous return (I don't know what it's called). When I send the command over putty, the output seems to refresh everytime (even you can scroll up an see the older outputs :D ).
First of all, with ssh2 this special response looks unformatted, so is there a way to make it readable? And is it possible to achive the same behaviour like the putty client, so I can refresh the continuous output in my textarea field?

I know it's hard to describe.
Therefore I made two screenshots, one of Putty and one of the console.log() with ssh2.

Can someone please help me?
Many thanks in advanced. :)

Putty: https://imgur.com/SvmSTfr
SSH2 - Console.log(): https://imgur.com/Xg6zyFz

**Comment by mscdex** [comment]
`console.log()` works with ANSI escape sequences just fine, but whatever is reading the output has to support them. In a terminal this works fine, but it appears you might be using some sort of IDE to read the output and the IDE may not support interpreting ANSI escape sequences.

If you're sending the output as-is to a browser, one easy solution would be to use a library like [xterm.js](https://github.com/xtermjs/xterm.js/) to emulate a terminal and interpret/render the output as you expect.

**Comment by borsTiHD** [comment]
Wow, thank you for your quick response.
And amazing that you understand my nonesense. :D

Yeah, I just write the exact output into an textarea and it looks like my console.log() output:
```
(...)
on('data', (data) => {
    document.getElementById(this.guiID).value += data
})
(...)
```

By the way, forgot to mention, I'm using Electron, but I guess it doesn't make much difference?
Thank you so much for the tip with xterm.js, I think this will be my solution. :)

**Comment by mscdex** [comment]
In general writing data in that way (blindly appending) can break output depending on how the `data` is being delivered and if multibyte characters exist in the `data` as you might have some bytes of a character in one chunk and more in the next chunk.
