### ISSUE TITLE
Question: Is there a way to check if the client is connected?

### ISSUE THREAD

**Issue by abmusse** [mscdex/ssh2#878]
```js
 const { Client } = require('ssh2');
 const client = new Client();

  // subscribe for events
  client.on('error', (error) => {
      console.log('SSH CLIENT ERROR: ', error);
      client.end();
  });

  client.on('ready', () => {
    if (verbose) {
      console.log('SSH Client is ready');
    }
    client.exec('some command', (error, stream) => {
           if (error) {
              client.emit('error', error);
              return;
          }

       ...
   }); 

 client.connect({ host: 'myhost', user: 'myuser', password: 'mypassword'});
```

In the case above `client.connect` will fail and an error will be emitted.

The error event handler will log the error and call `client.end()` since the client is not connected this should no op.

How do you check if a client is connected?

**Comment by mscdex** [comment]
There is no public API at the moment.

**Comment by abmusse** [comment]
Ok whats the proper way to clean up the client if an error is encountered.

Should I call `client.destory()`  in my error handler?

I need to push return the error object back up to the user.

**Comment by mscdex** [comment]
If you see an `'error'` event on the client, the connection is closed in just about all cases I can think of, so there isn't anything extra that needs to really be done.

**Comment by abmusse** [comment]
Nice so I do not need to worry about ending or destroying the client.

Thanks for the feedback.
