### ISSUE TITLE
Unsupported HMAC 

### ISSUE THREAD

**Issue by VirenVerma** [mscdex/ssh2#879]
```
13th Mar 2020 - 7:40:00 PM :: DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
13th Mar 2020 - 7:40:00 PM :: DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
13th Mar 2020 - 7:40:00 PM :: DEBUG: No matching Client->Server HMAC algorithm
```

Is there way to introduce more HMAC's?

**Comment by mscdex** [comment]
Sure, by adding proper support for them (this means more than simply adding the name to the list). You should also be able to avoid this issue with a matching authenticated mode cipher like aes-gcm.

**Comment by VirenVerma** [comment]
> Sure, by adding proper support for them (this means more than simply adding the name to the list). You should also be able to avoid this issue by using a matching authenticated mode cipher like aes-gcm.

Thanks. Unfortunately aes-gcm is not an option on the server I am trying to connect to. Could you guide as to how to add support for it? I would appreciate it.

**Comment by mscdex** [comment]
There's not really a guide per se, but the file you'd be editing would be lib/ssh.js in the `ssh2-streams` project. Since the algorithms listed are designed by the OpenSSH folks, you'd have to read up on the algorithm descriptions.

IIRC these "-etm" algorithms require deeper changes to packet handling in general because I believe they not only affect MAC calculations but they also change how packets are parsed.

**Comment by khayalan-mathew** [comment]
Running into the same issue, although for me its possible to switch to something like aes-gcm, its still not working
```
DEBUG: (local) Client->Server ciphers: aes128-gcm@openssh.com +0ms
DEBUG: (remote) Client->Server ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr +0ms
DEBUG: Client->Server Cipher: aes128-gcm@openssh.com +0ms
DEBUG: (local) Server->Client ciphers: aes128-gcm@openssh.com +0ms
DEBUG: (remote) Server->Client ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr +0ms
DEBUG: Server->Client Cipher: aes128-gcm@openssh.com +0ms
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-512,hmac-sha2-256 +0ms
DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com +0ms
DEBUG: No matching Client->Server HMAC algorithm +0ms
DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED) +1ms
```
Not sure how to handle the situation?

**Comment by mscdex** [comment]
FWIW `*-etm` HMACs are now supported in v1.0.0.
