### ISSUE TITLE
Uploading with FileZilla hangs after rekey.

### ISSUE THREAD

**Issue by btimby** [mscdex/ssh2#882]
I am having similar issue as:

https://github.com/mscdex/ssh2/issues/856

I am using the latest versions... `ssh2==0.8.9` and `ssh2-streams==0.4.10` with FileZilla 3.46.3...

```
FileZilla Client
----------------

Version:          3.46.3

Build information:
  Compiled for:   x86_64-pc-linux-gnu
  Compiled on:    x86_64-pc-linux-gnu
  Build date:     2020-01-02
  Compiled with:  gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
  Compiler flags: -g -O2 -fdebug-prefix-map=/build/filezilla-NtjK91/filezilla-3.46.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wall

Linked against:
  wxWidgets:      3.0.4
  SQLite:         3.22.0
  GnuTLS:         3.5.18

Operating system:
  Name:           Linux 4.15.0-91-generic x86_64
  Version:        4.15
  CPU features:   sse sse2 sse3 ssse3 sse4.1 sse4.2 avx avx2 aes pclmulqdq rdrnd bmi2 bmi2 adx lm
  Settings dir:   /home/btimby/.config/filezilla/
```

Downloads work fine, rekeying multiple times is not an issue. Uploading hangs on the first rekey at `1,069,563,904` bytes transferred (99% of the time). Rarely the upload will proceed past this point, but die at the next rekey.

I tried the workaround in the above issue

```
      algorithms: {
        kex: ALGORITHMS.KEX,
        kexBuf: ALGORITHMS.KEX_BUF,
        serverHostKey: ALGORITHMS.SERVER_HOST_KEY,
        serverHostKeyBuf: ALGORITHMS.SERVER_HOST_KEY_BUF,
        cipher: ['aes128-ctr'], // ALGORITHMS.CIPHER,
        hmac: ['hmac-sha1'], // ALGORITHMS.HMAC,
        // Disable compression.
        compress: ['none'],
      },
```

To no effect. I also tried the version released just after that issue was resolved (`ssh2==0.8.7` and `ssh2-streams==0.4.8`) to no effect.

Client log:

```
Trace:	Initiating key re-exchange (too much data sent)
Trace:	Doing ECDH key exchange with curve nistp256 and hash SHA-256 (unaccelerated)
Trace:	Initialised AES-256 SDCTR (AES-NI accelerated) outbound encryption
Trace:	Initialised HMAC-SHA-256 (unaccelerated) outbound MAC algorithm
Trace:	Initialised AES-256 SDCTR (AES-NI accelerated) inbound encryption
Trace:	Initialised HMAC-SHA-256 (unaccelerated) inbound MAC algorithm
```

Server log:

```
[117944.391576811] DEBUG: Parser: IN_PACKET
[117944.391576811] DEBUG: Parser: Decrypting
[117944.391576811] DEBUG: Parser: pktLen:3740,padLen:18,remainLen:3728
[117944.391576811] DEBUG: Parser: IN_PACKETDATA
[117944.391576811] DEBUG: Parser: Decrypting
[117944.391576811] DEBUG: Parser: HMAC size:32
[117944.391576811] DEBUG: Parser: IN_PACKETDATAVERIFY
[117944.391576811] DEBUG: Parser: Verifying MAC
[117944.391576811] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[117944.391576811] DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
[117944.391576811] DEBUG[SFTP]: Parser: Request: WRITE
[117944.391576811] DEBUG: Outgoing: Writing CHANNEL_WINDOW_ADJUST (256, 1050432)
[117944.391576811] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[117944.391576811] DEBUG[SFTP]: Outgoing: Writing STATUS
[117975.712900468] DEBUG: Local ident: 'SSH-2.0-SFTP server'
[117977.920379108] DEBUG: Local ident: 'SSH-2.0-SFTP server'
[117980.128364912] DEBUG: Local ident: 'SSH-2.0-SFTP server'
[117982.340449019] DEBUG: Local ident: 'SSH-2.0-SFTP server'
[117984.548375869] DEBUG: Local ident: 'SSH-2.0-SFTP server'
[117986.756308901] DEBUG: Local ident: 'SSH-2.0-SFTP server'
[117988.964400717] DEBUG: Local ident: 'SSH-2.0-SFTP server'
[117939.869790836] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[117944.391576811] DEBUG: Outgoing: Writing ping (GLOBAL_REQUEST: keepalive@openssh.com)
[117944.391576811] DEBUG: Parser: IN_PACKET
[117944.391576811] DEBUG: Parser: Decrypting
[117944.391576811] DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
[117944.391576811] DEBUG: Parser: IN_PACKETDATA
[117944.391576811] DEBUG: Parser: HMAC size:32
[117944.391576811] DEBUG: Parser: IN_PACKETDATAVERIFY
[117944.391576811] DEBUG: Parser: Verifying MAC
[117944.391576811] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[117944.391576811] DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_FAILURE
[117944.391576811] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[117939.869790836] DEBUG: Parser: IN_PACKET
[117939.869790836] DEBUG: Parser: Decrypting
[117939.869790836] DEBUG: Parser: pktLen:12,padLen:10,remainLen:0
[117939.869790836] DEBUG: Parser: IN_PACKETDATA
[117939.869790836] DEBUG: Parser: HMAC size:32
[117939.869790836] DEBUG: Parser: IN_PACKETDATAVERIFY
[117939.869790836] DEBUG: Parser: Verifying MAC
[117939.869790836] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[117939.869790836] DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_FAILURE
[117939.869790836] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
```

I am not sure what else to try.

**Comment by btimby** [comment]
OK, I found the problem.

I think I was misguided. The SFTP server is sending the data over a socket as it is received from the SFTP client. because of a mismatch in speed (downstream link is slower than the link between SFTP server and SFTP client) I was trying to apply backpressure by queuing replies to the SFTP client. Flushing this queue only when the downstream stream emitted ''drain'`.

But this was causing a deadlock, the downstream was awaiting data in order to reach a high water mark and drain. Meanwhile SFTP replies are queued awaiting that drain. The SFTP client is not sending more data, awaiting it's replies in order to finish the rekey.

I fixed this by modifying my code to always send a reply immediately, buffering data as fast as the client can send it. I might re-introduce the queue but with an interval that will flush the reply queue in absence of a drain event just to break the deadlock.

Is there a better way to try and apply backpressure so that the SFTP server does not become a buffer between the SFTP client and downstream?

**Comment by btimby** [comment]
IOW: I got fancy trying to reduce memory usage. Is there a less fancy way to accomplish the same thing? If you don't know or care, you can just close this issue. I will close it sometime tomorrow or report back more info for the sake of other folks googling.

**Comment by btimby** [comment]
![SFTP server as buffer](https://ibin.co/5HaJbkoR7INq.png)

So, this works now, but you can see in the image how memory is gobbled up buffering data from the client. This is about halfway through a 30GB transfer. The memory climbs steadily throughout (the transfer started to the left side of the graph and continued to the right). The dip in transfer and bump in memory usage was at a rekey. The client gets far ahead of the downstream socket.

Is there a way to keep both sides flowing at around the same rate?

**Comment by mscdex** [comment]
I don't really understand the situation/what you're trying to do. Perhaps showing relevant code might help?

**Comment by btimby** [comment]
Sure...

This is my sftpadapter. I have this handling the `WRITE` event on `SFTPStream`.

```javascript
  write(id, hBuf, offs, buffer, callback) {
    // NOTE: we are totally ignoring offset here. Since we are streaming, we can't seek.
    const openFile = this.getOpenHandle(hBuf);

    if (offs !== openFile.bytesRead) {
      // Sanity check, ensure the client is not doing random I/O on the file.
      this.status(id, SFTP.BAD_MESSAGE);
      callback();
    } else {
      // We reply in a callback after the write has been flushed. This should hopefully
      // provide some backpressure.
      openFile.write(id, buffer, (e) => {
        const status = (e) ? SFTP.FAILURE : SFTP.OK;
        this.status(id, status);
        callback();
      });
    }
  }
```

This is the `openFile` class the above writes to.

```javascript
const process = require('process');
const pathlib = require('path');
const { UPLOAD, UPLOAD_BYTES } = require('./metrics');
const logger = require('../logger');


/* Buffers data from the client and sends it to API by write()ing to request stream */
class SFTPOpenReadable {
  constructor(path, username, s) {
    this.path = path;
    this.username = username;
    this.start = process.hrtime();
    this.stream = s;
    this.bytesRead = 0;
    this.end = UPLOAD.startTimer();
    this.drainQueue = [];
    this.stream.on('drain', this._onDrain.bind(this));
  }

  _onDrain() {
    while (this.drainQueue.length) {
      this.drainQueue.shift().call();
    }
  }

  /*
  Called by SFTP server as data arrives from the client.

  Data is written directly to the HTTP request stream. This results
  in a Transfer-Encoding: chunked request.
  */
  write(id, buffer, callback) {
    try {
      this.bytesRead += buffer.byteLength;

      // Don't log every write, just every 5 megabytes.
      if ((this.bytesRead % (1024 ** 2 * 5)) === 0) {
        logger.debug(
          `WRITE(${id}, ${this.path}, ${this.bytesRead}, <data: ${buffer.byteLength}>)`
        );
      }

      const flushed = this.stream.write(buffer);

      if (flushed) {
        callback();
      } else {
        this.drainQueue.push(callback);
      }
    } catch (e) {
      callback(e);
    }
  }

  close(callback) {
    logger.debug(`FTPOpenReadable.close() ${this.bytesRead} bytes written`);

    // End the HTTP request.
    try {
      this.stream.on('response', (res) => {
        let e = null;
        if (res.statusCode !== 200) {
          e = new Error('API request failed.');
        }
        callback(e);
      });
      this.stream.end();
    } catch (e) {
      callback(e);
    }

    const labels = {
      extension: pathlib.extname(this.path),
      username: this.username,
    };

    this.end(labels);
    UPLOAD_BYTES.observe(labels, this.bytesRead);
  }
}


module.exports = {
  SFTPOpenReadable,
};
```

**Comment by btimby** [comment]
The problem is that I am deferring the replies to `write()`. The reason I am trying this is:

https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback

**Comment by mscdex** [comment]
Why not just do `this.stream.write(buffer, callback)` and avoid the whole `drainQueue` thing?

**Comment by btimby** [comment]
The summary is that the SFTP client is too fast and I want to slow it down.

In a normal situation (reading from a socket) that is easy, you just read less frequently and the kernel and TCP/IP slow down the sender. However, since I am reacting to the `WRITE` event, I am not sure how to accomplish this, my attempt was to slow down my SFTP replies (the `SFTP.OK` status message). I deferred the replies until I could flush data out the other side.

When I do this however, the server deadlocks when a rekey is requested by the client.

**Comment by btimby** [comment]
I think I did that initially, but I got an error from node about too many event listeners. So I consolidated them in a queue.

**Comment by btimby** [comment]
OK, using the callback directly also deadlocks. It seems like any delay in responding to a write will cause a deadlock at rekey.

**Comment by btimby** [comment]
I think it has something to do with outstanding replies at the time the rekey is requested. I don't know enough about SFTP / SSH, but if I modify the code to reply immediately, it works, but it fills my memory (node buffers the writes).

**Comment by btimby** [comment]
I also tried installing a `setInterval()` to drain the reply queue every 100ms, I hoped that would break the deadlock, but it still deadlocked. Anything but immediate replies deadlocks.

**Comment by btimby** [comment]
As an aside, I do the exact same thing for downloads. I have to buffer the `read()` calls from the SFTP client and respond to them as data arrives (more slowly) from my socket. This works fine even over multiple rekeys. It is just uploading that is giving me issues.

**Comment by btimby** [comment]
I think I have everything working now. Thank you for your help. I am going to close this issue.
