### ISSUE TITLE
No supported authentication methods available?

### ISSUE THREAD

**Issue by Panics11** [mscdex/ssh2#883]
Hello,

i´m trying to get the example server to run to tinker a bit but every time i try to connect i get this message: "No supported authentication methods available (server sent: )".
Am i missing something here? 
It is the example server from the Readme and i launching it on windows as i am planning to use it on 
a windows server.
I am using Putty to connect to it directly local on my pc.. 
Hope i am not just stupid as hell and someone could help me with this :'D

**Comment by mscdex** [comment]
Some clients may rely on the list of allowable authentication methods. You can pass this list to `reject()`. For example: `ctx.reject(['publickey'])`.

**Comment by Panics11** [comment]
Ahh okay thank you this worked so far but now i am getting "Server refused to start a shell/command" 
I am fairly new to SSH communication so sorry if i am just dumb..

**Comment by mscdex** [comment]
The server examples don't show interactive sessions. For that, you'll need to listen for the `'shell'` event on the session object instead of `'exec'`.
