### ISSUE TITLE
Getting  Digest method not supported in SSH2 handshake

### ISSUE THREAD

**Issue by sker65** [mscdex/ssh2#886]
I'm using ssh2 & ssh2stream for in implemetation of a sftp server. From time to time I get :

Error: Digest method not supported at new Hash (internal/crypto/hash.js:48:19) at Object.createHash (crypto.js:109:10) at KEXDH_REPLY (/opt/app/node_modules/ssh2-streams/lib/ssh.js:4740:21) at onKEXDH_INIT (/opt/app/node_modules/ssh2-streams/lib/ssh.js:2584:3) at SSH2Stream.<anonymous> (/opt/app/node_modules/ssh2-streams/lib/ssh.js:214:41) at SSH2Stream.emit (events.js:311:20) at parse_KEX (/opt/app/node_modules/ssh2-streams/lib/ssh.js:3930:12) at parsePacket (/opt/app/node_modules/ssh2-streams/lib/ssh.js:3770:12) at SSH2Stream._transform (/opt/app/node_modules/ssh2-streams/lib/ssh.js:701:13) at SSH2Stream.Transform._read (_stream_transform.js:191:10)

Any idea how to catch this?

**Comment by mscdex** [comment]
What node version are you using?

**Comment by mscdex** [comment]
Also what algorithms are negotiated? You can see this by viewing the output when setting `debug: console.log` in the connection config object.
