### ISSUE TITLE
Sending commands doesn't work

### ISSUE THREAD

**Issue by cifer1337** [mscdex/ssh2#887]
Hi,

i don't know if this is a problem from this Nodejs SSH2 Client or from the SSH Server but when i try to send a command via conn.exec(command, callback) i allways get the following response.

STDOUT: >-c radio status
Syntax error!

Sure the Syntax error message comes from the server, but why is there >-c before my command?

**Comment by mscdex** [comment]
Your guess is as good as mine. What you get through the stdout and stderr streams is what's sent by the server.
