### ISSUE TITLE
Suggestion: Add support for Win32-OpenSSH ssh-agent

### ISSUE THREAD

**Issue by rbuckton** [mscdex/ssh2#892]
Currently, the `ssh2` package only seems to support either Pageant or Cygwin SSH agents, but does not seem to support the OpenSSH implementation for Windows (https://github.com/PowerShell/openssh-portable). From what I understand, access to the running SSH agent on Windows using OpenSSH portal is accomplished via named pipes (the named pipe being `\.\pipe\openssh-ssh-agent`):

- https://github.com/PowerShell/Win32-OpenSSH/issues/1136#issuecomment-382063717
- https://github.com/PowerShell/Win32-OpenSSH/issues/1136#issuecomment-500549297

**Comment by mscdex** [comment]
Support for pipe paths for `agent` has been supported [since v0.8.0](https://github.com/mscdex/ssh2/commit/14aa624fe09a406b0c9306349133858a2cddf63c). I think you're missing an extra slash at the beginning.
