### ISSUE TITLE
How I can use a private key w/ passphase using a PKCS8 private key?

### ISSUE THREAD

**Issue by cgomestw** [mscdex/ssh2#893]
I have this error when I use a key PKS8: `Error: connect: Cannot parse privateKey: Unsupported key format`. But when a generate a key with PKS1 (PEM, old format) works with passphase. 

For security reasons, we need to use a key with AES256-CBC and PKS#8.

Can you help me? I've been trying for more than 2 days not to switch to python (it works).

I created a Issue [here](https://github.com/theophilusx/ssh2-sftp-client/issues/235) too, but this lib uses ssh2 to make sftp connection.

**Comment by mscdex** [comment]
`ssh2` only supports private keys generated via `ssh-keygen` or PuTTYgen, all of which support optional encryption.

**Comment by cgomestw** [comment]
Maybe this fix can resolve? I had the same error: https://github.com/mscdex/ssh2-streams/commit/8de25ea69a76dbf1c34e578e42571e97de926ac0

**Comment by mscdex** [comment]
If this is still an issue with `ssh2` v1.0.0 let me know and I can reopen this.

**Comment by SelfhostedPro** [comment]
Hey, not sure if it'd be better to open a new issue but I'm getting the same error.
```js
        const { publicKey, privateKey } = generateKeyPairSync('rsa', {
            modulusLength: 4096,
            publicKeyEncoding: {
                type: 'spki',
                format: 'pem'
            },
            privateKeyEncoding: {
                type: 'pkcs8',
                format: 'pem',
                cipher: 'aes-256-cbc',
                passphrase: passphrase,
            }
        })
        privateKey.toString()
```
It looks like it's in the correct format but obviously is having an issue. Have you considered adding documentation on generating a keypair with crypto for use with ssh2? It would be very beneficial to be able to generate keys on the fly.

**Comment by mscdex** [comment]
@SelfhostedPro OpenSSH (and thus `ssh2`) uses *PKCS1* for RSA with OpenSSH's older key format.
