### ISSUE TITLE
Password provided with a Keyboard Auth request terminates immediately after ready

### ISSUE THREAD

**Issue by joehal9000** [mscdex/ssh2#895]
## Summary
I am trying to connect to a server that has keyboard-interactive authentication. But when I provide the password field in Client.connect(), the session terminates as soon as I successfully log in. If I remove the password field, I am able to execute commands on the remote server.

## Environment
- OS: Windows 10
- Using Powershell
- Node: v14.3.0
- NPM: 6.14.5
- ssh2: 0.8.9
- Client SSH: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
- Remote Server: Linux 
- Remote Server Auth: Keyboard authentication: requests password, and then a DUO prompt

## Expected Behavior

Execute commands after successfully logging into a remote server. 

### Code Sample
```javascript
'use strict'
const Client = require('ssh2').Client; //version 0.8.9
const readline = require('readline'); //node v14 package

var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false
});

var conn = new Client();

conn.on('ready', () => {
    console.log('Client :: ready');
    conn.exec('uptime', function (err, stream) {
        if (err) throw err;
        stream.on('close', function (code, signal) {
            console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
            conn.end();
        }).on('data', function (data) {
            console.log('STDOUT: ' + data);
        }).stderr.on('data', function (data) {
            console.log('STDERR: ' + data);
        });
    });
}).on('keyboard-interactive', (name, instructions, lang, prompts, finish) => {
    console.log(prompts[0]['prompt']);
    //USE ONCE...if using rl.on, response gets sent twice and stalls
    rl.once('line', (line) => {
        finish([line])
    });
}).on('error', (err) => {
    console.log(err);
    conn.end();
}).on('end', () => {
    console.log("Client :: END")
}).on('close', () => {
    console.log("Client :: Close");
    process.exit();
}).connect({
    username: USERNAME,
    host: HOST_WITH_KEYBOARD_AUTH,
    debug: (debug) => { process.stderr.write(debug + "\n"); },
    password: PASSWORD, //this causes conn.exec to never run 
    tryKeyboard: true
})
```
### Without Password Field
```javascript
...
}).connect({
    username: USERNAME,
    host: HOST_WITH_KEYBOARD_AUTH,
    debug: (debug) => { process.stderr.write(debug + "\n"); },
    // password: PASSWORD, //this causes conn.exec to never run 
    tryKeyboard: true
})
```
Output:
```
Client :: ready
STDOUT:  19:12:29 up 75 days,  5:01, 157 users,  load average: 0.29, 0.49, 0.82

Stream :: close :: code: 0, signal: undefined
Client :: END
Client :: Close
```

### With Password Field
```javascript
...
}).connect({
    username: USERNAME,
    host: HOST_WITH_KEYBOARD_AUTH,
    debug: (debug) => { process.stderr.write(debug + "\n"); },
    password: PASSWORD, //this causes conn.exec to never run 
    tryKeyboard: true
})
```

Output:
```
Client :: ready
Client :: END
Client :: Close
```

### SSH Debug
Both ssh debug logs are [here](https://gist.github.com/joehal9000/cfdbbe9408d5ea2393e58f913ed43dab)

## Reason
Users of my app need to able to log into any server, whether they are authenticated via keyboard-interactive or simple password authorization. Currently, the app attempts a connection twice, once without a password and another time with a password.

**Comment by mscdex** [comment]
That's the complete debug output for the password case? That doesn't make sense why the server would disconnect abruptly and immediately after a successful authentication.

If you have access to the server, is there any additional information in the syslog/auth.log/etc. from the ssh server process?

**Comment by mscdex** [comment]
[Someone else awhile back](https://github.com/mscdex/ssh2/issues/175) had the same issue with Duo integration and I'm also seeing similar issues reported by others outside of node/`ssh2`. My guess is this has to do with the PAM configuration on the server or something. Either way I don't think there is anything `ssh2` can do.

**Comment by joehal9000** [comment]
Thank you for your quick response. I don't have root access on the server, so I can't see the auth logs. 
Both of the provided logs are complete though. The server just disconnects immediately. Thanks anyways.

**Comment by mscdex** [comment]
I'm curious... if you try connecting with OpenSSH instead of `ssh2`, does the same issue occur? Try with:

```sh
ssh -vvv -o PreferredAuthentications=password,keyboard-interactive user@host
```

That should force OpenSSH to attempt password first and then keyboard-interactive, just like `ssh2` is doing in the problematic case.

**Comment by mscdex** [comment]
If that *does* work with OpenSSH, please post the resulting output (removing hostname and/or any other sensitive information) as it would be interesting to see what's happening.

**Comment by joehal9000** [comment]
I tried it using the system ssh command you gave, and it quit immediately after connecting, just like the ssh2 module. I attached the file [open_ssh.log](https://gist.github.com/joehal9000/cfdbbe9408d5ea2393e58f913ed43dab) to the gist. 

I changed the `client.js` code so that it tries keyboard authentication first and then password, and the ssh2 code successfully connects to the problematic server. For completeness, the ssh2 log file is also in the gist as  `ssh2_with_pass_and_keyboard_auth_first.log`

**Comment by mscdex** [comment]
FWIW you can also pass in your own `authHandler` function that determines the authentication method order. You will still need to set the appropriate authentication-related config properties though (e.g. `password`, `tryKeyboard`, etc.).

**Comment by psaji1** [comment]
I have a similar issue with keyboard-interactive SFTP connection. 
I am using ssh2 npm for connection with NestJS
everything works fine when running from app and cron. 
Now, I created a CLI script. Executing the script like this` npm run execute process_report`
Here the connection fails. It never gets into 'keyboard-interactive' event. 
Any help is greatly appreciated.
