### ISSUE TITLE
How to send commands with shell in a windows cmd with ssh2

### ISSUE THREAD

**Issue by KentLeong** [mscdex/ssh2#897]
when I run 

```
client.shell((err,stream) => {
  stream.write("cd ..\n");
  stream.on("data", data => {
    console.log(data.toString());
  })
})
```

I can expect this to work if I ssh into a linux os, but on a windows os, it does not work. It seems to ignore the \n which executes the command. So I'm wondering how you're suppose to execute these commands in a windows os.

**Comment by mscdex** [comment]
In general the end-of-line sequence is `\r\n` on Windows, so the server may be expecting that.

**Comment by KentLeong** [comment]
Thank you
