### ISSUE TITLE
Node's URL library parses out the username as username%40internal.domain, but ssh2 does not handle it correctly.

### ISSUE THREAD

**Issue by netaskd** [mscdex/ssh2#898]
Initially the issue has been described [here](https://github.com/microsoft/vscode-docker/issues/2044).

The problem is in using username like `username@internal.domain` in ssh connection string like
`ssh://username@internal.domain@linux.host`

In this case, connection to `linux.host` will never successful because username converts to `username%40internal.domain` and I see in /var/log/secure logs, on remote side, a string like:
```sshd[116842]: input_userauth_request: invalid user username%40internal.domain [preauth]```

https://github.com/microsoft/vscode-docker/issues/2044#issuecomment-639472957:
> This is an issue in the [`ssh2`](https://www.npmjs.com/package/ssh2) Node package. In [`docker-modem`](https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L37), Node's [`URL`](https://nodejs.org/api/url.html) library parses out the username as `username%40internal.domain`, but `ssh2` does not handle it correctly.

**Comment by mscdex** [comment]
This isn't an `ssh2` issue. `ssh2` passes the username as-is, so if you set your username as `'username%40internal.domain'`, then that's exactly what the server will see.
