### ISSUE TITLE
How to limit cfg.algorithms.kex to {ecdh-sha2-nistp256} only?

### ISSUE THREAD

**Issue by caozhaohong** [mscdex/ssh2#900]
Dear ALL:

according to https://github.com/mscdex/ssh2/blob/master/lib/client.js->Line 126->algoList = cfg.algorithms.kex, we can identify the kex algorithms.

The default algorithms kex is:
ecdh-sha2-nistp256 ,
ecdh-sha2-nistp384 ,
ecdh-sha2-nistp521 ,
diffie-hellman-group-exchange-sha256 ,
diffie-hellman-group-exchange-sha1 ,
diffie-hellman-group14-sha1 ,
diffie-hellman-group1-sha1 

But we want to use ecdh-sha2-nistp256 only, and fobid all other ones( for eg. forbid ecdh-sha2-nistp384 , forbid diffie-hellman-group1-sha1).

How can I set the 'cfg.algorithms.kex'? can you share us some example?

we are client.

**Comment by mscdex** [comment]
You set it to an array of one or more names as described in the documentation:

>  * **algorithms** - _object_ - This option allows you to explicitly override the default transport layer algorithms used for the connection. Each value must be an array of valid algorithms for that category. The order of the algorithms in the arrays are important, with the most favorable being first. For a list of valid and default algorithm names, please review the documentation for the version of `ssh2-streams` used by this module. Valid keys:
>
>      * **kex** - _array_ - Key exchange algorithms.
>
>      * **cipher** - _array_ - Ciphers.
>
>      * **serverHostKey** - _array_ - Server host key formats.
>
>      * **hmac** - _array_ - (H)MAC algorithms.
>
>      * **compress** - _array_ - Compression algorithms.

**Comment by caozhaohong** [comment]
Thank u
