### ISSUE TITLE
This dependency was not found:  * dns in ./node_modules/ssh2/lib/client.js

### ISSUE THREAD

**Issue by sanjitkung** [mscdex/ssh2#901]
When I compile my electron app. I get this error

```
This dependency was not found:

* dns in ./node_modules/ssh2/lib/client.js
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```

How can I resolve this! Please help!

**Comment by mscdex** [comment]
You're better off asking on the Electron issue tracker as `dns` is a module built into node (and Electron) so there shouldn't be a problem with that.

As for the other errors, that's outside the scope of this module as well.
