### ISSUE TITLE
Cant connect to Huawei NE20 using netconf - KEY_EXCHANGE_FAILED

### ISSUE THREAD

**Issue by diorgesl** [mscdex/ssh2#904]
<pre>DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 1xx.1xx.0.129 on port 830 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-1.99--'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:644,padLen:7,remainLen:640
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha1,sm2kep-sha2-nistp256
DEBUG: KEX algorithm: ecdh-sha2-nistp256
DEBUG: (local) Host key formats: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa
DEBUG: (remote) Host key formats: ssh-dss,ssh-rsa,ecdsa-sha2-nistp521
DEBUG: Host key format: ecdsa-sha2-nistp521
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: AEAD_AES_256_GCM,aes256-gcm@openssh.com,AEAD_AES_128_GCM,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes128-cbc,3des-cbc
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: AEAD_AES_256_GCM,aes256-gcm@openssh.com,AEAD_AES_128_GCM,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes128-cbc,3des-cbc
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-96
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-96
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Server->Client compression algorithms: none,zlib
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXECDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:428,padLen:8,remainLen:424
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Signature verification failed
DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)</pre>

I'm trying to connect to a Huawei NE20 (Router) with netconf, I have success with NE40.

But its just with ssh2, because on linux terminal using:
`ssh netconf@1xx.1xx.0.129 -p 830 -s netconf`

I can connect normaly and receive the hello message.

I tried to reset the RSA key on router, but no success! FYI: on windows to connect to this device I have to force RSA algorithm, is there a way to this with ssh2?

Thank you

**Comment by mscdex** [comment]
> DEBUG: Remote ident: 'SSH-1.99--'

Was this line altered before it was posted? It's a bit strange to see an SSH ident string that bare...

**Comment by shangchengxiang** [comment]
May I ask a question? 
I get the figers from cmd and hostVerifier . But they are different.  
figer from cmd:
ssh-keygen -q -l -f .ssh/known_hosts -F hostname
hostname ECDSA SHA256:YuukV3vH+XwiDNtp62MvZsDr0XeIOmzNKOyPW/kLkQk
figer from  hostVerifier :
693994cdf1f576fea93ea184d668fa1bdb20d650dc78a44206bd4a0cf8fa7298
So if change the format to compare them?

**Comment by shangchengxiang** [comment]
May I ask a question? 
I get the figers from cmd and hostVerifier . But they are different.  
figer from cmd:
ssh-keygen -q -l -f .ssh/known_hosts -F hostname
hostname ECDSA SHA256:YuukV3vH+XwiDNtp62MvZsDr0XeIOmzNKOyPW/kLkQk
figer from  hostVerifier :
693994cdf1f576fea93ea184d668fa1bdb20d650dc78a44206bd4a0cf8fa7298
So if change the format to compare them?

**Comment by mscdex** [comment]
Algorithms can be forced via an `algorithms` object in your connection config object.

@shangchengxiang ssh-keygen is probably giving you the SHA256 hash of the key in base64. To do that with `ssh2` v0.8.x, you would need to make sure you have `hostHash` set to `'sha256'` and then convert the hex to base64. To do that with the current `ssh2` master branch, you can omit `hostHash` and you will get the raw key passed to your `hostVerifier` function, at which point you can use the `crypto` module manually to hash it directly to base64.
