### ISSUE TITLE
Execute Command More than one

### ISSUE THREAD

**Issue by abdrozak20** [mscdex/ssh2#905]
I want to execute command more than one..

this is my code
![image](https://user-images.githubusercontent.com/33420123/85839260-e7e15a00-b7c4-11ea-9366-29413fff15af.png)

i hope my code execute like this
![image](https://user-images.githubusercontent.com/33420123/85839497-33940380-b7c5-11ea-93ee-2f59b556000f.png)

Thanks for helping me

**Comment by mofux** [comment]
Your code looks good in general and should work, but your definition of `cmds` is wrong. I think it should be an array of command strings like this:
```javascript
var cmds = ['system', 'aaa'];
```

Please note that this is a bug tracker. You should consider asking such questions on user help forums like StackOverflow next time 😉
