### ISSUE TITLE
Which port segment will be listened by ssh2?

### ISSUE THREAD

**Issue by caozhaohong** [mscdex/ssh2#911]
Dear team:

     Background:

       We developed a VS Code extension named 'Extension1'.

      In the 'Extension1', we use 'mscdex/ssh2'(ssh client) to connect a ssh server.

      Question:  which port segment will possibly be listened by ssh2? for eg. (1024, 65505] ? or some other segment ?

      Thanks.

**Comment by mscdex** [comment]
I don't understand your question. Perhaps you could share the relevant code that uses `ssh2`?
