### ISSUE TITLE
SFTP readdir works in total commander, but not in filezilla

### ISSUE THREAD

**Issue by AlexandraK** [mscdex/ssh2#914]
In Total commander with sftp plugin, readdir seems to work fine.

But in Filezilla it fails with an error `unable to understand SFTP response packet from server: request ID mismatch`

I'm not sure if it's related, but I noticed that Filezilla issues multiple readdir requests at the same time (it does not wait for one to finish).

This is my readdir request handler:
```

    READDIR: async(reqid, handle) => {
      const data = handles.get(handle);    
      if(!data)
        return stream.status(reqid, STATUS_CODE.FAILURE, 'Invalid handle');

      if(data.listSent)
        return stream.status(reqid, STATUS_CODE.EOF);

      data.listSent = true;      
      const files = await fs.readdir(data.target);
      let names = [];
      for(const file of files){       
          const {mode, gid, uid, size, atime, mtime} = await fs.stat(path.join(data.target, file));
          names.push({
            filename: file,
            longname: file,
            attrs: {mode, gid, uid, size, atime, mtime},
          });
      }

      stream.name(reqid, names);    
  },
```

Looking at the log I see that Filezilla uses the same request ID at start for several commands, and only increases it after the 2nd readdir command:

REALPATH-256
REALPATH-256
OPENDIR-256
READDIR-256
READDIR-257
READDIR-258
READDIR-259

Could this be an issue with the Filezilla client? Coz it's weird, it's a pretty popular client :)

**Comment by AlexandraK** [comment]
Ok, after more tests I noticed that if I remove async/await from my handler and do fs sync calls instead, it works...
So I guess the issue is that ssh2 does not like async handlers?

**Comment by mscdex** [comment]
What is `fs` assigned to before that code?

**Comment by AlexandraK** [comment]
`fs` is the fs-extra module.

      const fs = require('fs-extra');

it's a drop-in replacement for the internal fs module that returns promises for async methods.

**Comment by mscdex** [comment]
`ssh2` does not care whether responses to requests are completed asynchronously or not. It just calls the request type implementations like a normal function and lets the implementation send a response whenever.

**Comment by AlexandraK** [comment]
If you want to test it, I can put here the entire server code, it's not big and it's really simple

**Comment by AlexandraK** [comment]
This seems related: https://forum.filezilla-project.org/viewtopic.php?t=49236
I think that Filezilla assigns the same request ID to different requests thinking that responses will come in the same order.
But in ssh2 when handling these requests in async mode, there is no guarantee about the order they complete

**Comment by schantaraud** [comment]
Here's a solution that worked for me:

```js
var cmdQueue = Promise.resolve();

for (const command in sftpCommands) {
  sftpStream.on(command, (...args) => {
    cmdQueue = cmdQueue.then(() => processCommand(command, ...args));
  });
}
```

**Comment by kolban-google** [comment]
I'm running into the same puzzle as @AlexandraK  ... @schantaraud ...  that is some elegant code ... did you come up with that?  If I'm reading it correctly, it appears to serialize requests.   Although you didn't state, I think that processCommand has to return a Promise that the command it is processing will be resolved.

**Comment by mscdex** [comment]
Ultimately I see this is a bug on FileZilla's side, as the [SFTPv3 RFC states](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#section-6.1):

>    There are no restrictions on the order in which responses to
   outstanding requests are delivered to the client, except that the
   server must ensure fairness in the sense that processing of no
   request will be indefinitely delayed even if the client is sending
   other requests so that there are multiple outstanding requests all
   the time.

I'm not convinced it's worthwhile to try to add a hack to workaround an implementation-specific bug like this, especially for an implementation that is arguably less common. Additionally I've never seen any other SFTP implementation exhibit this kind of behavior.

**Comment by kolban-google** [comment]
@mscdex .... I didn't see an email address for you, so hopefully this tag finds you.  No question here ... just a HUGE thank you for your SSH2 work.  I used this with a project to access Google Cloud Storage via SFTP and wrote an article on it here ...

https://medium.com/@kolban1/sftp-access-to-google-cloud-storage-43ffd6134b0e

Link to SSH2 included.  Again THANK YOU ... code and docs were GREAT and the community appreciates you.

Neil

kolban@google.com
