### ISSUE TITLE
When starting an interactive shell session, how to dynamically execute commands instead of using an array of commands?

### ISSUE THREAD

**Issue by funjobs** [mscdex/ssh2#915]
In the case of starting an interactive shell session, I want to dynamically send commands to the stream. I have tried a lot, but it doesn’t seem to work.

**Comment by mscdex** [comment]
I don't understand what you're asking. You can send whatever input to the shell's stdin at any time, just as if it had been typed interactively.

**Comment by funjobs** [comment]
@mscdex Is there a demo or related documents?

**Comment by funjobs** [comment]
@mscdex In this way, you may understand: how to pass the command entered by xtermjs to the shell?

**Comment by mscdex** [comment]
xtermjs is a frontend thing, so typically you'd have some way of writing to the interactive shell stream. It's just a matter of passing the input on.

[Here's an example](https://stackoverflow.com/questions/38689707/connecting-to-remote-ssh-server-via-node-js-html5-console) I wrote awhile back that may/may not be helpful.
