### ISSUE TITLE
The shell session using ssh2 is whether it is possible to save the stream returned by conn.shell. Always use the same stream for an ip instead of creating a client and reconnecting to send commands every time?

### ISSUE THREAD

**Issue by funjobs** [mscdex/ssh2#917]
I hope it is possible to send cmd multiple times for one ip instead of multiple cmd at once. What do I need to do?

**Comment by funjobs** [comment]
Where can I find more detailed documentation about SSH2? The documentation in README.md in github seems a bit simple. I want to find some more detailed usage documents.

**Comment by mscdex** [comment]
What you're asking for is really outside the scope of the project. General programming/design questions are better suited for places like [stackoverflow.com](https://stackoverflow.com) or perhaps [nodejs/help](https://github.com/nodejs/help/issues).
