### ISSUE TITLE
Making the server more resilient against errors.

### ISSUE THREAD

**Issue by xMarkusSpringerx** [mscdex/ssh2#923]
Hey, how is it possible to make the server more resilient when an error occurs? 
Even with implementing the listeners for errors this doesn't work that well. I know Node is single threaded and stuff but still if there are any errors even from the server itself, how can you handle them? I don't want the process to die here.

```
}).listen(Settings.PORT, '0.0.0.0', () => {
    logger.info('Listening on port ' + server.address().port);
}).on('error', (e) => {
    if (e) {
        logger.error(`${e.stack || e}`);
    }
});
```
Currently I have it like this. But what I want to achieve is, that for any error which can occur inside the app or the SSH2 server it gets properly handled, a log message gets written but the server just doesn't die.

**Comment by mscdex** [comment]
All of the server errors will get emitted as `'error'` events and as long as you have a handler for those events, that should be fine. For errors that can be determined immediately (e.g. user input errors), you can use try-catch statements. Any errors occurring outside of `ssh2` is beyond the scope of this project.

Is there something specifically you're running into that can't be handled?

**Comment by xMarkusSpringerx** [comment]
https://gist.github.com/xMarkusSpringerx/ba95a96da05f99480681439dc77268fc

I created a gist here. This is an overview how my full implementation looks like. But the server still dies on some errors. Couldn't reproduce it locally but on production installation this error pops  up sometimes:

```
throw er; // Unhandled 'error' event
```
But there is no additional error message.

**Comment by mscdex** [comment]
There should be a stack trace at least if it's crashing the process. Out of curiosity, what node version are you using in production? Is it different than what you're using locally?

The only real issue I see with the gist you posted is that you've put your `'ready'` handler inside the `'authentication'` handler, which will cause handlers to be called multiple times if there are multiple authentication attempts.
