### ISSUE TITLE
Can lrzsz be used?

### ISSUE THREAD

**Issue by funjobs** [mscdex/ssh2#924]
How to use lrzsz command in SSH2?

**Comment by funjobs** [comment]
In addition, is there any way to get the current file path?

**Comment by mscdex** [comment]
Any command can be used.

**Comment by funjobs** [comment]
@mscdex How to determine that the data returned by the server is the Zmodem protocol?

**Comment by mscdex** [comment]
> @mscdex How to determine that the data returned by the server is the Zmodem protocol?

That's beyond the scope of this project.
