### ISSUE TITLE
createWriteStream with content from parameter

### ISSUE THREAD

**Issue by diazgilberto** [mscdex/ssh2#926]
I'm trying to upload a file to an sftp server. My connection is working just fine. My issue is on creating the write stream and making it work without errors. If I read the content from `fs.createReadStream(...)` and then `readStream.pipe(uploadStream)` the code works just fine. However,  my content is coming as the parameter. If I don't use the `readStream(...)` but instead `uploadStream.write(contentFile)`, the file is not uploaded and I don't get any errors. If I add a `{ flags: "a" }` to `uploadStream = ...` then the file gets uploaded but it throws and error at the same time.
```
  moveFile: function(contentFile) {
    const conn = new Client()
    conn.on("ready", () => {
      conn.sftp((err, sftp) => {
        if (err) throw err
          const fs = require("fs")
          console.log(ediFile)
          // const readStream = fs.createReadStream("path/to/file")
          // const uploadStream = sftp.createWriteStream(`${this.outFolder}/fileName.txt`)
          const uploadStream = sftp.createWriteStream(`${this.outFolder}/fileName.txt`, { flags: "a" })
          uploadStream.on("close", () => {
            console.log(":::: File uploaded successfully ::::")
          })
          uploadStream.on("end", () => {
            console.log(":::: SFTP Connection Closed ::::")
            conn.close()
          })
          uploadStream.on("error", (err) => {
            console.log(":::: ERROR ::::", err)
          })
          uploadStream.write(contentFile)
          // readStream.pipe(uploadStream)

        })
    }).connect(this.connSettings)
  }
```
```
Error: Cannot find message [/dirtest01/CMS-Modified/fileName.edi]
    at SFTPStream._transform (/Users/gdiaz/workspace/thor/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:191:10)
    at SFTPStream._read (/Users/gdiaz/workspace/thor/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at SFTPStream.Writable.write (_stream_writable.js:316:11)
    at Channel.ondata (_stream_readable.js:714:22)
    at Channel.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
Emitted 'error' event on WriteStream instance at:
    at /Users/gdiaz/workspace/thor/node_modules/ssh2-streams/lib/sftp.js:3011:22
    at SFTPStream._transform (/Users/gdiaz/workspace/thor/node_modules/ssh2-streams/lib/sftp.js:417:17)
    at SFTPStream.Transform._read (_stream_transform.js:191:10)
    [... lines matching original stack trace ...]
    at Channel.emit (events.js:311:20) {
  code: 4,
  lang: ''
}
```

**Comment by mscdex** [comment]
You need to end the writable stream to tell the server there is no more data to send. Replace `uploadStream.write()` with `uploadStream.end()`.

**Comment by diazgilberto** [comment]
> You need to end the writable stream to tell the server there is no more data to send. Replace `uploadStream.write()` with `uploadStream.end()`.

`uploadStream.end(content)` did it. Thanks so much for your prompt response.

**Comment by diazgilberto** [comment]
We don't have a client event `success` [here](https://www.npmjs.com/package/ssh2#client-events). How I know if the upload was successful?

* `client.on("end") // connection got disconnected`
* `client.on("close") // connection closed` interesting is that this code gets triggered with uploadStream.end(content). It seems like `close` even is a graceful disconnection and `end` is an undesired disconnection.
* `client.on("error") // catching errors`
* `client.on("success") // ???`

**Comment by mscdex** [comment]
`uploadStream` is your file upload stream, so that is what you'd want to listen for events on to know when the upload has finished. All typical writable stream events are available, so most likely you'd listen for either `'close'` (the file is actually closed) or `'finish'` at the very least (the last chunk has been written but the file is not closed yet).
