### ISSUE TITLE
Using a readStream in server read request

### ISSUE THREAD

**Issue by steveswallow** [mscdex/ssh2#930]
I'm having a little trouble trying to figure out how to use a read stream to fulfill read requests using the sftp server I've implemented. Excuse me if this has already been asked, but I couldn't seam to find it. As a workaround I could stream the file to a local tmp and use sync file read, but it would be far faster to stream it.

Basically, if the read stream runs out of buffer, it needs to refill the buffer and continue. In that time a bunch of requests are coming in (i've tried returning true and false, not sure what the appropriate action would be if the stream isn't ready).

I can get it to read the entire file, and call EOF after, but it never finishes downloading (but is at 100%).

I can give you some pseudo code examples if you are not following.

**Comment by mscdex** [comment]
I think I'd need to see a simple example of what you're trying to accomplish.

**Comment by steveswallow** [comment]
Here is a simplified example. I have used a queue to send data requests back, which almost works (but just stops at 100%). The readStream is obtained by an abstracted sftpServer class, so you can basically get the source stream from anywhere.

The issue is, with bigger files that required the stream buffer to re-fill, I'm not exactly sure what should be done with the requests that can't be fulfilled in that time. In the following example, it just returns false. 

`.on("OPEN", (reqId, fileName, flags, attrs) => {
                    console.log("[OPEN]", reqId, fileName);
                    let handle = this.createHandle();
                    let flag = this.flagsToString(flags, SFTPStream);

                    if (flags === 42) flag = "w";

                    if (flag === "r") {
                      if (!this.handler.fileReadStream)
                        throw new Error(
                          "R14 SftpServer Error: fileReadStream method not found."
                        );
                      this.handler
                        .fileReadStream({
                          fileName: fileName,
                          session: r14SftpClientSession,
                        })
                        .then((readStream) => {
                          if (readStream === false)
                            sftpStream.status(reqId, STATUS_CODE.FAILURE);
                          this.handles[handle] = {
                            mode: "READ",
                            fileName: fileName,
                            state: "OPENING",
                            flag: flag,
                            fileStream: readStream,
                          };
                          readStream.on("readable", () => {
                            let sendHandle =
                              this.handles[handle].state !== "OPEN";
                            this.handles[handle].state = "OPEN";
                            sendHandle && sftpStream.handle(reqId, handle);
                          });
                          readStream.on("end", () => {
                            console.log("Reached end of stream.");
                            this.handles[handle].state = "SENT";
                          });
                          readStream.on("error", (res) => {
                            sftpStream.status(reqId, STATUS_CODE.FAILURE);
                          });
                        })
                        .catch((err) => {
                          return sftpStream.status(reqId, STATUS_CODE.FAILURE);
                        });
                    } else if (flag === "w") {
                    } else return sftpStream.status(reqId, STATUS_CODE.FAILURE);
                  })
                  .on("READ", (reqId, handle, offset, length) => {
                    if (!this.handles[handle]) {
                      console.error(`[READ] Handle not found ${handle}`);
                    } else if (this.handles[handle].state === "OPEN") {
                      let data = this.handles[handle].fileStream.read(length);
                      if (data) {
                        sftpStream.data(reqId, data || false);
                      } else return true;
                    } else if (this.handles[handle].state === "SENT") {
                      sftpStream.status(reqId, STATUS_CODE.EOF);
                    }
                  })`

**Comment by mscdex** [comment]
I'm curious as to why you're using a stream for this. Why not simply do the equivalent of `fs.open()` for `'OPEN'` requests, `fs.read()` for `'READ'` requests, etc., or using those exact methods if you're just reading from the local disk? That would simplify things a lot.

**Comment by steveswallow** [comment]
So, for this implementation, the source of the file isn't necessarily local, or a file. It is basically a virtual sftp server, as long as you can pass a stream (write or read), it can download or upload the "file" via sftp. For example, let's say we are using some S3 like remote file system which allows you get a read or write stream through an API. The abstracted adapter class allows you to serve files using sftp with any data you want. Without getting too in-depth here, we have a bunch of use cases for exactly this. I'm just stuck trying to figure how to deal with reading data that is not synchronous.

**Comment by mscdex** [comment]
Well in general, you can respond the requests at any time, you don't have to respond immediately within the request handler itself. So if you get a read request for more bytes than are available, just wait until that many bytes are available or the stream ends, whichever comes first. At that point you can respond with the appropriate response (`sftp.status(reqid, STATUS_CODE.EOF)` or `sftp.data(reqid, data);`).

**Comment by steveswallow** [comment]
Got it. So, should it respond to the requests in order? Also, it seams like returning true or false the cb has different behaviours. Should it just always return nothing /  undefined? I think your solution is basically the same as my queue solution, but I'm struggling with a request id mismatch error.

**Comment by mscdex** [comment]
You can respond to them in any order you want. However be aware that clients can request any `offset` at any time, which is going to be difficult/impossible to support with a readable stream backing the opened file.

On a related note, the S3 API allows for retrieving byte ranges of objects.

**Comment by steveswallow** [comment]
> You can respond to them in any order you want. However be aware that clients can request any offset at any time, which is going to be difficult/impossible to support with a readable stream backing the opened file.

I think this is exactly the problem I am running in to. I wish I could just call await this.read(readStream, length), it would make this really easy. 

> On a related note, the S3 API allows for retrieving partial objects by specifying byte ranges, which would work nicely inside the 'READ' handler.

I was just using S3 as an example. I'll give you another one, let's say you are using redis for input / output processing. You could use the sftp server to upload / download virtual files directly from redis. Serving dynamic files and folders from sftp is really powerful. I think I assumed that read streams would work, because streams are so tightly integrated into ssh2.

**Comment by mscdex** [comment]
It's not a node or `ssh2` issue, it's just that streams of data in general and SFTP are not really compatible for the reason I mentioned.

FWIW Redis also has a method for extracting subsets of data that could be used: [GETRANGE](https://redis.io/commands/getrange)

**Comment by steveswallow** [comment]
Thank you for all your help. I switched read to use fs.read type chunks instead of a read stream. It is working perfect now.
