### ISSUE TITLE
Run commands synchronously in the interactive shell

### ISSUE THREAD

**Issue by alex996** [mscdex/ssh2#931]
Not sure if this is feasible with `connection.shell()` but I'd like to run commands in a blocking (synchronous) fashion, e.g.

```js
conn.shell((err, stream) => {
  if (err) throw err

  stream
    .on('close', () => conn.end())
    .on('data', data => process.stdout.write(data))

  console.log('Changing directory')
  stream.write('cd /project\n') // any way to wait for this to finish?

  console.log('Listing contents') // this would only run after the above is complete
  stream.write('ls -al\n')

  console.log('Exiting')
  stream.end('exit\n')
})
```

Currently, this code prints

```
Changing directory
Listing contents
Exiting
Welcome to Ubuntu ...
...
logout
```
It seems that the lib "batches" all commands and runs them all at once. Is there any way to make it pause and wait for each one to finish, and only then proceed to the next? In other words, each command execution would block the event loop.

I get that it's possible with `conn.exec()` but `exec` doesn't keep the environment (particularly the working directory), and also creates a new session with each invocation (which is extra overhead unwarranted in this example), so I'd prefer to keep all commands in the same environment since they're interrelated.

Thanks.

**Comment by mofux** [comment]
The shell stream itself has no knowledge about the commands that are being executed, or when they finish. You could run all your commands in one sequence, e.g. `stream.write('cd /project && ls -alh && exit\n')`. This will make sure that all commands get executed in synchronous order, but this only works if you know all your commands in advance.

Alternatively, you could echo a "magic string" with every command executed, and then watch the stream data for that magic string to appear:

`stream.write('ls -alh && echo "====my-magic-string===="\n')`

This will result in the following data arriving at the readable side of the stream eventually:

```
# ls -alh && echo "====my-magic-string===="
total 0
drwxr-xr-x   24 root  admin   768B Aug 29 03:27 .
drwxr-xr-x   24 root  admin   768B Aug 29 03:27 ..
====my-magic-string====
```

As you can see, the actual output of the command is now surrounded by actual command, and the echoed magic string.

Once you read the magic string at the start of the line, you know the command has finished and you can issue the next command with the same technique.

I hope this helps as a starting point.

**Comment by alex996** [comment]
Thanks for the suggestions. I like your idea of checking a sentinel value in `stream.on('data')` and I was able to generalize it with a counter. But I think I'll keep all commands in one bash string for now, as it's easier to make the entire thing blocking and resume execution in `stream.on('close')`. Wish there was a built-in API for this in `ssh2` though.
