### ISSUE TITLE
new Buffer() Deprecation Warning

### ISSUE THREAD

**Issue by Coding-Kiwi** [mscdex/ssh2#932]
Hey, awesome package! My whole app is basically build around it 👍 

I get Buffer Deprecation warnings every time I start my app, if I understand correctly this comes from ssh2-streams -> streamsearch?

Not sure if you noticed but is there any problem with merging https://github.com/mscdex/streamsearch/pull/5?
More Info in https://github.com/mscdex/streamsearch/issues/4

Keep up the good work

**Comment by KerimG** [comment]
Yeah, just got this too on a dependent package and was wondering if I could help fix.

**Comment by mscdex** [comment]
The upcoming release doesn't use `ssh2-streams` anymore so it won't be an issue.

**Comment by KerimG** [comment]
Oh cool!

**Comment by daggett206** [comment]
hi @mscdex , when do you plan to release this fix? I also faced with `` new Buffer()`` issue in ssh2-streams

**Comment by Alicja-Kainos** [comment]
Hello, @mscdex, I would have exactly the same question as @daggett206: when the release of this fix will be done? I am facing the issue with new Buffer() also and would need to know when would I expect the fix. BR, Alicja

**Comment by mscdex** [comment]
The choices at the moment are: try the current master branch as that is where development is focused or use a fork of `ssh2` v0.8.x with the changes you need.
