### ISSUE TITLE
How to use existing "ssh -D" connections? 

### ISSUE THREAD

**Issue by vfilatov** [mscdex/ssh2#933]
# Objective
From serverA (192.168.0.1) I need to connect to BoxN (10.0.0.0/16).
BoxN is behind a firewall that allows connections only from serverB (192.168.0.2)

# CLI Solutions
### One of solution would be using "Jumpbox" technic
- $ ssh -J user@serverB admin@BoxN
that works, but each new connection spawns sshd on serverB which is not good when you
need few hundred connections at a time, that is why https://github.com/mscdex/ssh2#connection-hopping doesn't work for me

### The perfect solution
- create ssh tunnel to serverB
  $ ssh -D 2222 -NT user@serverB

- create ~/.ssh/config
```
  # make sure you have running "ssh -D 2222 -NT user@serverB"
  # make sure you have installed "netcat-openbsd - TCP/IP swiss army knife"
  Host 10.0.*
    ProxyCommand /usr/bin/nc -x 127.0.0.1:2222 %h %p
    PreferredAuthentications publickey
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
```
- now all connections go trough serverB transparently
  $ ssh admin@BoxN
  only one sshd on serverB serves all the traffic

# Question
lets say I still have running separate "ssh -D 2222 -NT user@serverB" process
How can I use it?
Is there any example?

**Comment by mscdex** [comment]
Implementing that is up to end users, `ssh2` will not do this automatically for you. `-D` utilizes SOCKS, so you'd need to have a SOCKS server running that would automatically forward new connection requests over an existing ssh connection (e.g. using `forwardOut()` on the ssh connection to get a stream you can pipe with your SOCKS connection).

Be aware however that many servers will limit the number of open channels on a single ssh connection, so if you are accepting hundreds of connections you will almost certainly need to utilize multiple ssh connections.

**Comment by vfilatov** [comment]
**mscdex**, thank you!

there is a server listening port 2222
```bash
$ netstat -an|grep 2222
tcp        0      0 127.0.0.1:2222          0.0.0.0:*               LISTEN     
tcp6       0      0 ::1:2222                :::*                    LISTEN     
```
and if I run netcat as below, I see sshd respond from BoxN
```bash
/usr/bin/nc -x 127.0.0.1:2222 10.0.0.1 22
SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
^C
```
Is there a way to use spawn process as a sock?
something like (this example is **NOT** working)
```javascript
var Client = require('ssh2').Client,
    spawn = require('child_process').spawn,
    netCat = spawn('/usr/bin/nc', ['-x', '127.0.0.1:2222', '10.0.0.1', 22]);
var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.shell(function(err, stream) {
    if (err) throw err;
    stream.on('close', function() {
      console.log('Stream :: close');
      conn.end();
    }).on('data', function(data) {
      console.log('OUTPUT: ' + data);
    });
    stream.end('ls -l\nexit\n');
  });
});

conn.connect({
  sock: netCat,
  username: 'admin',
  privateKey: require('fs').readFileSync(process.env.HOME + '/.ssh/id_rsa')
});
```

Is there an example available?

**Comment by mscdex** [comment]
The `sock` option requires a duplex stream (one that can both be read from and written to). `child_process.spawn()` does not return such streams, it returns individual streams for input and output.

**Comment by vfilatov** [comment]
I understand it might be not related to the project, but ...
Do you know how can I create a duplex stream using "individual streams for input and output" that `child_process.spawn()` returns?
Or there might be library that return duplex stream on spawn?

All solutions I googled, do not work with `sock` option

Thanks

**Comment by mscdex** [comment]
I think Stackoverflow or similar venues would be better places to ask that sort of thing.
