### ISSUE TITLE
ssh2@rewrite: Default export has changed

### ISSUE THREAD

**Issue by mofux** [mscdex/ssh2#938]
With previous versions of ssh2, the module would export a `Client` class:

```javascript
const { Client } = require('ssh2');
```

 With the current master, the client class is the main export, `require('ssh2').Client` does not exist anymore:

```javascript
const Client = require('ssh2');
```

This also means that the other exports of the module went lost:. `Client`, `Server`, `utils`, `HTTPAgent`, `HTTPSAgent`, `SFTP_STATUS_CODE` and `SFTP_OPEN_MODE`.

I guess that the intention is to still export the full set, and it is to the experminental nature of the master branch that they are not yet exposed?

**Comment by mscdex** [comment]
The following should definitely work in the current master:

```js
const { Client } = require('ssh2');
```

The other form does not work any longer as it was a bit of a kludge I had in there for backwards compatibility and I felt like now was a good opportunity to clean that up a bit for a v1.0.0 release.

The other values are still exported, but the SFTP-releated bits are namespaced now in the exports.

**Comment by mofux** [comment]
It doesn't seem to work for me, the Client class is the main export:

```
Welcome to Node.js v12.18.3.                                                                                            
Type ".help" for more information.                                                                                      
> const { Client } = require('ssh2')                                                                                    
undefined                                                                                                               
> Client                                                                                                                
undefined                                                                                                                                                                                                                         
> require('ssh2')                                                                                                       
[class Client extends EventEmitter]  
```

In `package.json` the `main` field specifies `./lib/client` as the entry point:
https://github.com/mscdex/ssh2/blob/ee93829e16636ccc63561d3df2d48b18a33abaae/package.json#L6

... And that file only has one default export, which is the `Client` class itself:

https://github.com/mscdex/ssh2/blob/ee93829e16636ccc63561d3df2d48b18a33abaae/lib/client.js#L1698

I guess the `main` field should point to `./lib/index.js` instead?

**Comment by mscdex** [comment]
Done. Thanks for the report!
