### ISSUE TITLE
Connection hopping with X11

### ISSUE THREAD

**Issue by rcketscientist** [mscdex/ssh2#944]
How would we connection hop with X11?

I've tried various permutations of the two sets of instructions, but I never end up with the x11 forwarded.  Would I need to do something with the `forwardOut` stream?

**Comment by rcketscientist** [comment]
Guess I missed a permutation.  Ended up getting it by applying the full X11 setup to both servers.

**Comment by mscdex** [comment]
You should just enable it wherever you need it. You shouldn't need to enable it on every hop if you're only wanting forwarding on the final host for example.

**Comment by rcketscientist** [comment]
That's what I initially thought, but swore that didn't work. I'll give it another shot tomorrow.

**Comment by rcketscientist** [comment]
Turns out I was resolving out of a promise incorrectly in one logic path.  As long I had a forwarding shell along the chain it worked with just the destination forwarding.  Thanks for the help.
