### ISSUE TITLE
SFTP Server fastGet interrupted 

### ISSUE THREAD

**Issue by mauriceleejy** [mscdex/ssh2#945]
Hi there

I am downloading many files from an SFTP server using fastGet method and noticed that the downloading always stop when the total volume of data downloaded reaches ~64GB/~65536MB. When this occurs, the last file will not be downloaded completely. I have tested this with 100MB files, 500MB files, or 1GB files and they all have the same issue of download stopping at ~64GB.

I currently have a workaround to prevent this download interruption by resetting the connection when download volume is at ~60GB but I am still curious as to what is causing this download limit of ~64GB. Are there any connection options for me to set to remove this limit? 

Thank you!

**Comment by mscdex** [comment]
Out of curiosity, would you mind testing (do not use this in production until its released though) the master branch of `ssh2` with your transfer and see if the same problem still exists? There have been some big changes in there recently that may impact issues like this.

**Comment by mauriceleejy** [comment]
You are right! The previous version which I was using is 0.8.9.  After testing with master branch of `ssh2` ("version": "1.0.0-beta.0"), the problem no longer exists. 

Just to confirm, there is currently no released version which fixes the issue right? v0.8.9 seems to be the latest released version.

**Comment by mscdex** [comment]
No release as of this writing. We're getting pretty close to decent code coverage and several issues from beta testers have been fixed, so I'm feeling more confident about the rewrite. However I can't give a definite date when the v1.0.0 release will be.

**Comment by mauriceleejy** [comment]
Ok got it. I will keep a lookout then. 

Thank you!
