### ISSUE TITLE
Channel open failure: open failed, reason: ADMINISTRATIVELY_PROHIBITED

### ISSUE THREAD

**Issue by vladislavmamchich** [mscdex/ssh2#946]
Hi there

I am using tunnel-ssh package which your package uses.
It worked before, now there is an error, who knows what could be the problem?

I will be grateful for any help

![image](https://user-images.githubusercontent.com/17312086/97185278-88ae4900-17a8-11eb-92a2-5598927a2be0.png)
![image](https://user-images.githubusercontent.com/17312086/97185680-06725480-17a9-11eb-904c-ebcd604e06a3.png)
![image](https://user-images.githubusercontent.com/17312086/97185837-3b7ea700-17a9-11eb-8758-eb60e7f13175.png)

**Comment by mofux** [comment]
Hard to say. Maybe the target ssh server does not allow port forwarding? There is also a restriction on most ssh servers that limit the number of open channels per session.

You could check the server's ssh log to see what is causing the error. You could also try with a different server and see if the problem reproduces there.

**Comment by mscdex** [comment]
Some servers may also restrict where you can connect to.

Are you able to successfully forward to the same destination host/port using the OpenSSH client?

Also, the code you highlighted in red is not related to your issue, that's for unsolicited connections from server to client.
