### ISSUE TITLE
Should ending the ssh client also end interactive shells?

### ISSUE THREAD

**Issue by AuspeXeu** [mscdex/ssh2#950]
I am creating an interactive shell stream like this.

```
let stream;
ssh
    .on('ready', () => {
      console.log('*** SSH connection established\r\n');
      ssh.shell((err, s) => {
        if (err) {
          return console.log(`*** SSH shell error: ${err.message}\r\n`);
        }
        stream = s
        // Send data from stream to socket
        s.on('data', (d: Buffer) => socket.send(utf8.decode(d.toString('binary')))).on('close', () => ssh.end());
      });
    })
    .connect({...})
```

Now, when I call `ssh.end()` data is still passed from the stream to my socket. For now I am manually doing this.

```
ssh.on('close', () => {
        socket.send('\r\n*** SSH connection closed\r\n');
        stream.close();
    })
```

**Comment by mofux** [comment]
I cannot reproduce this with the current `master` (has no npm release yet). Calling `client.end()` will also end the shell. Which version have you been using?

**Comment by mofux** [comment]
If I execute a command that produces lots of data, e.g. `ls -lR /` I can see that there is still some data arriving, but it looks to me like this is only the data that was still in the stream buffer at the time that `client.end()` was called. Once the buffer is flushed no more data arrives.

**Comment by AuspeXeu** [comment]
Aha! I think the latter is also what happened to me. I'll try to reproduce this.
