### ISSUE TITLE
SSH2 will not run under React on Ubuntu

### ISSUE THREAD

**Issue by westsuhanic** [mscdex/ssh2#953]
Hello:

I am using Ubuntu 20.04.1 LTS to develop a React App.
The version of React is 17.0.1.
The version of SSH2 that I have installed is "^0.8.9"
npm is version 6.14.9

When I do npm start for my application the following error shows up in my firefox browser. Any suggestions on how to address this issue?

===========================================================================

Error: process.binding is not supported
__webpack_require__
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

fn
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

./node_modules/ssh2-streams/index.js
node_modules/ssh2-streams/index.js:2
__webpack_require__
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

fn
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

__webpack_require__
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

fn
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

./src/App.js/<
src/App.js:4

  1 | import React, { useState, useEffect } from 'react';
  2 | import './App.css';
  3 | import io from 'socket.io-client';
> 4 | const Client = require('ssh2').Client;
  5 | const sftp = new Client();
  6 | 
  7 | const socket = io('http://localhost:3001',{

./src/App.js
http://localhost:3000/static/js/main.chunk.js:541:30
__webpack_require__
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

fn
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

__webpack_require__
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

fn
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

1
http://localhost:3000/static/js/main.chunk.js:878:18
__webpack_require__
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:856

  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }

checkDeferredModules
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:45

  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 

webpackJsonpCallback
/home/wsuhanic/encryptedDiskMountPoint/react/chat/client/webpack/bootstrap:32

  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;

(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:65

**Comment by mscdex** [comment]
I don't understand how `ssh2` is involved with what you're trying to do, but `ssh2` will not run in the browser as it requires a lot of low-level features like crypto and TCP connections. The former can technically be done in the browser with polyfills/WebCrypto, but plain TCP connections are currently not a feature exposed to normal JavaScript applications.

I'm not familiar with webpack, so I think you're probably better off asking the webpack folks about this one.
