### ISSUE TITLE
Timeout ForwardOut

### ISSUE THREAD

**Issue by Nisgrak** [mscdex/ssh2#955]
I try to connect to a machine forwarded in other (hopping), the method forwardOut fails but take like 40 or 50 seconds to finish.

I want a option like readyTimeout in connect.

![image](https://user-images.githubusercontent.com/19597708/100098167-ef815980-2e5d-11eb-9862-0499b6f135e7.png)

**Comment by mscdex** [comment]
There is no way to abort a pending `forwardOut()` request, short of disconnecting entirely, so I'm not sure how a timeout would work in that scenario.

**Comment by Nisgrak** [comment]
I make a workaround:
```js
let timeout = setTimeout(async () => {
  reject(await this.errorHandler({
    code: "TUNNEL_ERROR",
    error: "The connection with the tunnel fails"
  }))
}, 10000);

this.hoppingConnection.on('ready', () => {
  this.hoppingConnection.forwardOut('127.0.0.1', Math.floor(Math.random() * (65535 - 49152) + 49152), this.ip, 22, async (error, stream) => {
    clearTimeout(timeout);

   # the action to take...
  }
})
```
