### ISSUE TITLE
Can you publish the current master to npm under beta/next/alpha tag?

### ISSUE THREAD

**Issue by amotzte** [mscdex/ssh2#957]
Hi, 

Thanks for this excellent library!!

ssh2 stopped working for me with node14. This seems to be resolved on current master. I understand it is not stable yet and therefor you don't want to publish it in npm as ```latest```. But could you maybe publish it as ```beta``` tag so we could reference the ```packages.json``` to npm instead of github?
Thanks

**Comment by theophilusx** [comment]
Just FYI, I don't think the current master branch does fix the node v14 issue - at least not yet. In fact, it may actually be worse as I'm finding that the issue of fastPut hanging on larger files now occurs with node version 12, but works fine with ssh2 0.8.9. I'm currently digging into it and haven't identified the specific combination to trigger the hang, but I have noticed it is most common with larger files. Smaller ones seem to work ok.

**Comment by mscdex** [comment]
v1.0.0 is now released.
