### ISSUE TITLE
is there a list of classes and methods of the objects that you get?

### ISSUE THREAD

**Issue by Kreijstal** [mscdex/ssh2#964]
Basically I would like a API-esque documentation what the classes are called for example I would like to know what the sshStream methods are. 
And the only way to describe the "sshStream" is the evaluation of the call of the first parameter of the callback function that gets executed on the "shell" event, this object is obtained being the return of the call of the first parameter of another function and so on.. basically it's callback hell all the way in. and there's no way to find the methods of the callbacks besides reading the source. So maybe it'd be nice if that list existed.

Btw I'm refering to
```js
require("ssh2").server({},(client)=>client.on("session",(a,r)=>a().on("shell",a=>a()/*This Class that you get here*/ )))
```

**Comment by mscdex** [comment]
I'm not sure what you think is missing. The readme describes it all. "sshStream" is not even used anywhere in the documentation. Perhaps you're looking at some other project's documentation?

**Comment by Kreijstal** [comment]
that's right, I don't even know the names of the functions/methods. That I can get when calling accept()

**Comment by mscdex** [comment]
Closing this as there's nothing actionable to be done. The readme already mentions the type that is returned (which is `Channel` in this case).
