### ISSUE TITLE
Electron v11 terminates when the connection is established

### ISSUE THREAD

**Issue by borsTiHD** [mscdex/ssh2#967]
Hi all,

I'm using electron and since I upgraded electron to version 11 (v11.1.1) ssh2 terminates the node process when the connection is established.

My project is a little big, so I don't have a working test environment. :(
I'm using this boilerplate: https://github.com/michalzaq12/electron-nuxt

On electron v8, v9 and even v10 (v10.2.0) everything worked fine with the same code.

Here is an example for a connection (it doesn't matter if I use the renderer or main process of electron):
```
const settings = {
    host: this.ip,
    port: 22,
    keepaliveInterval: 10 * 1000,
    username: this.user,
    password: '',
    debug: (line) => console.log('ssh log: ' + line)
}

const client = new Client()

client.on('error', (err) => {
    console.error('ssh error:', err)
})

client.on('ready', () => {
    console.log('ssh connection established')
}).connect(settings)
```

My shortened log:
```
│  ssh log: DEBUG: Parser: IN_PACKET
│  ssh log: DEBUG: Parser: pktLen:532,padLen:8,remainLen:528
│  ssh log: DEBUG: Parser: IN_PACKETDATA
│  
│  ssh log: DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_GEX_GROUP
│  

i Electron-nuxt: Killing all processes... (reason: launcher close event)
```

Can someone please help me solve the problem?
Thanks in advance.

**Comment by mscdex** [comment]
`ssh2` never explicitly terminates the process. If the same code was working on previous Electron releases, either Electron is to blame or the node version they're using in that particular release is buggy.

Did you try the `ssh2` code with just plain node (the same version Electron is using -- v12.18.3 in this case) to narrow the problem down?

**Comment by borsTiHD** [comment]
Thanks for the quick response. :)
I'm not blaming you or ssh2 for the problem. I understand that the electron version provokes the problem, but i don't think i would get help with this problem there and I rather tried here first. :D 

Hm... no I didn't tried my code with plain node. I will try it out tomorrow.
Thanks for the tip. :)

Is it possible, or do you have any idea how I could capture such a termination in node and debug?
Maybe I could find more this way.

**Comment by SchoofsKelvin** [comment]
Something similar happens in VS Code 1.53.0, which has upgraded from Electron v9 to v11: SchoofsKelvin/vscode-sshfs#239

**Comment by borsTiHD** [comment]
Thanks for linking to this issue. :)

**Comment by borsTiHD** [comment]
https://github.com/electron/electron/issues/27673

**Comment by borsTiHD** [comment]
Can be closed. The current electron v11.3.0 solved my problem.
