### ISSUE TITLE
Unable to run the sample program .

### ISSUE THREAD

**Issue by dotrana** [mscdex/ssh2#968]
Hi. I can across a samp program from mscdex on stackoverflow. Hoping that it’s you, please help me troubleshoot this code. I have been working on it for the past two days without success.

```js
const mysql = require('mysql2');
const { Client } = require('ssh2');
const sshClient = new Client();
require('dotenv').config();

var ssh = new Client();
ssh.on('ready', function() {
  ssh.forwardOut(
    '127.0.0.1', 3308, '127.0.0.1', 3308,
    function (err, stream) {
      if (err) throw err;
      const dbServer = {
        host: process.env.DB_HOST,
        port: process.env.DB_PORT,
        user: process.env.DB_USER,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_DATABASE,
        ssl: {
            ca: require('fs').readFileSync('./certs/ca.pem'),
            key: require('fs').readFileSync('./certs/client-key.pem'),
            cert: require('fs').readFileSync('./certs/client-cert.pem')
        },
        stream: stream
    }
      var connection = mysql.createConnection(dbServer);
      connection.query('SELECT * FROM `users` ;',
      function(err, results, fields) {
          if (err) throw err;
          console.log(results); // results contains rows returned by server
      });
    });
}).connect({
    host: process.env.DB_SSH_HOST,
    port: process.env.DB_SSH_PORT,
    username: process.env.DB_SSH_USER,
    privateKey: require('fs').readFileSync(process.env.DB_SSH_KEY)
  });
```

I don’t see any errors thrown or results when I run the program.

**Comment by mscdex** [comment]
Other than perhaps specifying the host and port (which are unnecessary because you're passing a stream), I don't see anything wrong.

**Comment by stiv-yakovenko** [comment]
I also get an error trying to run scp server:

```
        OPEN_MODE,
        ^

TypeError: Cannot read property 'OPEN_MODE' of undefined
    at Object.<anonymous> (C:\Users\stiv\IdeaProjects\scp-server\server.js:8:9)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:986:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

```

**Comment by dotrana** [comment]
> Other than perhaps specifying the host and port (which are unnecessary because you're passing a stream), I don't see anything wrong.

I have tried either way. Does not change anything.

**Comment by Amrkamel1** [comment]
> > Other than perhaps specifying the host and port (which are unnecessary because you're passing a stream), I don't see anything wrong.
> 
> I have tried either way. Does not change anything. 

Hye man did you manage to solve your issue ?

If yes could you share your code sample.

**Comment by dotrana** [comment]
> > > Other than perhaps specifying the host and port (which are unnecessary because you're passing a stream), I don't see anything wrong.
> > 
> > 
> > I have tried either way. Does not change anything.
> 
> Hye man did you manage to solve your issue ?
> 
> If yes could you share your code sample.

ssh2 did not work for me. So worked around it, by first creating a ssh tunnel through `tunnel-ssh` package. And then using the promise to connect to the database. I started with mysql, but had to switch to mongodb for my needs. So I am using mongoose package for connecting to the DB. If you can want to use mysql, then you can use mysql2 (if I remember correctly). Here is a gist of what I am doing:

`const tunnel = require('tunnel-ssh');
var events = require('events');
require('dotenv').config();

let server;
const sshTunnelConfig = {
    host: process.env.DB_SSH_HOST,
    port: process.env.DB_SSH_PORT,
    username: process.env.DB_SSH_USER,
    privateKey: require('fs').readFileSync(process.env.DB_SSH_KEY),
    dstHost: process.env.localHost,
    dstPort: process.env.DB_PORT,
    localHost: process.env.localHost,
    localPort: process.env.DB_PORT
};

class mongocon {

    constructor() {
    }

    cnct2Tnl() {
        return new Promise(function (resolve, reject) {
            tunnel(sshTunnelConfig, (err, serv) => {
                if (err) {
                    reject(err);
                    return;
                }
                server = serv;
                resolve(serv);
            });
        })
    }

    cnct2db() {
        this.mongoose = require('mongoose');
        let mongoOpts = { useUnifiedTopology: true, useNewUrlParser: true };
        this.mongoose.connect('mongodb://'+process.env.DB_USER+':'+process.env.DB_PASSWORD+'@'+process.env.DB_HOST+':'+process.env.DB_PORT+'/'+process.env.DB_MEMBERS+'?authSource=admin', mongoOpts);
    }

    closeTnl() {
        server.emit('close');
        console.log('Tunnel closed');
    }

    closeMongo() {
        this.mongoose.connection.close();
        console.log('Mongo connection closed');
    }
}

exports.mongocon = mongocon;`
