### ISSUE TITLE
Unhandled 'error' event -- Timed out while waiting for handshake (client)

### ISSUE THREAD

**Issue by MattrCoUk** [mscdex/ssh2#969]
There seem to be no timeout handler causing the Node app to crash when connection timeout reached.
The only workaround I found is to set timeout to a ridiculously large number. Not sure if that’s intentional.

		conn = new ssh2();
		conn.on('ready', function() {
		  conn.exec('cat /dirs_on_remote/file.txt', function(err, stream) {
		    if (err) {
      
		      console.log('ERR: ' + data);
		      return;
		    }
		    stream.on('close', function(code, signal) {
		      conn.end();
		    }).on('data', function(data) {
		      console.log(data);
			
		    }).stderr.on('data', function(data) {
      
		      console.log('STDERR: ' + data);
		    });
		  });
		}).connect({
		  host: config.ssh_host,
		  port: 22,
		  username: config.ssh_username,
		  privateKey: require('fs').readFileSync(config.ssh_key_path),
		  readyTimeout: 5000
		});

Error message:

		events.js:292
		      throw er; // Unhandled 'error' event
		      ^

		Error: Timed out while waiting for handshake
		    at Timeout._onTimeout (/app/node_modules/ssh2/lib/client.js:695:19)
		    at listOnTimeout (internal/timers.js:549:17)
		    at processTimers (internal/timers.js:492:7)
		Emitted 'error' event on Client instance at:
		    at Timeout._onTimeout (/app/node_modules/ssh2/lib/client.js:697:14)
		    at listOnTimeout (internal/timers.js:549:17)
		    at processTimers (internal/timers.js:492:7) {
		  level: 'client-timeout'
		}

**Comment by mscdex** [comment]
As with any `EventEmitter` object in node, if  you add an `'error'` event handler on the connection object you can keep the process from exiting.

The `readyTimeout` may need to be increased depending on the ssh server, node version, and/or algorithms selected during the handshake (these are due to changes made in OpenSSL and are unavoidable in some cases).

**Comment by MattrCoUk** [comment]
Thanks for reply. I'm having difficulties figuring out which one is the _connection object_ in my example.
