### ISSUE TITLE
Host chaining

### ISSUE THREAD

**Issue by KaKi87** [mscdex/ssh2#971]
Hello,

Can I perform host chaining using `ssh2` ?

i.e. connecting to a first host then connecting from that one to another.

That would be the equivalent of running an `ssh` command inside an already active `ssh` command.

This feature is necessary when accessing a network of devices in which only one is exposed to the worldwide web.

Thanks

**Comment by mscdex** [comment]
Yes, there is a [connection hopping example in the readme](https://github.com/mscdex/ssh2/blob/v0.8.x/README.md#connection-hopping).

**Comment by KaKi87** [comment]
Oh, that was it ! I'm truly sorry for this disturbance. Thanks

**Comment by KaKi87** [comment]
Do you have any clue about getting input/focus back after shell unpiping ?

Here's my project : [`KaKi87/sshception`](https://git.kaki87.net/KaKi87/sshception.git)

More specifically :

[`lib/ssh.js:L24`](https://git.kaki87.net/KaKi87/sshception/src/branch/master/lib/ssh.js#L24)
```js
clientStream.on('unpipe', () => {
    onClose(clientStream);
    client.end();
});
```
[`lib/tui/index.js:577`](https://git.kaki87.net/KaKi87/sshception/src/branch/master/lib/tui/index.js#L577)
```js
/* onClose callback */
clientStream => {
    clientStream.stdout.unpipe(stream.stdin);
    stream.stdin.unpipe(clientStream.stdout);
    // FIXME input/focus
    init();
    _controllers.main(user);
}
```

Using [`chjj/blessed`](https://github.com/chjj/blessed) and `ssh2`.

Here's how it looks :

![](https://cdn.discordapp.com/attachments/493524617714204672/793215146951835678/Capture_decran_de_2020-12-28_21-09-21-min.png)

I've been stuck for months on this and still haven't any clue about it, I don't know much about `Stream` objects :/

Here's an [r/node post](https://old.reddit.com/r/node/comments/klyql5/help_wanted_ssh2_nodeblessed/) in which I explain all the issues I have on this project.

Thanks !
