### ISSUE TITLE
when deploy new version? 

### ISSUE THREAD

**Issue by shangchengxiang** [mscdex/ssh2#973]
I saw current newest version is v0.8.9. But due to my company's latest security regulations forbidden DEFAULT_SERVER_HOST_KEY, 
it contains ecdsa-sha2-nistp256,  ecdsa-sha2-nistp384,  ecdsa-sha2-nistp521 and  ssh-rsa. 
Then I found Latest Code changed this DEFAULT_SERVER_HOST_KEY, it added rsa-sha2-512, rsa-sha2-256. I expect to use them. 
So please tell me when can I use rsa-sha2-512 and rsa-sha2-256 in Released Version. Thanks.

**Comment by mofux** [comment]
Please see: https://github.com/mscdex/ssh2/issues/935#issuecomment-706143550
In the meantime you can already use the master version by specifying "mscdex/ssh2" as the version in your package.json:

```json
{
  "dependencies": {
    "ssh2": "mscdex/ssh2"
  }
}
```

**Comment by mscdex** [comment]
New version will get released when I'm comfortable doing so and there are no showstopping bugs/issues left with the rewrite.
