### ISSUE TITLE
Multiple SSH keys

### ISSUE THREAD

**Issue by julien-f** [mscdex/ssh2#974]
OpenSSH allows to specify multiple keys (`IdentityFile`) that will be tried in sequence for authenticating.

What's the best way to replicate this with this lib?

Thank you :slightly_smiling_face:

**Comment by mscdex** [comment]
There is currently no built-in functionality to achieve the same behavior.

**Comment by julien-f** [comment]
Thank you for your quick answer :slightly_smiling_face: 

It would be nice if we could explicitly list authentication methods to try.

In the meantime, I'll simply loop around `connect` and the `ready` event.

**Comment by mscdex** [comment]
> It would be nice if we could explicitly list authentication methods to try.

You can already do that with `authHandler` but that doesn't permit you to specify multiple `privateKey` for example, it only allows you to change the default *order* of authentication methods (and perhaps re-trying a particular configured method more than once).

**Comment by julien-f** [comment]
Indeed, as far as I understand, it only allows specifying which methods to retry, but not to change the settings (password, private key, etc.)

**Comment by julien-f** [comment]
Anyway, thanks for your answer, have a nice day!

**Comment by julien-f** [comment]
I'm trying to iterate on `connect()` but it's not working correctly, I suspect it's because I'm using a socket (`sock`) and that socket gets closed after the first failed attempt…

Any idea?

**Comment by mscdex** [comment]
You would need to pass in a new stream.
