### ISSUE TITLE
Each update is rendered as a separate output, without replacing the previous one

### ISSUE THREAD

**Issue by HemTech** [mscdex/ssh2#975]
I’m trying to use create console app using ink library. I’m using putty to test my app using telnet and ssh2.  My react app is working in console/telnet. 

I’m not able to control rendering of the same with SSH@. ssh2 render it twice and each update is rendered as a separate output, without replacing the previous one.

Minimal reproducible example - https://gitlab.com/Hemendra.patel/inkapp
1.	start: "npm run build && node dist/cli.js"   //command prompt,
2.	start_telnet: "npm run build && node dist/telnet/telnetserver.js",
3.	start_ssh: "npm run build && node dist/ssh/sshserver.js",

Do you have any idea what I could do to control ssh rendering?

**Comment by mscdex** [comment]
This seems beyond the scope of this module. If you're referring to duplicate output, maybe your local terminal has local echo enabled?
