### ISSUE TITLE
can not use sftp to connect remote server B on remote server A and get file from remote server B to remote server A

### ISSUE THREAD

**Issue by dlanorf** [mscdex/ssh2#976]
I tried to use ssh2 to connect a remote server A, and use sftp command on server A to connect to another remote server B,  then use sftp get file from server B to server A (not to local). But I failed to do that. 

I don't know what I missed. Below is the code I used to do that. After run this code, nothing happened, no error either. 
By the way, I also tried to put the next command execution in stream.on('data') event of previous command execution,  and no result.

```
// transfer file from remote B to remote A
function sftpTransferFile(remoteServerA, remoteServerB) {
    const ssh = new SSHClient();
    ssh.on("ready", function() {
        // 1. connect to sftp remote server B
        ssh.exec("sftp root@remoteServerB", (error1, stream) => {
            if (error1) return;
            stream.on("data", function(data1) {
                logger.info("success ?");
            })
        });
        // 2. give password for sftp remote server B
        ssh.exec("passwordForRemoteServerB", (error2, stream2) => {
            if (error2) return;
            stream2.on("data", function(data2) {
                logger.info("success ?");
            });
        });
        // 3. sftp get someFile from remote server B to remote server A
        ssh.exec("get /opt/someFile", (error3, stream3) => {
            if (error3) return;
            stream3.on("data", function(data3) {
                logger.info("success ?");
            });
        });
    }).on("close", function() {
        logger.error("closed");
    }).on("error", function(error) {
        logger.error(error);
    }).connect({
        host: remoteServerA,
        port: 22,
        username: 'frylock',
        password: 'frylockPassword'
    });
}

```

**Comment by mscdex** [comment]
The reason is that `exec()` executes commands in separate sessions.

**Comment by dlanorf** [comment]
you mean one exec for one command ?  It can not execute a series of commands ?

If so, how to achieve get file from remote B to remote A ?

**Comment by mscdex** [comment]
> It can not execute a series of commands ?

Not as-is. You would need to come up with some alternate solution, whether that's still utilizing `exec()` or using `shell()`. Your best bet is probably going to be using a single `exec()` to avoid unnecessary complications. There are a variety of solutions that can be found on google for downloading a file via command line via sftp non-interactively.
