### ISSUE TITLE
Catch error thrown after connection is rejected - Question

### ISSUE THREAD

**Issue by JRobertsDS** [mscdex/ssh2#979]
I have the following code to capture the fingerprint of a server for (server) testing.
I reject the connection after capturing the fingerprint by returning "false" from the hostVerifier.
Doing so causes an error (KEY_EXCHANGE_FAILED) that I would like to catch so that it doesn't propagate -- it's expected behavior in my testing environment.
But I am baffled as to how to catch this error, and am looking for ideas.

```
var Connection = require('ssh2');

function getSSHFingerprintSSH2(ip, port) {
  return new Promise(resolve => {
    let fingerprintToReturn = "fingerprint error";
    let sshConnection = new Connection();

    sshConnection.on('error', function() {
      //normal operation resolves here after rejecting the connection
      resolve(fingerprintToReturn);
    });
    sshConnection.connect({
      host: ip,
      port: port,
      username: '',
      password: '',
      hostHash: 'sha256',
      hostVerifier: function(fingerprint) {
        fingerprintToReturn = fingerprint;
        // returning "false" rejects the connection with a handshake error
        // which is what we want to do normally, having captured the fingerprint
        return false;
      },
    });
  });
}
```

**Comment by mscdex** [comment]
The code looks fine to me. Are you saying this code throws an error instead of being emitted under an `'error'` event? If so, what is the exact error that you're seeing? Are you on the latest `ssh2` v0.8.x?

**Comment by JRobertsDS** [comment]
I am using the latest, v.0.8.x.
The code itself is fine, the error, KEY_EXCHANGE_FAILED, is expected. My problem is that I don’t know how to catch the error so that I can prevent its writing to the console and appearing, in my test, to be a problem.  Essentially, where can I try...catch to catch this error, which is thrown by SSH2 after my callback returns “false”?

**Comment by mscdex** [comment]
There should be no async throwing in `ssh2`/`ssh2-streams`, that's why I was curious as to exactly which error you were seeing (in the console) that was not being handled by your `'error'` event handler.

**Comment by theophilusx** [comment]
In many cases, ssh2 reports errors using an error event. To 'catch'
this, you need to add an error listener which will handle the event. You
cannot use try/catch to catch events, only event listeners will work.

**Comment by JRobertsDS** [comment]
Thanks; I was missing the distinction between catching thrown errors and listening for error events.
