### ISSUE TITLE
stream doesn't close without listening to the data event

### ISSUE THREAD

**Issue by RobinSchapendonk** [mscdex/ssh2#980]
```
connection.on('ready', () => {
    connection.exec('docker-compose restart', (err, stream) => {
        stream.on('close', () => {
                console.log('c');
                return connection.end();
        }).on('data', function(data) {
            console.log('STDOUT: ' + data);
        });
    });
});
```
this logs c

```
connection.on('ready', () => {
    connection.exec('docker-compose restart', (err, stream) => {
        stream.on('close', () => {
                console.log('c');
                return connection.end();
        })
    });
});
```
this doesn't log c

**Comment by mscdex** [comment]
That's how node streams work in general. You need to consume them one way or another, whether it's with `'data'` event handlers, calling `.read()`, or calling a method like `.resume()` to just drain the data if you don't care about it.

**Comment by theophilusx** [comment]
Just wondering about using 'data' events. According to node docs, adding a data listener will put the stream into 'classic' legacy mode and lose the advantages of the stream2 api. Is it better to use pipe() and read() and avoid the use of a data listener or does it not matter for ssh2-streams?

**Comment by mscdex** [comment]
It's a normal stream like any other in node. Read it how you like. The point is like any other readable/writable stream in node these days you won't see `'close'` until there is nothing left to be read (and in the case of `ssh2`, when the remote process no longer exists -- much like child processes in node).
