### ISSUE TITLE
Handle logging errors when logging isn't available

### ISSUE THREAD

**Issue by kolban-google** [mscdex/ssh2#982]
The current implementation writes logging data to Cloud Logging.  But if we don't have access to Cloud Logging, we break ... for example, wrong project or no permissions to perform logging.  We need to handle meta errors ... errors about writing errors.

**Comment by mscdex** [comment]
I don't understand what you're asking for or what you're referring to. This project doesn't have anything cloud-specific in it. Errors should be handled in the usual node-esque ways (e.g. adding `'error'` event handlers).

**Comment by kolban-google** [comment]
I am **so** sorry ... I had your repo up and raised a defect against your repo when I meant to raise against another project/repo.  I am a dunce.  Apologies for the pollution.
