### ISSUE TITLE
SFTP Healthcheck

### ISSUE THREAD

**Issue by diazgilberto** [mscdex/ssh2#984]
This is more of a question. I have a microservice that interacts with an SFTP server. I writing the `http://localhost:3000/health` endpoint for devops to check if my service is up and running. Returning `200` at the moment. I would like to include the SFTP server since is a dependency. Is there anything that SFTP returns when a connection is established?

**Comment by mscdex** [comment]
I'm not sure what kind of information you're asking/looking for? Are you really interested specifically in the SFTP layer or the underlying SSH server instead?

At the very beginning of an SSH connection, there is a "hello" message that identifies the server SSH implementation software name/version and a possible generic comment.

SSH servers may also present a banner before the "hello" and another after a successful handshake but before user authentication. These free-form banners/messages are not common though, and are typically used for warnings about unauthorized access and the like.

SFTP itself has neither of these things. The only thing exchanged at the start is protocol version negotiation and announcement of protocol extensions, no free-form messages/information of any kind.

**Comment by mscdex** [comment]
As far as actual "health" checking goes, I would say the connection is "healthy" if:

* You have enabled/configured the keepalive behavior via the connection config object passed to `.connect()`
* You've seen the `'ready'` event
* You haven't seen the `'close'` event yet

**Comment by diazgilberto** [comment]
Sorry I wasn't clear. I'm writing a micro service and I'm using ssh2 for interacting with an sftp server, so I'm using ssh2 as a client. The service is exposing a REST interface 
* `http://<domain>/sftp/read-directory`
* `http://<domain>/sftp/read-file`
* `http://<domain>/sftp/write-directory`
* `http://<domain>/health`
In that `/health` route, the devops team is using it to check the health of my service. I want to check the health service's dependencies as well. I want to somehow pin sftp server and receive some status so I can return `200` or `unhealthy` in the case my dependency (sftp server) is unreachable.

Hope my question now makes sense.

Thanks!

**Comment by theophilusx** [comment]
this is a difficult question to answer without knowing more about how
the service is implemented - for example, does it make a new connnection
for every request or are you establishing a long term/running process
which is expected to remain open for multiple requests etc.

I would probably just do a basic directory listing or realpath call and
check the response. If you get back a value which makes sense, it is
working. If you get an error or unexpected close event, something is not
working.

--
Tim Cross

**Comment by diazgilberto** [comment]
> this is a difficult question to answer without knowing more about how the service is implemented - for example, does it make a new connnection for every request or are you establishing a long term/running process which is expected to remain open for multiple requests etc. I would probably just do a basic directory listing or realpath call and check the response. If you get back a value which makes sense, it is working. If you get an error or unexpected close event, something is not working.
> […](#)
> -- Tim Cross

I'm not sure If I understand. For a health check, I think I don't need to read any folder at all. Let get an sftp server out of the way. Let's say I have a microservice in NodeJS and does CRUD to Elasticsearch. In my Node microservice, I expose a route like `http://<domain>/health` that returns just `200`. Someone can hit that route just to make sure that my microservice is up and running. Now, since my microservice depends on Elasticsearch, I can do a health check to Elastic as well. So, in the same end point `http://<domain>/health`, I first health check Elastic, if Elastic returns `200` then I can return `200`. That gives to my client assurance that my microservice and its dependencies are usable.

My REST API is NOT an sftp server. My REST API interacts with an external sftp server, which makes that sftp server a dependency of my REST API.

My question is if sftp servers have some sort of health check.

**Comment by theophilusx** [comment]
No, they don't. You have to define what you mean by 'healthy' and then
implement the necessary code to verify that. Healthy might mean that you
can connect to the server, or it might mean you can connect to the
server and have access to a specific directory or it might mean you can
connect to the server, have access to a specific directory and can
read/write to that directory.
--
Tim Cross

**Comment by mscdex** [comment]
I already outlined what you need to determine the "health" status of an ssh/sftp connection. The only thing you might add to that is to verify that your `ssh.sftp()` was successful and that the sftp session isn't closed. With that addition, that should cover what you want. Unless like @theophilusx said, you require something additional, which of course would be application-specific (e.g. checking for access to files/directories).

**Comment by diazgilberto** [comment]
Working with those ideas.
Thanks to both!!
