### ISSUE TITLE
Jump into mongo / MySQL shell directly [Question] 

### ISSUE THREAD

**Issue by DeanKamali** [mscdex/ssh2#986]
I'm trying to start `mongo / MySQL` client on the remote host and start an interactive session without having the user type in mongo or MySQL client with options (hostname, port, database, password ..etc)  

- Goal is to jump into mongo / MySQL terminal directly

Example: 

`mongo -h 127.0.0.1  -u admin -p some_password`

I'm able to achieve this to a certain degree with 

```
  connection.shell((err, stream) => {
           stream.write('mongo -h 127.0.0.1 -u admin -p somepassowrd \n')
                stream.on('close', () => {
                    process.exit(0)
                })
 });
```

However, the shells start but the end-user is able to see connection details before the shell starts "mongo -h 127.0.0.1 -u admin -p somepassowrd" 

Is there is any way, I could hide this line from the end user?

**Comment by mscdex** [comment]
Did  you try using `.exec()` instead of `.shell()`?

**Comment by DeanKamali** [comment]
Yes, but unfortunately it's not interactive. 

is it possible to somehow spawn a child process on a remote bastion host and pass the steam back to the shell?

**Comment by mscdex** [comment]
Did you try setting `pty` with the call to `exec()`? That will request a pty to be allocated, like is done with interactive `shell()` sessions.
