### ISSUE TITLE
Execute commands while in interactive shell

### ISSUE THREAD

**Issue by ShlomiRex** [mscdex/ssh2#990]
Basically I have interactive shell
Basically I want every 5 sec to execute "pwd" command to check where I am, while having interactive shell open
Is this possible?
I mean, when interactive shell is open, to execute a command, I do "conn.exec" which creates another stream
So when i'm in root folder "/" and execute "pwd" then I get "/home/test" which is the the default home, even though I change directory and execute "pwd", it still same directory.

More broadly, how can I know where is the user while having interactive shell programically?

**Comment by mscdex** [comment]
To be honest I think you'd be better off having the shell show the current path instead.

However, aside from that the "easiest" solution (assuming you're logged into a *nix system with /proc filesystem support) would include obtaining the pid of the particular interactive shell (e.g. bash) session in one way or another and then reading the symlink at /proc/<pid>/cmd while the shell process is still alive.

**Comment by ShlomiRex** [comment]
> To be honest I think you'd be better off having the shell show the current path instead.
> 
> However, aside from that the "easiest" solution (assuming you're logged into a *nix system with `/proc` filesystem support) would include obtaining the pid of the particular interactive shell (e.g. bash) session in one way or another and then reading the symlink at `/proc/<pid>/cmd` while the shell process is still alive.

I have SSH shell but I don't see any file in /proc/<pid>/cmd
I see cmdline but it doesn't give any information I need

**Comment by mscdex** [comment]
It should be `cwd` not `cmd`.

**Comment by ShlomiRex** [comment]
> It should be `cwd` not `cmd`.

Ah yes, it's just symlink.
But I think I found a solution: multiple channels per SSH session. I read on google that you can do multiple stuff with each channel. I still investigate how to impliment this.
