### ISSUE TITLE
Code sample for connect/disconnect

### ISSUE THREAD

**Issue by Amrkamel1** [mscdex/ssh2#991]
Im trying to you connect to a remote db so i needed first to connect to the remote server via ssh

So where i can find a sample code to just connect and  and disconnect the ssh connection with integration to DB connection

**Comment by mscdex** [comment]
You'd use `forwardOut()` to create a new connection on the server, which there is an example of under "Send a raw HTTP request to port 80 on the server" in the readme. However, the database driver needs to first support accepting arbitrary streams to use as the underlying connection (not all drivers support this -- `mysql2` does for example but not `mysql` AFAIK).

**Comment by Amrkamel1** [comment]
Thanks, man it was really helpful I have managed it.
