### ISSUE TITLE
Allow async key.sign() for publickey authentication

### ISSUE THREAD

**Issue by dhensby** [mscdex/ssh2#992]
With the increased use of hosted [key](https://azure.microsoft.com/en-gb/services/key-vault/) [management](https://cloud.google.com/security-key-management) [services](https://aws.amazon.com/kms/), there's an increasing need to allow signing of data via asynchronous calls so that remote hosted keys can be used to sign data without an application actually being in possession of the raw private key.

All of the underlying work is available in ssh2-streams to allow async signing of the publickey authentication process, but this library is fairly tightly coupled to the bundled `keyParser` and node's build in `crypto` library being able to produce the perquisite signatures.

Possible changes to the :

1. Allow passing of a key object for signing; if this is done key signing alg checks are skipped and deferred to the key signer; also would require supporting async `key.sign()` method
2. Allow passing of a signing callback with the current key; this callback can be used to perform signing instead of the key's `sign` method.
3. Allow passing of a function that handles the entire auth flow against the stream

**Comment by mscdex** [comment]
There are already future plans to support custom (in-process) SSH key agents, but no work has been done on that front yet. I believe this would meet your needs.

**Comment by mscdex** [comment]
This should be possible in the master branch now with the introduction of custom Agent classes.
