### ISSUE TITLE
Feedback - new ssh2 version

### ISSUE THREAD

**Issue by theophilusx** [mscdex/ssh2#994]
Just some feedback which might be useful regarding the new (master) version of ssh2. 

Today, I was able to get this version to run with my ssh2-sftp-client module with no errors and all tests passing. This is really great. thanks for all the great work. I have only tested against node v15.8.0 so far. Last time I tried, a number of tests were failing (6 - 8 weeks back). 

One small issue I had was with managing errors. The challenge was that in some situations, a single action will generate multiple errors. For example, trying to connect to a bad hostname will generate a bad address error and a connection lost before handshake error. This caused 3 key challenges for my module.

As my module wraps interaction with the sftp server in promises, as part of each promise, I add event handlers for error, close and end. If an error occurs, the Promise is rejected. If all goes well it is resolved. After the promise is fulfilled, I remove the listeners to prevent too many listeners form being added (i.e. each Promise needs its own listeners because it has to call its own reject). Problem I had with multiple error events being raised from a single 'action' is that if I rejected based on the first error event and then removed the listener, I would end up with an uncaught error,  I cannot just wait for a second error as there may not always be a second error, plus I want to return the first error as that appears to be the more specific error (and provides more meaningful feedback to the client). 

One of the challenges with a Promise based approach is that you have to have some mechanism to deal with errors which occur in-between promises. For that I have default 'global' handlers for error (and close/end). The most common error of this type is a lost of connection or some other network issue. These 'global' handlers only take action if the event has not been flagged as already handled by a more specific Promise event handler. To 'handle' the error, they raise an exception after setting the sftp channel to null to indicate there is no current connection (preventing subsequent requests from being processed). The second error was tripping this action because no Promise specific handlers were still in place. 

For now, I have added a 1 second sleep after an error has been received during establishment of a connection before removing the error listeners. This seems to work pretty well. I then return the first error object as part of the reject.  The 1 second wait is not an issue as it will only occur when there has been an error during connect, in which case, you have other problems already anyway. 

I am wondering if the connection lost before handshake error is always a 'second' error i.e. only gets raised after some other error. If this was the case, I could just set my global error handler to ignore that error, remove the need for a 1 second sleep and slightly simplify the connection logic. 

It does appear that the multiple errors only occur during connection attempts. Failures or errors when performing other actions seem to only raise a single error.

**Comment by mofux** [comment]
I absolutely share your experience. The current master runs very stable and the only problem (annoyance) remaining is the handling of multiple errors. Please also see #972 which describes the problem in more detail and points to the commit that introduced this behaviour.

**Comment by mscdex** [comment]
I believe 459ab65de7f9ad0d7214d9f0035b188f794b653a should fix this particular issue.
