### ISSUE TITLE
How to exec several commands on ssh connection consequentially?

### ISSUE THREAD

**Issue by MurzNN** [mscdex/ssh2#995]
I need to exec several commands on ssh connection consequentially - exec one, wait for finish, catch the output, exec two, wait for finish, catch the output, disconnect. But I can't find the right way to implement this. 

For example, I need to execute those chain of commands:
1. Connect to remote ssh server.
2. Exec `git status`
3. Wait for finish of executing, get the the output to variable and parse it. If all in output is ok - continue.
4. Execute `git pull`, wait for finish and get the output
5. Execute the `git add; git commit -a`

I can call the `conn.exec(HOST, 'git status')` but this function is not async, so I can't understand how to implement `await` to finish execution of this exec, and so on.

As workaround, I can initiate a new separate ssh connection for each command, but this will be very ugly way.

Can anybody suggest the right solution for this task?

**Comment by mscdex** [comment]
I believe what you're asking for is outside the scope of this project, as you can handle async tasks generally in a variety of ways.

This module uses callbacks (specifically error-first callbacks in the style of node core). In particular, `exec()` will pass a stream when there was no error starting the command. Read from the stream to get the output and to know when the process finishes.

**Comment by MurzNN** [comment]
Yeah, thanks for describing, I implement this via Promice instance, that resolves on "stream.close" event, and later even found the [ssh2-promise](https://github.com/sanketbajoria/ssh2-promise) package as helper, here is the code example:

```js
    exec(cmd:string, params?:Array<string>, options?:any): Promise<any> {
        options = options || {};
        cmd += (Array.isArray(params) ? (" " + params.join(" ")) : "");
        return this.connect().then(() => {
            return new Promise((resolve, reject) => {
                this.sshConnection.exec(cmd, options, (err:any, stream:any) => {
                    if (err)
                        return reject(err);
                    var buffer = "";
                    stream.on('close', function () {
                        resolve(buffer);
                    }).on('data', function (data:any) {
                        buffer += data;
                    }).stderr.on('data', function (data:any) {
                        reject(data);
                    });
                })
            })
        })
    }
```
