### ISSUE TITLE
How to keep environment between several exec calls in one ssh connection?

### ISSUE THREAD

**Issue by MurzNN** [mscdex/ssh2#996]
I need to sequentially execute several commands on ssh in one environment, but the problem is that it is lost on every call. Example of problem:
1. Make the persistent connection via ssh2.connect.
2. Exec the `pwd` command: outputs "/home/user"
3. Exec the `cd /tmp; pwd`: outputs "/tmp"
4. Exec the `pwd` command again: outputs "/home/user"

Same problem is with environment variables, if I set varable `TEST1="Hello"; echo $TEST1`, on second `exec` call this env variable becomes empty.

The question is how to keep the all environment things between several exec calls?

**Comment by mscdex** [comment]
You'll either need to use `shell()` with its caveats or come up with a creative solution because the SSH protocol does not provide a solution.

**Comment by MurzNN** [comment]
Thanks for idea with `shell()`, but I can't find the way for programmatically pass command to active ssh2.shell instance, is it possible?

As other creative ideas only is concatenate multiple commands by ";" and implement all output parsing login via bash scripting :(

**Comment by mscdex** [comment]
You would just write to the input side of the stream passed to your `shell()` callback followed by a newline, just as if you were typing it interactively. There are many downsides to this approach though that would require creative solutions to overcome them, including: not knowing when the command exits, not being able to separate stdout and stderr output, not knowing the exit code of the command, etc.
